### ISSUE TITLE
gg.exe error

### ISSUE THREAD

**Issue by vacon04** [jb-alvarado/media-autobuild_suite#1001]
After running make, I get the following error

├ Running make...
Likely error:
gcc.exe: error: buildfreetype2-gitbuildsunix: No such file or directory
gcc.exe: error: buildfreetype2-gitinclude: No such file or directory
gcc.exe: error: FT2_BUILD_LIBRARY: No such file or directory
gcc.exe: error: FT_CONFIG_MODULES_H=<ftmodule.h>: Invalid argument
gcc.exe: error: FT_CONFIG_OPTIONS_H=<ftoption.h>: Invalid argument
gcc.exe: error: buildfreetype2-gitbuild-64bitftsystem.: No such file or directory
gcc.exe: error: buildfreetype2-gitsrcbaseftsystem.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
make: *** [/build/freetype2-git/builds/freetype.mk:210: /build/freetype2-git/build-64bit/ftsystem.] Error 1
make failed. Check C:/Mingw/build/freetype2-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sd64.zip
Copy and paste [logs.zip](https://0x0.st/sd64.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

I'm not really sure what to do here, I appreciate your help.

**Comment by wiiaboo** [comment]
I'd assume your install is just completely broken. Delete everything related to the suite and try installing again.
