### ISSUE TITLE
/local64/bin-video/libaacs.dll Not found

### ISSUE THREAD

**Issue by carlhen** [jb-alvarado/media-autobuild_suite#1002]
Running git clone for libbdplus...
┌ libbdplus git ..................................... [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
mv: cannot stat '/local64/bin/libaacs-0.dll': No such file or directory
├ /local64/bin-video/libaacs.dll ........................... [Not found]
└ libbdplus-git ............................................... [Failed]

Try deleting '/build/libbdplus-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

**Comment by LigH-de** [comment]
Confirming, MinGW32 doesn't build a libaacs.dll either. Will investigate in the libbruray project...

**Comment by wiiaboo** [comment]
I had the same issue days ago, but since I don't care about libbluray or companions I just disabled it locally.
I'll look into it.

**Comment by wiiaboo** [comment]
Oh lol, I switched the URLs when I updated them, my bad.

**Comment by LigH-de** [comment]
So shall I forward that it's an external mistake?

**Comment by wiiaboo** [comment]
Yes.
