### ISSUE TITLE
x265 hg failing

### ISSUE THREAD

**Issue by chhaugen** [jb-alvarado/media-autobuild_suite#1004]
┌ x265 hg ........................................... [Recently updated]
├ Building 12-bit lib for multilib...
├ Running cmake...
├ Running ninja...
├ Building 10-bit lib for multilib...
├ Running cmake...
├ Running ninja...
├ Building multilib lib/bin...
├ Running cmake...
├ Running ninja...
Likely error:
C:/media-autobuild_suite/build/x265-hg/source/encoder/search.cpp:2758:50: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct x265::Search::TUInfoCache'; use assignment or value-initialization instead [-Wclass-memaccess]
         memset(&m_cacheTU, 0, sizeof(TUInfoCache));
                                                  ^
In file included from C:/media-autobuild_suite/build/x265-hg/source/encoder/search.cpp:30:
C:/media-autobuild_suite/build/x265-hg/source/encoder/search.h:388:12: note: 'struct x265::Search::TUInfoCache' declared here
     struct TUInfoCache
            ^~~~~~~~~~~
[8/65] Building CXX object encoder/CMakeFiles/encoder.dir/analysis.cpp.obj
[9/65] Building CXX object encoder/CMakeFiles/encoder.dir/slicetype.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed. Check C:/media-autobuild_suite/build/x265-hg/build-64bit/8bit/ab-suite.ninja.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/snoX.zip
Copy and paste [logs.zip](https://0x0.st/snoX.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by schmidthubert** [comment]
Wait for closing of ticket https://bitbucket.org/multicoreware/x265/issues/458/commit-56a73c8-added-invalid-c-to-x265h or stick with previous working commit:

`if [[ ! $x265 = "n" ]] && do_vcs "hg::https://bitbucket.org/multicoreware/x265#commit=1f44f1f"; then`

**Comment by carlhen** [comment]
Thank you. It now compiles past that point :smiley:

**Comment by LigH-de** [comment]
Another related error in MinGW32 with GCC 7.4.0: `error: invalid conversion from 'char' to 'char*'` due to assigning '\0' instead of NULL. Patch is already proposed.

**Comment by wiiaboo** [comment]
Nice to know they still don't do any code review or CI whatsoever.

**Comment by LigH-de** [comment]
@Selur - probably yes. The *.pc file gets removed before rebuilding, and when the building fails, the *.pc file is not copied back.

@wiiaboo - well, my impression (from the outside) is: one developer or contributor proposes a patch, (usually) another skims through and either comments or commits; but I doubt **every patch** proposal is tested on **every supported compiler** before committing. Sometimes there is a comment that a patch doesn't fit anymore, so _at least sometimes_ it is indeed tested in a building task with _at least one compiler_. So far my observations. It's not exactly "no code review at all". But yes, it appears incomplete.

**Comment by BlackScreen** [comment]
The x265 issues seem fixed now. I could build it just now... Yesterday it did not work.

**Comment by LigH-de** [comment]
The proposed patch has been commited.
