### ISSUE TITLE
Build failed in libbs2b 64bit

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#101]
Today i wanted to build a new version and it failed in ffmpeg. I deleted everything and started again and he fails now in libbs2b with configure: error: Please install libsndfile.

Libsndfile is only compiled if sox is enabled but in the script snd are build after libbs2b

[compiler list]
msys2Arch=2
arch=3
free=1
ffmbc=2
vpx=1
x264=1
x265=1
other265=2
flac=1
mediainfo=1
soxB=2
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=2
mp4box=2
mplayer=2
mpv=2
mkv=2
cores=4
deleteSource=1
strip=1
pack=1

**Comment by nille02** [comment]
That works. Thank you very much.

**Comment by wiiaboo** [comment]
It shouldn't, lol, I'm erroring out. I'll fix in a few secs, wait.

**Comment by wiiaboo** [comment]
OK, now it should definitely work.
Sorry for the mistakes.

**Comment by nille02** [comment]
i had open another issue about it ;) But again thanks for your fix.
