### ISSUE TITLE
Script asks confirmation to install packs

### ISSUE THREAD

**Issue by username30** [jb-alvarado/media-autobuild_suite#1013]
Hello,

After executing
`- write fstab mount file`
line in main script,
![cmd_2019-01-10_23-11-43](https://user-images.githubusercontent.com/24947452/50994385-35183000-152d-11e9-9f2b-089cdd5c5015.png)

it pops up this confirmation:
![mintty_2019-01-10_23-12-48](https://user-images.githubusercontent.com/24947452/50994447-5416c200-152d-11e9-87e8-245cc3fd3a69.png)

And it waits for user input. I can answer "y" here and it will go on smoothly, but I think it would be great if the script would be fully automated. May this step be automated as well?

**Comment by Kagami** [comment]
You also need to run `pacman-key --lsign AE4FF531`, see https://github.com/jb-alvarado/media-autobuild_suite/issues/946

**Comment by wiiaboo** [comment]
It only asks once or if you remove/install packages manually.
And the script isn't made to be completely automated.

**Comment by username30** [comment]
> You also need to run `pacman-key --lsign AE4FF531`, see #946

Yes, I had some key signatures issues... But after restarting script at that point the script got all required certificates by itself, so somehow it all settled.
Thank you for advice though, maybe that issue will help me next time!

**Comment by 1480c1** [comment]
I found out why, line 92 of media-suite_update.sh, `pacman -Qqe | grep -q sed && pacman -Qqg base | pacman -D --asdeps -` causes those two packages to be installed as deps, and causes them to not show up when the script does the diff between the old and new.  Both mintty and flex are considered base.

**Comment by 1480c1** [comment]
I'm going to see if its better to remove them from msyspackages or set them as explicit after line 92.
