### ISSUE TITLE
libmysofa need upgrade.

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#1015]
https://github.com/hoene/libmysofa.git#tag=v0.5
not enough for recent ffmpeg.  

Running git update for ffmpeg...
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set.
MSVC cl.exe not found in PATH or through vswhere.
Disabling libnpp/cuda-sdk.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c: In function 'preload_sofa':
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c:164:32: error: implicit declaration of function 'mysofa_neighborhood_init_withstepdefine'; did you mean 'mysofa_neighborhood_init'? [-Werror=implicit-function-declaration]
         s->sofa.neighborhood = mysofa_neighborhood_init_withstepdefine(s->sofa.hrtf,
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                mysofa_neighborhood_init
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c:164:30: warning: assignment to 'struct MYSOFA_NEIGHBORHOOD *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
         s->sofa.neighborhood = mysofa_neighborhood_init_withstepdefine(s->sofa.hrtf,
                              ^
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavfilter/af_sofalizer.o] Error 1
make failed. Check C:/Users/kuh3h/Downloads/media-autobuild_suite/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/s7Wu.zip
Copy and paste [logs.zip](https://0x0.st/s7Wu.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by wiiaboo** [comment]
Your suite is old. This was fixed in b3d57e536015298dad59445d1d0ef241beb44b96

**Comment by brucedk** [comment]
I know this thread is closed, but i have the same error here, and I've just downloaded the script form here now... can it be some problem new? I will try a fresh instalation now again just to see if it works

**Comment by wiiaboo** [comment]
Try deleting libmysofa-git inside `build` to force a recompilation.

**Comment by brucedk** [comment]
sorry the delay, deleting libmysofa-git make the script works, thanks
