### ISSUE TITLE
any chance you add libxml2 support

### ISSUE THREAD

**Issue by ori1337** [jb-alvarado/media-autobuild_suite#1018]
Hello im tired of trying compiling and failing i tried everything 

there is any chance you adding libxml2 support ? 
im really trying the whole weak to get ffmpeg with libxml2

because dash streams become more and more popular 
and im trying to find a build of ffmpeg for years 
if any of you could help me just get ffmpeg with libxml2
and you guys add support for libxml2 
i'ill be greatfull because im really too old for that 

(also not comming to beg just really tried of looking )
thanks -ori

**Comment by schmidthubert** [comment]
"Zeranoe-emulating build", [RTFM](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/README.md)?

**Comment by wiiaboo** [comment]
It's been there for months.
