### ISSUE TITLE
mkvtoolnix patch problem

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#102]
> build mplayer-svn done...
-------------------------------------------------
-
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 17 (delta 15), reused 17 (delta 15), pack-reused 0
Unpacking objects: 100% (17/17), done.
From https://github.com/mbunkus/mkvtoolnix
 * branch            master     -> FETCH_HEAD
   726f041..9be0e47  master     -> origin/master
Updating 726f041..9be0e47
Fast-forward
 ChangeLog                           |  8 ++++++++
 src/merge/mkvmerge.cpp              |  6 +++++-
 src/merge/output_control.cpp        | 11 +++++++++--
 src/mkvtoolnix-gui/jobs/mux_job.cpp |  2 +-
 src/mmg/jobs.cpp                    |  2 +-
 src/mmg/mux_dialog.cpp              |  2 +-
 6 files changed, 25 insertions(+), 6 deletions(-)
   CLEAN
  rm -rf ./rake.d/dependency.d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   635  100   635    0     0   1311      0 --:--:-- --:--:-- --:--:--  1453
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/src/info/mkvinfo.cpp     2014-07-13 14:59:54.767079300 +0200
|+++ b/src/info/mkvinfo.cpp     2014-07-13 15:00:00.677417300 +0200
--------------------------
File to patch:

**Comment by wiiaboo** [comment]
Update your scripts. It's been fixed a few moments ago.
