### ISSUE TITLE
Rebuild without update

### ISSUE THREAD

**Issue by umpol** [jb-alvarado/media-autobuild_suite#1020]
Is it possible to build ffmpeg with the same files of "ffmpeg-git" ? I changed some line in /libavformat/http.c to comment out a warning (http reues) but everytime I builded script seem to sync to git source and replaced my edited file. I try to change file to "readonly" but script still overwrite the file.

**Comment by wiiaboo** [comment]
That's not how to do it.
Either save your changes as a patch and then apply them with ffmpeg_extra.sh, or run the compilation commands manually.

**Comment by wiiaboo** [comment]
See https://github.com/jb-alvarado/media-autobuild_suite/issues/775
