### ISSUE TITLE
shaderc compiling error

### ISSUE THREAD

**Issue by masterkivat** [jb-alvarado/media-autobuild_suite#1032]
┌ shaderc git ....................................... [Recently updated]
├ Running glslang-clone...
├ Running spirv-tools-clone...
├ Running spirv-headers-clone...
├ Running cmake...
Likely error:
-- SPIRV-Tools: nosetests was not found - python support code will not be tested
-- Found PythonInterp: E:/media-autobuild_suite/msys64/usr/bin/python.exe (found version "3.7.2")
-- Google Mock was not found - tests based on that will not build
-- optimizer enabled
CMake Error at third_party/CMakeLists.txt:91 (message):
  SPIRV-Cross was not found - required for compilation

-- Configuring incomplete, errors occurred!
See also "E:/media-autobuild_suite/build/shaderc-git/build-64bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check E:/media-autobuild_suite/build/shaderc-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
[sh1T.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2767031/sh1T.zip)

**Comment by 1480c1** [comment]
#1031
