### ISSUE TITLE
shaderc-git build failed. need  SPIRV-Cross clone?

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#1033]
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
cmake .. -G Ninja -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX=/local64 -DUNIX=on -DCMAKE_BUILD_TYPE=Release -GNinja -DSHADERC_SKIP_TESTS=ON
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/c++.exe
-- Check for working CXX compiler: C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shaderc: build type is "Release".
-- Configuring Shaderc to avoid building tests.
-- nosetests was not found - python code will not be tested
-- asciidoctor was not found - no documentation will be generated
-- SPIRV-Tools: nosetests was not found - python support code will not be tested
-- Found PythonInterp: C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/python.exe (found version "2.7.15") 
-- Google Mock was not found - tests based on that will not build
-- optimizer enabled
CMake Error at third_party/CMakeLists.txt:89 (message):
  SPIRV-Cross was not found - required for compilation

-- Configuring incomplete, errors occurred!
See also "C:/Users/kuh3h/Downloads/media-autobuild_suite/build/shaderc-git/build-64bit/CMakeFiles/CMakeOutput.log".

**Comment by 1480c1** [comment]
#1031
