### ISSUE TITLE
Installing python2-lxml failed  & Installing python2-six failed

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1043]
┌ fontconfig git .................................... [Recently updated]
Installing python2-lxml... failed
Installing python2-six... failed
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
make[2]: Leaving directory '/build/fontconfig-git/build-32bit/fontconfig'
Making all in fc-blanks
make[2]: Entering directory '/build/fontconfig-git/build-32bit/fc-blanks'
  GEN      fcblanks.h
/bin/sh: /mingw32/bin/python2: No such file or directory
make[2]: *** [Makefile:596: fcblanks.h] Error 1
make[2]: Leaving directory '/build/fontconfig-git/build-32bit/fc-blanks'
make[1]: *** [Makefile:579: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-32bit'
make: *** [Makefile:463: all] Error 2
make failed. Check C:/mingw/build/fontconfig-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sFPE.zip
Copy and paste [logs.zip](https://0x0.st/sFPE.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Try clink on the mintty at the base folder and then in the console that pops up, type, `pacman -Ss mingw32/mingw-w64-i686-python2`

**Comment by 1480c1** [comment]
rerun after

**Comment by schmidthubert** [comment]
This could be closed now as well, I didn't see this because no fontconfig in the subject. Sorry!
