### ISSUE TITLE
feature requirest: option to build xavs2 even when not included into ffmpeg

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#1044]
Would be nice if the xavs2 binaries could be build even when they are not added to ffmpeg.
(For ffmpeg I usually use the compatibility to zeronoe since I need a version can distribute, but I'd like to use the xavs2 binaries for encoding.)

**Comment by schmidthubert** [comment]
you can try the patch, just add avs2=1 to the ini.
