### ISSUE TITLE
You must have python installed to compile Fontconfig

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1050]
Running git update for fontconfig...
┌ fontconfig git .................................... [Recently updated]
Installing python2-lxml... done
Installing python2-six... done
├ Running autogen...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./autogen.sh --noconf

You must have python installed to compile Fontconfig.
Install the appropriate package for your distribution.
or get the source tarball at https://www.python.org/downloads/source/
autogen failed. Check C:/mingw/build/fontconfig-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sFDo.zip
Copy and paste [logs.zip](https://0x0.st/sFDo.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/issues/1043
