### ISSUE TITLE
[question] Build older version

### ISSUE THREAD

**Issue by BazookaJoe1900** [jb-alvarado/media-autobuild_suite#1056]
How do I use the tool and build older version of ffmpeg? with differnet options

**Comment by wiiaboo** [comment]
See https://github.com/jb-alvarado/media-autobuild_suite/issues/775

**Comment by BazookaJoe1900** [comment]
@wiiaboo  Thanks for the ansower.
but it didn't work. I added a
'git checkout n4.1' to ffmpef_extra.sh
it checked it the latest stable 4.1 out, but there was later compilation error.
do you consider such scenario as bug?

> 
> Note: checking out 'n4.1'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 10506de9ad cbs_av1: Support redundant frame headers
> ├ Compiling shared FFmpeg...
> ├ Running configure...
> Likely error:
> CFLAGS: -mthreads -mtune=generic -O2 -pipe
> LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
> ../configure --disable-static --enable-shared --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --extra-libs=-liconv --enable-version3 --prefix=/local64/bin-video/ffmpegSHARED
> Unknown option "--enable-libdav1d".
> See ../configure --help for available options.
> configure failed. Check C:/GitRepos/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.configure.log
> This is required for other packages, so this script will exit.
>   Creating diagnostics file...
> 
> All relevant logs have been anonymously uploaded to https://0x0.st/sCOR.zip
> Copy and paste [logs.zip](https://0x0.st/sCOR.zip) in the GitHub issue.
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by wiiaboo** [comment]
No, it's not a bug, it's an older release, thus why it's up to you to figure it out, not the suite.
In your case, you're trying to use an external library that didn't exist yet in FFmpeg.

**Comment by BazookaJoe1900** [comment]
its older, but not much. its the latest stable.
I will try to figure it.
thanks anyway

**Comment by wiiaboo** [comment]
libdav1d was released and added to FFmpeg supported external libraries after 4.1 was released. Nothing to do with age.
The suite is meant to build the latest releases or git/svn HEADs, not to handle everything single tag or branch that all the 50 packages being built by the suite have between them.
