### ISSUE TITLE
suite insists in recreating an existing .minttyrc (TERM vs. Term)

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#1057]
media-autobuild_suite.bat line 1337 ff.:

```
    if not exist "%instdir%\%msys2%\home\%USERNAME%" mkdir "%instdir%\%msys2%\home\%USERNAME%"
    for /F "tokens=2 delims==" %%b in ('findstr TERM %instdir%\%msys2%\home\%USERNAME%\.minttyrc') do set TERM=%%b
    if not defined TERM (
        %instdir%\%msys2%\usr\bin\bash.exe -lc "printf '%%s\n' Locale=en_US Charset=UTF-8 Font=Consolas Columns=120 Rows=30 TERM=xterm-256color>/home/%USERNAME%/.minttyrc"
    )
```

Because my already existing .minttyrc contained only `Term` (CamelCase) instead of `TERM` (UPPERCASE), it got substituted by a default content.

If you customize the mintty window and save the new content, it will possibly store the terminal mode with CamelCase `Term` identifier.

**Comment by wiiaboo** [comment]
Yeah, it's missing `/I`.

**Comment by BlackScreen** [comment]
Probably a little unrelated but not by so much...
I get the following error since a few changes ago:
`FINDSTR: Bauer\.minttyrc kann nicht geöffnet werden.`

My username has a space - "Jack Bauer" (yes, I know).
Probably add " after the FINDSTR?

**Comment by wiiaboo** [comment]
Yeah, even if spaces are not recommended, we should still consider them where we can.
@1480c1 ping

**Comment by 1480c1** [comment]
Hmm, I'll try to fix it so that It will work even the path has spaces.

**Comment by BlackScreen** [comment]
Hm. Not quite fixing the issue... Minor issue, so... I will just ignore it. Just FYI.
`FINDSTR: E:\AB-Suite\msys64\home\Jack Bauer\.minttyrc kann nicht geöffnet werden.`

**Comment by wiiaboo** [comment]
Probably because the file might not exist.

**Comment by BlackScreen** [comment]
Ok. But shouldn't the suite or the building environment create this?

**Comment by BlackScreen** [comment]
".minttyrc" is not in the folder.

And you mean this lines ("media-autobuild_suite.bat" - line 1336 ff.)?

```
    if not exist "%instdir%\%msys2%\home\%USERNAME%" mkdir "%instdir%\%msys2%\home\%USERNAME%"
    for /F "tokens=2 delims==" %%b in ('findstr /i TERM "%instdir%\%msys2%\home\%USERNAME%\.minttyrc"') do set TERM=%%b
    if not defined TERM (
        %instdir%\%msys2%\usr\bin\bash.exe -lc "printf '%%s\n' Locale=en_US Charset=UTF-8 Font=Consolas Columns=120 Rows=30 TERM=xterm-256color>/home/%USERNAME%/.minttyrc"
    )
```

**Comment by LigH-de** [comment]
If the file ".minttyrc" does not yet exist in E:\AB-Suite\msys64\home\Jack Bauer\, it should be created with some default content; I guess the target file name of this file creation needs double quotes too. But that starts getting complicated with nesting quotes... 

A quick workaround may be to create a new Windows user account with a short name without spaces, just to run MABS in it. Then you may copy the file from there and remove the account. Or keep it for other "what if" issues...

And 1480c1 means, when ".minttyrc" exists, then it should contain a line that starts with "TERM=...". But as long as it doesn't exist, you can't find text in this non-existent file.
