### ISSUE TITLE
the newest 32bit build

### ISSUE THREAD

**Issue by ksfalcon** [jb-alvarado/media-autobuild_suite#106]
First all, sorry my bad English, I will try to describe my problem.

I am select the build target system as 'both', I found if the script update the source in the building 64-bit tools, then I will get the old 32bit build and the newest 64bit build. If I need the newest 32bit build, then I will must to delete the source and run the script again. 

I think we only need to download the source once, if we need newest 32bit build, then we do not need delete the source, just run the script again.

**Comment by wiiaboo** [comment]
I don't understand what's the problem.

Answer this:
What happens?
What is the expected behavior?

And paste the contents of your .ini file.

**Comment by ksfalcon** [comment]
the ffmpeg-git may be continuously updated several times per hour. If the script update the source again in the second compiling 64-bit tools, that will also cause this issue.

The following is my solution, but I do not know will it works?

while [[ $run32bitagain = "yes" ]]
do
    run32bitagain=""
    run_builds
done

**Comment by wiiaboo** [comment]
That will only at most run the compilation twice. There's no loop and I don't think it's intended behavior to have a possibly unending loop because FFmpeg is always geting updated.

**Comment by ksfalcon** [comment]
I have a idea, I think we do not need to update the source again in the compiling 64-bit tools, if I need to update the tools to newest version, then I just need to run the script again and again...... until there are no updates.

**Comment by wiiaboo** [comment]
You really shouldn't need to keep doing that. Most of FFmpeg's updates aren't that important.

**Comment by ksfalcon** [comment]
I do not care most of FFmpeg's updates.
But I do not want to miss the 32-bit tools's important updates due to this issue.
I hope If I find bug, I hope I just run the script again to get fixed at this time and I do not need prior delete the source.

**Comment by wiiaboo** [comment]
If there are updates it will get compiled again. If there are no updates you can just create a file called `recently_updated` inside ffmpeg-git and make sure `build_successful32bit` doesn't exist and it will compile again. Or just delete `/local32/bin-video/ffmpeg.exe` and it will force build too.

**Comment by ksfalcon** [comment]
If I make the the following as comment, can I run the script again to recompile the 32-bit tools?
```
if [[ $run32bitagain = "yes" ]]; then
run_builds
    run_builds
fi

#find $LOCALBUILDDIR -maxdepth 2 -name recently_updated -delete
find $LOCALBUILDDIR -maxdepth 2 -name build_successful* -delete

if [[ $deleteSource = "y" ]]; then
```

**Comment by wiiaboo** [comment]
It already runs again if there are updates. Why do you want to run it thrice?

**Comment by ksfalcon** [comment]
If I found x265 32-bit build exist a bug but the 64-bit build not exist this bug, then I just run the script again to rebuild it.

If I make the the following as comment, can I run the script again to recompile the 32-bit tools?
```
run_builds

#if [[ $run32bitagain = "yes" ]]; then
#    run_builds
#fi

#find $LOCALBUILDDIR -maxdepth 2 -name recently_updated -delete
find $LOCALBUILDDIR -maxdepth 2 -name build_successful* -delete

if [[ $deleteSource = "y" ]]; then
```

**Comment by wiiaboo** [comment]
Or just delete x265.pc in /local32/lib/pkgconfig
It's very rare that some commit gets in while you're compiling so you don't need those modifications.

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/b3c9c52cf47709f6a22aa6a148fa0acf0314f546
Now it will always ask for recompilation if there are updates while compiling.
