### ISSUE TITLE
Disabling 32bit keeping just 64bit compilation

### ISSUE THREAD

**Issue by Murmur** [jb-alvarado/media-autobuild_suite#1063]
I have been running a compilation `media-autobuild_suite.bat` some time on Win10-64bit box. First I wanted to have 32bit and 64bit targets enabled so that is what happening at the moment.

Nowdays I really care about the 64bit binaries only so is there an easy way to disable 32bit target? I wish to keep it in the system and compile in case needed case-by-case?
- - - 
**(edit)** UUh I think it's a simple `build/media-autobuild_suite.ini | arch=`  option 1=both, 2=32bit, 3=64bit. When I get back home give it a try.

**Comment by wiiaboo** [comment]
Yeah, it's just that.
