### ISSUE TITLE
libquvi

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#107]
Could you please add libquvi to media-autobuild_suite?
Libquvi add direct support for reading files off various Internet streaming platforms directly (ex. can read youtube videos directly).
best regards,
laur

**Comment by wiiaboo** [comment]
No, there's youtube-dl for that purpose.
Libquvi is old, unmaintained and buggy.
At most, I'd only add it if mplayer is being compiled, since it's also old and mostly dead.
