### ISSUE TITLE
ffmpeg fails on 'libaom.a undefined reference to warn'

### ISSUE THREAD

**Issue by Murmur** [jb-alvarado/media-autobuild_suite#1078]
ffmpeg compilation stopped working few weeks ago on my system. I have been running `./update_suite.sh` and then `media-autobuild_suite.bat`, removed ffmpeg and libaom build folders. No luck.  I did edit `build/media-autobuild_suite.ini/arch=3` to have just 64bit compilation. Restoring back to 32bit+64bit compilation option does not fix anything.

[logs.zip, run on Win10](https://0x0.st/zsfl.zip)

```
/projects/media-autobuild_suite/media-autobuild_suite/local64/lib/libaom.a(av1_cx_iface.c.o):av1_cx_iface.c:(.text+0x1108): undefined reference to `warn'
/projects/media-autobuild_suite/media-autobuild_suite/local64/lib/libaom.a(av1_cx_iface.c.o):av1_cx_iface.c:(.text+0x1108): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `warn'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/ffbuild/library.mak:103: libavcodec/avcodec-58.dll] Error 1
make failed. Check /projects/media-autobuild_suite/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```

Anyone experience the same problems and understand more logs.zip errors?

**Comment by kuh3h3** [comment]
Maybe your aom is  old.
fixed already  in recent git aom.

try rerun MABS after remove media-autobuild_suite\build\aom-git folder.

=======

Remove a use of 'warn'.

'warn' isn't defined when tools are turned off.

And this warning wasn't that important.

BUG=aomedia:2310

Change-Id: If402549ea9a290088294c5d0199024ab042f4e24
diff --git a/av1/av1_cx_iface.c b/av1/av1_cx_iface.c
index 199ef0a..285e6a5 100644
--- a/av1/av1_cx_iface.c
+++ b/av1/av1_cx_iface.c
@@ -25,7 +25,6 @@
 #include "av1/encoder/bitstream.h"
 #include "av1/encoder/encoder.h"
 #include "av1/encoder/firstpass.h"
-#include "common/tools_common.h"
 
 #define MAG_SIZE (4)
 #define MAX_NUM_ENHANCEMENT_LAYERS 3
@@ -727,9 +726,6 @@
   oxcf->max_reference_frames = extra_cfg->max_reference_frames;
   if (oxcf->max_reference_frames > 3 && oxcf->max_reference_frames < 7) {
     // TODO(urvang): Enable all possible values, after they work properly.
-    warn(
-        "max_reference_frames values between 3 and 7 are not supported yet. "
-        "Using value 3 instead.");
     oxcf->max_reference_frames = 3;
   }
   oxcf->enable_masked_comp = extra_cfg->enable_masked_comp;

**Comment by kuh3h3** [comment]
also remove media-autobuild_suite\local64\include\aom and media-autobuild_suite\local64\lib\libaom.a

**Comment by Murmur** [comment]
Thanks, that did the trick (removed build/aom-git, local64/include/aom, local64/bin/libaom.a). For some reason my `MABS media-autobuild_suite.bat` script did not update aom git sources or compiled new library file.
