### ISSUE TITLE
new_updates-loop on ffmpeg update during compilation

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#109]
whenever there is a ffmpeg update during a script run, one always ends up inside a loop since 'new_update' seems to be never set back to 'false/No'
-> it should be set to something else in case that there is no new update,...

**Comment by wiiaboo** [comment]
What do you mean it doesn't get set back to "no"?
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-suite_compile.sh#L2121-L2123

I've only ever got this loop once since putting it in the script (I only compile to 64-bit).

**Comment by wiiaboo** [comment]
I thought I'd committed this before.
