### ISSUE TITLE
cuda_check.h compile error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#1096]
In file included from D:/ffmpeg-autobuild/build/ffmpeg-git/libavfilter/vf_scale_cuda.c:31:
D:/ffmpeg-autobuild/build/ffmpeg-git/libavutil/cuda_check.h: In function 'ff_cuda_check':
D:/ffmpeg-autobuild/build/ffmpeg-git/libavutil/cuda_check.h:38:7: error: 'tcuGetErrorName' undeclared (first use in this function); did you mean 'cuGetErrorName'?
     ((tcuGetErrorName *)cuGetErrorName_fn)(err, &err_name);
       ^~~~~~~~~~~~~~~
       cuGetErrorName
D:/ffmpeg-autobuild/build/ffmpeg-git/libavutil/cuda_check.h:38:7: note: each undeclared identifier is reported only once for each function it appears in
D:/ffmpeg-autobuild/build/ffmpeg-git/libavutil/cuda_check.h:38:24: error: expected expression before ')' token
     ((tcuGetErrorName *)cuGetErrorName_fn)(err, &err_name);
                        ^
D:/ffmpeg-autobuild/build/ffmpeg-git/libavutil/cuda_check.h:39:7: error: 'tcuGetErrorString' undeclared (first use in this function); did you mean 'cuGetErrorString'?
     ((tcuGetErrorString *)cuGetErrorString_fn)(err, &err_string);
       ^~~~~~~~~~~~~~~~~
       cuGetErrorString
D:/ffmpeg-autobuild/build/ffmpeg-git/libavutil/cuda_check.h:39:26: error: expected expression before ')' token
     ((tcuGetErrorString *)cuGetErrorString_fn)(err, &err_string);
                          ^
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavfilter/vf_scale_cuda.o] Error 1 
https://0x0.st/zici.zip

**Comment by wiiaboo** [comment]
That's likely an upstream issue. Report to ffmpeg.

**Comment by kliffgomel** [comment]
I do not have an account on their trac server, can you help me?

**Comment by 1480c1** [comment]
[Basic information](http://trac.ffmpeg.org/)
[Create Account](http://trac.ffmpeg.org/register)
[Info to read when creating a report](https://git.videolan.org/?p=ffmpeg.git;a=blob_plain;f=doc/issue_tracker.txt;hb=HEAD)
[Creating a bug report](https://ffmpeg.org/bugreports.html)

**Comment by kliffgomel** [comment]
I have registered, but my account has not yet been verified, I can not report an error.

**Comment by schmidthubert** [comment]
https://trac.ffmpeg.org/ticket/7742
