### ISSUE TITLE
Makefile:53: *** multiple target patterns.  Stop.

### ISSUE THREAD

**Issue by popek069** [jb-alvarado/media-autobuild_suite#1097]
07:44:26 ├ Running clean...

Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
make clean
Makefile:53: *** multiple target patterns.  Stop.
Makefile:53: *** multiple target patterns.  Stop.
clean failed. Check E:/media-autobuild_suite-master/build/mujs-git/ab-suite.clean.log
This is required for other packages, so this script will exit.

All relevant logs have been anonymously uploaded to https://0x0.st/zibI.zip
Copy and paste [logs.zip](https://0x0.st/zibI.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

solution from #752 didn't work.

**Comment by wiiaboo** [comment]
Complain to mujs.

**Comment by wiiaboo** [comment]
Can't reproduce.
