### ISSUE TITLE
32: error: implicit declaration of function 'mysofa_neighborhood_init_withstepdefine'; did you mean 'mysofa_neighborhood_init'? 

### ISSUE THREAD

**Issue by oatrx** [jb-alvarado/media-autobuild_suite#1099]
I:/ffmpeg_build/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c: In function 'preload_sofa':
I:/ffmpeg_build/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c:164:32: error: implicit declaration of function 'mysofa_neighborhood_init_withstepdefine'; did you mean 'mysofa_neighborhood_init'? [-Werror=implicit-function-declaration]
         s->sofa.neighborhood = mysofa_neighborhood_init_withstepdefine(s->sofa.hrtf,
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                mysofa_neighborhood_init
I:/ffmpeg_build/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c:164:30: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         s->sofa.neighborhood = mysofa_neighborhood_init_withstepdefine(s->sofa.hrtf,
                              ^
CC	libavfilter/af_stereowiden.o
cc1.exe: some warnings being treated as errors
CC	libavfilter/af_superequalizer.o
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavfilter/af_sofalizer.o] Error 1
make: *** Waiting for unfinished jobs....
CC	libavfilter/af_sofalizer.o
I:/ffmpeg_build/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c: In function 'preload_sofa':
I:/ffmpeg_build/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c:164:32: error: implicit declaration of function 'mysofa_neighborhood_init_withstepdefine'; did you mean 'mysofa_neighborhood_init'? [-Werror=implicit-function-declaration]
         s->sofa.neighborhood = mysofa_neighborhood_init_withstepdefine(s->sofa.hrtf,
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                mysofa_neighborhood_init
I:/ffmpeg_build/media-autobuild_suite/build/ffmpeg-git/libavfilter/af_sofalizer.c:164:30: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         s->sofa.neighborhood = mysofa_neighborhood_init_withstepdefine(s->sofa.hrtf,
                              ^
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavfilter/af_sofalizer.o] Error 1

**Comment by wiiaboo** [comment]
Report to https://github.com/hoene/libmysofa/issues

**Comment by wiiaboo** [comment]
Can't reproduce this issue.
