### ISSUE TITLE
x265 build failed

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#110]
With the latest head (9f3b90f) the build from x265 still fails 

Building CXX object CMakeFiles/cli.dir/x265.cpp.obj
Linking CXX executable x265.exe
g++.exe: error: x265_main12: No such file or directory
CMakeFiles/cli.dir/build.make:327: die Regel für Ziel „x265.exe“ scheiterte
make[2]: *** [x265.exe] Fehler 1
CMakeFiles/Makefile2:91: die Regel für Ziel „CMakeFiles/cli.dir/all“ scheiterte
make[1]: *** [CMakeFiles/cli.dir/all] Fehler 2
Makefile:116: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
[ 22%] Built target encoder
[ 86%] Built target common
[ 86%] Built target x265-static
Linking CXX executable x265.exe
g++.exe: error: x265_main12: No such file or directory
CMakeFiles/cli.dir/build.make:327: die Regel für Ziel „x265.exe“ scheiterte
make[2]: *** [x265.exe] Fehler 1
CMakeFiles/Makefile2:91: die Regel für Ziel „CMakeFiles/cli.dir/all“ scheiterte
make[1]: *** [CMakeFiles/cli.dir/all] Fehler 2
Makefile:116: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
sed: kann /local64/lib/pkgconfig/x265.pc nicht lesen: No such file or directory
-------------------------------------------------
Build of x265-hg failed...
Delete the source folder under '/build' and start again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

[compiler list]
msys2Arch=2
arch=3
free=1
ffmbc=2
vpx=1
x264=1
x265=1
other265=2
flac=1
mediainfo=1
soxB=2
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=2
mp4box=2
mplayer=2
mpv=2
mkv=2
cores=3
deleteSource=1
strip=1
pack=1

**Comment by wiiaboo** [comment]
I didn't check if the binary compiled, going to x265-devel solved it. Checking now.

**Comment by nille02** [comment]
Thank you, now it compiles fine
