### ISSUE TITLE
32 bit bin don't work

### ISSUE THREAD

**Issue by kenichi512** [jb-alvarado/media-autobuild_suite#1104]
When run the script in the first time, I wanted to have the bins in 32 and 64 bits at the same time, but only the 64 bits seems to work correctly. The 32-bit bin says that libopenh264.dll was not found. In the compilation process I did not see any error, but I'm not sure.

**Comment by 1480c1** [comment]
Did it not produce a zip file somewhere in build? Something like logs.zip or a link during the compilation like 0x0.st/***.zip?

If not, could you upload the compile.striped.log or compile.log to pastebin or somewhere to start with and post it here?

**Comment by 1480c1** [comment]
Also, at what point did the compilation say that openh264.dll was not found? During openh264 compilation, ffmpeg, or some other place?

**Comment by Selur** [comment]
@1480c1 : how I understand it he isn't complaining about a compilation problem, but about a dependency problem of a 32bit binary (probably ffmpeg)
@kenichi512 : ffmpeg will depend on libopenh264 depending on the extensions you compile in. (for both 32bit and 64bit) libopenh264.dll should also be in the local32/bin-video folder, if you copy ffmpeg out of it you have to move the libopenh264.dll with it.

**Comment by 1480c1** [comment]
> @1480c1 : how I understand it he isn't complaining about a compilation problem, but about a dependency problem of a 32bit binary (probably ffmpeg)
> @kenichi512 : ffmpeg will depend on libopenh264 depending on the extensions you compile in. (for both 32bit and 64bit) libopenh264.dll should also be in the local32/bin-video folder, if you copy ffmpeg out of it you have to move the libopenh264.dll with it.

Yea, I understand that part, I'm wondering if failed to find it on ffmpeg and if ffmpeg gave an error of where it tried to find libopenh264 and start from there since he hasn't provided any other output.
