### ISSUE TITLE
32+64 bit (arch=1): x265 HBD libs in 64 bit with noasm too

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#111]
When both architectures are compiled after each other (INI flag: `arch=1`), not only the HIGH_BIT_DEPTH libraries for x265 in 32 bit code will be compiled with the flag `ASSEMBLY=OFF`, but the 64 bit code variants too. You can check this by comparing

 * `x265 -V`
 * `x265 -D 10 -V`
 * `x265 -D 12 -V`

There is a condition in the script media-suite_compile.sh, near line 1708:

        if [[ $bits = "32bit" ]]; then
            xpsupport="-DWINXP_SUPPORT=ON"
            assembly="-DENABLE_ASSEMBLY=OFF"
        fi

This will set appropriate cmake flags for the 32 bit pass. But when the 64 bit pass follows, I believe the variables are not reset and persist. So instead, to be safe, I would suggest to even add an alternative condition with the opposite values:

        if [[ $bits = "32bit" ]]; then
            xpsupport="-DWINXP_SUPPORT=ON"
            assembly="-DENABLE_ASSEMBLY=OFF"
        else
            xpsupport="-DWINXP_SUPPORT=OFF"
            assembly="-DENABLE_ASSEMBLY=ON"
        fi

**Comment by jb-alvarado** [comment]
Thank you for the suggestion! It is fixed now.
