### ISSUE TITLE
jq: Python dependencies fail in configure

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#1110]
Does it suddenly require a newer Python version?

jq-git/build-32bit/ab-suite.configure.log
```
checking for Python dependencies... configure: error: 
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2908035/logs.zip)

**Comment by 1480c1** [comment]
I too have the same problem, but I chalked it up to something wrong with python or local. I guess not.

**Comment by 1480c1** [comment]
Mine is with 64-bit

**Comment by Qriist** [comment]
Yep, I'm piping in that I had the issue, too.

**Comment by LigH-de** [comment]
Has already been reported upstream: https://github.com/stedolan/jq/issues/1852

Patience. Workaround to build the rest: `jq=2` in **build/media-autobuild_suite.ini** until it's fixed up there.

**Comment by Qriist** [comment]
Thanks will try that shortly.
