### ISSUE TITLE
ffmpeg build wont find tesseract

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#1128]
Guys, I was building from zero and reciving this error on the ffmpeg build:

`ERROR: tesseract not found using pkg-config`

Here are the logs
https://0x0.st/zo6t.zip

**Comment by 1480c1** [comment]
You did try deleting tesseract-git and leptonica-git from build folder right?

**Comment by schmidthubert** [comment]
Just wait for Ricardo to merge [this](url) or meanwhile download the updated script from [here](https://github.com/schmidthubert/media-autobuild_suite/tree/tesseract-ffmpeg)

**Comment by 1480c1** [comment]
> Just wait for Ricardo to merge [this](url) or meanwhile download the updated script from [here](https://github.com/schmidthubert/media-autobuild_suite/tree/tesseract-ffmpeg)

Ahh, nice.
