### ISSUE TITLE
Audio tools (aften)

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#113]
What happend to:
1. aften
2. lame
3. speexenc
4. fdkaacenc
5. oggenc
?

I don't need them that often, but media-autobuild_suite was able to build them and it doesn't do so any more on my system using the following .ini:
>[compiler list]
msys2Arch=2
arch=1
free=2
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
mplayer=1
mpv=2
mkv=1
cores=8
deleteSource=1
strip=1
pack=2

**Comment by wiiaboo** [comment]
I assumed no one needed those tools. A few have been taken since https://github.com/jb-alvarado/media-autobuild_suite/compare/0332971742d28c7fa58cffc418143cb93e1a5c5f...f2877b19defce205c9b1ffa69126eb2272f2b0da and previous commits.

Most rarely get updates so there's no reason to want to build them yourself.
Aften = we don't compile a52, since it's useless, FFmpeg has a native AC3.
Lame = we don't compile lame, it gets installed by mingw. Rarely gets updates.
Speex = broken compilation of binaries since 1.2rc2, fixing now to reenable.
Oggenc = we don't compile it, just libvorbis. It needs additional compilation of `vorbis-tools`
fdkaacenc fdkaac needs free=1, fdkaacenc needs it too.

**Comment by Selur** [comment]
> fdkaacenc fdkaac needs free=1, fdkaacenc needs it too.
Why ? They both should be free unless you link them into ffmpeg or other stuff which has an incompatible license.
> Aften = we don't compile a52, since it's useless, FFmpeg has a native AC3.
Why is aften usless as a standalone ac3 encoder?

> Lame = we don't compile lame, it gets installed by mingw. Rarely gets updates.
 okay, found it inside the msys64\mingw..\bin folder

> Speex = broken compilation of binaries since 1.2rc2, fixing now to reenable.
nice :)

> Oggenc = we don't compile it, just libvorbis. It needs additional compilation of vorbis-tools
oggenc2 was available some time back

**Comment by wiiaboo** [comment]
>[fdk being compiled always]
Makes sense.
>Why is aften usless as a standalone ac3 encoder?

Last (stable) update was in 2007, you can simply get the binary from somewhere, probably.
>lame in mingw

be careful using it outside of that dir, since it's built shared, there's tons of places with that binary compiled statically.
>oggenc

they separated the binaries from libvorbis a while back, so we would have to add vorbis-tools.

**Comment by Selur** [comment]
> Last (stable) update was in 2007,

and it still has some features ffmpeg doesn't

> you can simply get the binary from somewhere, probably.

That can be said for a bunch of the other binaries too,...
mpv is offered by http://mpv.srsfckn.biz/
ffmpeg if offered by zeranoe
x264&x265 is offered by VLC
.....

I thought one of the main points about media-autobuild_suite was to get some independence to the update schedules of other folks building stuff,....

> be careful using it outside of that dir, since it's built shared, there's tons of places with that binary compiled statically.

okay, that makes it useless to me.

> so we would have to add vorbis-tools.

unless it's hard to do, I think it's a good idea to do so

**Comment by wiiaboo** [comment]
aften: I have no idea how to compile it and I can't find anyone that still compiles it with MingW. Unless @jb-alvarado knows how or you yourself tell me how to, I don't have time to waste with it.
vorbis-tools: added if --enable-libvorbis
fdkaac: compiled if --enable-libfdk-aac, even with free=2.
lame: compiled if --enable-libmp3lame

**Comment by Selur** [comment]
> aften: I have no idea how to compile it and I can't find anyone that still compiles it with MingW

okay

> vorbis-tools: added if --enable-libvorbis
fdkaac: compiled if --enable-libfdk-aac, even with free=2.
lame: compiled if --enable-libmp3lame

I hope these are not the ffmpeg flags, because the point was to have static oggenc2, fdkaacenc and lame binaries,.... 
also unless non-free is selected fdkaac should not be included into ffmpeg

**Comment by wiiaboo** [comment]
`--enable-libfdk-aac` gets removed from ffmpeg configure if `free=2` is in the ini, or it would break compilation, but fdkaac and fdkaacenc get compiled.

The others of course also depend on the flags. Including them in ffmpeg is OK (gpl-compatible) and you need the libs to compile the binaries.

**Comment by Selur** [comment]
Do I get this right, I should add '--enable-libfdk-aac' to the ffmpeg_options.txt and as long as free=2 is set my ffmpeg version will not include libfdk, but the binaries will be build?
(I really hope I misunderstand this, because this sound like the source of so much trouble in the long run.)

**Comment by wiiaboo** [comment]
That is correct and that is why by default --enable-libfdk-aac is in the options. The .ini file ALWAYS overrides whatever options follow, especially non-free options, even if you include --enable-nonfree in the options.

**Comment by wiiaboo** [comment]
Looking at git history, I'm pretty sure this never compiled aften. We did compile a52dec, but not a52enc/aften.

Also, spending some time googling I can't find any use for aften other than eac3to's and it comes with aften bundled.
If ffmpeg's native ac3 encoder isn't complete, it's likely that you can simply ask for it in their bug tracker, it's [active enough](http://git.videolan.org/?p=ffmpeg.git&a=search&h=HEAD&st=commit&s=^%28%28avcodec%2F%29|%29ac3&sr=1).
