### ISSUE TITLE
https://git.ffmpeg.org/ffmpeg.git is too slow.

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#1132]
Cloning into 'ffmpeg-git'...
remote: Counting objects: 563013, done.
remote: Compressing objects: 100% (118466/118466), done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

tried with big buffer.  17.00 KiB/s ?
it is too slow.

$ git config http.postBuffer 524288000
$ git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg-git
Cloning into 'ffmpeg-git'...
remote: Counting objects: 563013, done.
remote: Compressing objects: 100% (118466/118466), done.
Receiving objects:  23% (133331/563013), 37.25 MiB | 17.00 KiB/s

so i tried mirror site  https://github.com/FFmpeg/FFmpeg.

git clone https://github.com/FFmpeg/FFmpeg ffmpeg-git
Cloning into 'ffmpeg-git'...
remote: Enumerating objects: 563013, done.
remote: Total 563013 (delta 0), reused 0 (delta 0), pack-reused 563013
Receiving objects: 100% (563013/563013), 217.94 MiB | 7.36 MiB/s, done.
Resolving deltas: 100% (439533/439533), done.
Checking out files: 100% (7006/7006), done

7.36 MiB/s
great speed!!!

Please use https://github.com/FFmpeg/FFmpeg

**Comment by wiiaboo** [comment]
How is this a suite issue?
