### ISSUE TITLE
rav1e: Could not compile `proc-macro2` + `libc`

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#1133]
Reported to https://github.com/xiph/rav1e/issues/1094

I vaguely remember another project already had an issue with MSYS2 possibly not providing libc, or similar...

**Comment by schmidthubert** [comment]
Did you remove your opt/cargo folder and let rust rebuild?

**Comment by LigH-de** [comment]
Sounds like a strategy. :thinking: Is that to be expected regularly? :roll_eyes:

**Comment by schmidthubert** [comment]
Is this a yes or no?

**Comment by LigH-de** [comment]
I just even removed cargo, now the suite re-installed rust and continues ... will report when it reached rav1e.

**Comment by schmidthubert** [comment]
:+1:
