### ISSUE TITLE
fontconfig built error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#1137]
17:03:14 ┌ fontconfig git ......................... [Newer dependencies]
17:03:14 ├ Running uninstall...
17:03:20 ├ Running configure...
17:04:53 ├ Running make...
Likely error:
checking alignment of double... 8
checking alignment of void *... 8
checking that generated files are newer than configure... done
configure: creating ./config.status
 cd .. && /bin/sh /build/fontconfig-git/missing automake-1.16 --gnu
configure.ac:108: error: required file './config.rpath' not found
Makefile.am:94: warning: subst $(BASECONFIGDIR: non-POSIX variable name
Makefile.am:94: (probably a GNU make extension)
configure.ac:108: error: required file './ABOUT-NLS' not found
make: *** [Makefile:469: ../Makefile.in] Error 1
make failed. Check D:/media-autobuild_suite/build/fontconfig-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

https://0x0.st/z8qj.zip

**Comment by nille02** [comment]
delete fontconfig folder and run again, that was the fix for me.

**Comment by kliffgomel** [comment]
yes it works
