### ISSUE TITLE
ERROR: libvmaf >= 1.3.9 not found using pkg-config

### ISSUE THREAD

**Issue by vdvisa** [jb-alvarado/media-autobuild_suite#1139]
Hi, I downloaded vmaf library from https://github.com/Netflix/vmaf and followed instructions to install the libvmaf.a. Then downloaded the latest ffmpeg code and using  

./configure --enable-debug=1 --disable-asm --enable-libvmaf --enable-version3 --disable-optimizations

to configure, but see an error:

ERROR: libvmaf >= 1.3.9 not found using pkg-config

**Comment by 1480c1** [comment]
Why are you compiling vmaf and ffmpeg separate from the suite? vmaf is already included in the suite and compiling outside of the suite is outside the scope of this suite and if you really want to, it would be better to take this to a forum or to libvmaf.

If you really want to, you can run mintty at the root of the suite with
```
source /build/media-suite_helper.sh
do_vcs "https://github.com/Netflix/vmaf.git"
make clean
do_make INSTALL_PREFIX="$LOCALDESTDIR"
do_makeinstall INSTALL_PREFIX="$LOCALDESTDIR"
```

**Comment by 1480c1** [comment]
These were taken from 
https://github.com/jb-alvarado/media-autobuild_suite/blob/ddf92aeb0f71cf3299e803a1ea8fd2716a0b0061/build/media-suite_compile.sh#L1462-L1472

**Comment by vdvisa** [comment]
I tried to use the FFMPEG suite only and the above configure command still gives the same error.

**Comment by 1480c1** [comment]
Using the bat? If so please post the logs.zip, else can you put your full commands?

**Comment by wiiaboo** [comment]
Or at the very least, FFmpeg's config.log. Otherwise, you're just wasting everyone's time.

**Comment by vdvisa** [comment]
[config.log](https://github.com/jb-alvarado/media-autobuild_suite/files/2985470/config.log)

**Comment by vdvisa** [comment]
The above is the ffbuild/config.log with the ffmpeg suite and configure command

./configure --enable-debug=1 --disable-asm --enable-libvmaf --enable-version3 --disable-optimizations

**Comment by 1480c1** [comment]
`WARNING: pkg-config not found, library detection may fail.`
Can you run `pacboy -S pkg-config:x` if 64bit and `pacboy -S pkg-config:i` if 32bit

**Comment by 1480c1** [comment]
see if pkg-config is actually installed.

**Comment by 1480c1** [comment]
Are you running this from a mac.

**Comment by 1480c1** [comment]
If from a mac, run `brew install pkg-config`

**Comment by vdvisa** [comment]
Perfect, installing this pkg-config worked. I am able to configure now.

Thanks you so much for the help.
