### ISSUE TITLE
faac standalone binary

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#114]
would be nice to have faac as a standalone binary (once again) in media-autobuild_suite,
(would be cool if it would also be compiled with mp4v2 when non-free was enabled as an option, faac
is GPL-2 but the mp4v2 library is MPL-1.1, so it can't be used in public builds)

**Comment by wiiaboo** [comment]
>would be nice to have faac as a standalone binary (once again) in media-autobuild_suite

It never stopped being a binary, what do you mean?
![image](http://i.fsbn.eu/jPNF.png)

We don't compile with mp4v2 because compilation would fail.
Also, why would you want to use faac if you can have fdk-aac available?
