### ISSUE TITLE
Add libnpp statically

### ISSUE THREAD

**Issue by h0rn3z0r** [jb-alvarado/media-autobuild_suite#1140]
Hello, I used this suite to compile ffmpeg with libnpp support.
Here is the result:
<details>
  <summary>ffmpeg command output</summary>

```
> ffmpeg
ffmpeg version N-93396-g4ed6a485d3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.0 (Rev2, Built by MSYS2 project)
  configuration:
--enable-cuda
--enable-cuvid
--enable-nvenc
--disable-debug
--enable-nvdec
--enable-cuda-nvcc
--enable-libnpp
--enable-schannel
--enable-gpl
--enable-nonfree
--extra-cflags='-IC:/PROGRA~1/NVIDIA~2/CUDA/v10.1/include'
--extra-ldflags='-LC:/PROGRA~1/NVIDIA~2/CUDA/v10.1/lib/x64'
```
</details>

<details>
  <summary>ffmpeg_options.txt file</summary>

```
--enable-cuda
--enable-cuvid
--enable-nvenc
--disable-debug
--enable-nvdec
--enable-cuda-nvcc
--enable-libnpp
```
</details>

<details>
  <summary>media-autobuild_suite.ini file</summary>

```ini
[compiler list]
msys2Arch=2
arch=3
license2=1
standalone=2
vpx2=2
aom=2
rav1e=2
dav1d=2
x2643=7
x2652=4
other265=2
vvc=2
flac=2
fdkaac=2
faac=2
mediainfo=2
soxB=2
ffmpegB2=1
ffmpegUpdate=3
ffmpegChoice=1
mp4box=2
rtmpdump=2
mplayer2=2
mpv=2
bmx=2
curl=1
ffmbc=2
cyanrip2=2
redshift=2
ripgrep=2
jq=2
dssim=2
avs2=2
cores=4
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=1
timeStamp=2
noMintty=2
```
</details>

As you can see, the final build includes absolute paths to my CUDA SDK folder which seems not logical for me. That also means I cannot delete SDK (collection of tools needed only for development) or move executable to another computer.

Is there a way to include this library right into the executable file? Because carrying 2 GB folder in order to make one simple filter to work is not an option. Sure I missed some flag during installation, though I followed all instructions related to CUDA in readme.

**Comment by 1480c1** [comment]
I think if it is a static build, it should not need the sdk after building, although I'm not exactly sure on the interaction. Maybe wait for wiiaboo.

**Comment by wiiaboo** [comment]
There's no static libnpp in Windows.

**Comment by wiiaboo** [comment]
Use CUDA equivalents instead; libnpp is being deprecated by Nvidia.

**Comment by 1480c1** [comment]
Then should libnpp be excluded if it's a static build? Or is there some way to copy the libs and headers into the suite and use them instead?

**Comment by 1480c1** [comment]
Or is that not allowed?

**Comment by wiiaboo** [comment]
No. There's a lot of warnings that it will make FFmpeg and based stuff dependant on Cuda SDK.

**Comment by wiiaboo** [comment]
You're also not supposed to be distributing FFmpeg compiled with libnpp since it's using a non-free license, so distributing CUDA SDK libs doesn't make sense from a legal point-of-view, and I'd assume Nvidia also does not allow redistribution of their libraries outside of the SDK.

From a moral standpoint I'll not make it easier to prepare a non-free FFmpeg distribution, but since the suite is open source I obviously can't stop other people from doing what they want with their forks.
