### ISSUE TITLE
vulkan-loader: TypeError in _compile() in python3.7\re.py

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#1147]
Several header files don't compile:
```
...
  File "E:/MABS/local32/share/vulkan/registry\reg.py", line 943, in apiGen
    regEmitExtensions = re.compile(self.genOpts.emitExtensions)
  File "E:/MABS/msys64/mingw32/lib/python3.7\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "E:/MABS/msys64/mingw32/lib/python3.7\re.py", line 285, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
```
Seems to be a quite generic Python syntax issue.

[logs.zip](https://0x0.st/zKy5.zip)

**Comment by LigH-de** [comment]
^ apparently related to a recent Vulkan Headers update.

**Comment by LigH-de** [comment]
Comment by @jzulauf-lunarg
> Vulkan-Loader is not guaranteed to function with the tip of master on any of the constituent projects. Breakage and errors on the tip of those components aside, there may be incompatibilities, new features, or deprecations that affect compatibility. Updating to newer stable component releases is an on-going maintenance task.
So ... lock Vulkan headers to a stable release if you need Vulkan-Loader?

**Comment by 1480c1** [comment]
Maybe that might be a good idea.

**Comment by jzulauf-lunarg** [comment]
Both Vulkan-Loader and Vulkan-ValidationLayers use "known good" versions of constituent components -- 

Vulkan-ValidationLayers/scripts/known_good.json specifies a consistent set including loader, header, and glslang, and spriv components for those building their own, with helper scripts to configure and build.

See -- [Vulkan-ValidationLayers/BUILD.md](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md)

**Comment by jzulauf-lunarg** [comment]
Additionally, each release of the Khronos Vulkan SDK has a [branch](https://github.com/KhronosGroup/Vulkan-ValidationLayers/branches/all?utf8=%E2%9C%93&query=sdk) which could be used as a stable point for all components within the known-good list.

**Comment by weezzelboy** [comment]
How do you disable this in media_autobuild_suite? I dont think i need this, but not sure i just use this for a compiled version of ffmpeg to transcode my plex library as new content come is from the automation scripts.
any help would be great.

**Comment by 1480c1** [comment]
`if ! mpv_disabled vulkan` might help. Can you check your mpv option file?

**Comment by fzold** [comment]
Add --disable-vulkan
to mpv_options.txt in \build

The mpv player really doesn't need it,

**Comment by wiiaboo** [comment]
Clamped to v1.1.102 (as in known-good.json)

**Comment by LigH-de** [comment]
I believe vulkan-loader caught up with vulkan-headers, now it requires the most recent version again. So this patch can be revoked.

After deleting the `#tag=v1.1.102` URL anchor part, I also had to remove the build/vulkan-*-git directories to force an update.

**Comment by wiiaboo** [comment]
Yeah, maybe @1480c1 could also look into a solution for that.
Maybe a text file in the build directory with the last actual used commit/tag/branch before patches and this is checked in `do_vcs`.
Since vcs clamping is rarely used I never really invested that much in fixing this.

**Comment by 1480c1** [comment]
I can try

**Comment by 1480c1** [comment]
Would it just be better to parse the known_working json?

**Comment by LigH-de** [comment]
If you are able to implement that with little efforts, it would possibly be optimal.

**Comment by wiiaboo** [comment]
The know_working json is from vulkan-loaders, not vulkan-headers, so you'd have to compile the latter within vulkan-loaders.

**Comment by 1480c1** [comment]
I was thinking something like curling the know_working.json into maybe jq to get the version number and then do_vcs using that number

**Comment by 1480c1** [comment]
That way I don't need to clone the whole folder before needed and I could keep the current code as it
