### ISSUE TITLE
non-free standalone audio binaries

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#115]
Since I learned yesterday, I have to enable '--enable-libfdk-aac' even is 'free=2' is selected to get a standalone fdkaacenc binary.
What other tools can be enabled this way? 

Do I need to disable anything when 'free=2' is selected to make sure the ffmpeg build is still really a freely distributable build or will the script take care of it?

> --enable-librtmp --enable-gnutls --enable-frei0r --enable-libbluray --enable-libcaca \
--enable-libopenjpeg --enable-libass --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame \
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger \
--enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis \
--enable-libvo-aacenc --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid \
--enable-libzvbi --enable-libdcadec --enable-libbs2b --enable-libmfx --enable-libcdio --enable-libfreetype \
--enable-fontconfig --enable-libfribidi \
--enable-decklink --enable-libutvideo --enable-libgme \
--enable-nonfree --enable-nvenc --enable-libfdk-aac

do I have for example to remove '--enable-nonfree '

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-suite_compile.sh#L356-L373
I don't think the code is that hard to understand?

**Comment by Selur** [comment]
okay
