### ISSUE TITLE
configure: error: C++ compiler cannot create executables

### ISSUE THREAD

**Issue by weezzelboy** [jb-alvarado/media-autobuild_suite#1151]
18:10:51 ┌ tesseract git ............................ [Recently updated]
18:10:51 Installing docbook-xsl... done
18:11:05 Installing libarchive... done
18:11:07 ├ Running autogen...
18:11:33 ├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
../configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/local64 --disable-shared --enable-static --bindir=/local64/bin-global --disable-graphics --disable-tessdata-prefix LIBLEPT_HEADERSDIR=/local64/include LIBS=-LC:/MABS/local64/lib -LC:/MABS/msys64/mingw64/lib -LC:/MABS/local64/lib -LC:/MABS/msys64/mingw64/lib -liconv -llept -lz -lpng16 -lz -ltiff -ljpeg -llzma -lz -lzstd --datadir=/local64/bin-global
configure: loading site script /mingw64/etc/config.site
checking for x86_64-w64-mingw32-g++... x86_64-w64-mingw32-g++
checking whether the C++ compiler works... no
configure: error: in `/build/tesseract-git/build-64bit':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
configure failed. Check C:/MABS/build/tesseract-git/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
18:11:35   Creating diagnostics file...

**Comment by 1480c1** [comment]
`ld.exe: cannot find -ljpeg`
can you run `ld --verbose -ljpeg`

**Comment by weezzelboy** [comment]
found the issue on this one... I forgot that this is a new server install and i didn't install MS Visual studio..
Once that was done it went through just fine..

**Comment by 1480c1** [comment]
That should not be necessary though.

**Comment by 1480c1** [comment]
Oh well.
