### ISSUE TITLE
Dependency Problems Between AVDEVICE-58.DLL & AVFILTER-7.DLL

### ISSUE THREAD

**Issue by dcb-framatome** [jb-alvarado/media-autobuild_suite#1154]
I'm running into a strange dependency problem between AVDEVICE-58.DLL & AVFILTER-7.DLL built using the latest in this suite.  The problem appears when building QtAV with msvc2013.  See the output of dependency walker.  I thought it might have to do with the export .lib's.  When I tried to generate a new export .lib using the lib tool, I encountered the following error:

avdevice-58.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x368

According to my current understanding I should be able to use the mingw generated shared libraries in a msvc compiled application.  Perhaps that is not the case or I need to modify the build parameters to accommodate this build configuration.     

![depends](https://user-images.githubusercontent.com/38476386/55207299-ec792600-51af-11e9-86c6-99fc3f75dd08.png)

**Comment by 1480c1** [comment]
Although I can't say much right now due to not knowing exactly what qtav does and what the exact cause of your problem is, can you try to build qtav using the suite? I saw that it uses cmakefiles so it may be easy to build in the suite. It could be that there may be incompatibilities with msvc and GCC build code

**Comment by 1480c1** [comment]
Also btw, I think this would constitute as out of suite problem, and may be better on a ffmpeg board or qtav board or some other place with people who has more knowledge about your exact problem.

**Comment by 1480c1** [comment]
I can try to look into it more in the morning

**Comment by 1480c1** [comment]
<https://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls>
Would this potentially be related to your dependency walker problem?

**Comment by wiiaboo** [comment]
Out of scope for the suite. Everything compiled for Windows depends on those libs that come OOB with Win10, afaik.

**Comment by dcb-framatome** [comment]
The ffmpeg documentation indicates that it should be possible to link the mingw shared libraries to a msvc application.  However, after searching the web more it appears that in practice it does not work.  I find this build suite incredibly useful for building ffmpeg.  I will submit a patch that will build ffmpeg and a subset of supporting libraries using msvc.

**Comment by wiiaboo** [comment]
No, please don't. Fork your own version of the suite that does that if you want.
