### ISSUE TITLE
libwebp git: gcc.exe: error: unrecognized command line option '-V'

### ISSUE THREAD

**Issue by DragonMorkeleb** [jb-alvarado/media-autobuild_suite#1155]
The logs have been automatically uploaded to https://0x0.st/zPs_.zip

This happens from a fresh version of media-autobuild-suit just checked out.
Tried on two different Windows 10 system, same issue.

I think the same or similar issue came up with vulcan-loader a system that compiled correctly a few days ago, so I tried from scratch only to stumble over this issue.

This is the error displayed on the console:
11:32:59 ┌ libwebp git .............................. [Recently updated]
11:32:59 ├ Running autoreconf...
11:33:27 ├ Running configure...
Likely error:
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for x86_64-w64-mingw32-gcc... gcc
checking whether the C compiler works... no
configure: error: in `/build/libwebp-git/build-64bit':
configure: error: C compiler cannot create executables

**Comment by wiiaboo** [comment]
#1151
