### ISSUE TITLE
The build doesn't finish, here's link to log

### ISSUE THREAD

**Issue by teafusion** [jb-alvarado/media-autobuild_suite#1156]
Sorry, I'm no programmer per se, just power'ish computer user. Did read another thread about similar issues and will try something in those lines.

Here's what I was told to submit for an issue: [logs.zip](https://0x0.st/zPve.zip)

Or maybe I try and start over and select far less options for the build? This is nice service anyway and I would really like libfdk_aac enabled in the ffmpeg I use for my personal needs. Thanks! :)

**Comment by Helenerineium** [comment]
> Error 000 while downloading http://libsdl.org/release/SDL2-2.0.9.tar.gz

So you just ignore this error message? 
Most likely a network issue, just make sure the download works or disable it.

**Comment by teafusion** [comment]
Aah, it was libsdl.org that didn't like my VPN connection since the web page didn't load either. Now the web page loads and obviously the build will succeed past the missing library. Let's hope it was the only problem. 

Thank you Helenerium!
