### ISSUE TITLE
Build of lame-3.99.5 failed...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#116]
deleting the source under build/ didn't help
see: https://pastee.org/e38vk

using

ini:
> [compiler list]
msys2Arch=2
arch=1
free=2
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
mplayer=1
mpv=2
mkv=1
cores=8
deleteSource=1
strip=1
pack=2

and 
ffmpeg_options.txt:
> --enable-librtmp --enable-gnutls --enable-frei0r --enable-libbluray --enable-libcaca \
--enable-libopenjpeg --enable-libass --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame \
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger \
--enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis \
--enable-libvo-aacenc --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid \
--enable-libzvbi --enable-libdcadec --enable-libbs2b --enable-libmfx --enable-libcdio --enable-libfreetype \
--enable-fontconfig --enable-libfribidi \
--enable-decklink --enable-libutvideo --enable-libgme \
--enable-nonfree --enable-nvenc --enable-libfdk-aac

**Comment by jb-alvarado** [comment]
Sorry, I have remove lame again from building: It was now more then a year out from the script and nobody have miss it, and It is still in the msys2/mingw*/bin folder. When somebody have a patch for it the maybe we can put it back again.

**Comment by wiiaboo** [comment]
That lame.exe is shared.
And it's only the 32-bit compilation that fails. Using couple patches from mingw fixes it.
