### ISSUE TITLE
Compilation failed at libtiff build

### ISSUE THREAD

**Issue by Hackerpcs** [jb-alvarado/media-autobuild_suite#1162]
Windows 10 LTSC 64 bit, Intel i5 2500k, 16GB RAM DDR3 1600, GTX 1060 6GB (if it matters). I have Cygwin installed and bin in $PATH, don't know if that causes any trouble and also no WSL installed

[logs.zip](https://0x0.st/zZYN.zip)

```        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
Imported custom options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt

        Starting 64bit compilation of global tools
18:08:47 ├ Running download_rustup...

[snip]

18:35:22 Installing libjpeg-turbo... done
18:35:26   Running git clone for libtiff...
18:35:46 ┌ libtiff git .............................. [Recently updated]
18:35:46 ├ Running cmake...
18:36:10 ├ Running build...
Likely error:
          ^~~~
ninja: build stopped: subcommand failed.
[1/6] Linking C executable contrib\addtiffo\addtiffo.exe
[2/6] Linking C executable contrib\dbs\tiff-grayscale.exe
FAILED: contrib/dbs/tiff-grayscale.exe
cmd.exe /C "cd . && D:\media-autobuild_suite-master\msys64\mingw64\bin\gcc.exe -mthreads -mtune=generic -O2 -pipe -DLIBXML_STATIC -Wall -Winline -W -Wformat-security -Wpointer-arith -Wdisabled-optimization -Wno-unknown-pragmas -Wdeclaration-after-statement -fstrict-aliasing -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ contrib/dbs/CMakeFiles/tiff-grayscale.dir/tiff-grayscale.c.obj  -o contrib\dbs\tiff-grayscale.exe -Wl,--major-image-version,0,--minor-image-version,0  libtiff/libtiff.a port/libport.a C:/tools/cygwin64/lib/libm.a -Wl,-Bstatic -lz -ljpeg -llzma -lzstd -Wl,-Bdynamic -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmsvcrt.a(desis01151.o):(.text+0x0): multiple definition of `log10'
C:/tools/cygwin64/lib/libm.a(t-d000863.o):fake:(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/media-autobuild_suite-master/build/libtiff-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
18:36:42   Creating diagnostics file...```

**Comment by 1480c1** [comment]
That's due to a conflict with msvc's libs and mingw.
I do have a patch for it, but was unsure if it was needed.

**Comment by Hackerpcs** [comment]
> That's due to a conflict with msvc's libs and mingw. I do have a patch for it, but was unsure if it was needed.

I edit the first post that to say that have Cygwin installed and bin in $PATH, don't know if that causes any trouble?

**Comment by 1480c1** [comment]
https://gist.githubusercontent.com/1480c1/3d981dd54aad0baeed8f822bb156fb68/raw/16ed09dafca3b4b646592c0cde82b122a643ced1/0001-Don-t-use-libm-if-MINGW-due-to-conflict-with-libmsvc.patch

This would be applied to libtiff.

in the Msys2 shell, get
https://gist.githubusercontent.com/1480c1/fe9d0ed8a3e353ff99397efe2ff85779/raw/68671f0414d83b1ab08e3a3ae016a70b260ac061/0001-Don-t-use-libm-with-libtiff-due-to-conflict-with-lib.patch
and
then run `git
apply 0001-Don-t-use-libm-with-libtiff-due-to-conflict-with-lib.patch`
This will make the suite apply the patch to libtiff automatically.

Unsure right now I should upstream since technically, there is no need to
link libm for mingw, however, probably will open a issue or pr with libtiff
later.

**Comment by 1480c1** [comment]
Theoretically, it should not matter mainly as libm should not be linked
since mingw-w64 gcc uses libmsvcrt.a for math by default. However, libtiff
has a system to autoinclude libm if it's found. If the patch is applied, it
will only add libm if the system is not mingw

**Comment by wiiaboo** [comment]
FFmpeg uses libm since forever, this shouldn't be an issue (?)

**Comment by wiiaboo** [comment]
libmsvcrt is the thing that shouldn't be linked instead, afaik. That seems like it would only be used as an implicit linked lib, not explicitely.

**Comment by Hackerpcs** [comment]
I can't try the patch right now, for some reason
`info: caused by: https://static.rust-lang.org/rustup/release-stable.toml: timed out`
on a remote VPS I can connect alright

**Comment by 1480c1** [comment]
As far as I know, mingw auto links with libmsvc <
https://stackoverflow.com/questions/48134247/why-i-dont-need-the-flag-lm-in-mingw-but-in-linux-i-need-that-explicitly>
and <https://stackoverflow.com/questions/6394512/standard-c-library-in-mingw
>

**Comment by wiiaboo** [comment]
Why is it not an issue in FFmpeg then? (http://git.videolan.org/?p=ffmpeg.git;a=blob;f=configure;h=f6123f53e5c57c2222212794d4b6f8143f36a330;hb=HEAD#l6090)

**Comment by wiiaboo** [comment]
Also, why the fuck is it trying to use cygwin's libm?

**Comment by 1480c1** [comment]
For the cygwin, it's because I guess cygwin was in his path before mingw(?)
Idk why it only shows up for libtiff with cmake. I had that issue while I
was trying to use cmake for most of the packages, but I chalked it up to a
personal computer issue.

**Comment by 1480c1** [comment]
Libtiff seems to have their own cmake subsystem for detecting the
availability of libs.

**Comment by Hackerpcs** [comment]
> For the cygwin, it's because I guess cygwin was in his path before mingw(?) Idk why it only shows up for libtiff with cmake. I had that issue while I was trying to use cmake for most of the packages, but I chalked it up to a personal computer issue.

I have and use Cygwin personally regardless of compiling ffmpeg, it was in PATH before and without anything to do with media-autobuild_suite

**Comment by wiiaboo** [comment]
The best fix for this would be to sanitize CMake's library search path then. There's absolutely no reason why something within the suite should be looking for libs or executables outside of it (except for stuff like CUDA SDK). It broke here and it'll certainly lead to further breakages in other places.
