### ISSUE TITLE
User patches

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#1163]
Hi,

I need some help. I need to compile FFmpeg with one custom patch.

That's what I've done so far:
- Copy my patch to the directory `media-autobuild_suite-master/build/ffmpeg-git` (name like `ffmpeg-0001-my-patch.patch`).
- Edit the file `build/media-suite_compile.sh` file to add to it one line like `do_patch ffmpeg-0001-my-patch.patch` at this point:
 https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1672

However, I suggest to incorporate some enhancement to support "user patches". For example, listing the directory `local32|64/patches` and getting patches with names `ffmpeg-*.patch`, `mediainfo-*.patch`, etc. So the script then can apply them to each project before configure/compile it.

What you think?

**Comment by schmidthubert** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/pull/797

**Comment by wiiaboo** [comment]
Wait, that wasn't merged, so the idea is still up for grabs.

**Comment by lars18th** [comment]
> No, I strongly disagree with that. Patches get outdated, broken, etc. I'm not up for creating more reasons for new issues that don't have anything to do with the suite.

OK. So just a "simple" solution: Ask at the configuration stage to `1) Apply user patches; 2) No user patches [default][recommended]`. Then if someone has troubles, then it needs only to try with option "2". It's quite simple!

We need some way to apply _some_ patches!

In any case, please almost add some documentation (in the wiki) about the "correct" way to do it manually.

**Comment by wiiaboo** [comment]
For ffmpeg and mpv, just follow the link I posted above. For the others, someone still needs to implement that. I don't really have that much free time to work on this, so anyone's welcome to do it and I can review the solution.

**Comment by 1480c1** [comment]
I can try, however, I would need something like a template. Such as should the file name be matched to the foldername (`ffmpeg-MyPatch.patch` with `ffmpeg-git` and `gpac-mypatch.patch` with `gpac-git`) and where should the custom inputted patched be placed ( `MABS\build\patches`)?\
I can properly update the readme and add a warning that personal patches are not going to be fully supported

**Comment by wiiaboo** [comment]
I was thinking something like ffmpeg_extra.sh instead of just all ffmpeg-*.patch. It's more powerful for those that do need custom tinkering (not just patches).
Maybe something that could be `source`d and has pre-determined functions that would run pre/post configure and pre/post build.

**Comment by 1480c1** [comment]
>I was thinking something like ffmpeg_extra.sh instead of just all ffmpeg-*.patch. It's more powerful for those that do need custom tinkering (not just patches).

Sure, that is possible. Might add something similar to `[[ -f ffmpeg_extra.sh ]] && source ffmpeg_extra.sh` to each, maybe append it to do_vcs and use $vcsFolder if the folder already exists? (Should anything be done if the folder doesn't exist but the user wants to add their patch?

for `source.d`, do you mean under /build or under the individual folders?

**Comment by wiiaboo** [comment]
I mean scripts that could be imported with `source` after retrieving the source. The user-created shell script would contain functions like `_pre_configure()` and `_post_configure()` that would run on their respective points in each lib build.
The scripts might still be stored in `/build`.

**Comment by 1480c1** [comment]
Okay, got it

**Comment by lars18th** [comment]
Hi @wiiaboo & @1480c1 ,

Thank you guys for considering it! :wink: 
However, please @wiiaboo reopen the issue.

**Comment by schmidthubert** [comment]
Thanks. But my tiny mod was and still is good enough and working for me. My script/s is/are modified and I'm doing some things already different here and there anyway and personally I don't really need much extra stuff besides do_patch, sed and the other known tools. I will have to leave testing to lars as I won't have much time for the next 2-3 weeks or so. Once everything is "stable" I'll of course use the official scripts in my testinstalls of the script. Thank you for your work on the subject, I hope everything will work as expected! :+1:

**Comment by lars18th** [comment]
Hi @1480c1 ,

I'm trying your version about "custom scripts for patch". However, the example for `do_patch` uses one URL as the source. Plase, can you add some example using a local file? The question is where is the "relative" path where save the path.

And another question: About the `am` at the end: `do_patch "..." am`. Why we need it?

**Comment by schmidthubert** [comment]
am is needed and is for patches that need to be applied that way, to put it simple ...

**Comment by 1480c1** [comment]
I'll clear it up

**Comment by schmidthubert** [comment]
man 1 git-am, or anything downloaded from ffmpegs patchwork/devel list should suffice to explain it :+1:

**Comment by wiiaboo** [comment]
> am is needed and is for patches that need to be applied that way, to put it simple ...

Nah, you can still do a normal `diff` with git patches, but you can't do `git am` with non-git patches.

**Comment by 1480c1** [comment]
`git format-patch` or `git diff` or `diff` > `git apply` or `patch`. Discard authorship, commit name, etc. Only changes are applied
`git format-patch` > `git am` or `git apply` or `patch`. As if the commit is transferred with the differences and is committed using the information in the patch.  ( shows in `git log` )

Both patch and diff files can be applied with `patch` or `git apply`, but to retain details about a change from a commit, it is necessary to use format-patch and am to apply into another branch or computer etc.

**Comment by schmidthubert** [comment]
I said "simply put" guys. lars didn't even read the comment in the helper for "am", otherwise he wouldn't have asked that. "man git" would have helped as well as it points out git-am. That's why I wanted to keep it in laymens terms ... A function which lets say supports "several ways of doing things" will be a bit hard do explain to users which don't do daily work on the cmdline. Otherwise there should be aliases and function rewrites/overwrites which are more descriptive, which is also possible in shells. Anyway, I really hope you'll not be going from one explanation to the next for "normal users" by doing this change ...

**Comment by 1480c1** [comment]
I'll try to keep it as layman as possible in the readme

**Comment by lars18th** [comment]
Thank you @wiiaboo & @wiiaboo !! :+1:
