### ISSUE TITLE
Suite broken after updating msys / Problem with keyserver after clean install

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#1168]
I just ran the suite and before running the usual updates of msys were done.
But after the updates something seems wrong. I get this error message when starting mintty:

![mintty_error](https://user-images.githubusercontent.com/17316492/56140651-97088b80-5f9b-11e9-853f-4152b4fb57a8.png)
I know it's in german, but you probably can see the main infos.

After that I tried a clean install... But another error occured.
```
gpg: error reading key: public key not found
==> ERROR: The fingerprint of a specified key could not be determined.
gpg: requesting key AE4FF531 from hkp server pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
==> ERROR: Remote key not fetched correctly from keyserver.
gpg: error reading key: public key not found
==> ERROR: A specified signature could not be listed.
==> ERROR: AE4FF531 could not be locally signed.
kill: not enough arguments

-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

:: Synchronizing package databases...
 abrepo                                          29.0   B  0.00B/s 00:00 [#######################################] 100%
 abrepo.sig                                     566.0   B  0.00B/s 00:00 [#######################################] 100%
error: abrepo: key "EFD16019AE4FF531" is unknown
error: key "EFD16019AE4FF531" could not be looked up remotely
error: failed to update abrepo (invalid or corrupted database (PGP signature))
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
error: failed to synchronize all databases
error: abrepo: key "EFD16019AE4FF531" is unknown
error: key "EFD16019AE4FF531" could not be looked up remotely
```
Any ideas?

**Comment by 1480c1** [comment]
Something happened with gpg, I also have the problem

**Comment by wiiaboo** [comment]
Maybe just remove abrepo altogether. It's not being used for anything ATM.

**Comment by Selur** [comment]
same here :/

**Comment by moisesmcardona** [comment]
I had this issue earlier today. I deleted the msys64 folder and let it download fresh files. It worked after the second attempt, as the first one produced compilation errors building the suite.

**Comment by BlackScreen** [comment]
> I had this issue earlier today. I deleted the msys64 folder and ran the suite to let it download fresh files. It worked after the second attempt, as the first one produced compilation errors building the suite.
Deleting the "msys64" folder in the "old" install helped getting rid of the error in the screenshot, but the key errors are still there.

**Comment by moisesmcardona** [comment]
> > I had this issue earlier today. I deleted the msys64 folder and ran the suite to let it download fresh files. It worked after the second attempt, as the first one produced compilation errors building the suite.
> 
> Deleting the "msys64" folder in the "old" install helped getting rid of the error in the screenshot, but the key errors are still there.

Not sure what your problem may be. After I deleted it, it's been working fine and everything fetches and updates correctly. I'm not seeing any key errors.

**Comment by BlackScreen** [comment]
> Not sure what your problem may be. After I deleted it, it's been working fine and everything fetches and updates correctly. I'm not seeing any key errors.

I don't know it either. Is no one else having this problem? What can I do?

**Comment by Selur** [comment]
Had the same issue and deleting the msys64 folder made it working again for me too,..

**Comment by kliffgomel** [comment]
I had another similar self-signed certificate error with a clean install. How can you solve it?

Running download_rustup...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
curl https://sh.rustup.rs -sSo rustup.sh
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

https://0x0.st/zqQV.zip

**Comment by LigH-de** [comment]
Confirming the issue for two installations on different PCs. The core appears to be `GPGME error: Invalid Crypto Engine` after updating to gnupg-2.2.15-1, which interrupts the updating before pacman can find more indirectly related packages to be updated, like msys2-runtime.

You may remember that it happens quite often that there may be packages left not yet updated after an update, so it is quite a routine for me to interrupt the compilation after an update and start the suite over. I already suggested once to implement a loop: While there is an update, repeat until there was no more update, before continuing to the compilation.

@kliffgomel - to reinstall rust, delete /msys64/opt/cargo (I had to do that already a few times for different reasons).

**Comment by kliffgomel** [comment]
> @kliffgomel - to reinstall rust, delete /msys64/opt/cargo (I had to do that already a few times for different reasons).
I make a clean installation, the certificate error occurs when you first install the rust. I have nothing to delete.

**Comment by schmidthubert** [comment]
[This](https://github.com/msys2/MSYS2-packages/issues/1601) looks similar? Sounds as if gpg is the real culprit here? 

I'll probably put

`IgnorePkg	= mingw-w64-x86_64-gnupg mingw-w64-i686-gnupg libgpg-error libgpg-error-devel mingw-w64-x86_64-gpgme mingw-w64-i686-gpgme libgpgme libgpgme-devel libgpgme-python2 libgpgme-python3`

in my pacman.conf once I have backed up everything :+1:

**Comment by lars18th** [comment]
> Something happened with gpg, I also have the problem

Me too!
And the worst is the suite doesn't autoupdate (it fails too to download from the git repo). So to update I use `git pull origin master` as I downloaded the suite with `git clone`.

I hope someone will fix this bug.
Regards.

**Comment by BlackScreen** [comment]
Ok, well... It seems that it must have something to do with my network.
After making a hotspot with my mobile phone, the keys could be loaded. No more erros in that direction... Weird, but ok.
