### ISSUE TITLE
Custom Patches: Logging

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#1169]
Hi,

Testing the new functionality "Custom Patches" with a simple example like the one listed in the README: `Example Script: /build/ffmpeg_extra.sh for ffmpeg-git`, I found one "trouble":

- The logging system doesn't print anything about the execution of the patch:
```
13:41:40   Running git update for ffmpeg...
13:42:30 ┌ ffmpeg git .................................. [Updates found]
13:42:30 ├ Changing options to comply to nonfree...
13:42:32 ├ Compiling static FFmpeg...
13:42:34 ├ Running uninstall...
13:42:34 ├ Running pre_configure...
13:43:05 ├ Running configure...
13:48:39 ├ Running make...
```

And this is true with the local file `build/ffmpeg_extra.sh`. 
In fact, no problem at all... as the patch in the extra file is applyed.

However, perhaps will be interesting to print **almost** something like:
```
13:41:40   Running git update for ffmpeg... [using ffmpeg_extra.sh]
```

What you think @1480c1?
Any option to enable LOGGING _inside_ the extra file?

**Comment by 1480c1** [comment]
Possible, let me think

**Comment by 1480c1** [comment]
Can you check inside ffmpeg-git and see if there is a log file named "ab-suite.<pre_configure>.log" or whatever you did?

**Comment by lars18th** [comment]
> Can you check inside ffmpeg-git and see if there is a log file named "ab-suite.<pre_configure>.log" or whatever you did?

I don't see any log file in "ffmpeg-git" after the end of the compilation.

**Comment by 1480c1** [comment]
That possibly means that it did not run.
Can you show your ffmpeg_extra.sh?

**Comment by lars18th** [comment]
> That possibly means that it did not run.

I'm sure it runs... as the binary (and the code) contains the patch.

> Can you show your ffmpeg_extra.sh?

The file `ffmpeg_extra.sh`:
```
#!/bin/bash
_pre_configure(){
    # Apply a patch from ffmpeg's patchwork site.
#    do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/" am
    do_patch "../ffmpeg-0002.patch"
    do_patch "../ffmpeg-0003.patch"
    # Add extra configure options to ffmpeg (ffmpeg specific)
    # If you want to add something to ffmpeg not within the suite already
    # you will need to install it yourself, either through pacman
    # or compiling from source.
#    FFMPEG_OPTS+=(--enable-libsvthevc)
}
```

And I put the two files `ffmpeg-*.patch` in the same directory as the `ffmpeg_extra.sh` (aka `build/`).
Quite simple, rigth?

**Comment by 1480c1** [comment]
`13:42:34 ├ Running pre_configure...`
Nvm, it is there.

**Comment by 1480c1** [comment]
Maybe it can be polished or more noticable

**Comment by lars18th** [comment]
> Maybe it can be polished or more noticable

My suggestion is to make more visible:
- When the `*_extra.sh` script is running.
- And add support for logging from the script (for example redirecting `echo` commands, or printing some function calls, like `do_patch`).

This will have _two_ objectives:
1. Help writing these scripts (for testing).
2. Advertizing about his use.

I hope you can make it a little better.
Thank you! :wink:

**Comment by wiiaboo** [comment]
>     * And add support for logging from the script (for example redirecting `echo` commands, or printing some function calls, like `do_patch`).

Just use the same functions for logging as the suite uses. We're `source`ing the script, not interpreting it manually.

**Comment by lars18th** [comment]
> Just use the same functions for logging as the suite uses. We're `source`ing the script, not interpreting it manually.

OK. Then update the example (`/build/ffmpeg_extra.sh`) in the `README.md` file with just one example of a log message!

**Comment by 1480c1** [comment]
although it's possible to do so using `do_print_progress "Running My custom
patch"` somewhere in the ffmpeg_extra.sh. I do not think that it would
actually be necessary simply because it's more of an aesthetic thing rather
than a functional command

**Comment by lars18th** [comment]
> `do_print_progress "Running My custom patch"`

I feel it's good for _the example_ !!

**Comment by lars18th** [comment]
```
#!/bin/bash
_pre_configure(){
    # Apply a patch from ffmpeg's patchwork site.
    do_print_progress "Running My patch !!"
    do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/" am
    # Add extra configure options to ffmpeg (ffmpeg specific)
    # If you want to add something to ffmpeg not within the suite already
    # you will need to install it yourself, either through pacman
    # or compiling from source.
    FFMPEG_OPTS+=(--enable-libsvthevc)
}
```

**Comment by 1480c1** [comment]
If you want, you can submit a pr with what you think would make a good example. I'm not so good at that because I don't really use the extra_script function

**Comment by lars18th** [comment]
Hi @1480c1 ,

I need your help!

With this example of `ffmpeg_extra.sh`:
```
#!/bin/bash
_pre_configure(){
    # Apply a patch from ffmpeg's patchwork site.
    do_print_progress "Running My patch !!"
    do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/" am
    do_patch "/ffmpeg-0001-mypatch.patch"
    # Add extra configure options to ffmpeg (ffmpeg specific)
    # If you want to add something to ffmpeg not within the suite already
    # you will need to install it yourself, either through pacman
    # or compiling from source.
    FFMPEG_OPTS+=(--enable-libsvthevc)
}
```

I have troubles:

1. In the main window where running `media-autobuild_suite.bat` I only see:

```
11:33:56   Running git update for ffmpeg...
11:33:59 ┌ ffmpeg git ............................... [Recently updated]
11:33:59 ├ Changing options to comply to nonfree...
11:34:00 ├ Compiling static FFmpeg...
11:34:01 ├ Running pre_configure...
```

And nothing more!
However, inside the file `ffmpeg-git/ab-suite.pre_configure.log` I see:
`11:34:01 ├ Applying FFmpeg user patches...`.
But the idea is:
- Print some warning (message) in the _main_ window about the running user commands.
- Or enable from the `*_extra.sh` some function to print to the _main_ window.

So, It's the command `do_print_progress` the right command?

2. When I nee to apply a _local_ patch, the script now fails (from `ffmpeg-git/ab-suite.pre_configure.log`):

```
        Patch not found anywhere. Continuing without patching.
11:34:03 └ ffmpeg-0001-mypatch.patch ............................. [Failed]
Error 000 while downloading /ffmpeg-0001-mypatch.patch
<Ctrl+c> to cancel build or <Enter> to continue
```

- What's the correct code for forcing _local_ files?
- Any workaround to CONTINUE if the patch fails? The idea is overcome the user request, as the _main_ window doesn't print anything!

I hope you can fix this.
And thank you for your support.

**Comment by 1480c1** [comment]
>However, inside the file ffmpeg-git/ab-suite.pre_configure.log I see:
>11:34:01 ├ Applying FFmpeg user patches....

I think that is because of https://github.com/jb-alvarado/media-autobuild_suite/blob/8896e7743188a7f2a2e12c562086e1faca200903/build/media-suite_helper.sh#L1858
where that log is the over encompassing command that send all output to the log. To fix that, you could remove `log quiet "${stage}_${commandname}"` from the line and only have `_${stage}_${commandname}`. Since we already have do_print_progess with `Running ${stage} ${commandname} from ${vcsFolder}_extra.sh` it should be fine to remove log quiet. Only problem is that then there is no default log and so if someone does have a problem, it will become harder to debug.

**Comment by 1480c1** [comment]
>What's the correct code for forcing local files?
>Any workaround to CONTINUE if the patch fails? The idea is overcome the user request, as the main window doesn't print anything!

looking at do_patch, it seems that for local patches, it will only accept them if they are within the local folder (ffmpeg-git) and it cannot handle relative or absolute paths. Maybe I can fix, but it may take a while. Still feel drowsy

**Comment by lars18th** [comment]
> > What's the correct code for forcing local files?
> > Any workaround to CONTINUE if the patch fails? The idea is overcome the user request, as the main window doesn't print anything!
> 
> looking at do_patch, it seems that for local patches, it will only accept them if they are within the local folder (ffmpeg-git) and it cannot handle relative or absolute paths. Maybe I can fix, but it may take a while. Still feel drowsy

Don't worry. I'll try first to use them in the local folder. The objective is to publish in the example how to use it.

Regards.

**Comment by lars18th** [comment]
> > However, inside the file ffmpeg-git/ab-suite.pre_configure.log I see:
> > 11:34:01 ├ Applying FFmpeg user patches....
> 
> I think that is because of
> 
> [media-autobuild_suite/build/media-suite_helper.sh](https://github.com/jb-alvarado/media-autobuild_suite/blob/8896e7743188a7f2a2e12c562086e1faca200903/build/media-suite_helper.sh#L1858)
> 
> Line 1858 in [8896e77](/jb-alvarado/media-autobuild_suite/commit/8896e7743188a7f2a2e12c562086e1faca200903)
> 
>  log quiet "${stage}_${commandname}" _${stage}_${commandname} 
> 
> where that log is the over encompassing command that send all output to the log. To fix that, you could remove `log quiet "${stage}_${commandname}"` from the line and only have `_${stage}_${commandname}`. Since we already have do_print_progess with `Running ${stage} ${commandname} from ${vcsFolder}_extra.sh` it should be fine to remove log quiet. Only problem is that then there is no default log and so if someone does have a problem, it will become harder to debug.

Then perhaps the best option is then to print some `log` without `quiet` in the source script when the file `*_extra.sh` is used. From my point of view is sufficient to warn that this "optional" file is in use.
You agree?

**Comment by 1480c1** [comment]
`log` will print the `11:34:01 ├ Running pre_configure...` but the quiet will just suppress that so that way we can use the custom `do_print_progress "Running ${stage} ${commandname} from ${vcsFolder}_extra.sh"`

Have you pulled the latest?

**Comment by wiiaboo** [comment]
Why use do_patch if you're always getting the patch locally? You might as well just use `patch -p1 -i patch.diff` on its own.

**Comment by 1480c1** [comment]
That is true

**Comment by lars18th** [comment]
Hi @1480c1 ,

Good job! 
In lhe last version:
```
10:20:16   Running git update for ffmpeg...
10:20:19 ├ Found ffmpeg_extra.sh. Sourcing script...
10:20:19 ┌ ffmpeg git ............................... [Recently updated]
10:20:19 ├ Changing options to comply to nonfree...
10:20:21 ├ Compiling static FFmpeg...
10:20:23 ├ Running pre configure from ffmpeg_extra.sh...        /*  <<<=== +1  */
10:20:23 ├ Running configure...
10:24:50 ├ Running make...
```

That's all as I need.
Thank you!

And I created the PR #1176 to improve the example.
When it will be merged, then I'll close this issue.

Thank you all! :+1:

**Comment by lars18th** [comment]
Solver in #1181.
