### ISSUE TITLE
Build of ffmpeg-git failed...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#117]
> -------------------------------------------------
x265 is already up to date
-------------------------------------------------
-------------------------------------------------
ffmbc-0.7.4 is already compiled
-------------------------------------------------
Cloning into 'ffmpeg-git'...
remote: Counting objects: 432341, done.
remote: Compressing objects: 100% (91261/91261), done.
remote: Total 432341 (delta 343494), reused 429105 (delta 340353)
Receiving objects: 100% (432341/432341), 102.49 MiB | 733.00 KiB/s, done.
Resolving deltas: 100% (343494/343494), done.
Checking connectivity... done.
Checking out files: 100% (5212/5212), done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4212  100  4212    0     0   4220      0 --:--:-- --:--:-- --:--:--  4220
patching file configure
Hunk #1 succeeded at 5147 (offset 37 lines).
Hunk #2 succeeded at 5158 (offset 37 lines).
Hunk #3 succeeded at 5181 (offset 37 lines).
Hunk #4 succeeded at 5190 (offset 37 lines).
ERROR: x265 not found using pkg-config
>
>If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
Makefile:2: config.mak: No such file or directory
Makefile:59: /common.mak: No such file or directory
Makefile:100: /libavutil/Makefile: No such file or directory
Makefile:100: /library.mak: No such file or directory
Makefile:102: /doc/Makefile: No such file or directory
Makefile:185: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:59: /common.mak: No such file or directory
Makefile:100: /libavutil/Makefile: No such file or directory
Makefile:100: /library.mak: No such file or directory
Makefile:102: /doc/Makefile: No such file or directory
Makefile:185: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
-------------------------------------------------
Build of ffmpeg-git failed...
Delete the source folder under '/build' and start again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

deleting the ffmpeg source folder didn't help

**Comment by jb-alvarado** [comment]
Yesterday it has work... I have here the same problem, maybe something has change in x265. We need a deeper look at it.

**Comment by jb-alvarado** [comment]
The last part from config.log

```
D:/_System/msys2-64_Juni2015/local64/lib/libx265.a(api.cpp.obj):api.cpp:(.text+0x6b3): undefined reference to `x265_12bit::x265_api_get_63(int)'
D:/_System/msys2-64_Juni2015/local64/lib/libx265.a(api.cpp.obj):api.cpp:(.text+0x6c3): undefined reference to `x265_10bit::x265_api_get_63(int)'
D:/_System/msys2-64_Juni2015/local64/lib/libx265.a(api.cpp.obj):api.cpp:(.text+0x723): undefined reference to `x265_10bit::x265_api_query(int, int, int*)'
D:/_System/msys2-64_Juni2015/local64/lib/libx265.a(api.cpp.obj):api.cpp:(.text+0x733): undefined reference to `x265_12bit::x265_api_query(int, int, int*)'
collect2.exe: error: ld returned 1 exit status
ERROR: x265 not found using pkg-config
```

**Comment by wiiaboo** [comment]
Forgot to do a couple of `mv` and `cp`.

**Comment by wiiaboo** [comment]
Don't forget to delete x265-hg dir or deleting x265.pc in /local*/lib/pkgconfig/
