### ISSUE TITLE
Vulkan Headers : parsing .json file always fails

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#1172]
When the suite is trying the get the l**ast-known-good version** from the Vulcan Headers, the parsing using **jq** seems always to fail. {**jq gives a compile error**)
See the relevant output from the log below:

```
mujs git .................................................. [Up-to-date]
jq: error: select/1 is not defined at <top-level>, line 1:
.repos[] | select(.name == "Vulkan-Headers").commit           
jq: 1 compile error
(23) Failed writing body

media-autobuild_suite_647 (64bit):   Running git clone for vulkan-headers in .  Running git clone for vulkan-headers in .
+ [[ git = \s\v\n ]]
+ git clone https://github.com/KhronosGroup/Vulkan-Headers.git vulkan-headers-git
Cloning into 'vulkan-headers-git'...
remote: Enumerating objects: 917, done.

+ set +x
+ [[ git = svn ]]
+ [[ git = hg ]]
+ [[ git = git ]]
+ [[ -n https://github.com/KhronosGroup/Vulkan-Headers.git ]]
+ git remote set-url origin https://github.com/KhronosGroup/Vulkan-Headers.git
+ git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
+ [[ -f .git/refs/heads/ab-suite ]]
+ git branch -f --no-track ab-suite
+ git checkout ab-suite
Switched to branch 'ab-suite'
++ vcs_getlatesttag v1.1.106
++ local ref=v1.1.106
++ [[ -n git ]]
++ [[ git != git ]]
++ local tag
++ [[ v1.1.106 = \L\A\T\E\S\T ]]
++ [[ v1.1.106 = \G\R\E\A\T\E\S\T ]]
++ [[ v1.1.106 != \v\1\.\1\.\1\0\6 ]]
++ echo v1.1.106
+ git reset --hard v1.1.106
HEAD is now at 08cbb54 scripts: Fix generator on Windows with Python < 3.6
++ git rev-parse HEAD
+ oldHead=08cbb5458f692d4778806775f65eb3dc642ddbbf
+ set +x
┌ vulkan-headers git ................................ [Recently updated]

**Comment by 1480c1** [comment]
Can you delete jq-git if it exists in your build folder and rerun?

**Comment by pat357** [comment]
I have deleted the jq , vulkan-headers and vulkan folders from /build and forced recompile of those, but the same result 
```
jq: error: select/1 is not defined at <top-level>, line 1:
.repos[] | select(.name == "Vulkan-Headers").commit
jq: 1 compile error
(23) Failed writing body
```
Also tried with **jq=2 in the .INI** file and use the jq installed by pacman, but the same result ......

**Comment by 1480c1** [comment]
did you delete the jq.exe from the local64/bin-global folder

**Comment by pat357** [comment]
That was it ! It's solved now, but only the by pacman installed jq.exe seems to work ;  my own compile does not work for some unknown reasons.

**Comment by pat357** [comment]
Thanks for helping me out with this.

**Comment by 1480c1** [comment]
Is this still an issue? If not can @pat357 or @wiiaboo close this?

I think that I need to look at jq again.

**Comment by pat357** [comment]
It's just that the **jq.exe** compiled by the script does not work.
I have to use the one installed by pacman.

**Comment by wiiaboo** [comment]
The jq issue should be fixed, I submitted my PR to fix it, but I forgot to apply it in the suite.
The builtin.jq file containing select/to_entries, etc. wasn't found with out-of-root builds.
