### ISSUE TITLE
Newer commit always ask to remove luajit and install luajit-git

### ISSUE THREAD

**Issue by moisesmcardona** [jb-alvarado/media-autobuild_suite#1173]
MinGW always asks me to delete `mingw-w64-x86_64-luajit` and to install `mingw-w64-x86_64-luajit-git`

**Comment by schmidthubert** [comment]
Same here, even without updating msys/mingw for several weeks now, I'm just waiting that out a bit :+1: 

Another fuckup I guess, see my comment in https://github.com/jb-alvarado/media-autobuild_suite/pull/1171

**Comment by 1480c1** [comment]
I think its because we installed luajit-git using do_pacman_install so our system still thinks we need to use luajit-git since we never used do_pacman_remove

**Comment by schmidthubert** [comment]
I've tried all of them methods on the cmdline and it doesn't go away? force noconfirm nodeps asdeps etc you name it ...?

**Comment by 1480c1** [comment]
have you done `do_pacman_remove luajit-git`?

**Comment by schmidthubert** [comment]
Just look at the code please? It doesn't do anything special. So that'S yes, I have. It's getting removed from the extra pac file ...

**Comment by 1480c1** [comment]
I did, that's why I asked

**Comment by schmidthubert** [comment]
Simply install the 2.0.5 *on the cmdline*, you can even do it with -U and the path to 2.0.5 xz and leave 2.0.4-git installed. It will report to upgrade it (or whatever) and then check with pacman -Ss if it's reporting as installed. It is NOT for me.

**Comment by schmidthubert** [comment]
Probably -Sii or something to check all packages for depenciies ...

**Comment by schmidthubert** [comment]
Here's who committed luajit for luajit-git
https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-luajit

I'm getting tired!

**Comment by LigH-de** [comment]
By the way ... my update script complains that it is unable to set the **installation reason** for this package which it can't find. I guess that is related to using the correct media-suite_helper functions.

**Comment by LigH-de** [comment]
Will there be a solution?

**Comment by 1480c1** [comment]
To be honest, it doesn't occur on my system even though I've been running it every time there's a new commit or during testing and repeating compilation after it's done

**Comment by LigH-de** [comment]
So how would I clean my system from the installed versions and install the most recent versions manually, to ensure that the pacman repo is able to register an installation reason? I am not at all experienced with CLI parameters, nor do I know by heart which helper functions I may have to use alternatively.

**Comment by moisesmcardona** [comment]
It's true... I think deleting `msys64` and letting the suite download and install everything again will fix this. I'm doing a fresh installation on another PC and it didn't prompt me to remove luajit.

**Comment by wiiaboo** [comment]
Pacman is a bit dumb with replaced/conflicts packages, manual fix is ideal for this.

**Comment by LigH-de** [comment]
But what is the manual fix (except for deleting msys64 and installing the whole system again)?

**Comment by wiiaboo** [comment]
```bash
# remove the old package
pacboy -Rcs luajit-git
# install the new package
pacboy -S luajit
# remove traces of the old package from the suite's list of installed packages
sed 's;luajit-git;luajit;g' /etc/pac-mingw-extra.pk
```

**Comment by LigH-de** [comment]
Tried that; and then, next time I run the suite, it wants to uninstall luajit and re-install luajit-git (where it can't set the installation reason).

**Comment by wiiaboo** [comment]
Well, then I have no idea why it keeps trying to install luajit-git. There's nothing in the .bat for it have a reason to try to install luajit-git. Did you make sure /mys64/etc/pac-mingw-extra.pk doesn't have a line with it?

**Comment by LigH-de** [comment]
The sed did not change its content, apparently it prints it to the console only. I will delete the line there with an editor.

**Comment by 1480c1** [comment]
need -i flag
set -i ...

**Comment by wiiaboo** [comment]
Yeah, mb. I've updated the comment.
