### ISSUE TITLE
FFmpeg (Zeranoe-emulating build)

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#1174]
Was compairing the configuration (through ffmpeg.exe --version) of the suites Zeranoe-emulating build and Zeranoe's own and there is a couple of libs is missing in the suites compiles

  --enable-libx264
  --enable-libx265

**Comment by wiiaboo** [comment]
If you disable x264 and x265 compilation and you've never built them, the options are removed.

**Comment by Barough** [comment]
Didn't know that. Thnx for the info. 

Starting over again
