### ISSUE TITLE
FFmpeg pkg-config can't find OpenCL

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#1175]
[logs.zip](https://0x0.st/zbol.zip)
```
  Running git update for ffmpeg...
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libdav1d --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-libopenmpt --enable-version3 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --enable-libvmaf --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree
ERROR: opencl not found
```

**Comment by 1480c1** [comment]
Do you have opencl?

**Comment by Metaphorce812** [comment]
@1480c1 Yes.

**Comment by 1480c1** [comment]
can you put in the output of `ls $(cygpath.exe -S) | grep -i opencl` from a mintty shell?

**Comment by Metaphorce812** [comment]
@1480c1 
```
$ ls $(cygpath.exe -S) | grep -i opencl
OpenCL.dll
```

**Comment by 1480c1** [comment]
How about under local(64|32)/lib/libOpenCL.a?

**Comment by Metaphorce812** [comment]
@1480c1 Yup it's there.

**Comment by 1480c1** [comment]
Can you try recompiling after deleting libopencl.a and ffmpeg-git?

**Comment by Metaphorce812** [comment]
@1480c1 Tried that and got the same error.  
[logs.zip](https://0x0.st/zbLn.zip)

**Comment by 1480c1** [comment]
Seems that the problem is that one of the functions that ffmpeg checks for opencl availability is absent from your opencl library. How did you install opencl, and can you try reinstalling it?

**Comment by Metaphorce812** [comment]
@1480c1 I believe OpenCL was installed with the drivers for my nVidia GeForce GTX 1070 Ti. I just tried installing the Cuda Toolkit (v10.1), and the output when trying to build FFmpeg was different (I've bolded the new sections below), but unfortunately the result was the same.

[logs.zip](https://0x0.st/zczU.zip) 

Running git update for ffmpeg...
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
**FFmpeg and related apps will depend on CUDA SDK to run!**
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libdav1d --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-libopenmpt --enable-version3 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libnpp --enable-libopenh264 --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --enable-libvmaf --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree **--extra-cflags=-IC:/PROGRA\~1/NVIDIA\~2/CUDA/v10.1/include --extra-ldflags=-LC:/PROGRA\~1/NVIDIA\~2/CUDA/v10.1/lib/x64**
ERROR: opencl not found

```

**Comment by wiiaboo** [comment]
That's not different. That's exactly the same with a few more flags that don't affect absolutely anything to do with OpenCL.

**Comment by Metaphorce812** [comment]
@wiiaboo OK, any suggestions?

**Comment by wiiaboo** [comment]
Don't enable OpenCL? If it's broken for you, it's because the lib you're trying to use lacks the expected symbols/functions. Even if you get another OpenCL lib that has them, it might not work with your card/drivers.
