### ISSUE TITLE
Vulkan header fails because of '-Wno-stringop-truncation'

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#1179]
[logs.zip](https://0x0.st/zb4_.zip)

**Comment by 1480c1** [comment]
You should report to vulkan loader, their cmakelists adds that flag. Mention the they can use check_c_compiler_flag or something for their cmakelists

**Comment by 1480c1** [comment]
Also, what version is your GCC?

**Comment by 1480c1** [comment]
Either way, it seems that the error comes from something else, something about unknown types

**Comment by 1480c1** [comment]
` VkIcdSurfaceHeadless headless_surf;`
The VkIcdSurfaceHeadless is the unknown and was added in a recent commit. The struct is introduced in the vulkan-header commit (v1.1.107) and it seems as if you're vulkan-header updated so you should have it

**Comment by Selur** [comment]
> $ gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Selur** [comment]
-> disabled mpv for the time being so no need to build vulkan

**Comment by Helenerineium** [comment]
I believe the error comes from version mismatch between header (v1.1.106) and loader (HEAD - v1.1.107)
It can be solved by using the same version of header and loader.

https://github.com/jb-alvarado/media-autobuild_suite/blob/8b254d7568c3de6eaad992b674cddd7b9e5866bf/build/media-suite_compile.sh#L1866

should be `"https://github.com/KhronosGroup/Vulkan-Loader.git#tag=${_Vulkan_Version:-v1.1.106}"`

**Comment by 1480c1** [comment]
So should both version be using the known_good.json?

**Comment by Helenerineium** [comment]
> So should both version be using the known_good.json?

Yes, I'm using sdk-v1.1.106 for both, but v1.1.106 from known_good.json should also works.
