### ISSUE TITLE
ffmpeg.exe - Entry Point Not Found on Microsoft® Windows® Web Server 2008

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#118]
A user got an:
> ffmpeg.exe - Entry Point Not Found
The procedure entry point GetNumaNodeProcessorMaskEx could not be located in the dynamic link library KERNEL32.dll. 

exception trying to use ffmpeg, since GetNumaNodeProcessorMaskEx sounds like x265, is possible to disable libx265 from being build into ffmpeg? (checked the ffmpeg_options.txt, but there was no mentioning of x265)

**Comment by wiiaboo** [comment]
The script explicitly adds --enable-libvpx/libx264/libx265 according to whether the respective libs are built or not. I can take that away and just obey ffmpeg_options.txt.

Is that ffmpeg 32-bits that's giving that error? It shouldn't.

**Comment by Selur** [comment]
> Is that ffmpeg 32-bits that's giving that error? It shouldn't.

I think that it's ffmpeg 32bit, but I'll ask the user to make sure. (he didn't post if it was a 32bit OS)
(will report back once I get feedback from the user)

> The script explicitly adds --enable-libvpx/libx264/libx265 according to whether the respective libs are built or not. I can take that away and just obey ffmpeg_options.txt.

sounds good to me

**Comment by Selur** [comment]
He's using a 64bit system, so it's a 64bit OS and x265 also doesn't work for him properly. :(

**Comment by wiiaboo** [comment]
So it's 64-bit XP.

**Comment by Selur** [comment]
iirc Windows® Web Server 2008 is based on Vista, not XP

**Comment by wiiaboo** [comment]
Right, Vista/2008 didn't have that function either. Server 2008 R2 has it, since it's based on 7.

**Comment by wiiaboo** [comment]
Check a0b509ceb16456a1f923e8f859e36eec66c8fd38...531929ccc6edfebb3eb6999813ab927c6d1378ad.

**Comment by Selur** [comment]
Updated an got:

>updating msys2 system...
-------------------------------------------------------------------------------
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
-------------------------------------------------------------------------------
updating msys2 done...

will report back once the script ran through,...

**Comment by wiiaboo** [comment]
Sourceforge is down, you can't update msys.

**Comment by Selur** [comment]
ah okay. (the database being reported as invalid/corrupted sounded serious)

**Comment by wiiaboo** [comment]
You can still run the suite, it just won't upgrade msys/mingw. Also, make sure to not delete anything from /mingw32 or /mingw64, or it will prevent you from building.

**Comment by Selur** [comment]
Script is running, but since bitbucket is totally slow atm, it's really a pain,.. :)

**Comment by Selur** [comment]
stuck at: Cloning into 'libgme-git'...
for quite a bit of time now
-> will test tomorrow and report back
