### ISSUE TITLE
Adding libfdk-aac to my Zeranoe emulated FFmpeg build - how-to

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#1180]
Dont need to make the 'Full' FFmpeg, just need to add fdk-aac to my Zeranoe emulated FFmpeg. That will cover my needs.

I know it has something to do with adding --enable-libfdk-aac somewhere but i just can't find out the where and how, So can someone please let me know hpw to make this possible

**Comment by 1480c1** [comment]
you can change `ffmpegChoice` in the build\media-autobuild_suite.ini 1 and then follow the prompt and delete all of the unwanted flags. Provided you have libfdk-aac being built

**Comment by Barough** [comment]
That was an easy solution. Thanks a lot. :)
