### ISSUE TITLE
Disable logs uploads

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#1182]
Hi,

Any option to disable the logs upload functionality?

I'm using the `*_extra.sh` file to apply custom patches, and sometimes any of my patches fails to complie. So in this case it's irrelevant to upload the log.

Ideas?

**Comment by 1480c1** [comment]
Not really. It could be helpful still to upload log since that way you can
easily share it if some other package fails. If you have custom patches,
you should have patchedFolders file under build

**Comment by lars18th** [comment]
Hi @1480c1 ,

Think that this is quite stupid. If I try to recompile 10 times, and 5 the compilation fails because an incorrect CUSTOM PATCH (note this, the patch is LOCAL), why upload logs?

I feel it has sense to include the option to disable uploads with some flags from `*_extra.sh`.

**Comment by 1480c1** [comment]
It could be implemented under zip_logs, however, I still think there is
merit to uploading logs

**Comment by GyanD** [comment]
I suggest that the log uploading be factorized into a separate script and an option added whether to automatically call the script upon build failure. Default can be true. User can still manually upload logs afterwards even when set to false.

**Comment by wiiaboo** [comment]
Thanks, that's the exact same thing @lars18th said.

**Comment by lars18th** [comment]
Hi,

I checked that with the new flag `$LOCALBUILDDIR/no_logs` (that's to touch the file `no_logs` inside the `/build/` subdirectory, the logs aren't uploaded.

However, this functionality isn't _documented_.
I suggest to add some reference to it in the README.

Regards.
