### ISSUE TITLE
Request: recompile flag.

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#1186]
Hi,

After the insertion of `*_custom.sh` support, it will be interesting to support some _extended_ functions. Yes, I know, this suite isn't created for development, but I can assist.

Now we have the "file flag" `custom_updated` to force to recompile. And this is great, as we can enforce to recompile. However, in some cases it will be interesting to have too:
- `not_reconfigure_and_clean` flag: It will be a complement to `custom_updated` and the objective is to not "reconfigure" and not "clean" after the compilation. So we can call the suite another time and the target package (for example FFmpeg) don't be reconfigured, but it will be recompiled from the last state. Then it will be more simple to apply some new patch (or fix some problem) and recompile without waiting for the entire process.

What you think?

**Comment by wiiaboo** [comment]
Sure, it's a fine idea, as long as it's not a suite option.

**Comment by lars18th** [comment]
> Sure, it's a fine idea, as long as it's not a suite option.

I hope then @1480c1 will like to implement it, as I don't have enough knowledge of the suite's internal logic.

**Comment by 1480c1** [comment]
I can try

**Comment by 1480c1** [comment]
Should the flag be a one time thing only or always there?

**Comment by wiiaboo** [comment]
It should stay there unless you delete all the other suite build files [the already existing option] (or if the custom user manually deletes it to force a reconfigure).
