### ISSUE TITLE
Error when running git upate for vulkan-loader

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1187]
jq: error: select/1 is not defined at <top-level>, line 1:
.repos[] | select(.name == "Vulkan-Headers").commit
jq: 1 compile error
(23) Failed writing body
08:47:07   Running git update for vulkan-headers...
08:47:09 vulkan-headers git ............................... [Up-to-date]
08:47:09   Running git update for vulkan-loader...
08:47:11 ┌ vulkan-loader git ........................ [Recently updated]
08:47:12 ├ Running cmake...
08:47:16 ├ Running make...
Likely error:
../loader/vk_loader_platform.h:273:14: warning: 'loader_platform_basename' defined but not used [-Wunused-function]
 static char *loader_platform_basename(char *pathname) {
              ^~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:238:13: warning: 'loader_platform_is_path_absolute' defined but not used [-Wunused-function]
 static bool loader_platform_is_path_absolute(const char *path) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:231:13: warning: 'loader_platform_file_exists' defined but not used [-Wunused-function]
 static bool loader_platform_file_exists(const char *path) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
make failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
08:47:19   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zcn3.zip
Copy and paste [logs.zip](https://0x0.st/zcn3.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
does this https://github.com/jb-alvarado/media-autobuild_suite/pull/1184 solve your porblem?

**Comment by 1480c1** [comment]
Please try to update the suite and recompile

**Comment by wiiaboo** [comment]
Can't reproduce the issue.
