### ISSUE TITLE
ffmpeg fails with new decklink 11.1 sdk

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#1188]

**Comment by laurfb** [comment]
Hi.
Patch to use DeckLink SDK 11.1 till is fixed upstream: https://patchwork.ffmpeg.org/patch/12960/raw/
regards,
Laur

**Comment by wiiaboo** [comment]
Isn't that the same patch as in https://github.com/jb-alvarado/media-autobuild_suite/issues/1177#issuecomment-489209049?

**Comment by laurfb** [comment]
Yes.Sent from Mars, on my behalf, by my... Gizmo 😊-------- Original Message --------Subject: Re: [jb-alvarado/media-autobuild_suite] ffmpeg fails with new decklink 11.1 sdk (#1188)From: Ricardo Constantino To: jb-alvarado/media-autobuild_suite CC: laurfb ,Author Isn't that the same patch as in #1177 (comment)?
