### ISSUE TITLE
MPlayer missing libdvdread,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#119]
MPlayer was compiled without libdvdread support.
MPlayer SVN-r37424-4.9.2 (C) 2000-2015 MPlayer Team
ID_EXIT=NONE

will be displayer when trying to play a dvd structure form hdd

-> would be nice if libdvdread could be added to mplayer once again,...

You can easily verify whether libdvdread by calling mplayer and see whether the 'Basic options' contains: 
'dvd://<titleno>  play DVD title from device instead of plain file'

**Comment by wiiaboo** [comment]
Totally forgot about this.
