### ISSUE TITLE
Build Failed, Segmentation fault in xavs @svn checkout

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#120]
I have a fresh setup and he fail 2 times at the same spot.

E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 1762:  3360 Segmentation fault      (Speicherabzug geschrieben) svn checkout --trust-server-cert --non-interactive https://svn.code.sf.net/p/xavs/code/trunk xavs
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 1370: cd: xavs: No such file or directory
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 470: ./configure: No such file or directory
make: *** Keine Regel, um „libxavs.a“ zu erstellen.  Schluss.
install: der Aufruf von stat für „xavs.h“ ist nicht möglich: No such file or directory
install: der Aufruf von stat für „libxavs.a“ ist nicht möglich: No such file or directory
install: der Aufruf von stat für „xavs.pc“ ist nicht möglich: No such file or directory
-------------------------------------------------
Build of xavs failed...
Delete the source folder under '/build' and start again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

[compiler list]
msys2Arch=2
arch=3
free=1
ffmbc=2
vpx=1
x264=1
x265=1
other265=2
flac=1
mediainfo=2
soxB=2
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=2
mp4box=2
mplayer=2
mpv=2
mkv=2
cores=3
deleteSource=1
strip=1
pack=1

**Comment by wiiaboo** [comment]
I can't read German, but I'll assume it's because it's hosted in Sourceforge. Everything hosted in SF is having hosting problems, so either disable xavs or just wait.

**Comment by wiiaboo** [comment]
68ae68d207da95a3e6e460096c25e47933516639 fixes it, if you really want xavs.

I'm not doing this with the others that use Sourceforge for now. If SF is getting ready to die, it won't just stay offline.

**Comment by nille02** [comment]
Thanks for this. I choose the pragmatic path and disable it in the default options.
