### ISSUE TITLE
Custom patches for mpv

### ISSUE THREAD

**Issue by rld243** [jb-alvarado/media-autobuild_suite#1200]
How do I apply patches for mpv? I don't see any supported commands (do_autoreconf, do_configure etc.) in the whole mpv building process so I can't make mpv_extra.sh like this: 
```
_pre_configure(){
    do_patch "https://patch-diff.githubusercontent.com/raw/mpv-player/mpv/pull/5411.patch" am
}
```

**Comment by 1480c1** [comment]
I guess I need to add specific hooks for that. Please wait a little bit

**Comment by 1480c1** [comment]
I may have some trouble with it since it uses python waf.
