### ISSUE TITLE
FFmbc build fails - how to contact author?

### ISSUE THREAD

**Issue by BlohoJo** [jb-alvarado/media-autobuild_suite#1202]
This sort of issue has come up before with FFmbc:

#531 <--This one was solved quickly
#959 <--This one wasn't, it appears to be the same issue (??)

I know that FFmbc is not supported, but I'm not sure how issue #531 was resolved, as there are so many clones and code archives of FFmbc on the net, I'm not sure who to contact or where to post the issue, or who the correct author even is. I think [this](https://github.com/bcoudurier/FFmbc) is the correct repository, but it lacks an "Issues" page, there's 278 contributors, there's an e-mail address but it doesn't look like it's for issues, and there's an IRC channel and I can't use IRC.

Here's the fail info:

```
******************************
  32 bit
******************************
┌ FFmbc git ......................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error:
 #define gai_strerror __MINGW_NAME_AW(gai_strerror)

C:/AUDIO_WIP/build/FFmbc-git/libavformat/avio.c: In function 'ffurl_write':
C:/AUDIO_WIP/build/FFmbc-git/libavformat/avio.c:313:38: warning: passing argument 2 of 'retry_transfer_wrapper' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     return retry_transfer_wrapper(h, buf, size, size, (void*)h->prot->url_write);
                                      ^~~
C:/AUDIO_WIP/build/FFmbc-git/libavformat/avio.c:261:19: note: expected 'unsigned char *' but argument is of type 'const unsigned char *'
 static inline int retry_transfer_wrapper(URLContext *h, unsigned char *buf, int size, int size_min,
                   ^~~~~~~~~~~~~~~~~~~~~~
make: *** [/build/FFmbc-git/common.mak:47: libavformat/avio.o] Error 1
make failed. Check C:/AUDIO_WIP/build/FFmbc-git/build-32bit/ab-suite.make.log
This isn't required for anything so we can move on.
install: cannot stat 'ffmbc.exe': No such file or directory
├ /local32/bin-video/ffmbc.exe ................... [Not found]
└ FFmbc-git ................................................... [Failed]

Try deleting '/build/FFmbc-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.


******************************
  64 bit
******************************
┌ FFmbc git ......................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error:
 int poll(struct pollfd *fds, nfds_t numfds, int timeout);
          ~~~~~~~~~~~~~~~^~~
C:/AUDIO_WIP/build/FFmbc-git/libavformat/avio.c: In function 'ffurl_write':
C:/AUDIO_WIP/build/FFmbc-git/libavformat/avio.c:313:38: warning: passing argument 2 of 'retry_transfer_wrapper' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     return retry_transfer_wrapper(h, buf, size, size, (void*)h->prot->url_write);
                                      ^~~
C:/AUDIO_WIP/build/FFmbc-git/libavformat/avio.c:261:72: note: expected 'unsigned char *' but argument is of type 'const unsigned char *'
 static inline int retry_transfer_wrapper(URLContext *h, unsigned char *buf, int size, int size_min,
                                                         ~~~~~~~~~~~~~~~^~~
make: *** [/build/FFmbc-git/common.mak:47: libavformat/avio.o] Error 1
make failed. Check C:/AUDIO_WIP/build/FFmbc-git/build-64bit/ab-suite.make.log
This isn't required for anything so we can move on.
install: cannot stat 'ffmbc.exe': No such file or directory
├ /local64/bin-video/ffmbc.exe ................... [Not found]
└ FFmbc-git ................................................... [Failed]

Try deleting '/build/FFmbc-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.
```

Logs:
[[x64] ab-suite.make.log](https://github.com/jb-alvarado/media-autobuild_suite/files/3164572/x64.ab-suite.make.log)
[[x86] ab-suite.make.log](https://github.com/jb-alvarado/media-autobuild_suite/files/3164573/x86.ab-suite.make.log)

**Comment by 1480c1** [comment]
There does not seems to be a good place other than their irc to contact them.

**Comment by 1480c1** [comment]
This seems to be a conflict between winsock2.h (one of windows headers) and os_support.h from ffmbc about a duplicate struct.

**Comment by BlohoJo** [comment]
Looks like there's a web irc client at https://webchat.freenode.net/... I tried reporting this there. Not sure if it will do any good... #ffmbc channel seems dead. :p

**Comment by BlackScreen** [comment]
I have tried mailing the author at the adress provided here:
https://github.com/bcoudurier/FFmbc/blob/ffmbc/README.md
I mailed him on the 25th of April - but no response since then.

**Comment by 1480c1** [comment]
I have a high suspicion that the author does not want to do anything with it anymore since the last commit was in 2017 and the fact that the page lacks any form of communication other than an irc channel which seems dead and an email which is only for
```
consulting work
commercial support
```

Although he does seem to be somewhat active in ffmpeg with some of his commits in october, 2018

**Comment by BlohoJo** [comment]
I actually do have some utilities (Hybrid is one of them) that use ffmbc, mainly for muxing .ts files since it seems ffmpeg sometimes messes up the framerate when muxing .ts. I've had muxing of 60 fps .ts files mysteriously change to weird numbers like 58.12 or 59.66 when muxing with ffmpeg.

**Comment by wiiaboo** [comment]
Well, have you tried reporting that issue to FFmpeg? At least it's in active development, unlike FFmbc.

**Comment by wiiaboo** [comment]
Also, those numbers changes look like FFmpeg is reporting average fps, instead of a constant fps, which is what you seem to want and should be setting manually, then.
