### ISSUE TITLE
revert ffmpeg commit to fix HLS parsing regression?

### ISSUE THREAD

**Issue by aufkrawall** [jb-alvarado/media-autobuild_suite#1207]
Opening many (any?) HLS links in ffmpeg/mpv is not possible anymore due to a parsing regression.
This bug report mentions the responsible commit:
https://trac.ffmpeg.org/ticket/7871

Would it be possible to implement this by default for the time being? It's been left broken for > 2 weeks already and is quite a showstopper for mpv if you watch HLS a lot.

**Comment by GyanD** [comment]
It has been reverted.
