### ISSUE TITLE
New Mirror and gcc 5.2

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/media-autobuild_suite#121]
In the Mailing List they have post this:
https://github.com/Alexpux/MINGW-packages/issues/702

With this modification the pacman update change gcc to 5.2.

Hopefully it works with our script :).

**Comment by wiiaboo** [comment]
We could try, but it's probably best to wait until they update the scripts globally like they did to add a mirror that didn't use sourceforge.

**Comment by jb-alvarado** [comment]
At the moment I run a test with this. I also update some links, because of the source forge issue.

**Comment by wiiaboo** [comment]
~~I deleted local64 and it compiled fine for me with~~ 
Lol, nothing works now.
Looks like everything needs extra flags to compile statically or something.

**Comment by jb-alvarado** [comment]
really? At the moment it compile the 32 bit Versions, and now I am on mediainfo and beside kvazaar everything has work. I only had change some download links.

**Comment by wiiaboo** [comment]
I tried ffmpeg, mpv and rtmpdump. All require extra .dlls.

**Comment by jb-alvarado** [comment]
Oh, that sounds not good :).

**Comment by wiiaboo** [comment]
If I copy them to /mingw64/usr/bin they work fine.

**Comment by jb-alvarado** [comment]
This path I don't have. You mean the msys2 path? Or the mingw64 path to bin?

**Comment by wiiaboo** [comment]
/mingw64/bin I mean.

**Comment by jb-alvarado** [comment]
rtmpdump 32bit needs here no dll

**Comment by jb-alvarado** [comment]
Have you ran the batchfile, so that it was able to rename the dyn libs?

**Comment by wiiaboo** [comment]
No, just pacman and the .sh, that maybe fixes it, brb.

**Comment by jb-alvarado** [comment]
I think so ;).

**Comment by wiiaboo** [comment]
Hm, I wanted it to not replace the mirrorlist files, but I forgot it extracts the 7zip with the old mirrors. Oh well.

**Comment by jb-alvarado** [comment]
You need the original mirrorlist? 

At the moment it looks like this:
- kvazaar have problems with the source, but I think I have nothing to do with gcc 5.2 (-fPic produce also errors)
- mediainfolib have no GNU folder more, so is only possible to compile over cmake
- mediainfo cli the folder doesn't exist. 
- ffmbc have problems to.

**Comment by wiiaboo** [comment]
No, I wanted to use the new mirrorlist right away.

**Comment by jb-alvarado** [comment]
Ah and libmfx have also problems...

**Comment by wiiaboo** [comment]
Tons of problems. Let's hope they take a while to upgrade to GCC 5.x or else we're going to have to compile our own GCC or something.

**Comment by jb-alvarado** [comment]
Yeah, but some of them have nothing to do with gcc 5.2. Maybe there is a way to specify a version in pacman, and ignore updates?

**Comment by wiiaboo** [comment]
There is, but GCC 5.x comes with a lot of updates. A lot of libs were rebuilt to use GCC 5.x.

**Comment by jb-alvarado** [comment]
Yes that is truth.

**Comment by wiiaboo** [comment]
Two things missing from the new mirror is mingw-*-cloog and mingw-*-winstorecompat.
Pacman says nothing depends on them. Do you know of anything that needs them?

**Comment by jb-alvarado** [comment]
No, not that I know.

**Comment by wiiaboo** [comment]
Oh, seems gcc depends on cloog.

**Comment by jb-alvarado** [comment]
mkvtoolnix with qt5 have also a problem:

```
src/mkvtoolnix-gui/app.cpp:4:24: fatal error: QLocalServer: No such file or directory
compilation terminated.
     CXX src/mkvtoolnix-gui/app.cpp
src/mkvtoolnix-gui/app.cpp:4:24: fatal error: QLocalServer: No such file or directory
compilation terminated.
```

For me we can put it out to, you always get the newest version in the internet, so is not relay necessary.

**Comment by wiiaboo** [comment]
Fine by me, since the developer only really supports the official windows build, it's kind of useless to maintain it ourselves.

**Comment by wiiaboo** [comment]
Btw, mediainfo still has GNU directories in the Git repositores here in Github.

**Comment by jb-alvarado** [comment]
Yes that is true and we save a lot of time.

**Comment by jb-alvarado** [comment]
Can you check please ogg, it always build new and I don't know why.

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/40d848c018407cfb6e1cc9646ff80bcf41d85ad9#diff-f36c7b39d82976860d2ea88d28357632L812
You removed the wrong operator.

**Comment by jb-alvarado** [comment]
For libmfx I got an answer:
https://github.com/lu-zero/mfx_dispatch/issues/15#issuecomment-125321302
Maybe with this it works again.

**Comment by wiiaboo** [comment]
Try it and if it fixes he'll fix it upstream.

**Comment by wiiaboo** [comment]
Only ffmbc left to fix now?

**Comment by jb-alvarado** [comment]
Yes only ffmbc is left. Today I got a error in libass, but maybe they fix it soon. I hope the ffmbc dev people fix that problem. Only for that it makes no sense to compile gcc.

**Comment by wiiaboo** [comment]
What kind of error with libass? It compiles fine here in 64-bits.

**Comment by wiiaboo** [comment]
Also, can you confirm 64-bit ffmbc crashes/segfaults on being used? I actually never used it until now.

**Comment by wiiaboo** [comment]
I can confirm everything compiles fine at 64-bit with GCC 5.2 (without ffmbc).

**Comment by wiiaboo** [comment]
```
C:/builds/gcc52/msys64/mingw32/i686-w64-mingw32/include/io.h: In function '_findfirst64i32':
./libavutil/internal.h:148:17: error: implicit declaration of function 'strncpy_is_forbidden_due_to_security_issues_use_av_strlcpy' [-Werror=implicit-function-declaration]
 #define strncpy strncpy_is_forbidden_due_to_security_issues_use_av_strlcpy
                 ^
```

This is the error the breaks compilation of FFmbc. Not sure how often FFmbc devs fix stuff, but it's probably OK to disable FFmbc until it gets fixed. Maybe warn people before?

Other than this, I think everything is compatible with GCC 5.2, both 32-bit and 64-bit.

**Comment by jb-alvarado** [comment]
I think they fix the code not so fast, maybe we can try to get help somewhere, or we just deactivate it for the first. I can life with that. I have not use it often and when, then it was the 32 bit build.

**Comment by wiiaboo** [comment]
They finally updated SF's database to GCC 5.2, so I guess I'll try once more to see if ffmbc isn't compiled, and if not, disable it.

**Comment by jb-alvarado** [comment]
Yes, sound good to me.

**Comment by wiiaboo** [comment]
FFmbc gone, for now.

Probably a good idea to delete everything in /local* before the upgrade to GCC 5.2, so everything gets recompiled properly.
