### ISSUE TITLE
Compiling redshift fails: undefined reference to `localtime_r'

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#1211]
Reported to https://github.com/jonls/redshift/issues/721

**Comment by wiiaboo** [comment]
It might be a MinGW issue as well.
Try adding `-D_POSIX_C_SOURCE` to CFLAGS of redshift conf/make.

**Comment by BlohoJo** [comment]
I apologize for such a basic comment, but can *someone* ***please*** explain how to do the above? For years I have never been able to figure this out. No matter what I change, when MABS is re-run, it overwrites any changes I've made and continues to fail. That's the one thing about Github that I've never been able to understand.

**Comment by BlohoJo** [comment]
Also, the build fails with the same error on both mingw32 **and** mingw64.

**Comment by wiiaboo** [comment]
Yeah, if it's a MinGW issue it affects both bitness.

**Comment by wiiaboo** [comment]
Wait, why are you using GCC 7.4.0? I can't reproduce the issue here, with 8.3.0.

**Comment by 1480c1** [comment]
I can still repo with 9.1.0

**Comment by LigH-de** [comment]
MSYS2 only ships GCC 7.4.0 with MinGW32, because it fails to compile itself in higher versions.

**Comment by wiiaboo** [comment]
For some reason the update didn't go off, so after updating manually I am now at 9.1.0 as well, and I can reproduce the issue now.

Adding the CFLAG fixed it. According to https://linux.die.net/man/3/localtime_r the flag should've already been added by redshift, since `localtime_r` is only available with it.

**Comment by 1480c1** [comment]
> MSYS2 ships only GCC 7.4.0 with MinGW32, because it fails to compile itself in higher versions. MinGW64 has GCC 8.3.0.

Are you sure? I just installed mingw32's gcc and it shows 9.1.0
```
cddeg@ccom-pc MINGW32 ~
$ /mingw32/bin/gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Barough** [comment]
The MinGW packages have both been updated with GCC 9.1.0

Asked about it over @ MSYS2 and got this reply
'GCC 9.1.0 already in MINGW packages'

No issues at all with compiling 32bit EXE's with GCC 9.1.0

**Comment by LigH-de** [comment]
A quite recent update then... I was not up to date here, @1480c1

**Comment by LigH-de** [comment]
And now redshift doesn't compile anymore for win32, it cannot detect the compiler working correctly.

```
checking for i686-w64-mingw32-gcc... gcc
checking whether the C compiler works... no
configure: error: in `/build/redshift-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
```
configure:3559: checking whether the C compiler works
configure:3581: gcc + -D_POSIX_C_SOURCE -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -pipe -static-libgcc -static-libstdc++ conftest.c  >&5
gcc.exe: error: +: No such file or directory
```
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3240955/logs.zip)

**Comment by schmidthubert** [comment]
There is a typo in the redshift routine:
As in the jq routine it should be
`CFLAGS+=' -D_POSIX_C_SOURCE'`
and NOT
`CFLAGS=+' -D_POSIX_C_SOURCE'`

Probably Ricardo didn't copy and paste it ;)
