### ISSUE TITLE
Completely fails due to key failing to be found on pool.sks-keyservers.net

### ISSUE THREAD

**Issue by BlohoJo** [jb-alvarado/media-autobuild_suite#1215]
```
gpg: error reading key: public key not found
==> ERROR: The fingerprint of a specified key could not be determined.
gpg: requesting key AE4FF531 from hkp server pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
==> ERROR: Remote key not fetched correctly from keyserver.
gpg: error reading key: public key not found
==> ERROR: A specified signature could not be listed.
==> ERROR: AE4FF531 could not be locally signed.
kill: not enough arguments

-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

:: Synchronizing package databases...
 abrepo                    29.0   B  0.00B/s 00:00 [#####################] 100%
 abrepo.sig               566.0   B  0.00B/s 00:00 [#####################] 100%
error: abrepo: key "EFD16019AE4FF531" is unknown
:: Import PGP key 4096R/CB391133DF0BD5BC6AA32CFFEFD16019AE4FF531, "Ricardo Constantino <wiiaboo@gmail.com>", created: 2015-11-05? [Y/n]
error: key "Ricardo Constantino <wiiaboo@gmail.com>" could not be imported
error: failed to update abrepo (invalid or corrupted database (PGP signature))
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
error: failed to synchronize all databases
error: abrepo: key "EFD16019AE4FF531" is unknown
:: Import PGP key 4096R/CB391133DF0BD5BC6AA32CFFEFD16019AE4FF531, "Ricardo Constantino <wiiaboo@gmail.com>", created: 2015-11-05? [Y/n]
```

I can say "Y" at the prompts, but it will keep prompting, and eventually exit out completely failing to build anything, with all errors repeating or varying but always about error: `abrepo: key "EFD16019AE4FF531" is unknown`

Is this a problem with MABS or something else?

As the error says, the key does not appear to be available from the server it's trying to fetch it from:

http://pool.sks-keyservers.net/pks/lookup?search=AE4FF531&fingerprint=on&op=index
http://pool.sks-keyservers.net/pks/lookup?search=EFD16019AE4FF531&fingerprint=on&op=index
http://pool.sks-keyservers.net/pks/lookup?search=CB391133DF0BD5BC6AA32CFFEFD16019AE4FF531&fingerprint=on&op=index
http://pool.sks-keyservers.net/pks/lookup?search=4096R%2FCB391133DF0BD5BC6AA32CFFEFD16019AE4FF531&fingerprint=on&op=index

**Comment by 1480c1** [comment]
As far as I know, that seems to be a sks problem, as I've had times where it works completely fine, and times were I'm unable to connect to sks-keyservers at all.

**Comment by BlohoJo** [comment]
I was able to work around the issue by closing MABS, running mintty, running `pacman-key -r EFD16019AE4FF531; pacman-key --lsign EFD16019AE4FF531`, then re-running MABS.

**Comment by 1480c1** [comment]
Yea, it works if it's manually done, but when automatic, it has a chance to fail.
