### ISSUE TITLE
Build error, ERROR: failed checking for nvcc

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#1216]
Guys, I'm asking help, but something tells that this problem is here in my build.

the logs: https://0x0.st/zaCw.zip

For Information, I have the latest Nvidia Cuda (10.1) and the graphics driver (don't know if does anything, but have)

I only deleted the ffmpeg git, don't if there is something more that I can delete to test

**Comment by 1480c1** [comment]
Do you have nvcc in PATH?

**Comment by 1480c1** [comment]
I have mine in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe`

**Comment by brucedk** [comment]
> I have mine in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe`

Mine is in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe`,

**Comment by 1480c1** [comment]
Are you able to open a command prompt and type `nvcc --help`?

**Comment by brucedk** [comment]
Make an --help and --version
http://0x0.st/zBrz.zip

**Comment by 1480c1** [comment]
Actually, it seems that the problem is `nvcc fatal   : Cannot find compiler 'cl.exe' in PATH`

Do you have any version of VS or the msbuild installed?

**Comment by brucedk** [comment]
I have Community VS 2015 and 2017

**Comment by 1480c1** [comment]
Can you try to find a way to add their cl.exe to PATH?

**Comment by wiiaboo** [comment]
I think the issue is ffmpeg_options.txt with `--enable-cuda-sdk` instead of `--enable-cuda-nvcc`.
Update the suite and try again, I made a commit recently to remove the old option and replace it by cuda-nvcc. Change your ffmpeg_options.txt as well.

**Comment by brucedk** [comment]
@1480c1 @wiiaboo thanks guys, I download the new version and change the  ffmpeg_options.txt, now it works!

**Comment by caio-vinicius** [comment]
For people with problem with NVCC, try to check if CUDA is installed properly. Also, seems like nvcc is not in path, but if you look at `/usr/local/cuda/bin` you can find the binaries related to the Nvidia CUDA Compiler (nvcc).

So, in my Ubuntu 20.04: `export PATH=$PATH:/usr/local/cuda/bin`
