### ISSUE TITLE
libwebp

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#1218]
┌ libwebp git ....................................... [Recently updated]
├ Running autoreconf...
├ Running configure...
Likely error:
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for i686-w64-mingw32-gcc... gcc
checking whether the C compiler works... no
configure: error: in `/build/libwebp-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure failed. Check D:/media-ab_suite/build/libwebp-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zBKz.zip
Copy and paste [logs.zip](https://0x0.st/zBKz.zip) in the GitHub issue.

**Comment by wiiaboo** [comment]
Just add the line `Requires.private: libjpeg liblzma zlib libzstd` somewhere in /local(32|64)/lib/pkgconfig/libtiff-4.pc, ideally before `Libs:` or force a recompilation of libtiff.

**Comment by Barough** [comment]
That worked great. Thnx :)
