### ISSUE TITLE
kvazaar-git doesn't compile right

### ISSUE THREAD

**Issue by gaeldemarseille** [jb-alvarado/media-autobuild_suite#122]
compilation error
______________
Clonage dans 'kvazaar-git'...
remote: Counting objects: 166, done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 166 (delta 43), reused 34 (delta 7), pack-reused 0
Réception d'objets: 100% (166/166), 323.28 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (43/43), fait.
Vérification de la connectivité... fait.
gcc -I/local32/include -mms-bitfields -mthreads -mtune=generic -pipe -O2 -g -Werror -ftree-vectorize -fpic -fvisibility=hidden -std=gnu99 -DKVZ_DLL_EXPORTS -I. -I./strategies -I./extras -I.. -Wall -Wtype-limits -Wvla -m32 -D__USE_MINGW_ANSI_STDIO=1  -MMD -MP -c encmain.c -o encmain.o
gcc -I/local32/include -mms-bitfields -mthreads -mtune=generic -pipe -O2 -g -Werror -ftree-vectorize -fpic -fvisibility=hidden -std=gnu99 -DKVZ_DLL_EXPORTS -I. -I./strategies -I./extras -I.. -Wall -Wtype-limits -Wvla -m32 -D__USE_MINGW_ANSI_STDIO=1  -MMD -MP -c interface_main.c -o interface_main.o
encmain.c:1:0: error: -fpic ignored for target (all code is position independent) [-Werror]
 /*****************************************************************************
 ^
interface_main.c:1:0: error: -fpic ignored for target (all code is position independent) [-Werror]
 /*****************************************************************************
 ^
cc1.exe: all warnings being treated as errors
Makefile:240 : la recette pour la cible « interface_main.o » a échouée
make: *** [interface_main.o] Erreur 1
make: *** Attente des tâches non terminées....
cc1.exe: all warnings being treated as errors
Makefile:240 : la recette pour la cible « encmain.o » a échouée
make: *** [encmain.o] Erreur 1
cp: impossible d'évaluer « kvazaar.exe »: No such file or directory

________
.ini file
________
[compiler list]
msys2Arch=2
arch=1
free=1
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
mplayer=1
mpv=1
cores=2
deleteSource=1
strip=1
pack=2

**Comment by jb-alvarado** [comment]
Yes at the moment the the source code works not for us. Please deactivate it in the ini. We let this Issue here open until it works again.

**Comment by wiiaboo** [comment]
We have to either remove `-Werror` which makes warnings turn into errors or remove `-fpic` because it's always ignored when compiling for Windows. Either way we have to copy Makefile without either and run that Makefile instead.

**Comment by jb-alvarado** [comment]
Yesterday I had try to remove -fpic, but it was not enough.

**Comment by wiiaboo** [comment]
Fixed it for me at least?

**Comment by wiiaboo** [comment]
8143b23bb56b02aa4dffc663bbc9373765f398ae should have fixed the problem.
