### ISSUE TITLE
faac-1_29_9_2 running configure encounter error

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1227]
18:41:47 Installing faac... done
18:41:53 ┌ faac-1_29_9_2 .................................. [Downloaded]
18:41:54 ├ Running extract...
18:41:55 ├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe -DLIBXML_STATIC
LDFLAGS: -pipe -static-libgcc -static-libstdc++
../configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/local64 --disable-shared --enable-static --bindir=/local64/bin-audio
/build/media-suite_helper.sh: line 1210: ../configure: No such file or directory
configure failed. Check C:/mingw/build/faac-1_29_9_2/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
18:41:56   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zMWA.zip
Copy and paste [logs.zip](https://0x0.st/zMWA.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Hey, someone that does compile it. Why faac and not fdk-aac? Or if both, why faac at all?
