### ISSUE TITLE
FFmpeg

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#1228]
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
  444 | static av_always_inline av_const double round(double x)
      |                                         ^~~~~
In file included from D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/libavutil/common.h:36,
                 from D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/compat/w32pthreads.h:43,
                 from D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/libavutil/thread.h:133,
                 from D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/libavdevice/alldevices.c:22:
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/i686-w64-mingw32/include/math.h:1024:25: note: previous declaration of 'round' was here
 1024 |   extern double __cdecl round (double);
      |                         ^~~~~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavdevice/alldevices.o] Error 1
make failed. Check D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zMtu.zip
Copy and paste [logs.zip](https://0x0.st/zMtu.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
`ERROR: cuda requested, but not all dependencies are satisfied: ffnvcodec`
```
D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/libavutil/libm.h:444:41: error: static declaration of 'round' follows non-static declaration
  444 | static av_always_inline av_const double round(double x)
      |                                         ^~~~
```

Could you try deleting ffmpeg-git under the build folder and rerun?

**Comment by Barough** [comment]
Have already tried with deleting the ffmpeg-git folder and that didn't help

**Comment by Barough** [comment]
I removed all Git folders and started over and this time it worked. Must have made 3-4 tries before it finally worked.
