### ISSUE TITLE
list of scripts to download

### ISSUE THREAD

**Issue by Helenerineium** [jb-alvarado/media-autobuild_suite#1232]
https://github.com/jb-alvarado/media-autobuild_suite/blob/3c7b688f4e95e1aaf67b0f321f88ed40f0de7827/media-autobuild_suite.bat#L1417

The logic is broken since #1222 is merged.
It should be `if not exist "%build%\%%s" (`

**Comment by wiiaboo** [comment]
True, you can make a PR then.
