### ISSUE TITLE
TERM

### ISSUE THREAD

**Issue by Helenerineium** [jb-alvarado/media-autobuild_suite#1233]
https://github.com/jb-alvarado/media-autobuild_suite/blob/3c7b688f4e95e1aaf67b0f321f88ed40f0de7827/media-autobuild_suite.bat#L1303

This block will always be skipped since **TERM** is set to "xterm-256color" at the beginning.
At [this time](https://github.com/jb-alvarado/media-autobuild_suite/blob/f1d4b48bfa5bac08f7838e92601f8fccf536fe89/media-autobuild_suite.bat) TERM is not set in the bat.

Either remove that line or change the logic to 
`if not exist "%instdir%\%msys2%\home\%USERNAME%\.minttyrc"`

**Comment by wiiaboo** [comment]
What if the file exists and TERM is not defined in .minttyrc? Won't it be undefined in that case after the `for`?

**Comment by Helenerineium** [comment]
The current issue is if the file does not exist it will not be created.

**Comment by wiiaboo** [comment]
Would undefining it before the check be enough to make sure it works?
