### ISSUE TITLE
Error  Running git clone for libmusicbrainz-missing: LIBXML2_INCLUDE_DIRS

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1237]
03:07:14   Running git clone for libmusicbrainz...
03:07:23 ┌ libmusicbrainz git ....................... [Recently updated]
03:07:23 ├ Running cmake...
Likely error:
CMake Error at C:/mingw/msys64/mingw64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibXml2 (missing: LIBXML2_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/mingw/msys64/mingw64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibXml2.cmake:27 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:35 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "C:/mingw/build/libmusicbrainz-git/build-64bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check C:/mingw/build/libmusicbrainz-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
03:07:35   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zu-N.zip
Copy and paste [logs.zip](https://0x0.st/zu-N.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Update the suite.
