### ISSUE TITLE
ffmpeg doesn't compile with declink enabled

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#124]
Today I noticed that FFmpeg needs a new Declink SDK where a bug was intoduced.
FFmpeg adapted their code to work around this bug so that it wont compile any more with the older Declink SDK.

See commit from FFmpeg : 
http://git.videolan.org/?p=ffmpeg.git;a=commit;h=9c41126e1b9f8c625cba20164ab7d48c075f6923

with comment from FFmpeg: 

avdevice/decklink: Fix build error caused by a change in the SDK.
In version 10.4 of the DeckLink SDK, GetBufferedAudioSampleFrameCount() was changed to take an unsigned int instead of an unsigned long.

**Comment by pat357** [comment]
After rechecking the problem, I've found a solution : all one need is a 'DeckLinkAPIVersion.h' from a pre 10.1.4 Declink SDK version.
This allows FFmpeg to check the API version and do or do not apply their fix.
I've found a "DeckLinkAPIVersion.h" from SDK 10.1.1. Just put these in the same place as the other Declink files (include directory).

I don't know how to attach a small fie here. so I'll paste it here.

Begin=============================================================
/* -LICENSE-START-
 * ** Copyright (c) 2014 Blackmagic Design
 * **
 * ** Permission is hereby granted, free of charge, to any person or organization
 * ** obtaining a copy of the software and accompanying documentation covered by
 * ** this license (the "Software") to use, reproduce, display, distribute,
 * ** execute, and transmit the Software, and to prepare derivative works of the
 * ** Software, and to permit third-parties to whom the Software is furnished to
 * ** do so, all subject to the following:
 * ** 
 * ** The copyright notices in the Software and this entire statement, including
 * ** the above license grant, this restriction and the following disclaimer,
 * ** must be included in all copies of the Software, in whole or in part, and
 * ** all derivative works of the Software, unless such copies or derivative
 * ** works are solely in the form of machine-executable object code generated by
 * ** a source language processor.
 * ** 
 * ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * ** DEALINGS IN THE SOFTWARE.
 * ** -LICENSE-END-
 * */

/* DeckLinkAPIVersion.h */

#ifndef __DeckLink_API_Verison_h__
#define __DeckLink_API_Version_h__

#define BLACKMAGIC_DECKLINK_API_VERSION					0x0a010100
#define BLACKMAGIC_DECKLINK_API_VERSION_STRING			"10.1.1"

#endif	// __DeckLink_API_Version_h__ 
===========================================================================

**Comment by jb-alvarado** [comment]
I have try the new decklink sdk version 10.4.1, but this produce errors. Is the right, that I have to put your *version.h into the include folder with the new sdk files, and it works again?

**Comment by wiiaboo** [comment]
We could take the chance to update the SDK version too. Isn't 10.1.1 kinda old?

**Comment by jb-alvarado** [comment]
Ok Is update to the newest one and it works fine.

**Comment by pat357** [comment]
What worked for me was using the existing files and adding the above quoted "DeckLinkAPIVersion.h" from SDK 10.1.1. This worked fine and ffmpeg build is successful.
I did not use the new SDK because of the mentioned bug.
As for compiling FFmpeg, it probably does not matter which Declink SDK version you use as long as the the right  "DeckLinkAPIVersion.h"  is added.
FFmpeg checks the version from the SDK to see if it should or should not use the bugfix,
That's also the reason why it needs the "DeckLinkAPIVersion.h" : it needs to know the version to know if it should apply the bugfix or not.
As far as FFmpeg, both  the 10.4.1 and 10.1.1 should work.
But what will happen if another app needs/supports  Declink ?
I see no reason to update to a version that contains at least one extra bug !

**Comment by wiiaboo** [comment]
Added https://github.com/jb-alvarado/media-autobuild_suite/wiki/Getting-Decklink-headers too, since I found nowhere on how to create the header files.

**Comment by jb-alvarado** [comment]
Thank you for adding the infos to the wiki, wiiaboo. pat357, does anybody know that this bug affect the daily use? When it makes problems then I will add the old version back to our script.
