### ISSUE TITLE
media autobuild suite is not working

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1240]
After clicking on the .bat file the window appeared and showed "updating pacman database.." then "checking pacman packages..." and finally "updates finished".  The window then closed.  The window appears again and after a few moments later closed instead of continued to compile all the general tools, audio tools and video tools

**Comment by BlackScreen** [comment]
Same problem here. There are two lines of text apperaring very shortly in the window that normally shows the building process - before it abruptly closes. I can't say what stands there. Sorry.

**Comment by laurfb** [comment]
Orphan line.
Delete line 920 in media-suite_compile.sh
Regards,
laur

**Comment by Murmur** [comment]
Same same, but thanks to @laurfb a fix was easy, line 920 had an extra `fi`  (end-of-if) line. Removing that line runs autobuild script.

**Comment by BlackScreen** [comment]
> Orphan line.
> Delete line 920 in media-suite_compile.sh
> Regards,
> laur
Yeah, working. Thanks. But now, meson seems to be broken. See #1241
