### ISSUE TITLE
Build stops at libwebp

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#1243]
08:17:17 ┌ libwebp git .............................. [Recently updated]
Package libjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libjpeg.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libjpeg', required by 'libtiff-4', not found
08:17:18 ├ Running autoreconf...
08:17:54 ├ Running configure...
08:19:09 ├ Running make...
Likely error:
C:/AB-Suite/local64/lib/../lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x59e): undefined reference to `ZSTD_createDStream'
C:/AB-Suite/local64/lib/../lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x5b2): undefined reference to `ZSTD_initDStream'
C:/AB-Suite/local64/lib/../lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x5bd): undefined reference to `ZSTD_isError'
C:/AB-Suite/local64/lib/../lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x600): undefined reference to `ZSTD_getErrorName'
C:/AB-Suite/local64/lib/../lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x668): undefined reference to `ZSTD_maxCLevel'
C:/AB-Suite/local64/lib/../lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x671): undefined reference to `ZSTD_maxCLevel'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:433: get_disto.exe] Error 1
make[1]: Leaving directory '/build/libwebp-git/build-64bit/extras'
make: *** [Makefile:420: all-recursive] Error 1
make failed. Check C:/AB-Suite/build/libwebp-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
08:20:22   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zucM.zip
Copy and paste [logs.zip](https://0x0.st/zucM.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by Helenerineium** [comment]
It looks like you don't have libjpeg-turbo installed.
Try updating the suite and delete libtiff-git and libwebp-git and run again.

**Comment by BlackScreen** [comment]
The suite is on the newest commit. I already tried deleting "libwebp-git".
Now I also tried deleting "libtiff-git". Guess what, it worked.
"libtiff" and "libwebp" were running succesfully.
Hoping, that the suite now runs smoothly until the end. Thanks! 👍
