### ISSUE TITLE
Rust link not work on ReFS in Windows Server 2019.

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1244]
When building in ReFS filesystem it Will shows link error:

Is that a hard link which ReFS not support? I can't find the code.

https://docs.microsoft.com/en-us/windows-server/storage/refs/refs-overview

error log:

> media-autobuild_suite (64bit)
	[311mStarting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat
media-autobuild_suite (64bit): compiling global tools
	[311mStarting 64bit compilation of global tools
[313m10:22:12 ├ Running rustup_update...
Likely error:
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/rustup.exe update
info: syncing channel updates for 'stable-i686-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: checking for self-updates

    stable-i686-pc-windows-gnu unchanged - rustc 1.35.0 (3c235d560 2019-05-20)
  stable-x86_64-pc-windows-gnu unchanged - rustc 1.35.0 (3c235d560 2019-05-20)

error: could not create link from 'E:/Source_Code/media-autobuild_suite/msys64/opt/cargo\bin\rustup.exe' to 'E:/Source_Code/media-autobuild_suite/msys64/opt/cargo\bin\rustfmt.exe'
rustup_update failed. Check E:/Source_Code/media-autobuild_suite/build/ab-suite.rustup_update.log
This is required for other packages, so this script will exit.
[313m10:22:14   Creating diagnostics file...

**Comment by wiiaboo** [comment]
Seems like a rust issue. This is not the right place for it.

**Comment by wiiaboo** [comment]
Also, the suite and most everything depending on msys/cygwin requires hardlink support. It's a requirement that's plainly written in the suite's readme. Make a small NTFS partition if needed.
