### ISSUE TITLE
Error when build libmysofa in mingw64

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1245]
error message: https://0x0.st/zuyz.zip

Since default.sofa is already a symlink.

if I have to copy it to another path I should use the hard link in NTFS.

But I don't know what's going wrong right now.

Line 36 in my cmake_install.cmake is: 

>35  if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
36 file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/libmysofa" TYPE FILE FILES "C:/media-autobuild_suite/build/libmysofa-git/share/default.sofa")
37 endif()

**Comment by wiiaboo** [comment]
There's nothing set in the suite that would enable native symlinks. And even if there were, I can't reproduce the issue both with or without native symlinks.

Try deleting /local64/share/libmysofa and /build/libmysofa-git or try to clarify what's your issue.

**Comment by fuchanghao** [comment]
> 
> 
> There's nothing set in the suite that would enable native symlinks. And even if there were, I can't reproduce the issue both with or without native symlinks.
> 
> Try deleting /local64/share/libmysofa and /build/libmysofa-git or try to clarify what's your issue.

I delete the libmysofa git and anywhere have libmysofa it works now.
