### ISSUE TITLE
ripgrep build error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#1247]
media-autobuild_suite (64bit)
	Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
Imported custom options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
media-autobuild_suite (64bit): compiling global tools
	Starting 64bit compilation of global tools
 ├ Running rustup_update...
 ├ Running set_default_toolchain...
   Running git update for ripgrep...
 ┌ ripgrep git .............................. [Recently updated]
 ├ Running update...
 ├ Running build...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe build --release --target=x86_64-pc-windows-gnu --jobs=4 --features pcre2
 Downloading crates ...
error: failed to download from `https://crates.io/api/v1/crates/num_cpus/1.10.1/download`

Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3287788/logs.zip)

**Comment by wiiaboo** [comment]
Try again later? This doesn't seem like a suite issue.
