### ISSUE TITLE
Issue with build of MediaInfo exe

### ISSUE THREAD

**Issue by uberware** [jb-alvarado/media-autobuild_suite#126]
Git was failing to get the MediaInfo exe. I adjusted the media-suite_compile.sh script at line 1467 to:

    	do_git "https://github.com/MediaArea/MediaInfo" mediainfo noDepth master bin-video/mediainfo.exe

adding "noDepth" and "master" to get the correct parameters to the do_git command. If this is not the correct solution, please let me know. I don't know how to push my change back, but one of the contributors can make this one line change pretty easily. Thank you,

**Comment by jb-alvarado** [comment]
Thank you, I had this change somewhere but maybe I have not push it :). I will fix that.

**Comment by jb-alvarado** [comment]
Have you the newest script? Because there is the line:
`do_git "https://github.com/MediaArea/MediaInfo" mediainfo shallow master bin-video/mediainfo.exe`

**Comment by wiiaboo** [comment]
Did you have an older version than https://github.com/jb-alvarado/media-autobuild_suite/commit/5baf4da9886d694b2a6355b6ddb7ec06ebedc023 ? It should have fixed it.

**Comment by uberware** [comment]
I had downloaded the package instead of using git to get it. I'm in the middle of a build right now but I will try to update after this attempt before starting again. Thank you for the input.
