### ISSUE TITLE
[mingw64] can't build mpv

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1265]
It works fine yesterday And I don't know what's wrong right now.

(tried delete and rebuild still the same error.)

error log:https://0x0.st/z2pt.zip

my mpv_options.txt

> # Lines starting with this character are ignored
> 
> # Built-in options, use --disable- to disable them
> #--enable-cplayer
> --enable-manpage-build
> --enable-lua
> --enable-javascript
> --enable-libass
> --enable-libbluray
> --enable-uchardet
> --enable-rubberband
> --enable-lcms2
> --enable-libarchive
> --enable-libavdevice
> --enable-shaderc
> --enable-spirv-cross
> --enable-d3d11
> --enable-jpeg
> 
> # Common options or overriden defaults
> --disable-debug-build
> --lua=luajit
> 
> # Full
> --enable-dvdread
> --enable-dvdnav
> --enable-cdda
> --enable-egl-angle
> --enable-vapoursynth
> --enable-html-build
> --enable-pdf-build
> --enable-libmpv-shared
>

**Comment by 1480c1** [comment]
```
[ 33/480] Compiling video/out/vo_null.c
Traceback (most recent call last):
  File "C:\media-autobuild_suite\msys64\mingw64\bin\rst2pdf2-script.py", line 11, in <module>
    load_entry_point('rst2pdf==0.93.dev0', 'console_scripts', 'rst2pdf')()
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 85, in <module>
    from rst2pdf import flowables
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python2.7/site-packages/rst2pdf/flowables.py", line 875, in <module>
    if reportlab.Version == '2.1':
NameError: name 'reportlab' is not defined
```

**Comment by pat357** [comment]
It's probably due the recent update of **mingw-w64-i686-python2-reportlab** that the build fails.

In case you didn't know, it's **only building the pdf documentation that fails**, not the MPV app itself.

Just replace 
```
--enable-pdf-build
```
by
```
--disable-pdf-build
```
and MPV will build just fine.

**Comment by fuchanghao** [comment]
New error: https://0x0.st/z27F.zip

FFMPEG not found. Too strange.

Since I build the FFmpeg with --enable-libsvthevc it tell me like this.


> [313m10:01:52 ┌ mpv git ................................ [[311mNewer dependencies]
> [313m10:01:52 ├ Running bootstrap...
> cygpath: cannot create short name of C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\10.1
> cygpath: cannot create short name of C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\10.1
> [313m10:01:58 ├ Running configure...
> Likely error:
> Checking for MALI via Linux fbdev                                    : no 
> Checking for OpenGL context support                                  : yes 
> Checking for libplacebo support                                      : yes 
> Checking for Vulkan context support                                  : yes 
> Checking for EGL helper functions                                    : yes 
> Checking for FFmpeg/Libav present                                    : yes 
> Checking for libav* is FFmpeg                                        : no 
> Checking for libav* is Libav                                         : no 
> Checking for Libav/FFmpeg library versions                           : ffmpeg not found 
> Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
> configure failed. Check C:/media-autobuild_suite/build/mpv-git/ab-suite.configure.log
> This is required for other packages, so this script will exit.

**Comment by fuchanghao** [comment]
> [313m10:01:52 ┌ mpv git ................................ [[311mNewer dependencies]> [313m10:01:52 ├ Running bootstrap...> cygpath: cannot create short name of C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\10.1> cygpath: cannot create short name of C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\10.1> [313m10:01:58 ├ Running configure...> Likely error:> Checking for MALI via Linux fbdev                                    : no > Checking for OpenGL context support                                  : yes > Checking for libplacebo support                                      : yes > Checking for Vulkan context support                                  : yes > Checking for EGL helper functions                                    : yes > Checking for FFmpeg/Libav present                                    : yes > Checking for libav* is FFmpeg                                        : no > Checking for libav* is Libav                                         : no > Checking for Libav/FFmpeg library versions                           : ffmpeg not found > Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.> configure failed. Check C:/media-autobuild_suite/build/mpv-git/ab-suite.configure.log> This is required for other packages, so this script will exit.

**Comment by fzold** [comment]
--enable-pdf-build
Replace the folder \msys64\mingw64\lib\python2.7\site-packages\reportlab with content from old version 3.5.13.
Don't touch  reportlab-3.5.23-py2.7.egg-info  to prevent update.

Now mpv and  pdf generation work again.
