### ISSUE TITLE
Build error, Meson version mismatch.

### ISSUE THREAD

**Issue by MemmoB** [jb-alvarado/media-autobuild_suite#1266]
Building on Windows 10:
08:05:09 ┌ dav1d git ................................ [Recently updated]
08:05:10 ├ Running meson...
Likely error:
meson .. --default-library=static --buildtype=release --prefix=/local64 --backend=ninja --bindir=bin-video -Dbuild_tests=false -Dbuild_tools=false
The Meson build system
Version: 0.46.1
Source dir: C:/Users/mehboz01/work/media-autobuild_suite/build/dav1d-git
Build dir: C:/Users/mehboz01/work/media-autobuild_suite/build/dav1d-git/build-64bit
Build type: native build

meson.build:25:0: ERROR:  Meson version is 0.46.1 but project requires >= 0.47.0.

Logs at: https://0x0.st/z2fA.zip

I have tried re-starting the build a couple of times.

**Comment by 1480c1** [comment]
open the mintty shell and type meson --version

**Comment by 1480c1** [comment]
It seems you are unable to update properly, try deleting the msys64 folder if you are unsure if you can fix it manually

**Comment by MemmoB** [comment]
Thanks it worked!
