### ISSUE TITLE
Request: How to adhoc build a specific GPAC branch using this suite environment?

### ISSUE THREAD

**Issue by Murmur** [jb-alvarado/media-autobuild_suite#1270]
This suite makes it so easy to compile ffmpeg,mp4box and various tools in Windows for Windows. Today I have a need to compile a specific GPAC 0.9.x branch for testing.

**Branch: filters**
```
cd /build_custom
git clone --depth 1 --branch filters "https://github.com/gpac/gpac.git"
```

Is there an easy way to use this mintty console(mingw64bit) to compile this branch without breaking the default autosuite build process and executable to a new folder?

I think this need some extra understanding how this msys2+suite environment is setup in order to compile an adhoc app folder? I tried to follow gpac build documentation but `./configure, ./make` did a lot of errors. I tried "everything" so would appreciate some instructions how to run an adhoc need. 

```
CFLAGS+=" -I/local64/include -I/mingw64/include" \
CFLAGS+=" -I/build_custom/gpac/extra_lib/include" \
LDFLAGS+=" -L/build_custom/lib -L/mingw64/lib" \
../configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 \
  --prefix=/build_custom --disable-shared --enable-static --static-mp4box --use-zlib=no \
  --bindir=/build_custom/bin-video

CFLAGS+=" -I/local64/include -I/mingw64/include" \
CFLAGS+=" -I/build_custom/gpac/extra_lib/include" \
LDFLAGS+=" -L/build_custom/lib -L/mingw64/lib" \
make
```

**Comment by wiiaboo** [comment]
Try reading/using https://github.com/jb-alvarado/media-autobuild_suite#custom-patches first.
What do you mean by ad-hoc? The suite already builds the executable, even with standalone=n.

**Comment by Murmur** [comment]
Thanks, will study custom-patches info. Adhoc meaning was I want to keep an existing `/build/gpac-git` and `/local64/bin-video/mp4box.exe` as is but build an additional `gpac-git+mp4box.exe` from the filters branch. Best if I could launch a script individually without building everything else. 

Gpac 0.9.x has a lot of fundamental changes.

**Comment by Murmur** [comment]
Must really be something new in GPAC#filters branch. I did a testrun with the existing 0.8.x master trunk sources. I was able to compile gpac sources.
```
cd /build_custom
##git clone --depth 1 --branch filters "https://github.com/gpac/gpac.git" gpac-git
git clone --depth 1  "https://github.com/gpac/gpac.git" gpac-git
## must export var so cygpath cmd works inside compile.sh+source profile2.local scripting
export MSYS2_PATH
## use profile vars LOCALBUILDDIR=/build_custom and LOCALDESTDIR=/build_custom
## in a custom profile /build_custom/profile2.local 
## I customized this script removing everything but gpac block
./media-suite_compile.sh
```

**Comment by Murmur** [comment]
Sort of fixed for my adhoc need.
Copied `/local64/include/libavcodec,libavdevice,libavfilter,libavformat,libavutil,libswresample,libswscale` folders to `/build_custom/include/` folder.
Copied `/local64/lib/libavcodec.dll.a,libavdevice.dll.a,libavfilter.dll.a,libavformat.dll.a,libavutil.dll.a,libswresample.dll.a,libswscale.dll.a` files to `/build_custom/lib/` folder.
Copied `/local64/lib/pkgconfig/libavXXXX.pc` similar files to `/build_custom/lib/pkgconfig/` folder.
Run mintty console and run my custom `export MSYS2_PATH && /build_custom/media-suite_compile.sh` script.
Go to `cd /build_custom/gpac-git/build-64bit/applications/mp4box` folder and run `make all` script.

Binary is compiled to `\projects\media-autobuild_suite\media-autobuild_suite\build_custom\gpac-git\build-64bit\bin\gcc\MP4Box.exe` file. Next step is to try new features but it's not a buildsuite concern.

**Comment by wiiaboo** [comment]
Setting LDFLAGS and CFLAGS/CXXFLAGS to include the suite directories should be enough, you shouldn't need to copy the libs/includes.

**Comment by Murmur** [comment]
I think am having missing piece of knowledge how suite scripts run `configure+make` tools. I am unable to make this work without copying to my new `/build_custom/` destination folder. I always get a compilation error `C:/media-autobuild_suite/build_custom/gpac-git/src/filters/ff_common.h:30:10: fatal error: libavformat/avformat.h: No such file or directory 30 | #include <libavformat/avformat.h` 

I tried even this but no luck. 
```
# SUITEDESTDIR is "`cygpath -m /local64`" in a custom profile2.local var script.
if [[ $mp4box = "y" ]]; then
    cd_safe "$LOCALBUILDDIR/gpac-git"
    do_uninstall include/gpac "${_check[@]}"
    git grep -PIl "\xC2\xA0" | xargs -r sed -i 's/\xC2\xA0/ /g'
    LDFLAGS+=" -L$LOCALDESTDIR/lib -L$MINGW_PREFIX/lib -L$SUITEDESTDIR/lib -L/local64/lib" \
	CFLAGS+=" -I$SUITEDESTDIR/include -I/local64/include" \
	CXXFLAGS+=" -I$SUITEDESTDIR/include -I/local64/include" \
	CPPFLAGS+=" -I$SUITEDESTDIR/include -I/local64/include" \
        do_separate_conf --static-mp4box
    LDFLAGS+=" -L$LOCALDESTDIR/lib -L$MINGW_PREFIX/lib -L$SUITEDESTDIR/lib -L/local64/lib" \
	CFLAGS+=" -I$SUITEDESTDIR/include -I/local64/include" \
	CXXFLAGS+=" -I$SUITEDESTDIR/include -I/local64/include" \
	CPPFLAGS+=" -I$SUITEDESTDIR/include -I/local64/include" \
        do_make
    log "install" make install-lib
    do_install bin/gcc/MP4Box.exe bin-video/
    do_checkIfExist
	cd_safe "$LOCALBUILDDIR"
fi
```
