### ISSUE TITLE
Error when running git update for vulkan-loader...ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1274]
16:25:44   Running git update for vulkan-loader...
16:25:48 ┌ vulkan-loader git ........................... [Updates found]
16:25:48 ├ Running uninstall...
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch couldn't be applied with 'patch'. Continuing without patching.
16:25:49 ├ Running dependencies...
16:26:03 ├ Running uninstall...
16:26:03 ├ Running cmake...
16:26:04 ├ Running build...
16:26:04 ├ Running install...
16:26:04 └ vulkan-loader-git ................................. [Updated]
16:26:04 ├ Running cmake...
16:26:10 ├ Running make...
Likely error:
../loader/vk_loader_platform.h:358:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  358 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:349:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  349 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:273:14: warning: 'loader_platform_basename' defined but not used [-Wunused-function]
  273 | static char *loader_platform_basename(char *pathname) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
make failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
16:26:16   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zL8n.zip
Copy and paste [logs.zip](https://0x0.st/zL8n.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by pat357** [comment]
Reading from your log:
```
vulkan-0001-cross-compile-static-linking-hacks.patch
Patch couldn't be applied with 'patch'. Continuing without patching.
```
This means the needed patches to allow static linking were not applied.
Patch probably needs to be updated before it can work.

My last working commit is 42d8e9611 :
replace in media-suite_compile the following line:

do_vcs "https://github.com/KhronosGroup/Vulkan-Loader.git" vulkan-loader; then
by
do_vcs "https://github.com/KhronosGroup/Vulkan-Loader.git#commit=42d8e9611" vulkan-loader; then

This will allow you to build Vulkan again for the moment.

**Comment by ycwan** [comment]
Hi, pat357

I have replaced the line but the same error occurred and now "vulkan-loader git ........................... [Files missing]" 

10:48:08   Running git update for vulkan-loader...
10:48:09 ┌ vulkan-loader git ........................... [**Files missing**]
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch couldn't be applied with 'patch'. Continuing without patching.
10:48:10 ├ Running dependencies...
10:48:18 ├ Running uninstall...
10:48:18 ├ Running cmake...
10:48:19 ├ Running build...
10:48:19 ├ Running install...
10:48:19 └ vulkan-loader-git ................................. [Updated]
10:48:19 ├ Running cmake...
10:48:25 ├ Running make...
Likely error:
../loader/vk_loader_platform.h:358:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  358 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:349:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  349 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:273:14: warning: 'loader_platform_basename' defined but not used [-Wunused-function]
  273 | static char *loader_platform_basename(char *pathname) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
make failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
10:48:29   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zLAF.zip
Copy and paste [logs.zip](https://0x0.st/zLAF.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Patch has been rebased upstream.
