### ISSUE TITLE
Patch not found anywhere: when using do_patch with patchwork

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#1276]
Hi,

I'm using `ffmpeg_extra.sh` with a custom `_pre_configure()`:
```
#!/bin/bash

touch custom_updated

_pre_configure(){
    do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/" am
    FFMPEG_OPTS+=(--enable-cuda --enable-cuda-nvcc)
}
```
And the `do_patch` is **exactly** the same as described in the README.TXT (I use this onle only for testing). However, it doesn't work!
The file `ab-suite.pre_configure.log` indicates:
```
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
_pre_configure 
[93m(B[m
	Patch not found anywhere. Continuing without patching.
```
The same if I use any other mbox from the Patchwork repository.
However, if I download the `.diff` manually and I use the local file with the `do_patch` then it works.
Please, can you fix the problem?
Thank you!

**Comment by wiiaboo** [comment]
Try naming the patch: `do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/ svt-patch.patch" am` and also running it on its own in mintty, in ffmpeg's directory. Those patchwork /-ending patches are usually broken with `do_patch` so they require their own custom filename.

**Comment by lars18th** [comment]
> Try naming the patch: `do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/ svt-patch.patch" am` and also running it on its own in mintty, in ffmpeg's directory. Those patchwork /-ending patches are usually broken with `do_patch` so they require their own custom filename.

Hi @wiiaboo ,

Thank for the tip, it seems to work. However...
1. If it's **mandatory** to include a download name for the patch, why this isn't documented? See line 335: https://github.com/jb-alvarado/media-autobuild_suite/blob/master/README.md#335
2. I feel the used name is irrelevant. So why not update the source code to auto-include some temporal auto-assigned name?

Thank you for this useful suite!
Regads.

**Comment by wiiaboo** [comment]
It's not mandatory for the suite, it's mandatory especifically because patchwork links don't have a filename. It's an unfixable issue that you'd get if you called `curl -O https://patchwork.ffmpeg.org/patch/12563/mbox/` as well.

**Comment by wiiaboo** [comment]
You'd need the additional `-J/--remote-file-name` flag in curl, which we can't use as that only works with `-O`.

**Comment by lars18th** [comment]
Please @wiiaboo , merge this PR: https://github.com/jb-alvarado/media-autobuild_suite/pull/1278

I understand _all_ you comment here. And I accept that's complex to fix it. No problem at all from my point of view. But, to provide UP-TO-DATE documentation is a must have!

Regards. :wink:

**Comment by wiiaboo** [comment]
Why are talking in three different threads about the same thing that's already fixed? Stop spamming everywhere with that same fucking issue.
