### ISSUE TITLE
skip the asking about new updates

### ISSUE THREAD

**Issue by ksfalcon** [jb-alvarado/media-autobuild_suite#128]
Log:
```
Would you like to run compilation again to get those updates? Default: no
y/[n] -------------------------------------------------------------------------------

-------------------------------------------------------------------------------

Stripping binaries and libs... done!

-------------------------------------------------------------------------------
```
I think this should resolve the issue:
```
read -t 1 discard
read -p "y/[n] " ret
```
Please fix it, thanks!
Another issue, can you add libwebp?

**Comment by wiiaboo** [comment]
1 second is kinda fast, lol.
I assume most people running this long script aren't exactly looking at when it's finishing.
I thought of adding timeout at the time I added this, can't remember why I didn't. Probably because the rest of the script doesn't take that long (stripping/packing), compared to running it again.

What's the problem in waiting at most half a minute for it to finish?

**Comment by wiiaboo** [comment]
Re: libwebp
do you need the programs too or just the lib is enough?

**Comment by wiiaboo** [comment]
Wait, lol, you were the same one who asked for the "new updates" prompt. Are you sure one second is enough?

**Comment by ksfalcon** [comment]
I just need the lib.
If I press a keyboard key when the compiling, then the asking will get this wrong values from the buffer. How many seconds does not matter, I just need to clear the buffer.

**Comment by ksfalcon** [comment]
test
```
run_builds() {    
    echo run_builds
}

delay(){
    echo please wait...
    for((i=0;i<=20;i++))
    do
        echo -n " $i"
        sleep 0.1        
    done
    echo
}

while true; do
    delay
    ret="no"
    read -t 0.1 discard
    read -p "y/[n] " ret
    echo ret: $ret
    [[ $ret = "y" || $ret = "Y" || $ret = "yes" ]] && run_builds || break
    echo
done

read -t 0.1 discard
read -p "Press [Enter] key to start backup..."
```
If I press the Enter key  by mistake:
```
please wait...
 0 1 2 3 4 5 6 7 8 9 10
 11 12 13 14 15 16 17 18 19 20
y/[n] y
ret: y
run_builds

please wait...
 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
y/[n]
```
Press the Enter key twice by mistake:
```
please wait...
 0 1 2 3
 4 5 6 7 8
 9 10 11 12 13 14 15 16 17 18 19 20
y/[n] ret:
Press [Enter] key to start backup...
```
This does not seem a good solution.
