### ISSUE TITLE
ffmpeg librav1e patch fails after using libhevc&vapoursynth patch

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1280]
error log: https://0x0.st/zLRb.zip

patch error message:

> git.exe am --3way --ignore-space-change --keep-cr "C:\media-autobuild_suite\build\ffmpeg-git\FFmpeg-devel-PATCHv4-avcodec-Add-librav1e-encoder.patch"
> Applying: avcodec: Add librav1e encoder
> Using index info to reconstruct a base tree...
> M	configure
> M	doc/encoders.texi
> M	doc/general.texi
> M	libavcodec/Makefile
> M	libavcodec/allcodecs.c
> Falling back to patching base and 3-way merge...
> Auto-merging libavcodec/allcodecs.c
> Auto-merging libavcodec/Makefile
> Auto-merging doc/general.texi
> CONFLICT (content): Merge conflict in doc/general.texi
> Auto-merging doc/encoders.texi
> Auto-merging configure
> Patch failed at 0001 avcodec: Add librav1e encoder
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> 
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch' to see the failed patch

**Comment by wiiaboo** [comment]
Should be fixed. For reason I think I remember this having worked yesterday.
