### ISSUE TITLE
Update stuck at vulkan loader

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1285]
14:09:20   Running git update for vulkan-loader...
14:09:26 ┌ vulkan-loader git ........................... [Files missing]
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch couldn't be applied with 'patch'. Continuing without patching.
14:09:28 ├ Running dependencies...
14:09:47 ├ Running uninstall...
14:09:48 ├ Running cmake...
14:09:49 ├ Running build...
14:09:49 ├ Running install...
14:09:50 └ vulkan-loader-git ................................. [Updated]
14:09:51 ├ Running cmake...
14:10:04 ├ Running make...
Likely error:
../loader/vk_loader_platform.h:358:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  358 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:349:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  349 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:273:14: warning: 'loader_platform_basename' defined but not used [-Wunused-function]
  273 | static char *loader_platform_basename(char *pathname) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
make failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
14:10:10   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zpoo.zip
Copy and paste [logs.zip](https://0x0.st/zpoo.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
6bbe7a3
