### ISSUE TITLE
[mingw64] ffmpeg not found when build mpv

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1286]
Now it works fine with vulkan loader.

But now fails in mpv build.

ffmpeg both share and static build works.

error log: https://0x0.st/zpcL.zip

>  [313m04:14:56(B[m [1m┌ mpv git (B[m.................................. [[311mRecently updated(B[m]
> [313m04:14:57(B[m [1m├(B[m Running bootstrap...
> cygpath: cannot create short name of C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\10.1
> cygpath: cannot create short name of C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\10.1
> [313m04:15:05(B[m [1m├(B[m Running configure...
> Likely error:
> Checking for OpenGL context support                                  : yes 
> Checking for libplacebo support                                      : yes 
> Checking for Vulkan context support                                  : yes 
> Checking for VAAPI Vulkan                                            : vaapi not found 
> Checking for EGL helper functions                                    : yes 
> Checking for FFmpeg/Libav present                                    : yes 
> Checking for libav* is FFmpeg                                        : no 
> Checking for libav* is Libav                                         : no 
> Checking for Libav/FFmpeg library versions                           : ffmpeg not found 
> Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
> [31mconfigure failed. Check C:/media-autobuild_suite/build/mpv-git/ab-suite.configure.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [313m04:16:01(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/zpcL.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/zpcL.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

ffmpeg options:

> # Lines starting with this character are ignored
> 
> # Basic built-in options, can be removed if you delete "--disable-autodetect"
> --disable-autodetect
> --enable-amf
> --enable-bzlib
> --enable-cuda
> --enable-cuvid
> --enable-d3d11va
> --enable-dxva2
> --enable-iconv
> --enable-lzma
> --enable-nvenc
> --enable-schannel
> --enable-zlib
> --enable-sdl2
> --disable-debug
> --enable-ffnvcodec
> --enable-nvdec
> 
> # Common options
> --enable-gmp
> --enable-libmp3lame
> --enable-libopus
> --enable-libvorbis
> --enable-libvpx
> --enable-libx264
> --enable-libx265
> --enable-libdav1d
> 
> # Zeranoe
> --enable-fontconfig
> --enable-gnutls
> --enable-libass
> --enable-libbluray
> --enable-libfreetype
> --enable-libmfx
> --enable-libmysofa
> --enable-libopencore-amrnb
> --enable-libopencore-amrwb
> --enable-libopenjpeg
> --enable-libsnappy
> --enable-libsoxr
> --enable-libspeex
> --enable-libtheora
> --enable-libtwolame
> --enable-libvidstab
> --enable-libvo-amrwbenc
> --enable-libwavpack
> --enable-libwebp
> --enable-libxml2
> --enable-libzimg
> --enable-libshine
> --enable-gpl
> --enable-openssl
> --enable-libtls
> --enable-avisynth
> --enable-mbedtls
> --enable-libxvid
> --enable-libaom
> --enable-libopenmpt
> --enable-version3
> 
> # Full
> --enable-chromaprint
> --enable-cuda-nvcc
> --enable-decklink
> --enable-frei0r
> --enable-libbs2b
> --enable-libcaca
> --enable-libcdio
> --enable-libfdk-aac
> --enable-libflite
> --enable-libfribidi
> --enable-libgme
> --enable-libgsm
> --enable-libilbc
> --enable-libkvazaar
> --enable-libmodplug
> --enable-libnpp
> --enable-libopenh264
> --enable-librtmp
> --enable-librubberband
> --enable-libssh
> --enable-libtesseract
> --enable-libxavs
> --enable-libzmq
> --enable-libzvbi
> --enable-opencl
> --enable-opengl
> --enable-libvmaf
> --enable-libcodec2
> --enable-libsrt
> --enable-ladspa
> --enable-vapoursynth
> --enable-libsvthevc
> #--enable-librav1e
> #--enable-liblensfun

mpv opitions:

> # Lines starting with this character are ignored
> 
> # Built-in options, use --disable- to disable them
> #--enable-cplayer
> --enable-manpage-build
> --enable-lua
> --enable-javascript
> --enable-libass
> --enable-libbluray
> --enable-uchardet
> --enable-rubberband
> --enable-lcms2
> --enable-libarchive
> --enable-libavdevice
> --enable-shaderc
> --enable-spirv-cross
> --enable-d3d11
> --enable-jpeg
> 
> # Common options or overriden defaults
> --disable-debug-build
> --lua=luajit
> 
> # Full
> --enable-dvdread
> --enable-dvdnav
> --enable-cdda
> --enable-egl-angle
> --enable-vapoursynth
> --enable-html-build
> #--enable-pdf-build
> --disable-pdf-build
> --enable-libmpv-shared

**Comment by wiiaboo** [comment]
`cannot find -lSvtHevcEnc`. Check if the library has the same capitalization. If not, either change libav*.pc files to have all-lowercase name for this lib or try renaming the file to have the same capitalization.

**Comment by fuchanghao** [comment]
pkg-config --libs SvtHevcEnc
-LC:/media-autobuild_suite/local64/lib -lSvtHevcEnc

Is that means found or not found?

About libav*.pc files they are all have all-lowercase name.

libavcodec.pc

> prefix=/local64
> exec_prefix=${prefix}
> libdir=/local64/lib
> includedir=/local64/include
> 
> Name: libavcodec
> Description: FFmpeg codec library
> Version: 58.55.100
> Requires: libswresample >= 3.6.100, libavutil >= 56.32.100
> Requires.private: 
> Conflicts:
> Libs: -L${libdir}  -lavcodec -LC:/media-autobuild_suite/local64/lib -lvpx -lm -lpthread -LC:/media-autobuild_suite/local64/lib -lvpx -lm -lpthread -LC:/media-autobuild_suite/local64/lib -lvpx -lm -lpthread -LC:/media-autobuild_suite/local64/lib -lvpx -lm -lpthread -LC:/media-autobuild_suite/local64/lib -lwebpmux -lm -lwebp -lm -pthread -lm -llzma -LC:/media-autobuild_suite/local64/lib -ldav1d -lopencore-amrwb -LC:/media-autobuild_suite/local64/lib -lzvbi -lm -lpthread -lm -liconv -lpng -lz -lsnappy -lstdc++ -LC:/media-autobuild_suite/msys64/mingw64/lib -lz -LC:/media-autobuild_suite/local64/lib -laom -lm -lpthread -lcodec2 -LC:/media-autobuild_suite/local64/lib -lfdk-aac -lgsm -lilbc -pthread -lmp3lame -lm -lopencore-amrnb -LC:/media-autobuild_suite/msys64/mingw64/lib -lopenjp2 -lm -LC:/media-autobuild_suite/local64/lib -lopus -lm -LC:/media-autobuild_suite/local64/lib -lm -lshine -LC:/media-autobuild_suite/msys64/mingw64/lib -lspeex -lm -LC:/media-autobuild_suite/local64/lib -lSvtHevcEnc -ltheoraenc -ltheoradec -logg -ltwolame -lvo-amrwbenc -LC:/media-autobuild_suite/msys64/mingw64/lib -lvorbis -lm -logg -LC:/media-autobuild_suite/msys64/mingw64/lib -lvorbisenc -lvorbis -lm -logg -lwavpack -LC:/media-autobuild_suite/local64/lib -lwebp -lm -LC:/media-autobuild_suite/local64/lib -lx264 -LC:/media-autobuild_suite/local64/lib -lx265 -lstdc++ -lgcc -lxavs -pthread -lm -lxvidcore -LC:/media-autobuild_suite/msys64/mingw64/lib -lopenh264 -lstdc++ -LC:/media-autobuild_suite/local64/lib -lkvazaar -lpthread -lole32 -luser32 -ldl -LC:/media-autobuild_suite/local64/lib -lmfx -lstdc++
> Libs.private: 
> Cflags: -I${includedir}

libavdevice.pc

> prefix=/local64
> exec_prefix=${prefix}
> libdir=/local64/lib
> includedir=/local64/include
> 
> Name: libavdevice
> Description: FFmpeg device handling library
> Version: 58.9.100
> Requires: libavfilter >= 7.58.100, libswscale >= 5.6.100, libpostproc >= 55.6.100, libavformat >= 58.30.100, libavcodec >= 58.55.100, libswresample >= 3.6.100, libavutil >= 56.32.100
> Requires.private: 
> Conflicts:
> Libs: -L${libdir}  -lavdevice -lstdc++ -lole32 -loleaut32 -lpsapi -lole32 -lstrmiids -luuid -loleaut32 -lshlwapi -lgdi32 -lstdc++ -lole32 -loleaut32 -lm -lvfw32 -LC:/media-autobuild_suite/msys64/mingw64/lib -lcdio_paranoia -lcdio_cdda -lcdio -lm -lwinmm -liconv -LC:/media-autobuild_suite/msys64/mingw64/lib -lcaca -lz -lopengl32 -lgdi32 -LC:/media-autobuild_suite/local64/lib -lmingw32 -lSDL2main -lSDL2 -lmingw32 -lSDL2main -lSDL2 -Wl,--no-undefined -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -static-libgcc -ldl
> Libs.private: 
> Cflags: -I${includedir}

libavfilter.pc

> prefix=/local64
> exec_prefix=${prefix}
> libdir=/local64/lib
> includedir=/local64/include
> 
> Name: libavfilter
> Description: FFmpeg audio/video filtering library
> Version: 7.58.100
> Requires: libswscale >= 5.6.100, libpostproc >= 55.6.100, libavformat >= 58.30.100, libavcodec >= 58.55.100, libswresample >= 3.6.100, libavutil >= 56.32.100
> Requires.private: 
> Conflicts:
> Libs: -L${libdir}  -lavfilter -lm -LC:/media-autobuild_suite/local64/lib -lbs2b -lm -LC:/media-autobuild_suite/local64/lib -lrubberband -lstdc++ -lstdc++ -LC:/media-autobuild_suite/local64/lib -lmysofa -lz -lm -lflite_cmu_time_awb -lflite_cmu_us_awb -lflite_cmu_us_kal -lflite_cmu_us_kal16 -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmulex -lflite -LC:/media-autobuild_suite/local64/lib -lfribidi -LC:/media-autobuild_suite/local64/lib -lvmaf -lstdc++ -lpthread -lm -pthread -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -ltesseract -lpthread -lstdc++ -llept -lz -lpng16 -lz -ljpeg -ltiff -ljpeg -llzma -lz -lzstd -larchive -lnettle -lregex -lexpat -llzma -lzstd -llz4 -lbz2 -lz -lbcrypt -liconv -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -lass -lm -liconv -lharfbuzz -lm -lfontconfig -lintl -liconv -lxml2 -lz -llzma -liconv -lws2_32 -lfribidi -lfreetype -lz -LC:/media-autobuild_suite/local64/lib -lvidstab -lm -lgomp -lpthread -LC:/media-autobuild_suite/msys64/mingw64/lib -lzmq -lstdc++ -liphlpapi -lpthread -lws2_32 -lsodium -pthread -LC:/media-autobuild_suite/local64/lib -lzimg -lstdc++ -lOpenCL -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -lfontconfig -lintl -liconv -lxml2 -lz -llzma -liconv -lws2_32 -lfreetype -lz -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -lfreetype -lz -ldl -LC:/media-autobuild_suite/local64/lib -lmfx -lstdc++
> Libs.private: 
> Cflags: -I${includedir}
> 


libavformat.pc

> prefix=/local64
> exec_prefix=${prefix}
> libdir=/local64/lib
> includedir=/local64/include
> 
> Name: libavformat
> Description: FFmpeg container format library
> Version: 58.30.100
> Requires: libavcodec >= 58.55.100, libswresample >= 3.6.100, libavutil >= 56.32.100
> Requires.private: 
> Conflicts:
> Libs: -L${libdir}  -lavformat -lm -LC:/media-autobuild_suite/msys64/mingw64/lib -lxml2 -lz -llzma -liconv -lws2_32 -lbz2 -LC:/media-autobuild_suite/local64/lib -lgme -lstdc++ -LC:/media-autobuild_suite/msys64/mingw64/lib -lmodplug -lstdc++ -lm -LC:/media-autobuild_suite/local64/lib -lopenmpt -lrpcrt4 -lstdc++ -lstdc++ -LC:/media-autobuild_suite/local64/lib -lvsscript -lvapoursynth -lchromaprint -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -lbluray -lxml2 -lz -llzma -liconv -lws2_32 -LC:/media-autobuild_suite/msys64/mingw64/lib -lz -LC:/media-autobuild_suite/msys64/mingw64/lib -lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32 -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -lrtmp -lz -lgmp -lws2_32 -lwinmm -lgdi32 -lgnutls -lws2_32 -lgmp -latomic -lcrypt32 -ltasn1 -lhogweed -lgmp -lnettle -LC:/media-autobuild_suite/local64/lib -LC:/media-autobuild_suite/msys64/mingw64/lib -lsrt -lwsock32 -lws2_32 -lstdc++ -lmingwthrd -lmingw32 -lgcc -lmoldname -lmingwex -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingwthrd -lmingw32 -lgcc -lmoldname -lmingwex -lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lws2_32 -LC:/media-autobuild_suite/msys64/mingw64/lib -lssh -lz -lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32 -ldl
> Libs.private: 
> Cflags: -I${includedir}

libavutil.pc

> prefix=/local64
> exec_prefix=${prefix}
> libdir=/local64/lib
> includedir=/local64/include
> 
> Name: libavutil
> Description: FFmpeg utility library
> Version: 56.32.100
> Requires: 
> Requires.private: 
> Conflicts:
> Libs: -L${libdir}  -lavutil -pthread -lm -LC:/media-autobuild_suite/local64/lib -lmfx -lstdc++ -lOpenCL -luser32 -lbcrypt -ldl
> Libs.private: 
> Cflags: -I${includedir}

**Comment by Gryzmak** [comment]
Just copy and rename `libSvtHevcEnc.dll.a` to `libSvtHevcEnc.a`.

**Comment by wiiaboo** [comment]
Weird. mpv should still accept the `.dll.a` suffix eventually, if it can't find `.a`.

**Comment by fuchanghao** [comment]
> 
> 
> Just copy and rename `libSvtHevcEnc.dll.a` to `libSvtHevcEnc.a`.

Thanks a lot.

it works now.
