### ISSUE TITLE
[mingw64] dav1d build fails.

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1290]
It suddenly fails yesterday.

error log:https://0x0.st/zpUh.zip

> [313m14:33:44(B[m [1m┌ dav1d git (B[m................................... [[311mFiles missing(B[m]
> [313m14:33:44(B[m [1m├(B[m Running meson...
> [313m14:33:51(B[m [1m├(B[m Running build...
> Likely error:
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xb24): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xb40): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xb5c): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xb78): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xb94): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xbe1): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xc5d): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> 
> C:/media-autobuild_suite/local64/lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xe): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
> 
> collect2.exe: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> 
> [31mbuild failed. Check C:/media-autobuild_suite/build/dav1d-git/build-64bit/ab-suite.build.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [313m14:34:40(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/zpUh.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/zpUh.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

**Comment by GyanD** [comment]
And this can't be avoided by disabling dav1d since libdav1d has been hardcoded in ffmpeg config.

In https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-autobuild_suite.bat#L83,

```
set ffmpeg_options_basic=gmp libmp3lame libopus libvorbis libvpx libx264 libx265 ^
libdav1d
```
has to be changed to,

```
set ffmpeg_options_basic=gmp libmp3lame libopus libvorbis libvpx libx264 libx265 ^
::libdav1d
```

**Comment by wiiaboo** [comment]
Of course it can be disabled, just use ffmpeg_options.txt.

**Comment by GyanD** [comment]
Not at that machine right now, but I don't remember seeing that file. Is it present if ffmpeg build is set to full?

**Comment by 1480c1** [comment]
no, it is not generated if set to full
