### ISSUE TITLE
Saving output from media-suite_compile.sh to both a file and show on screen

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#130]
I'm looking for a way to follow the script on screen (like it is now) and also save the same output to a file.
Is this possible ?
I've tried with tee in the .bat file (where the media-suite_compile.sh is called, but this gives me a 0 byte logfile.  The problem is likely that the the bat (running Windows) do not share stdin/stdout with MSYS = where the "media-suite_compile.sh" runs
Some clever bash-guy around here ?

**Comment by wiiaboo** [comment]
I don't think it's feasible/easy to `tee` everything, but the next best thing is adding ` |& tee log` to run_builds in https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-suite_compile.sh#L2060 like:
`run_builds |& tee log`
It will disable colors and mess layout a bit in the log file, but it'll output stdout and stderr to log while still showing both in the console.

**Comment by jb-alvarado** [comment]
I have add logging function directly the the mintty shell output. Please report if it makes problems.
