### ISSUE TITLE
decklink option broken

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#1304]
After lates commits, even "--enable-nonfree" option is explicitely enabled in ffmpef_options.txt the media-autobuild failed to properly configure ffmpeg with decklink.
The error message is: "decklink is incompatible with the gpl and --enable-nonfree is not specified."

Please find the attached logs.zip file

regards,
Laur
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3440876/logs.zip)

**Comment by wiiaboo** [comment]
Yeah, I've seen what's causing the regression.
