### ISSUE TITLE
[mingw32] [mpv] No function '' defined in /build/mpv-git/wscript

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#1310]
```
Running configure...
Likely error:
Checking for DVB input module                                        : disabled 
Checking for w32 executable                                          : yes 
Checking for Apple Remote support                                    : cocoa not found 
Checking for macOS Touch Bar support                                 : cocoa not found 
Checking for macOS 10.11 SDK Features                                : cocoa not found 
Checking for macOS 10.14 SDK Features                                : cocoa not found 
Checking for macOS opengl-cb backend                                 : cocoa not found 
Writing configuration header:                                        : config.h 
'configure' finished successfully (18.986s)
No function '' defined in /build/mpv-git/wscript
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3450965/logs.zip)

Already tried to ask in IRC #mpv-devel @ Freenode, not yet much reply (only a guess that waf may be broken).

[Generated wscript file](https://pastebin.com/a8K3C6gv)

I wonder if it may be related to a recent Python update in MSYS2.

**Comment by wiiaboo** [comment]
Try deleting mpv-git folder.

**Comment by LigH-de** [comment]
I did once. It reconfigured to the same result... but that was a few hours ago. I will try again tomorrow. Maybe it got fixed.

**Comment by wiiaboo** [comment]
Maybe 32-bit is broken again. I've only tested in 64-bit.

**Comment by LigH-de** [comment]
Happens for me in 64-bit too.

**Comment by LigH-de** [comment]
I still don't know who to ask.

Maybe it's again time to re-install the whole suite.

**Comment by LigH-de** [comment]
Closing as unresolved, there are different issues now that I re-installed...

**Comment by LigH-de** [comment]
I reinstalled the suite a few days ago. Compiling everything in "non-free/custom" mode works. In "GPL3/Zeranoe" mode, configuring mpv stops as mentioned. So I guess that a kind of template is generated for a library which is not included, giving that template an empty identifier.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3492737/logs.zip)

**Comment by wiiaboo** [comment]
Have you tried disabling openal?

**Comment by LigH-de** [comment]
In the batch, like this?

```
set mpv_options_full=dvdread dvdnav cdda #egl-angle #html-build ^
#pdf-build libmpv-shared #openal
```

Not yet. Will try soon.

**Comment by wiiaboo** [comment]
No, using the mpv_options.txt, obviously.

**Comment by LigH-de** [comment]
But in GPL3 mode, options are used from the batch file. Obviously.
```
License: gplv3
Imported default mpv options from .bat
```

**Comment by wiiaboo** [comment]
Yeah, but if you want to selectively disable libs, it's easier to just use ffmpeg/mpv_option.txt instead of changing the suite files for no reason.

**Comment by wiiaboo** [comment]
@LigH-de does this still happen after #1342 was merged?

**Comment by LigH-de** [comment]
Sorry for the delay, my job was a bit under pressure today...

Confirming "fixed", the suite passed completely.
