### ISSUE TITLE
Please update the file README.md

### ISSUE THREAD

**Issue by filler56789** [jb-alvarado/media-autobuild_suite#1311]
The .bat file **requires PowerShell 5.1** and the readme file doesn't say a word about that.
Okay, it's possible to update PowerShell to version 5.1, but this is not the point.
Also, please stop assuming that every user of Windows has already switched to Windows 10. Both Windows 7 and Windows 8.1 still have a long way to travel.

**Comment by 1480c1** [comment]
I can either add it to the requirements in README.md or try to see if I can make the powershell scripts that we do have compatible with powershell 2.0

**Comment by 1480c1** [comment]
Although it's actually at least powershell 4 that we need (Windows 8.1 I think)

**Comment by wiiaboo** [comment]
You can just install a newer powershell, they're not stuck to Windows 10, I assume?

**Comment by 1480c1** [comment]
@wiiaboo, could i just separate out the individual powershell scripts in the batch file into a single powershell script under build? It's slightly annoying having to take care of escaping parentheses etc

**Comment by wiiaboo** [comment]
Sure.

**Comment by filler56789** [comment]
> You can just install a newer powershell, they're not stuck to Windows 10, I assume?

@wiiaboo — as I said, "upgrading" to PS 5.1 is not the problem, the problem is the text of the **README.md** doesn't say that the build script requires PS 5.1. In other words, the README should explicitly contain a download link to the archive **Win7AndW2K8R2-KB3191566-x64.zip** for the users of Windows 7 and Windows 8.1.

**Comment by filler56789** [comment]
**P.S.:** and a link to the "Windows 10 Universal C Runtime" stuff as well.

**Comment by 1480c1** [comment]
Would that be necessary? I've never had to install that when running the suite

**Comment by filler56789** [comment]
Good question. But some days ago I read elsewhere that PowerShell 5.1 (OR its damn installer, who knows?) requires the Windows 10 runtime thing and I installed it anyway, "just in case" and also because it's less of a bloatware than **KB3191566** itself.

**Comment by 1480c1** [comment]
As far as I know, the c runtime would only be for windows 10 and comes with a windows update, plus Powershell 5.1 would come with windows 10 already.

Either way, I'm right now trying to make it so the scripts work on Powershell 2.0 (available to all windows since XP sp3) or work but not with full features of the Powershell lacks it

**Comment by filler56789** [comment]
> As far as I know, the c runtime would only be for windows 10 and comes with a windows update,

Correct about the Windows update, incorrect about "only for Windows 10". Actually Windows 10 doesn't need it at all. If the MSU file required Windows 10 it would interrupt itself if run under any operating system below Windows 10.

**Comment by 1480c1** [comment]
Sorry, I mean as in ment for

**Comment by wiiaboo** [comment]
> Either way, I'm right now trying to make it so the scripts work on Powershell 2.0 (available to all windows since XP sp3) or work but not with full features of the Powershell lacks it

If it needs too much hacking, don't bother. People can just install newer powershell versions. Don't condone people staying with older versions of software for no good reason.

**Comment by filler56789** [comment]
Thanks!
