### ISSUE TITLE
FLAC build error

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#1325]
Running git clone for flac...
┌ flac git  .......................................... [Recently updated]
├ Running autogen...
Likely error:
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:41: error: installing './ar-lib'; error while making link: Operation not permitted
configure.ac:39: error: installing './compile'; error while making link: Operation not permitted
configure.ac:42: error: installing './config.guess'; error while making link: Operation not permitted
configure.ac:42: error: installing './config.sub'; error while making link: Operation not permitted
configure.ac:26: error: installing './install-sh'; error while making link: Operation not permitted
configure.ac:26: error: installing './missing'; error while making link: Operation not permitted
examples/c/decode/file/Makefile.am: error: installing './depcomp'; error while making link: Operation not permitted
autoreconf: automake failed with exit status: 1
autogen failed. Check D:/media-ab_suite/build/flac-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zO_T.zip
Copy and paste [logs.zip](https://0x0.st/zO_T.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Very possibly https://github.com/jb-alvarado/media-autobuild_suite/commit/9b3c50368c7672b6eee2edda883ce3d1c66ee6df

**Comment by 1480c1** [comment]
@wiiaboo, based on https://github.com/msys2/MSYS2-packages/issues/249, it may seem that symlinks require admin privileges

**Comment by BlackScreen** [comment]
Same here - and I can say that I have no admin rights on this computer (work pc).

```
08:12:35   Running git update for flac...
08:12:39 ┌ flac git  .................................... [Updates found]
08:12:42 ├ Running autogen...
Likely error:
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:41: error: installing './ar-lib'; error while making link: Operation not permitted
configure.ac:39: error: installing './compile'; error while making link: Operation not permitted
configure.ac:42: error: installing './config.guess'; error while making link: Operation not permitted
configure.ac:42: error: installing './config.sub'; error while making link: Operation not permitted
configure.ac:26: error: installing './install-sh'; error while making link: Operation not permitted
configure.ac:26: error: installing './missing'; error while making link: Operation not permitted
examples/c/decode/file/Makefile.am: error: installing './depcomp'; error while making link: Operation not permitted
autoreconf: automake failed with exit status: 1
autogen failed. Check C:/Development/MABS/build/flac-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
08:13:58   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zO_3.zip
Copy and paste [logs.zip](https://0x0.st/zO_3.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by wiiaboo** [comment]
In Win10 after Creator's update symlinks shouldn't need admin rights, but maybe that's why I didn't add winsymlinks before.

**Comment by BlackScreen** [comment]
In my company we are at 1709 - probably before that upgrade...
Maybe don't use the symlinks then?

**Comment by 1480c1** [comment]
I think there might be a way to match to windows 10 version  or test if ln works

**Comment by LigH-de** [comment]
For me it happens on Windows 7 SP1, in a directory outside the UAC protected branch.

**Comment by wiiaboo** [comment]
Yeah, Win7/8/8.1 will never get non-admin symlink support, I'd guess.

**Comment by wiiaboo** [comment]
And weird. Creator's update was before 1709. Maybe you have non-admin symlinks disabled by policy.

**Comment by wiiaboo** [comment]
You need to enable Developer Mode to have access to symlinks for a non-admin account, apparently.
![screenshot](https://i.fsbn.eu/vpeE.webp)

**Comment by LigH-de** [comment]
Leaves me wonder why it worked all the years before ... until now. Did these projects suddenly introduce links to their workflow?

I will try tomorrow if running the suite "as Administrator" works. You clamped fontconfig to a specific version, so I guess it doesn't need to recompile often.

**Comment by 1480c1** [comment]
ln -s in msys2 would actually copy the files instead

**Comment by LigH-de** [comment]
I wouldn't mind if it created a copy instead of failing, for the few times a symlink is used in a compilation workflow. May be related to the current configuration via MSYS variable (winsymlinks)?!

**Comment by nille02** [comment]
Symlinks can even be buggy on a admin account with UAC. If possible, i would suggest junctions.

**Comment by 1480c1** [comment]
Since we are limited by msys2's ln, we can't choose junctions

**Comment by ImportTaste** [comment]
@wiiaboo One possibility is if %noMinttyINI%==2, you could simply have the script restart itself with administrator permissions using with this command:
`fltmc >NUL || powershell "saps -FilePath '%0' -Verb RunAs"`

No issues with spacing, backwards compatible, all that jazz. It will prompt for admin permissions if UAC notifications are turned on but that's about it.

**Comment by wiiaboo** [comment]
No. Last thing we want is the suite running on admin. That's a security
hazard.

**Comment by LigH-de** [comment]
I agree; a few files being copied instead of linked is a minor inconvenience, in comparison.
