### ISSUE TITLE
ffmpeg+aom posibly build bug

### ISSUE THREAD

**Issue by GDXN** [jb-alvarado/media-autobuild_suite#1327]
I think that this is a compiling problem, as the official zeranoe binarie don't show this behaviour.

Even through the suit is build correctly for 64 bits wen encoding a video using ffmpeg and av1 the encoding stalls (cpu usage drops to zero and don't change) after encoding some frames.

I tried to clamp to the oldest revision build by me of libaom using the suite that works correctly and it stalls but the old build works correctly.

I need some help to troubleshot the problem more and if it helps the machine is a i7-7700hq running Windows 10.

**Comment by wiiaboo** [comment]
Whatever it is, it's not a suite issue. Maybe complain to MSYS2 as they compile the compilers.
Someone else said it maybe because MSYS2 is on GCC 9, while Zeranoe is probably still using GCC 8: https://github.com/jb-alvarado/media-autobuild_suite/issues/1259
