### ISSUE TITLE
x264 LGPL build

### ISSUE THREAD

**Issue by awede** [jb-alvarado/media-autobuild_suite#1329]
Hi,
First of all, great script, works perfectly.
This is more a request for help, then a bug.
We have a commercial license from x264 to use it as LGPL license.
Is there a way, how I can still build the x264 with this script and add it to FFmpeg, but have the whole FFmpeg build as LGPL.
I don't need the remaining libraries which are not build when LGPL is used, just the x264.

Thanks

Michal

**Comment by 1480c1** [comment]
Try compiling with x264 on and choosing the lgpl license and see if ffmpeg was compiled with the correct license. I don't think any libs are removed by the suite in lgpl. You can use the ffmpeg_options.txt (`Yes` for `Choose ffmpeg and mpv optional libraries?`) and disable all of the libs you don't need and enable only those you want (x264)

**Comment by wiiaboo** [comment]
x264 cannot be included in FFmpeg with only the LGPL license. If for some reason x264 released an LGPL version to you, you'd have to use the library directly, not included in FFmpeg.

**Comment by wiiaboo** [comment]
But FFmpeg user mailing lists are a more appropriate place for these questions. We use FFmpeg's licence restrictions directly. If they change x264 to not require --enable-gpl on git master, you'd then get your legal FFmpeg binaries. We will not accept patches to remove or change these restrictions.

**Comment by awede** [comment]
I undrestand, thank you for the information.

**Comment by Otiel** [comment]
Does that mean that [this answer](https://video.stackexchange.com/a/14804) is wrong?

># What about the x264 commercial license?
>
>The x264 commercial license is LGPL compatible, but FFmpeg does not have an option that disables the GPL requirement for commerical licensed x264 so you have to do that manually. Therefore, if you purchase a commercial license from x264 licensing then you are permitted to:
>
>* Compile x264 with `--disable-gpl`.
>* Modify the `configure` file in the FFmpeg source code to move libx264 from `EXTERNAL_LIBRARY_GPL_LIST` to `EXTERNAL_LIBRARY_LIST`.
>* Compile ffmpeg **without** `--enable-gpl` and link to your x264 that has been compiled **with** `--disable-gpl`.

Or that media-autobuild_suite doesn't offer the possibility perform the detailed steps?

**Comment by wiiaboo** [comment]
Looking at a [dead thread](https://ffmpeg.org/pipermail/ffmpeg-devel/2010-December/083754.html) in ffmpeg-devel, they thought of adding a way to officially support commercial x264 inclusion in LGPL FFmpeg, but looking at the commit history they never merged it.

So, it seems like you'd have to the steps you listed.

**Comment by Otiel** [comment]
Thanks for your reply. Any link to that commit?

A [later part of that thread](https://ffmpeg.org/pipermail/ffmpeg-devel/2010-December/083987.html) mentions another commit. Has this one been merged?

**Comment by wiiaboo** [comment]
No, the patches are old and I can't access them.
But it's likely something that would end in the same instructions in 
> > # What about the x264 commercial license?
> > The x264 commercial license is LGPL compatible, but FFmpeg does not have an option that disables the GPL requirement for commerical licensed x264 so you have to do that manually. Therefore, if you purchase a commercial license from x264 licensing then you are permitted to:
> > 
> > * Compile x264 with `--disable-gpl`.
> > * Modify the `configure` file in the FFmpeg source code to move libx264 from `EXTERNAL_LIBRARY_GPL_LIST` to `EXTERNAL_LIBRARY_LIST`.
> > * Compile ffmpeg **without** `--enable-gpl` and link to your x264 that has been compiled **with** `--disable-gpl`.

**Comment by wiiaboo** [comment]
You're welcome to propose another patch for that in ffmpeg-devel, or ask someone else to do it in ffmpeg-user.
