### ISSUE TITLE
openjp2

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/media-autobuild_suite#133]
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-suite_compile.sh#L526

Does it have a negative effect when we change the config to:

```
do_cmake -DOPENJPEG_INSTALL_BIN_DIR=$LOCALDESTDIR/bin-global \
-DBUILD_CODEC=off -DCMAKE_C_FLAGS="$CFLAGS -DOPJ_STATIC" \
-DBUILD_PKGCONFIG_FILES=on
```

Compiling the bin makes errors at the moment, with the option on top not. And maybe we don't need the executables.

**Comment by wiiaboo** [comment]
Errors with what, openjpeg2? FFmpeg? 32 or 64 bits? I compiled it fine yesterday and there are no new commits.

**Comment by wiiaboo** [comment]
It errored for me too if I didn't clean installed includes before compiling.
Did you do that?

**Comment by jb-alvarado** [comment]
I just run the script and it produce the errors in openjp2. Something with bmp-convert etc. Normally the script take car of the removing from the includes, or is there a mistake?

**Comment by wiiaboo** [comment]
I'm fixing it now.

**Comment by wiiaboo** [comment]
Should be fixed now.
