### ISSUE TITLE
libSvtHevcEnc.dll is still required on static build ffmpeg with --enable-libsvthevc

### ISSUE THREAD

**Issue by fangchunxi1999** [jb-alvarado/media-autobuild_suite#1330]
as the title said static ffmpeg with --enable-libsvthevc is depen on libSvtHevcEnc.dll to run
![image](https://user-images.githubusercontent.com/22297726/62555231-c7eb3400-b89c-11e9-85c5-ccf4b0bff347.png)
from quick google search 
https://github.com/OpenVisualCloud/SVT-HEVC/issues/255
is it a upstream problem that it still require .dll for now?

**Comment by 1480c1** [comment]
yes

**Comment by fangchunxi1999** [comment]
ok thank!
look like either disable svt-hevc or copy .dll together with ffmpeg.exe for now
