### ISSUE TITLE
Error running git update for libmediainfo

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1333]
20:41:07   Running git update for libmediainfo...
20:41:12 ┌ libmediainfo git  ............................ [Updates found]
20:41:12 ├ Running uninstall...
20:41:12 ├ Running cmake...
20:41:20 ├ Running build...
Likely error:
[231/234] Building RC object CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc.obj
FAILED: CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc.obj
C:\mingw\msys64\mingw64\bin\windres.exe -O coff -DMEDIAINFO_LIBMMS_NO -DUNICODE -D_FILE_OFFSET_BITS=64 -D_UNICODE -IC:/mingw/build/libmediainfo-git/Source -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/md5 -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/base64 -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/aes-gladman -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/sha1-gladman -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/sha2-gladman -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/hmac-gladman -IC:/mingw/msys64/mingw64/include -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/tinyxml2 -IC:/mingw/build/ZenLib/Source -IC:/mingw/local64/include  C:/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc.obj
[232/234] Building CXX object CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.cpp.o
[233/234] Building CXX object CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/ThirdParty/tinyxml2/tinyxml2.cpp.o
ninja: build stopped: subcommand failed.
[1/2] Building RC object CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc.obj
FAILED: CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc.obj
C:\mingw\msys64\mingw64\bin\windres.exe -O coff -DMEDIAINFO_LIBMMS_NO -DUNICODE -D_FILE_OFFSET_BITS=64 -D_UNICODE -IC:/mingw/build/libmediainfo-git/Source -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/md5 -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/base64 -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/aes-gladman -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/sha1-gladman -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/sha2-gladman -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/hmac-gladman -IC:/mingw/msys64/mingw64/include -IC:/mingw/build/libmediainfo-git/Source/ThirdParty/tinyxml2 -IC:/mingw/build/ZenLib/Source -IC:/mingw/local64/include  C:/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc CMakeFiles/mediainfo.dir/C_/mingw/build/libmediainfo-git/Source/MediaInfoDLL/MediaInfoDLL.rc.obj
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/libmediainfo-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
20:43:18   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zOya.zip
Copy and paste [logs.zip](https://0x0.st/zOya.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by ImportTaste** [comment]
I'm also having this issue, I turned off compiling mediainfo in the mean time.

**Comment by wiiaboo** [comment]
Probably the same binutils issue, try it again.

**Comment by ImportTaste** [comment]
I can confirm, it was the binutils issue.
