### ISSUE TITLE
dav1d build error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#1334]
dav1d git  ................................ [Recently updated]
Running meson...
Likely error:
Compiler for C supports arguments -mpreferred-stack-boundary=5: NO
Compiler for C supports arguments -mstack-alignment=32: NO
Configuring config.h using configuration
Configuring config.asm using configuration
Program nasm found: YES (D:\ffmpeg-autobuild\msys64\mingw64\bin/nasm.EXE)
Configuring version.h using configuration
Program doxygen found: YES (D:\ffmpeg-autobuild\msys64\usr\bin/doxygen.EXE)
Configuring Doxyfile using configuration
Configuring cli_config.h using configuration
Found pkg-config: D:\ffmpeg-autobuild\msys64\mingw64\bin/pkg-config.EXE (0.29.2)
meson failed. 
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3480125/logs.zip)

**Comment by LigH-de** [comment]
Building dav1d just passed for me (mingw32); either fixed or mingw64 only? Suite progressing...

**Comment by BlackScreen** [comment]
Building with 64 bit worked here also.

**Comment by kliffgomel** [comment]
Ok, maybe the problem is on my side.

**Comment by kliffgomel** [comment]
The problem seems to be in the meson. I deleted the folders msys64 local64 and tried to build the suite from scratch, but got a similar error when compiling Fribidi.
12:29:52 ┌ fribidi git  .............................. [Recently updated]
12:29:53 ├ Running meson...
Likely error:
Has header "sys/times.h" : NO
Has header "strings.h" : YES (cached)
Configuring config.h using configuration
Has header "stdlib.h" : YES (cached)
Has header "string.h" : YES (cached)
Has header "strings.h" : YES (cached)
Checking for size of "int" : 4
Configuring fribidi-config.h using configuration
Build targets in project: 19
Found ninja.EXE-1.9.0 at 'D:\ffmpeg-autobuild\msys64\mingw64\bin/ninja.EXE'
meson failed. Check D:/ffmpeg-autobuild/build/fribidi-git/build-64bit/ab-suite.meson.log

What could be the problem?
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3481102/logs.zip)

**Comment by wiiaboo** [comment]
I can't really read russian, but google says it's something to do with Invalid Parameter. Since we did not change anything to do with meson recently, I assume it's breakage either on meson or on MSYS2/MinGW. Either way, not a suite issue.

**Comment by wiiaboo** [comment]
Does it work now? Yesterday I did compile dav1d with no issues but I did block the binutils broken update.

**Comment by kliffgomel** [comment]
Once again I rebuilt the project from scratch and there were no errors.  Changed nothing, just reinstalled everything again.  Perhaps I have some kind of antivirus problem.
