### ISSUE TITLE
[mingw64] [SVT-HEVC] install check fails.

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1341]
commit: 44f45daaef44586dce1fd985955027392a9c2326
svt-hevc commit: https://github.com/OpenVisualCloud/SVT-HEVC/commit/835ec04a4bc9430169657abce5e41cdc6a73f129

Now the build's output library are libSvtHevcEnc.a not libSvtHevcEnc.dll.a

But the checking code in media-suite_compile.sh still use libSvtHevcEnc.dll.a.

https://github.com/jb-alvarado/media-autobuild_suite/blob/44f45daaef44586dce1fd985955027392a9c2326/build/media-suite_compile.sh#L1285

**Comment by wiiaboo** [comment]
#1340
