### ISSUE TITLE
wget error on new install

### ISSUE THREAD

**Issue by tcmbackwards** [jb-alvarado/media-autobuild_suite#1343]
Error

The errors happen right after one of the initial pacman updates and the script ends. Running it again just gives the same errors.

If I run mingw64 and run pacman manually, it installs an additional 78 packages including several crypto libraries. After that update finishes, I can run the script and it will build as normal.

![Annotation 2019-08-13 085653](https://user-images.githubusercontent.com/3756430/62943409-68af8700-bda8-11e9-8345-6fd785b410a3.jpg)
![Annotation 2019-08-13 085711](https://user-images.githubusercontent.com/3756430/62943414-6b11e100-bda8-11e9-9218-01aa8855c988.jpg)

[build.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3497000/build.zip)

**Comment by wiiaboo** [comment]
@1480c1 can you check this? Looking at the logs everything was properly installed but wget failed to get the suite's scripts.

**Comment by 1480c1** [comment]
I can try to see whats wrong

**Comment by 1480c1** [comment]
Was this a completely new install? Downloaded through either zip or git?

**Comment by wiiaboo** [comment]
Since the script files are missing, I'd assume he just downloaded the .bat.

**Comment by 1480c1** [comment]
Hmm, that's a way I didn't think was possible. I'll actually see if the bat file can be run on it's own (I thought it relied on update.sh for updating some stuff)

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-autobuild_suite.bat#L1445-L1451

**Comment by tcmbackwards** [comment]
> 
> 
> Since the script files are missing, I'd assume they just downloaded the .bat.

Yes that's what I did. It had worked that way several months ago when I last installed it fresh.

**Comment by 1480c1** [comment]
I'm going to see if I can reproduce
