### ISSUE TITLE
Mplayer hangs on ffmpeg merge,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#135]
mplayer hangs on the seconds run (64bit) with:

> Merge branch 'master' of /build/ffmpeg-git

# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"/build/mplayer-svn/ffmpeg/.git/MERGE_MSG" 7 lines, 270 characters

**Comment by wiiaboo** [comment]
It's because of a recent commit that made patches start using `git am` instead of patch and I forgot that mplayer doesn't reset git.
Working on a fix.

Meanwhile, just delete `ffmpeg` directory **inside** `mplayer-svn`. **No need to delete `ffmpeg-git`**.

**Comment by wiiaboo** [comment]
Even with the fixes, mplayer svn is broken. Not our fault. Turn it off meanwhile if you want to compile anything else.

**Comment by Selur** [comment]
> Updating FFmpeg, (re)move ffmpeg/mp_auto_pull to disable
Already on 'master'
Your branch is ahead of 'origin/master' by 46 commits.
  (use "git push" to publish your local commits)
It looks like git-am is in progress. Cannot rebase.
git pull failed, (re)move ffmpeg/mp_auto_pull to disable pulling
Makefile:22: config.mak: No such file or directory
make: *** osdep/: Is a directory.  Stop.
Makefile:22: config.mak: No such file or directory
make: *** osdep/: Is a directory.  Stop.
-------------------------------------------------
Build of mplayer-svn failed...


looks like there's still something off with the merge,....

**Comment by wiiaboo** [comment]
Testing a fix now, also I saw that they saw build was broken in Mingw and probably fixed it.

**Comment by wiiaboo** [comment]
Try now and remove ffmpeg folder inside mplayer, to be safe.
