### ISSUE TITLE
[|mingw64] [ffmpeg] librav1e: Could we skip some errors to successfully build librav1e into ffmpeg?

### ISSUE THREAD

**Issue by moisespr123** [jb-alvarado/media-autobuild_suite#1361]
I just gave librav1e another try and this is the new error:

```
Likely error:
H:/repos/media-autobuild_suite/build/ffmpeg-git/libavcodec/librav1e.c:118:13: error: implicit declaration of function 'rav1e_twopass_unref'; did you mean 'rav1e_twopass_in'? [-Werror=implicit-function-declaration]
  118 |             rav1e_twopass_unref(buf);
      |             ^~~~~~~~~~~~~~~~~~~
      |             rav1e_twopass_in
H:/repos/media-autobuild_suite/build/ffmpeg-git/libavcodec/librav1e.c: In function 'range_map':
H:/repos/media-autobuild_suite/build/ffmpeg-git/libavcodec/librav1e.c:67:1: error: control reaches end of non-void function [-Werror=return-type]
   67 | }
      | ^
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:59: libavcodec/librav1e.o] Error 1
```

So, the question is, is there a way to add `Wno-error=implicit-function-declaration` and `Wno-error=return-type`?

I'd like to see if the suite compiles librav1e into ffmpeg. I just need to know where's the correct place to add those 2 arguments to test it again and see if actually compiles.

The patches issue that we were having at issue #1279 are no longer happening. Instead, make just fails with the above mentioned errors.

**Comment by wiiaboo** [comment]
Use custom ffmpeg_extra.sh and use _pre_configure
