### ISSUE TITLE
Feature request: option to disable NUMA in x265 to be Windows XP and Windows Vista compatible

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#139]
Would be nice if there was an option which would allow to build Windows XP and Windows Vista compatible x265 versions even when building under Windows 7 oder Windows 10.

Or even better would be an option to additionally build such a version.

**Comment by wiiaboo** [comment]
What do you mean?
It's already there:
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-autobuild_suite.bat#L311-L312

**Comment by Selur** [comment]
Ah, didn't know since it was implemented after I setup my current build environment :)

**Comment by wiiaboo** [comment]
I didn't create a new option because I don't think enough people care about XP to make everyone rechoose their options. And other than x265 there aren't more libs that don't like XP other than libmfx(?)

**Comment by Selur** [comment]
Correction not exactly, what I would like are:
1. an x265.exe which includes 8bit, 10bit, 12bit (not XP compatible)
and
2. an x264.exe which includes 8bit, 10bit, 12bit and is XP compatible
and I would like to be able to build both in one run of the script

**Comment by Selur** [comment]
Nope, iirc only x265 (with NUMA is not XP compatible)

**Comment by wiiaboo** [comment]
Why not just compile the XP compatible version? It's compatible on all the others too. It's just a tiny bit slower and adds a huge bunch of time to the compilation time if you compile both versions.

**Comment by Selur** [comment]
" It's just a tiny bit slower " not if you cpu count is higher (according to the x265 developers).
Sure the whole x265 builds are compiled two times more, but that's it.

**Comment by wiiaboo** [comment]
Which one gets added to ffmpeg then?

**Comment by Selur** [comment]
I don't add x265 to ffmpeg, if I would do that I would probably build two versions, yes.

"It's just a tiny bit slower and adds a huge bunch of time to the compilation time if you compile both versions." -> that argument could also be used to argue for always enforcing XP compatibility ;)

**Comment by wiiaboo** [comment]
No, because fuck XP. It's not supported by anyone, so it should die. If you want a 13-year old you shouldn't expect bleeding-edge software to work.

That said, it's added. Haven't tested.

**Comment by Selur** [comment]
it's also Vista :) not only XP

**Comment by Selur** [comment]
for 64bit there's a x265.exe and a x265-numa.exe, for 32bit there is only a x265.exe

**Comment by wiiaboo** [comment]
You have to force both builds by making sure there are no `build_successful*bits` files inside x265-hg.
The variables were in the wrong place so x265-numa.exe was probably identical to x265.exe, try again now.

**Comment by Selur** [comment]
to be on the save site, I simply deleted the whole x265-hg folder form the build directory and this time both files were build :)
