### ISSUE TITLE
mpv - No such file or directory

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/media-autobuild_suite#140]
I getting always this message:
```
[238/242] Compiling video/out/gl_w32.c
[239/242] Linking build/mpv.com
+ install /local32/bin-video/mpv.com (from build/mpv.com)
[241/242] Linking build/mpv.exe
gcc.exe: error: CreateProcess: No such file or directory
```
Deleting the source folder has no effect.

**Comment by wiiaboo** [comment]
Never had that. Have no idea how to fix it.

**Comment by jb-alvarado** [comment]
That is interesting. I also think I am the only one with that problem, because no one put an issue - but by me I have it already longer.

**Comment by jb-alvarado** [comment]
Like this I am able to compile the mpv.exe:
- I copy the hole error message and delete everything except the gcc command.
- then I remove all the linker flags to the lib dirs, there are many lines with the same statement.
- at the end I add  -L/local32/lib -L/mingw32/lib (in that order it have to be)
- cd to the mpv-git/build dir
- and run gcc [...]

Thats it... 

That means waf take to many linking directorys. But how we can prevent this?

**Comment by wiiaboo** [comment]
I don't think we can, easily. The only problem I had with waf linking flags I fixed by temporarily renaming librtmp.a which was grabbing MinGW's instead of ours.

You could always make an issue in mpv-player.

**Comment by wiiaboo** [comment]
What are the options and ini you get that with?

**Comment by jb-alvarado** [comment]
I run the script now from the ground. Maybe after that it is ok...

**Comment by jb-alvarado** [comment]
Ok, the script is done and brings the same error. Maybe it have to do with that:
https://github.com/mpv-player/mpv/issues/2253

My ini looks like this:
```
[compiler list]
msys2Arch=2
arch=1
free=1
vpx=1
x264=1
x265=1
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=2
ffmpegChoice=2
mp4box=1
mplayer=1
mpv=1
cores=6
deleteSource=1
strip=1
pack=2
```

**Comment by wiiaboo** [comment]
Hm, what if you use that old sed again to remove the duplicated -L flags?
```bash
sed -r -i "s/LIBPATH_lib(ass|av(|device|filter)) = \[.*local(32|64).*mingw(32|64).*\]/LIBPATH_lib\1 = ['\/local\3\/lib', '\/mingw\4\/lib']/g" ./build/c4che/_cache.py
```
I removed it because I thought it was just about the cosmetics, but maybe it reduces the number of arguments enough to solve the issue.

Check if f23072b fixes it.

**Comment by jb-alvarado** [comment]
Ha, of course this helps, now it works! I remember darkly that in the past I have done play with the gcc command to find out what is happen, but I don't remember that I had use a sed :). Thanks for fixing it.
