### ISSUE TITLE
Suggestion..

### ISSUE THREAD

**Issue by shinchiro** [jb-alvarado/media-autobuild_suite#142]
Option to download/updating all library to latest git without compiling & option to compiling without checking latest git (offline mode) might be convenient for some people who doesnt always internet as compiling the whole thing take a lot of time

Thanks for this useful script

**Comment by wiiaboo** [comment]
If you don't have internet access it will still compile (or not if there weren't any updates) from the VCS sources, but there's a lot of tarballed sources too and those aren't so practical to make work like this. And then if you compile just tarballed there's some that depend on git/hg libs and then will fail to compile.

Ideally, you should only need time (and internet access) to compile everything once. If you can find internet access for that long, look at the README and check which options you can disable in the .ini (everything except flac). Run the script once like that and it will install most of the libs built from tarballs.

Then turn ffmpeg on and press ctrl+C after it runs the configure script. That means it will fail building but it downloaded the repository. FFmpeg is the biggest download in the script, so after that, if you want the other libs/apps it will go faster. After compiling kvazaar, vpx, x264 and x265 you can turn them off and if you still left their `--enable-lib*` options in `ffmpeg_options.txt` they will still be used.

I think adding a "download-only" option would be too specific and too much work for little gain, personally. You're welcome to make a pull request for it, though.

**Comment by jb-alvarado** [comment]
At the moment I also don't see much sense for a download only function, maybe download everything at first and then compile, but for that the script needs to to many changes, and I think it gets less readable for beginners. The second point can make sense, when we say for example we give an option for preventing msys2 from updating. And a other option for only some main tools to updating. This is also a lot of work. My goal, by stating this script, was a solution for people how have not skills in programming and scripting, for them to have a chance to compile ffmpeg and other tools directly in windows, and as easy as it can. When we bring more and more options, it can bring confusion to beginners. That means not that I am in general against this, we only need to see what is good and needed.

**Comment by wiiaboo** [comment]
You're welcome to add a way to do it yourself and make a pull request, but since neither of us think it's worth it, this is a wontfix.
