### ISSUE TITLE
DOS file format

### ISSUE THREAD

**Issue by ksfalcon** [jb-alvarado/media-autobuild_suite#143]
I have a little suggestion. Can you using DOS file format as output for the log files?
```
unix2dos ./newchangelog
[[ -f ./CHANGELOG.txt ]] && cat ./CHANGELOG.txt >> ./newchangelog
mv ./newchangelog ./CHANGELOG.txt
```
http://www.cyberciti.biz/faq/howto-unix-linux-convert-dos-newlines-cr-lf-unix-text-format/

**Comment by wiiaboo** [comment]
The changelog is easy. Mintty logs are maybe not so easy, since the script closes before we can change the log.

**Comment by wiiaboo** [comment]
Done in a4bfc474c465e4f18b2c6cc9c7e3bf7082db3376
