### ISSUE TITLE
Install path to fstab

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/media-autobuild_suite#144]
I would like to have the install path linked in the fstab file. For example:

```
C:\msys2\ /root
[...]
```
But /root is in *nix the place for the root user folder, so I guess a other name is better.

Do you have any suggestions?

**Comment by wiiaboo** [comment]
/trunk
It's above the root :evergreen_tree:

**Comment by jb-alvarado** [comment]
hehe, yes that sounds good!
