### ISSUE TITLE
decklink SDK 10.4.3

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/media-autobuild_suite#145]
Only a notice - decklink SDK 10.4.3 is out, so I can generate a new include file.

**Comment by wiiaboo** [comment]
No opinion on that, as I don't use it. As long as it doesn't break building, either way is fine by me.

**Comment by jb-alvarado** [comment]
It was more for my self, that I remember it.

**Comment by pat357** [comment]
I'm just wondering how you can create only 3 files out of the bunch .h files that are included in the SDK zip file ?
What tool do you use for this ?

Thanks,
Pat357

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/wiki/Getting-Decklink-headers

**Comment by laurfb** [comment]
Well, DeckLink SDK 10.5 is now available...
:)
regards,
laur

**Comment by jb-alvarado** [comment]
Really? Yesterday I only found 1.4.3. Is it on the same page?
