### ISSUE TITLE
libdvd-nav doesn't build anyore after update

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#146]
As the tiltle says : libdvd-nav doesn't build anymore after the changes from today (see http://git.videolan.org/?p=libdvdnav.git;a=summary).
How can I tell git to get the source from before these changes ?

This is what I get:
======================================================================
configure: WARNING: you should use --build, --host, --target
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... K:/Mingw64/msys64/mingw32/i686-w64-mingw32/bin/ld.exe
checking if the linker (K:/Mingw64/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw32/bin/nm -B
checking the name lister (/mingw32/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert i686-w64-mingw32 file names to i686-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert i686-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for K:/Mingw64/msys64/mingw32/i686-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic file format (pei*-i386(.*architecture: i386)?|pe-arm-wince|pe-x86-64)
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /mingw32/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (K:/Mingw64/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking whether byte ordering is bigendian... no
checking for gettimeofday... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for DVDREAD... yes
checking if gcc supports -mno-ms-bitfields flag... yes
checking if gcc supports -Wall -Wsign-compare -Wextra flag... yes
checking for doxygen... doxygen
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating misc/dvdnav.pc
config.status: creating misc/libdvdnav.spec
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-am
make[1]: Entering directory '/build/dvdnav-git'
  CC       src/dvdnav.lo
  CC       src/read_cache.lo
  CC       src/navigation.lo
  CC       src/highlight.lo
  CC       src/searching.lo
src/navigation.c: In function 'dvdnav_part_play_auto_stop':
src/navigation.c:247:66: warning: unused parameter 'parts_to_play' [-Wunused-parameter]
                                            int32_t part, int32_t parts_to_play) {
                                                                  ^
src/navigation.c: In function 'dvdnav_time_play':
src/navigation.c:254:58: warning: unused parameter 'title' [-Wunused-parameter]
 dvdnav_status_t dvdnav_time_play(dvdnav_t *this, int32_t title,
                                                          ^
src/navigation.c:255:43: warning: unused parameter 'time' [-Wunused-parameter]
                                  uint64_t time) {
                                           ^
src/searching.c: In function 'dvdnav_describe_title_chapters':
src/searching.c:650:16: error: invalid operands to binary == (have 'ptt_info_t {aka struct <anonymous>}' and 'void *')
     if (ptt[i] == NULL) {
                ^
src/searching.c:651:45: error: macro "printerr" passed 3 arguments, but takes just 1
       printerr("ptt NULL: %i %i.", i, parts );
                                             ^
src/searching.c:651:7: error: 'printerr' undeclared (first use in this function)
       printerr("ptt NULL: %i %i.", i, parts );
       ^
src/searching.c:651:7: note: each undeclared identifier is reported only once for each function it appears in
Makefile:601: recipe for target 'src/searching.lo' failed
make[1]: *** [src/searching.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/dvdnav-git'
Makefile:423: recipe for target 'all' failed
make: *** [all] Error 2
===========================================================================

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/e069ee155bf91e0a1a9118ec4f22c74d2d88da49

**Comment by wiiaboo** [comment]
Fixed.
