### ISSUE TITLE
"media-autobuild_suite.bat" exits before starting the actual compiling ("media-suite_compile.sh")

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#147]
"media-autobuild_suite.bat" exits due a small bug in the script:
At line 1197 the problem is generated:

if %removefstab%==yes (
    del %instdir%\%msys2%\etc\fstab.
    GOTO writeFstab
    )
If the variable "removefstab" is empty (empty string), this translates to
if ==yes (
In this case Windows generates an error like : did not expect a "("  at that point. 

It's actual the same to what happens in BASH when using single squares and the variables are not quoted. ( like if [ $var = value...). In BASH we quote or use if [[  $var =... ]] or initialize the variable.
 
Anyway, it's easy to correct  and there're many possible solutions:
what I did is initialize the variable "removefstab" before it's being used: 
add a line at 1179 : "set removefstab=no".

What wonders me is that I'm the first to bump against this issue .... maybe the way how Windows reacts is dependent for Windows versions and/or specific settings.

**Comment by jb-alvarado** [comment]
Thank you for tip! Is fixed now.
