### ISSUE TITLE
dynamic lib check fails

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#148]
After the update phase, the script starts checking for available dynamic libraries but fails:

```
check for dynamic libs
-------------------------------------------------------------------------------
"(" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```

**Comment by LigH-de** [comment]
Commit faf8fa79f7 (2015-08-29) still works.

**Comment by jb-alvarado** [comment]
That is strange because there was no change in the batch file. At the moment I have no time, I will take a look at it later. Or  wiiaboo is faster.

**Comment by ASopH** [comment]
please correct line 1179 in media-autobuild_suite.bat to: set removefstab=no

**Comment by wiiaboo** [comment]
Can't read german, what does that say?

**Comment by LigH-de** [comment]
Syntax error, unexpected "("

ASopH found a correct fix. This "set" was indeed missing.
