### ISSUE TITLE
FR: vpx enhancement - enable vp10 on demand

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#149]
The current sources of vpx contain a prepared branch for VP10 encoder and decoder, but it is per default disabled in the configuration (vpx-git/configure):
```
# disable vp10 codec by default
disable_feature vp10
```
Some may be interested in enabling it. Would that be suitable via media-autobuild_suite.ini configuration?

I'm unable to keep it enabled, it gets reset each time the suite runs a pass. No matter if I add ```--enable-vp10``` to the vpx extracommands, the configure script first recognizes it, but then still writes a configuration where vp10 is disabled.

**Comment by wiiaboo** [comment]
Isn't it just a copy of vp9 at this point?

**Comment by LigH-de** [comment]
OK, let's leave this issue postponed. Kurtnoise also does not recommend trying it. But it seems to be possible, there is a fresh build in the doom9 forum. Well possible VP10 does not yet differ from VP9 a lot.

**Comment by wiiaboo** [comment]
That's probably because the script runs a clean checkout of the master branch every time. You're supposed to compile it by yourself or add a patch/sed to the script if you really want the script to use it.

**Comment by wiiaboo** [comment]
I didn't turn it on by default, but you just need `--enable-vp10` in `configure` to enable it.
If you use the latest commit 31ea86bfc3e367c33bfdbafd69b7ad0fb0385165 there's a commented line and all you need to do is uncomment it.

Will uncomment the line when the upstream developers stop disabling it.
