### ISSUE TITLE
error "Cannot update paths and switch to branch 'ab-suite' at the same time"

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#151]
Hi. I found this error on compiling.log.
"............................................................
kvazaar is already up to date
............................................................
fatal: Cannot update paths and switch to branch 'ab-suite' at the same time.
Did you intend to checkout 'origin/fonts' which can not be resolved as commit?
fatal: Cannot update paths and switch to branch 'ab-suite' at the same time.
Did you intend to checkout 'origin/fonts' which can not be resolved as commit?
............................................................
libass is already up to date
............................................................"
regards,
laur

**Comment by wiiaboo** [comment]
Could you try deleting kvazaar-git directory?

**Comment by laurfb** [comment]
Can be closed I think (deleted libass-git and ran lattest script - no more error)
regards,
laur
