### ISSUE TITLE
suite stuck after compiling libass, waiting for input?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#158]
Compiling libass is done, directory "/build/libass-git" was left ... and nothing happens until I press ENTER.

```
make[2]: Verzeichnis „/build/libass-git“ wird verlassen
make[1]: Verzeichnis „/build/libass-git“ wird verlassen
{ Here I pressed ENTER }
-
-------------------------------------------------
build libass-git done...
-------------------------------------------------
-
```

**Comment by wiiaboo** [comment]
I still can't read german. What does that say

**Comment by nille02** [comment]
Leaving Directory „/build/libass-git“

**Comment by LigH-de** [comment]
Just what I described above. That's why I explained it before I quoted it.

"Verzeichnis „/build/libass-git“ wird verlassen" ~ "Leaving directory „/build/libass-git“".

**Comment by wiiaboo** [comment]
Ok, I can reproduce. Grep thinks "-liconv" is an option.
