### ISSUE TITLE
FFmpeg cosmetic's

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#159]
Since the new cosmetic SED command has been implemented, I get really ugly looking thinks in my config.h and ffmpeg -buildconf.

ffmpeg -buildconf gives:
===============================================
$ ffmpeg -buildconf
  libavutil      55.  1.100 / 55.  1.100
  libavcodec     57.  1.100 / 57.  1.100
  libavformat    57.  0.100 / 57.  0.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  1.100 /  6.  1.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100

  configuration:
    --enable-static
    --disable-shared--disable-debug
    --enable-gpl
    --disable-w32threads
    --enable-avisynth
    --pkg-config-flags=--static--enable-avisynth
    --enable-avresample
    --enable-gnutls
    --enable-frei0r
    --enable-libbluray
    --enable-libcaca
    --enable-libopenjpeg
    --enable-libass
    --enable-libgsm
    --enable-libilbc
    --enable-libmodplug
    --enable-libmp3lame
    --enable-libopencore-amrnb
    --enable-libopencore-amrwb
    --enable-libvo-amrwbenc
    --enable-libschroedinger
    --enable-libsoxr
    --enable-libtwolame
    --enable-libspeex
    --enable-libtheora
    --enable-libvorbis
    --enable-libvo-aacenc
    --enable-libopus
    --enable-libvidstab
    --enable-libxavs
    --enable-libxvid
    --enable-libzvbi
    --enable-libx265
    --enable-libx264
    --enable-fontconfig
    --enable-libfreetype
    --enable-libfribidi
    --enable-libkvazaar
    --disable-decoder=dca
    --enable-libdcadec
    --enable-libbs2b
    --enable-libmfx
    --enable-libcdio
    --enable-libsnappy
    --enable-libwavpack
    --enable-libwebp
    --enable-libvpx
    --enable-opengl
    --enable-decklink
    --enable-libutvideo
    --enable-libgme
    --enable-nonfree
    --enable-nvenc
    --enable-libfdk-aac--enable-version3
    --enable-filter=frei0r
===============================================
As you can see, some options got "sticked together".
By looking at my config.h before and after the SED command, it is obvious that the SED command causes this as the original doesn't have the sticky things.

This is one line from my original config.h (before sed):

======original, before sed ==================================================
#define FFMPEG_CONFIGURATION "--prefix=/local64 --bindir=/local64/bin-video --enable-static --disable-shared --target-os=mingw32 --disable-debug --enable-gpl --disable-w32threads --enable-avisynth --pkg-config-flags=--static --extra-cflags=-O3 --extra-cflags=-DPTW32_STATIC_LIB --extra-cflags='-mtune=native' --enable-avisynth --enable-avresample --enable-gnutls --enable-frei0r --enable-libbluray --enable-libcaca --enable-libopenjpeg --enable-libass --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvo-aacenc --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid --enable-libzvbi --enable-libx265 --enable-libx264 --enable-fontconfig --enable-libfreetype --enable-libfribidi --enable-libkvazaar --disable-decoder=dca --enable-libdcadec --enable-libbs2b --enable-libmfx --enable-libcdio --enable-libsnappy --enable-libwavpack --enable-libwebp --enable-libvpx --enable-opengl --enable-decklink --enable-libutvideo --enable-libgme --enable-nonfree --enable-nvenc --enable-libfdk-aac --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DKVZ_STATIC_LIB --extra-cflags=-DLIBTWOLAME_STATIC --enable-version3 --enable-filter=frei0r --extra-libs='-liconv -lpng -lpthread -lwsock32'"
#define FFMPEG_LICENSE "nonfree and unredistributable"

And this is the same line from my config.h  AFTER the SED command: 

======AFTER SED  ==================================================
#define FFMPEG_CONFIGURATION "--enable-static --disable-shared--disable-debug --enable-gpl --disable-w32threads --enable-avisynth --pkg-config-flags=--static--enable-avisynth --enable-avresample --enable-gnutls --enable-frei0r --enable-libbluray --enable-libcaca --enable-libopenjpeg --enable-libass --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvo-aacenc --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid --enable-libzvbi --enable-libx265 --enable-libx264 --enable-fontconfig --enable-libfreetype --enable-libfribidi --enable-libkvazaar --disable-decoder=dca --enable-libdcadec --enable-libbs2b --enable-libmfx --enable-libcdio --enable-libsnappy --enable-libwavpack --enable-libwebp --enable-libvpx --enable-opengl --enable-decklink --enable-libutvideo --enable-libgme --enable-nonfree --enable-nvenc --enable-libfdk-aac--enable-version3 --enable-filter=frei0r"
#define FFMPEG_LICENSE "nonfree and unredistributable"

Here  some options start to collide (stick together)
Maybe this can be relative simple fixed by a change in the SED command ?

Thanks  !

**Comment by wiiaboo** [comment]
Yes, should be easily fixed. Didn't test the sed enough.
