### ISSUE TITLE
FFMpeg build brokenby today Mingw updates

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#160]
After auto-updating MSYS and the rest. FFmpeg does not build anymore.
The problem is a current incompatible between FFmpeg and the todays MYS/Mingw updates.
All encoding/decoding by DXVA2 or D3D11 (hardware support) is broken.
FFMpeg talks about "ID3D11VideoContext" , but the new Mingw headers don't even know this word anymore. I don't knoow why but it sees that  Mingw did a lot of renaming in their headers.
The updates involved are:
mingw-w64-i686-headers-git-5.0.0.4573.628fdbf-1-any.pkg.tar
mingw-w64-x86_64-headers-git-5.0.0.4573.628fdbf-1-any.pkg.tar

and probably also:
mingw-w64-x86_64-crt-git-5.0.0.4573.628fdbf-1-any.pkg.tar
mingw-w64-i686-crt-git-5.0.0.4573.628fdbf-1-any.pkg.tar

The latest working version I have is:
headers-git-5.0.0.4531.49c7046-1-any.pkg.tar (both i686 and x86_64) dated 24/07/2015.

Just avoid these updates for now;  maybe ffmpeg will catch-up later, I don't know.
Although I haven't tested this myself, you can probably still build ffmpeg if you disable DXVA2 and D3D3VA :   --disable-d3d11va  --disable-dxva2 or  --disable-hwaccels (will also disable Intel's QS and NVidia's NVenc/dec). 

Here is my log from ffmpeg-build:
```
CC      ffmpeg.o
AR      libavdevice/libavdevice.a
AR      libavfilter/libavfilter.a
AR      libavformat/libavformat.a
CC      libavcodec/dxva2.o
In file included from libavcodec/dxva2_internal.h:37:0,
                 from libavcodec/dxva2.c:31:
libavcodec/d3d11va.h:66:5: error: unknown type name 'ID3D11VideoContext'
     ID3D11VideoContext *video_context;
     ^
In file included from libavcodec/dxva2.c:31:0:
libavcodec/dxva2.c: In function 'ff_dxva2_get_surface_index':
libavcodec/dxva2_internal.h:74:117: warning: pointer type mismatch in conditional expression
 #define DXVA_CONTEXT_SURFACE(avctx, ctx, i)     (avctx->pix_fmt == AV_PIX_FMT_D3D11VA_VLD ? ctx->d3d11va.surface[i] : ctx->dxva2.surface[i])
                                                                                                                     ^
libavcodec/dxva2.c:46:13: note: in expansion of macro 'DXVA_CONTEXT_SURFACE'
         if (DXVA_CONTEXT_SURFACE(avctx, ctx, i) == surface)
             ^
libavcodec/dxva2.c: In function 'ff_dxva2_commit_buffer':
libavcodec/dxva2.c:66:14: error: implicit declaration of function 'ID3D11VideoContext_GetDecoderBuffer' [-Werror=implicit-function-declaration]
         hr = ID3D11VideoContext_GetDecoderBuffer(D3D11VA_CONTEXT(ctx)->video_context,
              ^
libavcodec/dxva2.c:86:13: error: unknown type name 'D3D11_VIDEO_DECODER_BUFFER_DESC'
             D3D11_VIDEO_DECODER_BUFFER_DESC *dsc11 = dsc;
             ^
libavcodec/dxva2.c:88:18: error: request for member 'BufferType' in something not a structure or union
             dsc11->BufferType           = type;
                  ^
libavcodec/dxva2.c:89:18: error: request for member 'DataSize' in something not a structure or union
             dsc11->DataSize             = size;
                  ^
libavcodec/dxva2.c:90:18: error: request for member 'NumMBsInBuffer' in something not a structure or union
             dsc11->NumMBsInBuffer       = mb_count;
                  ^
libavcodec/dxva2.c:111:14: error: implicit declaration of function 'ID3D11VideoContext_ReleaseDecoderBuffer' [-Werror=implicit-function-declaration]
         hr = ID3D11VideoContext_ReleaseDecoderBuffer(D3D11VA_CONTEXT(ctx)->video_context, D3D11VA_CONTEXT(ctx)->decoder, type);
              ^
libavcodec/dxva2.c: In function 'ff_dxva2_common_end_frame':
libavcodec/dxva2.c:136:5: error: unknown type name 'D3D11_VIDEO_DECODER_BUFFER_DESC'
     D3D11_VIDEO_DECODER_BUFFER_DESC buffer11[4];
     ^
libavcodec/dxva2.c:149:18: error: implicit declaration of function 'ID3D11VideoContext_DecoderBeginFrame' [-Werror=implicit-function-declaration]
             hr = ID3D11VideoContext_DecoderBeginFrame(D3D11VA_CONTEXT(ctx)->video_context, D3D11VA_CONTEXT(ctx)->decoder,
                  ^
libavcodec/dxva2.c:171:16: error: 'D3D11_VIDEO_DECODER_BUFFER_PICTURE_PARAMETERS' undeclared (first use in this function)
         type = D3D11_VIDEO_DECODER_BUFFER_PICTURE_PARAMETERS;
                ^
libavcodec/dxva2.c:171:16: note: each undeclared identifier is reported only once for each function it appears in
libavcodec/dxva2.c:194:20: error: 'D3D11_VIDEO_DECODER_BUFFER_INVERSE_QUANTIZATION_MATRIX' undeclared (first use in this function)
             type = D3D11_VIDEO_DECODER_BUFFER_INVERSE_QUANTIZATION_MATRIX;
                    ^
libavcodec/dxva2.c:243:14: error: implicit declaration of function 'ID3D11VideoContext_SubmitDecoderBuffers' [-Werror=implicit-function-declaration]
         hr = ID3D11VideoContext_SubmitDecoderBuffers(D3D11VA_CONTEXT(ctx)->video_context,
              ^
libavcodec/dxva2.c:265:14: error: implicit declaration of function 'ID3D11VideoContext_DecoderEndFrame' [-Werror=implicit-function-declaration]
         hr = ID3D11VideoContext_DecoderEndFrame(D3D11VA_CONTEXT(ctx)->video_context, D3D11VA_CONTEXT(ctx)->decoder);
              ^
cc1.exe: some warnings being treated as errors
common.mak:57: recipe for target 'libavcodec/dxva2.o' failed
make: *** [libavcodec/dxva2.o] Error 1
-------------------------------------------------
Build of FFMPEG-GIT-32bit FAILED...
Delete the source folder under '/build' and start again.
If you're sure FFMPEG-GIT has no dependencies press C(ontinue) to continue building.
```

**Comment by wiiaboo** [comment]
I usually build with --disable-hwaccels so that's probably why I didn't have problems.

**Comment by jb-alvarado** [comment]
When this is about missing headers, maybe we can inform the msys2 devs and they take them back.

**Comment by pat357** [comment]
It's not really an issue about *missing* headers, more an issue off *changed* & incompatible headers.
The previous version from the MSYS/MingW headers worked fine and would work fine until ffmpeg updates their headers.
From previous experience, ffmpeg does not care too much about Mingw being able to build ffmpeg.
I really hope MSYS/Mingw will offer an easy and transparant way to go back to their previous version.

If not, Mingw builders will be without dvxa2 and D3D11 HW acceleration for a looong time.
A really bad thing for all owners from the NVdia GTX-960 thinking about the $$ they spend for this card and seeing it rotten away in their PC.

**Comment by wiiaboo** [comment]
It does care about Mingw being able to build. [It's one of the builds in FATE](http://fate.ffmpeg.org/?query=cc:gcc%204.9.3%20%28GCC%29%2F%2F). But those builds use latest stable Mingw headers (4.0.4?), not the git builds that are always getting broken once a month.

**Comment by wiiaboo** [comment]
It's bad but not the end of the world, unless you were planning to use hevc
acceleration. SW decoding isn't worse than HW. Just maybe less energy
efficient. I've notified both mingw packagers and FFmpeg. In the mean time,
d3d11va and dxva2 stay disabled.

**Comment by wiiaboo** [comment]
d3d11va is still broken but it won't stop ffmpeg building now. Now it's up to mingw packagers or mingw itself to readd the decoder properly again. dxva2 still works.
