### ISSUE TITLE
Missing Libarys in static builds

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#163]
Since the new usage of the mingw libarys, i cant launch a static ffmpeg.exe

He miss libcdio_cdda-2.dll, libcaca-0.dll, libcdio_paranoia-2.dll and libfontconfig-1.dll

**Comment by wiiaboo** [comment]
Apparently I didn't test enough with the full build in cmd.exe.

**Comment by nille02** [comment]
For now, i reverted back to bffa6485462bf1e53a3b47bb239ba75839b63b17

I setup a new environment, maybe there was a problem in the setup, from the old to the new.

**Comment by wiiaboo** [comment]
I think it's do_hide_pacman_sharedlibs() not working, not the libs themselves.
Trying again now with the fixes.

**Comment by wiiaboo** [comment]
Check if a2eaf3c9dc23b07c0a5f7bcef74ee16ef90ae255 fixed it.

**Comment by wiiaboo** [comment]
You may have to delete everything in /local32|64 to make sure all libs were compiled properly, if any is still complaining about missing .dlls.

**Comment by nille02** [comment]
yes, but he need some time ;)

**Comment by nille02** [comment]
He still miss the libs

**Comment by wiiaboo** [comment]
Even after deleting the /local folders?

**Comment by nille02** [comment]
Local64 and the git folders in build

**Comment by wiiaboo** [comment]
I still haven't finished compiling 64-bits, so I can't confirm. But does it ask for the same libs and only on ffmpeg.exe?

**Comment by nille02** [comment]
Everytime the same.

gif2webp miss libgif-7.dll
oggdec miss libvorbisfile-3.dll
oggenc miss libvorbis-0.dll and libvorbisenc-2.dll

**Comment by wiiaboo** [comment]
Make sure you have all the scripts updated and delete the /local64 folder entirely. You don't need to delete /build. Those 3 should not ask for dlls if they have been compiled correctly.

Finished 64-bit build just now and other than needing to disable tesseract all works for me.

**Comment by wiiaboo** [comment]
Run `for f in "$(find /mingw{32,64} -name *.dll.a)"; do [[ -f "$f" && -f "${f%*.dll.a}.a" ]] && echo "$f"; done` in mintty and paste the results here.

**Comment by nille02** [comment]
no result.

**Comment by wiiaboo** [comment]
Then it shouldn't be asking for dlls. If something is, you must not have deleted /local32|64 entirely to force everything to build again. I'm saying shift+delete the /local32 or /local64 folder.

**Comment by nille02** [comment]
i do this 2 times and the result is still the same. he need the dlls and your search command find nothing. its also a new setup.

**Comment by shinchiro** [comment]
In my case, even deleting /local folder did not solve problem with compilation error.
I solve by resetting the git/hg folder to its pristine state before start compile

As improvement to the script, I suggest these:
- Reset repo to its clean state by:
```
# git cleanup foreign files
git clean -f -d -x

# svn cleanup foreign files
svn cleanup --remove-unversioned --remove-ignored

# hg cleanup foreign files
hg --config "extensions.purge=" purge --all
```
- For wget package, how about copy downloaded package to a folder. Dont delete them. As compile finish, delete the wget repo folder. The next user want to compile again, copy & extract back the compressed package to /build folder.

**Comment by wiiaboo** [comment]
Sorry, I'm a fucking idiot.
Fixing now.

**Comment by wiiaboo** [comment]
76ab188340eee29be8aed6d7124b431a302cf07c simple fix but makes all the difference.

**Comment by wiiaboo** [comment]
@shinchiro 
git runs a clean checkout every time, so no need to clean.
svn would only work for mplayer and it would delete ffmpeg, forcing a reclone of it either from the web or locally and both take a shit load of time, even a shallow clone.
hg would only work for x265 and we don't touch a single file outside of /build.

The curl one can be done and only be deleted if you choose to delete sources.

**Comment by shinchiro** [comment]
git checkout only revert changes to tracked file according to current branch. 
git clean I mentioned will clean (delete) all untracked files. example, configure files, *.o files exist after configure/compile.

**Comment by wiiaboo** [comment]
There's no need to remove compiled files, we always run `make distclean` or similar. There's a lot of libs that don't have autotools stuff in the repo and it's a waste of time to generate them every time.

**Comment by nille02** [comment]
Yes its fixed now, thanks for you work.
