### ISSUE TITLE
Multiple .ini files?

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#164]
Since I wanted to change tools I build, I deleted my old .ini file, thinking that the script (like always before, would ask me what to build and create a new .ini file).
Strange thing is: It didn't ask me and now is building tools without the .ini file!
Ah,.. there is another .ini inside the build folder!
-> is it intended that there are multiple .ini files?

**Comment by wiiaboo** [comment]
There's only one .ini used. It's been changed to /build.

**Comment by Selur** [comment]
ah, okay. Thanks for clearing that up.
