### ISSUE TITLE
My FSTAB keeps growing due a bug in "media-autobuild_suite.bat"

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#168]
This is how my FSTAB currently looks like:
(Note : I added the # prefix to the extra lines that don't belong there).
On every start from "media-autobuild_suite.bat", an extra set is written to my FSTAB.

 ===============================
none / cygdrive binary,posix=0,noacl,user 0 0
K:\Mingw642\                        /trunk
K:\Mingw642\build\                  /build
K:\Mingw642\msys64\mingw32\         /mingw32
K:\Mingw642\msys64\mingw64\         /mingw64
K:\Mingw642\local32\                /local32
K:\Mingw642\local64\                /local64

#K:\Mingw642\ /trunk
#K:\Mingw642\build\ /build
#K:\Mingw642\msys64\mingw32\ /mingw32
#K:\Mingw642\msys64\mingw64\ /mingw64
#K:\Mingw642\local32\ /local32
#K:\Mingw642\local64\ /local64

#K:\Mingw642\ /trunk
#K:\Mingw642\build\ /build
#K:\Mingw642\msys64\mingw32\ /mingw32
#K:\Mingw642\msys64\mingw64\ /mingw64
#K:\Mingw642\local32\ /local32
#K:\Mingw642\local64\ /local64

#K:\Mingw642\ /trunk
#K:\Mingw642\build\ /build
#K:\Mingw642\msys64\mingw32\ /mingw32
#K:\Mingw642\msys64\mingw64\ /mingw64
#K:\Mingw642\local32\ /local32
#K:\Mingw642\local64\ /local64
==========================================================

This is why this happens:
I disabled @echo off for the responsible part of the .bat
This gives:
=========================================================
K:\Mingw642\build>if not exist K:\Mingw642\msys64\etc\fstab. GOTO writeFstab
K:\Mingw642\build>set removefstab=no
K:\Mingw642\build>for /F "tokens=2 delims=/" %b in ('findstr /i build32 K:\Mingw642\msys64\etc\fstab.') do set searchRes=oldbuild
K:\Mingw642\build>if "" == "oldbuild" set removefstab=yes
K:\Mingw642\build>for /F "tokens=2 delims=/" %a in ('findstr /i local32 K:\Mingw642\msys64\etc\fstab.') do set searchRes=%a
K:\Mingw642\build>set searchRes=local32
K:\Mingw642\build>set searchRes=local32
K:\Mingw642\build>set searchRes=local32
K:\Mingw642\build>set searchRes=local32
K:\Mingw642\build>if not "local32" == "local32" (set removefstab=yes )  else (if not yes == yes set removefstab=yes )
K:\Mingw642\build>for /F "tokens=2 delims=/" %a in ('findstr /i local64 K:\Mingw642\msys64\etc\fstab.') do set searchRes=%a
K:\Mingw642\build>set searchRes=local64
K:\Mingw642\build>set searchRes=local64
K:\Mingw642\build>set searchRes=local64
K:\Mingw642\build>set searchRes=local64
K:\Mingw642\build>if not "local64" == "local64" (set removefstab=yes )  else (if not yes == yes set removefstab=yes )
K:\Mingw642\build>for /F "tokens=2 delims=/" %a in ('findstr /i trunk K:\Mingw642\msys64\etc\fstab.') do set searchRes=%a
K:\Mingw642\build>set searchRes=trunk
K:\Mingw642\build>set searchRes=trunk
K:\Mingw642\build>set searchRes=trunk
K:\Mingw642\build>set searchRes=trunk
K:\Mingw642\build>if not "trunk" == "trunk" set removefstab=yes
K:\Mingw642\build>if no == yes (
del K:\Mingw642\msys64\etc\fstab.
 GOTO writeFstab
)
K:\Mingw642\build>if "trunk" == "local32" GOTO writeProfile32
K:\Mingw642\build>if "trunk" == "local64" GOTO writeProfile32
K:\Mingw642\build>echo -------------------------------------------------------------------------------
-------------------------------------------------------------------------------
K:\Mingw642\build>echo.
K:\Mingw642\build>echo.- write fstab mount file
- write fstab mount file
K:\Mingw642\build>echo.
K:\Mingw642\build>echo -------------------------------------------------------------------------------
-------------------------------------------------------------------------------
K:\Mingw642\build>set cygdrive=no
K:\Mingw642\build>if exist K:\Mingw642\msys64\etc\fstab. (for /F %b in ('findstr /i binary K:\Mingw642\msys64\etc\fstab.') do set cygdrive=y
es )
K:\Mingw642\build>set cygdrive=yes
=======================================================================

As you can see, no conditions are met to remove fstab, but the 2 following lines make that doesn't jump over the actual writing from fstab to  writeProfile32 or  writeProfile64 as it should do.
K:\Mingw642\build>if "trunk" == "local32" GOTO writeProfile32
K:\Mingw642\build>if "trunk" == "local64" GOTO writeProfile32

It seems that my last searchRes is "trunk" instead of local32/local64

For the moment I added a small work-around by adding
if removefstab=no GOTO writeProfile32.
Means : if the fstab is not removed, just skip the writefstab part, as this never makes sense to append something to an existing fstab. Fstab should always be deleted, before writing a new one.

Could you please look into this ?
Thanks,

Pat357

**Comment by wiiaboo** [comment]
Your post is really hard to read, can you add backticks where appropriate?
Like [this (in Code)](https://guides.github.com/features/mastering-markdown/#examples).

**Comment by pat357** [comment]
My apologies for the formatting : I'll make good looking messages from now on 
I don't know why some text is displayed with huge fonts : I didn't do that.
It seems I can not edit this text : when I press edit and want to add/delete something, the text stays as frozen. Could be due I have the Noscript addon installed in Firefox : blocks javascript and some other things.

**Comment by wiiaboo** [comment]
Probably. Since you like to use `=` and `#` as separators, those get parsed as Markdown, so that's what causes the giant text. Either use `-` instead or use three backticks to make your whole text render as you see. Or use Preview tab before commenting.

Anyway, I think I've fixed it.

**Comment by pat357** [comment]
BTW I have both 32/64 builds.

**Comment by wiiaboo** [comment]
I've tested with the three variations of both, and only 32 or 64-bits. The check should work as expected and if not it'll still delete the fstab. It was adding all those because the check for /trunk was the last one so it never deleted the fstab and never went to the proper GOTO.
