### ISSUE TITLE
FFmpeg fails to build after update from libASS (2015-09-23)

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#171]
Like the title says !
Look at https://github.com/libass/libass/commits/master.
After an update from libASS (git),  ffmpeg fails at the end when linking all libs."""
How can I go back to an earlier commit ?
Say I want commit 3e8ea94 21204b51a819d983ee1d924621259043c

I've tried 
do_vcs "https://github.com/libass/libass.git#commit=3e8ea94" libass

but I'm not sure this works with the git-hg-svn combined  VCS system...

This is the FFmpeg-build log:

GENTEXI doc/avoptions_format.texi
GENTEXI doc/avoptions_codec.texi
POD     doc/ffmpeg.pod
POD     doc/ffplay.pod
POD     doc/ffprobe.pod
POD     doc/ffmpeg-all.pod
POD     doc/ffplay-all.pod
POD     doc/ffprobe-all.pod
POD     doc/ffmpeg-utils.pod
POD     doc/ffmpeg-scaler.pod
POD     doc/ffmpeg-resampler.pod
POD     doc/ffmpeg-codecs.pod
POD     doc/ffmpeg-bitstream-filters.pod
POD     doc/ffmpeg-formats.pod
POD     doc/ffmpeg-protocols.pod
POD     doc/ffmpeg-devices.pod
POD     doc/ffmpeg-filters.pod
POD     doc/libavutil.pod
POD     doc/libswscale.pod
POD     doc/libswresample.pod
POD     doc/libavcodec.pod
POD     doc/libavformat.pod
MAN     doc/ffmpeg.1
POD     doc/libavdevice.pod
POD     doc/libavfilter.pod
MAN     doc/ffplay.1
MAN     doc/ffprobe.1
MAN     doc/ffmpeg-all.1
MAN     doc/ffplay-all.1
MAN     doc/ffprobe-all.1
MAN     doc/ffmpeg-utils.1
MAN     doc/ffmpeg-scaler.1
MAN     doc/ffmpeg-resampler.1
MAN     doc/ffmpeg-codecs.1
MAN     doc/ffmpeg-bitstream-filters.1
MAN     doc/ffmpeg-formats.1
MAN     doc/ffmpeg-protocols.1
MAN     doc/ffmpeg-devices.1
MAN     doc/ffmpeg-filters.1
MAN     doc/libavutil.3
MAN     doc/libswscale.3
MAN     doc/libswresample.3
MAN     doc/libavcodec.3
MAN     doc/libavformat.3
MAN     doc/libavdevice.3
MAN     doc/libavfilter.3
LD      ffmpeg_g.exe
LD      ffprobe_g.exe
K:/Mingw642/local32/lib/libgnutls.a(sha256-ssse3-x86.o): warning: common of `_gnutls_x86_cpuid_s' overriding smaller common
K:/Mingw642/local32/lib/libgnutls.a(x86-common.o): warning: smaller common is here
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x2b): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x6f): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0xa4): undefined reference to `ass_get_xgetbv'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0xcc): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x11c): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xc8): undefined reference to `ass_fill_solid_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xcc): undefined reference to `ass_fill_halfplane_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xd0): undefined reference to `ass_fill_generic_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xd4): undefined reference to `ass_add_bitmaps_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xe4): undefined reference to `ass_stripe_unpack_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xe8): undefined reference to `ass_stripe_pack_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xec): undefined reference to `ass_shrink_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf0): undefined reference to `ass_shrink_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf4): undefined reference to `ass_expand_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf8): undefined reference to `ass_expand_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xfc): undefined reference to `ass_pre_blur1_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x100): undefined reference to `ass_pre_blur2_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x104): undefined reference to `ass_pre_blur3_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x108): undefined reference to `ass_pre_blur1_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x10c): undefined reference to `ass_pre_blur2_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x110): undefined reference to `ass_pre_blur3_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x114): undefined reference to `ass_blur1234_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x118): undefined reference to `ass_blur1235_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x11c): undefined reference to `ass_blur1246_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x120): undefined reference to `ass_blur1234_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x124): undefined reference to `ass_blur1235_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x128): undefined reference to `ass_blur1246_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x148): undefined reference to `ass_fill_solid_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x14c): undefined reference to `ass_fill_halfplane_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x150): undefined reference to `ass_fill_generic_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x154): undefined reference to `ass_add_bitmaps_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x164): undefined reference to `ass_stripe_unpack_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x168): undefined reference to `ass_stripe_pack_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x16c): undefined reference to `ass_shrink_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x170): undefined reference to `ass_shrink_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x174): undefined reference to `ass_expand_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x178): undefined reference to `ass_expand_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x17c): undefined reference to `ass_pre_blur1_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x180): undefined reference to `ass_pre_blur2_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x184): undefined reference to `ass_pre_blur3_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x188): undefined reference to `ass_pre_blur1_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x18c): undefined reference to `ass_pre_blur2_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x190): undefined reference to `ass_pre_blur3_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x194): undefined reference to `ass_blur1234_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x198): undefined reference to `ass_blur1235_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x19c): undefined reference to `ass_blur1246_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a0): undefined reference to `ass_blur1234_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a4): undefined reference to `ass_blur1235_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a8): undefined reference to `ass_blur1246_vert_sse2'
collect2.exe: error: ld returned 1 exit status
Makefile:126: recipe for target 'ffplay_g.exe' failed
make: *** [ffplay_g.exe] Error 1
make: *** Waiting for unfinished jobs....
K:/Mingw642/local32/lib/libgnutls.a(sha256-ssse3-x86.o): warning: common of `_gnutls_x86_cpuid_s' overriding smaller common
K:/Mingw642/local32/lib/libgnutls.a(x86-common.o): warning: smaller common is here
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x2b): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x6f): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0xa4): undefined reference to `ass_get_xgetbv'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0xcc): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x11c): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xc8): undefined reference to `ass_fill_solid_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xcc): undefined reference to `ass_fill_halfplane_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xd0): undefined reference to `ass_fill_generic_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xd4): undefined reference to `ass_add_bitmaps_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xe4): undefined reference to `ass_stripe_unpack_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xe8): undefined reference to `ass_stripe_pack_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xec): undefined reference to `ass_shrink_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf0): undefined reference to `ass_shrink_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf4): undefined reference to `ass_expand_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf8): undefined reference to `ass_expand_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xfc): undefined reference to `ass_pre_blur1_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x100): undefined reference to `ass_pre_blur2_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x104): undefined reference to `ass_pre_blur3_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x108): undefined reference to `ass_pre_blur1_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x10c): undefined reference to `ass_pre_blur2_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x110): undefined reference to `ass_pre_blur3_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x114): undefined reference to `ass_blur1234_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x118): undefined reference to `ass_blur1235_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x11c): undefined reference to `ass_blur1246_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x120): undefined reference to `ass_blur1234_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x124): undefined reference to `ass_blur1235_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x128): undefined reference to `ass_blur1246_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x148): undefined reference to `ass_fill_solid_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x14c): undefined reference to `ass_fill_halfplane_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x150): undefined reference to `ass_fill_generic_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x154): undefined reference to `ass_add_bitmaps_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x164): undefined reference to `ass_stripe_unpack_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x168): undefined reference to `ass_stripe_pack_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x16c): undefined reference to `ass_shrink_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x170): undefined reference to `ass_shrink_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x174): undefined reference to `ass_expand_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x178): undefined reference to `ass_expand_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x17c): undefined reference to `ass_pre_blur1_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x180): undefined reference to `ass_pre_blur2_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x184): undefined reference to `ass_pre_blur3_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x188): undefined reference to `ass_pre_blur1_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x18c): undefined reference to `ass_pre_blur2_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x190): undefined reference to `ass_pre_blur3_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x194): undefined reference to `ass_blur1234_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x198): undefined reference to `ass_blur1235_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x19c): undefined reference to `ass_blur1246_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a0): undefined reference to `ass_blur1234_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a4): undefined reference to `ass_blur1235_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a8): undefined reference to `ass_blur1246_vert_sse2'
collect2.exe: error: ld returned 1 exit status
Makefile:126: recipe for target 'ffmpeg_g.exe' failed
make: *** [ffmpeg_g.exe] Error 1
K:/Mingw642/local32/lib/libgnutls.a(sha256-ssse3-x86.o): warning: common of `_gnutls_x86_cpuid_s' overriding smaller common
K:/Mingw642/local32/lib/libgnutls.a(x86-common.o): warning: smaller common is here
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x2b): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x6f): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0xa4): undefined reference to `ass_get_xgetbv'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0xcc): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_utils.o):ass_utils.c:(.text+0x11c): undefined reference to `ass_get_cpuid'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xc8): undefined reference to `ass_fill_solid_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xcc): undefined reference to `ass_fill_halfplane_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xd0): undefined reference to `ass_fill_generic_tile16_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xd4): undefined reference to `ass_add_bitmaps_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xe4): undefined reference to `ass_stripe_unpack_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xe8): undefined reference to `ass_stripe_pack_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xec): undefined reference to `ass_shrink_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf0): undefined reference to `ass_shrink_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf4): undefined reference to `ass_expand_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xf8): undefined reference to `ass_expand_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0xfc): undefined reference to `ass_pre_blur1_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x100): undefined reference to `ass_pre_blur2_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x104): undefined reference to `ass_pre_blur3_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x108): undefined reference to `ass_pre_blur1_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x10c): undefined reference to `ass_pre_blur2_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x110): undefined reference to `ass_pre_blur3_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x114): undefined reference to `ass_blur1234_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x118): undefined reference to `ass_blur1235_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x11c): undefined reference to `ass_blur1246_horz_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x120): undefined reference to `ass_blur1234_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x124): undefined reference to `ass_blur1235_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x128): undefined reference to `ass_blur1246_vert_avx2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x148): undefined reference to `ass_fill_solid_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x14c): undefined reference to `ass_fill_halfplane_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x150): undefined reference to `ass_fill_generic_tile16_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x154): undefined reference to `ass_add_bitmaps_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x164): undefined reference to `ass_stripe_unpack_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x168): undefined reference to `ass_stripe_pack_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x16c): undefined reference to `ass_shrink_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x170): undefined reference to `ass_shrink_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x174): undefined reference to `ass_expand_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x178): undefined reference to `ass_expand_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x17c): undefined reference to `ass_pre_blur1_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x180): undefined reference to `ass_pre_blur2_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x184): undefined reference to `ass_pre_blur3_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x188): undefined reference to `ass_pre_blur1_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x18c): undefined reference to `ass_pre_blur2_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x190): undefined reference to `ass_pre_blur3_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x194): undefined reference to `ass_blur1234_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x198): undefined reference to `ass_blur1235_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x19c): undefined reference to `ass_blur1246_horz_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a0): undefined reference to `ass_blur1234_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a4): undefined reference to `ass_blur1235_vert_sse2'
K:/Mingw642/local32/lib/libass.a(ass_bitmap.o):ass_bitmap.c:(.rdata+0x1a8): undefined reference to `ass_blur1246_vert_sse2'
collect2.exe: error: ld returned 1 exit status
Makefile:126: recipe for target 'ffprobe_g.exe' failed
make: *** [ffprobe_g.exe] Error 1

**Comment by wiiaboo** [comment]
That shouldn't be related to the latest commits.
Can't reproduce with my normal build.
Have you tried deleting libass-git and running `rm -rf $LOCALDESTDIR/include/ass $LOCALDESTDIR/lib/libass.{,l}a $LOCALDESTDIR/lib/pkgconfig/libass.pc` manually?

**Comment by wiiaboo** [comment]
Yeah, even with 32-bit build can't reproduce that.

**Comment by nille02** [comment]
Fresh build runs fine on my side

**Comment by pat357** [comment]
It was exactly the problem that Wiiaboo said.

In our script:
 if [[ $compile = "true" || $buildLibass = "y" ]]; then
        if [[ ! -f "configure" ]]; then
            autoreconf -fiv
        else
            rm -rf $LOCALDESTDIR/include/ass
            rm -f $LOCALDESTDIR/lib/libass.a $LOCALDESTDIR/lib/pkgconfig/libass.pc
            make distclean
        fi
If there is no configure script, the existing LibASS installation ( in include/lib) is not removed.
Better would be :+1: 
 if [[ $compile = "true" || $buildLibass = "y" ]]; then
        [[ ! -f "configure" ]]  && autoreconf -fiv || make distclean
        [[ -f $LOCALDESTDIR/lib/libass.a ]] && rm -rf $LOCALDESTDIR/include/ass \
         $LOCALDESTDIR/lib/libass.{,l}a{,dyn}   $LOCALDESTDIR/lib/pkgconfig/libass.pc

Please consider this change in the script, it would be more logical.

Pat357

**Comment by wiiaboo** [comment]
Weird that it worked fine for me for some reason.
