### ISSUE TITLE
When was mkvtoolnix dropped?

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#176]
Kind of missed that mkvtoolnix wasn't build anymore.
Any plans to add it again?

**Comment by wiiaboo** [comment]
Git log --grep=mkvtoolnix.
No. We didn't add anything to the builds that the officials didn't have. It
didn't work as well. The official source also builds regular nightlies. And
above all, only the official windows builds were supported.

**Comment by wiiaboo** [comment]
`git log --grep=mkvtoolnix` on `/trunk`.

No. We didn't add anything to the builds that the officials didn't have and it had bugs the officials didn't.
The official site also builds [regular nightlies](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/). And above all, only the official windows builds add supported, so issues with ours will always be ignored. So no, possibly never, nor there needs to be. Same with VideoLAN.
