### ISSUE TITLE
bat will not run the compile script

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#177]
bat will not run the compile script with --rtmpdump flag enabled in the start section at the end.
mintty just closes.
If --rtmpdump commented out it runs fine.

**Comment by wiiaboo** [comment]
I can't find any reason why it wouldn't work. Did you make sure everything is updated?

**Comment by wiiaboo** [comment]
Until we find a way to reliably update all the scripts needed, you have to download the whole repo before running a build, not just the .bat.

**Comment by hekitoshinoda** [comment]
Hi.
I usually update the .bat and the compile/helper/update.sh and that worked
just fine in the past.
The Repo (*.zip) isn't updated as frequently as the single files.

Anyway, if I use the Repo, do I have to dl all the stuff again in the
single subfolders?
Or will it be just updated as well?

Not wan't to trouble someone, I like these script, good work!


2015-10-10 14:06 GMT+02:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/archive/master.zip is always updated.
