### ISSUE TITLE
compiling ffmpeg troubles often

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#178]
compiling ffmpeg troubles often, just now with:

]0;compiling static FFmpeg 64bit[31m[1mERROR: kvazaar not found using pkg-config(B[m

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
Makefile:2: config.mak: No such file or directory
Makefile:62: /common.mak: No such file or directory
Makefile:104: /libavutil/Makefile: No such file or directory
Makefile:104: /library.mak: No such file or directory
Makefile:106: /doc/Makefile: No such file or directory
Makefile:189: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:62: /common.mak: No such file or directory
Makefile:104: /libavutil/Makefile: No such file or directory
Makefile:104: /library.mak: No such file or directory
Makefile:106: /doc/Makefile: No such file or directory
Makefile:189: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.

however kvazaar ist there and already compiled

**Comment by wiiaboo** [comment]
Check #177 
It's clear that you didn't update the scripts.
