### ISSUE TITLE
Issue with the msys update

### ISSUE THREAD

**Issue by sarbjit-longia** [jb-alvarado/media-autobuild_suite#181]
I am trying to build the tools after downloading the latest from git but somehow the script is giving issues. 

First I had to resolve the ")" issue in following command 

    for /F %%b in ( '%instdir%\build\wget -qO- http://sourceforge.net/projects/msys2/files/Base/i686/ ^| %instdir%\build\grep -o -P "(?<=tr title=).*(?<=class=)" ^| %instdir%\build\grep -m 1 -o "msys2-base-i686-*.*tar.xz"' ) do %instdir%\build\wget --tries=20 --retry-connrefused --waitretry=2 -c -O msys2-base.tar.xz http://sourceforge.net/projects/msys2/files/Base/i686/%%b/download)

Somehow the last ")" in new line was not right and i had to move it to previous line. After that the using pacman to update msys is not working fine. I am wondering if I am doing anything wrong.

**Comment by wiiaboo** [comment]
I can't find that line anywhere. You're probably using an old version of the scripts.

**Comment by sarbjit-longia** [comment]
I will update it and give it a try

**Comment by sarbjit-longia** [comment]
I got the latest and got this error again:

======================================================
- Download wget

-------------------------------------------------------------
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

retrieving http://blog.pixelcrusher.de/downloads/media-autobuild_suite/wget.zip
-------------------------------------------------------------------------------

- Download and install msys2 basic system

-------------------------------------------------------------------------------
( was unexpected at this time.
====================================================

**Comment by wiiaboo** [comment]
OK, it only happened when first creating the .ini file. As long as you didn't delete it would run fine after that problem.

**Comment by sarbjit-longia** [comment]
Hi Ricardo,

Can you please share your email, I wanted to talk to you about something.

Thanks,
Sarbjit

**Comment by wiiaboo** [comment]
I've made it temporarily public in my profile.
