### ISSUE TITLE
LGPL build not easy

### ISSUE THREAD

**Issue by sarbjit-longia** [jb-alvarado/media-autobuild_suite#182]
Script imposes --enable-gpl by default which makes it difficult to to build LGPL FFmpeg. Also the dependent libraries like librtmp, libsox which are LGPL is built static which will again violate the license.

Would be better if system has an option to build LGPL FFmpeg libraries.

**Comment by wiiaboo** [comment]
LGPL FFmpeg wasn't considered because it loses a lot of stuff. Non-free is
dealt with if you check helper.sh code. If you choose to not use non-free,
FFmpeg won't use certain libs.

**Comment by sarbjit-longia** [comment]
Thats ok, but if we need to use it in commercial software gpl is not an option. We are ok to loose certain libraries but need LGPL based ffmpeg thats the reason I am looking for this.

**Comment by sarbjit-longia** [comment]
btw I must say that the script is pretty good..you really did a great job here.

**Comment by wiiaboo** [comment]
It's way too late for me to change anything right now. I'm half asleep. If
you're in a hurry with the build, just remove --enable-gpl in the beginning
of compile.sh and remove --enable-* flags until configure stops
complaining. Or search FFmpeg's configure for "enabled gpl" and you'll
eventually find all the libs that depend on gpl, like x264 and x265.

**Comment by sarbjit-longia** [comment]
I understand and that's what I am doing right now. I appreciate your help and please go to sleep, I will talk tomorrow. I might have a project for you if you interested.

Have a nice night

**Comment by sarbjit-longia** [comment]
Thank you, you are awesome
