### ISSUE TITLE
Calling autosuite update fails

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#183]
After setting up the compiling options (didn't run the suite for a month), the update step failed. Here is the content of the batch console in a second run:

    -------------------------------------------------------------------------------
    update autobuild suite
    -------------------------------------------------------------------------------

And this dialog popped up:

    ---------------------------
    mintty
    ---------------------------
    /trunk/msys64/usr/bin/mintty: unknown option '-d'
    Try '--help' for more information.
    
    ---------------------------
    OK   
    ---------------------------

I wonder why I did not have to configure it again in a second run, because it did not write a new `media-autobuild_suite.ini` in the main directory ... ah, this appears to be stored in the `build` directory now.

**Comment by wiiaboo** [comment]
It's right there in the Known Issues.

**Comment by LigH-de** [comment]
So, shall I try to start over in a fresh directory?

**Comment by wiiaboo** [comment]
That works too. Though not needed if you just update mintty.

**Comment by LigH-de** [comment]
I would like to do that but can't find a current version.

https://code.google.com/p/mintty/ is obsolete.

https://mintty.github.io/ contains no binary downloads. It reports:

> In MSYS, the mintty package can be installed with the command "mingw-get install mintty".

But your MSYS installation does not provide the command `mingw-get`.

**Comment by wiiaboo** [comment]
What do you mean? Look at Readme.md. The instructions to fix it are right there.

**Comment by LigH-de** [comment]
I am sorry, I did not reason that "Known issues" is a chapter in the README.md; and I don't even know which application is used to display any *.md file under Windows.

Thank you, now I will try this solution.

**Comment by wiiaboo** [comment]
Notepad is fine.

**Comment by LigH-de** [comment]
Me dumb, that was "hidden in plain sight"...

The manual update of mintty worked well. The suite runs.
