### ISSUE TITLE
XP compatibility,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#184]
Doing some testing atm.  and decklink and opencl support need to be removed from the ffmpeg support for XP compatibility.

**Comment by Selur** [comment]
nope, still not enough,.. will do some more testing and report back I figured out which plugins need to be removed,..

**Comment by wiiaboo** [comment]
Probably tesseract too then.

**Comment by Selur** [comment]
atm. I'm building without libcac since that was my next choice it that doesn't help, I'll also remove tesseract, will report back once I know which libraries are problematic

**Comment by Selur** [comment]
=> removing decklink, opencl and libcaca fixes the issue
my ffmpeg_options.txt now looks like this::
``
--enable-gnutls
--enable-frei0r
--enable-libbluray
--enable-libass
--enable-libgsm
--enable-libilbc
--enable-libmodplug
--enable-libmp3lame
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-libvo-amrwbenc
--enable-libschroedinger
--enable-libsoxr
--enable-libtwolame
--enable-libspeex
--enable-libtheora
--enable-libvorbis
--enable-libopus
--enable-libvidstab
--enable-libxavs
--enable-libxvid
--enable-libtesseract
--enable-libzvbi
--enable-libdcadec
--enable-libbs2b
--enable-libcdio
--enable-libfreetype
--enable-fontconfig
--enable-libfribidi
--enable-opengl
--enable-libvpx
--enable-libx264
--enable-libkvazaar
--enable-libwebp
--enable-libgme
--enable-librubberband
--disable-w32threads
--enable-libzimg
``
-> would be nice if the xp compatibility option could automatically also remove the mentioned libraries

Cu Selur

**Comment by wiiaboo** [comment]
But did libcaca work before?

**Comment by Selur** [comment]
To be frank: no clue, since I normally didn't include it since I didn't have any use for it's functionality.
(searched the script folder for all files containing 'vsnprintf_s' and libcaca.a was the only one left which had it that didn't look like a part of mingw )

**Comment by wiiaboo** [comment]
If you know of any more libs that don't work with XP, let me know, reopen this.

**Comment by Selur** [comment]
will report if I run into any other incompatibilities
