### ISSUE TITLE
FFmpeg fails to build after update from VPX

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#185]
Like the title says.
This is the relevant part from the FFMpeg build log:

CC      libavcodec/libvpxenc.o
CC      libavcodec/libwavpackenc.o
CC      libavcodec/libwebpenc.o
libavcodec/libvpxenc.c:107:6: error: 'VP8E_UPD_ENTROPY' undeclared here (not in a function)
     [VP8E_UPD_ENTROPY]           = "VP8E_UPD_ENTROPY",
     ^
libavcodec/libvpxenc.c:107:6: error: array index in initializer not of integer type
libavcodec/libvpxenc.c:107:6: note: (near initialization for 'ctlidstr')
libavcodec/libvpxenc.c:108:6: error: 'VP8E_UPD_REFERENCE' undeclared here (not in a function)
     [VP8E_UPD_REFERENCE]         = "VP8E_UPD_REFERENCE",
      ^
libavcodec/libvpxenc.c:108:6: error: array index in initializer not of integer type
libavcodec/libvpxenc.c:108:6: note: (near initialization for 'ctlidstr')
libavcodec/libvpxenc.c:109:6: error: 'VP8E_USE_REFERENCE' undeclared here (not in a function)
     [VP8E_USE_REFERENCE]         = "VP8E_USE_REFERENCE",
      ^
libavcodec/libvpxenc.c:109:6: error: array index in initializer not of integer type
libavcodec/libvpxenc.c:109:6: note: (near initialization for 'ctlidstr')
common.mak:57: recipe for target 'libavcodec/libvpxenc.o' failed
make: *** [libavcodec/libvpxenc.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by wiiaboo** [comment]
Not our bug and should be fixed already in http://git.videolan.org/?p=ffmpeg.git;a=commit;h=6540fe04a3f9a11ba7084a49b3ee5fa2fc5b32ab

**Comment by tekmunki** [comment]
Like @wiiaboo stated it looks like the commit hasn't trickled down yet so if you do a brew reinstall --HEAD ffmpeg it will build fine.  Just had to do that on my system to keep some conversions going.
