### ISSUE TITLE
Kvazaar build problem

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#186]
There seems to be an issue with Kvazaar, since I'm not totally sure whether this is the fault of the script or of the Kvazaar source code I post this and also posted it to their bug trackter, see: https://github.com/ultravideo/kvazaar/issues/110

see, the compile.log: https://pastee.org/z76xk

**Comment by wiiaboo** [comment]
That's weird. It seems to be using the wrong flag when compiling that particular file.

**Comment by wiiaboo** [comment]
Have you tried deleting kvazaar-git?

**Comment by wiiaboo** [comment]
I'm not near a pc now so I can't test, but it should work now.
