### ISSUE TITLE
[Question] About ffmpeg patches

### ISSUE THREAD

**Issue by shinchiro** [jb-alvarado/media-autobuild_suite#187]
I just want to ask. Where do you get these ffmpeg's unofficial patches (the hevc one) which can be merged with official ffmpeg git? Because I looking around the web but cannot find it anywhere..

**Comment by wiiaboo** [comment]
Uh, it's right there in the commit message inside that patch (https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/patches/ffmpeg-0002-add-openhevc-intrinsics.patch#L6)
In that case it's not originally a single patch, I just merged the four commits to be simpler to apply.
The first one is based on https://github.com/lachs0r/mingw-w64-cmake/blob/master/packages/ffmpeg-0001-Use-pkg-config-for-more-external-libs.patch with my addition of twolame.
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/patches/ffmpeg-0003-avformat-implement-SChannel.patch is from the same repo as the openhevc one and the fourth one is mine to make rtmpe work with SChannel.

The other patches look for the commit that added them and probably tells where it's from.
bs2b patches, libjpeg and openjpeg "libs only" patches are mine.

**Comment by shinchiro** [comment]
Oh I see. I thought you get the ffmpeg patches from some mailing list which
I'm not fully aware since the submiter's name is not you. Its from hendrik
