### ISSUE TITLE
libbluray stuck,....

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#188]
https://pastee.org/wjpv is stuck at:

autoreconf: running: aclocal --force -I m4

(already tried aborting and deleting the libbluray-git folder)

**Comment by wiiaboo** [comment]
Can't reproduce with either 32-bit or 64-bit.
Have you tried restarting? Maybe some process is still open and preventing stuff from working.

**Comment by Selur** [comment]
restarted windows, deleted the libburay-git folder, restarted the script
-> stuck at the same place again :(
here's my ini
> [compiler list]
msys2Arch=2
arch=1
license=2
vpx=1
x264=4
xpcomp=1
x265=7
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
rtmpdump=2
mplayer=1
mpv=2
cores=8
deleteSource=1
strip=1
pack=2

and my ffmpeg_options:
> --enable-gnutls
--enable-frei0r
--enable-libbluray
--enable-libass
--enable-libgsm
--enable-libilbc
--enable-libmodplug
--enable-libmp3lame
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-libvo-amrwbenc
--enable-libschroedinger
--enable-libsoxr
--enable-libtwolame
--enable-libspeex
--enable-libtheora
--enable-libvorbis
--enable-libopus
--enable-libvidstab
--enable-libxavs
--enable-libxvid
--enable-libtesseract
--enable-libzvbi
--enable-libdcadec
--enable-libbs2b
--enable-libcdio
--enable-libfreetype
--enable-fontconfig
--enable-libfribidi
--enable-opengl
--enable-libvpx
--enable-libx264
--enable-libkvazaar
--enable-libwebp
--enable-libgme
--enable-librubberband
--disable-w32threads
--enable-libzimg

may be that helps to reproduce the problem.
(if you still can't reproduce the problem, I'll delete the whole media-autobuild_suite, make a new checkout and start from zero)

**Comment by wiiaboo** [comment]
Yeah, I can reproduce after all, after the updates.

**Comment by pat357** [comment]
I spent a whole evening trying to figure this out. Trying out earlier versions from libbluray....
Reinstalled all updates, but no avail. Then I reinstalled all the automake & autoconf versions, no avail.
Then I reinstalled all MSYS programs and you can guess: still nothing.
On my other system ( with updates blocked) everything is still working.
I think it's the new BASH ...

**Comment by pat357** [comment]
BTW, it also stalls the system on make distclean or even make clean.
If you can get over this, you can sucesful run Configure (copy from other system), but upon trying to compile this sucker, it hangs again on alocal..
There's currently no way to compile this program !!

**Comment by wiiaboo** [comment]
Msys2 managed to break everything again. They're very good at that.
It's not bash, it's msys2-runtime.

**Comment by wiiaboo** [comment]
`pacman -U $(ls /var/cache/pacman/pkg/msys2-runtime-2.2* | tail -1)` to downgrade the latest working version.
I'd recommend not running the script until this is working, but if you want to run the script meanwhile:
 - 1. Remove `#` from before "IgnorePkg" inside msys64/etc/pacman.conf
 - 2. Change line from `IgnorePkg = ` to `IgnorePkg = msys2-runtime` and save
 - 3. Remember to revert this process when/if this is fixed later

**Comment by pat357** [comment]
Thanks for the almost instantaneous (temporal, but working) solution !! You ARE really fast at such things ! 
I hope it won't take too long before MSYS2 is fixed, because a lot more packages then libbluray alone are affected.

**Comment by wiiaboo** [comment]
More of a bandaid than a solution. I fail to understand their need to always force unstable packages.

**Comment by pat357** [comment]
Yeah, introducing an alfa and beta stage is usual no luxury for software development.
For alfa, only a small group has access, for beta everyone has access on specific request.
After a minimum time in alfa/beta it should become the default for everyone.

What they do now is straight alfa and set it to the default for everyone.
It's not likely they did test this new MSYS2 much, as such bugs are easy to spot.

**Comment by wiiaboo** [comment]
Seems fixed with the latest version of msys2-runtime, can you check as well?

**Comment by Selur** [comment]
how do I tell the script that it is okay to update?
atm. I see:
> :: Starting full system upgrade...
warning: msys2-runtime: ignoring package upgrade (2.3.0.16690.4930b0d-1 => 2.3.0.16701.d6cd1b3-1)
 there is nothing to do
:: Starting full system upgrade...
warning: msys2-runtime: ignoring package upgrade (2.3.0.16690.4930b0d-1 => 2.3.0.16701.d6cd1b3-1)
 there is nothing to do

and libbluray is still stuck

**Comment by wiiaboo** [comment]
Update the script.

**Comment by Selur** [comment]
Updated, deleted the libbluray-git folder, now it  not stuck anymore. :)
Thanks!
