### ISSUE TITLE
Can't build Tesseract anymore after commit d69965c (= the latest that works)

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#189]
Not a brand new  bug, has nothing to do with system updates:

During compilation I get the following error:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../vs2010/port -DWINDLLNAME=\"libtesseract\" -I/local32/include -D__USE_MINGW_ANSI_STDIO=1 -I/local32/include/leptonica -mms-bitfields -IK:/Mingw642/local32/include -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include/cairo -IK:/Mingw642/msys64/mingw32/include/glib-2.0 -IK:/Mingw642/msys64/mingw32/lib/glib-2.0/include -IK:/Mingw642/msys64/mingw32/include/pixman-1 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -m32 -I/local32/include -mthreads -mtune=generic -O2 -pipe -std=c++11 -MT tessdatamanager.lo -MD -MP -MF .deps/tessdatamanager.Tpo -c tessdatamanager.cpp -o tessdatamanager.o
scanutils.cpp:42:14: error: conflicting declaration 'typedef long int off_t'
 typedef long off_t;
              ^
In file included from K:/Mingw642/msys64/mingw32/i686-w64-mingw32/include/stdio.h:80:0,
                 from scanutils.cpp:32:
K:/Mingw642/msys64/mingw32/i686-w64-mingw32/include/_mingw_off_t.h:24:17: note: previous declaration as 'typedef off64_t off_t'
 typedef off64_t off_t;
                 ^
Makefile:579: recipe for target 'scanutils.lo' failed
make[3]: *** [scanutils.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../vs2010/port -DWINDLLNAME=\"libtesseract\" -I/local32/include -D__USE_MINGW_ANSI_STDIO=1 -I/local32/include/leptonica -mms-bitfields -IK:/Mingw642/local32/include -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include/cairo -IK:/Mingw642/msys64/mingw32/include/glib-2.0 -IK:/Mingw642/msys64/mingw32/lib/glib-2.0/include -IK:/Mingw642/msys64/mingw32/include/pixman-1 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -m32 -I/local32/include -mthreads -mtune=generic -O2 -pipe -std=c++11 -MT tprintf.lo -MD -MP -MF .deps/tprintf.Tpo -c tprintf.cpp -o tprintf.o
make[3]: Leaving directory '/build/tesseract-git/ccutil'
Makefile:621: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/build/tesseract-git/ccutil'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git'
Makefile:387: recipe for target 'all' failed
make: *** [all] Error 2

It seems that Mingw has a problem with 'typedef long int off_t'.
I think it's relative easy to fix this or in the source or at configure level (just make that it does not detect support for 'typedef long off_t)
I locked it on the latest working commit:
do_vcs "https://github.com/tesseract-ocr/tesseract.git#commit=d69965c" tesseract

Can you replicate this ?

**Comment by wiiaboo** [comment]
You should probably this to them, since it's not related to the suite.

**Comment by wiiaboo** [comment]
Seems it needed autogen.sh to be run.
