### ISSUE TITLE
Not an issue, but a question about the license status from librtmp

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#190]
Is librtmp GPL or non-free ?
Does it depend on how it's compiled ? ie with GNUTLS or OPENSSL ?

I didn't see it listed in do_changeFFmpegConfig under GPL or non-free

**Comment by wiiaboo** [comment]
FFmpeg's configure doesn't say anything about it, so I don't know. IANAL.
But the script already recompiles librtmp if you use OpenSSL so I think
it's safe. If you use GnuTLS in FFmpeg librtmp will be recompiled to use
GnuTLS and vice-versa.

**Comment by wiiaboo** [comment]
As for rtmpdump, no idea whatsoever.

**Comment by wiiaboo** [comment]
Turns out OpenSSL was being used if --enable-gnutls was missing, thanks for making me look.

**Comment by pat357** [comment]
It's a bit strange that ffmpeg binaries compiled with librtmp (or even rtmpdump) (compiled with Openssl)  can be free distributed while Openssl is non-free.
Normal if you distribute binaries based on different libs, you'll end up with the most limited licence.
So the above case with ffmpeg, the binaries will in fact become non-free, ie non-distributable.

**Comment by wiiaboo** [comment]
┐(-｡ｰ;)┌
This suite won't knowingly create gpl-violating binaries at least afaik.
