### ISSUE TITLE
oggenc is broken somehow

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#193]
if I use:
``` 
ffmpeg -y -threads 8 -loglevel fatal -i "H:\Output\iId_1_aid_1_19_25_12_5110_01.mp3" -ac 2 -ar 48000 -f sox - | sox --multi-threaded --ignore-length --temp "H:\Temp" --buffer 524288 -S -t sox - -t flac - gain -n | oggenc --quiet --ignorelength -b 128 --utf8 -o "H:\Output\iId_1_aid_1_19_25_12_5110_02.ogg" -
```
oggenc crashes, when I on the other hand use oggenc2 from http://www.rarewares.org/ogg-oggenc.php everything works as it should.

**Comment by wiiaboo** [comment]
I don't think that's an appropriate bug to file here?
It's not a crash in compiling so why would it be the script's fault?

**Comment by Selur** [comment]
Reported it here since this did work before with the oggenc version that came out of the script. (since I don't use oggenc that often, I do not care much just wanted to let you know)

**Comment by wiiaboo** [comment]
Before doesn't say anything. Before what?

**Comment by Selur** [comment]
Haven't used oggenc for probably half a year, so can't say for sure.

**Comment by wiiaboo** [comment]
They're different programs too. Maybe Windows oggenc doesn't like stdin. Doesn't seem to crash with regular files.
Unless you're saying another compilation of vorbis-tools 1.4.0 behaves differently from one compiled with this suite, it's not our problem.

**Comment by Selur** [comment]
Like I wrote before, don't care that much about it, so sorry for disturbing you.

**Comment by wiiaboo** [comment]
Don't worry about it.
Sox and FFmpeg can perfectly decode and encode mp3 and ogg, btw.

**Comment by Selur** [comment]
> Sox and FFmpeg can perfectly decode and encode mp3 and ogg, btw.

only if they are compiled to do so,.... (+ I normally write my scripts&tools to run on mac&linux too, not just Windows so it's normally a good idea to be flexible)

**Comment by wiiaboo** [comment]
Nope, still broken in git.
If you eventually care enough about it, report it directly to them.

**Comment by wiiaboo** [comment]
@Selur have you tried since https://git.xiph.org/?p=vorbis-tools.git;a=commit;h=ef04f23e8eeb269bd98a2b0922b7e8183cdcd8ca ?
