### ISSUE TITLE
"Stripping binaries and libs" not working,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#195]
Tried it two times today and the compile.log does mention 

Stripping 64bit binaries
and
Stripping binaries and libs... done!

But for example ffmpeg is 135 MB in size, compared to the normal 35 MB.

**Comment by wiiaboo** [comment]
You have to add `--disable-debug` to your ffmpeg_options.txt. It was moved from the base to default options so people could do debug builds if they wanted. Stripping is disabled for ffmpeg/ffprobe because I had problems with trying to run debug builds that were stripped.
