### ISSUE TITLE
What happend to libutvideo ?

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#197]
Seems like current builds do not include '--enable-libutvideo', is there a reason for this?
(I see that utvideo is still supported (ffmpeg -codecs), but why not use libutvideo ?

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/wiki/FFmpeg-external-libraries
> FFmpeg has a compliant and faster native decoder and encoder

so it's not on by default. But you can add it if you really really want it for some reason.
