### ISSUE TITLE
"grep: unknown option..." error after 0f71312 commit

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#198]
Hi.
To resolve error, in media-suite_helper.sh line 345
            "if grep -qE "$option2" <(echo "$FFMPEG_OPTS"); then"
need to be changed to:
            "if grep -q -E -e "$option2" <(echo "$FFMPEG_OPTS"); then"
What do you think?
regards,

laurb

**Comment by wiiaboo** [comment]
Right, should've tested. It's interpreting ffmpeg's options as normal options, so it does need the -e.
