### ISSUE TITLE
incompatible libs for 64bit since adding autoreconf -fi

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#200]
This is probably only an issue for people who compile both 32bit and 64bit libs in a single session, like I do.

Can anyone replicate this ?

https://gist.github.com/pat357/8cfcd608f598db4df748

**Comment by pat357** [comment]
Alternative link : http://sprunge.us/CiIe
Notice the warning from libtool when installing the 64bit lib : 
libtool: warning: remember to run 'libtool --finish /local32/lib'

**Comment by wiiaboo** [comment]
I tried to only change autogen.sh to autoreconf if the file only had that,
but i didn't test every one. Not near a pc now

**Comment by pat357** [comment]
If anyone else is bumping against the same issue, here is a working solution:
replace the 2 lines
autoreconf -fi
[[ -f Makefile ]] && make distclean

by this
[[ -f Makefile ]] && make distclean
[[ $bits = 32bit || $build32 = n* ]] && autoreconf -fi

So make distclean must be first and autoreconf -fi is only run the first time in case build32=yes and build64=yes.
Running autoreconf twice (for 32 bit and for 64 bit also) makes not much sense and makes things only slower.

**Comment by wiiaboo** [comment]
It probably happens because some autoreconfs run `configure`, so that may be messing with some things. But yes, autoreconf/autogen should only be run once per update.

**Comment by wiiaboo** [comment]
And `make distclean` shouldn't be run before the autoreconf/autogen, since that might trigger a second autoreconf if autotools files were modified by a new commit.

**Comment by wiiaboo** [comment]
Probably fixed.
I tested before and didn't have any issues, so if latest commits fix anything could you check yourself?

**Comment by pat357** [comment]
I tested it atm : there still are some issues.
When the compilation directory in is not right under build (like in a deeper sub-directory), autoreconf is never executed because the "build_succesfull*" files are not found. The latter are always in the root dir from the project, right under /build/xxx-git.

This affects all packages where we do a "cd subdir" : Zenlib, libmediainfo, mediainfo, ...

**Comment by pat357** [comment]
BTW the same way is the file "recently_updated" not found, because it's a parent dir (are a parent from a parent..) then where you were looking.

This is easy to solve this way:
do_autoreconf() {
     local pdir=${PWD#*/build/}
     pdir=${pdir%%/*}

if [[ -f /build/$pdir/recently_updated  && -z $(ls /build/$pdir/build_successful* 2> /dev/null) ]]; then
     autoreconf -fiv
fi
}

Sorry for the bad alignment: I don't know how to

What was wrong with my [[ $bits = 32bit || build32 = n* ]]  ?
It should work for all combinations of build32=y/n and build64=y/n

**Comment by wiiaboo** [comment]
Use three backticks.

**Comment by wiiaboo** [comment]
Using that comparison would force autogen each time the script is run, even if there were no updates.

I like that one for find the dirname better. Could also be used for other things.

**Comment by pat357** [comment]
I see it didn't accept my "star" "wildcards" like this "********"
How can I type a wildcard ?
Can you figure out where these should be ?

**Comment by pat357** [comment]
local pdir=${PWD#"*"/build/}
pdir=${pdir%%/"*"}

I'm curious to see if this will be complete.

**Comment by pat357** [comment]
```do_autoreconf() {
    local pdir=${PWD#*/build/}
    pdir=${pg%%/*}
    pdir=/build/$pdir
    if [[ -f $pdir/recently_updated && -z $(ls $pdir/build_successful* 2> /dev/null) ]]; then
        echo -e "\\nStart AUTORECONF for ${packetname}-${bits}\\n"
        autoreconf -fiv
    fi
}
```

**Comment by wiiaboo** [comment]
Using the three backticks you have to leave the rest of the line with just the backticks.

**Comment by wiiaboo** [comment]
Also, check latest two commits and try again.

**Comment by pat357** [comment]
To find the package dir-name, it's indeed a handy feature.
Maybe you remember  I asked a similar question : find the package dir with only pwd as input... do you remember anything ?
I've spend a lot of time to come to such a simple solution. Before I found this, I had some other based on SED and GREP, but worked only for git|hg|svn.
It has proven to be very usefull to me and I use it alot in my "adapted" script.

**Comment by pat357** [comment]
Seems to work as far as I tested.
Another issue however with tesseract : 
setting : build32=yes, build64=yes

Using these settings, tesseract does never compile a new 64-bit version, probably because the 'recently_updated' file was deleted by git clean -xfd.

**Comment by wiiaboo** [comment]
Right. https://github.com/jb-alvarado/media-autobuild_suite/commit/e3d3d15d87ebcecca44ba0340466b27fb27f1fbd should do the trick. It removes only ignored files mentioned in .gitignore.

**Comment by pat357** [comment]
It doesn't seem right : git -clean will run every time (no conditions) and make the work-directory empty, while autogen runs only when recently_update is there and 'build_successful*' must be absent.

Imagine I want to rebuild tesseract (delete the tesseract.pc in local{32,64}. There are no updates via git.
What would happen ? ...  right , you'll end up with a clean dir and do_autogen does nothing.

Same story with 64-bit compile after sucessful 32-bit compile : build_successful32 is present  atm you are at the 64-bit compile : same story, empty dir and do_autogen does nothing because the  file build_successful32 is present.

See the problems here : I guess git clean should only run when autogen runs are the other way around.
It should be impossible that git clean runs and autogen does not.

I've given the conditions to run do_autogen to git clean, so they always run both or none of them runs.
I hope you fnd a better solution.

**Comment by pat357** [comment]
I still have look for giving the language of the code to get syntax highlighting....
I use this now:
```
if [[ $bits = 32bit || build32 = n* ]] && [[ -f recently_updated && ! -f build_successful${bits} ]]; then
    git clean -xfd -q -e "/build_successful*" -e "/recently_updated"
    ./autogen
fi

The do_autogen can be replaced by just './ autogen' because the code inside do_autogen is redundant in this case.

**Comment by wiiaboo** [comment]
Better to force autogen both times. I added git clean for tesseract since it fixed some issue 2 weeks ago.
Maybe the issue doesn't exist anymore.

**Comment by wiiaboo** [comment]
![image](http://j.fsbn.eu/K5nY.png)
