### ISSUE TITLE
tesseract does never compile a new 64-bit version (build32=yes, build64=yes )

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#202]
Like the title says.
The problem is that 'git clean -xfd' also deletes the 'recently_updated' file, so the 64 bit version always ssays : "is already up to date".

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/e3d3d15d87ebcecca44ba0340466b27fb27f1fbd should've fixed it.
