### ISSUE TITLE
Problem with GIT on https://github.com/xxxx : time-out

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#203]
After removing a lib in the Mingw{32,64} directories (gnutls, librtmp-git,) I can't make git to connect via port 443 (https) anymore. After a long time, it just times out.

It's not a firewall, because using my Firefox under Win, I can access the https git repo's without problems.
What is needed to make git able to acces https again ?

**Comment by wiiaboo** [comment]
I have no idea. Install git again from /var/cache/pacman/pkg/ ?
