### ISSUE TITLE
Still problems with libtool when build32=yes and build64=yes  (remember to run 'libtool --finish /local64/lib')

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#204]
I thought and hoped that this problem would be gone, but unfortunately it isn't.

Small part from compile.log:
```
Now the INSTALATION from LIBZEN 32bit

make[1]: Entering directory '/build/libzen-git/Project/GNU/Library'
 /usr/bin/mkdir -p '/local32/bin'
 /usr/bin/install -c libzen-config '/local32/bin'
 /usr/bin/mkdir -p '/local32/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libzen.la '/local32/lib'
libtool: install: /usr/bin/install -c .libs/libzen.lai /local32/lib/libzen.la
libtool: install: /usr/bin/install -c .libs/libzen.a /local32/lib/libzen.a
libtool: install: chmod 644 /local32/lib/libzen.a
libtool: install: ranlib /local32/lib/libzen.a
libtool: [31mwarning(B[m: [1mremember to run 'libtool --finish /local64/lib'(B[m
 /usr/bin/mkdir -p '/local32/lib/pkgconfig'
 /usr/bin/install -c -m 644 libzen.pc '/local32/lib/pkgconfig'
```

full log:
http://sprunge.us/UCKW

**Comment by pat357** [comment]
This problem appeared when trying to build the 32bit version from LibZen.
In this context, the "remember to run 'libtool --finish /local64/lib'" points to a previous session, where the 64-bit version was build. It apparently doesn't matter the 64-bit was build 2 weeks ago : libtool seems to store the latest build info & architecture somewhere in it's files.

How to get rid of this ? The new 32 bit build's are corrupted because they were build with libs from the 64-bit version.
Look in the log how short the compilation from libmediainfo is : it seems it's just relinking the 64bit libs to build the 32bit version !!

My "temporal" solution is to check for a build (check if the .a has been build) and then do a distclean BEFORE do_autogen runs.

[[ -f xxx.a &&  ! -f /xx/build_sucessfulxx  &&  is_firstrun ]] &&  do_distclean
do_autogen
[[ -f Makefile ]] && do_distclean

This works much better as far as I can see.  The second distclean is not executed if the first has run, because there can't be a Makefile anymore.

Another option is probably running 'libtool --finish /local64/lib' after the 64-bit version has been installed, but I have not tried this.

Any better ideas ??

**Comment by pat357** [comment]
Before you ask for it : I have already deleted all Mediainfo related directories a couple of times to make a fresh start, so this didn't help. The first compile (32 + 64 bit) are OK after a fresh start, but the next run gives this problem while compiling the 32bit version.

**Comment by wiiaboo** [comment]
Have you tried replacing the do_autogen with just do_autoreconf and see if that's enough?

**Comment by pat357** [comment]
The trick with the "git clean -xfd -e "/build_successful*" -e "/recently_updated" works, but there's still one problem left: if you just want to rebuild Zenlib, Libmediainfo, Mediainfo, tesseract,,... then the file "recently_updated" is not there and the rebuild will allways fail.

**Comment by wiiaboo** [comment]
Why would it fail?
If nothing is updated, there's no need to run autogen or git clean, just `make distclean` and all is good.

**Comment by wiiaboo** [comment]
Tesseract is always nuked, even from 32-bit to 64-bit.

**Comment by pat357** [comment]
That's exactly why it will fail: remember I why I started this thread : when you build with build32=yes and build64=yes, there is no distclean between the 64bit build and a next 32bit build !
Autogen runs BEFORE any distclean as far as I can see, even in your latest  version.

**Comment by pat357** [comment]
What's the error or problem you see with Tesseract ?

**Comment by wiiaboo** [comment]
Can't remember.
Anyway, autogen/autoreconf should only be needed when there are updates, not on rebuilds.
4b0bf79 should be done with it.

**Comment by wiiaboo** [comment]
I assume this has been fixed.
