### ISSUE TITLE
mp4box build problem

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#205]
https://pastee.org/pq8m7
```
H:/media-autobuild_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): In function `main':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
```
not sure whether it's a bug inside the the gpac source or with the build script,..

**Comment by wiiaboo** [comment]
It's GPAC's fault, most likely. That seems like a problem that would affect more than just GPAC if it were MinGW's.

**Comment by rdp** [comment]
ref: https://github.com/gpac/gpac/issues/344
