### ISSUE TITLE
Mediainfo - Load remote URL

### ISSUE THREAD

**Issue by silverkorn** [jb-alvarado/media-autobuild_suite#206]
Using an URL to get information of a remote stream, it is not possible since `libcurl` was not enabled.
```
> mediainfo.exe "http://hls1.addictradio.net/addictrock_aac_hls/playlist.m3u8"
E: Libcurl support is disabled due to compilation options
```
Is it possible to compile with libcurl by default or is there any flaw doing so?
Thanks!

**Comment by wiiaboo** [comment]
Should be possible, since MinGW's libcurl is static.

**Comment by wiiaboo** [comment]
Done.

**Comment by silverkorn** [comment]
Thanks!
