### ISSUE TITLE
ffmpeg - ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#207]
compile log: https://pastee.org/m2h4j

ffmpeg options:
> --enable-gnutls
--enable-frei0r
--enable-libbluray
--enable-libcaca
--enable-libass
--enable-libgsm
--enable-libilbc
--enable-libmodplug
--enable-libmp3lame
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-libvo-amrwbenc
--enable-libschroedinger
--enable-libsoxr
--enable-libtwolame
--enable-libspeex
--enable-libtheora
--enable-libvorbis
--enable-libopus
--enable-libvidstab
--enable-libxavs
--enable-libxvid
--enable-libtesseract
--enable-libzvbi
--enable-libdcadec
--enable-libbs2b
--enable-libmfx
--enable-libcdio
--enable-libfreetype
--enable-fontconfig
--enable-libfribidi
--enable-opengl
--enable-libvpx
--enable-libx264
--enable-libx265
--enable-libkvazaar
--enable-libwebp
--enable-decklink
--enable-libgme
--enable-librubberband
--disable-w32threads
--enable-opencl
--enable-libzimg
--disable-debug
--enable-nonfree
--enable-nvenc
--enable-libfdk-aac
--enable-openssl

media-autobuild_suite.ini
>[compiler list]
msys2Arch=2
arch=1
license=2
vpx=1
x264=4
xpcomp=1
x265=7
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
rtmpdump=2
mplayer=1
mpv=2
cores=8
deleteSource=1
strip=1
pack=2

**Comment by wiiaboo** [comment]
https://bitbucket.org/multicoreware/x265/issues/212/new-libx265-not-found-in-ffmpeg-configure

**Comment by wiiaboo** [comment]
Temporarily fixed with 54a388b.
