### ISSUE TITLE
ZIMG won't build without the temp. fix

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#209]
I just 've retried to build ZIMG without the fix : it fails immediately upon starting compilation:
A small part from the log:
```
make[1]: Entering directory '/build/zimg-git'
make[1]: *** No rule to make target 'vszimg.c', needed by 'vszimg.lo'.  Stop.
make[1]: *** Waiting for unfinished jobs....
```
With the fix, all goes well without noticeable problems. 
Complete log at: 
http://sprunge.us/ZWKE

**Comment by wiiaboo** [comment]
But have you deleted the directory?

**Comment by pat357** [comment]
Yep, you can clearly see that VCS is cloning. The folder was deleted this time.

**Comment by wiiaboo** [comment]
Right, I can  see one mention still left, it's probably that that's
breaking it.
I've mentioned it to him.

**Comment by wiiaboo** [comment]
No idea why it worked for me. Probably hadn't git pull'd the revert.

**Comment by wiiaboo** [comment]
Fixed upstream already
