### ISSUE TITLE
ffmpeg compile failed

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#213]
followed your steps to fix build errors without success.

Here is part of the log:
------------------------------
libcdio is gpl and --enable-gpl is not specified.(B[m

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
Makefile:2: config.mak: No such file or directory
Makefile:63: /common.mak: No such file or directory
Makefile:105: /libavutil/Makefile: No such file or directory
Makefile:105: /library.mak: No such file or directory
Makefile:107: /doc/Makefile: No such file or directory
Makefile:191: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:63: /common.mak: No such file or directory
Makefile:105: /libavutil/Makefile: No such file or directory
Makefile:105: /library.mak: No such file or directory
Makefile:107: /doc/Makefile: No such file or directory
Makefile:191: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
-------------------------------------------------
Building of ffmpeg-git failed...

If somebody of you could take a look...
thanks

**Comment by wiiaboo** [comment]
Had a typo in helper.sh. Should be fixed now.

**Comment by hekitoshinoda** [comment]
Whow!
That's fast ... ;-)
You're welcome and thank's a lot.


2015-12-05 15:46 GMT+01:00 Ricardo Constantino <notifications@github.com>:
