### ISSUE TITLE
Likely error leptonica

### ISSUE THREAD

**Issue by mangohugo** [jb-alvarado/media-autobuild_suite#2135]
18:08:16 ┌ leptonica git  ............................ [Recently updated]
18:08:16 ├ Running autogen...
18:08:31 ├ Running configure...
18:09:28 ├ Running make...
Likely error (tail of the failed operation logfile):
Making all in src
make[2]: Entering directory '/build/leptonica-git/build-64bit/src'
  CCLD     liblept.la
../libtool: line 7521: cd: lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'lib'
make[2]: *** [Makefile:635: liblept.la] Error 1
make[2]: Leaving directory '/build/leptonica-git/build-64bit/src'
make[1]: *** [Makefile:535: all-recursive] Error 1
make[1]: Leaving directory '/build/leptonica-git/build-64bit'
make: *** [Makefile:419: all] Error 2
make failed. Check C:/ffmpeg1/build/leptonica-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
18:09:48   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oK1s.zip
Copy and paste [logs.zip](https://0x0.st/oK1s.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
please repull the suite and delete build/libtiff-git and rerun
