### ISSUE TITLE
still ffmpeg building failed

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#214]
sorry, have another one ...
again, still after redownloaded the sources in build no success
----------------------------------
ERROR: dcadec not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
Makefile:2: config.mak: No such file or directory
Makefile:63: /common.mak: No such file or directory
Makefile:105: /libavutil/Makefile: No such file or directory
Makefile:105: /library.mak: No such file or directory
Makefile:107: /doc/Makefile: No such file or directory
Makefile:191: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:63: /common.mak: No such file or directory
Makefile:105: /libavutil/Makefile: No such file or directory
Makefile:105: /library.mak: No such file or directory
Makefile:107: /doc/Makefile: No such file or directory
Makefile:191: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
-------------------------------------------------
Building of ffmpeg-git failed...

**Comment by wiiaboo** [comment]
That one is weird. Try deleting dcadec-git directory and running the script again.

**Comment by hekitoshinoda** [comment]
Hhmm, I don't have that directory at all (shure, that's exactly what the
log said).
Have only the dvdnav-git and the dvdread-git, not another "d" ish directory.
But why it is not pulled in by your script or any dependency check for
ffmpeg?
Any Ideas?

2015-12-05 16:42 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
No idea. Can you post ffmpeg_options.txt, media-autobuild_suite.ini and compile.log to https://gist.github.com/?

**Comment by hekitoshinoda** [comment]
Yes. I can do that.
Where do I find the ffmpeg_options.txt?
The rest I know.

2015-12-05 16:56 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
If you don't have it it means you're using default options for ffmpeg so no need to post them.

**Comment by hekitoshinoda** [comment]
Yes, default.

<script src="https://gist.github.com/hekitoshinoda/880b01619d2447e65d33.js
"></script>

Need something else?

2015-12-05 17:01 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by hekitoshinoda** [comment]
Sorry, that was the embed one ...
Here is the link.

https://gist.github.com/hekitoshinoda/880b01619d2447e65d33

2015-12-05 17:01 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
That installation looks kinda screwed. Why is there a grep.exe in C:\mingw\build? Delete it and try again.

**Comment by hekitoshinoda** [comment]
Hey - that's amazing!
It runs and now I have also a dcadec-git folder.

I was wondering about all that GREP errors in the log too, but no Idea
about just a lost GREP in the wrong folder.

Maybe I should rework all that stuff from scratch.
It's an Installation from sometimes ago (~2 Years) only updated here and
there from time to time, and the hirarchy changed sometimes ago too (moved
the scripts to /build).
There is nothing like a "cleanup" script, so it's a grown build system.
Possibly left some of the now called "ghost-files" in subfolders ....
Maybe this was causing the latter failed build.

Thanks again a lot for the quick fix.


2015-12-05 18:09 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
A full rebuild every few months is a good idea, though shouldn't be needed. With ee6818e9285f5403dd17291c76f0cad2f943cba9 those stray .exes should be gone too.

**Comment by hekitoshinoda** [comment]
Ah, yay, that's a good idea.
Hint:
Maybe you could just do a search in the install path for comparison and the
several "zombie.exe" which don't match your scripts install location would
be deleted.


2015-12-05 18:44 GMT+01:00 Ricardo Constantino <notifications@github.com>:
