### ISSUE TITLE
libwebp not found using pkg-config

### ISSUE THREAD

**Issue by jeprojects** [jb-alvarado/media-autobuild_suite#216]
I'm getting this issue:

Applying: add openhevc intrinsics
ERROR: libwebp not found using pkg-config

Any ideas?

**Comment by wiiaboo** [comment]
That doesn't really say anything. FFmpeg's config.log would be more useful.

**Comment by wiiaboo** [comment]
Can't reproduce. Post FFmpeg's config.log, media-autobuild-suite.ini, compile.log and ffmpeg_options.txt (if it exists) to http://gist.github.com

**Comment by wiiaboo** [comment]
Original reporter MIA. I don't like useless open issues.
