### ISSUE TITLE
FFmpeg fails to build latest code from git

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#217]
Like title says:

Error is:
```
libavutil/opencl.c:34:0: note: this is the location of the previous definition
 #define UNLOCK_OPENCL pthread_mutex_unlock(atomic_opencl_lock)
 ^
libavutil/opencl.c:38:2: error: #endif without #if
 #endif
```
So it looks like a typo.
I guess the guys at ffmpeg haven't tried to compile their code, as no compiler would ever allow this.

**Comment by wiiaboo** [comment]
FATE doesn't test compilation with external libraries. That would make FFmpeg break with a lot more stuff.

**Comment by wiiaboo** [comment]
Should be fixed soon, no need to do anything.
