### ISSUE TITLE
UTV patch doesn't work anymore ; SED still works !

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#223]
When I use the UTVideo patch, the latest FFMpeg fails to build:
I got the following error upon linking the ffmpeg exe's:
```
K:/Mingw64/local32/lib/libutvideo.a(UL00Codec.o):UL00Codec.cpp:(.text+0x4b0): undefined reference to `hModule'
K:/Mingw64/local32/lib/libutvideo.a(UQ00Codec.o):UQ00Codec.cpp:(.text+0x180): undefined reference to `hModule'
collect2.exe: error: ld returned 1 exit status

Makefile:127: recipe for target 'ffmpeg_g.exe' failed
```
Full log at  
http://sprunge.us/jSiC

**Comment by wiiaboo** [comment]
What sed?

**Comment by pat357** [comment]
The sed (stream editor) replacements/insertions you used _before_ you made the patch for UTV.
Don't you remember you replaced some Sed commands by a patch for UTV ?

What I'm telling is : the previous solution based on sed commands only still works, but the patch doesn't.
As you can see in the log, I recompiled libutvideo with patch and ffmpeg won't build anymore.
Can you replicate this on your system ?

**Comment by wiiaboo** [comment]
No.
The new patch should be the same as the sed. It only hides DllMain.

**Comment by pat357** [comment]
You mean a patch you made today ?
Because my compile was done today, with all patches from online....

**Comment by wiiaboo** [comment]
I pushed a fix before closing the issue and ran a full compile with both utvideo and angle.
