### ISSUE TITLE
MPV-player 64bit : everything compiles OK, but .exe won't start, 32 bit is OK.

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#225]
A strange problem: the compiled "MPV.EXE"  64-bit  throws an error upon trying to start.
I have no errors during compilation.
I've tried with disabled Vapoursynth, disabled Angle,.. but no avail.
Also delete MPV-git folder, recompiling ffmpeg, Angle, ...

The message I get doesn't tell me very much
![mpv-64bit-error](https://cloud.githubusercontent.com/assets/13542862/12011977/842d9c74-ace5-11e5-9495-e369ac063eae.png)
[Uploading MPV-64bit-error.zip…]()

**Comment by pat357** [comment]
Just to be clear : the 32 bit MPV is OK.
It's only recently, as I compiled MPV yesterday to and this one is OK.
In mean time there were updates for the system : IIRC libcurl, openssl.,

**Comment by pat357** [comment]
If you can test it on your system, please let me know if your MPV.exe is OK or not, so I can stop pulling my hair at the risk of loosing all of it. ;)

**Comment by wiiaboo** [comment]
Build from ~16:00 today is working fine. Could be something to do with GCC upgrading to 5.3.0. Maybe good idea to recompile everything.

**Comment by wiiaboo** [comment]
Just finished building now, without rebuilding anything except whatever was updated since 7h ago. Still works.
Could be any number of things related to different options in ffmpeg.
Before despairing further, just make a fresh build of everything.
If there's still something wrong, just remove external stuff from ffmpeg until it works.

My working build's ffmpeg_options.txt:
```
--enable-libmp3lame
--enable-libvorbis
--enable-libx264
--disable-decoder=dca
--enable-libdcadec
--disable-postproc
--enable-gmp
--disable-doc
--enable-libvpx
--enable-libopus
--disable-hwaccels
--disable-sdl
--disable-encoder=vorbis
--disable-demuxer=asf
```

**Comment by pat357** [comment]
I could not pin the reason why I got this corrupt exe.
After removing all options in ffmpeg, disable vapoursynth, Angle,..I started re-adding 1 by 1 back and now it works OK.
