### ISSUE TITLE
FFmpeg with libgcrypt won't build

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#227]
I've tried to build ffmpeg without any crypto except "--enable-gcrypt", but it doesn't build.
Tested both with libgcrypt from Mingw and building "libgcrypt-1.6.4" myself (like we used to do some time ago), but nogo.

Has anyone managed to build ffmpeg with libgcrypt ?
Somehow I have overwritten my log file, but I can recompile to make a new log it it would add something useful.

**Comment by wiiaboo** [comment]
FFmpeg is missing gpg-error in the libs. I'll try sending a patch upstream.
