### ISSUE TITLE
tar cannot create symlink for soxr 0.1.2 sources

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#230]
In ab-suite.extract.error.log:

    tar: soxr-0.1.2-Source/inst-check-soxr-lsr: Cannot create symlink to ‘inst-check-soxr’: No such file or directory
    tar: Exiting with failure status due to previous errors

**Comment by wiiaboo** [comment]
Nothing can be done about it.

**Comment by wiiaboo** [comment]
Sorry, didn't notice this was stopping the build. Forgot about it.

**Comment by LigH-de** [comment]
You make it possible! :) - Big fat thanks and Happy New Year to the whole team!

(BTW: Is that a typo in the label "not ou*t* bug" => "not ou*r* bug"?)

**Comment by wiiaboo** [comment]
Hm, never noticed until now.

**Comment by LigH-de** [comment]
Wrong solution? Still the same error and halt.

**Comment by LigH-de** [comment]
Nope again: This will extract the tar to the console (ab-suite.extract.log contains the content as text), instead of a subdirectory.

**Comment by wiiaboo** [comment]
Sorry, too much champagne.

**Comment by LigH-de** [comment]
OK, this time soxr passed.

Bad time for support; get a rest. ;)
