### ISSUE TITLE
harfbuzz configure failed

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#233]
Hi. Running from scratch media_autobuild (32bit) failed to configure properly harfbuzz package:
".......
┌ harfbuzz-1.1.2 ........... [[33mUpdates found(B[m]
├ Running extract...
├ Running configure...
**configure failed. Check /build/harfbuzz-1.1.2/ab-suite.configure.error.log**"

and harfbuzz ab-suite.configure.error.log looks like:
"configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.15 is not found.
config.status: error: cannot find input file: `test/api/Makefile.in'"

regards,
laur

**Comment by wiiaboo** [comment]
Fixed in aceba0e91439e081535b697ea1f61e9211066d47
