### ISSUE TITLE
x265: version string misses commit hash

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#237]
x265 -V
```
x265 [info]: HEVC encoder version 1.8+191-
x265 [info]: build info [Windows][GCC 5.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT
```
Should be "1.8+191-375ce77b8c35" instead of "1.8+191-". I'd expect Mercurial to provide this value. The generation of x265.rc is the key, I believe.

My half-automated build environments, based on XhmikosR's MSYS packages, can provide it. Maybe there could be an incompatibility with a newer CMake? I still use v3.1.0.

**Comment by wiiaboo** [comment]
It's msys'  fault. The path conversion logic is screwing up with "{node|short}" or something.
