### ISSUE TITLE
DVDREAD-64bit (using GIT) fatal: dumb http transport does not support --depth

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#238]
When checking for updated (using git) for DVDREAD, I get an error saying "fatal: dumb http transport does not support --depth".

Any ideas ?

**Comment by wiiaboo** [comment]
Don't use depth? It doesn't matter that much bandwidth or space-wise and screws with some stuff.

**Comment by pat357** [comment]
I  don't use Depth, I just do
```
do_vcs "http://git.videolan.org/git/libdvdread.git" dvdread
```
Maybe the do_vcs generates a command containing "-depth ??

**Comment by wiiaboo** [comment]
I'm pretty sure it doesn't use that anymore.

**Comment by pat357** [comment]
Oops indeed, by accident I used an older version which still used do_git()..
Never mind, will close the issue.
Thanks anyway..
