### ISSUE TITLE
Question : ffmpeg : enable SFTP by  "--enable-libssh"

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#239]
Not really an issue, more a polite request...
I'm looking how to directly access my media on a remote PC with can only be accessed by SSH2 (Putty).
Now I first have to get the files by SFTP to my local system, but I wonder if it would be possible to directly access the media using FFMPEG's SFTP support.
The remote system is a Linux system running Ubuntu.

Problem is that FFmpeg does not build with  "--enable-libssh" (via pacman from MingW) ; can you have a look at it ?
Maybe the .pc file is just missing some libs...

**Comment by wiiaboo** [comment]
Last I checked it's not statically built.

**Comment by wiiaboo** [comment]
d9921de227f03d80ebd7e7ee085b98213a07bd6d
