### ISSUE TITLE
Unable to build Mediainfo.exe

### ISSUE THREAD

**Issue by cnrd** [jb-alvarado/media-autobuild_suite#242]
Hi

Sorry for nagging you.

I'm unable to build the mediainfo binary, when I enable the feature to build it, I get the following error:

g++.exe: error: C:/Dev/media-autobuild_suite/msys64/mingw64/lib/libz.dll.a: No such file or directory
g++.exe: error: C:/Dev/media-autobuild_suite/msys64/mingw64/lib/libintl.dll.a: No such file or directory
g++.exe: error: C:/Dev/media-autobuild_suite/msys64/mingw64/lib/libiconv.dll.a: No such file or directory
make: *** [mediainfo.exe] Error 1

When looking in the folder in which it is unable to find the file, I have the following files:
libz.a
libz.dll.a.dyn

libintl.a
libintl.dll.a.dyn

libiconv.a
libiconv.dll.a.dyn

**Comment by wiiaboo** [comment]
It should not be asking for those.
Can you upload compile.log and ab-suite.*.log inside mediainfo-git\Project\GNU\CLI somewhere and paste the link here?

**Comment by wiiaboo** [comment]
Can't reproduce.
Also upload ffmpeg_options.txt and media-autobuild_suite.ini.

**Comment by cnrd** [comment]
Using the newest version from GitHub:

https://drive.google.com/folderview?id=0B7yhIpV_wks7YWFjSjdvaUhEbWM&usp=sharing

**Comment by wiiaboo** [comment]
One more thing before trying those settings, can you run `pkg-config --static --libs libcurl` and paste what it replies here?

**Comment by wiiaboo** [comment]
Yeah, even with your settings, can't reproduce. Try forcing rebuild of libzen/libmediainfo/mediainfo by removing `libzen.pc` from `/local64/lib/pkgconfig`. This should also force rebuild of libmediainfo and mediainfo.

**Comment by cnrd** [comment]
Hmm don't know what was wrong, but apparently the old saying: "Have you tried turning it off and on again?" worked... (Also deleted everything before rebooting). I did try just deleting everything, that by itself did not work.

Everything is compiling now.

Thanks for your help :-)
