### ISSUE TITLE
Install routine does not recognize missing WSH

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#243]
The installation of the media-autobuild_suite apparently requires the presence of the Windows Script Host to execute a JScript. There was a user trying to install it who possibly did not have WSH installed, so all steps following the installation of wget failed.

**Comment by wiiaboo** [comment]
Nothing I can do about it. There's no native way to download files that comes with all Windows versions.

**Comment by LigH-de** [comment]
But maybe there is a way to check if the execution of the JScript succeeded, or even if WSH is installed before trying to execute it, and writing a meaningful error message in this case.

Possibly better than e.g. learning Auto-It in addition...

**Comment by wiiaboo** [comment]
What happens if cscript fails?

**Comment by wiiaboo** [comment]
Also, what version of Windows is that? I thought WSH was natively installed since XP.

**Comment by LigH-de** [comment]
He reported the following message:

```D:\media-autobuild_suite-master\media-autobuild_suite-master\build\install-wget.js(1, 1047) (null): Unbekannter Fehler```
(unknown error)

This does not really look like there is no script interpreter involved at all, but rather an error executing it. The position (visualized as }{ here) seems to be in the middle of:

```var dst = shell.NameSpace(dstdir); }{ var zipdir = shell.NameSpace(zip_file);```

**Comment by wiiaboo** [comment]
No idea. I didn't make the script and have no experience whatsoever in jscript.
A warning is good enough.

**Comment by LigH-de** [comment]
https://msdn.microsoft.com/de-de/library/windows/desktop/bb774085(v=vs.85).aspx

shell.NameSpace(vDir) returns null if the folder could not be created.

But I see no obvious reason why it may have failed there.

**Comment by wiiaboo** [comment]
Either way, it's some problem with the user, not with the script.
If you or anyone feel like improving the downloading script, go ahead and Pull Request.
