### ISSUE TITLE
How to build mpv with VapourSynth support?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#244]
The current suite offers an option:
```
3 = compile with Vapoursynth, if installed [see Warning]
```
Do I have to install VapourSynth inside the MSYS2 environment to get detected and enabled during the building?

I tried to build mpv with option 3, only having VapourSynth installed in 64-bit version in Windows (not in MSYS2 for the suite), and it works as frameserver for e.g. loading a *.vpy script into VirtualDub-AMD64. But mpv in local64 does not recognize the type of a *.vpy file. Scanning the mpv.exe for occurences of "vapour" only returns a few places where the build option "--disable-vapoursynth-lazy" was stored as string. Furthermore, build/mpv-git/build/config.h contains:
```
#define HAVE_VAPOURSYNTH 0
#define HAVE_VAPOURSYNTH_LAZY 0
#define HAVE_VAPOURSYNTH_CORE 0
```
So I guess it has to be installed in MSYS2?

**Comment by wiiaboo** [comment]
> Do I have to install VapourSynth inside the MSYS2 environment to get detected and enabled during the building?

No, default installation in 64-bit OS only (C:\Program Files (x86)\VapourSynth).

Just check yourself:
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1380

**Comment by wiiaboo** [comment]
Maybe it doesn't work with non-english OS, now that I think about it.

**Comment by wiiaboo** [comment]
What does `env | grep "^ProgramFiles(x86)" | sed -n 's;.*=;;p'` reply in your system?

**Comment by LigH-de** [comment]
So I may have a rather non-default installation:

a) in 64-bit mode;
b) in E:\Programme instead of C:\Program Files or C:\Program Files (x86)

In addition, inside the msys2_shell, the command "env" was not found.

**Comment by wiiaboo** [comment]
`/usr/bin/env` doesn't exist? That's very weird.
Also, did you change VapourSynth's default dir? It should always install to ..(x86).

**Comment by LigH-de** [comment]
I pasted your command accidently with some leading control keys, it did not start with the "e" of "env".

And yes, I installed VapourSynth into a custom directory, outside of the UAC.

**Comment by wiiaboo** [comment]
Why'd you do that? You can install user plugins to %AppData%/Vapoursynth. You shouldn't need to mess with the install dir.

**Comment by LigH-de** [comment]
Just noticed that your latest commit allows editing of the mpv build options in a text file. After re-installing VapourSynth to the default directory, it contains:

```
--enable-vapoursynth
```

**Comment by LigH-de** [comment]
Possibly important to know: The so called VapourSynth support in mpv means video filters only (e.g. try to apply QTGMC to a decoded video if you dare); but mpv won't be able to read *.vpy files as media source (error: "Failed to recognize file format.").

**Comment by wiiaboo** [comment]
That's expected. .vpy reading support would need a demuxer for it in FFmpeg.

**Comment by wiiaboo** [comment]
And you don't need mpv to read vpy directly, just pipe it from vspipe.
