### ISSUE TITLE
Some filter from libavfilter is not compiled anymore

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#245]
Hi. ffmpeg compile without any noticeable error but:
- the exe file is reduced to only 27-28M (pack is disabled in ini file)
- some filter is not compiled anymore (ex. tinterlace, vidstabdetect, blackframe, cropdetect, delogo)
- for filter mentioned above using "ffmpeg -h filter=filter_name" I get the error message "Unknown filter 'filter_name'"
This happened since 1416-1420 media_autobuild_script commits (don't know exactly).
Running few time from schratch :(
I don't think is ffmpeg related because today zeranoe build is running as expected.
Maybe I do something wrong, don't know...
Please find in attach my config files.
regards,
laur
[config_files.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/85168/config_files.zip)

**Comment by wiiaboo** [comment]
Upload config.log in ffmpeg's dir.

**Comment by laurfb** [comment]
Hi. Here is:
[config.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/85172/config.zip)

regards,
laur
