### ISSUE TITLE
Error compiling mediainfo

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#246]
Hi. 
Error message (warnig about missing mingw libs):

┌ libmediainfo git ..................................... Updates found
├ Running autoreconf...
├ Running distclean...
├ Running uninstall...
├ Running configure...
├ Running install...
└ libmediainfo-git ........................................... Updated
┌ mediainfo git ........................................ Files missing
├ Running distclean...
├ Running uninstall...
├ Running configure...
├ Running install...
Likely error:
g++.exe: error: D:/media-autobuild_suite-master/msys64/mingw64/lib/libz.dll.a: No such file or directory
g++.exe: error: D:/media-autobuild_suite-master/msys64/mingw64/lib/libintl.dll.a: No such file or directory
g++.exe: error: D:/media-autobuild_suite-master/msys64/mingw64/lib/libiconv.dll.a: No such file or directory
make: *** [mediainfo.exe] Error 1
install failed. Check /build/mediainfo-git/Project/GNU/CLI/ab-suite.install.error.log

regards,
laur

**Comment by wiiaboo** [comment]
Probably the same as https://github.com/jb-alvarado/media-autobuild_suite/issues/242
