### ISSUE TITLE
Reguest: bmx lib

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#247]
Hi again.
Could bmx lib (http://sourceforge.net/projects/bmxlib/) be added to media-autobuild_suite?
Brings better support for mxf files than ffmpeg.

regards,
laur

**Comment by wiiaboo** [comment]
Sorry, but doesn't that page already have binaries built?
What would be the difference if the suite had it?

**Comment by wiiaboo** [comment]
Ah, it's just snapshots.

**Comment by wiiaboo** [comment]
So many dependencies...
