### ISSUE TITLE
compilation of librtmp failed.

### ISSUE THREAD

**Issue by sarbjit-longia** [jb-alvarado/media-autobuild_suite#248]
I tried to build ffmpeg with --enable-librtmp option but it failed with following error:

G:\Codebase\media-autobuild_suite\msys64\mingw32\bin\ar.exe: creating librtmp.a
gcc.exe: error: G:/Codebase/media-autobuild_suite/msys64/mingw32/lib/libz.dll.a: No such file or directory
gcc.exe: error: G:/Codebase/media-autobuild_suite/msys64/mingw32/lib/libintl.dll.a: No such file or directory
gcc.exe: error: G:/Codebase/media-autobuild_suite/msys64/mingw32/lib/libiconv.dll.a: No such file or directory
make: *** [rtmpdump] Error 1

**Comment by wiiaboo** [comment]
Upload ffmpeg_options.txt, media-autobuild_suite.ini and all ab-suite.*.log inside librtmp-git.

**Comment by sarbjit-longia** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/89191/logs.zip)

**Comment by wiiaboo** [comment]
Yeah, I see rtmp is trying to use MinGW's GnuTLS instead of OpenSSL.
