### ISSUE TITLE
vpxenc with high bit depth support,... + /local32/include/kvazaar_version.h not found

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#253]
Don't know when it changed, but for some reason vpxenc isn't any more build with high bit depth support. (the vpxenc help output would a. mention 10bit and 12bit b. have two additional options  --input-bit-depth and --bit-depth

+ 

there is some problem with kvazaar:
```
kvazaar git ....................................... [Recently updated]
├ Running uninstall...
├ Running autogen...
                                                                                                                       ├ Running configure...
├ Running make...
├ Running install...
├ /local32/include/kvazaar_version.h ....................... [Not found]
└ kvazaar-git ................................................. [Failed]

Try deleting '/build/kvazaar-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.
```
deleted the kvazaar-git, but got the same message on the next run. :(

Would be cool if someone can look into this.

If I can provide additional infos to help debug these problems please post how I can help.

**Comment by wiiaboo** [comment]
I don't know anything about vpxenc, I haven't changed anything recently with it.
What does it show and what is it supposed to show?

**Comment by wiiaboo** [comment]
Just finished a fresh build and vpxenc does contain all three encoders.
I have no idea what happened to choosing bit-depth but the docs in the official site don't have any info on that either.
It's a fact the high bit-depth vp9 is being built since it's both on configure and make logs.

Ask the devs.

**Comment by wiiaboo** [comment]
Just confirmed. `-b` still works but needs `--profile=2` and `ffmpeg -h encoder=libvpx-vp9` lists 8, 10 and 12 bit-depths as supported. It just doesn't show in vpxenc's --help for some reason.

**Comment by wiiaboo** [comment]
The commit where it was removed from --help was https://chromium.googlesource.com/webm/libvpx/+/db14911ccb7e278357e76bfb3f1e7536b99bc889
If you really want it back, ask them in their bug tracker.

**Comment by Selur** [comment]
reported it
