### ISSUE TITLE
low cpu usage, long build times

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#254]
I just noticed that unlike previously when I used the suite cpu usage isn't near 100%, atm. sh.exe is around 2% cpu usage and from time to time one gcc instance is started and uses a single cpu core resulting in ~12% cpu usage,..
-> did something change the last month which is responsible for this slowdown ?
Would it help if I start from a fresh checkout of the suite?

**Comment by wiiaboo** [comment]
Probably. I don't think I changed anything to do with how many cores are used to build.

**Comment by Selur** [comment]
"Make sure to limit make/ninja to cpuCount" -> why I normally use core count and had no problem?

**Comment by wiiaboo** [comment]
In some packages only do_makeinstall is used which didn't have core limit, so it was always single-core. Ninja used cpuCount already, just changed the cosmetic of it.
