### ISSUE TITLE
distclean failed. Check /build/bmx-git/ab-suite.distclean.error.log

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#256]
libMXF-1.0 git ............................................ [Up-to-date]
libMXF++-1.0 git .......................................... [Up-to-date]
┌ bmx git ........................................... [Recently updated]
├ Running uninstall...
├ Running distclean...
Likely error:
configure: error: liburiparser not found
make: *** [config.status] Error 1
distclean failed. Check /build/bmx-git/ab-suite.distclean.error.log

**Comment by wiiaboo** [comment]
I don't compile those.
Upload the logs.

**Comment by Selur** [comment]
started a new run will upload the logs once that hangs again,..

**Comment by Selur** [comment]
attached the logs
[build.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/99782/build.zip)

**Comment by wiiaboo** [comment]
I need the logs from inside bmx-git.

**Comment by Selur** [comment]
attached
[bmx-git.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/99834/bmx-git.zip)

**Comment by wiiaboo** [comment]
Make sure to delete bmx-git.
