### ISSUE TITLE
ffmpeg compiler on win7 64bit

### ISSUE THREAD

**Issue by hashduk** [jb-alvarado/media-autobuild_suite#258]
ffmpeg (static) compiler failed attempting to download msys2. Downloaded manually and copied to build folder as instructed (exe file downloaded and not a folder) but still no joy. As a desperate measure even ran the exe file and installed msys2 to the build folder but still no joy. Running win7 64bit quad core processor. Help.

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/issues/252
