### ISSUE TITLE
Patch couldn't be applied with 'git am'

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#259]
Hi. Some trouble with latest script:
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
**ffmpeg-0001-configure-Try-pkg-config-first-with-a-few-libs.patch**
        **Patch couldn't be applied with 'git am'. Continuing without patching.**
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...

regards,
laur

[ffmpeg_options.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/107280/ffmpeg_options.txt)
[media-autobuild_suite.ini.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/107281/media-autobuild_suite.ini.txt)

**Comment by wiiaboo** [comment]
Failed patches aren't a problem unless they break builds.
