### ISSUE TITLE
Change request: enable interlaced encoding with x264 lib

### ISSUE THREAD

**Issue by loudmax** [jb-alvarado/media-autobuild_suite#260]
Thanks for adding 10bit lib option to x264. In broadcast world this can be used for AVC Intra encodings with x264 cli and ffmpeg.
Since most used format here is 1080i interlaced encoding is needed.
Could you please remove --disable-interlaced?

**Comment by wiiaboo** [comment]
Sure.
Can you give me some sample command/file to test?

**Comment by wiiaboo** [comment]
Tested with http://solidrun.maltegrosse.de/~fritsch/burosch1.mpg and ffmpeg, seems to work.

**Comment by loudmax** [comment]
Thanks!It seemed to work sometimes, but output was not standard compliant.
Great work btw!

Regards,Thomas 

    Ricardo Constantino <notifications@github.com> schrieb am 3:55 Donnerstag, 28.Januar 2016:
 

 Closed #260 via 9a994d2.—
