### ISSUE TITLE
Support for libvo-aacenc removed... 

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#262]
Not an issue as such, rather a FYI to the 
project maintainers, who, let me just stress again, 
are doing a most sterling job!

From the News section of the ffmpeg.org site: 

> January 30, 2016, Removing support for two external AAC encoders
> 
> We have just removed support for VisualOn AAC encoder (libvo-aacenc) 
> and libaacplus in FFmpeg master.

While libaacplus was not really a feasible choice on Windows, 
I do believe though (sorry if I'm wrong) that this project does offer 
--enable-libvo-aacenc 
as a configuration option for compiling FFmpeg; the build script 
should now have to be modified to accommodate the changes 
announced by the FFmpeg devs...

Regards

**Comment by wiiaboo** [comment]
It's been removed days ago in 391c147bfc7b690ea8b03245faabd0b83b14823f.
If people still have it in ffmpeg_options.txt they should remove it manually.

**Comment by Vangelis66** [comment]
My bad, then :-( 
I had not compiled during the last 6 days, plus I 
only browsed briefly the commits' history:
 
https://github.com/jb-alvarado/media-autobuild_suite/commits

and, frankly, I thought you'd remove support only 
after it was officially done so in FFmpeg by the Team themselves!
Apologies for the noise, 
keep well!

**Comment by wiiaboo** [comment]
It's useless for reasons they said in the frontpage. Native AAC encoder is close or as good as fdk so there's absolutely no reason for vo-aacenc and aacplus is also useless since fdk-aac was added.
