### ISSUE TITLE
FFmpeg fails (again)

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#263]
There are at least two issues with that.
First it gives an error at ab suite "unknown option /bin-video".
This I fixed, because in line 1140 in the compile.sh there is a split path (--bindir="$LOCALDESTDI**R"/bin-video "$**{FFMPEG_OPTS[@]}") so it should be (--bindir="$LOCALDESTDIR/bin-video/${FFMPEG_OPTS[@]}") I guess.
After this fix it looks like it compiles.
But at the End it moans there is no ffmpeg.exe in bin-video [Not Found] and ffmpeg-git [failed].
However of course there is no ffmpeg.exe in bin-video because that's the reason for compiling it...
It should not struggle at this point whether there is any ffmpeg.exe or not. 

Edit: Ah - strange, I have now an --enable-avisynth folder in bin-video with the ffmpeg stuff inside.
That's weird ...

**Comment by wiiaboo** [comment]
What?

**Comment by hekitoshinoda** [comment]
Which kind of more info do you need?

[compile.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/111270/compile.log.txt)
![bin-video](https://cloud.githubusercontent.com/assets/15063580/12702269/c56ed096-c823-11e5-9258-30586e45608f.jpg)

**Comment by hekitoshinoda** [comment]
Hi.
This is the "ab-suite" thing ...
Forget about the --enable-avisyth folder, this was my mistake trying to get
rid of this ab-suite misconfig.

2016-01-31 13:53 GMT+01:00 Ricardo Constantino <notifications@github.com>:

> What?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jb-alvarado/media-autobuild_suite/issues/263#issuecomment-177492443>
> .
>

./configure --prefix=/local64 --bindir=/local64 /bin-video --enable-avisynth --pkg-config-flags=--static --enable-frei0r --enable-libbluray --enable-libcaca --enable-libass --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid --enable-libtesseract --enable-libzvbi --enable-libdcadec --enable-libbs2b --enable-libmfx --enable-libcdio --enable-libfreetype --enable-fontconfig --enable-libfribidi --enable-opengl --enable-libx264 --enable-libx265 --enable-libkvazaar --enable-libwebp --enable-decklink --enable-libgme --enable-librubberband --disable-w32threads --enable-libzimg --enable-gcrypt --enable-nonfree --enable-nvenc --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --extra-cflags=-DPTW32_STATIC_LIB --extra-libs=-lpthread --extra-libs=-lwsock32 --extra-cflags=-DKVZ_STATIC_LIB --enable-gpl --enable-version3 --enable-filter=frei0r --disable-debug
Unknown option "/bin-video".
See ./configure --help for available options.

**Comment by wiiaboo** [comment]
I need that logs.zip. And I still don't get what's the problem.

**Comment by hekitoshinoda** [comment]
Hi.
Here is the logs.zip.
Problem is ffmpeg stops building with this ab-suite error.
See Screenshot
[image: Inline-Bild 1]

2016-01-31 19:49 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
Uh, I don't think github accepts email attachments.
But have you tried deleting everything and getting a fresh copy of the suite?

**Comment by hekitoshinoda** [comment]
This was exactly what I had made and then this error occur.
However I dont't deleted the buld folder with all that stuff.
Should I do this an reload all this sources?


2016-02-01 22:53 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
Probably best to delete everything. I can see mkvtoolnix-git still there, so that needs some cleaning up.

**Comment by hekitoshinoda** [comment]
Ok.
I'll try that.
Btw I like the new looking of your script but a little more verbosity here
and there would be sometimes nice.
But I understand, it's hard to decide how much verbosity is neccessary
(especially for joe average ;-) ).

2016-02-01 23:12 GMT+01:00 Ricardo Constantino <notifications@github.com>:

**Comment by wiiaboo** [comment]
Normal regular use doesn't need verbosity unless there's an error.
