### ISSUE TITLE
compile libxml2 fail

### ISSUE THREAD

**Issue by mojie126** [jb-alvarado/media-autobuild_suite#2636]
It seems that when compiling the first library, it reported an error and exited...

![微信截图_20240413092724](https://github.com/m-ab-s/media-autobuild_suite/assets/7426101/a7619975-bb4d-4bb4-94b9-8e8f57c92381)

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14964836/logs.zip)

**Comment by L4cache** [comment]
路径太长？

**Comment by L4cache** [comment]
https://github.com/ccache/ccache/issues/1409
