### ISSUE TITLE
Compiliation attempt failed

### ISSUE THREAD

**Issue by silverkorn** [jb-alvarado/media-autobuild_suite#265]
From a fresh clone of commit https://github.com/jb-alvarado/media-autobuild_suite/commit/0669c8facb75afdd21d7c053e4545e8d6be2d1f9: 32 & 64 compilation, stops at `fribidi`.

See the attached [logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/112485/logs.zip) (You might see some french from kernel's & third parties' logs)
Thanks!

**Comment by wiiaboo** [comment]
This is probably also because of the recent commits ignoring updates do msys2-runtime, since I can't reproduce.

Can you check if with latest commit it continues compiling?
If you're on Win7 64-bit it's probably better if you change to msys32 temporarily, since msys64 has issues with that version especifically.

**Comment by silverkorn** [comment]
Using a freshly new clone from commit a52a916593dd4defa43386d6ec2120ccd6c9b048,
Using msys32 on 64-bit, having this now:
```
libbs2b 3.1.0 .......................................... [Not installed]
┌ libbs2b-3.1.0 ........................................... [Downloaded]
├ Running extract...
├ Running configure...
├ Running make...
Likely error:
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_speex.o):(.text+0x58c): undefined reference to `speex_decoder_ctl'
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_speex.o):(.text+0x5c7): undefined reference to `speex_std_stereo_request_handler'
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_speex.o):(.text+0x5f0): undefined reference to `speex_decoder_ctl'
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_speex.o):(.text+0x6dd): undefined reference to `speex_decoder_ctl'
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_speex.o):(.text+0x889): undefined reference to `ogg_page_serialno'
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_speex.o):(.text+0x899): undefined reference to `ogg_stream_init'
E:/Users/danboi/Temp/media-autobuild-suite/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../lib/libsndfile.a(ogg_pcm.o):(.text+0x134): undefined reference to `ogg_sync_init'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [bs2bconvert.exe] Error 1
make: *** [all-recursive] Error 1
make failed. Check /build/libbs2b-3.1.0/build-32bit/ab-suite.make.error.log
This is required for other packages, so this script will exit.
```
See the attached [logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/114104/logs.zip)

**Comment by wiiaboo** [comment]
That was fixed already. Use the latest commit.

**Comment by silverkorn** [comment]
Pulled to commit e448c8fa6892ed9f5890dc8d3d25ea227c2b26a6, 
it seems to work but I'll need to try somewhere that the `git` port is not blocked :unamused: 
(such as __git.code.sf.net__ & __repo.or.cz__)

Talking about this, would it be possible to have an (un)official mirror fetchable as HTTP, HTTPS or SSH instead? Just asking...

**Comment by wiiaboo** [comment]
Mirror of what? The suite?
https://github.com/jb-alvarado/media-autobuild_suite/archive/master.zip is a constantly up-to-date snapshot of the master branch without the .git folder.
GitHub repos always work through HTTPS.

Changed all git:// to http:// now too.

**Comment by silverkorn** [comment]
Nevermind, I though some libraries were still using a "git://" URL.
I'll give it another try but with some additional attention with our proxy.

I'll close the issue if it works properly, thanks!

**Comment by silverkorn** [comment]
Seems good now, thank you!
