### ISSUE TITLE
error installing zvbi-0.2.35

### ISSUE THREAD

**Issue by cywang90** [jb-alvarado/media-autobuild_suite#267]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/113329/logs.zip)

**Comment by wiiaboo** [comment]
4cdb892d  should've fixed that. I can't reproduce it with master. Are you sure you're using the latest version?

**Comment by cywang90** [comment]
Yep, I'm on latest version. Checked helper.sh and it has the updated code from that commit.

**Comment by wiiaboo** [comment]
I'll try with your settings tomorrow.
It actually seems to have failed extracting correctly, from looking at the logs. Can you delete zvbi dir and archive and try again with b2e4559?

**Comment by wiiaboo** [comment]
I'll try with your settings tomorrow.
It actually seems to have failed extracting correctly, from looking at the logs. Can you delete zvbi dir and archive and try again with e448c8f?

**Comment by cywang90** [comment]
For now, I just disabled zvbi since I didn't need that lib anyway. I'm running some encodes right now but I'll try with the new commit tomorrow and report back.

**Comment by cywang90** [comment]
Just tested and it seems to be fixed as of cc93415.
