### ISSUE TITLE
when install rav1e, notice dep git2?

### ISSUE THREAD

**Issue by mojie126** [jb-alvarado/media-autobuild_suite#2670]
![微信截图_20240508230429](https://github.com/m-ab-s/media-autobuild_suite/assets/7426101/32c6d9df-ad1a-4b53-a8b4-ed49b9b1b687)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15250749/logs.zip)

**Comment by LigH-de** [comment]
Confirming.

```
  = note: G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgit2: No such file or directory
          collect2.exe: error: ld returned 1 exit status
          

error: could not compile `rav1e` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: CliError { error: Some(1 job failed), exit_code: 101 }
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15286305/logs.zip)

**Comment by LigH-de** [comment]
So let's wonder together if it may be related to the update to GCC 14.1 ...

**Comment by LigH-de** [comment]
Which patch where?

**Comment by LigH-de** [comment]
That patch was for gpac (MP4Box). It was not related to rav1e.

**Comment by LigH-de** [comment]
This issue is not solved yet. If there is a change that has to be made to make rav1e compile again, it has not yet been committed to the master branch of M-AB-S.
