### ISSUE TITLE
VPX fails

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#269]
>         Starting 32bit compilation of video tools
librtmp git ............................................... [Up-to-date]
┌ vpx git ........................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error:
H:\media-autobuild_suite\msys64\mingw32\bin\strip.exe: cannot create tempdir for archive copying (error: File exists)
make[1]: *** [libvpx.a] Error 1
make: *** [.DEFAULT] Error 2
make failed. Check /build/vpx-git/build-32bit/ab-suite.make.error.log
This is required for other packages, so this script will exit.
Attach /build/logs.zip to the GitHub issue.
Try running the build again at a later time.

attached the log
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/120721/logs.zip)
deleting the build/vpxgit and restarting the script didn't help

**Comment by Selur** [comment]
btw. current vpxenc builds crash her no matter the command line used, reported it to:
https://bugs.chromium.org/p/webm/issues/detail?id=1149

**Comment by wiiaboo** [comment]
Why do you use a pipe to vpxenc? If you're encoding to vp9 why not just use ffmpeg?

**Comment by Selur** [comment]
a. building vpxenc is way faster than building ffmpeg
b. building vpxenc is way easier than building ffmpeg
when not on Windows it's easier to tell folks how to compile an up-to-date vpxenc than an up-do-date ffmpeg with vpxenc
c. last time I checked ffmpeg didn't support all the options vpxenc offered
d. ffmpeg has no way to handle DVDs, so for dvd input I for example use mencoder as decoder
e. keeping encoding and decoding to separate tools allows better separation of decoding and encoding threads and I can use the same decoder call for different encoders or the same encoder for different decoders
f. building ffmpeg even with the media-autobuild_suite hasn't been that reliable in the last year that I would want to rely on it
g. tracing problems with libvpx have been easier to trace in the past using vpxenc than when using ffmpeg
-> depending on what you do using ffmpeg for everything might be more convenient but I prefer to be able to switch to other decoders and not have to rely on ffmpeg for everything and not have a fallback

**Comment by wiiaboo** [comment]
> c. last time I checked ffmpeg didn't support all the options vpxenc offered

~~Even with~~ I thought there was a `-vpx-params` as well, guess not.

> f. building ffmpeg even with the media-autobuild_suite hasn't been that reliable in the last year that I would want to rely on it

But is there any problem with it now?

**Comment by Selur** [comment]
> But is there any problem with it now?
No ffmpeg build fine today,...

**Comment by Selur** [comment]
after some testing: crashes can be fixed by not including VP10 into vpxenc

**Comment by wiiaboo** [comment]
That's weird. VP10 causes VP9 encoder to crash? I thought they were separate.
I'll just disable it then.

**Comment by Selur** [comment]
I thought to, but changing:

> [[ $standalone = y ]] && extracommands+=(--enable-vp10) || extracommands+=(--disable-examples)

to
>  [[ $standalone = y ]] || extracommands+=(--disable-examples)

and thus not adding VP10 to the build fixes the problems.
-> I agree that VP10 should be removed for the moment.

**Comment by wiiaboo** [comment]
That what 1ea5dff does.
