### ISSUE TITLE
Kvazaar build problem

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#270]
> H:\media-autobuild_suite\msys64\mingw32\bin\ranlib.exe: unable to rename '.libs/libsse2.a'; reason: Permission denied
make[2]: *** [libsse2.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
make failed. Check /build/kvazaar-git/build-32bit/ab-suite.make.error.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/120733/logs.zip)

**Comment by wiiaboo** [comment]
I have no idea. Run it again?

**Comment by Selur** [comment]
deleting the kvazaar git folder and running the script again seems to work,...

**Comment by wiiaboo** [comment]
Blame Windows, I guess.
