### ISSUE TITLE
Recompiled despite being "up-to-date"

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#273]
The following libraries are usually recompiled and even downloaded despite being reported as "(File) Up-to-date)":

- fontconfig
- harfbuzz
- bin-fdk-ac
- opus-tools

(So much until libbluray-git failed...)

I don't know if this happens intentionally or accidently; it just seemed suspicious to me.

**Comment by wiiaboo** [comment]
They also check if, in the case of fontconfig and harfbuzz, freetype2 was compiled more recently than the last successful build and recompile in case. As soon as the build completes successfully they should stop being recompiled.
It doesn't (or shouldn't) download the archive if it's already been downloaded and its hash is confirmed correct.
Same with bin-fdk-aac and opus-tools in the case of fdk-aac and opus, respectively.

**Comment by wiiaboo** [comment]
If they keep recompiling after a successful build of the suite, let me know.
