### ISSUE TITLE
do_pacman_install(dcadec) failed; cygpath: can't convert empty path

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#274]
After compiling x264 and x265, and before compiling ffmpeg, I see a message
```
Installing dcadec... failed
```
in the console and compile log.

Between uchardet and mpv, there are more error messages inserted:
```
Error (2): Das System kann die angegebene Datei nicht finden. { System can't find specified file }

cygpath: can't convert empty path
```
No logs.zip was built, attaching compile.log only.
[compile.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/128090/compile.log.txt)

**Comment by LigH-de** [comment]
I deleted media-autobuild_suite.ini and the *_options.txt to regenerate them; now, instead of the failed dcadec installation, a successful libgcrypt installation was reported. The mpv empty path warning persisted.

**Comment by wiiaboo** [comment]
There's no failed dcadec because dcadec stopped being in options by default, since a decoder based on it was integrated into FFmpeg recently.
What does `pacman -Qs dcadec` say?

The cygpath fails are probably because of Vapoursynth R31 changes, but it shouldn't be.

**Comment by LigH-de** [comment]
Appears to be fine now, there was no more error before compiling ffmpeg (I just deleted ffmpeg-git to enforce its recompilation).

```
$ pacman -Qs dcadec
local/mingw-w64-i686-dcadec-git 0.0.0.207.2a9186e-4
    dcadec is a free DTS Coherent Acoustics decoder with support for HD extensions (mingw-w64)
local/mingw-w64-x86_64-dcadec-git 0.0.0.207.2a9186e-4
    dcadec is a free DTS Coherent Acoustics decoder with support for HD extensions (mingw-w64)
```

Compiling ffmpeg will take a while now, will see later if the R31 warning still appears...

**Comment by wiiaboo** [comment]
Hm, dcadec-git should've been replaced with dcadec. Maybe I should make it explicit.

Also, what does `regtool -W list -v "/HKLM/software/vapoursynth"` say?

**Comment by LigH-de** [comment]
I guess my irregular and delayed updates provoke trouble sometimes.

Here the regtool of a 64-bit VPY installation:
```
$ regtool -W list -v "/HKLM/software/vapoursynth"
CorePlugins64 (REG_SZ) = "E:\Programme\VapourSynth\core64\plugins"
Plugins64 (REG_SZ) = "E:\Programme\VapourSynth\plugins64"
```

**Comment by LigH-de** [comment]
While ffmpeg 64-bit still compiles, I checked ffmpeg 32-bit, and its full help does not contain a reference to dcadec. I remember there was a notice that ffmpeg options have been changed to comply to nonfree license mode...

**Comment by wiiaboo** [comment]
A native decoder based on dcadec was pushed to FFmpeg a few days ago, there's no need for dcadec so it's not on the default options any more. Do you mean dcadec is present on 64-bit but not on 32-bit?

**Comment by LigH-de** [comment]
The 64-bit version of ffmpeg is not yet built, can't check for differences yet; but I guess it will be equivalent. So the DCA decoder in ffmpeg is now in ffmpeg sources, instead of linked from an external library – that would be an explanation why there is no string "dcadec" to be found in the help output, yet there is still a "DCA decoder" included and documented. It's just not separately named anymore.

**Comment by wiiaboo** [comment]
It can still be included, just add `--enable-libdcadec` to ffmpeg_options.txt. But right now they should be mostly equivalent, so there's no need.

**Comment by wiiaboo** [comment]
Testing a fix now for the Vapoursynth issues.
