### ISSUE TITLE
libfdk_aac is not actually enabled

### ISSUE THREAD

**Issue by zeroxia** [jb-alvarado/media-autobuild_suite#275]
Hi,

I enabled everything to perform the build, but in the resulting ffmpeg.exe, there still was no fdk aac encoder. -c:a libfdk_aac is not recognized.

Then I found that although in file "`media-autobuild_suite.ini`", there was the line:

```
fdkaac=1
```

but in "`ffmpeg_options.txt`", there was no such line:

```
--enable-libfdk-aac
```

So the script downloaded libfdk_aac and compiled it, but ffmpeg building just did not included this library.

Maybe you can check other libs as well.

**Comment by wiiaboo** [comment]
It's not supposed to.
ffmpeg_options.txt contains what you want to include into ffmpeg. You change it however you need.
You may want to compile the fdkaac binary but not include it in FFmpeg. Same with vpx, x264 and x265.

If you can give me a good reason why turning it on should force FFmpeg to include it (in case you're not using standalone=y, for example), I can change it.
