### ISSUE TITLE
".EXE" files do not get packed, even though pack=1 inside "media-autobuild_suite.ini"

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#276]
Using the latest version of the suite (https://github.com/jb-alvarado/media-autobuild_suite/commit/1ea5dffa0f235838592135e6f2152e1e863349d9) 
I decided, against the recommendation, to answer "Yes" 
when asked if I wanted to "Pack compiled files?".

However, during compilation of tools, the minnty console 
would print messages like: 
`/build/media-suite_helper.sh: line 385: do_pack: command not found`
and the resulting compiled executables (standalone=1) 
as well as the final ffmpeg.exe binary (took almost 10 hr from scratch 
in my low-spec old Vista laptop...) were not UPXed :-{ 

Although I know very little about the suite code, I tracked down line 385: 
[line 385](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_helper.sh#L385)
which calls subroutine "do_pack"; as the error suggested, 
it's not to be found, but searching the script with an 
editor I hit previous line 355: 
[line 355](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_helper.sh#L355)
the start of subroutine "do_packing"
It then became apparent to me that simply changing
 ```batchfile
355 - do_packing() {  
355 + do_pack() {
```
would fix this bug!

Patched locally and seems to work...
There you have it!
Keep up the otherwise excellent work :-)

**Comment by wiiaboo** [comment]
Yeah, I didn't actually test that, since IMO packing is completely useless.
