### ISSUE TITLE
error when starting compilation of global tools

### ISSUE THREAD

**Issue by jroncalli** [jb-alvarado/media-autobuild_suite#283]
I got an error once the first compilation of global tools started, freetype 2.6.3. It happened running everything 64-bit, deleted all folders and tried again 32-bit, same error. I attached the logs.

This was for a 32-bit attempt.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/145511/logs.zip)

Thanks

**Comment by wiiaboo** [comment]
At a first glance I can't tell what's wrong with it.
I'll try reproducing it later.

**Comment by jroncalli** [comment]
I got different errors when trying to compile 64 bit binaries. I am trying again and will post those logs. Thanks

**Comment by jroncalli** [comment]
Here is the log trying a 64-Bit build, still fails at first attempt to compile, but errors in log are different.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/145711/logs.zip)

**Comment by wiiaboo** [comment]
Yeah, I have no idea.
Could you paste the result of running `pacman -Q` here? Open mintty using the shortcut and just run that and select it to copy it.

**Comment by jroncalli** [comment]
Here you go

apr 1.5.1-1
apr-util 1.5.4-1
asciidoc 8.6.9-4
autoconf 2.69-3
autogen 5.18.4-2
automake-wrapper 10-1
automake1.10 1.10.3-3
automake1.11 1.11.6-3
automake1.12 1.12.6-3
automake1.13 1.13.4-4
automake1.14 1.14.1-3
automake1.15 1.15-2
automake1.6 1.6.3-2
automake1.7 1.7.9-2
automake1.8 1.8.5-3
automake1.9 1.9.6-2
bash 4.3.042-4
bash-completion 2.1-6
bison 3.0.4-1
bsdcpio 3.1.2-5
bsdtar 3.1.2-5
bzip2 1.0.6-2
ca-certificates 20150426-1
catgets 1.1-2
coreutils 8.24-1
crypt 1.1-6
curl 7.47.1-1
dash 0.5.8-1
db 5.3.28-2
diffstat 1.58-1
diffutils 3.3-3
docbook-xml 4.5-2
docbook-xsl 1.78.1-3
dos2unix 7.3.3-1
expat 2.1.0-2
file 5.25-1
filesystem 2015.04-3
findutils 4.6.0-1
flex 2.6.0-1
gawk 4.1.3-1
gcc-libs 4.9.2-6
gdbm 1.11-3
gettext 0.19.6-1
git 2.7.0-1
gmp 6.1.0-1
gnupg 1.4.19-1
gperf 3.0.4-3
grep 2.22-1
groff 1.22.3-1
gzip 1.6-1
heimdal 1.5.3-8
heimdal-libs 1.5.3-8
help2man 1.47.3-1
icu 56.1-1
inetutils 1.9.2-1
info 6.0-1
intltool 0.51.0-2
less 481-1
libarchive 3.1.2-5
libasprintf 0.19.6-1
libassuan 2.4.2-1
libbz2 1.0.6-2
libcatgets 1.1-2
libcrypt 1.1-6
libcurl 7.47.1-1
libdb 5.3.28-2
libedit 3.1-20150325
libexpat 2.1.0-2
libffi 3.2.1-1
libgc 7.2.d-1
libgcrypt 1.6.4-1
libgdbm 1.11-3
libgettextpo 0.19.6-1
libgpg-error 1.21-1
libgpgme 1.6.0-1
libguile 2.0.11-3
libiconv 1.14-2
libidn 1.32-1
libintl 0.19.6-1
libltdl 2.4.6-1
liblzma 5.2.1-1
liblzo2 2.09-1
libmetalink 0.1.2-2
libnettle 3.1.1-1
libopenssl 1.0.2.d-1
libp11-kit 0.23.2-1
libpcre 8.38-1
libpcre16 8.38-1
libpcre32 8.38-1
libpcrecpp 8.38-1
libpcreposix 8.38-1
libpipeline 1.4.0-1
libreadline 6.3.008-7
libsasl 2.1.26-8
libserf 1.3.8-2
libsqlite 3.10.0.0-1
libssh2 1.6.0-1
libtasn1 4.7-1
libtool 2.4.6-1
libunistring 0.9.6-1
libutil-linux 2.26.2-1
libxml2 2.9.2-2
libxslt 1.1.28-7
lndir 1.0.3-1
m4 1.4.17-4
make 4.1-4
man-db 2.7.4-1
mercurial 3.6.1-1
mingw-w64-x86_64-binutils 2.25.1-2
mingw-w64-x86_64-bzip2 1.0.6-4
mingw-w64-x86_64-c-ares 1.10.0-2
mingw-w64-x86_64-ca-certificates 20150426-2
mingw-w64-x86_64-cmake 3.4.1-1
mingw-w64-x86_64-crt-git 5.0.0.4609.566d621-1
mingw-w64-x86_64-curl 7.46.0-2
mingw-w64-x86_64-dlfcn 1.0.0-2
mingw-w64-x86_64-doxygen 1.8.10-2
mingw-w64-x86_64-expat 2.1.0-6
mingw-w64-x86_64-gcc 5.3.0-2
mingw-w64-x86_64-gcc-libs 5.3.0-2
mingw-w64-x86_64-gettext 0.19.6-2
mingw-w64-x86_64-gmp 6.1.0-1
mingw-w64-x86_64-gnutls 3.4.8-1
mingw-w64-x86_64-headers-git 5.0.0.4609.566d621-1
mingw-w64-x86_64-isl 0.15-1
mingw-w64-x86_64-jsoncpp 1.6.2-2
mingw-w64-x86_64-libarchive 3.1.2-7
mingw-w64-x86_64-libffi 3.2.1-3
mingw-w64-x86_64-libiconv 1.14-5
mingw-w64-x86_64-libidn 1.32-2
mingw-w64-x86_64-libpng 1.6.21-1
mingw-w64-x86_64-libssh2 1.6.0-2
mingw-w64-x86_64-libsystre 1.0.1-2
mingw-w64-x86_64-libtasn1 4.7-1
mingw-w64-x86_64-libtre-git r122.c2f5d13-4
mingw-w64-x86_64-libwinpthread-git 5.0.0.4573.628fdbf-1
mingw-w64-x86_64-lzo2 2.09-2
mingw-w64-x86_64-mpc 1.0.3-2
mingw-w64-x86_64-mpfr 3.1.3.p0-2
mingw-w64-x86_64-nasm 2.11.08-2
mingw-w64-x86_64-ncurses 6.0.20150627-2
mingw-w64-x86_64-nettle 3.1.1-3
mingw-w64-x86_64-ninja 1.6.0-1
mingw-w64-x86_64-openssl 1.0.2.e-1
mingw-w64-x86_64-p11-kit 0.23.1-3
mingw-w64-x86_64-pcre 8.37-2
mingw-w64-x86_64-pkg-config 0.29-1
mingw-w64-x86_64-readline 6.3.008-1
mingw-w64-x86_64-rtmpdump-git r499.a107cef-3
mingw-w64-x86_64-sqlite3 3.10.2.0-1
mingw-w64-x86_64-termcap 1.3.1-2
mingw-w64-x86_64-tools-git 5.0.0.4592.90b8472-1
mingw-w64-x86_64-windows-default-manifest 6.4-2
mingw-w64-x86_64-wineditline 2.101-4
mingw-w64-x86_64-winpthreads-git 5.0.0.4573.628fdbf-1
mingw-w64-x86_64-xz 5.2.1-3
mingw-w64-x86_64-yasm 1.3.0-2
mingw-w64-x86_64-zlib 1.2.8-9
mintty 1~2.2.3-1
mpfr 3.1.3.p0-1
msys2-keyring r9.397a52e-1
msys2-runtime 2.4.1.16860.40c26fc-1
ncurses 6.0.20151121-1
openssh 7.1p2-1
openssl 1.0.2.d-1
p11-kit 0.23.2-1
p7zip 9.38.1-1
pacman 5.0.0.6348.cc5a8f1-1
pacman-mirrors 20160112-1
patch 2.7.5-1
pax-git 20140703.2.1.g469552a-1
pcre 8.38-1
perl 5.22.0-2
perl-Authen-SASL 2.16-2
perl-Convert-BinHex 1.123-2
perl-Encode-Locale 1.04-1
perl-Error 0.17024-1
perl-File-Listing 6.04-2
perl-HTML-Parser 3.71-3
perl-HTML-Tagset 3.20-2
perl-HTTP-Cookies 6.01-2
perl-HTTP-Daemon 6.01-2
perl-HTTP-Date 6.02-2
perl-HTTP-Message 6.06-2
perl-HTTP-Negotiate 6.01-2
perl-IO-Socket-SSL 2.016-1
perl-IO-stringy 2.111-1
perl-LWP-MediaTypes 6.02-2
perl-Locale-Gettext 1.05-4
perl-MIME-tools 5.506-1
perl-MailTools 2.14-1
perl-Module-Build 0.4212-1
perl-Net-HTTP 6.09-1
perl-Net-SMTP-SSL 1.02-1
perl-Net-SSLeay 1.70-1
perl-TermReadKey 2.33-1
perl-Test-Pod 1.50-1
perl-TimeDate 2.30-2
perl-URI 1.68-1
perl-WWW-RobotRules 6.02-2
perl-XML-Parser 2.44-1
perl-YAML-Syck 1.29-1
perl-libwww 6.13-1
pkgfile 15-1
python 3.4.3-2
python2 2.7.10-1
rebase 4.4.1-6
repman-git r23.87bf865-1
scons 2.4.1-2
sed 4.2.2-2
subversion 1.9.3-1
tar 1.28-3
texinfo 6.0-1
tftp-hpa 5.2-1
time 1.7-1
tzcode 2015.e-1
ucl 1.03-1
unzip 6.0-2
upx 3.91-1
util-linux 2.26.2-1
vim 7.4.872-2
wget 1.17.1-2
which 2.21-2
winpty-git 1~0.2.2.365.79c9859-1
xmlto 0.0.26-2
xz 5.2.1-1
zip 3.0-1
zlib 1.2.8-3

**Comment by wiiaboo** [comment]
I don't see anything missing that shouldn't be. That is very weird. It could be from Win10, but I remember someone confirming it works.
Can you try with the latest version of the suite? I don't think it'll fix anything but it's worth a try.

**Comment by jroncalli** [comment]
Is there a newer version than the one I downloaded yesterday?

**Comment by jroncalli** [comment]
I tried to just do a simple make command from the freetype directory, I got the same error as when running from the script.
$ make
make: ver: Command not found

FreeType build system -- automatic system detection

The following settings are used:

  platform                    unix
  compiler                    gcc
  configuration directory     ./builds/unix
  configuration rules         ./builds/unix/unix.mk

If this does not correspond to your system or settings please remove the file
`config.mk' from this directory then read the INSTALL file for help.

Otherwise, simply type `make' again to build the library,
or `make refdoc' to build the API reference (this needs python >= 2.6).

Generating modules list in ./objs/ftmodule.h...
* module: truetype  (Windows/Mac font files with extension *.ttf or *.ttc)
* module: type1     (Postscript font files with extension *.pfa or *.pfb)
* module: cff       (OpenType fonts with extension *.otf)
* module: cid       (Postscript CID-keyed fonts, no known extension)
* module: pfr       (PFR/TrueDoc font files with extension *.pfr)
* module: type42    (Type 42 font files with no known extension)
* module: winfnt    (Windows bitmap fonts with extension *.fnt or *.fon)
* module: pcf       (pcf bitmap fonts)
* module: bdf       (bdf bitmap fonts)
* module: sfnt      (helper module for TrueType & OpenType formats)
* module: autofit   (automatic hinting module)
* module: pshinter  (Postscript hinter module)
* module: raster    (monochrome bitmap renderer)
* module: smooth    (anti-aliased bitmap renderer)
* module: smooth    (anti-aliased bitmap renderer for LCDs)
* module: smooth    (anti-aliased bitmap renderer for vertical LCDs)
* module: psaux     (Postscript Type 1 & Type 2 helper module)
* module: psnames   (Postscript & Unicode Glyph name handling)
done.
cd builds/unix; \
        ./configure
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/trunk/build/freetype-2.6.3/builds/unix':
configure: error: C compiler cannot create executables
See `config.log' for more details
builds/unix/detect.mk:85: recipe for target 'setup' failed
make: *** [setup] Error 77

It says the C compiler does not work? Does this help at all?

**Comment by wiiaboo** [comment]
No, that's the same problem.

> Is there a newer version than the one I downloaded yesterday?

Yes, I pushed two new commits.

**Comment by jroncalli** [comment]
Same issue with new version, I am trying it on a Windows 7 pc right now.

**Comment by jroncalli** [comment]
So it seems to be a Windows 10 issue, tried it on a Windows 7 PC and it worked great. Is there something in the script that is querying the build system, and maybe returning a different value that what Win7 returns? Anything I can check that might help you make it Win 10 compatible?

Great program by the way, been building ffmpeg in cygwin, can be kind of a pain, this worked wonderfully.

**Comment by wiiaboo** [comment]
There is something that changes the number of packages pacman installs at a time just for Win7 to avoid some weird bug, but I don't think that's the cause of it. A few days ago every other Windows used the same staggered install as Win7, I just changed back to normal for the other Windows after this specific issue was opened.

Other than that, there's nothing that I can think of that could be causing this. I use 8.1. I think @Selur is on Windows 10.

**Comment by Selur** [comment]
Yes, I'm on Windows 10, only problem on
I normally use Tortoise git (https://tortoisegit.org/) to checkout the repository and then run the 'media-autobuild_suite.bat' and either disable my personal firewall during the run or step-by-step enable all the tools which want to go online during the runs.  Sometimes it's necessary to restart the run (since allowing access inside the firewall wasn't fast enough, especially the first few times) until all updates have been installed, but after that most of the times it runs smooth.
-> especially those all-in-one anti virus and firewall software solutions might hinder the script quite a bit unless told to ignore the tools inside the script folder.

I normally use 64bit msys2 targeting 32&64bit.
Started a fresh checkout&co just now for testing, will report back once I'm done. (I this doesn't happen in the next hour, I'm off to work and will report back in sometime tonight - in 13+ hrs)

**Comment by Selur** [comment]
so far it stopped at freetype (due to firewall), but got it after a restart of the script (and an additional firewall exception).

**Comment by jroncalli** [comment]
I use Norton 360. I added the folders the tools reside in as an exception for antivirus scans, and completely disabled the firewall and antivirus while I ran it. Still hangs at freetype.

**Comment by Selur** [comment]
script ran through here while I was at work,..
(I would try if it helps to disable Norton 360, just to be sure)

**Comment by wiiaboo** [comment]
Yeah, something else is wrong in your system. I just tried myself on at least a clean install of Win10 and it ran fine.

**Comment by jroncalli** [comment]
Thank you for all your help. I tried it at home, and it worked fine, (I had been trying at work.) I would understand if it failed while downloading for example, I know we block ftp here, however where it was failing is odd. Anyway, it is working great on my home pc, with Win 10 Pro.

Thank's again, and again, great tool.

Jerry

**Comment by wiiaboo** [comment]
Probably something to do with permissions and/or anti-virus, which are usually the likely suspects in these unexplicable issues.
