### ISSUE TITLE
Compilation issues and current failure

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#285]
First of all, forgive the generic issue title; 
second, I'll be somewhat verbose, so bear with me...

 After many months not using it, I re-installed the suite from scratch
 (on a new external HDD) on 14/02/2016, when it was on snapshot 
git-1ea5dff. All went along fine, up to the point x265 compilation was 
happening; the script aborted and advised to run it later. So I did. 
 The second time I executed the main suite batch file, I witnessed 
what is described in #273 (which did strike me as odd), but the suite 
proceeded into full fruition with no other errors.
Sadly, I have not kept any logs from those runs (1st failed & second 
successful).

On Feb 20th, I updated the suite (from git-1ea5dff) to git-47af811.
Because I wanted to possibly replicate the "first-time" failure, I deleted 
the contents of directories "build" & "local32"; "buiild" was populated with 
the contents of the extracted "build" folder, plus the backed-up copies of 
my previous "media-autobuild_suite.ini" + "ffmpeg_options.txt"

Despite `#--enable-libfreetype #--enable-libfribidi`, those two 
plus harfbuzz were downloaded, compiled and installed - 
are they needed by something else I've selected? 
But again the script exited in x265 compilation; do not know if it 
matters now, log kept and attached as "20160220101053Z-logs.zip"
[20160220101053Z-logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/149528/20160220101053Z-logs.zip)
The second attempt was (as in the case of my initial install) 
successful, ffmpeg.exe was generated!
Two or maybe three days ago, running "media-autobuild_suite.bat" 
initiated (and completed successfully) a full upgrade of msys2 (/mingw32), 
I'm mentioning this in case it has to do with my current issue.

Yesterday, I updated suite manually (from git-git-47af811) to git-aee3146, 
but this time I simply overwrote files with the new (downloaded) ones; no 
folders emptied or deleted.

When I then started the suite, I witnessed the freetype2 upgrade to v2.6.3 
(which was expected by https://github.com/jb-alvarado/media-autobuild_suite/commit/91c3d4534b6fcf973be929df0ff8cf894fea0ddd), but now the script does not 
even make it to x265; it aborts in the "libass" stage. Although "libass git" 
is reported as `[Up-to-date]`, it is uninstalled and then configure fails with a new 
type of error, it won't find DIRECTWRITE. Logs attached.
[1st-try-after-suite-update_logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/149532/1st-try-after-suite-update_logs.zip)
As advised, I tried later, to no avail - second logs:
[2nd-try-after-suite-update_logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/149534/2nd-try-after-suite-update_logs.zip)
And in a desperate third attempt, I first deleted "\build\libass-git" 
and tried anew, again with no luck (no third time's a charm for me!)
Third time logs: [3rd-try-(after-del-libass-git)_logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/149538/3rd-try-.after-del-libass-git._logs.zip)

The error mentions Fontconfig; am I now to `--enable-fontconfig` for this to compile?
Mere days ago the script would run OK on the same "suite" & "ffmpeg" options.
Please do share your educated knowledge on what I did wrong 
to break the suite and an advice to restore it without having to 
compile everything from the start... :-(
[I am seeing new commits pushed to the git repo today, 
they seem pertinent to angle only (?)]

Many thanks for your constant assistance!
Regards

EDIT: Maybe https://github.com/jb-alvarado/media-autobuild_suite/commit/21beaf43f06f4346bcfd8e32d8676bc1b344810e has something to do with my problem?

**Comment by wiiaboo** [comment]
That is a very complicated bug. It could be anything from your changes causing the issue.
> Despite #--enable-libfreetype #--enable-libfribidi, those two
plus harfbuzz were downloaded, compiled and installed -
are they needed by something else I've selected? 

libass needs them.

> Although "libass git"
is reported as [Up-to-date], it is uninstalled and then configure fails with a new
type of error, it won't find DIRECTWRITE. Logs attached.

Unless you didn't install the Platform Update that added DirectWrite to Windows Vista, it won't find it (since it doesn't exist in Vista before that).
I assume people keep their OS up-to-date so I won't add a check for a missing DirectWrite (there's no easy way to check either).
Either update your system or add --enable-fontconfig to ffmpeg_options.txt so libass uses that instead of DirectWrite.

21beaf4 might've caused the problem to show up because it was wrong before and disabled fontconfig if --enable-fontconfig was in ffmpeg_options.txt (which is obviouly wrong).

Regarding the x265 error, I have no idea, never seen that error before. Delete x265-hg and try again.

**Comment by Vangelis66** [comment]
Had my hands full all day with other things, so only now the follow-up:
> Regarding the x265 error, I have no idea, 
> never seen that error before. 
> Delete x265-hg and try again.

 That error only manifested itself on the first time 
the suite was run immediately after a clean installation 
from scratch; without doing anything extra, the second 
time the suite was run, that same error vanished, x265 
compilation was completed and the script moved on; also, 
on future x265 code updates and recompilations, it was 
never to be seen again. 
 I am more clueless than you about that, 
but luckily it was not fatal...

> libass needs them.

Thanks; so if 
`#--enable-fontconfig #--enable-libass #--enable-libfreetype #--enable-libfribidi`
freetype2, harfbuzz & fribidi won't be downloaded and 
compiled as global tools...

> That is a very complicated bug. It could be anything 
> from your changes causing the issue. 

Thanks for taking the time to look into it. 
No real cause and solution was found by me... : -( 
(see further down).
> https://github.com/jb-alvarado/media-autobuild_suite/commit/21beaf43f06f4346bcfd8e32d8676bc1b344810e might've caused the problem to show up 
> because it was wrong before and disabled fontconfig 
> if --enable-fontconfig was in ffmpeg_options.txt 
> (which is obviouly wrong).

I already had `#--enable-fontconfig` inside "ffmpeg_options.txt", 
so in closer inspection https://github.com/jb-alvarado/media-autobuild_suite/commit/21beaf4 shouldn't be to blame. 
I even did a test: while being at suite snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/aee3146, I reverted locally 
https://github.com/jb-alvarado/media-autobuild_suite/commit/21beaf4 with an editor and then tried again; the fatal libass error persisted! 
I even went as far as to suspect the updated versions 
of freetype2 (2.6.3) + harfbuzz (1.2.3), so I performed 
another test: 
I downgraded the suite to snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/47af811 (that I knew was working), 
which downloaded freetype2 2.6.2 + harfbuzz 1.1.3 ; 
alas, I was met again by the same fatal libass error!

> Although "libass git" is reported as [Up-to-date], it is uninstalled

I guess no answer exists why that happened...

> Either update your system or add --enable-fontconfig 
> to ffmpeg_options.txt so libass uses that instead of DirectWrite.

The hard fact remained that on this same system, 
the same "ffmpeg_options.txt" worked fine mere days ago. 
The following is from a binary built on Feb 22nd:

``
ffmpeg version N-78635-g36ad681-g76377d6 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.0 (Rev2, Built by MSYS2 project)
``
``
configuration:  --disable-w32threads --enable-libass --enable-libbs2b --enable-libkvazaar --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libspeex --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-nonfree --enable-openssl --enable-libilbc --enable-libwavpack --enable-libfaac --enable-libfdk-aac --enable-libgsm --enable-libtheora --enable-libvo-amrwbenc --disable-encoder=vorbis --enable-libxavs --enable-librtmp --enable-libssh --enable-doc --disable-ffplay --disable-ffprobe --enable-gpl --enable-version3 --disable-debug
``

where one can see that libass is enabled, while fontconfig is not!

 Doing test after test was time and resource consuming (due to https://github.com/jb-alvarado/media-autobuild_suite/issues/273) 
and was leading me nowhere, plus frustration started to engulf me, 
so I decided it was time to throw in the towel and wiped out everything!
 You can close this one issue as "Unresolved" !

(I then downloaded and clean-installed snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/841eec4 
of the suite and started from scratch; 
a non-fatal error now encountered, 
the subject of another issue report...)

**Comment by wiiaboo** [comment]
> Thanks; so if
#--enable-fontconfig #--enable-libass #--enable-libfreetype #--enable-libfribidi
freetype2, harfbuzz & fribidi won't be downloaded and
compiled as global tools...

Also, mpv and mplayer need libass, so if you're compiling any of them, libass and dependencies will be compiled.

> I already had #--enable-fontconfig inside "ffmpeg_options.txt",
so in closer inspection 21beaf4 shouldn't be to blame. 

It is. Before, it disabled fontconfig in libass if --enable-fontconfig was in ffmpeg_options.txt. You can see how that's wrong. Now it disables fontconfig if --enable-fontconfig is **not** in ffmpeg_options.txt so it doesn't get included even if available. If you don't have DirectWrite you need --enable-fontconfig in ffmpeg_options.txt in order for libass to compile. The script can't check if DirectWrite is available.

If the suite keeps failing, you can rename `build/last_run` to `build/last_successful_run` so anything that was successfully compiled isn't recompiled again. The script checks if the compiled libs are more recent than that file and compiles certain libs again if they are.

**Comment by Vangelis66** [comment]
Yesterday I wrote: 
> (I then downloaded and clean-installed snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/841eec4 
> of the suite and started from scratch; 
> a non-fatal error now encountered, 
> the subject of another issue report...)

 That snapshot was the latest at the time of installing. 
After the initial download & install of msys2/mingw32 
(which had quite a large number of updates), 
I used the same configurations/options mentioned 
previously in this thread, let the suite compile 
unattended and left home for many hours...
When back late at night, no minnty console was open, 
which meant the suite had completed without a fatal error!
Yes, all my compiled binaries were found at 
their expected locations - so the clean install 
has remedied my original issue :-) 

@wiiaboo said: 
> It is. Before, it disabled fontconfig in libass 
> if --enable-fontconfig was in ffmpeg_options.txt. 
> You can see how that's wrong. 
> Now it disables fontconfig if --enable-fontconfig is not in ffmpeg_options.txt 
> so it doesn't get included even if available. 
> If you don't have DirectWrite you need --enable-fontconfig in ffmpeg_options.txt 
> in order for libass to compile.

Yes, thank you, I think I understood this the first time you mentioned it, 
but how do you explain that now (as before my issue occurred) 
libass gets compiled even though `#--enable-fontconfig --enable-libass` 
in ffmpeg options? I certainly did not do any system update...
Is it possible some other lib silently enables fontconfig 
despite it explicitly not being enabled in ffmpeg itself?
[media-autobuild_suite.ini.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/151969/media-autobuild_suite.ini.txt)
[ffmpeg_options.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/151970/ffmpeg_options.txt)

Well, being absent during compilation, I had to 
inspect "compile.log" inside "trunk\build" (attached) 
[compile.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/151957/compile.log.txt)
The following section appears ominous to me, 
and I've also witnessed it in the past but did not 
bother to report: 
`[1m└ x264-git (B[m...................................... [[34mUpdated(B[m]`
 `     2 [main] python2 3384 child_info_fork::abort: address space needed by 'mpatch.dll' (0x560000) is already occupied`
`abort: Resource temporarily unavailable`
`abort: Broken pipe`
`abort: Broken pipe`
`[1m┌ x265 hg (B[m..................................... [[33mRecently updated(B[m]`
Is it really something to worry about?

And, of course, I then read this: 
`[33mffmpeg-0001-configure-Try-pkg-config-first-with-a-few-libs.patch(B[m`
`	Patch couldn't be applied with 'git am'. Continuing without patching.`

That also wasn't fatal, my ffmpeg.exe was built!
I couldn't tell how important that patch failure was, 
and that was the error I hinted about previously.
I thought it was again caused by a fault in my setup, 
but today, while posting this, I became aware of #288. 
So the fix for that is to update the suite to 
snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/b318482 , right?
(I hope I don't break things this time...)

> If the suite keeps failing, you can rename build/last_run to build/last_successful_run 
> so anything that was successfully compiled isn't recompiled again. 
> The script checks if the compiled libs are more recent than that file 
> and compiles certain libs again if they are.

That is a most useful tip, thank you very much indeed!
Noted down for future reference!

Much obliged in general :-)

**Comment by wiiaboo** [comment]
> Is it possible some other lib silently enables fontconfig
despite it explicitly not being enabled in ffmpeg itself?

It shouldn't, but if libass is compiled, everything is fine. Maybe it found DirectWrite this time.

> Is it really something to worry about?

Never seen that before. If nothing stopped compiling, it shouldn't be a problem.

> That also wasn't fatal, my ffmpeg.exe was built!
I couldn't tell how important that patch failure was, 

That patch is non-essential. It probably isn't even needed for the most part. I'll test a smaller version later.
