### ISSUE TITLE
Would it be much work,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#286]
to allow to use another gcc version than gcc 5.3 ?
Having some issues with avisynth + x265 and after comparing some x265 versions compiled by others, it seems like only the gcc 5.3 builds cause the crashes I experience.

**Comment by Selur** [comment]
forget it, just crashed with a 4.8 build,...

**Comment by wiiaboo** [comment]
Also, only 5.3 and git is available through pacman. For other version we would have to rebuild GCC ourselves.
