### ISSUE TITLE
install of libressl-2.3.2 fails!

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#289]
Hello, again!
It looks as though I am cursed :-{

Suite was on snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/841eec4 (after a clean install), 
was working otherwise fine, apart from https://github.com/jb-alvarado/media-autobuild_suite/issues/288.

Earlier today I updated the suite to latest snapshot 
https://github.com/jb-alvarado/media-autobuild_suite/commit/61c949b to get rid of https://github.com/jb-alvarado/media-autobuild_suite/issues/288 and to try the newly 
implemented, librtmp/SSL related, security improvements...
Alas, disappointment again:

libressl-2.3.2 was downloaded, configure'd, 
and after a relatively lengthy first time make, 
it was compiled but **failed to be installed**!
Excerpt from minnty output is attached: 
[minnty_output.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/153773/minnty_output.txt)

As instructed, "ab-suite.install.log" was inspected (attached);
[ab-suite.install.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/153790/ab-suite.install.log.txt)
What stands out from that is line 67 (translated from Greek):
`mkdir: cannot create directory «//local32»: Read-only file system`
Possibly some fault of the code, that adds one extra "/" in the 
directory path; BTW, "openssl.exe" does exist inside "bin-global".
Full log also attached:
[20160301193114Z_logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/153797/20160301193114Z_logs.zip)

Frustrated again, waiting for further instructions...
Regards (still many thanks, despite...)

**Comment by wiiaboo** [comment]
Linux doesn't generally mind double slashes, Windows/Msys does.
