### ISSUE TITLE
x265-hg compilation fails

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#294]
Hi 
Last night, the suite was updated to snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/d2913b31e0d7cbea1fb84cb3ead7ba5b4c5be0a4, 
which is the last to compile x265 from GitHub repo 
and carries the commit hash fix (many thanks). 
All went along fine, I chose to recompile only x265.exe, 
produced binary now reports:

`x265 [info]: HEVC encoder version 1.9+62-g01cba3c`

Commit https://github.com/videolan/x265/commit/01cba3c88bc926bafa899a9b753c5e7511165ac4 is currently the latest in the GitHub repo 
(equivalent to [88aebc1](https://bitbucket.org/multicoreware/x265/commits/88aebc1) in the bitbucket one)

At noon today, suite was manually updated to https://github.com/jb-alvarado/media-autobuild_suite/commit/c3be7e4
(latest), that again compiles x265 from Bitbucket. 

Just to be on the safe side, I deleted:
1. /build/x265-git
2. /build/x265-hg (left-over from 28/02/2016, 
when hg would work with the suite)
3. /local32/bin-video/x265.exe (probably unnecessary).

When I fired up the updated suite, the script was 
halted in the x265-hg stage; no logs.zip was created, 
for starters I've attached direct minnty output:
[minnty_output.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/159963/minnty_output.txt)

(BTW, why does the script currently try 
`x265-fix-git-describe.diff` on hg source?)

In a separate minnty instance, if I run 
`$ hg clone https://bitbucket.org/multicoreware/x265` I get:
[minnty2_output.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/159965/minnty2_output.txt)
EDIT: 
A somewhat similar error also received from time to time:
[minnty3_output.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/159966/minnty3_output.txt)
The errors always occur at the 
"resolving manifests" step ;-{

It appears I can't still fetch source from Bitbucket.
I have tried many times since then, to no avail, 
that is why issue was created...

Is this again msys2 related or particular to my setup/OS (Vista32) ?
Prior to opening this issue, I did a test:
On a second external HDD I have a very old 
image of the suite (from Nov 2014) that has 
not been updated since; in its minnty console I again typed 
`$ hg clone https://bitbucket.org/multicoreware/x265`
and with first attempt I got:
[oldminnty_output.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/159940/oldminnty_output.txt) so it succeeds there (???)

If it matters, I've assembled a "logs.zip" file manually; 
folders "x265-hg/.hg/cache" & "x265-hg/.hg/store" 
were omitted, due to very large size.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/159952/logs.zip)

As an interim workaround, can I simply
1. Rename folder "x265" downloaded via 
old minnty to "x265-hg"
2. Place the latter inside "/build/" 
of the new suite, deleting previously 
created eponymous folder
3. Run the suite again?

Awaiting guidance, for fear of making things worse myself...
Apologies for yet another harassment...

EDIT2:
After googling for those `child_info_fork::abort` errors, 
it appears I may have to "rebaseall" (you probably know 
what that means already, I don't) my MSYS2 system, 
possibly after the updated Python 2.7 package. 
Plus, I discovered in that old HDD a previous (2014) note 
from Jonathan (@jb-alvarado) that said:
>  It's been a long time since I last tested the "32 bit msys2" version, 
> so I didn't notice this error. I think I fixed it now (v2.9).
> You also need to have in mind that when v2.9 runs 
> and later you want to make a new run and the script starts an msys2 update, 
> it can be that after that you have to run the autorebase.bat 
> from the msys32 folder. 
> This only happens with the 32 bit version, but please don't ask me why :).

In current incarnation of the suite, there exist 
two "rebase" batch files: `autorebase.bat` 
& `autorebasebase1st.bat`. 
Do you think jb's note is relevant to my current 
predicament and which of the two .bat should be run? 

Many thanks for any resolution proposed...

**Comment by wiiaboo** [comment]
Try running `autorebase.bat` then. I think the suite runs it already in case of 32-bit Msys.

>  (BTW, why does the script currently try
x265-fix-git-describe.diff on hg source?)

It also has a fix for mercurial version that probably only occurs in Windows.

**Comment by Vangelis66** [comment]
> Try running autorebase.bat then
> Try running it as administrator if it still doesn't work.

**YES**, executing "autorebase.bat" as admin solved my issue:
[compile.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/160432/compile.log.txt)
(albeit with a small harmless error:
`Deleting source folders.../build/media-suite_helper.sh: line 1127: popd: /build/x265-hg/build/msys/8bit: No such file or directory`)

>  I think the suite runs it already in case of 32-bit Msys
> The suite does run it every time after doing the updates for msys32.

So why that issue presented itself in my case?
Sadly I have not kept "update.log" from the time 
I received the Python MSYS update, but 
I can assure you it happened without a glitch 
and then the suite continued to compile tools, 
where, as posted, it errored out on x265-hg.

Perhaps this is only related to x86 architecture 
(thus running msys32), but could the found solution 
be somehow reflected in the wiki? E.g.

_If on x86 Windows OS (thus running msys32) 
and you experience suite failures with various 
**child_info_fork::abort** errors after a recent 
MSYS update, exit the suite and execute as admin
`trunk/msys32/autorebase.bat`_

I wrote:

>`x265 [info]: HEVC encoder version 1.9+62-g01cba3c`
> 
> Commit videolan/x265@01cba3c is currently the latest in the GitHub repo
> (equivalent to [88aebc1](https://bitbucket.org/multicoreware/x265/commits/88aebc1) in the bitbucket one)

In #292 @wiiaboo wrote:

> Also, don't trust git to treat commits the same as mercurial

I fear you are right - freshly compiled binary from Bitbucket reports:

`x265 [info]: HEVC encoder version 1.9+68-88aebc166fa8e16f`

so even if **git-01cba3c**=**hg-88aebc1**, in the first case 
revision is calculated to be **62**, while in the second case it 
is reported as being **68** (???). The mysteries of VCS...

Thank you again for getting me back to 
a working state!

Most kind regards.
