### ISSUE TITLE
fdkaac not included in ffmpeg binary?

### ISSUE THREAD

**Issue by mario897** [jb-alvarado/media-autobuild_suite#295]
I came here to create my own ffmpeg build because I wanted to use fdk-aac. I configured with "license=nonfree" and fdk-aac enabled, then I waited until the building was finished, then I executed
`ffmpeg -i <input> -c:a libfdk_aac -vbr 5 <output>`
However, this showed me the error message
> Unknown encoder 'libfdk_aac'

What went wrong here?
In the "local64\bin-audio" folder, there is indeed a file called "fdkaac.exe", but that's not what I wanted. I wanted to include fdk-aac in ffmpeg. I thought this is allowed if you don't redistribute the .exe afterwards?
Can you (in general) accomplish what I am looking for with your script or did I have wrong expectations?

Other build parameters: 64-bit / tried both static and shared.

P.S. Your claim inside the build script that ffmpeg's native aac is competing or even superior to fdk-aac is daringly given that recent real world listening tests (like [this one](https://hydrogenaud.io/index.php/topic,111085.0.html)) found fdk-aac to be way superior even at 128k.

**Comment by Vangelis66** [comment]
Hello Mario 
I am not the author or maintainer of the script, but:

> I wanted to include fdk-aac in ffmpeg. 
> I thought this is allowed if you don't 
> redistribute the .exe afterwards

Of course it is allowed!

> Can you (in general) accomplish 
> what I am looking for with your script

Of course you can!

As @wiiaboo would surely tell you, you need 
to provide more info regarding what you did 
on your setup, to possibly debug what setting is wrong... 
Mainly, navigate to your "build" directory and look for files:
 
"ffmpeg_options.txt", "mpv_options.txt",
"media-autobuild_suite.ini", "compile.log", 
"last_run", "last_successful_run"

Create a folder named "logs", put those 
files in, zip the folder and upload "logs.zip" 
by first editing your original post and 
then attaching the zip file by drag-n-drop. 

>I configured with "license=nonfree" and fdk-aac enabled

your ffmpeg_options.txt should then contain:
`--enable-nonfree --enable-libfdk-aac`

NB: Do make sure you have downloaded 
the most recent snapshot of the suite; there was 
a typo yesterday (https://github.com/jb-alvarado/media-autobuild_suite/commit/cc0bdbd) 
that was pertinent to libfdk_aac.

Regards

**Comment by mario897** [comment]
I found it out! Thank you for the answer.

It's a little bit complicated with the options, but I think the issue might have been that if you choose "ffmpeg and mpv optional libraries?" = No, then the previous decision to include fdk-aac is being overwritten.

So if I choose "ffmpeg and mpv optional libraries?" = Yes, then add "--enable-libfdk-aac" in ffmpeg_options.txt like you suggested, then it will include fdk-aac in ffmpeg.

I also found a previous discussion where it was said that external tools will not be included in ffmpeg if you choose "standalone"=yes. However, in my case it doesn't matter what I choose here. "ffmpeg and mpv optional libraries?" = No (lite build) indeed overrides my previous decision even if I choose "standalone"=no which might be a bug or at least an usability issue.

**Comment by Vangelis66** [comment]
@mario897 

Please read carefully the commit message at https://github.com/jb-alvarado/media-autobuild_suite/commit/4ebbc6b 
That one was pushed three days ago...

libfdk_aac is an **optional** non-free ffmpeg library, 
so it is not included in "light" & "zeranoe" options 
presets. To enable it in ffmpeg, you either have to choose
 
**`ffmpegChoice=1`** inside "media-autobuild_suite.ini" 
in which case a custom ffmpeg_options.txt file will be 
created (iwhere you can enable/disable libs or 
add other valid configure options, e.g. --disable-ffprobe), 

or choose **`ffmpegChoice=4`** to enable the "full" preset 
which includes `--enable-libfdk-aac`

`fdkaac=1` in "media-autobuild_suite.ini" is needed to 
enable compilation of the library; if `standalone=1`, 
fdkaac.exe is built, but `--enable-libfdk-aac` is not 
a granted; if `fdkaac=1` && `standalone=2`, then 
according to the change introduced in https://github.com/jb-alvarado/media-autobuild_suite/commit/ac9078bea9599c64cec1c9e091f2f5c0f02233cb
`--enable-libfdk-aac` is triggered forcibly.

(I am still learning things, I hope 
I have not posted untruths!)

Cheers.

**Comment by wiiaboo** [comment]
That commit that included libs if standalone=n was reverted, but I'll re-revert just the fdk-aac one for now.

**Comment by Vangelis66** [comment]
@wiiaboo wrote:

> That commit that included libs if standalone=n was reverted

 Apologies, my bad. I should have searched better commits' history.
Indeed, https://github.com/jb-alvarado/media-autobuild_suite/commit/ac9078bea9599c64cec1c9e091f2f5c0f02233cb was reverted 5 days 
later by https://github.com/jb-alvarado/media-autobuild_suite/commit/1175ead3cc5b30eb62310d86390bd9481fb385f7; and today, that 
one was again reverted for fdk-aac only by https://github.com/jb-alvarado/media-autobuild_suite/commit/e8cf8c35fd611b066271a42680749396ab119c18

Thanks and regards
