### ISSUE TITLE
x265 32bit compilation fails

### ISSUE THREAD

**Issue by anana93** [jb-alvarado/media-autobuild_suite#296]
x265 64bit compilation success, but 32bit failed...
It happen since yesterday. Clean install still failed...

here's the log
[https://www.sendspace.com/file/yys6cu](url)

**Comment by wiiaboo** [comment]
Can't reproduce, but I did some fixes to the GCC compiler. Make sure you remove x265-hg and you're using the latest version of the suite before trying again.

**Comment by anana93** [comment]
Clean install again, use latest version of media-autobuild_suite, still failed for compile x265 32bit...
Try again, remove x265-hg, still failed for 32bit...

Here's the log:
[https://www.sendspace.com/file/irzfg1](url)

**Comment by wiiaboo** [comment]
Remove only `x265-hg` and try lowering the core count to 2. Other than trying different stuff, I don't think it's a bug of the script. Try sending an issue to x265 themselves.

**Comment by anana93** [comment]
It works now, for 32 & 64 bit. Thx for the reply...
