### ISSUE TITLE
kvazaar.exe git version info

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#297]
Hello 

This is an **enhancement** request, not a "real" issue.

Much like vpx-git and gpac-git, kvazaar-git also gets very 
frequent updates:
https://github.com/ultravideo/kvazaar/commits
(already three for today so far...)

I have `standalone=1 (.ini)` & `--enable-libkvazaar (options)`, 
so a static **kvazaar.exe** gets compiled. However, unlike the 
frequently updated _vpx(dec|enc).exe_ & _mp4box.exe_, 
every compiled _kvazaar.exe_ simply reports: 
`kvazaar --version` => 
`Kvazaar 0.8.3`
`Kvazaar license: LGPL version 2`

Can I kindly ask you, if at all possible, 
to patch the script in a way similar to 
what was done for _rtmpdump.exe_, so 
that the compiled standalone kvazaar 
binariy prints more useful info about 
its version/git source?

For example, the most fresh compile could report:

`Kvazaar-0.8.3-master-g1671725-20160308-i686-static`

where
**1671725** = commit hash of source
**20160308** = push date of above commit
i686 = architecture of compiled binary

I think I am running out of praise words for you, 
so yes, that is my enhancement request...

Many thanks indeed...

**Comment by wiiaboo** [comment]
You should ask them yourself. For rtmpdump it would be probably be harder, but kvazaar is in github.

**Comment by Vangelis66** [comment]
Thanks for your swift reply!

> You should ask them yourself

I interpret this as an implication the kvazaar 
code itself has to be patched first ...

> but kvazaar is in github

OK then, I'll post my enhancement request 
to their own issue tracker, too...

> For rtmpdump it would probably be harder 

As far as you are concerned, I have no more 
requests with regards to rtmpdump; what you 
have already done in https://github.com/jb-alvarado/media-autobuild_suite/issues/287 is superb!

Regards

**Comment by wiiaboo** [comment]
If they don't think it's necessary, then there's no need to show the commit being used. That's why.

I said to ask them yourself since it's easier for everyone and they're on GitHub too, so you don't need anything extra to ask them.

**Comment by Vangelis66** [comment]
I wrote

> OK then, I'll post my enhancement request
> to their own issue tracker, too...

Just submitted https://github.com/ultravideo/kvazaar/issues/128
Let us wait for their reply...

@wiiaboo wrote: 

> I said to ask them yourself since...

No need to explain yourself further, I did not sense 
even the slightest hint of reluctance on your part;
given the excellent work done on rtmpdump, I 
misthought the same could apply, in suite-code level 
only, for kvazaar too!

All the best.

**Comment by Venti-** [comment]
I guess that would be nice to have. Not exactly sure how to do that, such that it would also work with configure being run outside the git folder, but passing the result of git describe to should be easy enough.

**Comment by wiiaboo** [comment]
x264 uses a shell script during configure to create an header that gets included during compilation: https://git.videolan.org/?p=x264.git;a=blob;f=version.sh;hb=HEAD

**Comment by Venti-** [comment]
I moved my reply to Kvazaar issue, where I originally intended it, but yeah, something like that would be required. Preferably through autoconf that already generates a header. That version could then be overridden by a more up to date version string during make when building in the git directory.
