### ISSUE TITLE
Delete "/bin-video/ffmpeg.exe" only after a successful recompilation

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#299]
I sometimes neglect to transfer successfully 
compiled ffmpeg binaries out of the suite directory
to a different storage location elsewhere on disk.

When the suite arrives at the ffmpeg compilation stage, 
it first deletes extant binary in `/local32/bin-video/`;
in cases like today's (for which I feel partly responsible) 
where compilation fails for one thing or another, 
one is left with no ffmpeg.exe binary at all... :-(

I distinctly remember in older versions of the suite 
(possibly two weeks ago) that I could find unstripped 
(ffmpeg_g.exe) as well as stripped (ffmpeg.exe) copies 
of the last successfully compiled binaries inside 
folder `/build/ffmpeg-git` - I guess a recent suite 
commit "took care" of those copies... 

What I am kindly asking is that existing 
"**/bin-video/ffmpeg.exe**" is deleted (overwritten?) 
only after a successful ffmpeg compilation 
(so it is not wiped out prior to a compilation failure...). 

 We could have the script first backup 
previously compiled binary (if it indeed exists), 
delete the backup after a successful compilation 
or restore the backup after a compilation failure 
(or some other scenario that you can think of 
that has the same net result...)

Regards

**Comment by wiiaboo** [comment]
It could be a matter of just not uninstalling the binaries.

**Comment by Vangelis66** [comment]
Thanks! Despite 

`Add option to uninstall binaries in case some builds fail in the future.`

not being that transparent (did you actually mean 
"_to not uninstall binaries_"?), does https://github.com/jb-alvarado/media-autobuild_suite/commit/1935a745d1972363e7455f7b943d28122322483e have an effect 
on all binaries if `standalone=1` and not just ffmpeg.exe? 

Cheers

**Comment by wiiaboo** [comment]
It's an option for script use only, not for the user. Meaning, if something breaks because the binaries aren't uninstalled (shouldn't be necessary, `make install` always overwrites), it's just enough to add `all` after the respective `do_uninstall`.
