### ISSUE TITLE
Failed at mediainfo step on Server 2012 R2

### ISSUE THREAD

**Issue by voltagex** [jb-alvarado/media-autobuild_suite#300]
[logs.zip](https://0x0.st/Kau.zip)

**Comment by voltagex** [comment]
C:/Users/Administrator/Downloads/media-autobuild_suite-master/build/libmediainfo-git/Project/CMake/build-64bit/CMakeFiles/Export/C_/Users/Administrator/Downloads/media-autobuild_suite-master/local64/lib/cmake/mediainfolib/MediaInfoLibTargets-noconfig.cmake is over 255 characters long, which might be causing some problems. 

I couldn't just move the media-autobuild folder to a shorter path (a whole lot of bash functions were not found), I basically had to start from scratch

**Comment by wiiaboo** [comment]
Windows doesn't like long paths. Added a FAQ to the wiki explaining how to move the suite and a check at the start of the .bat for too long paths.
