### ISSUE TITLE
ffmbc removed?

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#303]
When was ffmbc removed?
Looked into my local32/64 folders but it isn't there any more.
Since the media-autobuild_suite way the only reliable way to get a ffmbc build it's king of a shame that it was removed.

Will all projects that only get updates every 1/2 year be removed one by one?

**Comment by wiiaboo** [comment]
It stopped being reliable.

**Comment by Selur** [comment]
> More exactly, it stopped working with GCC 5.3

Sad to hear that. :(

**Comment by wiiaboo** [comment]
> Will all projects that only get updates every 1/2 year be removed one by one?

If they stop working and I can't fix them, yes. Why would they not?
I didn't sign up to be a maintainer of old projects.

**Comment by Selur** [comment]
Throwing out projects because they seem to be old, doesn't seem a valid reason to me, since most of the projects that are build are old. ;)

I agree that it's a valid point that ffmbc was dropped since it wouldn't compile with newer gcc versions.

**Comment by wiiaboo** [comment]
It's not because they're old, it's because they **_don't work_**.

**Comment by Selur** [comment]
Got it, didn't work with GCC 5.3x -> was dropped.

**Comment by wiiaboo** [comment]
I didn't answer the first question either. It was removed in 6782bf4459617e4220fb762f444a11cf3cb844f3.

**Comment by wiiaboo** [comment]
Readded ffmbc, try it.

**Comment by Selur** [comment]
updated and started the script, will report tomorrow whether it finished :)
