### ISSUE TITLE
kvazaar error

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#313]
stop at the same build every time. Started a new fresh install, but it didn't help.

  Running git update for kvazaar...
┌ kvazaar git ....................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
../../src/encmain.c:501:85: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: all warnings being treated as errors
Makefile:1377: recipe for target 'kvazaar-encmain.o' failed
make[2]: *** [kvazaar-encmain.o] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
Makefile:514: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
Makefile:384: recipe for target 'all' failed
make: *** [all] Error 2

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/200689/logs.zip)

**Comment by wiiaboo** [comment]
@Venti-

**Comment by Venti-** [comment]
Thanks, it's fixed now.

**Comment by ASopH** [comment]
thank you ! good work
