### ISSUE TITLE
git timeout : how to shorten it in case that git host is not reachable ?

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#319]
When git is updating, I have too often that one of the the hosts is not reachable.
The default time-out before git gives up the host and let the rest continue is about 300s = 5 min

This is a very long time if am watching and following the whole build and IMHO makes no sense.
I'd like that git times-out after 30s or max 1 min.

How can I accomplish this ?

**Comment by wiiaboo** [comment]
**http.lowSpeedLimit, http.lowSpeedTime**

    If the HTTP transfer speed is less than http.lowSpeedLimit for longer than http.lowSpeedTime seconds, the transfer is aborted. Can be overridden by the GIT_HTTP_LOW_SPEED_LIMIT and GIT_HTTP_LOW_SPEED_TIME environment variables.
