### ISSUE TITLE
mpv.exe link failure (symbol conflict over fwprintf)

### ISSUE THREAD

**Issue by gglachant** [jb-alvarado/media-autobuild_suite#327]
Multiple definitions of fwprintf when building mpv (defined in libmsvcrt and also in libx265)

Logs generated by the build script: [logs.zip](https://0x0.st/NrB.zip)

Running [latest commit](https://github.com/jb-alvarado/media-autobuild_suite/commit/c5d72c97fe7a81196d5643cf949d343d0ec81fc5) as of this issue.

**Comment by wiiaboo** [comment]
Fixed in https://github.com/jb-alvarado/media-autobuild_suite/commit/cb686bc59c80504e37961aa2ca78971cc504c57d. Hopefully they'll merge this upstream.
