### ISSUE TITLE
libbluray: configure fails with libudfread source tree not found

### ISSUE THREAD

**Issue by voltagex** [jb-alvarado/media-autobuild_suite#328]
[logs.zip](https://0x0.st/N-6.zip)

**Comment by voltagex** [comment]
Looks like #325 but deleting the libbluray source and rebuilding didn't work.

**Comment by wiiaboo** [comment]
Yeah, they're using a deprecated url for the submodule.
Man, fuck submodules.

**Comment by syslogic** [comment]
`git submodule update --init` fetches the headers.
