### ISSUE TITLE
vcs_clone issue in media-suite-helper

### ISSUE THREAD

**Issue by projalepeno** [jb-alvarado/media-autobuild_suite#332]
Hi,

I am getting the following error when building the suite.  It seems to be failing on 'vcs_clone' right after Miinty lists 'running git clone for libopenjp2...'

error log:
[ab-suite.git.clone.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/264407/ab-suite.git.clone.log.txt)

.ini config
[media-autobuild_suite.ini.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/264410/media-autobuild_suite.ini.txt)

I am on Win10 Pro x64 and have the latest packages.  This is a first-time install, not an update.

Thank you for any assistance.

**Comment by wiiaboo** [comment]
I need the logs.zip. Those files don't tell me anything.

**Comment by projalepeno** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/264588/logs.zip)

I didn't have a specific logs.zip file but I gathered all the .log files and zipped them.  Thanks and let me know if you need something else.

**Comment by wiiaboo** [comment]
diagnostics.txt is actually be the most important.

**Comment by wiiaboo** [comment]
Actually, no need. For some reason, git especifically failed installation.
Open mintty using the shortcut and run `pacman -Qi git` and paste here what it says.

**Comment by projalepeno** [comment]
Name            : git
Version         : 2.8.1-1
Description     : The fast distributed version control system
Architecture    : x86_64
URL             : https://git-scm.com/
Licenses        : GPL2
Groups          : VCS
Provides        : git-core
Depends On      : curl  expat>=2.0  libpcre  vim  openssh  openssl  perl-Error  perl>=5.14.0  perl-Authen-SASL
                  perl-libwww  perl-MIME-tools  perl-Net-SMTP-SSL  perl-TermReadKey
Optional Deps   : python2: various helper scripts [installed]
                  subversion: git svn [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : git-core
Installed Size  : 21.86 MiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Tue, Apr 5, 2016 5:02:25 AM
Install Date    : Sat, May 14, 2016 3:11:24 AM
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by wiiaboo** [comment]
And `git status`?

**Comment by projalepeno** [comment]
bash: git: command not found

**Comment by wiiaboo** [comment]
`pacman -S --force git`?

**Comment by projalepeno** [comment]
$ pacman -S --force git
warning: git-2.8.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) git-2.8.1-1

Total Installed Size:  21.86 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [#######################################] 100%
(1/1) checking package integrity                                         [#######################################] 100%
(1/1) loading package files                                              [#######################################] 100%
(1/1) checking for file conflicts                                        [#######################################] 100%
(1/1) checking available disk space                                      [#######################################] 100%
warning: could not get file information for usr/bin/git-cvsserver
warning: could not get file information for usr/bin/git-receive-pack.exe
warning: could not get file information for usr/bin/git-shell.exe
warning: could not get file information for usr/bin/git-upload-archive.exe
warning: could not get file information for usr/bin/git-upload-pack.exe
warning: could not get file information for usr/bin/git.exe
warning: could not get file information for usr/lib/git-core/git-am.exe
warning: could not get file information for usr/lib/git-core/git-annotate.exe
warning: could not get file information for usr/lib/git-core/git-apply.exe
warning: could not get file information for usr/lib/git-core/git-archive.exe
warning: could not get file information for usr/lib/git-core/git-bisect--helper.exe
warning: could not get file information for usr/lib/git-core/git-blame.exe
warning: could not get file information for usr/lib/git-core/git-branch.exe
warning: could not get file information for usr/lib/git-core/git-bundle.exe
warning: could not get file information for usr/lib/git-core/git-cat-file.exe
warning: could not get file information for usr/lib/git-core/git-check-attr.exe
warning: could not get file information for usr/lib/git-core/git-check-ignore.exe
warning: could not get file information for usr/lib/git-core/git-check-mailmap.exe
warning: could not get file information for usr/lib/git-core/git-check-ref-format.exe
warning: could not get file information for usr/lib/git-core/git-checkout-index.exe
warning: could not get file information for usr/lib/git-core/git-checkout.exe
warning: could not get file information for usr/lib/git-core/git-cherry-pick.exe
warning: could not get file information for usr/lib/git-core/git-cherry.exe
warning: could not get file information for usr/lib/git-core/git-clean.exe
warning: could not get file information for usr/lib/git-core/git-clone.exe
warning: could not get file information for usr/lib/git-core/git-column.exe
warning: could not get file information for usr/lib/git-core/git-commit-tree.exe
warning: could not get file information for usr/lib/git-core/git-commit.exe
warning: could not get file information for usr/lib/git-core/git-config.exe
warning: could not get file information for usr/lib/git-core/git-count-objects.exe
warning: could not get file information for usr/lib/git-core/git-credential.exe
warning: could not get file information for usr/lib/git-core/git-describe.exe
warning: could not get file information for usr/lib/git-core/git-diff-files.exe
warning: could not get file information for usr/lib/git-core/git-diff-index.exe
warning: could not get file information for usr/lib/git-core/git-diff-tree.exe
warning: could not get file information for usr/lib/git-core/git-diff.exe
warning: could not get file information for usr/lib/git-core/git-fast-export.exe
warning: could not get file information for usr/lib/git-core/git-fetch-pack.exe
warning: could not get file information for usr/lib/git-core/git-fetch.exe
warning: could not get file information for usr/lib/git-core/git-fmt-merge-msg.exe
warning: could not get file information for usr/lib/git-core/git-for-each-ref.exe
warning: could not get file information for usr/lib/git-core/git-format-patch.exe
warning: could not get file information for usr/lib/git-core/git-fsck-objects.exe
warning: could not get file information for usr/lib/git-core/git-fsck.exe
warning: could not get file information for usr/lib/git-core/git-gc.exe
warning: could not get file information for usr/lib/git-core/git-get-tar-commit-id.exe
warning: could not get file information for usr/lib/git-core/git-grep.exe
warning: could not get file information for usr/lib/git-core/git-gui
warning: could not get file information for usr/lib/git-core/git-hash-object.exe
warning: could not get file information for usr/lib/git-core/git-help.exe
warning: could not get file information for usr/lib/git-core/git-index-pack.exe
warning: could not get file information for usr/lib/git-core/git-init-db.exe
warning: could not get file information for usr/lib/git-core/git-init.exe
warning: could not get file information for usr/lib/git-core/git-interpret-trailers.exe
warning: could not get file information for usr/lib/git-core/git-log.exe
warning: could not get file information for usr/lib/git-core/git-ls-files.exe
warning: could not get file information for usr/lib/git-core/git-ls-remote.exe
warning: could not get file information for usr/lib/git-core/git-ls-tree.exe
warning: could not get file information for usr/lib/git-core/git-mailinfo.exe
warning: could not get file information for usr/lib/git-core/git-mailsplit.exe
warning: could not get file information for usr/lib/git-core/git-merge-base.exe
warning: could not get file information for usr/lib/git-core/git-merge-file.exe
warning: could not get file information for usr/lib/git-core/git-merge-index.exe
warning: could not get file information for usr/lib/git-core/git-merge-ours.exe
warning: could not get file information for usr/lib/git-core/git-merge-recursive.exe
warning: could not get file information for usr/lib/git-core/git-merge-subtree.exe
warning: could not get file information for usr/lib/git-core/git-merge-tree.exe
warning: could not get file information for usr/lib/git-core/git-merge.exe
warning: could not get file information for usr/lib/git-core/git-mktag.exe
warning: could not get file information for usr/lib/git-core/git-mktree.exe
warning: could not get file information for usr/lib/git-core/git-mv.exe
warning: could not get file information for usr/lib/git-core/git-name-rev.exe
warning: could not get file information for usr/lib/git-core/git-notes.exe
warning: could not get file information for usr/lib/git-core/git-pack-objects.exe
warning: could not get file information for usr/lib/git-core/git-pack-redundant.exe
warning: could not get file information for usr/lib/git-core/git-pack-refs.exe
warning: could not get file information for usr/lib/git-core/git-patch-id.exe
warning: could not get file information for usr/lib/git-core/git-prune-packed.exe
warning: could not get file information for usr/lib/git-core/git-prune.exe
warning: could not get file information for usr/lib/git-core/git-pull.exe
warning: could not get file information for usr/lib/git-core/git-push.exe
warning: could not get file information for usr/lib/git-core/git-read-tree.exe
warning: could not get file information for usr/lib/git-core/git-receive-pack.exe
warning: could not get file information for usr/lib/git-core/git-reflog.exe
warning: could not get file information for usr/lib/git-core/git-remote-ext.exe
warning: could not get file information for usr/lib/git-core/git-remote-fd.exe
warning: could not get file information for usr/lib/git-core/git-remote-ftps.exe
warning: could not get file information for usr/lib/git-core/git-remote-http.exe
warning: could not get file information for usr/lib/git-core/git-remote-https.exe
warning: could not get file information for usr/lib/git-core/git-remote.exe
warning: could not get file information for usr/lib/git-core/git-repack.exe
warning: could not get file information for usr/lib/git-core/git-replace.exe
warning: could not get file information for usr/lib/git-core/git-rerere.exe
warning: could not get file information for usr/lib/git-core/git-reset.exe
warning: could not get file information for usr/lib/git-core/git-rev-list.exe
warning: could not get file information for usr/lib/git-core/git-rev-parse.exe
warning: could not get file information for usr/lib/git-core/git-revert.exe
warning: could not get file information for usr/lib/git-core/git-rm.exe
warning: could not get file information for usr/lib/git-core/git-send-pack.exe
warning: could not get file information for usr/lib/git-core/git-shortlog.exe
warning: could not get file information for usr/lib/git-core/git-show-branch.exe
warning: could not get file information for usr/lib/git-core/git-show-ref.exe
warning: could not get file information for usr/lib/git-core/git-show.exe
warning: could not get file information for usr/lib/git-core/git-stage.exe
warning: could not get file information for usr/lib/git-core/git-status.exe
warning: could not get file information for usr/lib/git-core/git-stripspace.exe
warning: could not get file information for usr/lib/git-core/git-submodule--helper.exe
warning: could not get file information for usr/lib/git-core/git-symbolic-ref.exe
warning: could not get file information for usr/lib/git-core/git-tag.exe
warning: could not get file information for usr/lib/git-core/git-unpack-file.exe
warning: could not get file information for usr/lib/git-core/git-unpack-objects.exe
warning: could not get file information for usr/lib/git-core/git-update-index.exe
warning: could not get file information for usr/lib/git-core/git-update-ref.exe
warning: could not get file information for usr/lib/git-core/git-update-server-info.exe
warning: could not get file information for usr/lib/git-core/git-upload-archive.exe
warning: could not get file information for usr/lib/git-core/git-var.exe
warning: could not get file information for usr/lib/git-core/git-verify-commit.exe
warning: could not get file information for usr/lib/git-core/git-verify-pack.exe
warning: could not get file information for usr/lib/git-core/git-verify-tag.exe
warning: could not get file information for usr/lib/git-core/git-whatchanged.exe
warning: could not get file information for usr/lib/git-core/git-worktree.exe
warning: could not get file information for usr/lib/git-core/git-write-tree.exe
warning: could not get file information for usr/lib/git-core/git.exe
:: Processing package changes...
(1/1) reinstalling git                                                   [#######################################] 100%
warning: warning given when extracting /usr/lib/git-core/git-am.exe (Can't create '/usr/lib/git-core/git-am.exe')
warning: warning given when extracting /usr/lib/git-core/git-annotate.exe (Can't create '/usr/lib/git-core/git-annotate.exe')
warning: warning given when extracting /usr/lib/git-core/git-apply.exe (Can't create '/usr/lib/git-core/git-apply.exe')
warning: warning given when extracting /usr/lib/git-core/git-archive.exe (Can't create '/usr/lib/git-core/git-archive.exe')
warning: warning given when extracting /usr/lib/git-core/git-bisect--helper.exe (Can't create '/usr/lib/git-core/git-bisect--helper.exe')
warning: warning given when extracting /usr/lib/git-core/git-blame.exe (Can't create '/usr/lib/git-core/git-blame.exe')
warning: warning given when extracting /usr/lib/git-core/git-branch.exe (Can't create '/usr/lib/git-core/git-branch.exe')
warning: warning given when extracting /usr/lib/git-core/git-bundle.exe (Can't create '/usr/lib/git-core/git-bundle.exe')
warning: warning given when extracting /usr/lib/git-core/git-cat-file.exe (Can't create '/usr/lib/git-core/git-cat-file.exe')
warning: warning given when extracting /usr/lib/git-core/git-check-attr.exe (Can't create '/usr/lib/git-core/git-check-attr.exe')
warning: warning given when extracting /usr/lib/git-core/git-check-ignore.exe (Can't create '/usr/lib/git-core/git-check-ignore.exe')
warning: warning given when extracting /usr/lib/git-core/git-check-mailmap.exe (Can't create '/usr/lib/git-core/git-check-mailmap.exe')
warning: warning given when extracting /usr/lib/git-core/git-check-ref-format.exe (Can't create '/usr/lib/git-core/git-check-ref-format.exe')
warning: warning given when extracting /usr/lib/git-core/git-checkout-index.exe (Can't create '/usr/lib/git-core/git-checkout-index.exe')
warning: warning given when extracting /usr/lib/git-core/git-checkout.exe (Can't create '/usr/lib/git-core/git-checkout.exe')
warning: warning given when extracting /usr/lib/git-core/git-cherry-pick.exe (Can't create '/usr/lib/git-core/git-cherry-pick.exe')
warning: warning given when extracting /usr/lib/git-core/git-cherry.exe (Can't create '/usr/lib/git-core/git-cherry.exe')
warning: warning given when extracting /usr/lib/git-core/git-clean.exe (Can't create '/usr/lib/git-core/git-clean.exe')
warning: warning given when extracting /usr/lib/git-core/git-clone.exe (Can't create '/usr/lib/git-core/git-clone.exe')
warning: warning given when extracting /usr/lib/git-core/git-column.exe (Can't create '/usr/lib/git-core/git-column.exe')
warning: warning given when extracting /usr/lib/git-core/git-commit-tree.exe (Can't create '/usr/lib/git-core/git-commit-tree.exe')
warning: warning given when extracting /usr/lib/git-core/git-commit.exe (Can't create '/usr/lib/git-core/git-commit.exe')
warning: warning given when extracting /usr/lib/git-core/git-config.exe (Can't create '/usr/lib/git-core/git-config.exe')
warning: warning given when extracting /usr/lib/git-core/git-count-objects.exe (Can't create '/usr/lib/git-core/git-count-objects.exe')
warning: warning given when extracting /usr/lib/git-core/git-credential.exe (Can't create '/usr/lib/git-core/git-credential.exe')
warning: warning given when extracting /usr/lib/git-core/git-describe.exe (Can't create '/usr/lib/git-core/git-describe.exe')
warning: warning given when extracting /usr/lib/git-core/git-diff-files.exe (Can't create '/usr/lib/git-core/git-diff-files.exe')
warning: warning given when extracting /usr/lib/git-core/git-diff-index.exe (Can't create '/usr/lib/git-core/git-diff-index.exe')
warning: warning given when extracting /usr/lib/git-core/git-diff-tree.exe (Can't create '/usr/lib/git-core/git-diff-tree.exe')
warning: warning given when extracting /usr/lib/git-core/git-diff.exe (Can't create '/usr/lib/git-core/git-diff.exe')
warning: warning given when extracting /usr/lib/git-core/git-fast-export.exe (Can't create '/usr/lib/git-core/git-fast-export.exe')
warning: warning given when extracting /usr/lib/git-core/git-fetch-pack.exe (Can't create '/usr/lib/git-core/git-fetch-pack.exe')
warning: warning given when extracting /usr/lib/git-core/git-fetch.exe (Can't create '/usr/lib/git-core/git-fetch.exe')
warning: warning given when extracting /usr/lib/git-core/git-fmt-merge-msg.exe (Can't create '/usr/lib/git-core/git-fmt-merge-msg.exe')
warning: warning given when extracting /usr/lib/git-core/git-for-each-ref.exe (Can't create '/usr/lib/git-core/git-for-each-ref.exe')
warning: warning given when extracting /usr/lib/git-core/git-format-patch.exe (Can't create '/usr/lib/git-core/git-format-patch.exe')
warning: warning given when extracting /usr/lib/git-core/git-fsck-objects.exe (Can't create '/usr/lib/git-core/git-fsck-objects.exe')
warning: warning given when extracting /usr/lib/git-core/git-fsck.exe (Can't create '/usr/lib/git-core/git-fsck.exe')
warning: warning given when extracting /usr/lib/git-core/git-gc.exe (Can't create '/usr/lib/git-core/git-gc.exe')
warning: warning given when extracting /usr/lib/git-core/git-get-tar-commit-id.exe (Can't create '/usr/lib/git-core/git-get-tar-commit-id.exe')
warning: warning given when extracting /usr/lib/git-core/git-grep.exe (Can't create '/usr/lib/git-core/git-grep.exe')
warning: warning given when extracting /usr/lib/git-core/git-gui (Can't create '/usr/lib/git-core/git-gui')
warning: warning given when extracting /usr/lib/git-core/git-hash-object.exe (Can't create '/usr/lib/git-core/git-hash-object.exe')
warning: warning given when extracting /usr/lib/git-core/git-help.exe (Can't create '/usr/lib/git-core/git-help.exe')
warning: warning given when extracting /usr/lib/git-core/git-index-pack.exe (Can't create '/usr/lib/git-core/git-index-pack.exe')
warning: warning given when extracting /usr/lib/git-core/git-init-db.exe (Can't create '/usr/lib/git-core/git-init-db.exe')
warning: warning given when extracting /usr/lib/git-core/git-init.exe (Can't create '/usr/lib/git-core/git-init.exe')
warning: warning given when extracting /usr/lib/git-core/git-interpret-trailers.exe (Can't create '/usr/lib/git-core/git-interpret-trailers.exe')
warning: warning given when extracting /usr/lib/git-core/git-log.exe (Can't create '/usr/lib/git-core/git-log.exe')
warning: warning given when extracting /usr/lib/git-core/git-ls-files.exe (Can't create '/usr/lib/git-core/git-ls-files.exe')
warning: warning given when extracting /usr/lib/git-core/git-ls-remote.exe (Can't create '/usr/lib/git-core/git-ls-remote.exe')
warning: warning given when extracting /usr/lib/git-core/git-ls-tree.exe (Can't create '/usr/lib/git-core/git-ls-tree.exe')
warning: warning given when extracting /usr/lib/git-core/git-mailinfo.exe (Can't create '/usr/lib/git-core/git-mailinfo.exe')
warning: warning given when extracting /usr/lib/git-core/git-mailsplit.exe (Can't create '/usr/lib/git-core/git-mailsplit.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-base.exe (Can't create '/usr/lib/git-core/git-merge-base.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-file.exe (Can't create '/usr/lib/git-core/git-merge-file.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-index.exe (Can't create '/usr/lib/git-core/git-merge-index.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-ours.exe (Can't create '/usr/lib/git-core/git-merge-ours.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-recursive.exe (Can't create '/usr/lib/git-core/git-merge-recursive.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-subtree.exe (Can't create '/usr/lib/git-core/git-merge-subtree.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge-tree.exe (Can't create '/usr/lib/git-core/git-merge-tree.exe')
warning: warning given when extracting /usr/lib/git-core/git-merge.exe (Can't create '/usr/lib/git-core/git-merge.exe')
warning: warning given when extracting /usr/lib/git-core/git-mktag.exe (Can't create '/usr/lib/git-core/git-mktag.exe')
warning: warning given when extracting /usr/lib/git-core/git-mktree.exe (Can't create '/usr/lib/git-core/git-mktree.exe')
warning: warning given when extracting /usr/lib/git-core/git-mv.exe (Can't create '/usr/lib/git-core/git-mv.exe')
warning: warning given when extracting /usr/lib/git-core/git-name-rev.exe (Can't create '/usr/lib/git-core/git-name-rev.exe')
warning: warning given when extracting /usr/lib/git-core/git-notes.exe (Can't create '/usr/lib/git-core/git-notes.exe')
warning: warning given when extracting /usr/lib/git-core/git-pack-objects.exe (Can't create '/usr/lib/git-core/git-pack-objects.exe')
warning: warning given when extracting /usr/lib/git-core/git-pack-redundant.exe (Can't create '/usr/lib/git-core/git-pack-redundant.exe')
warning: warning given when extracting /usr/lib/git-core/git-pack-refs.exe (Can't create '/usr/lib/git-core/git-pack-refs.exe')
warning: warning given when extracting /usr/lib/git-core/git-patch-id.exe (Can't create '/usr/lib/git-core/git-patch-id.exe')
warning: warning given when extracting /usr/lib/git-core/git-prune-packed.exe (Can't create '/usr/lib/git-core/git-prune-packed.exe')
warning: warning given when extracting /usr/lib/git-core/git-prune.exe (Can't create '/usr/lib/git-core/git-prune.exe')
warning: warning given when extracting /usr/lib/git-core/git-pull.exe (Can't create '/usr/lib/git-core/git-pull.exe')
warning: warning given when extracting /usr/lib/git-core/git-push.exe (Can't create '/usr/lib/git-core/git-push.exe')
warning: warning given when extracting /usr/lib/git-core/git-read-tree.exe (Can't create '/usr/lib/git-core/git-read-tree.exe')
warning: warning given when extracting /usr/lib/git-core/git-receive-pack.exe (Can't create '/usr/lib/git-core/git-receive-pack.exe')
warning: warning given when extracting /usr/lib/git-core/git-reflog.exe (Can't create '/usr/lib/git-core/git-reflog.exe')
warning: warning given when extracting /usr/lib/git-core/git-remote-ext.exe (Can't create '/usr/lib/git-core/git-remote-ext.exe')
warning: warning given when extracting /usr/lib/git-core/git-remote-fd.exe (Can't create '/usr/lib/git-core/git-remote-fd.exe')
warning: warning given when extracting /usr/lib/git-core/git-remote-ftps.exe (Can't create '/usr/lib/git-core/git-remote-ftps.exe')
warning: warning given when extracting /usr/lib/git-core/git-remote-http.exe (Can't create '/usr/lib/git-core/git-remote-http.exe')
warning: warning given when extracting /usr/lib/git-core/git-remote-https.exe (Can't create '/usr/lib/git-core/git-remote-https.exe')
warning: warning given when extracting /usr/lib/git-core/git-remote.exe (Can't create '/usr/lib/git-core/git-remote.exe')
warning: warning given when extracting /usr/lib/git-core/git-repack.exe (Can't create '/usr/lib/git-core/git-repack.exe')
warning: warning given when extracting /usr/lib/git-core/git-replace.exe (Can't create '/usr/lib/git-core/git-replace.exe')
warning: warning given when extracting /usr/lib/git-core/git-rerere.exe (Can't create '/usr/lib/git-core/git-rerere.exe')
warning: warning given when extracting /usr/lib/git-core/git-reset.exe (Can't create '/usr/lib/git-core/git-reset.exe')
warning: warning given when extracting /usr/lib/git-core/git-rev-list.exe (Can't create '/usr/lib/git-core/git-rev-list.exe')
warning: warning given when extracting /usr/lib/git-core/git-rev-parse.exe (Can't create '/usr/lib/git-core/git-rev-parse.exe')
warning: warning given when extracting /usr/lib/git-core/git-revert.exe (Can't create '/usr/lib/git-core/git-revert.exe')
warning: warning given when extracting /usr/lib/git-core/git-rm.exe (Can't create '/usr/lib/git-core/git-rm.exe')
warning: warning given when extracting /usr/lib/git-core/git-send-pack.exe (Can't create '/usr/lib/git-core/git-send-pack.exe')
warning: warning given when extracting /usr/lib/git-core/git-shortlog.exe (Can't create '/usr/lib/git-core/git-shortlog.exe')
warning: warning given when extracting /usr/lib/git-core/git-show-branch.exe (Can't create '/usr/lib/git-core/git-show-branch.exe')
warning: warning given when extracting /usr/lib/git-core/git-show-ref.exe (Can't create '/usr/lib/git-core/git-show-ref.exe')
warning: warning given when extracting /usr/lib/git-core/git-show.exe (Can't create '/usr/lib/git-core/git-show.exe')
warning: warning given when extracting /usr/lib/git-core/git-stage.exe (Can't create '/usr/lib/git-core/git-stage.exe')
warning: warning given when extracting /usr/lib/git-core/git-status.exe (Can't create '/usr/lib/git-core/git-status.exe')
warning: warning given when extracting /usr/lib/git-core/git-stripspace.exe (Can't create '/usr/lib/git-core/git-stripspace.exe')
warning: warning given when extracting /usr/lib/git-core/git-submodule--helper.exe (Can't create '/usr/lib/git-core/git-submodule--helper.exe')
warning: warning given when extracting /usr/lib/git-core/git-symbolic-ref.exe (Can't create '/usr/lib/git-core/git-symbolic-ref.exe')
warning: warning given when extracting /usr/lib/git-core/git-tag.exe (Can't create '/usr/lib/git-core/git-tag.exe')
warning: warning given when extracting /usr/lib/git-core/git-unpack-file.exe (Can't create '/usr/lib/git-core/git-unpack-file.exe')
warning: warning given when extracting /usr/lib/git-core/git-unpack-objects.exe (Can't create '/usr/lib/git-core/git-unpack-objects.exe')
warning: warning given when extracting /usr/lib/git-core/git-update-index.exe (Can't create '/usr/lib/git-core/git-update-index.exe')
warning: warning given when extracting /usr/lib/git-core/git-update-ref.exe (Can't create '/usr/lib/git-core/git-update-ref.exe')
warning: warning given when extracting /usr/lib/git-core/git-update-server-info.exe (Can't create '/usr/lib/git-core/git-update-server-info.exe')
warning: warning given when extracting /usr/lib/git-core/git-upload-archive.exe (Can't create '/usr/lib/git-core/git-upload-archive.exe')
warning: warning given when extracting /usr/lib/git-core/git-var.exe (Can't create '/usr/lib/git-core/git-var.exe')
warning: warning given when extracting /usr/lib/git-core/git-verify-commit.exe (Can't create '/usr/lib/git-core/git-verify-commit.exe')
warning: warning given when extracting /usr/lib/git-core/git-verify-pack.exe (Can't create '/usr/lib/git-core/git-verify-pack.exe')
warning: warning given when extracting /usr/lib/git-core/git-verify-tag.exe (Can't create '/usr/lib/git-core/git-verify-tag.exe')
warning: warning given when extracting /usr/lib/git-core/git-whatchanged.exe (Can't create '/usr/lib/git-core/git-whatchanged.exe')
warning: warning given when extracting /usr/lib/git-core/git-worktree.exe (Can't create '/usr/lib/git-core/git-worktree.exe')
warning: warning given when extracting /usr/lib/git-core/git-write-tree.exe (Can't create '/usr/lib/git-core/git-write-tree.exe')
warning: warning given when extracting /usr/lib/git-core/git.exe (Can't create '/usr/lib/git-core/git.exe')
warning: warning given when extracting /usr/bin/git-cvsserver (Can't create '/usr/bin/git-cvsserver')
warning: warning given when extracting /usr/bin/git-receive-pack.exe (Can't create '/usr/bin/git-receive-pack.exe')
warning: warning given when extracting /usr/bin/git-shell.exe (Can't create '/usr/bin/git-shell.exe')
warning: warning given when extracting /usr/bin/git-upload-archive.exe (Can't create '/usr/bin/git-upload-archive.exe')
warning: warning given when extracting /usr/bin/git-upload-pack.exe (Can't create '/usr/bin/git-upload-pack.exe')
warning: warning given when extracting /usr/bin/git.exe (Can't create '/usr/bin/git.exe')

**Comment by wiiaboo** [comment]
Never seen that before. So weird.
According to a thread I found the issue can be that you're running the suite in a FAT drive? Can you check?

**Comment by projalepeno** [comment]
it is exFAT... I can move it to the C: drive and give it a go

**Comment by wiiaboo** [comment]
Git package uses hard-links which don't work with FAT, so that'll probably fix it.
After moving, make sure to delete `/msys64/etc/fstab` file before running the suite, since that has hardcoded paths.

**Comment by projalepeno** [comment]
same issue after moving to the C: drive and removing the file in /msys64/etc/fstab

I can restart the whole process.  Maybe something else got messed up running it from the exFAT drive.

**Comment by wiiaboo** [comment]
Probably. I'll add that FAT issue to the FAQ.

**Comment by wiiaboo** [comment]
ReFS drives (from Windows Server?) also don't support hard links, so in Windows, only NTFS is supported.

**Comment by projalepeno** [comment]
good to know.  thanks for the assist!... I was using a fast external drive that I can take between systems (thus exFAT).  it is trying to rebuild from scratch now so I'll post a comment later with the status.

**Comment by projalepeno** [comment]
it just got past the step it was failing on before, so looking good.  Will post an update later

**Comment by projalepeno** [comment]
it worked.  really appreciate your help.  thanks again.
