### ISSUE TITLE
git.videolan.org is down

### ISSUE THREAD

**Issue by voltagex** [jb-alvarado/media-autobuild_suite#334]
Yes, I realise this isn't your issue but it'll break a lot of media-autobuild-suite builds. Perhaps the libraries should be mirrored somewhere?

I was going to list out the affected libraries and then I realised this includes x264 so it's basically pointless. One of the most used libraries around and they're not funded enough to keep a reliable source control server :-1:

**Comment by wiiaboo** [comment]
It won't stay down forever. They're getting hit by a DoS or something.

**Comment by moppman** [comment]
yeah, seem completely down now, I noticed extremely low speeds in the last couple of days already...
https://git.ffmpeg.org/ffmpeg.git looks good, though.

**Comment by wiiaboo** [comment]
FFmpeg has been replaced, but the others that only have videolan as official repo, there's no point in changing. We can't get updates but the devs can't push updates either, so no point.

**Comment by wiiaboo** [comment]
It's back.

**Comment by voltagex** [comment]
According to IRC, hardware failure :(. Thanks though.
