### ISSUE TITLE
Q : MPV & angle backend

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#337]
This is probably not an issue from the media-autobuild_suite, but I ask it here anyway because it is certain a common issue for all the users from the media-autobuild_suite.

I can't get the dynamic loading from the Angle-backend to work in mpv. 
Here's what I have tried do far with mp.exe & mpv.com 32 bit in a separate directory:

1. Copy the libEGL.dll & libglesv2.dll from my Chrome-installation to the directory  containing mpv.{exe,com}.   trying to play a MKV ->  black screen with a lot of shader loading errors.
Copy also from Chrome the file "d3dcompiler_47.dll" to mpv folder.
Now the MKV plays ok with 32bit MPV.
However, can't be sure whether angle-backend is actually loaded and used..

2. Now trying to get it work for MPV 64 bit.
AFAIK, Chrome is only 32bit, so this is no option.
Getting Angle-project via pacman : the 2 dll's are further depended on other MingW-files (like stdc++, winpthread). After I copy everything (2 dll's + MingW files) to MPV directory, it seems to work.
However, can't be sure whether angle-backend is actually loaded and used.

3. Compile the 2 dll's myself using the same makefile we used to compile static angle-backend.
"make libEGL.dll"   compiles both static and dynamic libs, including  libEGL.dll & libglesv2.dll.
Upon testing with MPV however, MPV allways crashes immediately.................. no idea why.
The .dll's have no MingW dependencies.

Is there a way to be 100 sure  that MPV is loading and using the angle-backend ?
Some parameter to force it ?
I use the following parameters for mpv :  -vo opengl
( This works with and without angle backend)

As most users compile 64 bit (I do both), I wonder how other users got the angle-backend working.

**Comment by wiiaboo** [comment]
Chrome has 64-bit builds.
To force angle use `--vo opengl=backend=angle`

**Comment by pat357** [comment]
For compiling, you said to set ""SHARED=y"" as an argument for MAKE or as an ENV variable ?

**Comment by wiiaboo** [comment]
Both should work, maybe.
I've posted an updated [makefile](https://gist.github.com/wiiaboo/b56661ced88adfa9f71c) in gist. Static ANGLE was never officially supported upstream and now it's not supported in mpv, so I removed that.
Mingw's Angle is good enough for me, so I won't keep updating  that gist or readd it to the suite.

**Comment by pat357** [comment]
When using the Mingw Angel-backend .DLL's, you always have to put/have the 2 extra DLL's from MingW (stdc++, winpthread) in your path.
I still think it would be better to  compile these ourselves, so no dependencies from MingW are needed.
I don't run MPV under MingW, just in plain Windows 7/8 !

**Comment by pat357** [comment]
\\\\\\\\\\

**Comment by wiiaboo** [comment]
I mean mingw's angle headers. The dlls I get from Chrome.
To keep building would mean I'd have to keep changing the patch over and over for every little modification and there's no point, imo. It's an optional backend that even runs worse than the other two for me, so even less point.
You're welcome to send a PR and keep updating it.

**Comment by pat357** [comment]
You're right about maintaining the patch needed to compile it yourself : keeping it up-to-date is a never ending job.
The issue about the needed "d3dcompiler_47.dll" is undocumented and not so easy to figure out because none of the other .dll files has a visible dependency to this "d3dcompiler_47.dll". 
Maybe this is worthwhile to mention it in your doc's or in the suite itself.
Also about Google 32/64 bit : you need the correct architecture depending on how mpv was compiled(32 or 64 bit). -> useful for mentioning in your doc.

BTW, I've tried "d3dcompiler_43.dll", but this was a no-go (blue screen with errors about loading shaders).
Probably because the google dll's are compiled with d3dcompiler4.7 present...

Anyway, keep up the great job !

Ps.
In the script you use something like [[ $hash ]] as a condition:
is it the same as
1. [[ -e $hash ]] / test -e "$hash"  or
2. [[ ! -z $hash ]] / [[ -n $hash ]] or 
3. [[ -g hash ]]
 
What if hash is not defined (does not exist) ?
What if hash is 0 ?
What for other non-zero values of hash ?

**Comment by wiiaboo** [comment]
> Also about Google 32/64 bit : you need the correct architecture depending on how mpv was compiled(32 or 64 bit). -> useful for mentioning in your doc.

The wiki is public, you can make a simple article about it.

> In the script you use something like [[ $hash ]] as a condition:

Same as [[ -n $hash ]]. If you don't surround it with quotes it can be misinterpreted.

**Comment by wiiaboo** [comment]
There, it's back.

d3dcompiler_47.dll comes with Windows 8/8.1/10, so that's why I never needed it. For Vista/7, you need to get d3dcompiler_47.dll from Win 8.1 SDK, d3dcompiler_46.dll from Win8 SDK or d3dcompiler_43.dll from DirectX 9 redistributables. Supposedly it should work with either of these.
