### ISSUE TITLE
Question: Is there an easy way to apply an additional patch ...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#338]
to x265, but only for to the numa build?
I'd like to apply the patch from https://patches.videolan.org/patch/13436/ but from the looks of it, it can only be applied to the numa enabled version.

**Comment by wiiaboo** [comment]
Why only the numa version? Doesn't it only affect numa-enabled stuff?

Check https://github.com/jb-alvarado/media-autobuild_suite/commit/4398c014e9b87c35c32fb14f9cf77607b154aeff.

`do_patch numa.diff` tries to get the patch from `http://jb-alvarado.github.io/media-autobuild_suite/patches/numa.diff, and if the url doesn't exist → from the same dir (`/build/x265-hg/numa.diff`) or from the patches dir (`/build/patches/numa.diff`).

You can also run patch manually, using something like `patch -p1 -N < numa.diff`.
