### ISSUE TITLE
compiled Angle-backend doen't work for 32-bit

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#339]
I just compiled the Angle-backend (32bit), compile went fine, but MPV 32bit gave an error on running:
"Error opening/initializing the selected video_out (-vo) device."
This is the command I used "mpv --vo opengl=backend=angle ..... "

Did this 32bit work on your system ??

Upon first test, the 64-bit version seems to work !  Great job !
Will do more tests.

**Comment by wiiaboo** [comment]
I can confirm it doesn't work with 32-bit, but I still don't care about it. It works fine with Chrome/Visual Studio DLLs.

**Comment by wiiaboo** [comment]
I've uploaded my [builds of angle](https://i.fsbn.eu/pub/angle/) if you want to check the speed difference. It's more noticeable with better scalers.

**Comment by pat357** [comment]
I've been trying to narrow down the problem with the 32-bit compile: it's a function "_setjmp3"  in "libGLESv2.dll" that should be in our "msvcrt.dll", but doesn't exist in the latter.
In the 64bit version the function is _setjmp (without the 3) which does exist in the 64 bit "msvcrt.dll".
Maybe we don't have the correct version... or maybe there is a bug in MingW...

If I just could compile the 32-bit "libGLESv2.dll" with msvcrt.dll  *statically* linked in, than I guess it works.
Do you happen to know how to accomplish this ?

It *is* possible because I 've done so when compiling .exe's to avoid msvcrt shit on different systems.
These MS runtime problems are not so uncommon, as it is a mess from different "almost" compatible versions with enough differences that one fails while the other just works.

**Comment by wiiaboo** [comment]
Maybe check if the patches other people use help, like [MinGW's](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-angleproject-git) or [Fedora's](http://pkgs.fedoraproject.org/cgit/rpms/mingw-angleproject.git/).
Since it's more troublesome and slower, I have little to no interest in fixing this.
