### ISSUE TITLE
media-suite_helper.sh 'source'ing fails

### ISSUE THREAD

**Issue by Patlamgoc** [jb-alvarado/media-autobuild_suite#341]
media-suite_compile.sh fails with 'command not found' errors as 'source'ing of media-suite_helper.sh fails as LOCALBUILDDIR variable is empty before 'profile.local' is sourced. 'newchangelog' goes to wrong directory (/) also. I didn't dig the script for other potential early referencing problems but setting LOCALBUILDDIR manually at the very beginning seems to work.
(cb3b76ac863d30cccd4e5da737df48d3fcce5228)

**Comment by wiiaboo** [comment]
Failed installation, delete everything and try again.
If it fails again, post logs.zip, or I can't do anything.

**Comment by Patlamgoc** [comment]
As helper is not included in the first place and everything fails very prematurely, obviously 'logs.zip' thingy is not working also, so I made a collection of logs manually, but nothing fancy in them really. I think compile script should source profile.local immediately after getting the variables from bat file to set the environment properly but not in the late stage of run_builds() call.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/288340/logs.zip)

**Comment by wiiaboo** [comment]
It should anyway. It adds a source profile.local to `/msys64/etc/profile` which should source `/local64/etc/profile.local` right at the start of a new session.

Can you check that first file and if anything exists in /local64/etc/profile.local?

**Comment by Patlamgoc** [comment]
Yes, files are perfectly intact, here is another zip. I indeed saw your profile.local call in the msys64 profile and it is really strange that LOCALBUILDDIR is still empty.
[profiles.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/288360/profiles.zip)

**Comment by wiiaboo** [comment]
Can you paste contents of /msys64/etc/fstab?

**Comment by Patlamgoc** [comment]
Here it is:
`none / cygdrive binary,posix=0,noacl,user 0 0

C:\media-autobuild_suite\ /trunk
C:\media-autobuild_suite\build\ /build
C:\media-autobuild_suite\msys64\mingw32\ /mingw32
C:\media-autobuild_suite\msys64\mingw64\ /mingw64
C:\media-autobuild_suite\local32\ /local32
C:\media-autobuild_suite\local64\ /local64`

**Comment by wiiaboo** [comment]
And that's indeed the root of the suite?
`cygpath -w /trunk` does return `C:\media-autobuild_suite`?

**Comment by Patlamgoc** [comment]
Yes, no problem here also.
![captrure](https://cloud.githubusercontent.com/assets/19628633/15633814/f5fcbc5c-25be-11e6-85bd-043c2572dc04.PNG)

**Comment by wiiaboo** [comment]
Lol, and manually `source /local64/etc/profile.local` works?

**Comment by Patlamgoc** [comment]
Yes, as always dirty fixing works perfectly :)

By the way, I'm on Windows 10 Pro x64 Insider Preview Build 14342 and using an account with administrator rights. Though being irrelevant, I also tried even setting Everyone-Full Control on security and as I also have VS2015 Community edition on the box, I even checked if some name clash might destroy the environment but can't find anything. Strange really.

**Comment by wiiaboo** [comment]
Run just the mintty shortcut and paste what returns from `echo $MSYSTEM`.

**Comment by Patlamgoc** [comment]
`MSYS`

**Comment by wiiaboo** [comment]
OK, that solves the issue.
Try removing `-z "$MSYSTEM" &&` from that `if` in /msys64/etc/profile and the suite should work now.
Should look like:
```bash
if [[ -f /local64/etc/profile.local ]]; then
```

**Comment by Patlamgoc** [comment]
Yes, it works now (with original `media-suite_compile.sh`), but I'm not sure if problem can still affect 32bit builds.

**Comment by wiiaboo** [comment]
It shouldn't.

**Comment by Patlamgoc** [comment]
Thank you very much for your time and efforts :)

**Comment by wiiaboo** [comment]
The /local(32|64) are always there if respective builds are being run. It doesn't depend on msys bitness.

**Comment by Patlamgoc** [comment]
Thanks for the remark, I've just tried to remind if `profile` file would be exported to an msys32 properly also, and I'm confirming that d90c698fbce6802a3a41bd1ccc6e4bf8e240e635 works perfectly here.

**Comment by wiiaboo** [comment]
It should. It's the `%msys32%` variable there in line 1463 of the .bat.

**Comment by Patlamgoc** [comment]
Yes, line 140 sets the target and 1463 exports well. I know you mean `%msys2%` but just remarking the typo for future readers :) Thanks again.
