### ISSUE TITLE
x265 ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#342]
Hi. Error compiling x265, 12-bit (msys32):

"├ Running ninja...
Likely error:
                                                            ^
ninja: build stopped: subcommand failed.
[1/37] Building CXX object common/CMakeFiles/common.dir/threadpool.cpp.obj
[2/37] Building CXX object common/CMakeFiles/common.dir/wavefront.cpp.obj
FAILED: D:\ffmpeg_build\media-autobuild_suite-master\msys32\mingw32\bin\c++.exe   -DEXPORT_C_API=0 -DHAVE_INT_TYPES_H=1 -DHIGH_BIT_DEPTH=1 -DX265_ARCH_X86=1 -DX265_DEPTH=12 -DX265_NS=x265_12bit -D_WIN32_WINNT=_WIN32_WINNT_WINXP -D_WIN32_WINNT_WIN7=0x0601 -D__STDC_LIMIT_MACROS=1 -ID:/ffmpeg_build/media-autobuild_suite-master/build/x265-hg/source/. -ID:/ffmpeg_build/media-autobuild_suite-master/build/x265-hg/source/common -ID:/ffmpeg_build/media-autobuild_suite-master/build/x265-hg/source/encoder -I. -mthreads -mtune=generic -O2 -pipe  -O3 -DNDEBUG   -Wall -Wextra -Wshadow -std=gnu++98 -march=i686 -Wno-array-bounds -ffast-math -mstackrealign -fno-exceptions -MMD -MT common/CMakeFiles/common.dir/threadpool.cpp.obj -MF common/CMakeFiles/common.dir/threadpool.cpp.obj.d -o common/CMakeFiles/common.dir/threadpool.cpp.obj -c D:/ffmpeg_build/media-autobuild_suite-master/build/x265-hg/source/common/threadpool.cpp
D:/ffmpeg_build/media-autobuild_suite-master/build/x265-hg/source/common/threadpool.cpp: In static member function 'static int x265_12bit::ThreadPool::getCpuCount()':
D:/ffmpeg_build/media-autobuild_suite-master/build/x265-hg/source/common/threadpool.cpp:590:66: error: 'GetNumaNodeProcessorMaskEx' was not declared in this scope
         GetNumaNodeProcessorMaskEx((UCHAR)i, groupAffinityPointer);
                                                                  ^
ninja: build stopped: subcommand failed."_

Please find error logs at: [logs.zip](https://0x0.st/b3K.zip)
regards,
laurfb

**Comment by wiiaboo** [comment]
Just wait a couple hours or report to them next time.
