### ISSUE TITLE
patch for libopenh264 no longer online ?

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#343]
See title concerning "ffmpeg-0001-lavc-libopenh264enc-update-to-openh264-1.6.patch"
I tried to compile ffmpeg (with libopenh264 enabled)  -without- the patch, but this was a NO-GO.

With the patch ffmpeg always compiles fine.

**Comment by pat357** [comment]
If you wonder where I'm looking for this patch:
https://github.com/jb-alvarado/media-autobuild_suite/tree/master/build/patches

**Comment by wiiaboo** [comment]
Patches and extra files were moved to another branch.
https://github.com/jb-alvarado/media-autobuild_suite/blob/gh-pages/patches/ffmpeg-0001-lavc-libopenh264enc-update-to-openh264-1.6.patch
