### ISSUE TITLE
Smaller master ZIP archive for download?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#344]
Not really an issue if there is no content missing; I just noticed that the master ZIP archive you can download from github is now a lot smaller than it used to be (<60 KB instead of >120 KB before). Did you reduce the content, or is just the ZIP suddenly compressed now (and was not before)?

**Comment by wiiaboo** [comment]
The patches and nvenc/decklink headers are in a separate branch now.
