### ISSUE TITLE
GPU resize

### ISSUE THREAD

**Issue by GregAlanR** [jb-alvarado/media-autobuild_suite#349]
Would it be possible to add "nvresize" filter to the windows build ? 
Here's the info for Ubuntu: http://developer.download.nvidia.com/compute/redist/ffmpeg/1511-patch/FFMPEG-with-NVIDIA-Acceleration-on-Ubuntu_UG_v01.pdf
PDF linked on this page: https://developer.nvidia.com/ffmpeg

Here's a link with more info from FFmpeg-devel: https://ffmpeg.org/pipermail/ffmpeg-devel/2015-November/182781.html

With the GPU resize a total hardware transcode chain could be used with resizing.
Software resizing with swscale creates a bottle neck that slows hardware decoding/encoding on my GTX 960 by almost 50%.

Thank you

**Comment by wiiaboo** [comment]
I can't. No Nvidia gpu to test it. PRs welcome.

**Comment by wiiaboo** [comment]
Also, from reading the thread, that patch won't be applied, so no point.

**Comment by wiiaboo** [comment]
I've bought a Nvidia card now but apparently libnpp can't be included statically in Windows, so you'd need CUDA SDK installed to even run FFmpeg.
