### ISSUE TITLE
Daala: Add "decoder-example.exe" standalone 

### ISSUE THREAD

**Issue by moppman** [jb-alvarado/media-autobuild_suite#350]
Would be nice to be able to decode back to .y4m in order to make better comparisons.

**Comment by wiiaboo** [comment]
There's no decoder-example. You mean dump-video.exe, I guess?

**Comment by moppman** [comment]
Ah, sorry, I was referencing this: https://wiki.xiph.org/Daala_Quickstart_Windows
They mention "decoder-example.exe" under the "Building the executables" section, but later seem to call it dump-video indeed.

**Comment by wiiaboo** [comment]
Maybe the Visual Studio version changes it to decoder-example.exe.
