### ISSUE TITLE
gpac compile error

### ISSUE THREAD

**Issue by kronflux** [jb-alvarado/media-autobuild_suite#351]
I'm not entirely sure of the context of the error message here, but it says copy and paste this?
[logs.zip](https://0x0.st/TG_.zip)

Specifically(just in case that's not relevant), here's a pastebin of the error log

http://pastebin.com/raw/wWvmWg4x

**Comment by moppman** [comment]
Got this just now:
`Likely error:
make[1]: Entering directory '/build/gpac-git/build-64bit/src'
  CC /build/gpac-git/src/terminal/media_object.c
C:/media-autobuild_suite-master/build/gpac-git/src/terminal/media_object.c: In function 'gf_mo_hint_quality_degradation':
C:/media-autobuild_suite-master/build/gpac-git/src/terminal/media_object.c:1487:2: error: stray '\302' in program
  if (!mo->odm || !mo->odm->codec) {
  ^
C:/media-autobuild_suite-master/build/gpac-git/src/terminal/media_object.c:1487:2: error: stray '\240' in program
make[1]: *** [../config.mak:140: terminal/media_object.o] Error 1
make[1]: Leaving directory '/build/gpac-git/build-64bit/src'
make: *** [Makefile:9: all] Error 2
make failed. Check C:/media-autobuild_suite-master/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...`

[https://0x0.st/Td2.zip](Log.zip)
