### ISSUE TITLE
Still gpac compile error

### ISSUE THREAD

**Issue by moppman** [jb-alvarado/media-autobuild_suite#352]
Got this just now:
`Likely error:
make[1]: Entering directory '/build/gpac-git/build-64bit/src'
  CC /build/gpac-git/src/terminal/media_object.c
C:/media-autobuild_suite-master/build/gpac-git/src/terminal/media_object.c: In function 'gf_mo_hint_quality_degradation':
C:/media-autobuild_suite-master/build/gpac-git/src/terminal/media_object.c:1487:2: error: stray '\302' in program
  if (!mo->odm || !mo->odm->codec) {
  ^
C:/media-autobuild_suite-master/build/gpac-git/src/terminal/media_object.c:1487:2: error: stray '\240' in program
make[1]: *** [../config.mak:140: terminal/media_object.o] Error 1
make[1]: Leaving directory '/build/gpac-git/build-64bit/src'
make: *** [Makefile:9: all] Error 2
make failed. Check C:/media-autobuild_suite-master/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...`

[Log](https://0x0.st/Td2.zip)

EDIT: I just saw @wiiaboo already [posted about this](https://github.com/gpac/gpac/issues/573) on the gpac github.

**Comment by wiiaboo** [comment]
Please don't open another issue for the same thing.

**Comment by moppman** [comment]
I didn't mean to, because I wrongly assumed [this](https://github.com/jb-alvarado/media-autobuild_suite/commit/68629933c0950b53ece770896d4fd41dcb100eba) would have fixed it.

**Comment by wiiaboo** [comment]
You should've replied and/or reopened the original issue then.
I didn't test the fix then, but it should work now.

**Comment by moppman** [comment]
Yep, working now. Thanks.
