### ISSUE TITLE
vpx build problem

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#354]
`Likely error:
     STOREARGB
     ^
../third_party/libyuv/source/row_win.cc:84:32: error: expected primary-expression before ')' token
     _mm_storeu_si128((__m128i *)(dst_argb + 16), xmm1);                        \
                                ^
../third_party/libyuv/source/row_win.cc:120:5: note: in expansion of macro 'STOREARGB'
     STOREARGB
     ^
make[1]: *** [Makefile:160: third_party/libyuv/source/row_win.cc.o] Error 1
make: *** [Makefile:17: .DEFAULT] Error 2`
 
[logs.zip](https://0x0.st/Arr.zip)

**Comment by wiiaboo** [comment]
It's being reverted upstream.
