### ISSUE TITLE
Issue with compiling sendfile/sox 

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#355]
While compiling the script exits with errors relatet to sendfile/sox.
Redownloaded media-autobuild-suite and sendfile/sox sources but still the same since ten days.
Maybe there is some change in attributes or so which causes the script to exit.
Unfortunately these are neccessary for ffmpeg.
Here is the log: https://0x0.st/As0.zip)
and also the one of the ab-suite mentioned in the error text
[sox-ab-suite.make.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/337313/sox-ab-suite.make.log.txt)

**Comment by wiiaboo** [comment]
Try with latest commit.

**Comment by wiiaboo** [comment]
Also, I can't reproduce the issue either before or after the commit, so it could be an issue with your changes.

**Comment by hekitoshinoda** [comment]
Hi RiCON
Sorry, was out for meeting til now.
Just tried it and it works with your latest patched version from this
evening.
Thanks

But what do you mean "with your changes"?
I havn't changed something ...

Anyway it's fixed
Thanks

2016-06-28 19:03 GMT+02:00 RiCON <notifications@github.com>:

**Comment by wiiaboo** [comment]
You were using an older version and there's some changes in CFLAGS and others from looking at the scripts. That was a linking issue so CFLAGS aren't likely to have caused it, so no idea.

**Comment by hekitoshinoda** [comment]
Right I search/replace the CFLAGS for x264/x265 encoder  to fit best my cpu
for speed reasons.
This method is failsafe this way I think and it saves me hours of encoding
time.
Others I don't touch because I have only basic skills with shell scripting.
I don't like to mess up things.

I guessed there were an updater for your scipt introduced not long ago?
If it don't update your script to the latest version then what is this for?
Or is it just not enabled?

Anyway
Thanks for your quick response

2016-06-28 23:07 GMT+02:00 RiCON <notifications@github.com>:

**Comment by wiiaboo** [comment]
>Right I search/replace the CFLAGS for x264/x265 encoder to fit best my cpu for speed reasons.

I also introduced a way to set your own CFLAGS AND LDFLAGS at your request, back in https://github.com/jb-alvarado/media-autobuild_suite/commit/11ca57a4d10f52ca2d01e261031c11b8ea00b80e, why aren't you using that instead?

>I guessed there were an updater for your scipt introduced not long ago? If it don't update your script to the latest version then what is this for? Or is it just not enabled?

It's an option in the .bat that creates a `update_suite.sh` script in the root of the suite that you drag manually to mintty shortcut to update the suite. It's not automatic because it removes any changes the user did (exports them to a .diff).

**Comment by hekitoshinoda** [comment]
Hhmm I wasn't aware of that possibility.
Better than search/replace this stuff everytime the script changes.
Is there any explanation/advise how to use it on your site (or elsewhere)?

Sorry sounds dumb but I have so much workload that I totally forgot about
this way.
Does this look for a file (txt?) with the extra CFLAGS inside?

The first steps with the update I have made so it is in my root only the
drag to mintty info was lost ...
Will try that next time for update.

2016-06-28 23:37 GMT+02:00 RiCON <notifications@github.com>:

**Comment by wiiaboo** [comment]
Just a normal text file called custom_build_options.
Mine:
```
export CFLAGS="-mthreads -march=native -O3 -pipe"
export CXXFLAGS="${CFLAGS}"
```

**Comment by hekitoshinoda** [comment]
Hi
Ok
Made the test - update went fine with the drag method ;-)

Had little glitches with the custom file.
I made one as you advised and put it in the mingw folder - result nothing
I copied it to the /build folder - result nothing
Then I looked at your script and just checked by renaming $HOME to
$LOCALBUILDDIR - this worked
So the custom file is working and your code picks it up proper only the
location trouble is left now.
However the intention is to not change your script.

Question: Where is the $HOME on a mingw  WIN7x64 installation in this case?
Is it just C:\ or the programs Dir or the user Dir?
If I echo $HOME I get "home/user is a directory"
But if I put the file in the user folder there is no use of it.

2016-06-29 0:43 GMT+02:00 RiCON <notifications@github.com>:

**Comment by wiiaboo** [comment]
>Just a normal text file called custom_build_options inside /msys64/home/<your username>/

If the suite is in `C:\ab-suite`, it's `C:\ab-suite\msys64\home\<your username>\custom_build_options`.
You can also get it by opening mintty and executing `cygpath -w $HOME`.

**Comment by hekitoshinoda** [comment]
Ok
Will try that one later and report.
Tanks

2016-06-29 14:28 GMT+02:00 RiCON <notifications@github.com>:

**Comment by hekitoshinoda** [comment]
Ok
Exactly that was the path I was searching for.
Is working now.
Perfect!
Many Thanks

2016-06-29 14:28 GMT+02:00 RiCON <notifications@github.com>:
