### ISSUE TITLE
failed to compile mplayer & mencoder

### ISSUE THREAD

**Issue by anana93** [jb-alvarado/media-autobuild_suite#356]
Here's the log:
https://www.sendspace.com/file/23iy84

**Comment by wiiaboo** [comment]
Nothing can be done until mplayer gets updated. Complain in their bug tracker. mplayer can't be built with FFmpeg releases nor git master and I certainly don't care enough to keep track of what FFmpeg commit it's compatible with.

**Comment by wiiaboo** [comment]
Fixed in https://github.com/jb-alvarado/media-autobuild_suite/commit/2c24349f476a0ed441dd7399b1e0c9ff1e6e7ab5 but don't expected any more fixes from me for this piece of crap.
