### ISSUE TITLE
Suggestion: Add lavf and ffms support for standalone x264

### ISSUE THREAD

**Issue by moppman** [jb-alvarado/media-autobuild_suite#359]

**Comment by moppman** [comment]
Changing the `x2642` flag to `4` in `media-autobuild_suite.ini` still gives me 
`Infile can be raw (in which case resolution is required),
  or YUV4MPEG (*.y4m),
  or Avisynth if compiled with support (yes).
  or libav* formats if compiled with lavf support (yes) or ffms support (no).` for x264.exe

**Comment by wiiaboo** [comment]
Did you force recompilation?

**Comment by moppman** [comment]
Yeah, I deleted x264.pc and x264.exe.

**Comment by moppman** [comment]
Working fine now 😄
