### ISSUE TITLE
decklink v10.7.0

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#360]
Hello.
Please find here the decklink v10.7.0 files: http://www18.zippyshare.com/v/t8t16ZsS/file.html
regards,
laur

**Comment by wiiaboo** [comment]
Including the License in a separate file so I can see if there's any change and running dos2unix on all the files would be helpful too.

**Comment by laurfb** [comment]
Hi again.
Could you check please the hash for DeckLinkAPI_i.c (v10.7.0)?
Line 818 in media-suite_compile.sh?
regards,
laurfb

**Comment by wiiaboo** [comment]
I forgot to also push the updated gh-pages branch.
The DeckLinkAPI_i.c file has no changes from 10.6.6.
