### ISSUE TITLE
please use '--large-address-aware' for 32bit binaries

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#361]
Run into ffmpeg 32bit crashing when using 2GB RAM and normally --large-address-aware should help on windows to let it use more than 2 GB of RAM. :)

**Comment by wiiaboo** [comment]
FFmpeg is already using that.

**Comment by wiiaboo** [comment]
If there's still an issue, it's unlikely the suite's. Post in the respective issue tracker, please.

**Comment by Selur** [comment]
ok, thanks for checking just was confused since media-suite_compile.sh didn't mention it and the crashes always occur on the same position when more than 2GB are used.
-> it's probably something else here thats the problem then :)

**Comment by wiiaboo** [comment]
FFmpeg's configure itself adds the flag, not the suite.
