### ISSUE TITLE
MP4Box Compilation error

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#363]
MP4Box Compilation error
https://0x0.st/mcv.zip

**Comment by wiiaboo** [comment]
You're not using the latest version of the suite.

**Comment by Barough** [comment]
The Suite updates every time i run it so it should be up to date
 
Just ran it again and it say that everything is up to date here

**Comment by wiiaboo** [comment]
I don't see the modification added in https://github.com/jb-alvarado/media-autobuild_suite/commit/5c44f1bf2f0fd78d682b04ea19700053967e9290 in your files though.

**Comment by Barough** [comment]
Beats me what going on then

**Comment by wiiaboo** [comment]
What are you doing to update the suite? Normal `git pull` or just replacing the files?
On the zip the last time the scripts were updated was back in June.

**Comment by wiiaboo** [comment]
If there's a file called `update_suite.sh` in the root of the suite you run it by dragging it to the "mintty" shortcut and that's how to reliably update the suite.

**Comment by Barough** [comment]
I just run the 'media-autobuild_suite.bat' file in my 'media-autobuild_suite' folder

**Comment by Barough** [comment]
Ok, will try that

**Comment by wiiaboo** [comment]
The .bat doesn't update the suite's files. You can't replace or change files being executed.

**Comment by Barough** [comment]
Thnx for the info. 

Maybe the info on how to update the suite files should be posted on the suites main page. I can't find anything about it on the site.
