### ISSUE TITLE
Recommended way to compile local/private ffmpeg changes

### ISSUE THREAD

**Issue by softworkz** [jb-alvarado/media-autobuild_suite#365]
First I'd like to thank you for providing and maintaining this awesome tool for building ffmpeg on Windows! Or more accurate: "building a full-featured version of ffmpeg".

Now I'm doing local changes to the ffmpeg code (in a different folder outside of ab-suite) and I want to compile those changes with ab-suite.

What is the recommended way to use my local changes when compiling with ab-suite? Is there any convenient method?

I know I can make changes to media-suit_compil.sh to do anything I want, but since this file is regularly auto-updated such changes won't last for long...

So what procedure would you suggest for this case?

Thanks again,

softworkz

**Comment by wiiaboo** [comment]
If you're more or less familiar with git, you could add a commit to add your patch and then using `git pull` should auto-merge whichever updates keep coming.

Ex:
Assuming your patch is called "new_feature.patch", place your patch inside `ffmpeg-git` directory and add
```bash
git am "new_feature.patch" am && let _patches+=1
```
after the line
```bash
do_patch "ffmpeg-0002-add-openhevc-intrinsics.patch" am && let _patches+=1
```
in `media-suite_compile.sh` and then open mintty and execute
```bash
git add /trunk/build/media-suite_compile.sh
git commit -m "Adding my new_feature.patch"
```
This adds a commit of your own to the timeline. Then you can simply run mintty and `git pull` to merge upstream changes with your commit and keep up-to-date.


If you're not comfortable doing this, I could add a way to add your FFmpeg patch using `custom_build_options`.

**Comment by softworkz** [comment]
The problem with this is that I have to create a new patch file for each change I'm doing, Then I must copy the file over, modify the .sh file and commit the change. That's quite a task to do each time...

I think I found a better solution: I created a project on github.com and added this project as an additional upstream project for my local ffmpeg clone. Now, when I do a local commit, I push it to github.
The only required change in **media-suite_compile.sh** was to replace the official ffmpeg git url with my "proxy" repository on github.

This works fine so far!

Now the only concern is about updates. My local version of media-suite is already cloned via git, but it seems that the auto-update machanism is still active. Wouldn't this overwrite the **media-suite_compile.sh** file?

**Comment by wiiaboo** [comment]
It's relatively easy for me to create a way to add your own patches.
I'd recommend to create these with `git format-patch` instead of `git diff` since if new files are created they're easier to clean before each build.
You'd create a file called `custom_build_options` inside `/msys64/home/<your username>/` and inside set an array variable containing your patch(es). Ex:

**custom_build_options**
```bash
ffmpeg_patches=(patch1.patch patch2.patch)
```

These then get applied before each build to FFmpeg only. If you want to add new patches, just place them inside ffmpeg-git and change custom_build_options to include them.

That's easiest way I can think of, at least.

**Comment by wiiaboo** [comment]
By the way, the suite never auto-updates itself unless you use the update_suite.sh file. That does reset the files. This file is meant for people not comfortable with using git.

**Comment by softworkz** [comment]
> By the way, the suite never auto-updates itself unless you use the update_suite.sh file. That does reset the files. This file is meant for people not comfortable with using git.

OK, thanks for clarifying!

**Comment by softworkz** [comment]
> That's easiest way I can think of, at least

Creating a patch file, copying this file to another directory and finally modifying a config file - for every single commit? That would be OK for a single situation but it's not an acceptable process for regular development (IMO).

Besides the workaround using a github project as a proxy like I described previously, I could also imagine another approach: If you would extend the **do_vcs** function in **media-suite_helper.sh** to accept local paths as source, then users could simply replace the git url with a local path from where the source files would be copied then.

What do you think?

**Comment by wiiaboo** [comment]
You could also just do something like this, assuming your patched ffmpeg git is inside "/build":
```
git fetch /build/ffmpeg-private-patches
git merge FETCH_HEAD
```
Adding this after the line
```
_patches="$(git rev-list origin/master.. --count)"
```
should count any extra commits fetched from your private repo as patches so you can keep track.
This should be equivalent with your method and you wouldn't even have to keep your patched ffmpeg git up-to-date, it'd just merge any extra commits.

You can also perfectly use do_vcs with local directories, afaik. I've tried just now and it works fine (`do_vcs /build/ffmpeg-git example` gets me an "example-git" folder git cloned from /build/ffmpeg-git).

**Comment by softworkz** [comment]
Now we're talking :-)

Both options seem to be great! I'll try the second one since my private ffmpeg is outside the media-suite directory..

For the second option, does the path have to end with "git"?

**Comment by wiiaboo** [comment]
> Both options seem to be great! I'll try the second one since my private ffmpeg is outside the media-suite directory..

If it's in f.ex `C:\ffmpeg-private-patches` you can get it from `/c/ffmpeg-private-patches`.

> For the second option, does the path have to end with "git"?

No, it was just that example. do_vcs assumes any path that doesn't start with the protocol to be git. If you were trying to do this with x265, you'd need to add "hg::" before the path to make it use mercurial commands.

**Comment by softworkz** [comment]
Excellent! Thanks very much for your assistance and for creating this tool!

**Comment by roeihe** [comment]
hey need some help..
i am using vlc in android studio with ffmpeg in linux i need to modify some code in ffmpeg c file.
when i compile ffmpeg and run vlc app in android it uses the original version of ffmpeg and not the modified .

any suggestion why this occured maybe another way to compile or how to find the source of ffmpeg

*if i delete the file of ffmpeg and compile it restrore the ffmpeg file from somewhere dont know how.

tnx

**Comment by roeihe** [comment]
hey need some help..
i am using vlc in android studio with ffmpeg in linux i need to modify some code in ffmpeg c file.
when i compile ffmpeg and run vlc app in android it uses the original version of ffmpeg and not the modified .

any suggestion why this occured maybe another way to compile or how to find the source of ffmpeg

*if i delete the file of ffmpeg and compile it restrore the ffmpeg file from somewhere dont know how.

tnx
