### ISSUE TITLE
An option to compile current working tree

### ISSUE THREAD

**Issue by shekh** [jb-alvarado/media-autobuild_suite#366]
I have read #365, but it would be nice to completely disable git update.
For instance, I want to compile historic snapshot from specific commit, and also maybe do some local hacking right in build\ffmpeg-git directory.

I sort of accomplished this by adding code:

```
do_vcs_skip() {
    local vcsType="${1%::*}"
    local vcsURL="${1#*::}"
    [[ "$vcsType" = "$vcsURL" ]] && vcsType="git"
    local vcsBranch="${vcsURL#*#}"
    [[ "$vcsBranch" = "$vcsURL" ]] && vcsBranch=""
    local vcsFolder="$2"
    local vcsCheck=("${_check[@]}")
    local deps=("${_deps[@]}") && unset _deps
    local ref
    [[ ! "$vcsFolder" ]] && vcsFolder="${vcsURL##*/}" && vcsFolder="${vcsFolder%.*}"

    echo
    cd_safe "$LOCALBUILDDIR"
    cd_safe "$vcsFolder-$vcsType"

        touch recently_updated
        rm -f build_successful{32,64}bit
        if [[ $build32 = "yes" && $build64 = "yes" ]] && [[ $bits = "64bit" ]]; then
            new_updates="yes"
            new_updates_packages="$new_updates_packages [$vcsFolder]"
        fi
        echo "$vcsFolder" >> "$LOCALBUILDDIR"/newchangelog
        vcs_log
        echo >> "$LOCALBUILDDIR"/newchangelog
        do_print_status "тФМ ${vcsFolder} ${vcsType}" "$orange" "Updates found"

    do_print_status "${vcsFolder} ${vcsType}" "$green" "Skipping update"
    return 0
}
```

and also replace
`    if do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then`
with
`    if do_vcs_skip "https://git.ffmpeg.org/ffmpeg.git"; then`

But honestly I barely understand what is going on, maybe you can come with cleaner solution.

Thanks!

**Comment by wiiaboo** [comment]
> For instance, I want to compile historic snapshot from specific commit, and also maybe do some local hacking right in build\ffmpeg-git directory.

That's way too specific a use to warrant being in the suite, imo. If you need that much hacking you might as well just disable ffmpeg and compile it yourself. Just disable cleaning of the suite at the end and check the command run to configure in the first line of ab-suite.configure.log.

Unless I'm misunderstanding what you want, this is a wontfix.
