### ISSUE TITLE
Suggestion: Get rsync with MinGW

### ISSUE THREAD

**Issue by softworkz** [jb-alvarado/media-autobuild_suite#367]
Hi,

I tried building and using FATE for testing and noticed that when I execute

make fate-rsync

in order to download/refresh the test data I get an error about missing rsync command.

It would be great if the MinGW environment that you are setting up would include the rsync component...

Thanks,

softworkz

**Comment by wiiaboo** [comment]
Why? It's not needed for any build. Just install it yourself.
`pacman -S --asdeps rsync`

**Comment by softworkz** [comment]
Well, It's needed in order to run "make fate". It's not a build but something you would run after a build (when you did some development).

> pacman  -S --asdeps rsync

If I had known this command, it would have been easy :-)
