### ISSUE TITLE
building ffmpeg fails,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#368]
> ┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to gplv3...
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_Z23_txnal_cow_string_c_strPKv+0x1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_Z23_txnal_sso_string_c_strPKv+0x1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_Z20_txnal_cow_string_D1Pv+0x5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_Z20_txnal_cow_string_D1Pv+0x1e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_addUserCommitAction'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorC1EPKc+0x2e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_memcpyRnWt'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_memcpyRnWt'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x36): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
H:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorD0Ev+0x1a): additional relocation overflows omitted from the output
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:131: ffmpeg_g.exe] Error 1
make failed. Check H:/media-autobuild_suite/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

[logs.zip](https://0x0.st/mRq.zip)

**Comment by wiiaboo** [comment]
Try removing --enable-libzimg from ffmpeg_options.txt.
Almost all libs depending on libstdc++ are broken with GCC 6 in 64-bit. In my tests, zimg seemed to work, but maybe not.

**Comment by wiiaboo** [comment]
Try with latest commit, I forgot to actually check for the broken libs in configure options.

**Comment by Selur** [comment]
removed libzimg and it ran through, added it again, updated and it ran through since everything was 'up-to-date' -> will let it run tomorrow again and report back in case it fails then.

**Comment by wiiaboo** [comment]
It should actually remove the broken libs now. While it isn't fixed in MinGW upstream apparently only x265 works, for some reason. Every other stdc++-depending lib is broken when linking with FFmpeg and mpv.

c.f. https://github.com/Alexpux/MINGW-packages/issues/1580
