### ISSUE TITLE
libbluray build error

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#371]
> ┌ libbluray git ........................................ [Updates found]
├ Running autoreconf...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
../src/libbluray/bluray.c:2783:11: error: 'BLURAY {aka struct bluray}' has no member named 'bdjstorage'
         bd->bdjstorage.no_persistent_storage = !value;
           ^~
../src/libbluray/bluray.c: In function '_set_rate':
../src/libbluray/bluray.c:3561:43: warning: unused parameter 'rate' [-Wunused-parameter]
 static int _set_rate(BLURAY *bd, uint32_t rate)
                                           ^~~~
make[1]: *** [Makefile:1497: src/libbluray/bluray.lo] Error 1
make[1]: Leaving directory '/build/libbluray-git/build-32bit'
make: *** [Makefile:918: all] Error 2
make failed. Check H:/media-autobuild_suite/build/libbluray-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.

[logs.zip](https://0x0.st/aOy.zip)

**Comment by wiiaboo** [comment]
Update the suite.
