### ISSUE TITLE
libcurl fails,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#372]
Had to make a clean clone and ended at:
 [logs.zip](https://0x0.st/aWd.zip) 
restarted the build and this time it ended at:
 [logs.zip](https://0x0.st/aWn.zip) 
 restarting again adn edede at:
  [logs.zip](https://0x0.st/aW5.zip
 which seems to be the same spot.

**Comment by Selur** [comment]
just made a pull and still got stuck at libcurl:
libcurl 7.49.1 ......................................... [Not installed]
├ curl-7.49.1 ........................................ [File up-to-date]
├ Running extract...
├ Running configure...
Likely error:
../configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/local32 --disable-shared --enable-static --bindir=/local32/bin-global --with-gnutls --without-ssl --without-nghttp2 hide_conflicting_libs -R
configure: WARNING: you should use --build, --host, --target
configure: error: unrecognized option: `-R'
Try `../configure --help' for more information
configure failed. Check H:/media-autobuild_suite/build/curl-7.49.1/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/a4_.zip
Copy and paste [logs.zip](https://0x0.st/a4_.zip)

**Comment by wiiaboo** [comment]
Typo.
