### ISSUE TITLE
vorbis fails

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#373]
>  vorbis-tools git .................................. [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
├ /local32/bin-audio/oggenc.exe ............................ [Not found]
└ vorbis-tools-git ............................................ [Failed]
 
Try deleting '/build/vorbis-tools-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

Deleting '/build/vorbis-tools-git' and restarting just ends up at the same error,...

**Comment by wiiaboo** [comment]
Where's the logs?

**Comment by Selur** [comment]
Which do you need? The script doesn't offer any by itself

>         Starting 32bit compilation of all tools
Imported FFmpeg options from ffmpeg_options.txt
License: gplv3
Imported mpv options from mpv_options.txt
 
>         Starting 32bit compilation of global tools
> 
  Running git update for libopenjp2...
libopenjp2 git ............................................ [Up-to-date]
freetype2 2.6.4 ........................................... [Up-to-date]
fontconfig 2.12.0 ......................................... [Up-to-date]
harfbuzz 1.3.0 ............................................ [Up-to-date]
fribidi 0.19.7 ............................................ [Up-to-date]
sdl 1.2.15 ................................................ [Up-to-date]
gnutls 3.5.2 .............................................. [Up-to-date]
libcurl 7.49.1 ............................................ [Up-to-date]
> 
  Running git update for libwebp...
libwebp git ............................................... [Up-to-date]
> 
  Running git update for zimg...
zimg git .................................................. [Up-to-date]
> 
        Starting 32bit compilation of audio tools
libilbc 2.0.3-dev ......................................... [Up-to-date]
> 
  Running git update for flac...
flac git .................................................. [Up-to-date]
vo-amrwbenc 0.1.2 ......................................... [Up-to-date]
> 
  Running git update for fdk-aac...
fdk-aac git ............................................... [Up-to-date]
> 
  Running git update for bin-fdk-aac...
bin-fdk-aac git ........................................... [Up-to-date]
> 
  Running git update for vorbis-tools...
┌ vorbis-tools git .................................. [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
├ /local32/bin-audio/oggenc.exe ............................ [Not found]
└ vorbis-tools-git ............................................ [Failed]
> 
Try deleting '/build/vorbis-tools-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

is the only thing I see
