### ISSUE TITLE
Is it possible to build a specific version of ffmpeg?

### ISSUE THREAD

**Issue by filoe** [jb-alvarado/media-autobuild_suite#374]
Is it possible to build a specific version of ffmpeg? Directly from source, from any git commit,...?

**Comment by wiiaboo** [comment]
Yes.

**Comment by filoe** [comment]
Nice ... so how? I would like to build ffmpeg 3.0 (see https://github.com/FFmpeg/FFmpeg/releases/tag/n3.0).
Thanks!

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1119
Add "#tag=n3.0" to the git url, so it's `do_vcs "https://git.ffmpeg.org/ffmpeg.git#tag=n3.0"`.

**Comment by AndreBenoit** [comment]
Is it possible to build my own modified version of ffmpeg in my computer?

**Comment by 1480c1** [comment]
What do you mean? FFmpeg version or different libs?

**Comment by AndreBenoit** [comment]
I made a modification in libavformat for STREAM_TYPE_AUDIO_AC3 and I want to use this modified version. It is possible?

**Comment by 1480c1** [comment]
What kind of modification? Diff/patch? Look at the readme for ffmpeg_extra.sh

**Comment by AndreBenoit** [comment]
in the libavformat /mpegts.h /#define STREAM_TYPE_AUDIO_AC3       0x81 must be 0x332D4341.
So what's the solution of using this libavformat instead of FFmpeg one?

**Comment by 1480c1** [comment]
Do you understand how to use bash and commands like sed?

**Comment by AndreBenoit** [comment]
not yet! :)

**Comment by AndreBenoit** [comment]
what do you propose?

**Comment by 1480c1** [comment]
1. create a file called `ffmpeg_extra.sh` under the build folder: `touch ffmpeg_extra.sh`
2. add executable bit: `chmod +x ffmpeg_extra.sh`
3. edit it with

``` bash
# Runs before running ./configure
_pre_configure(){
    # Replace "#define STREAM_TYPE_AUDIO_AC3       0x81" with "#define STREAM_TYPE_AUDIO_AC3       0x332D4341" in the file libavformat/mpegts.h under $REPO_DIR (ffmpeg-git)
    # No need for "/g" at the end of sed's script since it only appears once
    sed -i 's/#define STREAM_TYPE_AUDIO_AC3       0x81/#define STREAM_TYPE_AUDIO_AC3       0x332D4341/' ${REPO_DIR}/libavformat/mpegts.h
}
```

**Comment by wiiaboo** [comment]
That seems like a change that should be asked of FFmpeg directly. Google shows me a couple of open trac issues about that identifier.

**Comment by AndreBenoit** [comment]
Yes, but it's look like nobody want to do something... Lot of unanswered tickets.

**Comment by wiiaboo** [comment]
[Bump it](https://trac.ffmpeg.org/ticket/2162) with an explanation of why you want to use 0x41432D33/0x332D4341 instead of the standard 0x81 that is determined in AC-3 and H.222 (MPEG-TS) standards. At most, the least broken way to implement this would be a special flag specific for `.m2ts`, since that stream type identifier seems to only appear on those.
