### ISSUE TITLE
lame-3.99.5 compiling error

### ISSUE THREAD

**Issue by hvthinh** [jb-alvarado/media-autobuild_suite#375]
I've ran into issue while compiling libmp3lame.
Here is the link to log.zip `https://0x0.st/a6J.zip`
Is there any way I can build this myself, like the flac from the wiki? Thank you.

> ├ lame-3.99.5 ........................................ [File up-to-date]
> ├ Running extract...
> ├ Running configure...
> Likely error:
> checking size of long... 4
> checking size of unsigned long... 0
> checking size of long long... 8
> checking size of unsigned long long... 0
> checking size of float... 4
> checking size of double... 0
> *** I have a problem determining the size of some variable types. Either
> *** you compiler is broken, or your system+compiler combination is not
> *** supportet by the "autoconf" framework we use to generate this
> *** configure script.

.ini file 
> [compiler list]
> msys2Arch=2
> arch=3
> license2=1
> xpcomp=2
> standalone=2
> vpx2=2
> aom=2
> daala=2
> x2642=1
> x2652=1
> other265=2
> flac=1
> fdkaac=1
> mediainfo=2
> soxB=2
> ffmpegB=1
> ffmpegUpdate=2
> ffmpegChoice=1
> mp4box=2
> rtmpdump=2
> mplayer=2
> mpv=2
> angle=2
> bmx=2
> cores=4
> deleteSource=1
> strip=1
> pack=2
> logging=1
> updateSuite=1

And ffmpeg_option.txt (I removed all the lines start with # character)

> --enable-avisynth --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx
> --enable-libx264 --enable-libx265 
> # Zeranoe
> --disable-w32threads --enable-fontconfig --enable-libmfx
> --enable-libwavpack --enable-libxvid --enable-libzimg
> # Full
> --enable-opengl --enable-libfdk-aac

**Comment by wiiaboo** [comment]
Can't tell what the problem is, but it's not the suite. I can't reproduce it.

```
C:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file conftest.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
```
Try running it again, after updating to the latest commit.

**Comment by hvthinh** [comment]
I ran the update_suite.sh and was able to install libmp3lame successfully. Not sure what went wrong the first time.

Thank you for your help.
