### ISSUE TITLE
"zlib1.dll: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#378]
Hi. Seems that today msys/mingw update broke x265 builds.
regards,
laur
[logs.zip](https://0x0.st/Mwy.zip)

**Comment by wiiaboo** [comment]
That doesn't seem related to x265 itself. Can you run `which zlib1.dll`?

**Comment by wiiaboo** [comment]
Can you try running this to see if it's fixed?:
```bash
# [open mintty]
source /build/media-suite_helper.sh
do_pacman_install lz4
cmake --version
```
It shouldn't complain about missing dlls anymore.

**Comment by laurfb** [comment]
Hi. It's Ok now. Thx!
regards,
laur
