### ISSUE TITLE
compiler could not find wget-pack.exe

### ISSUE THREAD

**Issue by fergoman123** [jb-alvarado/media-autobuild_suite#380]
I was trying to compile the suite and i came up with this error.

![capture](https://cloud.githubusercontent.com/assets/3822061/18025933/9baa48ec-6c7b-11e6-92df-2fd700bdc950.PNG)

My System
Windows 10 Pro 64-bit
Intel Core i5 5200U 2.20GHz

**Comment by wiiaboo** [comment]
No idea. Try running the suite on a smaller path, like `C:\stuff\ab-suite`.
