### ISSUE TITLE
gnutls  configure failed.

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#381]
[logs.zip](https://0x0.st/MkS.zip)

**Comment by wiiaboo** [comment]
No idea.
Btw, any special reason why GnuTLS instead of SChannel? Still XP-compability?

**Comment by Selur** [comment]
yes, xp compatibility is enabled

**Comment by wiiaboo** [comment]
I can reproduce it, at least, but still no idea.
