### ISSUE TITLE
libopenjpg cmake failed

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#382]
[logs.zip](https://0x0.st/MkW.zip)

**Comment by wiiaboo** [comment]
This one should've been fixed already. Try running again. You have an old version of libarchive.

**Comment by Selur** [comment]
I just installed the VM and made a checkout a few hours ago,...
my repository is up-do-date (just ran a git clone to be sure) and still stops with:
[logs.zip](https://0x0.st/Mkk.zip)

**Comment by wiiaboo** [comment]
Can you open mintty and run `pacman -Sy && pacman -Quq`?

**Comment by Selur** [comment]
that gives me:
> :: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date

btw. this is on Win 8.1 32bit

**Comment by wiiaboo** [comment]
`pacman -Q $(pacman -Qqs "mingw.*libarchive")`?

**Comment by Selur** [comment]
> $ pacman -Q $(pacman -Qs "mingw.*libarchive")
mingw-w64-i686-libarchive 3.2.1-1
error: package '3.2.1-1' was not found
error: package 'library' was not found
error: package 'that' was not found
error: package 'can' was not found
error: package 'create' was not found
error: package 'and' was not found
error: package 'read' was not found
error: package 'several' was not found
error: package 'streaming' was not found
error: package 'archive' was not found
error: package 'formats' was not found
error: package '(mingw-w64)' was not found

btw. I only selected 32bit mingw:

> [compiler list]
msys2Arch=1
arch=2
license2=2
xpcomp=1
standalone=1
vpx2=1
aom=1
daala=1
x2642=4
x2652=6
other265=1
flac=1
fdkaac=1
faac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=2
rtmpdump=2
mplayer=1
mpv=2
angle=1
bmx=1
cores=2
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=1


on this system,...

**Comment by wiiaboo** [comment]
If you ever meet someone that works in MinGW IRL, please punch them in the head.
