### ISSUE TITLE
x264 build fail,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#383]
>  x264-git  ................................................... [Updated]
 
>  Running hg clone for x265...
Likely error:
      1 [main] python2 1112 child_info_fork::abort: unable to remap _hashlib.dll to same address as parent (0x2F0000) - try running rebaseall
abort: Resource temporarily unavailable
hg.clone failed. Check C:/Users/Selur/Desktop/MediaBuildSuite/build/ab-suite.hg.clone.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
 
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

no link to a debug log was created,....

**Comment by Selur** [comment]
after restarting the script I got

>  Running git update for x264...
x264 git .................................................. [Up-to-date]

 > Running hg update for x265...
┌ x265 hg .............................................. [Files missing]
├ Building 12-bit lib for multilib...
├ Running cmake...
Likely error:
  configure_file Problem configuring file

> CMake Error: File C:/Users/Selur/Desktop/MediaBuildSuite/build/x265-hg/source/x265.pc.in does not exist.
CMake Error at CMakeLists.txt:565 (configure_file):
  configure_file Problem configuring file

> -- Configuring incomplete, errors occurred!
See also "C:/Users/Selur/Desktop/MediaBuildSuite/build/x265-hg/build-32bit/12bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check C:/Users/Selur/Desktop/MediaBuildSuite/build/x265-hg/build-32bit/12bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

> All relevant logs have been anonymously uploaded to https://0x0.st/MdT.zip
Copy and paste [logs.zip](https://0x0.st/MdT.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by wiiaboo** [comment]
You're running into everything today.

**Comment by Selur** [comment]
I know,... :(

**Comment by wiiaboo** [comment]
Why are you using a 32-bit VM anyway? Msys32 is likely more untested and likely to have extra bugs that Msys64 doesn't.

**Comment by Selur** [comment]
got a 32bit VM I wanted to use to build some 32bit ffmpeg, staying with mingw32 seemed like a good choice,..

**Comment by wiiaboo** [comment]
You know you can build and test both 32 and 64-bit with msys64?

**Comment by Selur** [comment]
I know, but I planned to use different ffmpeg dependencies (no x264, x265) for the 32bit bit build.

just stopped with:
>  Running hg clone for x265...
Likely error:
      1 [main] python2 4024 child_info_fork::abort: address space needed by 'msys-ssl-1.0.0.dll' (0x620000) is already occupied
abort: Resource temporarily unavailable
hg.clone failed. Check C:/Users/Selur/Desktop/MediaBuildSuite/build/ab-suite.hg.clone.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by wiiaboo** [comment]
That looks like a very screwed installation. Wait until I test everything so I can at least know it's not the suite's fault.

**Comment by Selur** [comment]
okay, will wait with running the script on the VM

**Comment by wiiaboo** [comment]
I've succesfully compiled at least the 32-bit part of everything with gplv3 license.
Make sure to update the suite to the latest before trying again. If it still doesn't work, try removing everything and starting from scratch, you can copy media-autobuild_suite.ini and ffmpeg_options.txt to avoid remaking the choices.

If it still doesn't work, it's likely some issue that only affects msys32 and it's out of my hands, so I'd advise getting a 64-bit VM and avoid dealing with buggier msys32.

**Comment by Selur** [comment]
deleted the old checkout, made a clean clone and started the script, will report back whether this helped or not

**Comment by Selur** [comment]
didn't change a thing,..
>Running hg clone for x265...
Likely error:
      1 [main] python2 3064 child_info_fork::abort: address space needed by 'msys-ssl-1.0.0.dll' (0x620000) is already occupied
abort: Resource temporarily unavailable
hg.clone failed. Check C:/Users/Selur/Desktop/media-autobuild_suite/build/ab-suite.hg.clone.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
seems like mingw32 is problematic

**Comment by wiiaboo** [comment]
Can you run autorebase.bat as administrator inside msys32 and try one more time?

**Comment by Selur** [comment]
gave up and deleted the checkout, now started to build the 32bit binaries inside a 64bit VM

**Comment by wiiaboo** [comment]
Good luck, lol.

**Comment by wiiaboo** [comment]
@Selur any news?

**Comment by Selur** [comment]
works with 64bit VM and the default mingw selection (32+64)

**Comment by wiiaboo** [comment]
Then it's some issue specific to msys32.
