### ISSUE TITLE
x265 gmp not found

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#384]
> Running git update for ffmpeg...
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to gplv3...
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
Likely error:
../configure --prefix=/local32 --bindir=/local32/bin-video --pkg-config-flags=--static --enable-avisynth --enable-gmp --                                                                                                  enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --disable-w32threads --enable-fon                                                                                                  tconfig --enable-frei0r --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libfreetype --enabl                                                                                                  e-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libopencore-amrnb --enable-li                                                                                                  bopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enab                                                                                                  le-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enab                                                                                                  le-libxavs --enable-libxvid --enable-libzimg --enable-libsnappy --enable-gpl --enable-nvenc --extra-cflags=-DLIBTWOLAME_                                                                                                  STATIC --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-libs=-lstdc++ --extra-cflags=-DMODPLUG_STATIC --extra-cflags=                                                                                                  -DPTW32_STATIC_LIB --extra-libs=-lpthread --extra-libs=-lwsock32 --enable-version3 --enable-filter=frei0r --disable-debu                                                                                                  g
ERROR: gmp not found

> If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
configure failed. Check H:/media-autobuild_suite/build/ffmpeg-git/build-static-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

> All relevant logs have been anonymously uploaded to https://0x0.st/MdS.zip
Copy and paste [logs.zip](https://0x0.st/MdS.zip) in the GitHub issue.

**Comment by wiiaboo** [comment]
This one has probably been fixed by https://github.com/jb-alvarado/media-autobuild_suite/commit/1f55f27fc992437702ba8ac4d5a558800cbee179.
