### ISSUE TITLE
Beware OpenSSL 1.1 update against Sweet32 vulnerability, may break a lot

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#385]
I just read reports about possible issues when you update to OpenSSL 1.1: Not only are there incompatible API changes breaking compilation, but there may also be incompatibilities which change default values or behaviours and invalidate known usage strategies.

[Example for Debian](https://breakpoint.cc/openssl-1.1-rebuild-2016-08-26/) - more _failed than _success

**Comment by wiiaboo** [comment]
We don't compile or use OpenSSL. Does that affect LibreSSL?

**Comment by LigH-de** [comment]
It may, there seem to be relations between both libraries. At least projects which may alternatively use either library may have to refurbish their logic how to tell them apart. But I am no specialist in this topic, and I only have a [German secondary source](https://blog.fefe.de/?ts=a93f56bb)...

I believe it will be advisable to test tools using secure connections if they still work as expected, after they have been altered to possibly support OpenSSL v1.1+ to avoid the Sweet32 vulnerability.

**Comment by wiiaboo** [comment]
I'm still considered sort of an end user, so other than freezing to a certain version, I don't know what you expect me to do.

**Comment by wiiaboo** [comment]
Anyway, this'll only  be relevant with possibly the next release of libressl.

**Comment by LigH-de** [comment]
It was just meant to be a notification to expect problems in the future, so you may already be aware of a possible reason.

**Comment by pat357** [comment]
Time to test !!
A major update for libressl-v2.5.0 has arrived on their server.
They jumped from 2.4.2 right to 2.5.0, so expect new features/bug fixes (new bugs) !

**Comment by LigH-de** [comment]
And if you are unlucky, more updates are required: [v1.1.0a intruduces remote code executioon](https://www.openssl.org/news/secadv/20160926.txt) ... *facepalm*

**Comment by wiiaboo** [comment]
People are preemptively fixing issues with OpenSSL 1.1, even though we don't use it and LibreSSL 2.5.x doesn't break everything like it, so probably safe to close.
