### ISSUE TITLE
mediainfo didn't find git repository

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#391]
Running git update for mediainfo...
Likely error:
vcs_update
fatal: Not a git repository (or any of the parent directories): .git
fatal: not in a git directory
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/461065/logs.zip)

**Comment by wiiaboo** [comment]
Delete all mediainfo directories.

**Comment by ASopH** [comment]
thx, that's it
