### ISSUE TITLE
ffmpeg   Compile error 

### ISSUE THREAD

**Issue by wljcom** [jb-alvarado/media-autobuild_suite#397]
[ab-suite.make.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/494766/ab-suite.make.zip)

**Comment by wiiaboo** [comment]
I need the rest of the information gather in logs.zip, or I can't help you.

**Comment by wiiaboo** [comment]
Nevermind, I can reproduce. Shared builds of FFmpeg are broken with SDL2.
