### ISSUE TITLE
Build failure with libopenjp2

### ISSUE THREAD

**Issue by cojj90** [jb-alvarado/media-autobuild_suite#399]
Hello,

Build failed today and I keep getting message like below. 
I'm using Windows10 64bit and never had problem with the autobuild thus far.

My apologies if there's nothing wrong with the script :)

Thank you.

```
 Running git clone for libopenjp2...
 Running git update for libopenjp2...
┌ libopenjp2 git .................................... [Recently updated]
├ Running cmake...
├ Running install...
├ /local64/include/openjpeg-2.1/openjpeg.h ................. [Not found]
└ libopenjp2-git .............................................. [Failed]

Try deleting '/build/libopenjp2-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.
```

**Comment by cojj90** [comment]
Additionally, I tried deleting /build/libopenjp2-git and also tried doing a fresh build from a fresh git-pull.

**Comment by cojj90** [comment]
duplicate with https://github.com/jb-alvarado/media-autobuild_suite/issues/398

**Comment by cojj90** [comment]
Sorry, reading carefully again, seems like related but a bit different. Mine fails on build process.

**Comment by wiiaboo** [comment]
If it failed on building surely there's logs.
