### ISSUE TITLE
gpac error after fresh install

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#401]
perhaps not an error of the suite ... I don't know

┌ gpac git .......................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error:
F:/m-a-s/build/gpac-git/src/compositor/texturing_gl.c:1043:40: error: 'nb_frames' undeclared (first use in this function)
  if (txh->raw_memory || nb_views == 1) nb_frames = 1;
                                        ^~~~~~~~~
F:/m-a-s/build/gpac-git/src/compositor/texturing_gl.c: In function 'gf_sc_texture_get_transform':
F:/m-a-s/build/gpac-git/src/compositor/texturing_gl.c:1471:30: error: 'GF_VisualManager {aka struct _visual_manager}' has no member named 'current_view'
   if (txh->compositor->visual->current_view%2 != 0 && !txh->compositor->multiview_mode){
                              ^~
make[1]: *** [../config.mak:140: compositor/texturing_gl.o] Error 1
make[1]: Leaving directory '/build/gpac-git/build-32bit/src'
make: *** [Makefile:9: all] Error 2

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/531083/logs.zip)

**Comment by wiiaboo** [comment]
Tell them, not me. They keep ignoring Travis results so I don't think they care very much if it's broken.

**Comment by ASopH** [comment]
thx for information ..
