### ISSUE TITLE
Avira AntiVirus causes total malfunction

### ISSUE THREAD

**Issue by Patlamgoc** [jb-alvarado/media-autobuild_suite#402]
It seems Avira AntiVirus tampers with EXE and DLL base addresses shamelessly which causes cygwin (so msys2, so whole suite) to malfunction (possibly during forks). Even installation scripts crash randomly at random places with errors like below and leaves a piece of garbage. Disabling antivirus doesn't help either, you need to uninstall Avira completely to restore back everything. Logic says other security products which uses Avira engine (like Qihoo 360) might cause problems also. Curiously, this conflict seems to be very ancient: http://blog.dimajix.de/archives/130-Cygwin-+-Avira-Nogo.html

Obviosuly this is not a fixable issue but I think it worths reporting for possible victims. 
Thank you for an excellent piece of code by the way.

```
/build/media-suite_update.sh: line 166: file: command not found
Updating /local32 profile
      2 [main] head (1480) D:\media-autobuild_suite\msys64\usr\bin\head.exe: *** fatal error - cygheap base mismatch detected - 0x1802FE408/0xF6E408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
/build/media-suite_update.sh: line 166: file: command not found
Updating /local64 profile
```

**Comment by wiiaboo** [comment]
Don't use it, then. What am I supposed to do?

**Comment by Patlamgoc** [comment]
As I mentioned, I know this is not fixable but as almost all review sites recommending Avira as #1 choice for quite a long time, this note might prevent some others tearing their hair for days like me. Thx again.

**Comment by Barough** [comment]
It's simple, tell Avira to totally ignore the media-autobuild_suite folder

**Comment by Patlamgoc** [comment]
Thx but nope, adding to every exclusion, disabling resident trample detection algorithm named 'AHeAD' (which is supposed to detect unknown threats in advance), disabling malicious macro discovery, disabling cloud services don't help. Then I got crazy and tried things like closing every other programs, rebasing DLL's every time with autorebase.bat in msys2 directory before building, even not touching mouse and keyboard to not to cause a some kind of sinister 'memory event' (as Windows 10 is not an XP in terms of memory management) with no success, my box has Windows 10 Pro build 14931 by the way.

As I've mentioned before, disabling the Avira realtime protection completely doesn't help either. I'd like to emphasize that this is not a false positive detection or an access blocking issue, but Avira is tampering with EXE and/or DLL base addresses on the fly for some reason (so possibly forking fails) and I'm afraid this is a structural issue to the core. Suite builts without a glitch with AVG and Panda by the way.

**Comment by Barough** [comment]
Contact Avira about the issue then. They tend to be pretty good to deal with. Have had some head butting with them but it have all come out good it then end.

**Comment by Patlamgoc** [comment]
In a way I did, at least I did write a feedback which briefs the cygwin issue but I'm not sure if they would concern few crackpots who try to run ported code which expects *nix memory management on a Windoze :) I'm sure more serious cygwinners may report more eligible issues than me, I'm just a hobbyist.

**Comment by wiiaboo** [comment]
You can also make an issue in https://github.com/Alexpux/MSYS2-packages and/or https://github.com/Alexpux/MINGW-packages.

**Comment by Patlamgoc** [comment]
Aha thx, I discovered many other cygheap issues there :) I'll try to contribute.

**Comment by Patlamgoc** [comment]
Ok, it seems Windows 10 x64 build 14931 had been the real culprit and Avira just caused the problem to manifest, because after upgrading to build 14946, I had no problems so far even without excluding the suite directory from realtime protection, so changing the issue title for sanity.
