### ISSUE TITLE
Need new patch for dynamic loading CUDA/cuvid for ffmpeg

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#407]
The current patch online  **ffmpeg-dyncuda.patch** stopped working .
The error is  **Patch couldn't be applied with 'git am'. Continuing without patching.**

Thx,
Pat357

**Comment by sftt** [comment]
Detail Logs:
> @ /trunk/build/ffmpeg-git
> $ git reset --hard origin/HEAD
> HEAD is now at 75a1311 avformat/mux: remove unnecessary autobsf hack
>
> $ git am --ignore-whitespace ffmpeg-dyncuda.patch
> Applying: compat/cuda: add dynamic loader
> .git/rebase-apply/patch:1518: new blank line at EOF.
> +
> warning: 1 line adds whitespace errors.
> Applying: avutil/hwcontext_cuda: use dynamically loaded CUDA
> error: patch failed: configure:5414
> error: configure: patch does not apply
> .git/rebase-apply/patch:339: new blank line at EOF.
> +
> **Patch failed at 0002** avutil/hwcontext_cuda: use dynamically loaded CUDA
> The copy of the patch that failed is found in: .git/rebase-apply/patch
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> 
> $ git am --abort

same error on ffmpeg tags/n3.1.4 & n3.1.5
and on `#tag=n3.2`:
> $ git reset --hard n3.2
> HEAD is now at ebf8ec5 avisynth: fix Planar RGB output
> 
> $ git am --ignore-whitespace ffmpeg-dyncuda.patch
> Applying: compat/cuda: add dynamic loader
> .git/rebase-apply/patch:1518: new blank line at EOF.
> +
> warning: 1 line adds whitespace errors.
> Applying: avutil/hwcontext_cuda: use dynamically loaded CUDA
> .git/rebase-apply/patch:339: new blank line at EOF.
> +
> warning: 1 line adds whitespace errors.
> Applying: avcodec/cuvid: use dynamically loaded CUDA/CUVID
> Applying: avfilter/vf_scale_npp: use dynamically loaded CUDA
> Applying: avcodec/nvenc: use dynamically loaded CUDA
> error: patch failed: configure:2694
> error: configure: patch does not apply
> **Patch failed at 0005** avcodec/nvenc: use dynamically loaded CUDA
> The copy of the patch that failed is found in: .git/rebase-apply/patch
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".

**Comment by sftt** [comment]
@wiiaboo master branch changes very fast, 
thus patch on one commit outdates so quick.

provide patches for stable release is better,
or mark down the commit id on which the patch is made.


@pat357 Here's a temp fix https://github.com/sftt/media-autobuild_suite/commit/cedee94958950be4216356498ec41c3be07593a5

**Comment by wiiaboo** [comment]
That makes no sense. Master has features and code that the releases are missing. It'd be even more pointless to try to fix patches to work for arbitrary releases.
