### ISSUE TITLE
small issue with commit #8232bd0 (mpv: use waf install)

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#409]
```
+            mv -f $LOCALDESTDIR/{bin-video,lib}/pkgconfig
```
This creates an extra directory pkgconfig inside the directory /lib/pkgconfig, so we end up with
/localxx/lib/pkgconfig/pkgconfig/mpv.pc.
Also mpv.pc contains a bad **libdir** inside.

fix is to replace the line by this:
```
mv -f $LOCALDESTDIR/{bin-video,lib}/pkgconfig/mpv.pc
rmdir $LOCALDESTDIR/bin-video/pkgconfig
sed -ri 's;^(libdir=/[^/]+/)bin.*;\1lib;' "$LOCALDESTDIR"/lib/pkgconfig/mpv.pc
```

**Comment by wiiaboo** [comment]
Please do a pull request.
