### ISSUE TITLE
latest Media Auto Build Suite just closes

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#410]
MediaSuiteAutoBuild log -> Error:
/build/media-suite_compile.sh: line 374: syntax error near unexpected token `fi'
/build/media-suite_compile.sh: line 374: `fi'

seems like a missing ";" before "then" in line 369

After adding it it runs through.

**Comment by hekitoshinoda** [comment]
thx

Maybe while you are at it, just for cosmetics ...

Just seen in compile.sh line 358 - the link formatting is different there,
just *link* instead of *"link"* as usual used in you script.
However it makes no trouble (now).

2016-11-15 13:05 GMT+01:00 RiCON <notifications@github.com>:

**Comment by wiiaboo** [comment]
Unless they have variables, wildcards or spaces, it doesn't matter if they're in quotes or not. Since they're always full URLs the quotes aren't needed at all.
