### ISSUE TITLE
tesseract build error

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#413]
Running git update for tesseract...
┌ tesseract git ..................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
../../arch/dotproductavx.cpp:93:55: error: '_mm256_extract_epi64' was not declared in this scope
       _mm256_extract_epi64(_mm256_castpd_si256(sum), 0);
                                                       ^
make[3]: *** [Makefile:542: libtesseract_avx_la-dotproductavx.lo] Error 1
make[3]: Leaving directory '/build/tesseract-git/build-32bit/arch'
make[2]: *** [Makefile:589: all-recursive] Error 1
make[2]: Leaving directory '/build/tesseract-git/build-32bit/arch'
make[1]: *** [Makefile:484: all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-32bit'
make: *** [Makefile:393: all] Error 2
make failed. Check D:/media-autobuild_suite-master/build/tesseract-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.

[logs.zip]
https://0x0.st/_4u.zip

**Comment by wiiaboo** [comment]
Great, I was thinking of using mingw tesseract instead, I guess that's the straw.
