### ISSUE TITLE
libmediainfo fails

### ISSUE THREAD

**Issue by wljcom** [jb-alvarado/media-autobuild_suite#414]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/608022/logs.zip)
libzen git ................................................ [Up-to-date]

  Running git update for libmediainfo...
┌ libmediainfo git .................................. [Recently updated]
├ Running cmake...
Likely error:

  but not all the files it references.

Call Stack (most recent call first):
  E:/opensource/media-autobuild_suite/local64/lib/cmake/zenlib/ZenLibConfig.cmake:28 (include)
  CMakeLists.txt:37 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by wiiaboo** [comment]
Delete "libzen-git"  inside "build" and try again.

**Comment by wiiaboo** [comment]
Can't reproduce, probably caused by the previous failed builds.
