### ISSUE TITLE
Disable check for git head

### ISSUE THREAD

**Issue by 2mmi** [jb-alvarado/media-autobuild_suite#415]
Hi

Is it somhehow possible to disable the check for the default head at git ?
If i made any change to a souce file, it will be update to the default from git.
 - Can i turn this feature off ?

**Comment by wiiaboo** [comment]
Explain better. What check?

**Comment by 2mmi** [comment]
Okay lets say if i made some modification in a file in a ffmpeg source file (like the mxfenc.c)
Then if i run, the media-autobuild_suite, it will be set back to the git default. And my changes are gone.
Does that make sense ? :-)
I just want to have no check.

**Comment by wiiaboo** [comment]
Use patches, diffs and apply them using ffmpeg_extra.sh which is run [after the git checkout and before configure](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1112).
The suite is not made to support random changes in the build folders. That would break a lot more than is worth my free time.
