### ISSUE TITLE
your commit #34e8ca5 : small bug

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#419]
```
+    if [[ $bits = 64bit ]] && ! mpv_disabled egl-angle && mpv_enabled egl-angle-lib &&
         do_vcs "https://chromium.googlesource.com/angle/angle" angleproject; then
         code
         code
 +    elif ! mpv_disabled egl-angle && mpv_enabled egl-angle-lib; then
+        echo -e "${green}angle in 32-bits with GCC 6 doesn't work."
+        mpv_disable egl-angle-lib
     fi      
```
If there is no update from git, the if will never be true and the code will jump to the elif, were it will disable egl-angle-lib. This also happens when $bits = 64bit !!

fix
add [[ $bits = 32bit ]]  to the elif  or 

or

make the if without the vcs and use a new if for the vcs.
if [[ $bits = 64bit ]] && ! mpv_disabled egl-angle && mpv_enabled egl-angle-lib ; then
   if  do_vcs "https://chromium.googlesource.com/angle/angle" angleproject; then

**Comment by wiiaboo** [comment]
Make a PR.

**Comment by wiiaboo** [comment]
If you have a fix ready stop making issues and do a pull request instead.

**Comment by wiiaboo** [comment]
http://lmgtfy.com/?q=pull+request+github
