### ISSUE TITLE
MPV linking problem still present

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#420]
The changes related to -lmingwex in x265.pc   didn't solve the problem for me....

Do you have any idea where the below mentioned path =C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/dllmain.c:10: comes from ?

I have no such directory on my C drive...

[468/470] Linking build/mpv.com
[469/470] Linking build/mpv-1.dll
[470/470] Linking build/mpv.exe
K:/Mingw644/local64/lib/libGLESv2.a(global_state.o):(.text+0x1e0): multiple definition of `DllMain'
K:/Mingw644/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libmingwex.a(lib64_libmingwex_a-dllmain.o):C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/dllmain.c:10: first defined here
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed (exit status 1):

**Comment by wiiaboo** [comment]
Why open a duplicate?
