### ISSUE TITLE
error, after a fresh install too

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#425]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/621338/logs.zip)

  Running git update for libzen...
┌ libzen git ........................................ [Recently updated]
├ Running cmake...
Likely error:
cmake ../Project/CMake -G Ninja -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX=/local32 -DUNIX=on -DCMAKE_BUILD_TYPE=Release
F:/m-a-s/msys64/mingw32/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
cmake failed. Check F:/m-a-s/build/libzen-git/build-32bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/LK-.zip
Copy and paste [logs.zip](https://0x0.st/LK-.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
That looks more like cmake is broken again. libzen hasn't had a commit for a month.

**Comment by wiiaboo** [comment]
Yeah, it's a broken cmake. From what I can tell, it's been fixed in their repo, so it should work in a few hours at most, when there's another update to libarchive.

**Comment by wiiaboo** [comment]
While it's not fixed, run mintty and
```bash
$ source /build/media-suite_helper.sh
$ do_pacman_install libxml2
```
That should fix cmake meanwhile.

**Comment by ASopH** [comment]
thx, good work :-)
