### ISSUE TITLE
Building x264 and libmfx shared components

### ISSUE THREAD

**Issue by jules43** [jb-alvarado/media-autobuild_suite#428]
I hope this is the appropriate place to post this question.

I am using the media-autobuild_suite to create 64 bit shared libraries to use in a standalone app built with Visual Studio 2015 (on Windows 10 with latest version of autobuild script).

With x264 and libmfx (QuickSync) enabled (in it successfully builds/copies av*.lib, av*.dll and the relevant headers to the local64/bin-video/ffmpegSHARED directory.

Unfortunately I can't build with this as the x264 dll, lib and headers and the corresponding libmfx dll, lib and headers are not created.

Is there a way to get the media-autobuild_suite to build these components and put them in the correct place? If not, could it be modified to do so?

Alternatively, is there a way to use the environment setup by the autobuild script to create these elements.

I ran the minty shortcut in the root directory and then typed:

`cd build/x264-git`
`./configure --host="$MINGW_CHOST" --disable-cli --disable-asm --enable-shared --enable-pic --prefix=/local64/bin-video/ffmpegSHARED`
`make`
`make install`

And this created:
    bin/libx264-148.dll
    lib/libx264.dll.a
    include/x264.h
    include/x264_config.h
    lib/pkgconfig/x264.pc

But I don't end up with lib/libx264.lib.

So I tried to get it to generate a .def file by adding --extra-ldflags="-Wl,--output-def=libx264.def" to the configure command. This creates libx264.def in the x264-git directory, but I can't figure out how to create the .lib from that.

I'm also uncertain how one would modify the master script to add this to it.

Also, doing this seems to cause problems if I then re-run the normal build batch file.

With libmfx, the files generated are libmfx.a, libmfx,la and libmfx.pc. I'm assuming I need libmfx.lib and libmfx.dll (and possibly libmfxsw64.dll as a binary from somewhere).

I tried opening the libmfx.sln in VS2015 (converts project) and then tweaking the include directory to include $(ProjectDir) but this SLN does not build the DLL either.

I'm wondering if I should be using dlltool.exe which is in mingw64/bin, but I've not figured out how to use it.

It seems possible I should use MSVC's lib.exe but it's not on the path and even if I launch msys2_shell from the VS command prompt it disappears from path.

lib.exe /def:libx264.def /OUT:libx264.lib

Any suggestions, help would be  much appreciated.

Thanks

Jules

**Comment by wiiaboo** [comment]
Sorry, I don't have time to answer this question. x264 is easy to compile with msvc. No idea on mfx. Use Google.
