### ISSUE TITLE
Why a separate Win64 NUMA build for x265?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#430]
Both generated EXE files appear to have the same size. So I scanned the shell scripts and found no place where a different set of compilation options is prepared. Furthermore, the CMake script remarks that binding libnuma is exclusively for Linux. Somehow I doubt that building x265 separately with and without NUMA support is a valid option for the Windows target at all; a Win64 EXE should support multi-socket boards automatically.

**Comment by wiiaboo** [comment]
I don't know, the only thing it does is build with winxp support off. If you're telling me they're exactly the same other than targeting maybe a different SDK, what's the point of winxp support being off by default?

**Comment by LigH-de** [comment]
At least with Win64 target, both EXE files are _almost_ binary identical. The only difference may be for Win32 builds, but mainly in the disabled XP support (NUMA support or not would be merely a side effect, and I see little reason to have a multi-socket system with 32-bit only CPUs).

So at least for the Win64 branch, there is no need to run the compilation twice. And regarding x265, Win32 support in general may be debatable, as the limitations by this architecture are already a pain (FullHD resolutions are already a challenge due to the RAM demand, and support for vector math SIMD extensions developed remarkably only in the 64-bit CPU era).

If anyone really really needs a Win32 build, then most probably because there is still XP running. Thus it may need rather compatibility than multi-socket support. My recommendation would therefore be: Either Win32 with XP or Win64 with NUMA.

**Comment by wiiaboo** [comment]
Don't forget there's still _special_ people with 64-bit XP.

**Comment by wiiaboo** [comment]
Anyway, the extra numa build isn't in the first options and isn't recommended, it's only there for whoever really has time to waste building both winxp-compatible and non-winxp compatible multilibs of x265. Unless they remove the winxp option or it breaks something, there's really no reason to remove the option from the suite. I certainly don't use it.
