### ISSUE TITLE
Abort while compiling FFmpeg with 64 Bit

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#432]
Hello guys,
I stumbled upon this great project on GitHub and was psyched that I can build my own FFmpeg with this. First and foremost: Thank you for this script!
Poorly: Something went wrong while compiling FFmpeg just now. I tried it a few times, always the same issue.
Can you have a look at the logs and tell me what went wrong?
[logs.zip] (https://0x0.st/96Y.zip)

Thank you!

Merry Christmas and happy Holidays!

**Comment by BlackScreen** [comment]
I updated the suite, but the build still does not work. :(
[logs.zip] (https://0x0.st/9IS.zip)

**Comment by wiiaboo** [comment]
You need to delete libgme.pc from /local64/lib/pkgconfig to force a rebuild of the lib. Or the libgme-git directory in /build.

**Comment by BlackScreen** [comment]
@wiiaboo: Thank you for the tip. Now I could build FFmpeg without a problem.
The suite did not run through without problems though. It stopped on building the anglelib.
[logs.zip] (https://0x0.st/9I6.zip)
