### ISSUE TITLE
wget.js doesn't support TLS

### ISSUE THREAD

**Issue by mirh** [jb-alvarado/media-autobuild_suite#434]
`wget.js(3, 42) WinHttp.WinHttpRequest: The connection with the server was terminated abnormally`

When I change wget download URL to plain *http* everything works. 
An alternative might be BITSAdmin (as explained in the stackoverflow post below the one we are linking to) or [this](https://gist.github.com/duncansmart/5821523) random script I found. 

My greatest congratulations for your script then.

**Comment by wiiaboo** [comment]
Works fine in Win10. Are you running this on WinXP or something?

**Comment by mirh** [comment]
Windows 7 64 bit.

**Comment by wiiaboo** [comment]
Do you have IE11 installed?

**Comment by mirh** [comment]
Sure, with all updates up to November.

**Comment by wiiaboo** [comment]
Downloading it through IE directly works, I assume?

**Comment by mirh** [comment]
Correct.

**Comment by wiiaboo** [comment]
Fixed it in the server.

**Comment by mirh** [comment]
It now works indeed. 
Thanks.
