### ISSUE TITLE
Ask for "bug report" uploads

### ISSUE THREAD

**Issue by mirh** [jb-alvarado/media-autobuild_suite#435]
I mean, privacy and bla bla bla concerns aside, it's just I find it pointless when the only problem in sight is me hazardously tinkering with the scripts.

**Comment by wiiaboo** [comment]
What?

**Comment by wiiaboo** [comment]
If you mean the upload of the logs, there's no privacy concern. Only you know the link until you give it to someone else.

**Comment by wiiaboo** [comment]
Just comment [this line](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_helper.sh#L949) and it won't upload anything.

**Comment by mirh** [comment]
Mhh.. 
Seems it does it, but I still think a question should be there (and **not** for privacy concerns, but because IM, the script is so perfect by now that the only people possibly going to see that are those in my same hackish self-inflicted situation)

**Comment by wiiaboo** [comment]
I'm reverting it if issues start popping up with the zip, though.
