### ISSUE TITLE
Cut down useless .git history

### ISSUE THREAD

**Issue by mirh** [jb-alvarado/media-autobuild_suite#437]
We don't need git history to compile code. Thus we could use ([credits](http://stackoverflow.com/questions/19352894/how-to-git-fetch-efficiently-from-a-shallow-clone)):
`git clone --branch master --depth 1 --single-branch git://github.com/FFmpeg/FFmpeg.git`
In this example I saved 100MB. 

Git archive would be even better than (afaiu no .git folder at all), but github doesn't support it. And for as much there are plenty of [workarounds](http://stackoverflow.com/questions/160608/do-a-git-export-like-svn-export) (from using svn to curl), I know you are for simplicity 😃

**Comment by wiiaboo** [comment]
We do. Most configure scripts need full history to generate a proper version.
100MB is peanuts compared to trouble arising from screwed versions and git pulls taking forever. There are only a couple repos that take that much space anyway.
And nothing supports git archives.

Overall, no.

**Comment by mirh** [comment]
Just noticed there's even a *unshallow* check.. 
Ok

**Comment by wiiaboo** [comment]
That's because the suite used shallow clones before and it was a pain.
