### ISSUE TITLE
Build FFmbc with suite?

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#441]
Hello,
would it be possible to include FFmbc in the suite?
It is very difficult to find builds of FFmbc, so I would like to build them myself.
Git-source: https://github.com/bcoudurier/FFmbc

Thanks for your answer! :)

**Comment by wiiaboo** [comment]
Unless you give good reasons why, not just that it's difficult to find, no.

**Comment by BlackScreen** [comment]
It can do some things that FFmpeg can not do.
For example FFmbc is better suited for professional use with easier supporting formats like XDCAM HD422, DNxHD, ProRes and so on. These files can then be easily imported into Final Cut, Media Composer or Premiere.
I tried doing so with FFmpeg but failed to do so. FFmbc was the easier and better way.
Since your suite is really great, I thought and addition of FFmbc would make it even better. :)

**Comment by wiiaboo** [comment]
I'll try building it again, but I still don't see any fix for GCC >5.2, so it's unlikely.

**Comment by wiiaboo** [comment]
Yep, still broken.

**Comment by BlackScreen** [comment]
Ok, I understand. Thanks for checking. :)

**Comment by wiiaboo** [comment]
@BlackScreen readded FFmbc, try it.

**Comment by BlackScreen** [comment]
That is great news. Thanks!
I have tried the new version of the suite - it stops currently at the distclean of ffmpeg git.
I have tried building with a clean install and a few times - no success. [logs.zip] (https://0x0.st/JmF.zip)
I rewinded to the version after all commits from Feb 22, 2017. This one seems to work (running as I write, but it got further than the current version), but I could not test the FFmbc building...
Can you please have a look at that?

**Comment by wiiaboo** [comment]
It was just a typo in the latest commit. Go ahead.

**Comment by BlackScreen** [comment]
Updated the suite, tried a new run - success. Thanks! 👍
