### ISSUE TITLE
VP10 support option

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#442]
would be nice to have an option to compile vp10, not totally sure if it's stable again to use, but to build some testing builds and test VP10 it would help to have an option to enable it.

**Comment by wiiaboo** [comment]
Isn't AV1 basically VP10?

**Comment by wiiaboo** [comment]
Also, not sure where vp10 is. libvpx's configure only lists vp8/vp9.

**Comment by wiiaboo** [comment]
Just enable aom, it's been there since a few months ago.

**Comment by Selur** [comment]
Is  there a way to build ffmpeg with libaom ? encoding av1 with aomenc is fine, but being able to decode using e.g. ffplay would also be nice.

**Comment by wiiaboo** [comment]
No.

**Comment by Selur** [comment]
Thanks for the info thought the bitstream was already frozen. :)

**Comment by wiiaboo** [comment]
You're welcome to try http://tmod.nmm-hd.org/LAVFilters/patches/ ffmpeg-lavf-0003 to 0005 patches to see if it works.

Create a file called `ffmpeg_extra.sh` inside ffmpeg-git with:
```bash
git am ffmpeg-lavf-0003-av1-Add-codec_id-and-basic-demuxing-support.diff &&
git am ffmpeg-lavf-0004-av1-Add-libaom-decoding-support.diff &&
git am ffmpeg-lavf-0005-configure-don-t-use-pkgconfig-for-libaom-HACK.diff || git am --abort
```
after downloading the patches.

**Comment by Selur** [comment]
thanks :)
