### ISSUE TITLE
git.update failed. Check C:/autobuild/build/angleproject-git/ab-suite.git.update

### ISSUE THREAD

**Issue by riordans** [jb-alvarado/media-autobuild_suite#444]
[logs.zip](https://0x0.st/fj5.zip) 
  Running git update for angleproject...
Likely error:
vcs_update
fatal: Not a git repository (or any of the parent directories): .git
fatal: not in a git directory
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
git.update failed. Check C:/autobuild/build/angleproject-git/ab-suite.git.update.log
This is required for other packages, so this script will exit.
Press anything to pack a zip with relevant logs and upload it automatically
or Ctrl+C/close the window to exit immediately.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/fj5.zip
Copy and paste [logs.zip](https://0x0.st/fj5.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Try deleting angleproject-git just in case, update the suite and try again.

**Comment by wiiaboo** [comment]
I'll just assume it's fixed.
