### ISSUE TITLE
How to enable support for Intel Quick Sync?

### ISSUE THREAD

**Issue by dakser** [jb-alvarado/media-autobuild_suite#445]
Hi, I'm using this tool and is excelent but it could be great to know how to enable support for Intel Quick Sync? Any help is appreciated.

**Comment by wiiaboo** [comment]
Add `--enable-libmfx` to ffmpeg_options.txt or choose Zeranoe-emulating build. See https://github.com/jb-alvarado/media-autobuild_suite/wiki/ffmpeg_options.txt#external-libraries-needed-for-basic-support-of-formats-decoding and https://trac.ffmpeg.org/wiki/HWAccelIntro#IntelQSV.
