### ISSUE TITLE
Angle Lib broke the building of the suite

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#446]
Hello,
since the last git update I can not build all files anymore.
It seems to be related to the Angle Lib...
[logs.zip] (https://0x0.st/f_T.zip)

Thanks for fixing! :)

**Comment by wiiaboo** [comment]
I was in the middle of updating something, should be fixed now.

**Comment by BlackScreen** [comment]
Confiremd. Works again. Thanks!
