### ISSUE TITLE
Delayload option?

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#447]
Hi.
It's complicated to add DELAYLOAD option to media-autobuild_script so ffmpeg can dynamical load specific libraries only if needed? For CUDA/OpenGL for example?
regards,
laur

**Comment by wiiaboo** [comment]
That's not a suite issue.
Unless you're using --enable-libnpp there's no hard dependency on cuda. It's dynamically loaded as needed, afaik. Same with OpenGL.

**Comment by wiiaboo** [comment]
It can be done for OpenCL, probably, but the others no. Ask in FFmpeg issue tracker.
