### ISSUE TITLE
strange problem when building mplayer,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#449]
` mplayer svn .......................................... [Updates found]
├ Running distclean...
fatal: 'C:/Program Files (x86)/Git/build/ffmpeg-git' does not appear to be a git repository
fatal: Could not read from remote repository.
`
seems like for some reason the script gets paths mixed up,....
(script is installed under H:\media-autobuild_suite )

**Comment by wiiaboo** [comment]
Try deleting the whole mplayer-svn dir and running again.

**Comment by Selur** [comment]
will do. thanks.

**Comment by Selur** [comment]
that seems to help :D

**Comment by wiiaboo** [comment]
Mplayer is overall an unmaintained waste of time. They themselves recommend mpv over it.
