### ISSUE TITLE
Abort of building with mpv

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#450]
Since today, after updating the suite, the building is broken and aborts at building mpv.
I tried deleting the mpv folder already, but that did not fix it.
Here are the logs: [logs.zip] (https://0x0.st/Ozz.zip)

**Comment by wiiaboo** [comment]
You need to recompile FFmpeg to use the newer chromaprint. If there hasn't been any updates, remove ffmpeg.exe to force a recompilation.

**Comment by BlackScreen** [comment]
Yes, that solved the issue. Thanks and sorry for complaining! :)
