### ISSUE TITLE
Cmake error on libzen

### ISSUE THREAD

**Issue by mtrandl** [jb-alvarado/media-autobuild_suite#456]
Here is the output.

`Running git update for libzen...
libzen git ........................................ [Recently updated]
Running cmake...
Likely error:
cmake ../Project/CMake -G Ninja -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX=/local64 -DUNIX=on -DCMAKE_BUILD_TYPE=Release
cmake failed. Check Z:/temp/media-autobuild_suite-master/build/libzen-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
Press anything to pack a zip with relevant logs and upload it automatically
or Ctrl+C/close the window to exit immediately.`

**Comment by wiiaboo** [comment]
Thanks for pressing anything.

**Comment by wiiaboo** [comment]
Unless you send me something, I can't reproduce your problem.

**Comment by mtrandl** [comment]
ok oops. pressed..

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/736694/logs.zip)

**Comment by wiiaboo** [comment]
Yeah, still no idea. Try removing libzen-git.
