### ISSUE TITLE
Error with libsnd even after a fresh installation

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#460]
lame 3.99.5 ............................................... [Up-to-date]
  Running git update for sndfile...
┌ sndfile git ....................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
make[1]: Entering directory '/build/sndfile-git/build-32bit/examples'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/build/sndfile-git/build-32bit/examples'
Making all in tests
make[1]: Entering directory '/build/sndfile-git/build-32bit/tests'
autogen --writable ../../tests/utils.def
fserr 2: cannot map data file utils.tpl:  No such file or directory
make[1]: *** [Makefile:1216: utils.h] Error 2
make[1]: Leaving directory '/build/sndfile-git/build-32bit/tests'
make: *** [Makefile:526: all-recursive] Error 1
make failed. Check F:/m-a-s/build/sndfile-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
Press anything to pack a zip with relevant logs and upload it automatically
or Ctrl+C/close the window to exit immediately.

.. and i can't upload logs.zip. It says: We don’t support that file type. Try again with a PNG, GIF, JPG, DO

**Comment by wiiaboo** [comment]
There's any other uploading site too. And it automatically should've uploaded if you just pressed any key combination other that Alt+F4 or Ctrl+C.

**Comment by wiiaboo** [comment]
But did you make sure to use the latest version of the suite. That's been fixed twice already.

**Comment by ASopH** [comment]
yes, run updater every start from suite.. yesterday erased the hole dir and started new again. I download the archive and start a new try ..

**Comment by ASopH** [comment]
sndfile passed.. there was a error in my copy of m-a-s. Many thanks for the effort and the good work :-)
