### ISSUE TITLE
Large pacman cache: must it persist?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#461]
I don't know whether it is usual or due to interrupting the normal execution; but I just discovered that my installation uses already 10.7 GB, and 2.8 GB alone in msys64/var/cache/pacman/pkg with many tar.xz files I would assume to deserve a clean-up. Is it safe to do so? May there be a pacman command to do that as intended?

I guess I should do a `pacman -Sc` or `paccache -r[k 1]`, according to this ArchWiki article: [pacman – Cleaning the package cache](https://wiki.archlinux.org/index.php/pacman#Cleaning_the_package_cache).

If this is convenient, you may like to add it to the end of the self-updating script. With or without a manual confirmation or setup option (clean package cache after update)...

**Comment by wiiaboo** [comment]
You can run `pacman -Sc`, sure. We don't install anything too big (like qt) so it's not a huge part of the space requirement to warrant doing it in every run.
