### ISSUE TITLE
script.exe.stackdump appears in build directory

### ISSUE THREAD

**Issue by jules43** [jb-alvarado/media-autobuild_suite#464]
When I ran the script yesterday, I was seeing errors indicating that avdevice.dll was missing. I decided to allow some time to pass and retried today.

When I run the build a script.exe.stackdump file appears in the build directory (see attached).
[script.exe.stackdump.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/757324/script.exe.stackdump.txt)

The build now seems to complete correctly but this stackdump file is appearing.

**Comment by wiiaboo** [comment]
That's a msys issue, not the suites.

**Comment by wiiaboo** [comment]
C.f. https://github.com/Alexpux/MSYS2-packages/issues/793

**Comment by wiiaboo** [comment]
Fixed in MSYS with latest version of msys2-runtime.
