### ISSUE TITLE
Debug Symbols / pdbs?

### ISSUE THREAD

**Issue by jules43** [jb-alvarado/media-autobuild_suite#465]
Is there any way to get the script to generate symbols / pdbs for debugging?

Is there any way to cause it to do a debug rather than release build?

I am building the 64 bit shared dlls/libs. Everything is working well and I'd like to be able step into code when debugging.

Any pointers would be appreciated. Apologies if not appropriate place for this question.

Thanks

Jules

**Comment by wiiaboo** [comment]
Add --enable-debug to ffmpeg_options.txt. It's enabled by default but the suite adds --disable-debug.

**Comment by wiiaboo** [comment]
It'll create a separate .debug file that contains the debug symbols to be used with gdb. It's unrelated to VS's pdb. If you need to debug with VS, you also need to build FFmpeg with VS.

**Comment by wiiaboo** [comment]
This might also be incorrect, but I don't know enough about debugging to answer that, ask in #ffmpeg in Freenode IRC for more appropriate help.
