### ISSUE TITLE
build/script.exe.stackdump persists, cause unknown

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#466]
I keep getting a stackdump file of msys64\usr\bin\script.exe quite at the beginning of an autoupdate+build session. Unfortunately I could not yet discover the reason. It seems not to be harmful. Yet, being a bit pedantic, I guess it may be useful to discover the reason to avoid it. Can you give me recommendations how to help you regarding this matter?

[script.exe.stackdump.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/763860/script.exe.stackdump.zip)

**Comment by wiiaboo** [comment]
Again, don't open duplicate issues: https://github.com/jb-alvarado/media-autobuild_suite/issues/464

That's been fixed already on my side. You still need to delete the remaining stackdumps by yourself after the update.
