### ISSUE TITLE
0-byte files after update_suite.sh-run

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#470]
every time update_suite.sh creates a zero-byte file in the build-dir
normally it can be deleted, but it stays..
i know, not really a bug but my build dir is full of  user-changes-yyyy-mm-dd-hh.mm.ss.diff -files :-)

**Comment by wiiaboo** [comment]
It'll create those one more time unless you change update_suite.sh to include the fix, but it shouldn't anymore after that.

You have untracked files somewhere in the suite, those were creating the empty diffs.
