### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#471]
Hey there, me again...
After the automatic updates when starting the suite today, the building stopped.
See [logs.zip] (https://0x0.st/4ON.zip).

After that when I restart, it always wants to remove some packages and then reinstall them.

I also tried a clean install with the same problem.
I did have the line 21 uncommented as you recommended for me in both cases...

**Comment by wiiaboo** [comment]
Your ffmpeg_options.txt seems broken somehow, but not the one inside the zip.
What text editor did you use?

**Comment by BlackScreen** [comment]
Notepad++

**Comment by wiiaboo** [comment]
Run this in mintty:
```bash
cd /trunk
source /build/media-suite_helper.sh
ffmpegChoice=y do_getFFmpegConfig
printf '"%q"\n' "${FFMPEG_OPTS[@]}"
```

**Comment by ASopH** [comment]
same problem here
after
cd /trunk
source /build/media-suite_helper.sh
ffmpegChoice=y do_getFFmpegConfig
printf '"%q"\n' "${FFMPEG_OPTS[@]}"


[diagnostics.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/780588/diagnostics.txt)

**Comment by ASopH** [comment]
I'd same problem like BlackScreen and run the lines in mintty..
after restarting the suite the following lines shown up :-(
Something went wrong.
MSYSTEM: MINGW64
pwd: F:\m-a-s
fstab:
none / cygdrive binary,posix=0,noacl,user 0 0

F:\m-a-s\ /trunk
F:\m-a-s\build\ /build
F:\m-a-s\msys64\mingw32\ /mingw32
F:\m-a-s\msys64\mingw64\ /mingw64
F:\m-a-s\local32\ /local32
F:\m-a-s\local64\ /local64
Create a new issue and upload all logs you can find, especially compile.log
Enter to continue

**Comment by wiiaboo** [comment]
That code snippet isn't a fix, it's a diagnostic.

**Comment by wiiaboo** [comment]
It's an issue with latest version of MSYS sed, but it'll still need to be fixed here, probably.

**Comment by ASopH** [comment]
I have no fix .. 
after the last diagnosting the suite will deinstall packages..

-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date

-------------------------------------------------------------------------------
Checking pacman packages...
-------------------------------------------------------------------------------


-------------------------------------------------------------------------------
You have more packages than needed!
Do you want to remove them?
-------------------------------------------------------------------------------

Remove:
asciidoc
autoconf
autogen
automake-wrapper
bison
diffstat
dos2unix
git
gperf
help2man
intltool
libtool
make
man-db
mercurial
mingw-w64-i686-cmake
mingw-w64-i686-dlfcn
mingw-w64-i686-doxygen
mingw-w64-i686-gcc
mingw-w64-i686-libpng
mingw-w64-i686-nasm
mingw-w64-i686-ninja
mingw-w64-i686-pcre
mingw-w64-i686-pkg-config
mingw-w64-i686-tools-git
mingw-w64-i686-yasm
mingw-w64-x86_64-cmake
mingw-w64-x86_64-dlfcn
mingw-w64-x86_64-doxygen
mingw-w64-x86_64-gcc
mingw-w64-x86_64-libpng
mingw-w64-x86_64-nasm
mingw-w64-x86_64-ninja
mingw-w64-x86_64-pcre
mingw-w64-x86_64-pkg-config
mingw-w64-x86_64-tools-git
mingw-w64-x86_64-yasm
p7zip
patch
python
subversion
texinfo
unzip
upx
wget
winpty
xmlto
zip
remove packs [y/n]?

 and so on. Like in a loop
 ...

sorry forget to press "Comment"

**Comment by wiiaboo** [comment]
Stop running the suite, I'm thinking of a fix.

**Comment by BlackScreen** [comment]
This is the output:
```
$ printf '"%q"\n' "${FFMPEG_OPTS[@]}"
"$'--enable-avisynth\r'"
"$'--enable-gcrypt\r'"
"$'--enable-libmp3lame\r'"
"$'--enable-libopus\r'"
"$'--enable-libvorbis\r'"
"$'--enable-libvpx\r'"
"$'--enable-libx264\r'"
"$'--enable-libx265\r'"
"$'--enable-cuda\r'"
"$'--enable-cuvid\r'"
"$'--enable-schannel\r'"
"$'--enable-sdl2\r'"
"$'--enable-decklink\r'"
"$'--enable-fontconfig\r'"
"$'--enable-frei0r\r\r'"
"$'--enable-libass\r'"
"$'--enable-libbluray\r'"
"$'--enable-libbs2b\r'"
"$'--enable-libcaca\r'"
"$'--enable-libfreetype\r'"
"$'--enable-libfribidi\r'"
"$'--enable-libgme\r'"
"$'--enable-libgsm\r'"
"$'--enable-libilbc\r'"
"$'--enable-libmfx\r'"
"$'--enable-libmodplug\r'"
"$'--enable-libopencore-amrnb\r'"
"$'--enable-libopencore-amrwb\r'"
"$'--enable-libopenjpeg\r'"
"$'--enable-librtmp\r'"
"$'--enable-libschroedinger\r'"
"$'--enable-libsoxr\r'"
"$'--enable-libspeex\r'"
"$'--enable-libtheora\r'"
"$'--enable-libtwolame\r'"
"$'--enable-libvidstab\r'"
"$'--enable-libvo-amrwbenc\r'"
"$'--enable-libwavpack\r'"
"$'--enable-libwebp\r'"
"$'--enable-libxavs\r'"
"$'--enable-libxvid\r'"
"$'--enable-libzimg\r'"
"$'--enable-openssl\r'"
"$'--enable-libsnappy\r'"
"$'--enable-gpl\r'"
"$'--enable-opencl\r'"
"$'--enable-opengl\r'"
"$'--enable-libcdio\r'"
"$'--enable-libfdk-aac\r'"
"$'--enable-libkvazaar\r'"
"$'--enable-librubberband\r'"
"$'--enable-libssh\r'"
"$'--enable-libtesseract\r'"
"$'--enable-libzvbi\r'"
"$'--enable-chromaprint\r'"
"$'--enable-libopenh264\r'"
"$'--enable-libopenmpt\r'"
"$'--enable-netcdf\r'"
"--enable-libnpp"
```

It did not solve my problem when starting the suite, that everytime it is asking for removing and reinstalling some packages. Also the suite exited on the same point - [logs.zip] (https://0x0.st/4Od.zip).

**Comment by wiiaboo** [comment]
Basically, some update to sed/readline/whatever screwed parsing of text files with CRLF lines.
Every sed that assumed CR as a valid endline character is likely fucked.

**Comment by gapbl4** [comment]
I just removed everything I don't need from ffmpeg_options.txt and mpv_options.txt files and everything thats left is just separated by spaces. Works fine it seems.

**Comment by wiiaboo** [comment]
It should be fixed with git master as of https://github.com/jb-alvarado/media-autobuild_suite/commit/42e3b9a60da2124b190fc5febd6b0e308acc1cce, at least from trying my full build.
Though it's likely some other thing could've broke silently.

**Comment by BlackScreen** [comment]
Thanks for the fixes. The build works smoothly again for me now. :)
