### ISSUE TITLE
[REQ] Option to Select Default and/or Stable Branch for x265

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#472]
Wonder if it would be possible for you to add Option to Select Default and/or Stable Branch for x265

**Comment by wiiaboo** [comment]
Change
```
do_vcs "hg::https://bitbucket.org/multicoreware/x265"
```
to
```
do_vcs "hg::https://bitbucket.org/multicoreware/x265#branch=stable"
```

Maybe it works. As for an additional option for this, I don't really for it. Patches welcome.

**Comment by LigH-de** [comment]
Old issue, new dimension:

The x265 development is now split into three branches: "default" with experimental patches, "release_X.Y" (apparently being renamed to match milestones) with bug fix patches and sub version tags, and "stable" with rare merges. You cannot rely on "tip" pointing to either.

**Comment by 1480c1** [comment]
So should we "checkout" default then? (I'm not sure the terminology for mercurial)

**Comment by LigH-de** [comment]
Mercurial (hg) uses "clone" and "update" (but has aliases for users with git habits).

I believe updating to the "default" branch is the default, so may be omitted.

**Comment by wiiaboo** [comment]
Didn't changing the branch break stuff in 5 minutes last time we did it?

**Comment by Barough** [comment]
DIdn't work especially well for some weird reason
