### ISSUE TITLE
failed build for mpv ??

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#476]
Running git update for angleproject...
┌ angleproject git ..................................... [Files missing]
angle in 32-bits with GCC 6 doesn't work.
  Running git clone for mpv...
  Running git update for mpv...
┌ mpv git ........................................... [Recently updated]
├ Running configure...
├ Running build...
Likely error:
[235/238] Compiling audio/decode/ad_lavc.c
[236/238] Compiling osdep/subprocess-win.c
[237/238] Linking build/mpv.com
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): In function `main':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check F:/m-a-s/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

sorry, I don't can upload logs.zip, 
It shows- We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. 
drag'n'drop doesn't go ...???

**Comment by wiiaboo** [comment]
Upload it somewhere else, then. Mediafire, dropbox, google drive, onedrive, etc.
I can't guess what's wrong.

**Comment by ASopH** [comment]
https://drive.google.com/open?id=0Bw7wTtlOFiD0aWtMd2dlTld0Y3c

**Comment by ASopH** [comment]
https://drive.google.com/open?id=0Bw7wTtlOFiD0aWtMd2dlTld0Y3c

**Comment by projalepeno** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/785243/logs.zip)

here ^^ also, thank you

**Comment by wiiaboo** [comment]
They're actually the same bug after all.
