### ISSUE TITLE
Key Ring Problems after Updating Suite

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#477]
Key Ring Problems after Updating Suite.
No compiling at all.

warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
├ Running extract...
/build/media-suite_helper.sh: line 55: cd: libgcrypt-1.7.3: No such file or directory
  Creating diagnostics file...

These are the significant lines in the compile.log

**Comment by wiiaboo** [comment]
Check the solutions in the other two issues that were fixed already.

**Comment by hekitoshinoda** [comment]
Hi, Sorry I don't check the tickets before.
Seems that #469 does the trick:


   1. completely remove msys64
   2. make sure you applied that change to media-suite_update.sh (you can
   also remove the whole line
      - make sure it's the line with [[ "$(uname)" = *6.1* ]] && nargs="-n
      4". Delete it or add a #before.
   3. after the change is done and msys64 is removed, run the .bat. It'll
   download everything again but maybe without that line in
   media-suite_update.sh it won't cause trouble this time.


Looks good so far, is running and loading/compiling the libs after
reinstalling the msys64.
With kind regards
Ben

2017-02-19 23:46 GMT+01:00 RiCON <notifications@github.com>:
