### ISSUE TITLE
write error in access to libmxf?

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#478]
Running git clone for libMXF-1.0...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_clone
fatal: unable to access 'http://git.code.sf.net/p/bmxlib/libmxf/': Connection timed out after 300015 
                                                                ~?
milliseconds
git.clone failed. Check F:/m-a-s/build/ab-suite.git.clone.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[diagnostics.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/787343/diagnostics.txt)

**Comment by wiiaboo** [comment]
Sourceforge's git is unstable, nothing I can do about it.
