### ISSUE TITLE
Add shared libass feature

### ISSUE THREAD

**Issue by Kagami** [jb-alvarado/media-autobuild_suite#481]
Right now libass is linked statically, so if you want to enable libass e.g. in both libavfilter and mpv, it will link it twice, wasting additional ≈1.5MB (libass+freetype+fribidi). Which might be inappropriate for lightweight size-optimized builds.

Would be nice to allow building libass.dll (or at least giving instructions how to do that).

**Comment by wiiaboo** [comment]
You'll likely need to shared-compile all the deps too, since I don't think autotools likes mixed shared/static libs very much, just like mpv.

**Comment by wiiaboo** [comment]
Shared libass and deps is 1.9MB instead of 1.2MB. You sure you want this?

**Comment by Kagami** [comment]
Well, it's still smaller than 2*1.2MB… At least I would like to try, does it save some space.

**Comment by wiiaboo** [comment]
Try it: http://sprunge.us/YiRb
Can't test right now with FFmpeg/mpv, just ran those manually to see if it built.

**Comment by wiiaboo** [comment]
You can compile libvpx shared but you can save 2.4MB by disabling vp8 encdec, vp9 decoder and high-bitdepth vp9.

**Comment by wiiaboo** [comment]
Check git master, I've managed to reduce ffmpeg+mpv+vpx+x264 to 28MB (not including angle).

**Comment by Kagami** [comment]
Was able to save 2 megabytes and only 300 kilobytes 7zipped with all changes from master.
Thanks a lot for help anyway, now it's much easier to experiment further.
