### ISSUE TITLE
[Question] Avoiding updates (Build only)

### ISSUE THREAD

**Issue by silverkorn** [jb-alvarado/media-autobuild_suite#482]
Hi,

I remember having a limitation forcing me to update libraries and/or having access to the Internet when I wanted to apply a self-patch.

Is there a way/option to avoid this behaviour and proceed to the build without needing to absolutely update the libraries?

Thanks!

**Comment by wiiaboo** [comment]
No. The suite is made with the assumption of internet access but maybe works without it, if the needed resources weren't cleaned up (deleteSource=2).

**Comment by silverkorn** [comment]
Yes, I have been using this option but the script doesn't want to proceed elsewise.
So I guess I'll run everything one by one then.

**Comment by myfreeer** [comment]
You can simpily add thing like `patch -p1 /trunk/build/ffmpeg-git/cmdutils.c /trunk/build/ffmpeg.patch` after those `do_vcs` stuff in `media-suite_compile.sh` where `/trunk/build/ffmpeg-git/cmdutils.c` stand for file to patch, and `/trunk/build/ffmpeg.patch` stands for your custom patch file.
