### ISSUE TITLE
ffmpeg won´t compile

### ISSUE THREAD

**Issue by Felixkruemel** [jb-alvarado/media-autobuild_suite#483]
Here all informations: https://0x0.st/J5U.zip

**Comment by wiiaboo** [comment]
Seems like some weird issue on your side.
Open mintty and run `pacman -S mingw-w64-x86_64-chromaprint` and paste the output of the command here or on some pastebin.

**Comment by Felixkruemel** [comment]
`$ pacman -S mingw-w64-x86_64-chromaprint
error: failed to init transaction (unable to lock database)
error: could not lock database: File exists
  if you're sure a package manager is not already
  running, you can remove /var/lib/pacman/db.lck
`

**Comment by wiiaboo** [comment]
Sure. Check if pacman isn't running in your task manager and remove that file if it isn't.

**Comment by Felixkruemel** [comment]
Ok worked. Thanks.
