### ISSUE TITLE
It´s Possible to Include --enable-libzmq ?

### ISSUE THREAD

**Issue by renatosbc** [jb-alvarado/media-autobuild_suite#484]
Hi !

jb-alvarado, great great job !   :-)

It´s possible to compile ffmpeg in windows enviroment with ZeroMQ (http://zeromq.org) support ?
In Linux it´s easy: compile libzmq and add --anable-libzmq in ffmpeg ./configure options.

Zeromq has a windows installer - http://zeromq.org/distro:microsoft-windows, that installs DLLs, sources and Libs in specific folders (C:\Program Files\ZeroMQ 4.0.4\bin, C:\Program Files\ZeroMQ 4.0.4\src and C:\Program Files\ZeroMQ 4.0.4\lib. 

I´m a novice in windows enviromment compilling, but I´m a great fan o ffmpeg and I expect to callaborate with this great project.  :-)

**Comment by BlackScreen** [comment]
Seems to not work at my end: [logs.zip] (https://0x0.st/yip.zip)
When uncommenting the "--enable-libzmq" it builds without problems for me.

**Comment by wiiaboo** [comment]
Typos. Should be fixed now.

**Comment by BlackScreen** [comment]
Confirmed. Building works. Thanks for fixing!
