### ISSUE TITLE
ffmpeg fails on 'undefined reference to fribidi_charset_to_unicode'

### ISSUE THREAD

**Issue by Murmur** [jb-alvarado/media-autobuild_suite#485]
(Win10-64bit, autobuild scripts updated from git)
ffmpeg fails on 'undefined reference to fribidi_charset_to_unicode'
Copy and paste [logs.zip](https://0x0.st/yz5.zip) in the GitHub issue.

I did a random test using `$ pacman -S mingw-w64-x86_64-fribidi` command in Mintty console, this downloaded `mingw-w64-x86_64-glib2-2.50.3-2, mingw-w64-x86_64-fribidi-0.19.7-1` packages. No help. I have not run a build for several months until today.

> Likely error:
> libavfilter/vf_drawtext.o:vf_drawtext.c:(.text+0x10ad): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `fribidi_unicode_to_charset'
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/library.mak:103: libavfilter/avfilter-6.dll] Error 1
> LD      libavfilter/avfilter-6.dll
> libavfilter/vf_drawtext.o:vf_drawtext.c:(.text+0xf06): undefined reference to `fribidi_charset_to_unicode'
> libavfilter/vf_drawtext.o:vf_drawtext.c:(.text+0xf06): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `fribidi_charset_to_unicode'
> libavfilter/vf_drawtext.o:vf_drawtext.c:(.text+0x10ad): undefined reference to `fribidi_unicode_to_charset'
> libavfilter/vf_drawtext.o:vf_drawtext.c:(.text+0x10ad): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `fribidi_unicode_to_charset'
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/library.mak:103: libavfilter/avfilter-6.dll] Error 1
> make failed. Check C:/projects/media-autobuild_suite/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
> This is required for other packages, so this script will exit.

**Comment by Murmur** [comment]
**Solved** Somehow I had an older non working `fribidi.a/.dll` files in a local64/ folder and build script did not rebuild them. Deleted files and a build process completed.

**Comment by wiiaboo** [comment]
FFmpeg's shared-only build also makes some libs shared (freetype, fribidi, libass,. Is this expected or do you prefer the previous way with everything statically inside FFmpeg libs?

**Comment by Murmur** [comment]
Thanks for fast response.  I prefer to have a separate `avcodec|device|filter|format|util.dll` files and small ffmpeg.exe and ffprobe.exe files. I made a git pull command and rerun a build, set `ffmpegB2=3, ffmpegUpdate=1, ffmpegChoice=1` options and run script. 

Binaries and dll files were built but `freetype|fribidi|libass.dll` files were not created. I could take them from the backup folder so binaries work but build script should have had create them?
