### ISSUE TITLE
Support quick sync video codec

### ISSUE THREAD

**Issue by sarbjit-longia** [jb-alvarado/media-autobuild_suite#486]
I really loved this build suite. It is very helpful but I would love if you can support quick sync video support while building the ffmpeg libraries.

**Comment by myfreeer** [comment]
Did you mean [`--enable-libmfx`](https://github.com/jb-alvarado/media-autobuild_suite/wiki/ffmpeg_options.txt#external-libraries-needed-for-basic-support-of-formats-decoding)?

**Comment by sarbjit-longia** [comment]
yes

**Comment by myfreeer** [comment]
Then add that to `build/ffmpeg_options.txt`.

**Comment by sarbjit-longia** [comment]
Simply adding that wont work, we have to link it against the libmfx library.

**Comment by myfreeer** [comment]
Then edit `media-autobuild_suite.ini`, find and change things like `ffmpegChoice=*` to `ffmpegChoice=1` to use options in `build/ffmpeg_options.txt`

**Comment by sarbjit-longia** [comment]
Thanks for the reply and I will try that. Can you also please guide me as how can i link this against libmfx. I need to specify somewhere where to find libmfx. I found this link where they mentioned steps but finding it hard to use the steps in the script

https://gist.github.com/Brainiarc7/dd9e9b62bddb53b771b3a0754e352f53

**Comment by sarbjit-longia** [comment]
look at this too

https://github.com/lu-zero/mfx_dispatch

**Comment by myfreeer** [comment]
libmfx would be automatically downloaded to `build/libmfx-git` and compile to `local64/lib/libmfx.a` with `--enable-libmfx`.

**Comment by sarbjit-longia** [comment]
oh ok awesome...let me try that..thanks a lot

**Comment by sarbjit-longia** [comment]
It worked fine..thanks for a awesome tool to build FFmpeg.
