### ISSUE TITLE
FFmpeg with 10-Bit X264?

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#488]
Today I have tried capturing a 10-Bit MP4 from a Decklink card with a build from your suite. 
I discovered that my builds could only capture with 8-Bit. Did I do something wrong or is this currently not possible? If so, could you add an option for building FFmpeg with 8-Bit and/or 10-Bit X264?
Thanks for your reply.

**Comment by wiiaboo** [comment]
It's already there. Change `x2642` to `x2642=3` in the .ini and it'll compile with 10-bit x264 only.

**Comment by wiiaboo** [comment]
Also, x264 has nothing to do with decklink. Use `-pix_fmt` in FFmpeg to decide what you want the format of the output to be in.
If you want 10-bit input to be output as 10-bit you do need 10-bit x264 or `-c copy` might also work.
Any further questions do them on FFmpeg support forum/IRC/etc.

**Comment by BlackScreen** [comment]
@wiiaboo: Never mind my explanation with the Decklink card - just wanted to present you with a use case of mine. ;)
I tested the other option (x2642=3) and I got FFmpeg with 10-Bit support for libx264. My standard config here is "4". So my question is: if it isn't possible to build FFmpeg with 8-Bit and 10-Bit support, then would it be possible to build two versions of FFmpeg when the INI-value "x2642" is "1" and "4"? It would really help me. Thanks! :)

**Comment by wiiaboo** [comment]
You could also pipe using FFmpeg and whatever x264 bitness you want. There's x264.exe and x264-10bit.exe. Compiling two FFmpeg's just to use different x264 libs is bothersome. That's an extra 30 mins just to build FFmpeg again with only one different lib.
@Selur probably knows more about piping FFmpeg.

**Comment by BlackScreen** [comment]
@wiiaboo: Piping would also be an option. I just don't know how to do it, so I am looking forward to a little explanation. :+1:

**Comment by wiiaboo** [comment]
What's the format/codec that decklink comes  in?

**Comment by BlackScreen** [comment]
This is my command line to capture a MP4 from 1080i50 input:
`ffmpeg.exe -hide_banner -r 25 -rtbufsize 2048M -channels 2 -video_input sdi -audio_input embedded -f decklink -i "DeckLink HD Extreme 3D@9" -vf "yadif" -vcodec libx264 -s 1920x1080 -pix_fmt yuv420p -preset ultrafast -crf 18 -profile:v high -level 4.0 -acodec aac -ab 256k "Capture.mp4"`

**Comment by Selur** [comment]
I don't think piping would be the right approach to this since audio and video input would be processed separability and result in two output which later would need to be synched (<- this might be problematic) and muxed into one output file.
What should be possible is to use an ffmpeg build which uses dynamically linked x264, this way ffmpeg should switch between 8bit and 10bit. (see: http://lists.ffmpeg.org/pipermail/ffmpeg-user/2013-January/012769.html)

**Comment by wiiaboo** [comment]
Yeah, but what does it say in this part:
```
Input #0, [...]
--->  Stream #0:0: Video: h264 (High 10), yuv420p10le(tv, bt709, progressive), 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
```
If the Video is already h264 you could just use `-vcodec copy` and avoid having to reencode to either 8 or 10-bit.

Is the input not always 10-bit? Why would you want to encode the input to 10 or 8-bit depending on input (losing quality) but not do the format conversion in FFmpeg and always encode to 10-bit or 8-bit (always encoding to 10-bit but upsampling to 10-bits losing less quality)?

I've never used decklink so I don't know what formats/codecs it supports, but I'd think decklink itself does encoding on-the-fly looking at the tech specs in the site?

**Comment by wiiaboo** [comment]
Alternatively I could add an option to compile x264 to shared libs and then you could rename them accordingly, but that's still troublesome to work with, I'd say. Much less work to just encode everything to 10-bit. There's always quality loss involved since you're not encoding losslessly.

**Comment by wiiaboo** [comment]
The examples in FFmpeg docs always use `-vcodec copy -acodec copy`: https://www.ffmpeg.org/ffmpeg-devices.html#decklink

**Comment by Selur** [comment]
@wiiaboo: 'rawvideo (UYVY / 0x59565955), uyvy422, 1920x1080,' is 8bit and not h264, so '-vcodec copy' won't work.

**Comment by Selur** [comment]
> The examples in FFmpeg docs always use -vcodec copy -acodec copy: 

and thus save to uncompressed avi output (in general: bad idea)

**Comment by wiiaboo** [comment]
Sure, it's probably huge. But looking at the options, whether it's yuv422 or v210 depends on using -bm_v210 or not, so usually the input is always v210 if the device supports it or yuv422 which isn't 10-bit. Is it that important for the output to always use the same bitness as the input if you're encoding anyway?

**Comment by Selur** [comment]
> Is it that important for the output to always use the same bitness as the input if you're encoding anyway?

The format of the output of the encoding should be up to the users needs. :)
He's aiming for a 10bit H.264 output so either he needs to use:
a. a statically compiled ffmpeg version which incorporates 10bit libx264
or
b. a dynamically compiled ffmpeg version + the matching 10bit libx264

**Comment by BlackScreen** [comment]
@Selur: How would I build or use a FFmpeg build with dynamically linked x264?
Sorry for probably asking a stupid question, but I used only static builds until now.
Thank you both for helping out! :+1:

**Comment by wiiaboo** [comment]
>He's aiming for a 10bit H.264 output so either he needs to use:
a. a statically compiled ffmpeg version which incorporates 10bit libx264
or
b. a dynamically compiled ffmpeg version + the matching 10bit libx264

Exactly. So why would a FFmpeg with just 10-bit libx264 and `-pix_fmt yuv420p10le` not be enough for whatever input he gets?

**Comment by Selur** [comment]
@wiiaboo: I never said it wouldn't. (assuming he always needs 10bit x264 output)
@BlackScreen: I think the script should already be able to compile a dynamically linked ffmpeg, but wiiaboo can probably clear that up. :)

**Comment by wiiaboo** [comment]
Seems to work fine. You'll still need to rename them when you want to switch between 8-bit and 10-bit.

Do you really really need to be able to choose between one or the other on runtime? You'd need to remember to rename the dll to the right name each time or copy ffmpeg.exe to a different directory and rename `libx264-148-10bits.dll` to `libx264-148.dll` and call the directory `ffmpeg-10bits` or something.

Sounds like a chore to me that could be avoided by just always encoding to 10-bit x264.

Before you say 'why not compile two ffmpeg.exe with different x264 bitness?', that would be the exact same chore as what I said above. Same wasted space, much more wasted time on each compilation, same need to point to different paths.

**Comment by BlackScreen** [comment]
Cool, thanks for including this. Will try it out!

**Comment by BlackScreen** [comment]
It works. Thanks!
Just one quick question: Would it be possible to offer a combination of the "x2642"-value in the INI which builds the shared libs and the binaries? (4+5?)

**Comment by wiiaboo** [comment]
"standalone" option controls whether binaries are built or not.

And if you're only using x264 within FFmpeg you don't need option 4 is exactly the same as the others. The only thing that does is enable x264.exe to read more formats/codecs, not the library.
