### ISSUE TITLE
MinGW32 GCC compiler isn't installed; maybe the download didn't work Do you want to try it again?

### ISSUE THREAD

**Issue by seasun** [jb-alvarado/media-autobuild_suite#491]
bug i see the log show like these:
error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
error: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
error: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust.

the logs.zip is here.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/849601/logs.zip)

my windows is 10.1.
thank you.

**Comment by wiiaboo** [comment]
Looks like a completely screwed up installation. No idea. Remove everything and try again.
