### ISSUE TITLE
freetype2 2.7.1 can't download in china

### ISSUE THREAD

**Issue by seasun** [jb-alvarado/media-autobuild_suite#494]
http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.bz2 
this link can not access.
but I found this link be work.(https://nchc.dl.sourceforge.net/project/freetype/freetype2/2.7.1/freetype-2.7.1.tar.bz2)

how to replace the error link?
I can not find it.
I try change in dependencies-releases.txt file,but not work.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/857991/logs.zip)

**Comment by seasun** [comment]
media-suite_compile.sh

**Comment by wiiaboo** [comment]
Weird, http://www.blockedinchina.net/?siteurl=download.savannah.gnu.org says it isn't blocked.

**Comment by myfreeer** [comment]
@wiiaboo possible to add an option to apply a proxy on `do_wget()` and `clean_html_index()` ?

**Comment by seasun** [comment]
download.savannah.gnu.org  can indeed access,but http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.bz2 not work.

**Comment by wiiaboo** [comment]
Create a text file called `custom_build_options` inside `/msys64/home/<your username>/` with:
```bash

export HTTP_PROXY=ip.address:port
export HTTPS_PROXY=ip.address:port

```
and it should work.

**Comment by seasun** [comment]
@wiiaboo i had resloved it by https://nchc.dl.sourceforge.net/project/freetype/freetype2/2.7.1/freetype-2.7.1.tar.bz2
thanks all the same.

**Comment by wiiaboo** [comment]
Maybe it's redirecting to a blocked mirror.
