### ISSUE TITLE
this bat only build FFmpeg (shared or static)?

### ISSUE THREAD

**Issue by seasun** [jb-alvarado/media-autobuild_suite#495]
I want to build ffmpeg dev and include fdk-aac?
I only find .a files, not find dll and .lib files.

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-autobuild_suite.bat#L529-L556
Pretty clear.

**Comment by wiiaboo** [comment]
If for some reason you missed the option when you first ran the suite, you can delete the .ini file in /build and remake the choices.
