### ISSUE TITLE
replace git urls with http urls

### ISSUE THREAD

**Issue by sarbjit-longia** [jb-alvarado/media-autobuild_suite#496]
Its not an issue just enhancement request that for download urls that are available through http use http instead of git as behind firewall git protocol might be blocked but http is always enabled.

**Comment by wiiaboo** [comment]
What? There's no git:// anywhere on the script. What do you mean?

**Comment by wiiaboo** [comment]
The last git:// URIs were removed with caf940ef108b304d22a135c80ccfb93ddb6c10d6 almost a month ago.
Unless you're more clear about what you mean, this isn't an issue.

**Comment by sarbjit-longia** [comment]
Thanks for update, i actually tried it few weeks ago and it failed on my system which is behind firewall. I will try it again.

Thanks

**Comment by sarbjit-longia** [comment]
I checked it and it worked great.. as always you guys came more than my expectations. Carry on great work.
