### ISSUE TITLE
libdcadec support

### ISSUE THREAD

**Issue by AnryCryman** [jb-alvarado/media-autobuild_suite#497]
Hi. Can you please add libdcadec (https://github.com/foo86/dcadec) to your autobuild suite?

**Comment by wiiaboo** [comment]
Why? It's natively in FFmpeg.

**Comment by wiiaboo** [comment]
That repo is basically only good for a standalone decoder, nothing else.

**Comment by wiiaboo** [comment]
Not to mention it stopped being updated since being integrated into FFmpeg, it's basically dead.
