### ISSUE TITLE
Build still fails while making liblsmash

### ISSUE THREAD

**Issue by aidik** [jb-alvarado/media-autobuild_suite#500]
[logs.zip](https://0x0.st/vGf.zip)

Despite the fact that I get the latest version the build still fails.

`HEAD is now at 2b08c74 lsmash: use lightffmpeg PKG_CONFIG_PATH too`

**Comment by wiiaboo** [comment]
Try removing everything in /local32/opt/lightffmpeg.

**Comment by wiiaboo** [comment]
Can't reproduce it on my side.

**Comment by aidik** [comment]
Still the same problem.

 [logs.zip](https://0x0.st/vdh.zip)

Can I somehow provide more info?

**Comment by wiiaboo** [comment]
OK, sorry. Didn't realize you were not using the full x264 option. Should be fixed now.

**Comment by aidik** [comment]
Oh, that was quick, thank you. I'm testing it and will let you know as soon as I know more.

**Comment by aidik** [comment]
BTW: what is the full option wit x264?

**Comment by wiiaboo** [comment]
The fourth one.

**Comment by aidik** [comment]
> liblsmash git ............................................. [Up-to-date]
> ├ Building 10-bit x264...
> ├ Running configure...
> ├ Running make...
> ├ Building 8-bit x264...
> ├ Running configure...
> ├ Running make...
> ├ Running install...
> ├ Stripping...
> └ x264-git ................................................... [Updated]

It works! Thank you again.
