### ISSUE TITLE
Likely error

### ISSUE THREAD

**Issue by aidik** [jb-alvarado/media-autobuild_suite#502]
> Likely error:
> make -C ffmpeg libavcodec/libavcodec.a
> make[1]: Entering directory '/build/mplayer-svn/ffmpeg'
> CC      libavcodec/qsvdec_other.o
> libavcodec/qsvdec_other.c:27:26: fatal error: mfx/mfxvideo.h: No such file or directory
>  #include <mfx/mfxvideo.h>
>                           ^
> compilation terminated.
> make[1]: *** [common.mak:60: libavcodec/qsvdec_other.o] Error 1
> make[1]: Leaving directory '/build/mplayer-svn/ffmpeg'
> make: *** [Makefile:740: ffmpeg/libavcodec/libavcodec.a] Error 2
> install failed. Check C:/media-autobuild_suite/build/mplayer-svn/ab-suite.install.log
> This isn't required for anything so we can move on.

**Comment by wiiaboo** [comment]
mplayer is unsupported. It breaks too easily. Try their bug tracker.
