### ISSUE TITLE
small question regarding ffmpeg,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#505]
Why does it take so long to compile it ? 
There are multiple sh.exe instances but at most one or two are using 0.5-2% CPU usage,... is there some flag to speed this up?

**Comment by wiiaboo** [comment]
No idea. Wrong place to ask that. Try msys2 or FFmpeg.

**Comment by wiiaboo** [comment]
Blame NTFS/Windows, basically, afaik.

**Comment by wiiaboo** [comment]
Dedicating a disk to a VM for cross-compilation in some distro would probably be tons faster than doing it on Windows.

**Comment by Selur** [comment]
Yes, a build suite for linux which can crosscompile all the stuff media-autobuild_suite can build would be nice.

**Comment by wiiaboo** [comment]
That's mostly what https://github.com/rdp/ffmpeg-windows-build-helpers does, then.

**Comment by wiiaboo** [comment]
Or even running this suite in wine might work too. Never tried.

**Comment by Selur** [comment]
> That's mostly what https://github.com/rdp/ffmpeg-windows-build-helpers does, then.
only if you just need ffmpeg and don't care about all the other tools,...
-> not really an option
