### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#506]
Hi.
Decklink v10.8.6 - http://www94.zippyshare.com/v/qX4TsgaY/file.html

regards,
laur

**Comment by wiiaboo** [comment]
Do you happen to have any contacts inside Decklink to ask why the SDK is unredistributable?
To be completely legal, I'd have to delete the decklink headers from the repo too.

**Comment by wiiaboo** [comment]
Send them this message in particular: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839941#35

**Comment by laurfb** [comment]
Nope, I don't have any contacts... sorry
:(

**Comment by BlackScreen** [comment]
What happened with the Decklink SDK? Am I understanding this correctly that this could mean, that we no longer could build FFmpeg builds with Decklink support? This would be really uncool.

**Comment by wiiaboo** [comment]
You can, but not redistribute the binaries. Complain to Decklink. Maybe they add a exception for the headers in the SDK EULA, maybe not.

**Comment by BlackScreen** [comment]
Ok, redistribution would not be a problem for me, as long as I can build FFmpeg versions with Decklink support for the time beeing, I would be fine.

**Comment by wiiaboo** [comment]
Merged.
