### ISSUE TITLE
Question about CPU cores usage

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#509]
Hello 

My (old) CPU [Intel(R) core(TM)2 Duo CPU T5250 @ 1.50GHz] has only 2 cores, 
so in **media-autobuild_suite.ini** I have set `cores=1` 

I have an old habit of keeping Windows Task Manager always open, 
to inspect what is doing what in terms of RAM+CPU...

Earlier today I had fired up the suite and at some time I noticed, to my surprise, 
that both cores of my CPU were under heavy strain; no other heavy CPU processes 
were running at the same time, not even a browser (nor any scan of some sort by 
my Security suite, in fact it was turned off at the time - only ab-suite using laptop's resources...).
I have attached a sceengrab of when the suite was compiling updated speex lib: 

![compiler](https://cloud.githubusercontent.com/assets/9669492/25306867/33cd2af2-279f-11e7-816e-b27f46ca11ac.jpg)

Any thoughts?

TIA

**Comment by wiiaboo** [comment]
I didn't make the build systems, so I can't tell how they do their multi-threading.

No idea.
