### ISSUE TITLE
error building mpv

### ISSUE THREAD

**Issue by myfreeer** [jb-alvarado/media-autobuild_suite#510]
┌ mpv git ......................................... [Newer dependencies]
├ Running configure...
├ Running build...
Likely error:
[470/475] Compiling common/encode_lavc.c
[471/475] Compiling options/parse_commandline.c
[472/475] Compiling video/filter/vf_sub.c
[473/475] Linking build/mpv.com
[474/475] Linking build/mpv.exe
gcc.exe: error: CreateProcess: No such file or directory

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check E:/ProTools/media-autobuild_suite-master/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/xF8.zip
Copy and paste [logs.zip](https://0x0.st/xF8.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Just try running it again, that's not a suite error.

**Comment by myfreeer** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/949747/logs.zip)
... and fails again.

**Comment by wiiaboo** [comment]
Still not the suite's fault. Try removing mpv-git directory.

**Comment by myfreeer** [comment]
Running git clone for mpv...
  Running git update for mpv...
┌ mpv git ........................................... [Recently updated]
├ Running configure...
├ Running build...
Likely error:
[470/475] Compiling video/out/opengl/hwdec_d3d11eglrgb.c
[471/475] Compiling audio/filter/af_pan.c
[472/475] Compiling audio/decode/dec_audio.c
[473/475] Compiling options/parse_commandline.c
[474/475] Linking build/mpv-1.dll
gcc.exe: error: CreateProcess: No such file or directory

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check E:/ProTools/media-autobuild_suite-master/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
rm: cannot remove 'logs.zip': Device or resource busy

All relevant logs have been anonymously uploaded to https://0x0.st/xCg.zip
Copy and paste [logs.zip](https://0x0.st/xCg.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Try using less cores.

**Comment by myfreeer** [comment]
┌ mpv git .............................................. [Updates found]
├ Running configure...
├ Running build...
Likely error:
[470/475] Compiling osdep/path-unix.c
[471/475] Compiling osdep/glob-win.c
[472/475] Compiling osdep/win32/pthread.c
[473/475] Compiling ta/ta_utils.c
[474/475] Linking build/mpv.exe
gcc.exe: error: CreateProcess: No such file or directory

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check E:/ProTools/media-autobuild_suite-master/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/3-I.zip
Copy and paste [logs.zip](https://0x0.st/3-I.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
I can't hand-hold you any more, sorry.

**Comment by Vangelis66** [comment]
@myfreeer 
I am sorry, I can't help you either with your issue, but if you eventually fail to get it sorted out, 
you can always download pre-compiled mpv x64 binaries from:

https://sourceforge.net/projects/mpv-player-windows/files
http://mpv.srsfckn.biz/

If you insist on compiling yourself, maybe take a look at 
https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md
and/or report your issue over at 
https://github.com/mpv-player/mpv/issues

**Comment by pavelxdd** [comment]
I've also had the same issue, and solved it by disabling `--enable-libcdio` flag in ffmpeg configuration options and recompiling both ffmpeg and mpv.

So it actually seems to be an issue with the suite scripts, @wiiaboo

**Comment by wiiaboo** [comment]
Great, send a pull request then. I don't have time.

**Comment by pavelxdd** [comment]
Sorry, these errors seem to be completely random. I enabled libcdio again and recompiled - and all went fine.

**Comment by LigH-de** [comment]
I'm running into #519 as well, regularly now. Unfortunately, this error message is so vague. Is there any way to discover which process could not be created, which dependent executable could not be found? According to some cross compiling Wiki FAQ I found, it might e.g. be the cc1.exe; another source mentioned the g++.exe; so I wonder if the reason might be an incompletely downloaded and extracted GCC package (similar to an incomplete libressl I just had).

I fear I may have to clean the whole suite and let it re-install from scratch to fix this, if there is no hint which executable spawn fails exactly. But it seems not to be very uncommon among the GCC package and related compilers, that subsequently called executables are not reliably found if e.g. the PATH is incomplete, or there was a wrong assumption navigating the directory tree (e.g. too few/many '..' up-levels). The web is full of reports for the most versatile reasons.

**Comment by myfreeer** [comment]
@LigH-de pacman has signature validation and would refuse to install broken packages. Check `build\update.log` and it's likely to have things like `checking package integrity`.

**Comment by LigH-de** [comment]
Second PC. Same failure. This is no more coincidence, there is a reason behind it.

I'll re-install one.

**Comment by LigH-de** [comment]
The re-installed suite passed.

So I wonder if something during the update to GCC 6.3.0 might have failed. Or whatever. Sometimes a fresh start is the solution when you can't find another.

**Comment by wiiaboo** [comment]
The only thing in common with all the issues and my inability to reproduce it is that you're running the suite in a relatively long directory tree ("E:/ProTools/media-autobuild_suite-master/" instead of "E:/ab" like me) and all possible FFmpeg external libs (also unlike me).

You're reaching over [Windows' 32767 character command limit](https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553). There's no way to fix this other than using a shorter directory tree or less external libs.

There's no way you need all extralibs for anything. Even Zeranoe's list of external libs is way too much.

**I'm closing this as wontfix and locking any further issues from this error after adding the hack.**

If you still want every useless external lib just cross-compile in Linux.
