### ISSUE TITLE
Truncate git object hash back to 7 characters

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#512]
Hello; this isn't an issue but rather a help/support request; it isn't addressed strictly 
to the suite maintainer, if you happen to be in the know, chime in...

Latest compiler that comes with the suite incorporates git v2.12.1: 
```
$ git --version
git version 2.12.1
```
It looks as though git 2.12.1 defaults now to a length of 10 characters when calculating/printing 
the SHA1 commit hash of the code snapshot compiled FFmpeg binary was built from: 
```
$ ffmpeg -version
ffmpeg version N-85705-ge061826eb2 Copyright (c) 2000-2017 the FFmpeg developers

  built with gcc 6.3.0 (Rev2, Built by MSYS2 project)
```
To be on par with the Zeranoe/Roger Pack FFmpeg compiles (which still print a 7-char hash), 
I started exploring the possibility of truncating the 10-char hash the suite produces.

It appears the compiler calculates version+extra-version by running the bash script "version.sh" 
inside ffmpeg-git sources:
```
$ cd build/ffmpeg-git && sh version.sh
N-85705-ge061826eb2
```
OTOH, inside **media-suite_compile.sh** there's 
```
        [[ -f ffmpeg_extra.sh ]] && source ffmpeg_extra.sh

        _patches="$(git rev-list origin/master.. --count)"
        [[ $_patches -gt 0 ]] &&
            do_addOption "--extra-version=g$(git rev-parse --short origin/master)+$_patches"
```
which,  as I see it, generate the **extra-version** string the compiled binary prints; indeed: 
```
$ git rev-parse --short origin/master
e061826eb2
```
Searching on Google, if I issued **short=7**, it would appear I could achieve what I want: 
```
$ git rev-parse --short=7 origin/master
e061826
```
so I went ahead and modified the "do_addOption" line accordingly... 
After 20min on "configure" and another 55min on "make" (old CPU), I was dispared to find 
that the re-compiled binary (source hadn't changed in between) still came with the 10-char hash. 
I verified my patched "media-suite_compile.sh" wasn't altered during the process, so what am I 
missing? 
Sadly, I can't afford much of trial-and-error on this old machine and on this quite hot day (24C), 
so if you have any advice to offer, do so... 
Otherwise, as I said, this is not an issue and should become a change I'll have to live with...

**Comment by wiiaboo** [comment]
You'd need to ask FFmpeg if they want to add that `--short=7` to version.sh, but I think it's better to handle whatever size hash it's there. If git thinks 10 chars are less ambiguous than 7,  they probably have a good enough reason to break a lot of scripts that assume it's 7.

Don't forget that it can also be bigger if 7 chars aren't unique within the repository.

**Comment by wiiaboo** [comment]
It actually depends on the number of commits, it's not fixed to 10, so expect it to be at least 10 and more in the future. It's the more future-proof way than hardcoding it to 7.

**Comment by Vangelis66** [comment]
Many thanks for your prompt replies :+1: 
Actually, while searching for this earlier, I did come across [this](http://stackoverflow.com/questions/18134627/how-much-of-a-git-sha-is-generally-considered-necessary-to-uniquely-identify-al) StackOverFlow entry,  which also links to https://github.com/git/git/commit/e6c587c733 that you referenced; so I already know about the logic behind Git 2.12.1 defaulting to 10 hexdigits...
What I asked in essence was a way to revert to the 7 hexdigits behaviour...

> You'd need to ask FFmpeg if they want to add that `--short=7` to version.sh

Well, I did inspect locally file "version.sh" and the part of it that calculates the N-tag & extra-version is 
```
# check for git short hash
if ! test "$revision"; then
    if (cd "$1" && grep git RELEASE 2> /dev/null >/dev/null) ; then
        revision=$(cd "$1" && git describe --tags --match N 2> /dev/null)
    else
        revision=$(cd "$1" && git describe --tags --always 2> /dev/null)
(snip)
# Shallow Git clones (--depth) do not have the N tag:
# use 'git-YYYY-MM-DD-hhhhhhh'.
test "$revision" || revision=$(cd "$1" &&
  git log -1 --pretty=format:"git-%cd-%h" --date=short 2> /dev/null)
```
It turns out (via studying their --help output) that "git (describe|log)" do not accept `--short=7` 
but rather `--abbrev=7`, so I applied [version.sh.patch](https://github.com/jb-alvarado/media-autobuild_suite/files/966491/version.sh.patch.txt) to "version.sh" and then, in minnty, I issued: 

`$ cd build/ffmpeg-git/build-static-32bit && make && make install`

Everything was already pre-compiled, so that took ca. 2min; installed FFmpeg.exe now prints: 
```
ffmpeg version N-85705-ge061826 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.0 (Rev2, Built by MSYS2 project)
```
(As a sidenote, "make" at the end printed the following warnings, can't really tell if they're benign:
```
G:/Compiler-v3/media-autobuild_suite/msys32/mingw32/lib/libssh.a(ge25519.c.obj):
 warning: definition of `crypto_sign_ed25519_ref_ge25519_base' overriding common
G:/Compiler-v3/media-autobuild_suite/msys32/mingw32/lib/libssh.a(ed25519.c.obj):
 warning: common is here
G:/Compiler-v3/media-autobuild_suite/local32/lib/libgnutls.a(sha256-ssse3-x86.o):
 warning: common of `_gnutls_x86_cpuid_s' overridden by definition
G:/Compiler-v3/media-autobuild_suite/local32/lib/libgnutls.a(x86-common.o):
 warning: defined here
```
This is on a build with `--enable-gnutls --enable-libssh`; these warnings may have been already output by "make" at the end of initial compilation by the suite, but minnty had suppressed them... ).

So, what I now need as a final step is for some kind soul to provide a patch for "**media-suite_compile.sh**" 
that itself patches version.sh prior to compiling (make) ffmpeg...
["You must not lose faith in humanity" - part of a Mahatma Gandhi quote...]

Thanks as ever...

**Comment by wiiaboo** [comment]
It's easy to patch version.sh, but still I think you shouldn't assume it'll always have 7 characters in the hash. Zeranoe and the others will eventually have the same version of git so they'll eventually have 10 characters or more too.

**Comment by wiiaboo** [comment]
Create a file called ffmpeg_extra.sh inside ffmpeg-git and place this in it:
```bash
sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2/g' version.sh
```

**Comment by Vangelis66** [comment]
@wiiaboo wrote: 

> Create a file called ffmpeg_extra.sh inside ffmpeg-git and place this in it:
> 
> `sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2/g' version.sh`

Hello :smiley: 
Having been quite ill the previous days, I only decided to revisit this today...
Yesterday night I ran the suite to update the libs (libressl-2.5.4 alone took 70min to compile!) 
and today I ran the suite with `ffmpegUpdate=3` to only build (updated) ffmpeg with your fix 
(for which I am immensely grateful :+1:).

Early on, I got the following in the console: 
(with **ffmpeg-extra.sh** inside /build/ffmpeg-git :) 
```
  Running git update for ffmpeg...
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
sed: -e expression #1, char 40: unterminated `s' command
├ Compiling static FFmpeg...
├ Running configure...
```
I immediately figured out it had to do with **ffmpeg_extra.sh**, so I killed the console...
Upon closer inspection of the contents of the ffmpeg-git dir, I soon spotted the existence 
of a "new" folder named **ffbuild** which contains: 
```
$ cd build/ffmpeg-git/ffbuild && ls
arch.mak  common.mak  library.mak  version.sh
```
So it does appear that due to upstream changes, file **version.sh** has been relocated inside /ffbuild. 
I am unsure whether this change has an overall effect on the compile script, 
currently I am running the suite without **ffmpeg-extra.sh**, configure completed without errors 
and am now runnning make...

So, should your fix be simply patched to show 

`sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2/g' /ffbuild/version.sh` 

or do I still need something more? 
As ever, thanks for your continuous guidance and sorry for the occasional "harassment"...

Regards

**Comment by wiiaboo** [comment]
My mistake, it's `sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2;g /ffbuild/version.sh'. Forgot to replace the last `/` in the sed string.

**Comment by Vangelis66** [comment]
Thanks, but is what you posted 

`sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2;g /ffbuild/version.sh`

correct? There's only one left single quote in the command (after -ri); should I write

`sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2;g' /ffbuild/version.sh` 

instead? Thanks!

**Comment by wiiaboo** [comment]
The second one.

**Comment by Vangelis66** [comment]
File ffmpeg-extra.sh changed to contain exactly: 

sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2;g /ffbuild/version.sh'

New error now: 
```
├ Changing options to comply to nonfree...
sed: -e expression #1, char 42: unknown option to `s'
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
```
???????????????????

(I fear now'll be the time you'll say you can't hand hold me anymore...)

**Comment by Vangelis66** [comment]
OK, I 'trial-and-error'ed in the minnty console, after cd to `/build/ffmpeg-git`, and it appears 
the correct command to patch the relocated version.sh is exactly: 

`$ sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2;g' ffbuild/version.sh`

So **ffmpeg-extra.sh** should contain: 

`sed -ri 's;(describe) (--tags);\1 --abbrev=7 \2;g' ffbuild/version.sh`

Thanks for your patience...
