### ISSUE TITLE
aom git build error,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#513]
[logs.zip](https://0x0.st/3w7.zip) likely error in aom itself, but I thought I post it so others can comment whether this happens to them as well (just in case that it is an compiler problem)

**Comment by wiiaboo** [comment]
Would probably be more useful to post it to their bug tracker. I doubt anyone from there comes here.

I don't have time to investigate this.

**Comment by Selur** [comment]
ok
