### ISSUE TITLE
error building ffmpeg

### ISSUE THREAD

**Issue by myfreeer** [jb-alvarado/media-autobuild_suite#519]
While static builds goes just fine...
```
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
patching file /trunk/build/ffmpeg-git/cmdutils.c
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error:
LD      libswresample/swresample-2.dll
sed -e "s/ @[^ ]*//" libpostproc/postproc-54.orig.def > libpostproc/postproc-54.def; dlltool -m i386:x86-64 -d libpostproc/postproc-54.def -l libpostproc/postproc.lib -D postproc-54.dll
sed -e "s/ @[^ ]*//" libswscale/swscale-4.orig.def > libswscale/swscale-4.def; dlltool -m i386:x86-64 -d libswscale/swscale-4.def -l libswscale/swscale.lib -D swscale-4.dll
sed -e "s/ @[^ ]*//" libswresample/swresample-2.orig.def > libswresample/swresample-2.def; dlltool -m i386:x86-64 -d libswresample/swresample-2.def -l libswresample/swresample.lib -D swresample-2.dll
LD      libavcodec/avcodec-57.dll
gcc.exe: error: CreateProcess: No such file or directory
make: *** [/build/ffmpeg-git/ffbuild/library.mak:102: libavcodec/avcodec-57.dll] Error 1
LD      libavcodec/avcodec-57.dll
gcc.exe: error: CreateProcess: No such file or directory
make: *** [/build/ffmpeg-git/ffbuild/library.mak:102: libavcodec/avcodec-57.dll] Error 1
make failed. Check E:/ProTools/media-autobuild_suite-master/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
```
All relevant logs have been anonymously uploaded to https://0x0.st/E-A.zip
Copy and paste [logs.zip](https://0x0.st/E-A.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Isn't this exactly the same as https://github.com/jb-alvarado/media-autobuild_suite/issues/510?

**Comment by LigH-de** [comment]
All of the related reports are closed. Does that mean nobody cares about either?

BTW, recently I had this issue on two distinct PC's. I re-installed the suite on both. It compiled on both for a while. Now it fails again on one of them (the other to be tested later)...

```
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error:
sed -e "s/ @[^ ]*//" libpostproc/postproc-54.orig.def > libpostproc/postproc-54.def; dlltool -m i386 -d libpostproc/postproc-54.def -l libpostproc/postproc.lib -D postproc-54.dll
LD      libswresample/swresample-2.dll
sed -e "s/ @[^ ]*//" libswscale/swscale-4.orig.def > libswscale/swscale-4.def; dlltool -m i386 -d libswscale/swscale-4.def -l libswscale/swscale.lib -D swscale-4.dll
sed -e "s/ @[^ ]*//" libswresample/swresample-2.orig.def > libswresample/swresample-2.def; dlltool -m i386 -d libswresample/swresample-2.def -l libswresample/swresample.lib -D swresample-2.dll
LD      libavcodec/avcodec-57.dll
gcc.exe: error: CreateProcess: No such file or directory
make: *** [/build/ffmpeg-git/ffbuild/library.mak:102: libavcodec/avcodec-57.dll] Error 1
LD      libavcodec/avcodec-57.dll
gcc.exe: error: CreateProcess: No such file or directory
make: *** [/build/ffmpeg-git/ffbuild/library.mak:102: libavcodec/avcodec-57.dll] Error 1
```

**Comment by wiiaboo** [comment]
It means it's useless to open here since I both don't think it's a suite issue and it's not an issue I can fix since I can't reproduce it . Since I'm the only one maintaining this, I think it's reasonable.

**Comment by LigH-de** [comment]
I wonder if it might be possible that a search path gets cropped or otherwise messed, right before compiling ffmpeg, so that GCC tools can't find their supplemental tools. In this case it might be a suite issue. But how to prove or disprove this theory? One would have to know which tool it is trying to launch and fail. I'll try to chat with GNU people on IRC. More later, I hope...

**Comment by wiiaboo** [comment]
The suite doesn't do any magic commands or options, though. Just plain `configure/make/make install`s. If it were a suite issue, it'd be reproducible with every installation of the suite.

Look at the ab-suite.*.logs and use the same commands manually in mintty and with `make V=1` with the same number of jobs the suite uses.

**Comment by LigH-de** [comment]
https://pastebin.com/0Pf3kXpj

Different error, different reason. I guess the suite prepares a PATH or exports locations to GCC before calling make, which a simple shell launch does not.

**Comment by wiiaboo** [comment]
You're running the wrong shell. It's mingw64 or mingw32.

**Comment by wiiaboo** [comment]
Or `source /local32/etc/profile2.local` for mingw32 or `source /local64/etc/profile2.local`.

**Comment by LigH-de** [comment]
Hmmm ... progress, I believe?

https://pastebin.com/qqPFQscM => same error; now, executing this whole command manually, adding `-v` to the end:

https://pastebin.com/samC6w5N

Is the reason possibly a prepended space in line 11? Or anything else?

```
 H:/development/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/collect2.exe -plugin ...
```

H:\development\media-autobuild_suite-master\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\6.3.0\collect2.exe does exist.

**Comment by wiiaboo** [comment]
It should.
```
λ ls /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/collect2.exe
/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/collect2.exe
λ pacman -Qo /mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/collect2.exe
/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/collect2.exe is owned by mingw-w64-x86_64-gcc 6.3.0-3
```

**Comment by LigH-de** [comment]
So as far as I understand it, gcc.exe is unable to launch collect2.exe; or am I already wrong here?

And if not: Is the prepended space a possible reason to fail, because it is assumed to be part of the executable file name?

**Comment by wiiaboo** [comment]
Didn't you just said it doesn't exist in your installation? That would be a big hint of why it doesn't work.

And no, spaces shouldn't just break running, unless you messed with something else. If it were something modified by the suite it would affect everyone using it.

**Comment by LigH-de** [comment]
I did not change anything after re-installing the whole suite. I should probably select static ffmpeg only and test if that passes. Or try only one job, no parallel compilation.

**Comment by wiiaboo** [comment]
You could be reaching the maximum character limit on a command. That line 11 is 33.335 characters long.

**Comment by wiiaboo** [comment]
Could you pastebin your ffbuild/config.mak?

**Comment by wiiaboo** [comment]
See https://github.com/jb-alvarado/media-autobuild_suite/issues/510#issuecomment-304753101

**Comment by myfreeer** [comment]
Not sure if related...
```
┌ ffmpeg git ........................................... [Files missing]
├ Changing options to comply to nonfree...
patching file /trunk/build/ffmpeg-git/cmdutils.c
├ Compiling shared FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
libavfilter/src_movie.o:src_movie.c:(.text.unlikely+0x6c): undefined reference to `avformat_close_input'
libavfilter/vf_signature.o:vf_signature.c:(.text+0x25f4): undefined reference to `av_get_frame_filename'
libavfilter/vf_signature.o:vf_signature.c:(.text.unlikely+0x1ee): undefined reference to `av_get_frame_filename'
libavfilter/vf_subtitles.o:vf_subtitles.c:(.text.unlikely+0x1f1): undefined reference to `avformat_open_input'
libavfilter/vf_subtitles.o:vf_subtitles.c:(.text.unlikely+0x220): undefined reference to `avformat_find_stream_info'
libavfilter/vf_subtitles.o:vf_subtitles.c:(.text.unlikely+0x25a): undefined reference to `av_find_best_stream'
libavfilter/vf_subtitles.o:vf_subtitles.c:(.text.unlikely+0x5f3): undefined reference to `av_read_frame'
libavfilter/vf_subtitles.o:vf_subtitles.c:(.text.unlikely+0x754): undefined reference to `avformat_close_input'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/ffbuild/library.mak:102: libavfilter/avfilter-6.dll] Error 1
make failed. Check E:/ProTools/media-ab/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
```
All relevant logs have been anonymously uploaded to https://0x0.st/6K6.zip
Copy and paste [logs.zip](https://0x0.st/6K6.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by LigH-de** [comment]
OK, exceeding a length limit is a probable reason; it's scary how long one single call can grow, makes me wonder if there is a difference between my two PC's how I configured the library configuration. Yesterday I re-configured the other to static-only, and using the text file to configure extra libraries: This one built well. I'll keep experimenting here. Let's leave this one closed until one can reproduce it with a clearly shorter call.

**Comment by wiiaboo** [comment]
@myfreeer unrelated. Pastebin the content of libavformat/avformat.def inside ffmpeg-git/build-shared-64bit.

**Comment by myfreeer** [comment]
@wiiaboo 
[avformat-57.def](https://pastebin.com/tDyAc0sj)
[avformat-57.orig.def](https://pastebin.com/uVVqqMvD)

**Comment by wiiaboo** [comment]
You need to recompile libgme then. Delete libgme-git or libgme.pc file inside /local(32|64)/lib/pkgconfig and re-run the suite.

**Comment by myfreeer** [comment]
@wiiaboo solved. Thank you. 
Suggestion: add things like 'use short path for the suite' to README.md

**Comment by wiiaboo** [comment]
It's already warned in the .bat, I'll just make it warn with smaller paths.

**Comment by LigH-de** [comment]
I believe that using the editable options file helps somewhat. But I don't know if it is really referenced as options file, or if you read it out and construct a long CLI call from it anyway. But I'm just running the suite again, with all options in the file enabled (call it a "stress test"), and both shared and static ffmpeg get built.

**Comment by wiiaboo** [comment]
Markdown is just plain text. It's just as readable as if you called it .txt.

**Comment by LigH-de** [comment]
After removing libschroedinger support from ffmpeg, it builds now in both mode 1 (txt) and 4 (all) with my path, 25 chars may be a bit tight as warning threshold now. But no need to change it all over again; the next user with such a problem may find several suggestions here, and as you said, much more format support than the zeranoe template is not even sensible for practical use. It's still somewhat scary to me how long a command line can grow. Support for parameter files would have eased this risk, and I would not be surprised if that was not already discussed for GNU compilers.

**Comment by wiiaboo** [comment]
Besides linux not having problems with such huge lines, `ld` and `gcc`, apparently, can also take parameters from a file. So FFmpeg/mpv probably should consider using those, at least for linking since it always involves a lot of commands.

**Comment by GyanD** [comment]
> Besides linux not having problems with such huge lines, `ld` and `gcc`, apparently, can also take parameters from a file. So FFmpeg/mpv probably should consider using those, at least for linking since it always involves a lot of commands.

ffmpeg now does this for linking in https://github.com/FFmpeg/FFmpeg/commit/9e857e1f8aeeb655adb9d09bf53add26a27092e2
