### ISSUE TITLE
Some build thoughts and questions

### ISSUE THREAD

**Issue by mabreedlove** [jb-alvarado/media-autobuild_suite#52]
Was curious if you put any thought into enabling LTO under ffmpeg.  It increases the build time for it naturally but I've been able to build it successfully just by passing in --enable-lto and the static executable drops about 2MB worth of bulk with that alone.  I'm trying to see which other static libraries can be built successfully with LTO to see just how slim it can get.  Some of them won't build if they have code written in assembly, but most of the others seem to get built fine.

As for some other questions:

1. Fontconfig - I'm not sure why but the configure script for this trashes the CFLAGS env variable although allows CPPFLAGS and LDFLAGS to pass through perfectly.  It looks like it makes an effort in trying to save/restore the value it receives whether from the env variable or passed in to the script itself.  Everything builds fine but unless flags are in CPPFLAGS or LDFLAGS, they get clobbered.  I've been using a sed replace on the Makefiles to get around this so I can pass in custom options.

2. On SDL, when you pass in CFLAGS="-DDECLSPEC=" this clobbers any of the CFLAGS in the environment so like the one above, the result is the same.  I wasn't sure if this was intentional or not.  Right now I'm testing it with CFLAGS="${CFLAGS} -DDECLSPEC="

**Comment by mabreedlove** [comment]
3.  On FLAC, we've updated to revision 1.3.1 however the script is still removing flac-1.3.0 which doesn't exist anyway so subsequent builds aren't built cleanly.

**Comment by jb-alvarado** [comment]
This LTO Flag looks interesting, I have not thought about it before. It want be great if this we can use for other libs to.
Witch CPPFLAGS and LDFLAGS you will give to the fontconfig? When the configure don't take the flag, then normally it is enough to write this at th begin of the configure line. Like in SDL: LDFLAGS:="[...]" ./configure
Your second point about SDL, I only copy the code from some where else, and don't thought about it to put also my flags in it :). But you normally a  CFLAGS+="-DDECLSPEC=" will work to.

The wrong flac version I have also fix already on my local repo. Later I will try this with LTO to, then I upload it.

Thank you for your effort!

**Comment by mabreedlove** [comment]
Enabling LTO on ffmpeg is pretty easy.  All we have to do is add that flag in.  Normally you have to pass in "-flto -ffat-lto-objects" in CPP/CXXFLAGS and "-flto -fuse-linker-plugin" to LDFLAGS but some software bails out with it (ffmpeg will too so you have to add that flag instead).

On fontconfig, none of that works.  Anything you try to pass in through the environment or by adding it to the configure line does get passed into the configure script but it gets clobbered and ends up empty by the time the configure script is over.  I ended up just using the following to replace the line in each of the Makefiles under that directory:
```
sed -i "s|^CFLAGS\s\+=.*|& ${CFLAGS}|" Makefile **/Makefile
```
If you can find a way around it getting clobbered, it would be nice but nothing I tried worked.  This way just replaces the Makefile in the current directory as well as globbing all the subdirectory Makefiles.  CPPFLAGS and LDFLAGS pass through fine so I have a feeling this has to do with how fontconfig gathers the dependency library flags.

For LTO, don't bother trying with gnutls.  It causes a segfault while linking.

**Comment by jb-alvarado** [comment]
By me something goes wrong when I try to enable LTO. I get this:

```
[...]
CC      ffprobe.o
AR      libavdevice/libavdevice.a
AR      libavfilter/libavfilter.a
AR      libavformat/libavformat.a
AR      libavcodec/libavcodec.a
AR      libpostproc/libpostproc.a
AR      libswresample/libswresample.a
AR      libswscale/libswscale.a
AR      libavutil/libavutil.a
LD      ffmpeg_g.exe
LD      ffplay_g.exe
LD      ffprobe_g.exe
D:\_System\mingw64_Januar2015\msys64\tmp\cc1irlK0.ltrans0.ltrans.o:cc1irlK0.ltrans0.o:(.text.startup+0x39): undefined reference to `av_log_set_flags'
D:\_System\mingw64_Januar2015\msys64\tmp\cc1irlK0.ltrans0.ltrans.o:cc1irlK0.ltrans0.o:(.text.startup+0xfb): undefined reference to `av_register_all'
D:\_System\mingw64_Januar2015\msys64\tmp\cc1irlK0.ltrans0.ltrans.o:cc1irlK0.ltrans0.o:(.text.startup+0x100): undefined reference to `avformat_network_init'
[...]
```
And many more from that errors.

**Comment by jb-alvarado** [comment]
To fontconfig: maybe it works when you run "make CFLAGS+=${CFLAGS}"?

**Comment by mabreedlove** [comment]
For ffmpeg, make sure you're just using the --enable-lto flag and not passing in anything LTO-related in through CFLAGS/CXXFLAGS/LDFLAGS or it'll break it.  Their configure script handles all of that on its own.  If you're already doing this, mind adding "--trace" to your make compile line and copying in some of it?

**Comment by mabreedlove** [comment]
Under the mp4box build within gpac, I've modified things to get around a hiccup in the configure script:
```
	if [[ $compile == "true" ]]; then
		if [ -f $LOCALDESTDIR/bin-video/MP4Box.exe ]; then
			rm $LOCALDESTDIR/bin-video/MP4Box.exe
			make uninstall
			make distclean
		fi
		
		./configure --build=$targetBuild --host=$targetHost --target-os=MINGW32 --prefix=$LOCALDESTDIR --static-mp4box --enable-static-bin --use-ffmpeg=no --use-png=no --disable-ssl --enable-depth --extra-cflags="${CFLAGS}"
```

1.  I had to change the "make clean" to "make distclean" because the directory was only clearing out object files and leaving the config's from the prior build."

2.  I found and added the "--target-os=MINGW32" flag to the configure command.  Previously, the script would run "uname -s" which yields MINGW64 and would not match the configuration section.  Because it failed to match, ".so" shared libraries were just being generated instead of the normal .dlls and it also removed the requirement of passing in the extra libs since those are both defined in that section.

3.  No clue what -"-extra-depth" does but it sounded cool so I added it.  As for the "--extra-cflags" this is to get around the configuration script not detecting some of the libraries we've manually built as well as letting optimization flags get passed in.  I've included the differences between the two below:

```
** Extra Libraries used **
SpiderMonkey: no
FreeType: system
JPEG: no
- OpenJPEG: no
+ OpenJPEG: system
PNG: no
- MAD: no
+ MAD: system
FAAD: no
XVID: system
FFMPEG: no
Xiph OGG: system
Platinum UPnP: no
AVCap: no
Xiph Vorbis: system
- Xiph Theora: no
+ Xiph Theora: system
- A52 (AC3): no
+ A52 (AC3): system
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no
```

Here's a listing of what I've been able to optimize and their before and after sizes.  If the file isn't listed then it either came out the exact same size or I haven't finished it yet:

```
3.0M 2.8M /local64/bin-global/certtool.exe
3.0M 2.8M /local64/bin-global/danetool.exe
248K 236K /local64/bin-global/dcadec.exe
 52K  48K /local64/bin-global/extract_dca.exe
256K 260K /local64/bin-global/extract_j2k_from_mj2.exe
1.4M 1.3M /local64/bin-global/fc-cache.exe
1.4M 1.3M /local64/bin-global/fc-cat.exe
1.4M 1.3M /local64/bin-global/fc-list.exe
1.4M 1.3M /local64/bin-global/fc-match.exe
1.4M 1.3M /local64/bin-global/fc-pattern.exe
1.4M 1.3M /local64/bin-global/fc-query.exe
1.4M 1.3M /local64/bin-global/fc-scan.exe
1.4M 1.3M /local64/bin-global/fc-validate.exe
232K 216K /local64/bin-global/file.exe
148K 140K /local64/bin-global/fribidi.exe
3.0M 2.8M /local64/bin-global/gnutls-cli.exe
2.9M 2.8M /local64/bin-global/gnutls-cli-debug.exe
2.9M 2.8M /local64/bin-global/gnutls-serv.exe
516K 524K /local64/bin-global/mj2_to_frames.exe
920K 796K /local64/bin-global/mpicalc.exe
2.9M 2.7M /local64/bin-global/ocsptool.exe
2.8M 2.7M /local64/bin-global/psktool.exe
2.8M 2.7M /local64/bin-global/srptool.exe
2.6M 1.7M /local64/bin-global/wxrc.exe
2.7M 1.7M /local64/bin-global/xmlcatalog.exe
2.7M 2.5M /local64/bin-global/xmllint.exe

140K 136K /local64-old/bin-audio/a52dec.exe
 52K  48K /local64-old/bin-audio/extract_a52.exe
188K 184K /local64-old/bin-audio/faac.exe
700K 660K /local64-old/bin-audio/fdkaac.exe
712K 704K /local64-old/bin-audio/flac.exe
432K 428K /local64-old/bin-audio/metaflac.exe
292K 264K /local64-old/bin-audio/opusdec.exe
736K 640K /local64-old/bin-audio/opusenc.exe
 92K  76K /local64-old/bin-audio/opusinfo.exe
3.7M 3.6M /local64-old/bin-audio/play.exe
3.7M 3.6M /local64-old/bin-audio/rec.exe
3.7M 3.6M /local64-old/bin-audio/sox.exe
3.7M 3.6M /local64-old/bin-audio/soxi.exe
212K 236K /local64-old/bin-audio/speexdec.exe
280K 292K /local64-old/bin-audio/speexenc.exe

844K 836K /local64/bin-video/cacaclock.exe
1.1M 1.1M /local64/bin-video/cacademo.exe
856K 820K /local64/bin-video/cacafire.exe
840K 824K /local64/bin-video/cacaplay.exe
856K 832K /local64/bin-video/cacaview.exe
856K 824K /local64/bin-video/img2txt.exe
344K 308K /local64/bin-video/kvazaar.exe
3.4M 3.6M /local64/bin-video/MP4Box.exe [size due to additional library support]
2.8M 2.7M /local64/bin-video/rtmpdump.exe
2.8M 2.7M /local64/bin-video/rtmpgw.exe
2.8M 2.7M /local64/bin-video/rtmpsrv.exe
2.8M 2.7M /local64/bin-video/rtmpsuck.exe
2.9M 1.3M /local64/bin-video/vpxdec.exe
3.3M 2.8M /local64/bin-video/vpxenc.exe
556K 524K /local64/bin-video/xavs.exe
```

**Comment by jb-alvarado** [comment]
Hi Matt, sorry the next days I have not much time to look truth. When you want I can add you to the project, then you can also push changes to the repo. 
But lto in in ffmpeg don't run here at the moment. Don't know why.

**Comment by mabreedlove** [comment]
That might be a good idea.  There are maybe 4 or so packages out of date that I've updated as well as  a couple bugs.  Some are small like the "rm -rf flac-1.3.0" line despite us being on 1.3.1 so you can't refresh the build but I already have patches for all the updates and those small cases.  I've changed a lot of "make clean" to "make distclean" when supported too since make clean just removes object files mostly.  I'd also like to put something into place so that if you've set deleteSource to no, then it'll leave the actual archives on-disk as well instead of downloading them each time.  That may spare us some time on rebuilds.

**Comment by jb-alvarado** [comment]
I have add you now, Matt, as a "collaborators". I think now you can make changes, and push them to the repo to.

**Comment by jb-alvarado** [comment]
Ah - the weekend I also though, maybe is better when we put out the pacman update and give the script a fixed download link. Then we have more control over the msys2 and the mingw libs. I have not try it that this works, but I will.

**Comment by wiiaboo** [comment]
Same errors when I tried enabling LTO now. I assume it's a mingw problem.
