### ISSUE TITLE
We can no longer compile X264 (yasm doesn't work, needs minimum NASM v2.13)

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#520]
Building 8-bit x264 in x264-git
Running configure in x264-git
Found yasm 1.3.0
**Minimum version is nasm-2.13**
If you really want to compile without asm, configure with --disable-asm.
This is required for other packages, so this script will exit.
  Creating diagnostics file in x264-git

Attach K:\Mingw643\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

**Comment by wiiaboo** [comment]
1 - it's clamped to a commit before so it shouldn't error
2 - it's been reported already in the only other open issue and it's been updated in upstream's PKGBUILDs so we're waiting for the package to be updated.
