### ISSUE TITLE
LibreSSL 2.5.4 needs more time than 32 bit

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#522]
Building libressl for x86 fails due to short datetime type (max. year = 2038).

[logs.zip](https://0x0.st/EAi.zip)

```
┌ libressl-2.5.4 .......................................... [Downloaded]
├ Running extract...
sed: can't read apps/openssl/Makefile.in: No such file or directory
├ Running configure...
Likely error:
checking size of time_t... 4
 ** Warning, this system is unable to represent times past 2038
 ** It will behave incorrectly when handling valid RFC5280 dates
 **
 ** You can solve this by adjusting the build flags in your
 ** mingw-w64 toolchain. Refer to README.windows for details.
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `include/Makefile.in'
```

**Comment by wiiaboo** [comment]
I'm not MinGW. I have no idea how to fix this.
Please submit these issues to libressl or MinGW or both.

**Comment by wiiaboo** [comment]
From what I read 32-bit isn't supposed to have more than 4 bytes for time_t, so this shouldn't be a breaking error, unless for some reason they obsoleted building for 32-bit. Either way, I have no idea and I don't have 32-bit mingw installed right now.

**Comment by wiiaboo** [comment]
That error you got doesn't even seem related to time_t. It looks like you're missing some file.

**Comment by wiiaboo** [comment]
Check if 2c0ebf8 fixes it.

**Comment by Vangelis66** [comment]
FWIW, I'm on Windows Vista SP2 32bit fully updated (including post EOL updates for WS2008 SP2), only the 32bit toolchain is installed and the last time I compiled a non-free win32 build of FFmpeg (--enable-openssl was included in options), LibreSSL 2.5.4 did compile without fatal errors (but took quite a long time to...).

I checked and I indeed have file `Makefile.in` inside
`./media-autobuild_suite/build/libressl-2.5.4/apps`

BTW, folder `trunk/build/libressl-2.5.4` is still there because I have `deleteSource=2` inside `media-autobuild_suite.ini`

(Sadly, 30min ago pacman downloaded and installed 20 updates to the toolchain, am currently 
in the process of assessing whether compiler is still usable on Vista...)

**Comment by LigH-de** [comment]
Sorry, seems to be an issue on one of my PC's only. Update didn't detect receiving only a 1 MB part of the archive libressl-2.5.4.tar.gz, which unpacked only a part of the whole branch, missing the apps directory and more. I wonder why, though, would expect both downloading and unpacking to return error states when the archive is truncated.

**Comment by wiiaboo** [comment]
There's no hash for libressl because it's always getting the latest release.

**Comment by LigH-de** [comment]
I rather thought of something similar to ERRORLEVEL in CMD batch...

**Comment by pat357** [comment]
The too short timer for win32 can be fixed with this:
```
        [[ $bits = 32bit ]] && E_CPP=" -D__MINGW_USE_VC2005_COMPAT" || E_CPP=""
        CPPFLAGS+="${E_CPP}" do_separate_confmakeinstall global
        do_checkIfExist
        unset E_CPP _sed sha256sum 
    fi
fi

**Comment by wiiaboo** [comment]
What?

**Comment by pat357** [comment]
It's in the included readme's how to get a proper timer in 32 bit.
I quote the README.windows:
'''
To configure and build LibreSSL for a 32-bit system, use the following
build steps:

 CC=i686-w64-mingw32-gcc CPPFLAGS=-D__MINGW_USE_VC2005_COMPAT \
 ./configure --host=i686-w64-mingw32
 make
 make check
 '''
Why this -D__MINGW_USE_VC2005_COMPAT  is needed for i686  ?
Is also explained in the README.windows.

My code works fine !

**Comment by pat357** [comment]
Maybe I should do a pull request ?

**Comment by wiiaboo** [comment]
This isn't an issue. I'd hope that by the time we reach 2038 32-bit is long dead.
