### ISSUE TITLE
doxygen can't load shared libraries in opus git

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#523]
[logs.zip](https://0x0.st/EBV.zip)

Happened right after I deleted ffmpeg and mpv gits from build due to running into #519 ... but that may be a coincidence, opus seems to have updated at the same time.

You switched to doxygen just yesterday?

**Comment by wiiaboo** [comment]
You didn't update the suite. It's been fixed hours ago.

**Comment by Vangelis66** [comment]
... I've had the same issue causing an aborted compilation last night; as instructed, this afternoon I proceeded to updating the suite to its latest version (git-d6c1455). But, silly me, I managed to mess things up right after that... 

 After firing up the updated suite, pacman informed me that I had redundant packages and asked me to remove them; I, foolishly, typed "n" and then pacman again informed me that missing packages needed to be installed, so I OKed that; another doxygen package then got installed. You can view an excerpt from the pacman dialogues [here](https://github.com/jb-alvarado/media-autobuild_suite/files/1022777/doxygen_upgrade.txt) (some Greek strings included). Thus, I ended up with two doxygen packages.

I killed the minnty console and started the suite anew, but this second time I wasn't asked by pacman to remove `mingw-w64-i686-doxygen` package (perhaps my previous "no" answer to that is saved somewhere?); additionally, in the minnty console I get: 
```
username@laptopname /trunk
$ doxygen --version
G:/Compiler-v3/media-autobuild_suite/msys32/mingw32/bin/doxygen.exe: error while loading shared libraries: libsqlite3-0.dll: cannot open shared object file: No such file or directory
```
and the suite itself again fails trying to build docs for opus-git: 
```
├ Running make...
Likely error:
make[3]: Entering directory '/build/opus-git/build-32bit/doc'
doxygen
G:/Compiler-v3/media-autobuild_suite/msys32/mingw32/bin/doxygen.exe: error while loading shared libraries: libclang.dll: cannot open shared object file: No such file or directory
make[3]: *** [Makefile:485: doxygen-build.stamp] Error 127
make[3]: Leaving directory '/build/opus-git/build-32bit/doc'
make[2]: *** [Makefile:3180: all-local] Error 2
make[2]: Leaving directory '/build/opus-git/build-32bit'
make[1]: *** [Makefile:2441: all-recursive] Error 1
make[1]: Leaving directory '/build/opus-git/build-32bit'
make: *** [Makefile:1430: all] Error 2
make failed. Check G:/Compiler-v3/media-autobuild_suite/build/opus-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```
My gut feeling is I need to force uninstall the former doxygen package, which is still interfering (?).
Any help with that, please? Will `pacman -R mingw-w64-i686-doxygen` in the minnty terminal suffice or is something more elaborate required? 
Many thanks to whoever comes to the rescue!

**Comment by wiiaboo** [comment]
```bash
source /build/media-suite_helper.sh
do_pacman_remove doxygen
```

**Comment by Vangelis66** [comment]
While I do have to thank you for your prompt reply, I'd have appreciated something a layman could understand; I did locate subroutine **do_pacman_remove** inside referenced bash script: 
```
do_pacman_remove() {
    local installed
    local pkg
    installed="$(pacman -Qqe | /usr/bin/grep "^${MINGW_PACKAGE_PREFIX}-")"
    for pkg; do
        [[ "$pkg" != "${MINGW_PACKAGE_PREFIX}-"* ]] && pkg="${MINGW_PACKAGE_PREFIX}-${pkg}"
        [[ -f /etc/pac-mingw-extra.pk ]] &&
            sed -i "/^${pkg#$MINGW_PACKAGE_PREFIX-}$/d" /etc/pac-mingw-extra.pk >/dev/null 2>&1
        /usr/bin/grep -q "^${pkg}$" <(echo "$installed") || continue
        echo -n "Uninstalling ${pkg#$MINGW_PACKAGE_PREFIX-}... "
        do_hide_pacman_sharedlibs "$pkg" revert
        if pacman -Rs --noconfirm "$pkg" >/dev/null 2>&1; then
            echo "done"
        else
            pacman -D --asdeps "$pkg" >/dev/null 2>&1
            echo "failed"
        fi
    done
    do_hide_all_sharedlibs
}
```
but I remain clueless as to what to do with that :sob: ;should I save that block of code as `do_pacman_remove.sh` and then, in minnty terminal, cd to where it's saved and type `do_pacman_remove doxygen` ? Instructions for dummies, please...

**Comment by wiiaboo** [comment]
Just copy and paste those two lines into mintty and run them.

**Comment by Vangelis66** [comment]
First of all, I was using your unedited reply from the github e-mail, which did not contain the "do this in mintty" bit; so apologies; have done as instructed: 
```
username@laptopname /trunk
$ source /build/media-suite_helper.sh
username@laptopname /trunk
$ do_pacman_remove doxygen
username@laptopname /trunk
$ doxygen --version
G:/Compiler-v3/media-autobuild_suite/msys32/mingw32/bin/doxygen.exe: error while loading shared libraries: libsqlite3-0.dll: cannot open shared object file: No such file or directory
```
but no output from minnty, doxygen --version reports an error - what next?

**Comment by wiiaboo** [comment]
`pacman -Rcs mingw-w64-{i686,x86_64}-doxygen`

**Comment by Vangelis66** [comment]
And the result of that is: 
```
username@laptopname /trunk
$ pacman -Rcs mingw-w64-{i686,x86_64}-doxygen
error: target not found: mingw-w64-x86_64-doxygen
username@laptopname /trunk
``` 
which should be OK, given that I don't have the 64bit toolchain installed, right? 
but then again, 
```
$ doxygen --version
G:/Compiler-v3/media-autobuild_suite/msys32/mingw32/bin/doxygen.exe: error while loading shared libraries: libsqlite3-0.dll: cannot open shared object file: No such file or directory
```
There's still `doxygen.exe` inside `G:\Compiler-v3\media-autobuild_suite\msys32\mingw32\bin`
I am truly sorry I'm harassing you with that, but am at a loss currently... 
I need to get the suite up and running, I want to compile ffmpeg-3.3.1 ...

**Comment by wiiaboo** [comment]
`pacman -Rcs mingw-w64-i686-doxygen` then.

**Comment by Vangelis66** [comment]
YES, that finally did it! :+1:
```
$ pacman -Rcs mingw-w64-i686-doxygen
checking dependencies...

Packages (8) mingw-w64-i686-clang-4.0.0-1  mingw-w64-i686-llvm-4.0.0-1
             mingw-w64-i686-ncurses-6.0.20170325-1
             mingw-w64-i686-readline-7.0.003-1  mingw-w64-i686-sqlite3-3.18.0-1
             mingw-w64-i686-termcap-1.3.1-2
             mingw-w64-i686-xapian-core-1~1.4.2-1
             mingw-w64-i686-doxygen-1.8.13-2

Total Removed Size:  436.62 MiB

:: Do you want to remove these packages? [Y/n] Y
:: Processing package changes...
(1/8) removing mingw-w64-i686-doxygen              [#####################] 100%
(2/8) removing mingw-w64-i686-xapian-core          [#####################] 100%
(3/8) removing mingw-w64-i686-sqlite3              [#####################] 100%
(4/8) removing mingw-w64-i686-readline             [#####################] 100%
(5/8) removing mingw-w64-i686-termcap              [#####################] 100%
(6/8) removing mingw-w64-i686-ncurses              [#####################] 100%
(7/8) removing mingw-w64-i686-clang                [#####################] 100%
(8/8) removing mingw-w64-i686-llvm                 [#####################] 100%
```
but now no doxygen is found: 
```
$ doxygen --version
bash: /mingw32/bin/doxygen: No such file or directory
```
I compile my ffmpeg with `--enable-doc`, will the suite now use 
`G:\Compiler-v3\media-autobuild_suite\msys32\usr\bin\doxygen.exe` ?

**EDIT**: After firing up the suite and an auto-rebase, I have now correctly reported: 
```
$ doxygen --version
1.8.11
```
Ricardo, I do owe you a sixpack (or two?) :love_letter:
