### ISSUE TITLE
Light FFmpeg unwanted compilation

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#526]
After my recent, self-inflicted, suite issue (see https://github.com/jb-alvarado/media-autobuild_suite/issues/523#issuecomment-303452672), I got it back up again and working, thanks to @wiiaboo's help! 

I let the suite run overnight, in the morning when I woke up there was no open minnty console, 
so at a quick glance I could tell everything went OK. Back at home this afternoon, after examining 
`trunk/build/ffmpeg-git` folder, I discovered a new subfolder named `build-light-32bit` and sized ~ 38.5MB, which was never there after previous suite invocations. Adding to that, in 
`./media-autobuild_suite/local32/opt/lightffmpeg/lib` there are compiled lib files (*.a & *.la), the whole `lightffmpeg` folder is ~ 19.1 MB in size, all these lead me to believe the suite did compile things meant for the "Light FFmpeg" version, prolonging considerably the termination of the suite; since I have `ffmpegB2=1` 
inside my suite config, why was that done? 
If this is a new, by design, change, is it documented somewhere and can it be circumvented? 
Thanks for any insight ...

**Comment by wiiaboo** [comment]
That's for x264 with lavf. It's exactly to avoid needless recompilations.

**Comment by wiiaboo** [comment]
It's not prolonging anything, it compiled FFmpeg already specifically for x264. The difference now is that it's installed to a different place.

**Comment by Vangelis66** [comment]
OK then, many thanks for your detailed explanation! :+1: And sorry for the noise caused...
