### ISSUE TITLE
Not a bug : Angle patch

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#527]
Have you seen this https://github.com/mpv-player/mpv/issues/4443 ?
Especially an adapted patch for Angle : https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/angle-0001-custom-gyp.patch#L25

Although I had no more problems since your own additional include, it might be worth to keep an eye on this.

**Comment by wiiaboo** [comment]
Yes, I do read those sometimes.

**Comment by wiiaboo** [comment]
You can just ping me in the repo next time instead of opening a useless issue in an unrelated repo.
