### ISSUE TITLE
FR: When building Win64 after Win32, update sources only once?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#529]
Some tools update often. So it is rather common than incidental that Win32 and Win64 builds differ in source versions.

_Today I built everything in Win32, then ffmpeg updated to remove support for libschroedinger in between both runs, so that the Win64 build failed._

Would it be suitable to skip source updating during the Win64 builds if it follows after a previous Win32 build, to use the same sources in both runs? That would probably also make a re-run in case of intermediate updates obsolete.

**Comment by wiiaboo** [comment]
Troublesome to implement.
I'd rather implement an option to ignore updates on 64-bit than add tons of ifs for this usecase.

**Comment by wiiaboo** [comment]
Not that hard after all, but it'll still run the update twice if the first one didn't find any update.
