### ISSUE TITLE
wxWidgets isn't compiling (again)

### ISSUE THREAD

**Issue by wiiaboo** [jb-alvarado/media-autobuild_suite#53]
So I think MinGW broke wxWidgets and mkvtoolnix now, again due to time.h stuff.

```
(if test -f utils/wxrc/Makefile ; then cd utils/wxrc && make all ; fi)
make[1]: Entering directory '/build64/wxWidgets-3.0.2/utils/wxrc'
x86_64-w64-mingw32-g++ -o wxrc.exe wxrc_wxrc.o    -L/build64/wxWidgets-3.0.2/lib  -L/local64/lib -pipe -static -static-libgcc -static-libstdc++    -lwx_baseu_xml-3.0 -lexpat -lwx_baseu-3.0     -lwxregexu-3.0  -L/local64/lib -pipe -static -static-libgcc -static-libstdc++   -lz -lrpcrt4 -loleaut32 -lole32 -luuid -llzma -ljbig -lwinspool -lwinmm -lshell32 -lcomctl32 -lcomdlg32 -ladvapi32 -lwsock32 -lgdi32 -loleacc  -lz -lrpcrt4 -loleaut32 -lole32 -luuid -llzma -ljbig -lwinspool -lwinmm -lshell32 -lcomctl32 -lcomdlg32 -ladvapi32 -lwsock32 -lgdi32 -loleacc
E:/ab/build64/wxWidgets-3.0.2/lib\libwx_baseu_xml-3.0.a(xmllib_xml.o):xml.cpp:(.text+0x5d0): multiple definition of `asctime_r(tm const*, char*)'
wxrc_wxrc.o:wxrc.cpp:(.text+0x30): first defined here
E:/ab/build64/wxWidgets-3.0.2/lib\libwx_baseu-3.0.a(baselib_appbase.o):appbase.cpp:(.text+0x4f0): multiple definition of `asctime_r(tm const*, char*)'
wxrc_wxrc.o:wxrc.cpp:(.text+0x30): first defined here
[...]
E:/ab/build64/wxWidgets-3.0.2/lib\libwx_baseu-3.0.a(baselib_base64.o):base64.cpp:(.text+0x0): multiple definition of `asctime_r(tm const*, char*)'
wxrc_wxrc.o:wxrc.cpp:(.text+0x30): first defined here
E:/ab/build64/wxWidgets-3.0.2/lib\libwx_baseu-3.0.a(baselib_ipcbase.o):ipcbase.cpp:(.text+0x60): multiple definition of `asctime_r(tm const*, char*)'
wxrc_wxrc.o:wxrc.cpp:(.text+0x30): first defined here
E:/ab/build64/wxWidgets-3.0.2/lib\libwx_baseu-3.0.a(baselib_timercmn.o):timercmn.cpp:(.text+0x300): multiple definition of `asctime_r(tm const*, char*)'
wxrc_wxrc.o:wxrc.cpp:(.text+0x30): first defined here
collect2.exe: error: ld returned 1 exit status
Makefile:118: recipe for target 'wxrc.exe' failed
make[1]: *** [wxrc.exe] Error 1
make[1]: Leaving directory '/build64/wxWidgets-3.0.2/utils/wxrc'
Makefile:16136: recipe for target 'wxrc' failed
make: *** [wxrc] Error 2
```

**Comment by jb-alvarado** [comment]
Have you try to remove the -D_POSIX Flag? I hope is now the last time that they change this things mingw-w64... I try to take a look on it in the evening.

**Comment by wiiaboo** [comment]
Seems to fix it. mkvtoolnix still needs the patch.
Haven't tried ffmpeg without it yet.
Also, file/magic needs recompilation. It's also at 5.22.

**Comment by mabreedlove** [comment]
No, this is a result of stupidity on the part of mingw-w64.  I'm getting tired of this to be honest.  Once again, they have changed things:  http://sourceforge.net/p/mingw-w64/mailman/message/33212333/

Make sure you're completely up-to-date with pacman -Syyu as they just pushed a slurry of revision changes out.  Any libraries linked in packages that fail with this error will need to be rebuilt.  I haven't tested the fix for everything but I've also been experiencing it within x264 when linking to the ffmpeg libs.  Make sure when building x264 that ffmpeg's libs are actually linked in because otherwise they will fail to be detected in the configuration script (like i'm experiencing).

jb: this may be why you are also getting lto failures from ffmpeg also.

**Comment by jb-alvarado** [comment]
Yes this can be, Matt. They have fix this issue I think. But maybe we have now already a mess up in our actual build...  
The weekend I am not here and the bing of next week I have also a lot to work, so sorry when I am not always response directly.

**Comment by mabreedlove** [comment]
Right now, I'm going through and rebuilding everything against the latest crt-git and headers-git along with modifying parts of the script that build under LTO successfully.  I'll report back if everything is ok and in the least, I can commit a modified script that you can test with.  I did this yesterday but some of the libraries were compiled from the previous packages and some compiled with the new one which led me to that mingw-w64 post.

**Comment by mabreedlove** [comment]
wxWidgets is building for me properly.  I've also removed the -D_POSIX flag from it as well.  I'm not to the point where I've tested ffmpeg and such without it yet but I'm assuming the same can be said for it as well.

**Comment by wiiaboo** [comment]
Just finished compiling ffmpeg without -D_POSIX. The storm is over.

**Comment by jb-alvarado** [comment]
NIce, thank you for trying. I will update later the source.
