### ISSUE TITLE
FFmbc building broken

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#531]
┌ FFmbc git ......................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error:
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c: In function 'vf_next_put_image':
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c:622:16: error: 'AVFilterBuffer {aka struct AVFilterBuffer}' has no member named 'please_use_av_free'
     picref->buf->please_use_av_free= av_free;
                ^~
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c: In function 'init':
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c:768:36: warning: passing argument 2 of 'm->vf.info->vf_open' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     if(m->vf.info->vf_open(&m->vf, args)<=0){
                                    ^~~~
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c:768:36: note: expected 'char *' but argument is of type 'const char *'
make: *** [/build/FFmbc-git/common.mak:47: libavfilter/vf_mp.o] Error 1
make failed. Check E:/AB-Suite/build/FFmbc-git/build-64bit/ab-suite.make.log
This isn't required for anything so we can move on.

**Comment by wiiaboo** [comment]
> ffmbc (git) **(unsupported)**

This means I don't really care.

**Comment by wiiaboo** [comment]
Maybe fixed.

**Comment by BlackScreen** [comment]
Hm. Thanks for trying to fix the problem, but sadly it still does not work:

┌ FFmbc git ......................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error:
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c: In function 'vf_next_put_image':
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c:622:16: error: 'AVFilterBuffer {aka struct AVFilterBuffer}' has no member named 'please_use_av_free'
     picref->buf->please_use_av_free= av_free;
                ^~
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c: In function 'init':
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c:768:36: warning: passing argument 2 of 'm->vf.info->vf_open' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     if(m->vf.info->vf_open(&m->vf, args)<=0){
                                    ^~~~
E:/AB-Suite/build/FFmbc-git/libavfilter/vf_mp.c:768:36: note: expected 'char *' but argument is of type 'const char *'
make: *** [/build/FFmbc-git/common.mak:47: libavfilter/vf_mp.o] Error 1
make failed. Check E:/AB-Suite/build/FFmbc-git/build-64bit/ab-suite.make.log
This isn't required for anything so we can move on.

**Comment by wiiaboo** [comment]
No idea then. Let the author know. I'm not spending any time fixing this.

**Comment by BlackScreen** [comment]
Ok. Thanks!

**Comment by himslm01** [comment]
Original source code fixed now.

**Comment by BlackScreen** [comment]
Yes, thanks for the fix! :+1:
