### ISSUE TITLE
new fontconfig v2.12.3 fails to build

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#532]
Fails to build 64-bit version:
```
In file included from ../../src/fcobjs.c:33:0:
fcobjshash.gperf:28:1: error: conflicting types for 'FcObjectTypeHash'
../../src/fcobjs.c:28:1: note: previous declaration of 'FcObjectTypeHash' was here
 FcObjectTypeHash (register const char *str, register FC_GPERF_SIZE_T len);
 ^~~~~~~~~~~~~~~~
In file included from ../../src/fcobjs.c:33:0:
fcobjshash.gperf:172:1: error: conflicting types for 'FcObjectTypeLookup'
../../src/fcobjs.c:31:1: note: previous declaration of 'FcObjectTypeLookup' was here
 FcObjectTypeLookup (register const char *str, register FC_GPERF_SIZE_T len);
 ^~~~~~~~~~~~~~~~~~
................................

**Comment by wiiaboo** [comment]
And? The suite is still on 2.12.1.

**Comment by pat357** [comment]
If that is your policy, ok, now I know at least.
It's really a pitty though !

**Comment by wiiaboo** [comment]
You're right. Supporting things that are not in the suite isn't in my policy. At least until you pay me to do so.

My free time is to do things I want. And supporting other people's broken code is not among the list of things I want to waste my free time on.

If it's a pity that I don't slave myself to your issues, then great, gtfo.
