### ISSUE TITLE
Latest Version (2017.05.31) fails to build "make"

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#533]
[logs.zip](https://0x0.st/6uP.zip)

I just downloaded the latest version and ran it and got the following error:

Starting 64bit compilation of global tools
freetype2 2.8.0 ........................................... [Up-to-date]
Running git update for fontconfig...
┌ fontconfig git .................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
  GEN      fcblanks.h
Traceback (most recent call last):
  File "../../fc-blanks/fc-blanks.py", line 15, in <module>
    from six.moves import range
ImportError: No module named six.moves
make[2]: *** [Makefile:593: fcblanks.h] Error 1
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/fc-blanks'
make[1]: *** [Makefile:579: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-64bit'
make: *** [Makefile:463: all] Error 2
make failed. Check C:/media-autobuild_suite/build/fontconfig-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

**Comment by wiiaboo** [comment]
Should be fixed now.
