### ISSUE TITLE
libmediainfo cmake error

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#534]
[logs.zip](https://0x0.st/6uW.zip)

I installed the version you just updated and it fixed my previous problem, but now I have a new problem:

libzen git ................................................ [Up-to-date]
  Running git update for libmediainfo...
┌ libmediainfo git ..................................... [Updates found]
├ Running uninstall...
├ Running cmake...
Likely error:

  but not all the files it references.

Call Stack (most recent call first):
  C:/media-autobuild_suite/local64/lib/cmake/zenlib/ZenLibConfig.cmake:28 (include)
  CMakeLists.txt:37 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/media-autobuild_suite/build/libmediainfo-git/build-64bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check C:/media-autobuild_suite/build/libmediainfo-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.

**Comment by wiiaboo** [comment]
That's weird. Can you check if local64/lib/libzen.a does in fact not exist?

**Comment by myfreeer** [comment]
Try to remove all `libzen` related stuff from `local64/lib` to force rebuilding it.

**Comment by Metaphorce812** [comment]
The libzen.a file was there. I deleted it, installed the latest build of MABS, and this time it successfully built libmediainfo. Thanks!

**Comment by LigH-de** [comment]
Running into the same issue, building for Win32 first. Also after deleting `build/libzen-git` and `build/libmediainfo-git` before trying again.

```
CMake Error at H:/dev/mabs/local32/lib/cmake/zenlib/ZenLibTargets.cmake:69 (message):
  The imported target "zen" references the file

     "/local32/lib/libzen.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "H:/dev/mabs/local32/lib/cmake/zenlib/ZenLibTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  H:/dev/mabs/local32/lib/cmake/zenlib/ZenLibConfig.cmake:28 (include)
  CMakeLists.txt:37 (find_package)
```

The supposedly missing file `/local32/lib/libzen.a` does exist, was built fresh. 

[logs.zip](https://0x0.st/I8t.zip) #1

After deleting it, a missing file was detected, libzen was rebuilt, but same error while building libmediainfo right after.

[logs.zip](https://0x0.st/I8Y.zip) #2

**Comment by wiiaboo** [comment]
Maybe CMake doesn't like Unix paths.

**Comment by LigH-de** [comment]
I reverted patch [a91ee08](https://github.com/jb-alvarado/media-autobuild_suite/commit/a91ee0812bff6ee7bb4347587d16cc66dea3b52c) manually, deleted `/local32/lib/libzen.a` to force a rebuild.

Compiling `libzen-git`, `libmediainfo-git`, and `mediainfo-git` passed.

**Comment by wiiaboo** [comment]
Weird then. The bug seems to be older than that commit.

**Comment by LigH-de** [comment]
So maybe different reasons (and different errors) causing the same error message? This seems to be a "catch them all" type of message for several reasons of errors.
