### ISSUE TITLE
x265 12bit CMake Error

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#535]
[logs.zip](https://0x0.st/6_j.zip)

I downloaded and ran the latest media-autobuild_suite today at 4:36PM and got the following error:

┌ x265 hg .............................................. [Updates found]
├ Building 12-bit lib for multilib...
├ Running cmake...
Likely error:
-- Found assembler: C:/media_AB_suite/msys64/mingw64/bin/yasm.exe
-- Looking for strtok_r
-- Looking for strtok_r - found
CMake Error at CMakeLists.txt:541 (list):
  list index: 1 out of range (-1, 0)

-- Configuring incomplete, errors occurred!
See also "C:/media_AB_suite/build/x265-hg/build-64bit/12bit/CMakeFiles/CMakeOutput.log".
See also "C:/media_AB_suite/build/x265-hg/build-64bit/12bit/CMakeFiles/CMakeError.log".
cmake failed. Check C:/media_AB_suite/build/x265-hg/build-64bit/12bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.

**Comment by wiiaboo** [comment]
Did you try deleting x265-hg and running the suite again?

**Comment by wiiaboo** [comment]
I can't reproduce this, so I'll assume deleting the directory fixed it.
