### ISSUE TITLE
SDL2 : conditions to (re)build sdl2

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#536]
For SDL2 you have:
```
if { [[ $ffmpeg != "no" ]] && ! disabled sdl2; } ||
    { [[ $mpv != "no" ]] && mpv_enabled sdl2; } || [[ $daala = y ]] &&
    do_pkgConfig "sdl2 = 2.0.5"; then
```
In this case, if  daala = n, then the block do_pkgConfig "sdl2 = 2.0.5" will be ignored.
Remember that the && has a higher priority then ||,  similar to algebra where the
multiplication has a higher priority than summing.
The above expression in simple algebra (&& = . and  || = + )
```
     (a . b + c . d + e) . f     
```

I think this is more what you mean:
```
if  {  [[ $ffmpeg != "no" ]] && ! disabled sdl2 ||
       [[ $mpv != "no" ]] && mpv_enabled sdl2 || [[ $daala = y ]]; } &&
       do_pkgConfig "sdl2 = 2.0.5"; then

agree ?

**Comment by wiiaboo** [comment]
Sure, learn to make a pull request, please.

**Comment by wiiaboo** [comment]
And no, that's wrong:
```bash
$ [[ y = y ]] || [[ n = n ]] || [[ m = m ]] && echo y
y
$ [[ y != y ]] || [[ n = n ]] || [[ m = m ]] && echo y
y
$ [[ y != y ]] || [[ n = n ]] || [[ m != m ]] && echo y
y
$ [[ y = y ]] || [[ n != n ]] || [[ m != m ]] && echo y
y
```

**Comment by pat357** [comment]
I don't see your point why I should be wrong.
Please explain.
Of course your 4 examples all give a "y". They should as long as one of the || (or'ed) conditions is true.
What part of my claim is not true ??

**Comment by wiiaboo** [comment]
> In this case, if daala = n, then the block do_pkgConfig "sdl2 = 2.0.5" will be ignored.

The final && always runs as long as one of them is true. That's what I meant by you being wrong. But I still made it explicit anyway.
