### ISSUE TITLE
libbluray fails org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Murmur** [jb-alvarado/media-autobuild_suite#537]
(Windows 10/64bit)

I run a git pull to update most recent files, media-autobuild_suite.bat script fails on libbluray compilation.

**Java class version numbers** J2SE8=52, J2SE7=51 

I have two JDK folders, jdk7 is current version in a winregistry.
C:\Program Files\Java\jdk1.7.0_75
C:\Program Files\Java\jdk1.8.0_112

WinRegistry
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit
CurrentVersion=1.7
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\1.7
JavaHome=C:\Program Files\Java\jdk1.7.0_75

Do anyone has idea how to solve this problem, I cannot move or rename JDK1.8 folder Windows is locking a folder. Helper script function `build/media-suite_helper.sh/get_java_home()` makes a registry lookup and should pick currentversion=1.7 Java. 

I cannot verify this in any of the logfiles to see if this is the case. Maybe some of the scripts go wild and use JDK1.7 and JDK1.8 mixed environment.

```
dvdnav git ................................................ [Up-to-date]
  Running git update for libbluray...
â”Œ libbluray git ........................................ [Files missing]
â”œ Running ant-diagnostics...
Likely error:
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Exception in thread "main" ant-diagnostics failed. Check C:/projects/media-autobuild_suite/media-autobuild_suite/build/libbluray-git/ab-suite.ant-diagnostics.log
This is required for other packages, so this script will exit. Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/6pO.zip
Copy and paste [logs.zip](https://0x0.st/6pO.zip) in the GitHub issue.

CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ant -diagnostics
java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : 
Unsupported major.minor version 52.0 at java.lang.ClassLoader.defineClass1(Native Method)

```

**Comment by wiiaboo** [comment]
I honestly have no idea. I think I've only tested with jdk-8u.
If Windows is locking the folder, just restart and clean that up.

I could not  use java stuff if the version isn't 1.8.

**Comment by Murmur** [comment]
Thanks your confirmation JDK8 can be used for libbluray compilation gave me an idea. I manually edited a JavaSDK winregistry `CurrentVersion=1.8` and rerun a build. Everything is fine now, should have seen this trick before posting a bug report. I have some of the apps requiring default jdk 1.7 but need to study forcing them to use an explicit jdk_home path.
