### ISSUE TITLE
mintty error when updating suite / executing suite

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#539]
Since a few updates of msys I always get an error when trying to update the suite or execute it.
I get the error: "Font not found, using system substitute: Consolas". I can then proceed with clicking "I see".
In the mintty window there also is an error at the top: "put: unknown terminal "xterm-256color"
Is this an error that will get fixed upstream? Probably not your error, right?

**Comment by wiiaboo** [comment]
No idea. Just delete .minttyrc inside your /msys64/home/<user> directory.
