### ISSUE TITLE
build stops at building anglelib

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#541]
[logs.zip] (https://0x0.st/6gR.zip)

**Comment by wiiaboo** [comment]
Should be averted by 98d1afb3230e553aa8bbd1652a78f1da7d99a9e0.

**Comment by wiiaboo** [comment]
And apparently static angle seems broken since it needs D3DCompiler_43.dll which isn't anywhere in Win10, at least.

**Comment by BlackScreen** [comment]
Yes, the fix works. Thanks!
