### ISSUE TITLE
mintty-system not installed successfully

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#542]
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\protocol': No such file or directory
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\services': No such file or directory
/usr/bin/cp: cannot stat 'C:\Windows\system32\drivers\etc\networks': No such file or directory
/local64/etc/profile2.local: line 37: /etc/profile.d/perlbin.sh: No such file or directory
/local32/etc/profile2.local: line 37: /etc/profile.d/perlbin.sh: No such file or directory

        Starting 32bit compilation of all tools
/build/media-suite_helper.sh: line 583: dos2unix: command not found
Imported FFmpeg options from ffmpeg_options.txt
License: gplv3
/build/media-suite_helper.sh: line 583: dos2unix: command not found
Imported mpv options from mpv_options.txt

        Starting 32bit compilation of global tools
freetype2 2.8.0 ........................................ [Not installed]
â”œ freetype-2.8 ....................................... [File up-to-date]
â”œ Running extract...
/build/media-suite_helper.sh: line 53: cd: freetype-2.8: No such file or directory
  Creating diagnostics file...
/build/media-suite_helper.sh: line 1003: 7za: command not found

Failed changing to directory freetype-2.8.

log: https://drive.google.com/open?id=0Bw7wTtlOFiD0dUZ4TExQZ3lKMW8

**Comment by wiiaboo** [comment]
Doesn't seem like just mintty. Everything's fucking broken there.

**Comment by eltoddy** [comment]
I got the same problem, the package ucl-1.03-1-x86_64 was not getting installed from the repo. A workaround that seems to be working is fetching the package and installing it manually:

wget http://repo.msys2.org/msys/x86_64/ucl-1.03-1-x86_64.pkg.tar.xz
pacman -U ucl-1.03-1-x86_64.pkg.tar.xz

**Comment by ASopH** [comment]
It seems the  workaround runs. Thanks for your help!

**Comment by wiiaboo** [comment]
3885ca3 should workaround this.
