### ISSUE TITLE
Problem with all hg clones from bitbucket.org. 

### ISSUE THREAD

**Issue by Mitra-M** [jb-alvarado/media-autobuild_suite#546]
Some people like me have problem with hg clones from bitbucket.org.

Please see [this](https://stackoverflow.com/questions/44483533/mingwmsys2-failed-to-connect-to-bitbucket-org-network-is-unreachable).

**Request:**  would you please replace bitbucket.org clones to another addresses? 
for example , you can replace `https://bitbucket.org/multicoreware/x265` with `https://github.com/videolan/x265` in your script.

**OR** 
Find another way to solve this problem.

Thanks

**Comment by wiiaboo** [comment]
No. The github mirror is not the official repository. The commit hashes are unrelated, so versioning is useless.

If you have issues with bitbucket complain to bitbucket themselves or your network admin. Or find another mercurial mirror so the hashes are the same.

**Comment by wiiaboo** [comment]
Also, the problem is yours only, so you should find a way to solve it yourself. If your solution fixes it for yourself and doesn't break usability for others, I'd be more than welcome to accept it, of course.

**Comment by Mitra-M** [comment]
I don't think so, that am alone in this problem.
Because many of ISP providers in many countries does not support the IPv6 yet.

Anyway, thank you for your answer.

**Comment by wiiaboo** [comment]
What does ipv6 have to do with it? Bitbucket is in no way ipv6-only.

**Comment by Mitra-M** [comment]
There are issues reporting current problem to access bitbucket through https ([issue 13060](https://bitbucket.org/site/master/issues/13060/failed-to-connect-to-bitbucketorg-port-443) , [issue 12184](https://bitbucket.org/site/master/issues/12184/failed-to-connect-to-bitbucketorg-port-443) )
Please have a look at [this](https://stackoverflow.com/questions/38606443/failed-to-connect-to-bitbucket-org-port-443-network-is-unreachable/38606704?noredirect=1#comment75955866_38606704).

**Comment by wiiaboo** [comment]
You're using the wrong IP according to those pages.
Change the hosts to `104.192.143.1 bitbucket.org` or `104.192.143.3 bitbucket.org`.

**Comment by Mitra-M** [comment]
I tried all of them. (104.192.143.1 , 104.192.143.2 , 104.192.143.3)

**Comment by Mitra-M** [comment]
It works only for inux, and other UNIX-based operating systems.

**Comment by wiiaboo** [comment]
Then it really has nothing to do with ipv6 but with your network/ISP. Complain to them or just change the files for yourself. It's one line. And I'm not breaking versioning for everyone because you have a shitty ISP.

**Comment by wiiaboo** [comment]
Run `hg clone -v https://bitbucket.org/multicoreware/x265` in mintty and it'd probably have more information.

**Comment by Mitra-M** [comment]
$ hg clone -v https://bitbucket.org/multicoreware/x265
abort: error: Network is unreachable

**Comment by Mitra-M** [comment]
you said: 

> ... or just change the files for yourself ...

I know that you can not change the script for my sake, but please tell me what can I change files to solve this problem for myself.
Thanks

**Comment by wiiaboo** [comment]
You said it right at the first post. Just change `hg::https://bitbucket.org/multicoreware/x265` to `https://github.com/videolan/x265`.

**Comment by Mitra-M** [comment]
I tried to change ` hg::https://bitbucket.org/multicoreware/x265` to `https://github.com/videolan/x265` in media-suite_compile.sh once before, but did not work. That's why I mistakenly thought I should change anything else in the script.

But now I tried again , worked without error.
Thank you very much for your time.

your script is great.
