### ISSUE TITLE
Error compiling FFmbc-0.7.2

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#55]
Hi. I've try several time to compile FFmbc-0.7.2 without luck :(.
I wonder if anyone else manage to compile ffmbc.
The error message is:
"Creating config.mak and config.h...
make: *** INTERNAL: readdir: No such file or directory.  Stop.
make: *** INTERNAL: readdir: No such file or directory.  Stop.

-------------------------------------------------
Build FFmbc-0.7.2 failed...
Delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it."

All other packages compiles well.

best regards,
laurb

**Comment by nille02** [comment]
same for me

**Comment by jb-alvarado** [comment]
Have you select msys2 32 bit? Because this Problem comes from this, but I don't know why. Under msys2 64bit I had not this problem.

**Comment by laurfb** [comment]
Hi. Yes, I use 64bit. Here is my media-autobuild_suite.ini:
[compiler list]
msys2Arch=2
arch=2
free=1
ffmbc=1
ffmpegB=1
ffmpegUpdate=1
mp4box=2
mplayer=2
mpv=2
mkv=2
cores=2
deleteSource=2
strip=2
pack=1

best regards,
laurb

**Comment by nille02** [comment]
i'm 64bit only too

**Comment by jb-alvarado** [comment]
Sorry for my late response. At the moment I can not reproduce this problem, but please can you show me the config.mak file, from it?

**Comment by nille02** [comment]
Sure

https://dl.dropboxusercontent.com/u/95325704/config.mak

**Comment by jb-alvarado** [comment]
Can you please try something? When the configure is already done and the error is come up, open: common.mak and replace all "$(SRC_DIR)" with a "." . After that open the mintty shell and navigate to the folder like: cd /build64/FFmbc-* and run "make". When it works by you I can put a fix in the script. 
Thank you!

**Comment by jb-alvarado** [comment]
Or better, don't replace this variable and run "make SRC_DIR=.".

**Comment by nille02** [comment]
That works.

**Comment by jb-alvarado** [comment]
Ok it is fixed. Thank for testing and reporting!

**Comment by nille02** [comment]
make SRC_DIR=. -j $cpuCount works too

**Comment by nille02** [comment]
Mh, something still went wrong. 

LD      ffmbc_g.exe
CP      ffmbc.exe
STRIP   ffmbc.exe
make: *** INTERNAL: readdir: No such file or directory.  Schluss.
-------------------------------------------------
Build FFmbc-0.7.2 failed...
Delete the source folder under '/build64' and start again,
or if you know there is no dependences hit enter for continue it.

**Comment by jb-alvarado** [comment]
Ah... yes that can be, I will put it in the script. Thanks!
