### ISSUE TITLE
compile shared ffmpeg error !!!

### ISSUE THREAD

**Issue by wljcom** [jb-alvarado/media-autobuild_suite#550]
compile shared ffmpeg error !!!

├ Running make...
Likely error:
libavformat/wvdec.o:wvdec.c:(.text+0xd84): undefined reference to `av_packet_unref'

libavformat/wvedec.o:wvedec.c:(.text+0x62): undefined reference to `av_get_bits_per_sample'

libavformat/yop.o:yop.c:(.text+0xce): undefined reference to `av_packet_unref'

libavformat/yop.o:yop.c:(.text+0x109): undefined reference to `av_packet_unref'

libavformat/yop.o:yop.c:(.text+0x1ea): undefined reference to `av_new_packet'

libavformat/yop.o:yop.c:(.text+0x22c): undefined reference to `av_packet_unref'

libavformat/yop.o:yop.c:(.text+0x294): undefined reference to `av_shrink_packet'

libavformat/yuv4mpegdec.o:yuv4mpegdec.c:(.text+0x12c): undefined reference to `av_packet_unref'

collect2.exe: error: ld returned 1 exit status

make: *** [/build/ffmpeg-git/ffbuild/library.mak:102: libavformat/avformat-57.dll] Error 1

**Comment by wiiaboo** [comment]
I need any .def files inside `build\ffmpeg-git\build-shared-(32|64)bit`.

**Comment by wiiaboo** [comment]
Force recompilation of x265 and it should be fixed.
