### ISSUE TITLE
Decklink devices not working in builds after May 30

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#553]
I just saw, that in my latest build the usage of decklink is not possible. The last build which works is from May 30.
The error message I get is the following:
```
DeckLink drivers not installed.
[decklink @ 00000000027b3a40] Could not create DeckLink iterator
DeckLink HD Extreme 3D: Generic error in an external library
```
Any ideas? Or is this an error of FFmpeg?

**Comment by wiiaboo** [comment]
I haven't the faintest idea. Try asking FFmpeg and Decklink.

**Comment by BlackScreen** [comment]
FYI: Updating the driver to the newest version (10.9.3) did the trick. Weird that all other updates since then did not break the functionality. I had 10.6.4 installed.

**Comment by wiiaboo** [comment]
Makes sense.

**Comment by tenisak** [comment]
I'm trying to compile FFmpeg, but I do not know what settings to use. My last attempt failed. This may be a my wrong setting. I need to build as zeranoe but with the `--decklink-enable` parameter. Could you please advise me what to do?
