### ISSUE TITLE
broken characters,.. probably some code page issues

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#554]
Deleted my old build checkout with all it's files and made a new checkout a few days ago and since then there are some broken character which might be due to some code page issue:
it looks like this:
> â”Œ speex git ......................................... [Recently updated]
â”œ Running autoreconf...
â”œ Running configure...
â”œ Running make...
â”œ Stripping...
â”” speex-git .................................................. [Updated]
  Running git update for flac...
â”Œ flac git ............................................. [Updates found]
â”œ Running autogen...
â”œ Running uninstall...
â”œ Running configure...

isn't really anything problematic since the scripts runs as it should, but I thought I should report to let you know there might be some issue.

**Comment by wiiaboo** [comment]
mintty's default font isn't unicode. Just change it to something else, like Consolas.
