### ISSUE TITLE
sed: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#555]
> /build/media-suite_update.sh: line 85: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_update.sh: line 86: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_update.sh: line 87: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_update.sh: line 88: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_update.sh: line 89: /usr/bin/sed: cannot execute binary file: Exec format error
Starting 32bit compilation of all tools
/build/media-suite_helper.sh: line 607: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_helper.sh: line 607: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_helper.sh: line 610: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_helper.sh: line 610: /usr/bin/sed: cannot execute binary file: Exec format error
Imported default FFmpeg options from .bat
License: gplv3
/build/media-suite_helper.sh: line 791: /usr/bin/sed: cannot execute binary file: Exec format error
/build/media-suite_helper.sh: line 791: /usr/bin/sed: cannot execute binary file: Exec format error
Imported default mpv options from .bat

see:  [logs.zip](https://0x0.st/U_Y.zip)

**Comment by wiiaboo** [comment]
The logs are empty, lol. That looks like a completely screwed installation.

**Comment by Selur** [comment]
strange,... was a clean install,.. deleted evertyhing before I did a git clone,..
-> will do it anew and report back in a day or so since compiling the whole setup takes ages,..

**Comment by wiiaboo** [comment]
Is that a 32 or 64-bit OS?
That error shows if you install the wrong Msys bitness which could mean my check is wrong.

**Comment by Selur** [comment]
64bit os, but can't test any more, deleted the whole thing and restarting and building it anew.

**Comment by wiiaboo** [comment]
fwiw, i've just tried a fresh build root and it worked fine, so it doesn't seem something wrong with the script if everything managed to update/install fine.

**Comment by Selur** [comment]
with the new install first non-fatal error I got:

> â”Œ ffmpeg git ........................................ [Recently updated]
â”œ Changing options to comply to gplv3...
â”œ Compiling static FFmpeg...
â”œ Running configure...
â”œ Running make...
â”œ Running install...
â”œ Stripping...
â”” ffmpeg-git ................................................. [Updated]
  Running svn clone for mplayer...
â”Œ mplayer svn ....................................... [Recently updated]
â”œ Running configure...
â”œ Running install...
Likely error:
X86ASM  libavcodec/x86/vp9lpf.o
X86ASM  libavcodec/x86/vp9lpf_16bpp.o
X86ASM  libavcodec/x86/vp9mc.o
X86ASM  libavcodec/x86/vp9mc_16bpp.o
X86ASM  libavcodec/x86/xvididct.o
AR      libavcodec/libavcodec.a
H:\media-autobuild_suite\msys64\mingw32\bin\ar.exe: libavcodec/x86/aacencdsp.o:                                      No such file or directory
make[1]: *** [ffbuild/library.mak:21: libavcodec/libavcodec.a] Error 1
make[1]: Leaving directory '/build/mplayer-svn/ffmpeg'
make: *** [Makefile:740: ffmpeg/libavcodec/libavcodec.a] Error 2
install failed. Check H:/media-autobuild_suite/build/mplayer-svn/ab-suite.instal                                     l.log
This isn't required for anything so we can move on.

**Comment by wiiaboo** [comment]
mplayer is always broken, don't bother telling me about it.
And change the font of mintty to something that's not Lucida Console.
