### ISSUE TITLE
Fails when building libmysofa

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#559]
[logs.zip](https://0x0.st/0z7.zip)
I updated to the most recent version of media-autobuild_suite and tried deleting the build/libmysofa-git folder, but I keep getting the same error.

**Comment by wiiaboo** [comment]
Probably to mingw cmake being broken. Should be fixed as soon as it's updated.

**Comment by wiiaboo** [comment]
Using make instead of ninja fixes it for me.

**Comment by Metaphorce812** [comment]
@wiiaboo How do I set it to use make instead of ninja? And is there a way to revert to the previous version of mingw?

**Comment by wiiaboo** [comment]
I pushed a fix just now.

**Comment by Metaphorce812** [comment]
Thanks, that fixed it!
