### ISSUE TITLE
x265 compilation error

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#560]
â”Œ x265 hg ........................................... [Recently updated]
â”œ Building 12-bit lib for multilib...
â”œ Running cmake...
Likely error:

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
See also "D:/media-ab_suite/build/x265-hg/build-32bit/12bit/CMakeFiles/CMakeOutput.log".
See also "D:/media-ab_suite/build/x265-hg/build-32bit/12bit/CMakeFiles/CMakeError.log".
cmake failed. Check D:/media-ab_suite/build/x265-hg/build-32bit/12bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/0iK.zip
Copy and paste [logs.zip](https://0x0.st/0iK.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Same as #559
