### ISSUE TITLE
mintty error: "Font not found"

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#562]
I don't think this is actually anything wrong with media-autobuild_suite's code, but I was still wondering if you could help me. When msys and/or mingw was automatically updated when I ran media-autobuild_suite this morning, it messed up the terminal. Now I get a pop-up window labeled "mintty" with the error "Font not found, using system substitute: Courier New"
And then when media-autobuild_suite is running, in the terminal text appears like this:
```
â”Œ libmediainfo git ..................................... [Updates found]
â”œ Running uninstall...
â”œ Running cmake...
â”œ Running install...
â”œ Stripping...
â”” libmediainfo-git
```
whereas before the update the terminal would show lines on the left margin instead of those weird characters. 
I did notice that the version of mintty being used is 2.7.7, while [the latest version is 2.7.8](https://github.com/mintty/mintty). But I don't know if I could manually update it and/or if that would fix the problem.
I'm running Windows 7 SP1 x64 by the way.

**Comment by wiiaboo** [comment]
Maybe msys/mintty will eventually fix their regressions. I'll just change it back to Consolas and stop caring about the warnings.

**Comment by BlackScreen** [comment]
This config works for me - I do not get any errors now when opening mintty. The strange font problems with the lines still exist.
```
Locale=en_US
Charset=UTF-8
Font=Consolas
Columns=120
Rows=30
BoldAsFont=-1
```

**Comment by wiiaboo** [comment]
I don't know anymore. It's working fine for me on several installations.

**Comment by Metaphorce812** [comment]
@BlackScreen 
I did a few things and now it's displaying correctly. Unfortunately I don't remember exactly what changes I made, let alone which one fixed the issue. But here's my best guess. I deleted all the files with "mintty" in the name inside media-autobuild-suite's directory. Then I ran the suite again. I also changed mintty's settings to the following:
`Locale=en_US
Charset=UTF-8
Language=*
Term=xterm
Font=Consolas
BoldAsFont=-1`
I think xterm is the default terminal style and our other settings are the same. 
If your Language isn't `*` you might try changing that (in mintty go to Options>Window>UI language and select `*Locale environm.*` in the drop down menu).
If that doesn't work, try deleting all the mintty files and running [the latest version of] media-autobuild_suite again.
If that still doesn't work, try setting mintty's settings to the ones I listed above since they'll have been deleted in the previous step, then run the suite again.
If that _still_ doesn't work, consult a voodoo priest.
Good luck!

**Comment by wiiaboo** [comment]
The mintty settings should be saved in .minttyrc, btw.

**Comment by nille02** [comment]
Its a weird problem. i had it too and fix it with open the mintty options from the window and saved the font manual. The .minttyrc file looks like before but the error is gone.

**Comment by BlackScreen** [comment]
FYI: The problem is solved in my installation now. The problem were CRLF in the .minttyrc.
I replaced them to only have LF left in the config and now everything is working again (symbols and font).

**Comment by wiiaboo** [comment]
Oh. That would make sense.
