### ISSUE TITLE
C++ libs broken with GCC 7

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#566]
[logs.zip] (https://0x0.st/0_9.zip)

**Comment by Jimmmyz** [comment]
I am also having the error where chromaprint is not being found during ffmpeg configure.

**Comment by LigH-de** [comment]
Same here.

[logs.zip](https://0x0.st/0_d.zip)

May happen only during the 64b build (32b passed on this PC), but I am not sure if it failed during the 32b build on my other PC, have to check there again.

**Comment by wiiaboo** [comment]
C++ Libs which use exceptions are momentarily broken due to misbuild of GCC 7. Just disable those or wait until it's fixed in MinGW. These include chromaprint and rubberband. x265 shouldn't be broken because it doesn't use exceptions, iirc.

**Comment by irie-at** [comment]
The same error applies to zimg (just adding to the list).

**Comment by wiiaboo** [comment]
As soon as mingw-w64-x86_64-gcc-7.1.0-2 shows up in the update, it should be fixed.

**Comment by irie-at** [comment]
You said it ... and it happend :-)
mingw-w64-x86_64-gcc-7.1.0-2 is available and upgrading fixed this issue.

**Comment by BlackScreen** [comment]
Confirmed. Also working for me after the update. Thanks!
