### ISSUE TITLE
Installing libzen fails with directory fractions in wrong scope

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#567]
[logs.zip](https://0x0.st/04w.zip) -- please notice the "pseudo full-qualified" directory in the **make[2]** line:

```
├ Running install...
Likely error:
<command-line>:0:4: error: 'dev' was not declared in this scope
<command-line>:0:8: error: 'mabs' was not declared in this scope
<command-line>:0:13: error: 'msys64' was not declared in this scope
<command-line>:0:20: error: 'D_FILE_OFFSET_BITS' was not declared in this scope
<command-line>:0:20: note: suggested alternative: 'FILE_OPEN_IF'
<command-line>:0:20: error: expected ';' at end of member declaration
<command-line>:0:39: error: expected unqualified-id before numeric constant
make[2]: *** [CMakeFiles/zen.dir/build.make:87: CMakeFiles/zen.dir/H_/dev/mabs/build/libzen-git/Source/ZenLib/CriticalSection.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/zen.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I doubt that the directory should get engrafted here from its root (drive letter) on.

There have been recent changes in ZenLib, so I asked [there](https://github.com/MediaArea/ZenLib/issues/58) if they made a mistake.

**Comment by wiiaboo** [comment]
It could be something to do with the patches/sed we do.

**Comment by wiiaboo** [comment]
Wasn't the patch, but as soon as https://github.com/MediaArea/ZenLib/pull/61 is merged or https://github.com/MediaArea/ZenLib/issues/58 is closed, this should be working again.
