### ISSUE TITLE
Compile shared FFmpeg error

### ISSUE THREAD

**Issue by wljcom** [jb-alvarado/media-autobuild_suite#570]
┌ ffmpeg git ........................................ [[311mRecently updated]
├ Changing options to comply to nonfree...
├ Compiling shared FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --disable-static --enable-shared --pkg-config-flags=--static --enable-avisynth --enable-gcrypt --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-cuda --enable-cuvid --enable-schannel --enable-libfdk-aac --enable-gpl --enable-nonfree --disable-debug --prefix=/local64/bin-video/ffmpegSHARED
ERROR: gcrypt not found

**Comment by wiiaboo** [comment]
Where's the logs?
