### ISSUE TITLE
Cannot install msys2 on Windows 10 64 bit

### ISSUE THREAD

**Issue by LuciferSam86** [jb-alvarado/media-autobuild_suite#571]
Hello,
Windows 10 Pro 64 bit
Disabled antivirus (comodo)

msys2 have some errors on package signatures and then fails.
Do you have any idea?

If you need anything else I can attach it 🙂 

[logs_and_config.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1132311/logs_and_config.zip)

**Comment by wiiaboo** [comment]
Nope. But probably your anti-virus or some firewall is messing with the files corrupting them. Or some program in PATH interfering.
Either way, not a problem with the suite.

**Comment by LuciferSam86** [comment]
Yup, it was that below average comodo antivirus. Removed it and turned back to Windows Defender and Sandboxie, and now it's compiling.
Closing the ticket.
