### ISSUE TITLE
mpv compile error

### ISSUE THREAD

**Issue by wljcom** [jb-alvarado/media-autobuild_suite#572]
┌ mpv git ........................................... [Recently updated]
Installing python3-docutils... done
├ Running configure...
Likely error:
Checking for Xv video output                                      : x11 not found
Checking for OpenGL Cocoa Backend                                 : cocoa not found
Checking for OpenGL X11 Backend                                   : x11 not found
Checking for OpenGL X11 EGL Backend                               : x11 not found
Checking for OpenGL DRM EGL Backend                               : drm, gbm not found
Checking for OpenGL Wayland Backend                               : wayland not found
Checking for OpenGL Win32 Backend                                 : yes
Checking for OpenGL/DirectX Interop Backend                       : yes
Checking for OpenGL ANGLE headers                                 : no
You manually enabled the feature 'egl-angle', but the autodetection check failed.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1144162/logs.zip)

**Comment by wiiaboo** [comment]
I forgot to push the fix days ago.
