### ISSUE TITLE
fontconfig fails to update

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#574]
[logs.zip](https://0x0.st/Gtm.zip)

I'm running the latest version of media-autobuild_suite on Windows 7 SP1 x64.

**Comment by wiiaboo** [comment]
Weird. Seems like a python error.

**Comment by wiiaboo** [comment]
Can't reproduce here. Can you try deleting fontconfig-git dir?

**Comment by Metaphorce812** [comment]
Yeah I've tried that 3 times now and I keep getting the same error:
```
┌ fontconfig git .................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
  File "../../fc-blanks/fc-blanks.py", line 14, in <module>
    from lxml import html
  File "C:/media_AB_suite/msys64/mingw64/lib/python2.7/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: DLL load failed: The specified module could not be found.
make[2]: *** [Makefile:593: fcblanks.h] Error 1
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/fc-blanks'
make[1]: *** [Makefile:579: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-64bit'
make: *** [Makefile:463: all] Error 2
make failed. Check C:/media_AB_suite/build/fontconfig-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/GtG.zip
Copy and paste [logs.zip](https://0x0.st/GtG.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by wiiaboo** [comment]
Can you try `pacman -S --force mingw-w64-x86_64-python2-lxml mingw-w64-x86_64-python2-six` on mintty?

**Comment by Metaphorce812** [comment]
I tried that and still got the exact same error :(

**Comment by wiiaboo** [comment]
Try any of these: https://www.google.pt/search?q=DLL+load+failed%3A+The+specified+module+could+not+be+found.

**Comment by wiiaboo** [comment]
If still unsuccessful, I can revert back to using a tarball instead so python isn't needed.

**Comment by Metaphorce812** [comment]
It seems to be a problem with python communicating with visual C++. I found [this question](https://stackoverflow.com/questions/7228229/lxml-dll-load-failed-the-specified-module-could-not-be-found) about the same error I'm having and the top answer is to install an unofficial build from [http://www.lfd.uci.edu/~gohlke/pythonlibs/](http://www.lfd.uci.edu/~gohlke/pythonlibs/), but I don't know how to do that.

**Comment by wiiaboo** [comment]
Try installing [x64 version of python 2.7](https://www.python.org/ftp/python/2.7.13/python-2.7.13.amd64.msi). It might also install whatever redistributables that are missing. According to that site, if the error still occurs you might want to install Microsoft Visual C++ 2008 x86 and x64 redistributables, along with SP1.

I've never had that error before, so I can't tell how to fix it exactly.

**Comment by Metaphorce812** [comment]
OK, I'll try that python install. I've got the latest versions of MVC++ Redistributables 2008 x86 & x64, and I tried uninstalling and reinstalling them, but it didn't fix the error.

**Comment by Metaphorce812** [comment]
Well installing python 2.7 didn't work, so I deleted the entire msys64 folder from the media-autobuild_suite folder, ran the suite again, let it re-install msys, and that fixed it. I wish I'd done that to begin with instead of all the other troubleshooting that didn't work lol.

**Comment by wiiaboo** [comment]
Welcome to trial and error debugging.
