### ISSUE TITLE
Can't configure ffmpeg

### ISSUE THREAD

**Issue by Felixkruemel** [jb-alvarado/media-autobuild_suite#575]
First: If I start the command file it displays me a warning that it misses a font and so it switches to default. This is no problem but I think I should report it.

My problem is that it is not possible to compile ffmpeg now. It fails with "Unknown option --enable-libschroedinger". I even don't know this library but it is required for others. The complete log has been (automatically) uploaded to https://0x0.st/G7F.zip 

The console output:

â”œ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-avisynth --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-decklink --enable-fontconfig --enable-frei0r --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmfx --enable-libmodplug --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxavs --enable-libxvid --enable-libzimg --enable-openssl --enable-libsnappy --enable-gpl --enable-nvenc --enable-opencl --enable-opengl --enable-libcdio --enable-libfdk-aac --enable-libkvazaar --enable-librubberband --enable-libssh --enable-libtesseract --enable-libzvbi --enable-chromaprint --enable-libopenh264 --enable-libopenmpt --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-libs=-lpng --disable-w32threads --extra-cflags=-DPTW32_STATIC_LIB --extra-libs=-lpthread --extra-libs=-lwsock32 --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --enable-filter=frei0r --disable-debug
Unknown option "--enable-libschroedinger".
See ../configure --help for available options.
configure failed. Check D:/media-autobuild_suite-master/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.

**Comment by wiiaboo** [comment]
Old version of the suite.

**Comment by wiiaboo** [comment]
Actually no, but libschroedinger has been gone for months from FFmpeg.

**Comment by wiiaboo** [comment]
Use FFmpeg's native `vc2` encoder. `libschroedinger` is dead, unmaintained and a security risk.

**Comment by wiiaboo** [comment]
Reasons: https://patchwork.ffmpeg.org/patch/3755/
