### ISSUE TITLE
make failed. Check H:/media-autobuild_suite/build/zimg-git/build-32bit/ab-suite.

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#577]
[logs.zip](https://0x0.st/DSh.zip)

**Comment by wiiaboo** [comment]
https://github.com/sekrit-twc/zimg/issues/76

**Comment by wiiaboo** [comment]
Clamped to older commit as workaround. Problem is with mingw GCC specifically, so unlikely to be fixed soon.
