### ISSUE TITLE
Script builds redundant tools

### ISSUE THREAD

**Issue by AnryCryman** [jb-alvarado/media-autobuild_suite#578]
The script builds the following tools despite the fact that I've not opted to build them and the lines are commented out in ffmpeg_options.txt:

- freetype
- harfbuzz
- fribidi
- libass
- rubberband
- lame
- sdl2
- libbluray

[ffmpeg_options.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1168242/ffmpeg_options.txt)
[compile.log.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1168243/compile.log.txt)

**Comment by wiiaboo** [comment]
> freetype
harfbuzz
fribidi
libass
rubberband
libbluray

All enabled by default if you build mplayer or mpv. Disable them explicitly.

> sdl2

Enabled by default by ffmpeg. Disable it explicitly.

> lame

I see `--enable-libmp3lame` in your ffmpeg_options.txt.

**Comment by wiiaboo** [comment]
Also, read the readme next time. It's right there that sdl2 is enabled by default.

**Comment by AnryCryman** [comment]
> freetype
> harfbuzz
> fribidi
> libass
> rubberband
> libbluray
> All enabled by default if you build mplayer or mpv. Disable them explicitly.

I'm building neither mplayer nor mpv. How do I disable them explicitly? And what's the point of these lines in ffmpeg_options.txt then?
```
#--enable-libfreetype
#--enable-libfribidi
#--enable-libass
#--enable-librubberband
#--enable-libbluray
```

**Comment by AnryCryman** [comment]
BTW, I just checked the FFmpeg config. The output is:
```
ffmpeg version N-86841-g7e9f550003 Copyright (c) 2000-2017 the FFmpeg developer

  built with gcc 7.1.0 (Rev2, Built by MSYS2 project)
  configuration:  --enable-avisynth --enable-gcrypt --enable-libmp3lame --enabl
-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 -
enable-cuda --enable-cuvid --enable-schannel --enable-libmfx --enable-libtheora
--enable-libxvid --enable-opencl --enable-opengl --enable-libfdk-aac --enable-l
bkvazaar --enable-libopenh264 --extra-cflags=-DKVZ_STATIC_LIB --enable-gpl --en
ble-nonfree --disable-debug
  libavutil      55. 68.100 / 55. 68.100
  libavcodec     57.102.100 / 57.102.100
  libavformat    57. 76.100 / 57. 76.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 95.100 /  6. 95.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outf
le}...
```
It doesn't contain these things:
```
--enable-libfreetype
--enable-libfribidi
--enable-libass
--enable-librubberband
--enable-libbluray
```
So, are they built just for the sake of being build, taking more time to process everything?

**Comment by wiiaboo** [comment]
They don't take that much time to build anyway and they're rarely updated, other than libbluray. Only libass and libbluray use git, so as soon as they're built they aren't built again until there's an updated release.

I don't know the .ini you used the first time you built them, so I don't know what you did wrong.

freetype, fribidi and harfbuzz are libass dependencies, so only libass needs to be enabled to build all of them.

Give me ffmpeg_options.txt and the .ini that you use and I'll try myself.

**Comment by wiiaboo** [comment]
> How do I disable them explicitly?

`--disable-libwhatever`, amazingly.

> And what's the point of these lines in ffmpeg_options.txt then?

No point. They're prefixed by #, so it's the same as them not being there.

**Comment by AnryCryman** [comment]
I used these options.

[options.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1168341/options.zip)
