### ISSUE TITLE
Soxr HAVE_WORDS_BIGENDIAN_EXITCODE potential failures

### ISSUE THREAD

**Issue by mabreedlove** [jb-alvarado/media-autobuild_suite#58]
jb,

I was hoping you knew something about the HAVE_WORDS_BIGENDIAN_EXITCODE flag within the soxr build.  I see it mentioned in the install file but its only referenced for Linux host crossbuilding.  I was curious if you knew the original reason for the flag.  During testing, I noticed that the presence (or value when set to 0) causes soxr to fail its own self-tests.  Removing it or changing it to 1 (the default) let's the tests build and complete without issue with no other noticeable effects that I can see.  The default value is listed in the TRY_RUN section of the CMakeCache.txt file which makes me think its only relevant when doing self-tests.  Any ideas?

**Comment by jb-alvarado** [comment]
Hello Matt,
sorry I don't really know for what this parameter is. I think I have this config line copy from somewhere else and it was working for me. But when I remove this I get:
Performing Test HAVE_WORDS_BIGENDIAN - Failed

And with it it comes:
 Performing Test HAVE_WORDS_BIGENDIAN - Success

So I guess it is ok to late it in.

**Comment by mabreedlove** [comment]
Yeah, that's the result from the test in the configure seeing if it requires it or not.  If you run "make test" after the actual compile within that directory to let it do its self-test against the build though, it will fail out if you have the flag in place.  The actual reasoning is referenced in this link: https://bugs.busybox.net/show_bug.cgi?id=6956

**Comment by jb-alvarado** [comment]
Ah ok. So you recommend to remove this parameter, or set them to 1?

**Comment by mabreedlove** [comment]
Actually, removing it and setting it to 1 is the same since the configure script handles it.  The flag has no effect unless we're doing a "make test" within the build directory to do its self-tests so whether its there or not right now, it doesn't make any real difference.  

In the makepkg system, however, there are sections for running checks to verify the builds and I wanted to make sure there wasn't a particular reason for it being there that I wasn't aware of.  I'm going to remove it since it doesn't do anything right now anyway and would fail checks even if we did start using them.  Other than simplifying the script, this won't have any effect on current builds being done.
