### ISSUE TITLE
fresh run: stops at libbluray

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#580]
[1mdvdnav git (B[m............................................. [[32mAlready built(B[m]
  Running git update for libbluray...
[1m┌ libbluray git (B[m..................................... [[311mRecently updated(B[m]
├ Running autoreconf...
├ Running ant-diagnostics...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ant -diagnostics
/opt/apache-ant/bin/ant: line 173: cd: C:\Program Files (x86)\Java\jdk1.8.0_121: No such file or directory
Error: JAVA_HOME is not defined correctly.
  We cannot execute /build/libbluray-git/bin/java
[31mant-diagnostics failed. Check F:/m-a-s/build/libbluray-git/ab-suite.ant-diagnostics.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m
  Creating diagnostics file...

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1168375/logs.zip)

**Comment by wiiaboo** [comment]
Open mintty and run this:
```
source /build/media-suite_helper.sh
echo "$(get_java_home)"
```

**Comment by ASopH** [comment]
Arne@Arne-PC /trunk
$ source /build/media-suite_helper.sh
Arne@Arne-PC /trunk
$ echo "$(get_java_home)"
/c/Program Files/Java/jdk1.8.0_141

looks like my part.
I'd cleaned up my java but don't change the environment-var to the new path. -.-
I've change it and the suite runs.

Thank you very much for your effort. Great Job !!
