### ISSUE TITLE
failed to run the script, something went wrong

### ISSUE THREAD

**Issue by mahdi87gh** [jb-alvarado/media-autobuild_suite#583]
Hi,
I'm on windows 10 64 bit, I have downloaded the latest version but as soon as I run the batch file, I get this error message and there is no log file to see the problem.

`Something went wrong.
MSYSTEM: MINGW64
pwd: D:\mingw\media-autobuild_suite-master\build
fstab:
# For a description of the file format, see the Users Guide
# http://cygwin.com/cygwin-ug-net/using.html#mount-table

# DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
none / cygdrive binary,posix=0,noacl,user 0 0
none /tmp usertemp binary,posix=0,noacl 0 0
Create a new issue and upload all logs you can find, especially compile.log
Enter to continue
`

**Comment by wiiaboo** [comment]
I have no idea what happened to your fstab. Just delete it.
