### ISSUE TITLE
ZIMG build problem

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#585]
[logs.zip](https://0x0.st/dW8.zip)

**Comment by wiiaboo** [comment]
Check if latest upstream commit fixed it.

**Comment by Selur** [comment]
I'm already using the current commit, so an additional 'pull' didn't change anything,...

**Comment by wiiaboo** [comment]
There was a fix commit yesterday but he seems to have removed it, for some reason.
Either way, open an issue here https://github.com/sekrit-twc/zimg/issues. He responds much more rapidly than me.

**Comment by wiiaboo** [comment]
Just post the make log inside zimg-git. It's the only thing that's needed.

**Comment by wiiaboo** [comment]
Can't reproduce with 32 or 64-bits, maybe was fixed already.
