### ISSUE TITLE
Libzen CMake Error

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#587]
[logs.zip](https://0x0.st/nJ2.zip)
I downloaded the latest version of media-autobuild_suite, ran it, and got the error:
`Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
cmake ../Project/CMake -G MSYS Makefiles -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX=/local64 -DUNIX=on -DCMAKE_BUILD_TYPE=Release
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
C:/Media-AB_Suite/msys64/mingw64/share/cmake-3.8
CMake Error: Error executing cmake::LoadCache(). Aborting.`

I noticed when I first ran it, there was a pacman update. When I looked in my `C:/Media-AB_Suite/msys64/mingw64/share/` directory, I noticed there was both a cmake-3.8 and a cmake-3.9 folder. The cmake-3.8 folder is only 15 KB and only contains a total of 3 files and 3 folders. However, the cmake-3.9 folder is 4.24 MB and contains 2,226 files and 38 folders. So I'm guessing there's some sort of issue where CMake was updated, but something still tried to used the old version.

**Comment by wiiaboo** [comment]
It's probably fixed like with the other two cmake issues?

**Comment by Metaphorce812** [comment]
Nope, still getting same error: [logs.zip](https://0x0.st/nUD.zip)

```
Running git update for libzen...
┌ libzen git ........................................ [Recently updated]
├ Running cmake...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
cmake ../Project/CMake -G MSYS Makefiles -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX=/local64 -DUNIX=on -DCMAKE_BUILD_TYPE=Release
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
C:/Media-AB_Suite/msys64/mingw64/share/cmake-3.8
CMake Error: Error executing cmake::LoadCache(). Aborting.

cmake failed. Check C:/Media-AB_Suite/build/libzen-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
```

**Comment by wiiaboo** [comment]
Can't reproduce that. Try deleting that cmake-3.8 directory completly.

**Comment by Metaphorce812** [comment]
I tried that and got the same error: [logs.zip](https://0x0.st/n0I.zip) 
It's still looking for CMake in the [now non-existent] "cmake-3.8" directory for some reason.

**Comment by wiiaboo** [comment]
Open mintty, go to `/var/cache/pacman/pkg` and `pacman -U mingw-w64-x86_64-cmake-3.8.2-2-any.pkg.tar.xz`. That should downgrade cmake to the previous version. If needed, add `--force` and run `cmake -V`. If it worked so far, then do `pacman -Syu` so cmake gets upgraded again. It should install properly and `cmake -V` should work again.

**Comment by Metaphorce812** [comment]
That worked! Thanks! I had to add `--force` to both of those pacman commands to get them to work. And the command to check cmake's version is apparently `cmake --version`, but it's now v3.9.1 and working.
