### ISSUE TITLE
failed to build x265 (unknown error (_ssl.c:2755))

### ISSUE THREAD

**Issue by m-audio91** [jb-alvarado/media-autobuild_suite#59]
Hello jb-alvarado,
Many thanks for this script and your hard work,
can you please give me a hand:)

My main goal is to compile FFmpeg with fdk-aac enabled.
However, I have problem compiling x265, with this error:

/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
install -m 644 x264_config.h /local32/include
install -m 644 x264.pc /local32/lib/pkgconfig
install -m 644 libx264.a /local32/lib
ranlib /local32/lib/libx264.a
-
-------------------------------------------------
build x264-git done...
-------------------------------------------------
-
abort: error: unknown error (_ssl.c:2755)
D:\mingw\media-suite_compile.sh: line 85: cd: x265-hg: No such file or directory
D:\mingw\media-suite_compile.sh: line 1544: cd: build/msys: No such file or directory
CMake Error: The source directory "D:/source" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat ‘x265.exe’: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
CMake Error: The source directory "D:/source" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
-------------------------------------------------
Build x265-git failed...
Delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it.
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////

I also have some other errors (mostly certificate errors)  that i think its better to separate them to new issues?
Sorry for my English and thanks again.

**Comment by jb-alvarado** [comment]
Hello m-audio91,
normally this works good, but your message looks like that there was something wrong with the install process at the begin. Maybe you can delete the msys64 folder and the mintty shortcut and run the script again?

The other error messages will be also interesting. You can post them here.

**Comment by m-audio91** [comment]
thanks for the fast response,

Actually other errors looks the same,
They tell something about certificate location,
I've  managed to ignore them in a dangerous way (by adding GIT_SSL_NO_VERIFY=true before "git clone $gitURL $gitFolder" and "git clone --depth 1 $gitURL $gitFolder" in main script file.
But two of them showing that error no matter what I've done,
(I didn't touch any other thing in script;)


/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
build libbluray-git done...
-------------------------------------------------
-
Cloning into 'libutvideo-git'...
fatal: unable to access 'https://github.com/qyot27/libutvideo.git/': error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
D:\mingw\media-suite_compile.sh: line 1108: cd: libutvideo-git: No such file or directory
D:\mingw\media-suite_compile.sh: line 1126: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
-------------------------------------------------
build libutvideo-git failed...
delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window
Cloning into 'libass-git'...
remote: Counting objects: 61, done.
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
compile video tools 32bit

-------------------------------------------------------------------------------
Cloning into 'libvpx-git'...
fatal: unable to access 'http://git.chromium.org/webm/libvpx.git/': Couldn't resolve host 'git.chromium.org'
D:\mingw\media-suite_compile.sh: line 42: cd: libvpx-git: No such file or directory
D:\mingw\media-suite_compile.sh: line 980: ./configure: No such file or directory
sed: can't read libs-x86-win32-gcc.mk: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
mv: cannot stat ‘/local32/bin/vpxdec.exe’: No such file or directory
mv: cannot stat ‘/local32/bin/vpxenc.exe’: No such file or directory
-------------------------------------------------
build libvpx-git failed...
delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////

Looking at the given location, I see two files named "ca-bundle.crt" and "ca-bundle.trust.crt" but both of them are empty 0 byte files.

And the last error is about libcaca (it cant retrieve libcaca tried many times):
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
-- Installing: D:/mingw/local32/lib/libvidstab.a
-- Installing: D:/mingw/local32/lib/pkgconfig/vidstab.pc
-
-------------------------------------------------
build vidstab-git done...
-------------------------------------------------
-
--2015-03-20 18:16:38--  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Resolving fossies.org (fossies.org)... 78.46.58.28
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:17:00--  (try: 2)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:17:23--  (try: 3)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:17:46--  (try: 4)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:18:09--  (try: 5)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:18:32--  (try: 6)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:18:55--  (try: 7)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:19:18--  (try: 8)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:19:41--  (try: 9)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:20:04--  (try:10)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:20:27--  (try:11)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:20:50--  (try:12)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:21:13--  (try:13)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:21:36--  (try:14)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:21:59--  (try:15)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:22:22--  (try:16)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:22:45--  (try:17)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:23:08--  (try:18)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:23:31--  (try:19)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:23:54--  (try:20)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Giving up.

tar: libcaca-0.99.beta19.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove ‘libcaca-0.99.beta19.tar.gz’: No such file or directory

/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////


For x265 error, I will do and inform you, thanks.

**Comment by m-audio91** [comment]
thanks for the fast response,

Actually other errors looks the same,
They tell something about certificate location,
I've  managed to ignore them in a dangerous way (by adding GIT_SSL_NO_VERIFY=true before "git clone $gitURL $gitFolder" and "git clone --depth 1 $gitURL $gitFolder" in main script file.
But at least one of them showing that error no matter what I've done,
(I didn't touch any other thing in script;)


/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
build libbluray-git done...
-------------------------------------------------
-
Cloning into 'libutvideo-git'...
fatal: unable to access 'https://github.com/qyot27/libutvideo.git/': error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
D:\mingw\media-suite_compile.sh: line 1108: cd: libutvideo-git: No such file or directory
D:\mingw\media-suite_compile.sh: line 1126: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
-------------------------------------------------
build libutvideo-git failed...
delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window
Cloning into 'libass-git'...
remote: Counting objects: 61, done.
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////


Looking at the given location, I see two files named "ca-bundle.crt" and "ca-bundle.trust.crt" but both of them are empty 0 byte files.

And the last errors is about libcaca and lib-vpx  (it cant retrieve libcaca and lib-vpx tried many times):
(don't know how to get them because they cause FFmpeg to fail)
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
compile video tools 32bit

-------------------------------------------------------------------------------
Cloning into 'libvpx-git'...
fatal: unable to access 'http://git.chromium.org/webm/libvpx.git/': Couldn't resolve host 'git.chromium.org'
D:\mingw\media-suite_compile.sh: line 42: cd: libvpx-git: No such file or directory
D:\mingw\media-suite_compile.sh: line 980: ./configure: No such file or directory
sed: can't read libs-x86-win32-gcc.mk: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
mv: cannot stat ‘/local32/bin/vpxdec.exe’: No such file or directory
mv: cannot stat ‘/local32/bin/vpxenc.exe’: No such file or directory
-------------------------------------------------
build libvpx-git failed...
delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
-- Installing: D:/mingw/local32/lib/libvidstab.a
-- Installing: D:/mingw/local32/lib/pkgconfig/vidstab.pc
-
-------------------------------------------------
build vidstab-git done...
-------------------------------------------------
-
--2015-03-20 18:16:38--  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Resolving fossies.org (fossies.org)... 78.46.58.28
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:17:00--  (try: 2)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:17:23--  (try: 3)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:17:46--  (try: 4)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:18:09--  (try: 5)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:18:32--  (try: 6)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:18:55--  (try: 7)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:19:18--  (try: 8)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:19:41--  (try: 9)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:20:04--  (try:10)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:20:27--  (try:11)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:20:50--  (try:12)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:21:13--  (try:13)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:21:36--  (try:14)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:21:59--  (try:15)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:22:22--  (try:16)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:22:45--  (try:17)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:23:08--  (try:18)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:23:31--  (try:19)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Retrying.

--2015-03-20 18:23:54--  (try:20)  https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz
Connecting to fossies.org (fossies.org)|78.46.58.28|:443... failed: Connection timed out.
Giving up.

tar: libcaca-0.99.beta19.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove ‘libcaca-0.99.beta19.tar.gz’: No such file or directory

/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////


For x265 error, I will do and inform you, thanks.

**Comment by jb-alvarado** [comment]
Hello again, this thing with the certificates is a problem and I think you can not really fix that by ignore the waring. I don't know exactly in witch msys2 tool this is include, but in general you can reinstall them with pacman -S "[...]". For libvpx you can try the address https://git.chromium.org/git/webm/libvpx.git and libcaca should be only again. Hope this solves some problems. And when you don't found the cert files I can send them to you to.

**Comment by m-audio91** [comment]
Hello again and sorry for the delay,

So I have done a clean install (using your script version downloaded after you changed libvpx address - its not the latest version now),
And now I have my FFmpeg build with fdk-aac enabled.
This time, cert files have generated correctly in first install section so no cert issues happened and above x265 error is gone.
I've reached my goal. Thank you +1.

However, mplayer failed to compile if you are interested:

/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////
libmpcodecs/ve_qtvideo.c: In function 'vf_open':
libmpcodecs/ve_qtvideo.c:333:20: warning: assignment from incompatible pointer type
     NewHandleClear = (OSErr(*)(Size))GetProcAddress(handler, "NewHandleClear");
                    ^
Makefile:731: recipe for target 'libmpcodecs/ve_qtvideo.o' failed
make: *** [libmpcodecs/ve_qtvideo.o] Error 1
-------------------------------------------------
Build mplayer-svn failed...
Delete the source folder under '/build32' and start again,
or if you know there is no dependences hit enter for continue it.
/////////////////////////////////////////////////////////////[code]////////////////////////////////////////////////////////////////////

**Comment by jb-alvarado** [comment]
Try please the new script, I think it works now.

**Comment by m-audio91** [comment]
OK,
tested last night and mplayer compiles. thanks.
FFmpeg failed, though. and I think you are currently aware of it (https://trac.ffmpeg.org/ticket/4391#comment:1).
thanks.

**Comment by m-audio91** [comment]
Hello again jb-alvarado,
its all OK now for me. thanks.
