### ISSUE TITLE
python2-olefile update fails: egg-info exists

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#590]
The update could not be completed even with --force parameter:

```
mingw-w64-i686-python2-olefile: /mingw32/lib/python2.7/site-packages/olefile-0.44-py2.7.egg-info exists in file system
mingw-w64-x86_64-python2-olefile: /mingw64/lib/python2.7/site-packages/olefile-0.44-py2.7.egg-info exists in file system
```

BTW, how do I quickly switch the MSYS2 shell between English and my native language? The messages above are manually translated, and I know you only accept English messages ...

**Comment by wiiaboo** [comment]
Run `pip uninstall olefile` on both mingw32 and mingw64 shells.

**Comment by LigH-de** [comment]
That takes quite a long time without any visible reaction after listing the scheduled actions; but I will be patient...

**Comment by wiiaboo** [comment]
You can add `-v -v -v` after `uninstall` but it's really just deleting files.

**Comment by LigH-de** [comment]
I don't recognize any files getting deleted.

```
$ pip uninstall -v -v -v olefile
Uninstalling olefile-0.44:
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile-0.44-py2.7.egg-info
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/__init__.py
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/__init__.pyc
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/contributors.txt
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/license.txt
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/olefile.py
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/olefile.pyc
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/readme.html
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefile/readme.rst
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefileio_pl.py
  h:/dev/mabs/msys64/mingw32/lib/python2.7/site-packages/olefileio_pl.pyc

```

And here: absolutely idle, 0% CPU utilization from bash up to python2, no I/O activity (according to ProcessExplorer).

ProcessState: Wait:UserRequest ... do I have to press 'Y'?!

**Comment by wiiaboo** [comment]
Oh, yeah, I forgot mingw python has that issue. Add a `--yes` after `uninstall` too.

**Comment by LigH-de** [comment]
68 updates finished. Thank you!
