### ISSUE TITLE
x265: -DENABLE_DYNAMIC_HDR10 got renamed to -DENABLE_HDR10_PLUS

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#591]
Current builds don't support Dynamic HDR10+ JSON configuration for this reason.

**Comment by wiiaboo** [comment]
Since june??

**Comment by LigH-de** [comment]
Oh yes, it is not really "new". Just somehow missed. Though ... I wonder if I mentioned that already, some time ago.

**Comment by wiiaboo** [comment]
If you did, it wasn't to me.

**Comment by wiiaboo** [comment]
Sounds pretty retarded to just change an option like that too.

**Comment by LigH-de** [comment]
It was obviously absolutely vital to point at the "plus"; general Dynamic HDR10 is possible without reading JSON configuration files.
