### ISSUE TITLE
Is flite not included?

### ISSUE THREAD

**Issue by schmidthubert** [jb-alvarado/media-autobuild_suite#594]
Hi again,

tried to add --enable-libflite to the options, but no go. @rdp's build has it ...

http://www.festvox.org/flite/

Thanks!

**Comment by wiiaboo** [comment]
No. Doesn't seem to work out-of-box, so I'd have to spend time on this that I really don't have.

**Comment by schmidthubert** [comment]
Ah, that looks as if it could work without any patches. :clap:

**Comment by schmidthubert** [comment]
Great, compiling fine here, thank you again! :+1:
