### ISSUE TITLE
Please add --enable-avresample to default ffmpeg options

### ISSUE THREAD

**Issue by schmidthubert** [jb-alvarado/media-autobuild_suite#595]
Thanks! :+1:

**Comment by wiiaboo** [comment]
You can add them yourself with custom ffmpeg_options.txt, you know?

**Comment by schmidthubert** [comment]
Yes I know and do that. But why not make it a default for everyone ;-)

**Comment by wiiaboo** [comment]
Because it's not supposed to be default. Most apps based on ffmpeg/libav expect them to use their version of swresample/avresample respectively.

**Comment by schmidthubert** [comment]
OK, now problem then. What I thought was just zeranoe + rdp DO have SWResample build in by default so why not jb has it as well? See? ;-)

**Comment by wiiaboo** [comment]
swresample IS enabled by default already. If you do want avresample you can just add it.

**Comment by schmidthubert** [comment]
OK, no problem, thanks!
