### ISSUE TITLE
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavfilter/vf_scale_cuda.ptx.o] Error 1

### ISSUE THREAD

**Issue by schmidthubert** [jb-alvarado/media-autobuild_suite#596]
Hi again,

when adding --enable-cuda-sdk to ffmpegs buildconf the make fails with compiling vf_scale_cuda.ptx.c, the errors being (just a snippet): 
`[...]`
`libavfilter/vf_scale_cuda.ptx.c:1220:2: warning: missing terminating " character`
`libavfilter/vf_scale_cuda.ptx.c:1220:2: error: missing terminating " character`
`libavfilter/vf_scale_cuda.ptx.c:1221:1: error: stray '\' in program`
`libavfilter/vf_scale_cuda.ptx.c:1221:3: warning: missing terminating " character`
`libavfilter/vf_scale_cuda.ptx.c:1221:3: error: missing terminating " character`
`[...]`
I don't think all these DOS-linebreaks should be in there? Do you know how to fix this? I'm using VC++ 2013 + SDK 8.0.61 in case this should matter. Thank you!

**Comment by schmidthubert** [comment]
Maybe ffmpeg-git\compat\cuda\ptx2c.sh needs a patch? ;-)

**Comment by wiiaboo** [comment]
This isn't the FFmpeg bug tracker, btw.

**Comment by schmidthubert** [comment]
cu->ptx->c So nvcc.exe isn't strictly an "ffmpeg bug" here. Seems someone at uppity NVidia quality control(err,what's that again?) simply "forgot" to add an EOL conversion switch for nvcc then, or maybe I'm totally blind as I could find it? Anyway, I fixed the problem myself now with a simple 

`dos2unix "$2"`

in ptx2c.sh. Feel free to make a sed patch or whatever here, or do the same as I did, or wait forever for NV, or simply ignore this post. Thank you! :expressionless:

**Comment by wiiaboo** [comment]
It's still a ffmpeg issue, not the suite's. Let them know about it.

**Comment by wiiaboo** [comment]
I sent a patch to the FFmpeg ML. As soon as it's merged it should be fixed.

**Comment by schmidthubert** [comment]
Yes, I checked the ML just now and see it. Thank you! :+1:

**Comment by schmidthubert** [comment]
OK, it is merged now. :smiley:
