### ISSUE TITLE
Snow Encoder options missing?

### ISSUE THREAD

**Issue by schmidthubert** [jb-alvarado/media-autobuild_suite#597]
Hi again,

when comparing to rdp's ffmpeg build there are lots of snow encoder options missing here? Do you happen to know the reason for this? I cannot find any specific or additional option(s) to enable what's missing here? I'm attaching a screenshot from the diff so you can see what I mean ...

![image](https://user-images.githubusercontent.com/26191502/29855245-b8bb3720-8d4a-11e7-9b2e-545a5692ba3d.png)

**Comment by wiiaboo** [comment]
I haven' the faintest idea. Like I said, this isn't the FFmpeg bug tracker.

**Comment by wiiaboo** [comment]
You have to ask rdp. Looking at the source file of snowenc I don't see any of those missing options.

**Comment by wiiaboo** [comment]
https://github.com/FFmpeg/FFmpeg/commit/95a6de5674ab8f5116241cfa4bb02a0954b843d8 this commit removed those extra options, apparently.

**Comment by schmidthubert** [comment]
The left area of my screenshot is rdp's script, the right area is the result from your script. Yesterday I even manually removed my ffmpeg sources in my VM where rdp's script is running and rebuild ffmpeg completely with the above result on the left hand side. The option (for instance) "-mpv_flags" is still in there, it's in libavcodec/mpeg2video.h:

![image](https://user-images.githubusercontent.com/26191502/29871057-b6d03dee-8d8a-11e7-855e-2e91914e2ac5.png)

That file is from Aug 28 so the options are still in there, strange ...

**Comment by wiiaboo** [comment]
Still not the suite's issue. Refrain from opening these kind of issues comparing different scripts if you're not using the same version and options for both. And even if you are, try researching the issue first, please. This is not my day job.

**Comment by schmidthubert** [comment]
The thing is I DO use the same options, otherwise I would have come here with this ...

**Comment by wiiaboo** [comment]
Well, you were obviously not using the same version.
