### ISSUE TITLE
add support for libnpp* from cuda sdk 9

### ISSUE THREAD

**Issue by hydra3333** [jb-alvarado/media-autobuild_suite#598]
I notice that ffmpeg now supports  cuda sdk 9:

configure: add support for libnpp* from cuda sdk 9
https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/f762555a90790dbfca016ff81b3a4972c39babb4..1ac03c8dc0a9359cdd33e341303296862a0e5f84:/configure

Would it be possible for the suite to now also support it?

**Comment by wiiaboo** [comment]
It's supported already.
