### ISSUE TITLE
error building with cuda_sdk v9

### ISSUE THREAD

**Issue by hydra3333** [jb-alvarado/media-autobuild_suite#600]
OK thank you for the great Suite !

I thought I'd try to build ffmpeg with the new cuda_sdk v9, so I downloaded and installed that and rebooted.
(I don't have Visual Studio installed.)
(my video card is an nvidia 8600GT)

Then I downloaded and ran the media-autobuild_suite and the error below popped up.
`nvcc fatal   : Cannot find compiler 'cl.exe' in PATH`

Am I supposed to do something else pre running the suite ?

```
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK!
FFmpeg and related apps will depend on Nvidia drivers!
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
CC      libavfilter/vf_removegrain.o
CC      libavfilter/vf_removelogo.o
CC      libavfilter/vf_repeatfields.o
CC      libavfilter/vf_rotate.o
CC      libavfilter/vf_sab.o
CC      libavfilter/vf_scale.o
CC      libavfilter/vf_scale_cuda.o
NVCC    libavfilter/vf_scale_cuda.ptx
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
make: *** [/build/ffmpeg-git/ffbuild/common.mak:95: libavfilter/vf_scale_cuda.ptx] Error 1
make failed. Check G:/ffmpeg_build/media-autobuild_suite-master/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach G:\ffmpeg_build\media-autobuild_suite-master\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already
```

**Comment by hydra3333** [comment]
Ah.

rtfm.

`scale_cuda (needs CUDA SDK and MSVC 2015 installed and cl.exe in PATH)`

**Comment by schmidthubert** [comment]
https://devtalk.nvidia.com/default/topic/997997/cuda-support-for-visual-studio-2017/

It should ... ;-)

**Comment by hydra3333** [comment]
ok thanks trying it now ...

**Comment by hydra3333** [comment]
ok, trying it now ...

I also see that gcc 7.2.0 is out and appears to be significantly faster at least for one user.
https://forum.videohelp.com/threads/384929-GCC-7-2-0-for-MSYS2

**Comment by wiiaboo** [comment]
You can still install VS2015 through 2017's installer. I think I tried with 2017 cl.exe, even with 9 RC, and it didn't work.

**Comment by schmidthubert** [comment]
If you google "385.41 release notes" (or take any other version) then those pdf's have the info what CUDA version is supported by the driver. For now all the latest drivers still have CUDA 8.0, even the 384.94 which comes with the CUDA SDK 9.0 RC. If ffmpeg compiles fine when pointing to a v9.0 CUDA path and then "doesn't work" that's the reason. So just wait for SDK 9.0 final. Then there will be info on the SDK download page as well as to what the minimum driver version for CUDA 9.0 support will be as was the case with CUDA 8.0 ... :+1:

**Comment by hydra3333** [comment]
Ah.  Thank you.  OK, waiting for v9.0 CUDA final.

In regard to gcc 7.2.0, there's errors when unpacking the .xz and the .gz  :( :( :(
I had to resort to something like this in a branch of rdp's lovely script. Still testing though.

```
  gcc_ver=7.2.0
  tmp_gcc_ver=${gcc_ver//./_} # eg 7.2.0 becomes 7_2_0 # ${string//substring/replacement} Replace all matches of $substring with $replacement.
  #echo "tmp_gcc_ver = \"${tmp_gcc_ver}\""
  rm -rfv gcc-"$gcc_ver"
  svn checkout svn://gcc.gnu.org/svn/gcc/tags/gcc_${tmp_gcc_ver}_release gcc-"$gcc_ver" > >(build_log) 2>&1 || print_error
```
