### ISSUE TITLE
Build fails at libass

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#601]
Bug that will be fixed upstream?
[logs.zip] (https://0x0.st/ROz.zip)

**Comment by wiiaboo** [comment]
During the next 4 months, I'm not at a place with good enough net or
resources to be able to fix the suite.
If possible, open an issue in libass github with the same logs and it'll
probably be fixed faster.

**Comment by laurfb** [comment]
libass is now switching to nasm. 
Temporarely you can change line 192 from media-suite_compile.sh to:

    if do_vcs "https://github.com/libass/libass.git#commit=6092e27^"; then

regards,
laur

**Comment by wiiaboo** [comment]
The suite should have nasm already. x264 has required it since a few months ago, so I don't know why it suddenly stopped working and I can't really debug why, since I'm on a Mac for a few months.

**Comment by Metaphorce812** [comment]
I'm having the same issue: [logs.zip](https://0x0.st/7XY.zip)
```
┌ libass git ........................................ [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
Likely error:
make[1]: Entering directory '/build/libass-git/build-64bit'
Making all in libass
make[2]: Entering directory '/build/libass-git/build-64bit/libass'
  NASM     x86/rasterizer.lo
../../libass/x86/rasterizer.asm:21: fatal: unable to open include file `x86/utils.asm'
make[2]: *** [Makefile:790: x86/rasterizer.lo] Error 1
make[2]: Leaving directory '/build/libass-git/build-64bit/libass'
make[1]: *** [Makefile:476: all-recursive] Error 1
make[1]: Leaving directory '/build/libass-git/build-64bit'
make: *** [Makefile:385: all] Error 2
make failed. Check C:/Media-AB_Suite/build/libass-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/7XY.zip
Copy and paste [logs.zip](https://0x0.st/7XY.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by Metaphorce812** [comment]
@laurfb Thanks! That worked!

**Comment by wiiaboo** [comment]
The commit that broke it broke out-of-root compilation. The issue is libass', so [make them know](https://mpv.io/manual/master/#files-on-windows).

**Comment by wiiaboo** [comment]
Fixed upstream.
