### ISSUE TITLE
Build fails at cmake

### ISSUE THREAD

**Issue by wellivea1** [jb-alvarado/media-autobuild_suite#604]
Starting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat

        Starting 64bit compilation of global tools
freetype2 2.8.0 ........................................... [Up-to-date]
  Running git update for fontconfig...
fontconfig git ............................................ [Up-to-date]
  Running git update for harfbuzz...
harfbuzz git .............................................. [Up-to-date]
fribidi 0.19.7 ............................................ [Up-to-date]
  Running git update for libass...
libass git ................................................ [Up-to-date]
libgcrypt 1.7.8 ........................................... [Up-to-date]
libssl 2.6.1 ................................................ [Outdated]
┌ libressl-2.6.1 .......................................... [Downloaded]
├ Running extract...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ libressl-2.6.1 ............................................. [Updated]
libcurl 7.55.1 .............................................. [Outdated]
┌ curl-7.55.1 ............................................. [Downloaded]
├ Running extract...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
├ Running ca-bundle...
Likely error:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
Failed downloading via HTTPS with curl
Falling back to HTTP
URLs other than HTTPS are disabled by default, to enable use -k
make: *** [Makefile:147: ca-bundle] Error 1
ca-bundle failed. Check C:/Users/welli/media-autobuild_suite-master/build/curl-7.55.1/ab-suite.ca-bundle.log
This isn't required for anything so we can move on.
├ Stripping...
└ curl-7.55.1 ................................................ [Updated]
  Running git update for libwebp...
libwebp git ............................................... [Up-to-date]
rubberband 1.8.1 .......................................... [Up-to-date]
  Running git update for zimg...
zimg git .................................................. [Up-to-date]

        Starting 64bit compilation of audio tools
libilbc 2.0.3-dev ......................................... [Up-to-date]
  Running git update for flac...
flac git .................................................. [Up-to-date]
vo-amrwbenc 0.1.3 ......................................... [Up-to-date]
  Running git update for fdk-aac...
fdk-aac git ............................................... [Up-to-date]
  Running git update for libsoxr...
libsoxr git ............................................... [Up-to-date]
libgme 0.6.1 .............................................. [Up-to-date]
libbs2b 3.1.0 ............................................. [Up-to-date]
  Running git update for sndfile...
sndfile git ............................................... [Up-to-date]
sox 14.4.2 ................................................ [Up-to-date]

        Starting 64bit compilation of video tools
  Running git update for librtmp...
┌ librtmp git ..................................... [Newer dependencies]
├ Running uninstall...
├ Running clean...
├ Running install...
├ Stripping...
└ librtmp-git ................................................ [Updated]
  Running git update for vpx...
vpx git ................................................... [Up-to-date]
sdl2 2.0.5 ................................................ [Up-to-date]
  Running git update for libbluray...
libbluray git ............................................. [Up-to-date]
xavs 0.1 .................................................. [Up-to-date]
  Running git update for libzen...
libzen git ................................................ [Up-to-date]
  Running git update for libmediainfo...
┌ libmediainfo git ................................ [Newer dependencies]
├ Running uninstall...
├ Running cmake...
Likely error:
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZenLib: C:/Users/welli/media-autobuild_suite-master/local64/include
CMake Error at CMakeLists.txt:48 (else):
  A duplicate ELSE command was found inside an IF block.

-- Configuring incomplete, errors occurred!
See also "C:/Users/welli/media-autobuild_suite-master/build/libmediainfo-git/build-64bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check C:/Users/welli/media-autobuild_suite-master/build/libmediainfo-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\Users\welli\media-autobuild_suite-master\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1300769/logs.zip)

**Comment by wiiaboo** [comment]
Open the same issue in libmediainfo repository please. The problem is probably on their side.

**Comment by BlackScreen** [comment]
Also breaking at fontconfig...
[logs.zip] (https://0x0.st/72a.zip)

**Comment by wiiaboo** [comment]
fontconfig doesn't use cmake, so I doubt this is the same issue, @BlackScreen.

**Comment by kliffgomel** [comment]
There are no compilation errors of fontconfig now.

**Comment by LigH-de** [comment]
Often there are missing updates after a larger update. Did you try to update again? I remember that ca-certs were post-updated.

I made it a habit to interrupt the build step and restart the suite until no more updates were applied: (`do try2update until !updated; build;`).

**Comment by wiiaboo** [comment]
Can't reproduce.
