### ISSUE TITLE
Build fails at fontconfig

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#605]
Since it is not the same issue as mentioned in #604, I will open another issue...
[logs.zip] (https://0x0.st/72a.zip)

**Comment by laserfoxcn** [comment]
modify the "media-suite_compile.sh",
Line 152: `-e '/^SUBDIRS=/,+2{s;fontconfig.*;fontconfig fc-blanks src;g;/fc-[^b]/d}' \`
delete "fc-blanks"
save it then recompile.
try.

**Comment by BlackScreen** [comment]
Yeah. That fixed it. Thanks!
