### ISSUE TITLE
Dependencies for mpv Vulkan support

### ISSUE THREAD

**Issue by aufkrawall** [jb-alvarado/media-autobuild_suite#608]
Hello,
would it be possible to add those?

Btw: Thanks for this great toolset!

**Comment by wiiaboo** [comment]
Not likely until at least mid of December, at least from me.
If someone else does the work I can merge the PR.

**Comment by wiiaboo** [comment]
Done in https://github.com/jb-alvarado/media-autobuild_suite/commit/7d4f75b7eb028bf5f9009cacb5765cf0fc1248e3.
Only tested with 64-bits.

**Comment by aufkrawall** [comment]
Thanks, it's working without issues for me for mpv vulkan rev2.
