### ISSUE TITLE
Way to detect built version of lib

### ISSUE THREAD

**Issue by wiiaboo** [jb-alvarado/media-autobuild_suite#61]
Most of the built libraries' versions can be detected by using `pkg-config --modversion`, so I'm working on using that instead of simply looking for the static lib's filename.

Some like openjpeg don't build pkg-config files so they'll be harder to detect.

**Comment by jb-alvarado** [comment]
That will be great! There exist a trick to include openjpeg2 in ffmpeg, so 1,5 is not absolutely necessary. When this helps, let's integrate it.
https://github.com/qyot27/mpv/blob/extra-new/DOCS/crosscompile-mingw-tedious.txt

**Comment by wiiaboo** [comment]
Btw, we have to build twolame, since it depends on sndfile. That .txt file actually points to his github which has the fixes to build static twolame easily.

**Comment by wiiaboo** [comment]
Also, if we're building both 32 and 64-bit couldn't we use build32 git repos as remotes for build64? They would trigger in case of an update all the same, we wouldn't need to download the same things twice.

**Comment by jb-alvarado** [comment]
Ah ok, yes then we need to build twolame again. Maybe it was in the list, in the past, so we can take the source from there. 
In the past I also though about it, to use only one build folder, but it is not so easy - the 64 bit builds need to know that the source was updated and it is new.

I can also add you to the list, so it is more easy for you to push changes.

**Comment by wiiaboo** [comment]
I'll try to use branches and pull requests to avoid breaking something.

**Comment by wiiaboo** [comment]
By the way, we can't upgrade openjpeg to 2.0 because FFmbc uses a too old version of FFmpeg that only supports openjpeg 1.x.
But I've been able to compile openjpeg 2.1.0 successfully, without JPIP.

**Comment by jb-alvarado** [comment]
Ah this ffmbc, I wish they work together with the ffmpeg team and and merge the projects :).
