### ISSUE TITLE
more of a comment: Khrono's ICD Loader for OpenCL

### ISSUE THREAD

**Issue by hydra3333** [jb-alvarado/media-autobuild_suite#610]
More of a comment.

I don't know if you build with Khrono's ICD Loader for OpenCL, however if you do then please be aware building it now breaks under the latest commit (at least when cross-compiling under Ubuntu).

6849f617e991e8a46eebf746df43032175f263b3 is last working commit before they broke it (at least when cross-compiling under Ubuntu)

**Comment by wiiaboo** [comment]
I haven't the slightest idea on what that is or how to fix it. Try some place else.
I very much doubt it has something to do with the suite. Try Msys2-packages or Mingw-packages instead.

**Comment by hydra3333** [comment]
OK thanks.  It is apparently used as a part of the OpenCL linking process unless you link against Windows OpenCL dlls.  Cross-compiling ffmpeg with OpenCL using RDP's suite can use the "ICD" if you build it as a dependency, but it is not used by your suite by the looks then.

**Comment by wiiaboo** [comment]
We use import libs made against Windows' OpenCL libs, yes, we don't compile anything related to OpenCL, we just link it.
