### ISSUE TITLE
libopenjpeg not found

### ISSUE THREAD

**Issue by GyanD** [jb-alvarado/media-autobuild_suite#611]
Openjpeg 2.3 was recently released, and the autobuild script upgrades to the new package.

ffmpeg's configure manually checks only upto v2.2, so the script fails with "libopenjpeg not found" .

I've sent a patch to ffmpeg, but till applied, users will need to exclude libopenjpeg for successful compilation.

**Comment by wiiaboo** [comment]
There's been 2 other patches submitted before too. Just ping/RE: them so
they're merged.

**Comment by GyanD** [comment]
Done, and pushed.
