### ISSUE TITLE
FFmpeg build fails with error "libmysofa not found"

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#614]
[logs.zip](https://0x0.st/Cuu.zip)

For some reason libmysofa can't be found by the configure file, even though I definitely have it. Yesterday everything worked fine. Given the timing, I'm guessing this might be the same issue as #613. 
I tried deleting all the libmysofa folders and files and rebuilding it, but ran into the same error:
```
  Running git clone for libmysofa...
┌ libmysofa git ..................................... [Recently updated]
├ Running uninstall...
├ Running cmake...
├ Running install...
├ Stripping...
└ libmysofa-git .............................................. [Updated]
```
...
```
  Running git update for ffmpeg...
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-avisynth --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-cuda --enable-cuvid --enable-schannel --enable-decklink --enable-fontconfig --enable-frei0r --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmfx --enable-libmodplug --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxavs --enable-libxvid --enable-libzimg --enable-openssl --enable-libsnappy --enable-gpl --enable-opengl --enable-libcdio --enable-libfdk-aac --enable-libkvazaar --enable-librubberband --enable-libssh --enable-libtesseract --enable-libzvbi --enable-chromaprint --enable-libopenh264 --enable-libopenmpt --enable-libzmq --enable-libmysofa --enable-libflite --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpng --extra-libs=-lpsapi --disable-w32threads --extra-cflags=-DPTW32_STATIC_LIB --extra-libs=-lpthread --extra-libs=-lwsock32 --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --enable-filter=frei0r --disable-debug
ERROR: libmysofa not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/Media-AB_Suite/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
```

**Comment by Metaphorce812** [comment]
I tried disabling libmysofa for the ffmpeg build and got this error instead: 
`ERROR: libssh not found using pkg-config`
[logs.zip](https://0x0.st/Cu9.zip)

**Comment by wiiaboo** [comment]
Both you and #613: try adding --extralibs=-lz to ffmpeg_options.txt.

**Comment by schmidthubert** [comment]
I'm getting the same error, --extra-libs=-lz doesn't make a difference for me. Is this error maybe the result of https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/6dfcbd80ad446ff163b47f2bf432bbf706436ea8 configure change regarding sofalizer 
`+sofalizer_filter_deps="libmysofa avcodec"`
`+sofalizer_filter_select="fft"`
and/or
`+enabled libmysofa         && require libmysofa "mysofa.h" mysofa_load -lmysofa`
and/or
`+enabled sofalizer_filter    && prepend avfilter_deps "avcodec"`

???

**Comment by wiiaboo** [comment]
Probably not, if ssh also complains about the same missing symbols.

**Comment by kliffgomel** [comment]
same error
[C1N.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1382236/C1N.zip)

**Comment by wiiaboo** [comment]
I can't really debug anything thoroughly until December.
Try opening a bug in FFmpeg's bug tracker (not github's).

**Comment by BlackScreen** [comment]
There is a fix for the libmysofa problem:
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/6b52c0b583b84aa5290f3c8a022deefe8dc2fed1

Sadly, the build is still breaking. I don't know why. Still seems to be something missing.
[logs.zip] (https://0x0.st/Cjc.zip)

**Comment by wiiaboo** [comment]
libssh also needs libz.

**Comment by schmidthubert** [comment]
--extra-libs=-lz still doesn't make any difference if I put that anywhere in my ffmpeg_options.txt. If I add 
the following to media-suite_compile.sh ~line 1438 or so like this 

  `enabled libzvbi && do_addOption --extra-libs=-lpng`
    `enabled frei0r && do_addOption --extra-libs=-lpsapi`
	`do_addOption --extra-libs=-lz`

then I'm getting 
`ERROR: No usable libcdio/cdparanoia found`

Getting from one problem to the next. Where exactly is "QM" here if changing/patching something as MOST important as ffmpegs OWN configure file I wonder??? Is it non-existent as in M$ Gates stupid Windoze clown programmers full of bugs case??? Why the heck the shuffle-around/add/remove etc at all in configure???  I'll give up for today! I'm not the ffmpegs team banana here and have certainly better things to do in my free time ... :-1:

**Comment by schmidthubert** [comment]
Apart from that fontconfig now wants to have freetype 2.8.1, so that can be fixed with:

`    # if do_pkgConfig "freetype2 = 20.0.14" "2.8.0"; then`
`    #    do_wget_sf -h a3c603ed84c3c2495f9c9331fe6bba3bb0ee65e06ec331e0a0fb52158291b40b \`
`    #        "freetype/freetype2/2.8/freetype-2.8.tar.bz2"`
`	if do_pkgConfig "freetype2 = 21.0.15" "2.8.1"; then`
`        do_wget_sf -h bf0a210b6fe781228fa0e4a80691a521 \`
`            "freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2"`

**Comment by schmidthubert** [comment]
It seems building ffmpeg is really broken or better completely f***** up now, nice job! >:-(( ffmpeg-devel ML as in this thread http://ffmpeg.org/pipermail/ffmpeg-devel/2017-October/217858.html has more of what's going on ...  Will probably take them lots of days if not weeks to FIND and fix everything ... :disappointed:

**Comment by wiiaboo** [comment]
@schmidthubert that 2.8.1 change has been made 14 days ago in https://github.com/jb-alvarado/media-autobuild_suite/commit/e706b3a8f7b991a60a3a6e2102323638f95270c8

**Comment by schmidthubert** [comment]
Strange then that my last successful ffmpeg build I could still make on Oct 8 and the suite didn't warn me about this fact, only yesterday after my complete wipe. From https://cgit.freedesktop.org/fontconfig/log/ the requirement for => 2.8.1 happened already on Sep 28 so everyone (like me) who was/is using an older version of your suite should have received the error much earlier. It could mean that something isn't properly cleaned regarding freetype and/or fontconfig when building. Anyway, it's a different problem than this thread. I will download your latest version of the suite now and bring my stuff up to date then. Thanks! :+1:

**Comment by wiiaboo** [comment]
The updates to the suite aren't automatic. There should be a "update_suite.sh" file if you didn't disabled that option in the .ini, and you run it by dragging to the mintty shortcut.

**Comment by BlackScreen** [comment]
I have had succesful builds of FFmpeg from October 11, if I remember correctly. I can check in monday. Maybe we then can narrow it down to when a commit broke the builds.

**Comment by schmidthubert** [comment]
Updated everything and now and the current error is 
`ERROR: zvbi-0.2 not found using pkg-config`
but there are no errors in build/zvbi-0.2.35/build-32bit/ab-suite.configure.log
Must be because of https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/458783315b8fb84e0a06346184b3cf62314c9e2e

So it's still a mess and not fixed completely :-1:

**Comment by wiiaboo** [comment]
It is because of that commit. Every check needs the correct libs now, so you have to let them know of every broken lib so it's fixed upstream.

**Comment by schmidthubert** [comment]
https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/06558100727420f33186e8656936a9373fa647ee
should fix https://github.com/jb-alvarado/media-autobuild_suite/issues/614#issuecomment-336523270 then, will test later ...

**Comment by kliffgomel** [comment]
I in case of compilation have an error now "ERROR: libssh not found using pkg-config".
[CIn.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1386299/CIn.zip)

**Comment by GyanD** [comment]
Same error here. I have to manually tweak ffmpeg's configure to disable libssh, zvbi, libcdio to get configure to complete. Compilation starts but fails when linking ffmpeg_g. harfbuzz, and a few other libs complain of undefined references.

**Comment by schmidthubert** [comment]
The build system is completely f***d now, ssh cdio paranoia gcrypt and other errors. If you want to make a working build without changing lots and lots of things replace the 4 links in media-suite_compile.sh
"https://git.ffmpeg.org/ffmpeg.git" with either

"https://git.ffmpeg.org/ffmpeg.git#commit=58143b15adda6391ec07f3eb19e80ed91d801edd"
or
"https://git.ffmpeg.org/ffmpeg.git#tag=n3.4"
which will get you at least a working stable 3.4 version in the latter case. The former is the last working commit before their configure change which also still works. Everything newer than that doesn't. :-1:

**Comment by hydra3333** [comment]
The ffmpeg maintainers changed the way the ffmpeg configure works.  It's broken pending "upstream" software dependency maintainers adjusting their build systems to be "correct" in specifying which libraries they link to.  Or something like that.   So, ffmpeg git changed something like paraphrased as "extralibs no longer being global after this merge" which broke the building process ... hence one interim a workaround could be add back in lots of "--extra-libs=" to temporarily fix it.   As soon as everything is fixed upstream then we can probably remove the lots of brute-force "--extra-libs=" which make this interim build work.

For some commonly specified dependencies, this is what I use in an ubuntu cross-compile to add to the ffmpeg "configure" line, so I suppsoe an equivalent more or less may do the trick for you.

```
# 2017.10.14 - START add this for various errors per https://patchwork.ffmpeg.org/patch/5540/ - they removed from being extralibs being global any more
    #config_options+=" --extra-libs=-lpthread" # is global again 2017.10.15
    #config_options+=" --extra-libs=-lm" # is global again 2017.10.15
    config_options+=" --extra-libs=-lcrypt32"
    config_options+=" --extra-libs=-lshlwapi"
    config_options+=" --extra-libs=-lstdc++"
    config_options+=" --extra-libs=-lass"
    config_options+=" --extra-libs=-lfontconfig"
    config_options+=" --extra-libs=-lexpat"
    config_options+=" --extra-libs=-lfribidi"
    config_options+=" --extra-libs=-lfreetype"
    config_options+=" --extra-libs=-lharfbuzz"
    config_options+=" --extra-libs=-lbz2"
    config_options+=" --extra-libs=-llzma"
    config_options+=" --extra-libs=-liconv"
    config_options+=" --extra-libs=-lcdio"
    config_options+=" --extra-libs=-lcdio_paranoia"
    config_options+=" --extra-libs=-lz"
    config_options+=" --extra-libs=-lpsapi" # dlfcn [frei0r?] requires this, has no .pc file should put in frei0r.pc? ...
    config_options+=" --extra-libs=-lspeexdsp" # libebur :|
    config_options+=" --extra-libs=-lgdi32"
    #config_options+=" --extra-libs=-luser32"
    config_options+=" --extra-libs=-lwinmm"
#    export LDFLAGS="$LDFLAGS -l-lstdc++ ... etc "
    # 2017.10.14 - END add this for various errors per https://patchwork.ffmpeg.org/patch/5540/ - they removed from being extralibs being global any more
```

**Comment by schmidthubert** [comment]
https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/ae6fe04bee600dec99e81efba3b8350366f6367c
should fix hls+gcrypt errors (why 1.7.8 BTW if there's 1.8.2 already?). Setting cyanrip to 0 or 3 should get anyone rid of any --enable-cdio accociated errors and further down the possible error ladder. Although --enable-gnutls is used by many so no use for openssl actually, but let's see what errors/fixes pop up next then ... :sleeping:

**Comment by GyanD** [comment]
With the latest ffmpeg commit*, it compiles if zvbi is disabled. configure has switched to pkg_config, but I did't find any .pc for zvbi. 

* https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/15b86d3b4aeb51d92687f031934a807fd6f29b99

**Comment by BlackScreen** [comment]
I have opened an issue on the FFmpeg bug tracker. Let's see what happens...
https://trac.ffmpeg.org/ticket/6753#ticket

**Comment by LigH-de** [comment]
^ which advances to the libssh tracker:
https://bugs.libssh.org/T77

**Comment by BlackScreen** [comment]
Seems like it will be a little while. Where can I add the lines to fix building at the moment? Do I have to go with the extra text file for this or can I include it in the build script somehome for the time beeing? I tried looking into it, but did not understand the code entirely.

**Comment by wiiaboo** [comment]
You need to google for the missing references and add the corresponding `--extra-libs=-l<library name>` to ffmpeg_options.txt, probably.

**Comment by BlackScreen** [comment]
Yeah, I actually added all of these in "ffmpeg_options.txt", but building does not work...
```
--extra-libs=-lz
--extra-libs=-lcrypt32
--extra-libs=-lshlwapi
--extra-libs=-lstdc++
--extra-libs=-lass
--extra-libs=-lfontconfig
--extra-libs=-lexpat
--extra-libs=-lfribidi
--extra-libs=-lfreetype
--extra-libs=-lharfbuzz
--extra-libs=-lbz2
--extra-libs=-llzma
--extra-libs=-liconv
--extra-libs=-lcdio
--extra-libs=-lcdio_paranoia
--extra-libs=-lz
--extra-libs=-lpsapi
--extra-libs=-lspeexdsp
--extra-libs=-lgdi32
--extra-libs=-lwinmm
```
The error I get is:
`ERROR: zvbi-0.2 not found using pkg-config`
I could not find the correct library to load.

**Comment by wiiaboo** [comment]
Maybe it doesn't use --extra-libs when checking the external libs.
Try adding them to FFmpeg's configure LDFLAGS (line 1322).

**Comment by schmidthubert** [comment]
Patch to old configure: 
`-enabled libzvbi           && require_pkg_config libzvbi zvbi-0.2 libzvbi.h vbi_decoder_new &&`
`+enabled libzvbi           && require libzvbi libzvbi.h vbi_decoder_new -lzvbi &&`

that nonsense error should go away?

**Comment by wiiaboo** [comment]
No, that'll be worse. The pkg-config should contain at least that -lzvbi and more.

**Comment by hydra3333** [comment]
"Yeah, I actually added all of these in "ffmpeg_options.txt", but building does not work..."
I cross-compile and use those on my ffmpeg configure and it built OK tonight.
Maybe add --extra-libs=-lzvbi for you too ?

**Comment by GyanD** [comment]
I didn't find any .pc for zvbi.

**Comment by hydra3333** [comment]
for interest here's my x63 configure commandline

`# ./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-withOpenCL-master/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --enable-gray --enable-version3 --disable-debug --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --enable-nvenc --enable-cuda --enable-cuvid --enable-d3d11va --enable-libsoxr --enable-fontconfig --enable-libass --enable-libbluray --enable-iconv --enable-libtwolame --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --extra-libs=-loleaut32 --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --enable-bzlib --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxva2 --enable-gray --enable-libopenh264 --enable-libmysofa --enable-libflite --enable-lzma --enable-libsnappy --enable-libzimg --enable-libbs2b --enable-gmp --enable-libfribidi --enable-cross-compile --enable-pic --extra-libs=-lpsapi --extra-libs=-lspeexdsp --disable-schannel --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-gpl --enable-avisynth --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libmfx --enable-avresample --enable-libcdio --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-withOpenCL-master/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-decklink --enable-libfdk-aac --enable-opencl --enable-runtime-cpudetect --extra-libs=-lcrypt32 --extra-libs=-lshlwapi --extra-libs=-lstdc++ --extra-libs=-lass --extra-libs=-lfontconfig --extra-libs=-lexpat --extra-libs=-lfribidi --extra-libs=-lfreetype --extra-libs=-lharfbuzz --extra-libs=-lbz2 --extra-libs=-llzma --extra-libs=-liconv --extra-libs=-lcdio --extra-libs=-lcdio_paranoia --extra-libs=-lz --extra-libs=-lpsapi --extra-libs=-lspeexdsp --extra-libs=-lgdi32 --extra-libs=-lwinmm`

**Comment by wiiaboo** [comment]
There should be a zvbi-0.2.pc. That's what the third parameter for require_pkg_config accepts.

**Comment by hydra3333** [comment]
I see a zvbi-0.2.pc in my build and it contains
`Libs: -L${libdir} -lzvbi -lm -lpthread -lwsock32  -lpthread -lpng -lm -liconv -lpng -lz`

**Comment by wiiaboo** [comment]
There's the -lz there. It should be working.
Can anyone send another log with what's failing?

**Comment by GyanD** [comment]
I get null results for zvbi* under the mediatools folder. I do find libzvbi.h, a, .la under local64/lib and /include.

**Comment by wiiaboo** [comment]
There should be a local64/lib/pkgconfig/zvbi-0.2.pc.

**Comment by schmidthubert** [comment]
Should, but it's not. Because:

Comment from rdp's script section build_zvbi():
`#   there is no .pc for zvbi, so we add --extra-libs=-lpng to FFmpegs configure TODO there is a .pc file it just doesn't get installed [?]`
`#   sed -i.bak 's/-lzvbi *$/-lzvbi -lpng/' "$PKG_CONFIG_PATH/zvbi.pc"`

Note the TODO and the question mark here ...

Other than that: after all zvbi looks "old" to me, no configure.ac for instance. Someone should fork/fix that. Still others can do better: archlinux for instance HAS a [usr/lib/pkgconfig/zvbi-0.2.pc](https://www.archlinux.org/packages/extra/x86_64/zvbi/files/) file. So the src package should have more info about the flow ...

So until some who's able to properly fix this **** (not me) just patch back to ffmpeg old configure regarding this error ...

**Comment by wiiaboo** [comment]
I didn't notice this script wasn't installing the pkgconfig.
Last commit should fix that. Didn't test.

**Comment by schmidthubert** [comment]
The zvbi-0.2 error is gone at least, thanks. :+1:  I've replaced
 
`do_pkgConfig "ZVBI = 0.2.35"; then`
with
`do_pkgConfig "zvbi-0.2 = 0.2.35"; then`

though :wink:

**Comment by wiiaboo** [comment]
Yeah, fixed.

**Comment by schmidthubert** [comment]
While at it you can change your line 1221

`do_addOption --extra-cflags=-DLIBSSH_STATIC "--extra-ldflags=-Wl,--allow-multiple-definition"`
to
`do_addOption --extra-libs=-lz --extra-cflags=-DLIBSSH_STATIC "--extra-ldflags=-Wl,--allow-multiple-definition"`

That's [your own fix](https://github.com/jb-alvarado/media-autobuild_suite/issues/614#issuecomment-336318379) too  :wink:

**Comment by wiiaboo** [comment]
I committed a better fix.

**Comment by schmidthubert** [comment]
Thanks! :+1: 

BTW: building cyanrip.exe now fails with "more undefined references to `omp_unset_lock' follow" and some other references to omp_, but I don't use that anyway. Just in case this has something todo with your latest cdio change in the suite?

**Comment by wiiaboo** [comment]
Dunno. Have to check when I get home. Probably missing some -lgomp somewhere.

**Comment by wiiaboo** [comment]
Going to need some log with cyanrip. Mine isn't failing.

**Comment by schmidthubert** [comment]
Maybe it's me then, too many tests/changes recently. Let me cleanup again and do 1 or 2 more rounds first. cyanrip=3 was/is ok, but cyanrip=1 was failing with those errors referring to libsox lib IIRC. Did you try toggling that switch?

**Comment by Metaphorce812** [comment]
Just tried the latest version and it didn't even get to ffmpeg because it failed building libmediainfo:
[logs.zip](https://0x0.st/srpI.zip)
 ```
Running git update for libmediainfo...
┌ libmediainfo git .................................. [Recently updated]
├ Running cmake...
Likely error:

  but not all the files it references.

Call Stack (most recent call first):
  Z:/Media-AB_Suite/local64/lib/cmake/zenlib/ZenLibConfig.cmake:28 (include)
  CMakeLists.txt:37 (find_package)
```

**Comment by schmidthubert** [comment]
That's a Windoze 10 error and probably nothing todo with the problems we're talking about here. Let me google that for you: http://bfy.tw/Ebgs So your problem is elsewhere. Bill Gate$ once said all you will ever need is 64kB RAM, but he didn't talk just stack variables back then. ;) Nowadays he looks like an idiot when there's powershell and bash for windoze when for ages he was BASHing everyone using the cmdline LOL ... :):)

**Comment by schmidthubert** [comment]
>Going to need some log with cyanrip. Mine isn't failing.

Mine still is with setting cyanrip=1 in the ini. I'm doing the following now: my ffmpeg_options.txt + my media-autobuild_suite.ini copied into the suites build directory from a fresh download from here. Let's see if it fails again ...

**Comment by schmidthubert** [comment]
Here's logs.zip for the cyanrip error. 
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1404681/logs.zip)

**Comment by wiiaboo** [comment]
> Just tried the latest version and it didn't even get to ffmpeg because it failed building libmediainfo:

Looks like libzen is missing, for some reason.

> Mine still is with setting cyanrip=1 in the ini.

It's strongly encouraged that you re-compile FFmpeg for cyanrip. There's a lot of trash in FFmpeg that cyanrip doesn't remotely need.
But it sounds like FFmpeg isn't adding libsoxr's openmp extralibs to the pkg-config, so it's a FFmpeg issue.

**Comment by schmidthubert** [comment]
>It's strongly encouraged that you re-compile FFmpeg for cyanrip.

Sorry, what do you mean by that? This was a fresh build just for you, which builds ffmpeg.exe just fine and which was configured with "--enable-libsoxr"  and "--enable-libopenmpt". And I already explained that setting cyanrip=3 works fine and this is what I normally use, I don't have any use for cyanrip.exe and could use cyanrip=2 as well here. Setting cyanrip=1 was just for fun when this error occured. And I thought it must be YOU who needs to maybe do something about this error since it's your script on line 1607 which tests for cyanrip=1 and this it when fails. I don't understand how this is an ffmpeg issue when ffmpeg with all my options I normally use builds just fine again? :confused:

**Comment by wiiaboo** [comment]
cyanrip doesn't use 99% of what's considered a full FFmpeg build. So option 3 is strongly preferred to 1.

It's a FFmpeg issue in the sense that their pkg-config is lacking some libs that are needed to compile stuff using FFmpeg.

I wonder why cyanrip is failing but mpv isn't though. Maybe because cyanrip checks for individual libs and not all of them together like mpv.

**Comment by wiiaboo** [comment]
It's probably fixed now, you just need to recompile libsoxr and it won't require -lgomp anymore.

I managed an almost-full build now, so I'll consider this issue fixed.

**Comment by schmidthubert** [comment]
Yes, the builds completed! :+1:
