### ISSUE TITLE
L.A.M.E. v3.100

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#618]
Not sure if this is the right place but here we go......

The new MSYS2 Packages for L.A.M.E. v3.100 is available (https://quodlibet.duckdns.org/msys2/base/mingw-w64-lame) but for some reason so doesn't the suite get updated with them. I've tested manually to install them (through minty with the pacman installation command for the packages in question) but when the suite runs so do the v3.99.5 binaries still get compiled and not v3.100. 

Hope for that someone have a solution to this issue

**Comment by wiiaboo** [comment]
It'll get updated when they compile it and upload the package.

**Comment by Barough** [comment]
Thanks for the reply/info.

Noticed now that they're working on the packages. Last Update: 2017-10-24 19:06:08

**Comment by Metaphorce812** [comment]
@Barough If you need a pre-compiled Windows version of LAME 3.100 in the meantime, you can download it from [RareWares.org](http://www.rarewares.org/mp3-lame-bundle.php)

**Comment by BlackScreen** [comment]
It seems like they are compiled.
https://quodlibet.duckdns.org/msys2/package/mingw-w64-x86_64-lame?repo=mingw64
But they did not install on my end. Still the old lame 3.99.5...

**Comment by wiiaboo** [comment]
That's not the official repository.

**Comment by BlackScreen** [comment]
Ah ok. Then I'll wait for the official version.

**Comment by wiiaboo** [comment]
I see there's a 3.100 already in mingw repositories. I forgot the suite also compiles its own, for the standalone binary. I'll update it in the weekend.

**Comment by Barough** [comment]
@wiiaboo 
Any progress regarding the suites own complies?

**Comment by wiiaboo** [comment]
Should be able to do it this week, finally finished what was keeping me busy.

**Comment by Barough** [comment]
That's great news. :)

**Comment by wiiaboo** [comment]
Done in https://github.com/jb-alvarado/media-autobuild_suite/commit/e8e63ecb3caa9f39a2ec726d7c1d807e29526e5a

**Comment by Barough** [comment]
Thnx a lot :)
