### ISSUE TITLE
Running git update for harfbuzz fail

### ISSUE THREAD

**Issue by dooley2009** [jb-alvarado/media-autobuild_suite#620]
Please find the zip with my logs.
https://0x0.st/ssO9.zip

I have had this happen on two separate computers. I have no idea what is going on or how to fix it. I never had any problems before compiling.

Any help would be greatly appreciated.

**Comment by laurfb** [comment]
Change line 161 in media-suite_compile.sh to:
    if [[ $ffmpeg != "sharedlibs" ]] && do_vcs "https://github.com/behdad/harfbuzz.git#commit=5014c60^"; then

regards,
laur

**Comment by wiiaboo** [comment]
Let them know: https://github.com/behdad/harfbuzz/issues

**Comment by dooley2009** [comment]
Very good laurfb. That seems to have fixed the issue. Many thanks.

**Comment by ebraminio** [comment]
hb-uniscribe build on harfbuzz is currently broken and [this](https://github.com/jb-alvarado/media-autobuild_suite/blob/c1a36d60eb62f2e612c35cdaa0cc977b63368f63/build/media-suite_compile.sh#L166) apparently suggests hb-uniscribe is enabled but I can't see how. As most projects don't need that, like Chrome/Chromium, can you disable it in meanwhile? It will save some kilobytes also.

**Comment by wiiaboo** [comment]
Committed that disabling of uniscribe, can anyone check if that fixes it?

**Comment by laurfb** [comment]
Hi. Yes, you can closed the ticket.
regards,
laurb

**Comment by dooley2009** [comment]
Laurb fixed the issues pretty quickly for me. Spot on with line 161 code change. 

Thanks again fellas. Y’all are on the ball. 

--
Regards,

Jeff

**Comment by ebraminio** [comment]
Uniscribe is fixed on upstream but please keep it disabled as it is just not needed, its use is comparing harfbuzz shaping against uniscribe and it shouldn't be needed outside the harfbuzz project mostly. Thanks everyone.
