### ISSUE TITLE
FFmpeg compiling error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#623]
ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK!
FFmpeg and related apps will depend on Nvidia drivers!
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error:
D:/ffmpeg-autobuild/build/ffmpeg-git/libavformat/tls_openssl.c:285:5: error: implicit declaration of function 'BIO_meth_set_create'; did you mean 'BIO_gethostbyname'? [-Werror=implicit-function-declaration]
     BIO_meth_set_create(p->url_bio_method, url_bio_create);
     ^~~~~~~~~~~~~~~~~~~
     BIO_gethostbyname
D:/ffmpeg-autobuild/build/ffmpeg-git/libavformat/tls_openssl.c:286:5: error: implicit declaration of function 'BIO_meth_set_destroy'; did you mean 'ff_mutex_destroy'? [-Werror=implicit-function-declaration]
     BIO_meth_set_destroy(p->url_bio_method, url_bio_destroy);
     ^~~~~~~~~~~~~~~~~~~~
     ff_mutex_destroy
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavformat/tls_openssl.o] Error 1
make failed. Check D:/ffmpeg-autobuild/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
[ssn3.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1440536/ssn3.zip)

**Comment by vxd123** [comment]
I'm getting the exact same error at my end, tried excluding openssl, libssh, gnutls in configure options to get rid it to build but to no avail.

**Comment by Metaphorce812** [comment]
I'm still having the same issue as well - first referenced in #622 . Tried disabling openssl and gnutls and it still didn't compile. Even tried deleting MABS and starting from scratch and didn't fix it.
[logs.zip](https://0x0.st/szXM.zip)

**Comment by schmidthubert** [comment]
Use --enable-gnutls ...

**Comment by Metaphorce812** [comment]
I've tried it with the default full build settings, and with the ffmpeg_options.txt file with only --enable-gnutls, but not openssl, and vice versa. Also tried it without either of them enabled. I get the same error message every time.

**Comment by GyanD** [comment]
Received same error here.

**Comment by GyanD** [comment]
Omitting openssl worked here.

**Comment by vxd123** [comment]
I've commented out openssl & schannel in ffmpeg_options.txt the rest is enabled. That got it compiled for me.

**Comment by clampak** [comment]
I have this same issue, but the ffmpeg_options.txt file is missing in mine.  What does it look like?

**Comment by Metaphorce812** [comment]
@clampak ffmpeg_options.txt is only created (in the "build" folder) if you select option 1 ("Yes") for "Choose ffmpeg and mpv optional libraries?" when you first run the suite. If you go into the "build" folder, you can edit "media-autobuild_suite.ini" and change "ffmpegChoice=_#_" to "ffmpegChoice=1". That should create the file the next time you run the suite.

**Comment by Metaphorce812** [comment]
MABS just successfully built ffmpeg for me when I used ffmpeg_options.txt and un-commented every option (thereby enabling them) except for "--enable-openssl" (thereby excluding it from the build).
I've attached my ffmpeg_options.txt file with a comment about gnutls and openssl if anyone wants to use it (remember it will only work if "ffmpegChoice=1" is set in "media-autobuild_suite.ini").
[ffmpeg_options.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1444373/ffmpeg_options.txt)

**Comment by LigH-de** [comment]
You seem to agree that the generation of the build options file should be changed. So I will close [ffmpeg ticket #6801](https://trac.ffmpeg.org/ticket/6801).

**Comment by wellivea1** [comment]
https://0x0.st/szCX.zip same here

**Comment by LigH-de** [comment]
I wonder if this ffmpeg commit caused it:

[avformat/tls_openssl: move some functions up in the file](https://github.com/FFmpeg/FFmpeg/commit/eaa25b09e4116f2fd649c8638021514911e908c9)

In the ffmpeg ticket 6801 (which was reopened), 'cehoyos' mentioned a patch fixing it, but I don't see any more recent commits related to "tls" or "ssl".

**Comment by LigH-de** [comment]
Check #630: ffmpeg builds after patching the gnutls installation (to retrieve the directory content and download a version 3.6.1+ via https instead of ftp) and disabling openssl, in favour of gnutls.

**Comment by kliffgomel** [comment]
If to apply the specified patches, then errors in case of compilation do not arise. Then why these patches are not applied directly in the original project?

**Comment by LigH-de** [comment]
Because I am only a contributor, not a developer. I do not understand the whole project. I don't know where the best position in the sources is to fix it in a way that the suite will also generate a correct `ffmpeg_options.txt` in the future. And on top, I am not experienced with submitting patches in this github environment, I am afraid to mess something up. Finally, I probably don't have "commit" rights here anyway.

**Comment by wiiaboo** [comment]
Doing a pull request doesn't merge automatically and doesn't mess anything.

If you know how to fix something, a pull request is good enough.

**Comment by sftt** [comment]
[logs.zip](https://0x0.st/soWy.zip)

**Comment by wiiaboo** [comment]
Fixing this would involve not using `--enable-openssl` in FFmpeg or replacing LibreSSL with OpenSSL. I have zero time to do the latter, so if someone does a pull request with that, I'd merge it.

**Comment by LigH-de** [comment]
This issue can be closed, ffmpeg builds again (shared and static).

**Comment by wellivea1** [comment]
https://0x0.st/sHTS.zip Still shows an error for me.

**Comment by wiiaboo** [comment]
@wellivea1  That error is unrelated to FFmpeg. Force recompilation of soxr.

**Comment by wellivea1** [comment]
@wiiaboo How do I force recompilation of soxr?

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/doc/forcing-recompilations.md
