### ISSUE TITLE
www.webdav.org not reachable 

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#624]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1441553/logs.zip)
can't compile suite without  ...
is there any alternate adress?

**Comment by Metaphorce812** [comment]
I had the same problem. I just downloaded neon-0.30.2.tar.gz from [here](https://ftp.osuosl.org/pub/blfs/conglomeration/neon/neon-0.30.2.tar.gz), put it in the "build" folder, and it worked.

**Comment by ASopH** [comment]
Yes, thanks for your help!
