### ISSUE TITLE
MPV fails because it needs a fork from ffmpeg from https://github.com/mpv-player/ffmpeg-mpv

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#625]
MPV can't find the correct ffmpeg libs/headers and says: 
Unable to find development files for some of the required FFmpeg/Libav libraries. You need git master. **For FFmpeg, the mpv fork,** that might contain additional fixes and features **is required**. It is available on **https://github.com/mpv-player/ffmpeg-mpv**  Aborting.

```
Checking for Direct3D support                                     : yes
Checking for Raspberry Pi support                                 : no
Checking for iOS OpenGL ES hardware decoding interop support      : no
Checking for OpenGL without platform-specific code (e.g. for libmpv) : yes
Checking for MALI via Linux fbdev                                    : libdl not found
Checking for OpenGL context support                                  : yes
Checking for Vulkan context support                                  : no ('vulkan' not found)
Checking for libshaderc SPIR-V compiler                              : no
Checking for EGL helper functions                                    : yes
Checking for FFmpeg/Libav present                                    : yes
Checking for libav* is FFmpeg mpv modified version                   : no
Checking for libav* is upstream FFmpeg (unsupported)                 : disabled
Checking for libav* is Libav                                         : no
Checking for Libav/FFmpeg library versions                           : ffmpeg-mpv not found
Unable to find development files for some of the required FFmpeg/Libav libraries. You need git master. For FFmpeg, the mpv fork, that might contain additional fixes and features is required. It is available on https://github.com/mpv-player/ffmpeg-mpv Aborting.
This is required for other packages, so this script will exit.
  Creating diagnostics file in mpv-git

All relevant logs have been anonymously uploaded to https://0x0.st/ssF5.zip
Copy and paste [logs.zip](https://0x0.st/ssF5.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
```
Do we need to compile 2 versions from ffmpeg ??

**Comment by wiiaboo** [comment]
Yeah, no, I don't have any time to deal with a short-lived fork. Add `--enable-ffmpeg-upstream` to mpv_options.txt, or just disable mpv meanwhile.

**Comment by schmidthubert** [comment]
Same error with --enable-ffmpeg-upstream 

`+ mpv git ........................................... [Recently updated]`
`+ Running configure...`
`Likely error:`
`Checking for OpenGL context support                                  : yes`
`Checking for Vulkan context support                                  : no ('vulkan' not found)`
`Checking for libshaderc SPIR-V compiler                              : no`
`Checking for EGL helper functions                                    : yes`
`Checking for FFmpeg/Libav present                                    : yes`
`Checking for libav* is FFmpeg mpv modified version                   : no`
`Checking for libav* is upstream FFmpeg (unsupported)                 : yes`
`Checking for libav* is Libav                                         : no`
`Checking for Libav/FFmpeg library versions                           : no ('libavutil >= 56.0.100 libavcodec >= 58.2.100 libavformat >= 58.0.102 libswscale >= 5.0.101 libavfilter >= 7.0.101 libswresample >= 3.0.100' not found)`
`Unable to find development files for some of the required FFmpeg/Libav libraries. You need git master. For FFmpeg, the mpv fork, that might contain additional fixes and features is required. It is available on https://github.com/mpv-player/ffmpeg-mpv Aborting.`

**Comment by schmidthubert** [comment]
The error says libavcodec >= 58.2.100 is required but if I look at build\ffmpeg-git\libavcodec\version.h it reads 
`#define LIBAVCODEC_VERSION_MAJOR  58`
`#define LIBAVCODEC_VERSION_MINOR   1`
`#define LIBAVCODEC_VERSION_MICRO 100`

???

This is ffmpeg master. Is this a typo at mpv's end or is this the ffmpeg team again???

**Comment by schmidthubert** [comment]
Seems it's mpv,  they did "Update FFmpeg URL, drop support for FFmpeg releases" in https://github.com/mpv-player/mpv-build/commit/f1a45b0c9d20a754b8f0d51c7a264d7dbfeac4c4 and their libavcodec version in https://github.com/mpv-player/mpv-build indeed reads 58.2.100 now ...

**Comment by schmidthubert** [comment]
https://github.com/mpv-player/mpv/issues/5066
So it's sit and wait as usual then ... :ambulance:

**Comment by schmidthubert** [comment]
Changing 
`if do_vcs "https://github.com/mpv-player/mpv.git"; then`
to
`if do_vcs "https://github.com/mpv-player/mpv.git#tag=v0.27.0"; then`
will work as well for now :circus_tent:

**Comment by pat357** [comment]
I"m closing this issue because we have no influence on the way MPV uses their own ffmpeg fork.
