### ISSUE TITLE
Webdav.org denies Connection

### ISSUE THREAD

**Issue by Gnarmagon** [jb-alvarado/media-autobuild_suite#626]
The Batch file can't download neon and stops at this point.
Doesn't work in Browser too -.-

**Comment by fast9881** [comment]
I solved this by modifying `http://www.webdav.org/neon/neon-0.30.2.tar.gz` to `https://fossies.org/linux/www/neon-0.30.2.tar.gz`

**Comment by wiiaboo** [comment]
Duplicate of https://github.com/jb-alvarado/media-autobuild_suite/issues/624
