### ISSUE TITLE
Can't compile ffmpeg with libnpp

### ISSUE THREAD

**Issue by SamusAranX** [jb-alvarado/media-autobuild_suite#628]
I downloaded the CUDA Toolkit from Nvidia and installed it, just to be sure.
Here's my ffmpeg_options.txt:
```
# Lines starting with this character are ignored
--enable-avisynth
--enable-gcrypt
--enable-libmp3lame
--enable-libopus
--enable-libvorbis
--enable-libvpx
--enable-libx264
--enable-libx265
--enable-cuda
--enable-cuvid
--enable-schannel
# Zeranoe
--enable-decklink
--enable-fontconfig
--enable-frei0r
--enable-gnutls
--enable-libass
--enable-libbluray
--enable-libbs2b
--enable-libcaca
--enable-libfreetype
--enable-libfribidi
--enable-libgme
--enable-libgsm
--enable-libilbc
--enable-libmfx
--enable-libmodplug
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-libopenjpeg
--enable-librtmp
--enable-libsoxr
--enable-libspeex
--enable-libtheora
--enable-libtwolame
--enable-libvidstab
--enable-libvo-amrwbenc
--enable-libwavpack
--enable-libwebp
--enable-libxavs
--enable-libxvid
--enable-libzimg
#--enable-openssl
--enable-libsnappy
--enable-gpl
# Full
--enable-opencl
--enable-opengl
--enable-libcdio
--enable-libfdk-aac
--enable-libkvazaar
--enable-librubberband
--enable-libssh
--enable-libtesseract
--enable-libzvbi
--enable-chromaprint
--enable-libopenh264
--enable-libopenmpt
--enable-libnpp
--enable-libzmq
--enable-libmysofa
--enable-cuda-sdk
--enable-libflite
```
Except for openssl, which was causing the build to fail, everything's enabled.
Running this command
`.\ffmpeg.exe -hwaccel cuvid -c:v h264_cuvid -i "4k_test.mp4" -vf scale_npp=-1:720 -c:v h264_nvenc -preset slow test.mp4`
with the resulting ffmpeg build results in this error message:
```
[AVFilterGraph @ 000001768a61ac60] No such filter: 'scale_npp'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!
```

Are there any additional steps I have to take in order for the accelerated scale filter to work?

**Comment by schmidthubert** [comment]
Try this: 
`... -vf "format=yuv420p|cuda,hwupload,scale_npp=w=720:h=-2:format=yuv420p,hwdownload" ...`
Use -2 not -1 otherwise you'll get odd numbers at times which aren't "standard" ...

**Comment by wiiaboo** [comment]
`ffmpeg -filters` should show `scale_npp`, first of all. If not, you didn't compile it in. If cuda SDK was installed properly, the compile.log should have warned "FFmpeg and related apps will depend on CUDA SDK!" somewhere. If not, you didn't install the SDK correctly. Btw, it'll only work with 64-bit.

**Comment by schmidthubert** [comment]
With --enable-cuda-sdk you can use 
`... -vf scale_cuda=-2:720 ...`
directly, but that's only for 264/265 input material ...

**Comment by SamusAranX** [comment]
Turns out that a standard Visual Studio install doesn't include cl.exe anymore, which is _extremely bad_ if you want to actually, like, compile something.
Re-installing Visual Studio fixed all of my problems.
