### ISSUE TITLE
fontconfig build fails

### ISSUE THREAD

**Issue by GyanD** [jb-alvarado/media-autobuild_suite#629]
After git update, fontconfig is stuck at `Running autogen`. Examining the log in the FC repo dir reveals that autogen is waiting for user input: "Press Return key to ...".  So, pressing Return key -- twice, there's a 2nd instance of expected user input -- allows it to proceed to 'configure'. But that fails. Turns out a recent commit requires an updated version of autotools, afaict.

Changing the repo fetch from

`do_vcs "https://anongit.freedesktop.org/git/fontconfig"`

to

`do_vcs "https://anongit.freedesktop.org/git/fontconfig#commit=0c149259"`

 in `build/media-suite_compile.sh`  works

**Comment by BlackScreen** [comment]
Yes, I am having the same issue. Here are logs...
[logs.zip] (https://0x0.st/szV2.zip)

**Comment by BlackScreen** [comment]
Still not working for me. Stuck at autogen again.
When I press enter a few times, it goes on to configure and breaks at make.
See: [logs.zip](https://0x0.st/szwL.zip)

**Comment by kliffgomel** [comment]
I have the same.

**Comment by wiiaboo** [comment]
Try d597900. If it's still not working, I don't give a shit anymore. Someone else fix this.

**Comment by BlackScreen** [comment]
Well, fontconfig builds now, but it is now stuck at libgcrypt... :(

**Comment by schmidthubert** [comment]
>Someone else fix this.
@rdp has
`--prefer-stable=y build a few libraries from releases instead of git master`
in his script. Maybe you should think of such a switch as well. I for don't give a shit if some lazy kid brought out version 175.16747.1564.2 instead of .1 but did "forget" to test the crap s/he produced ... :roller_coaster:
