### ISSUE TITLE
Syntac Error

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#63]
After the first run he close any new start immediately. 
He report:
"(" kann syntaktisch an dieser Stelle nicht verarbeitet werden. (That should be something like "syntax error near unexpected token")

i have to delete the config file and start again for a new run.

**Comment by jb-alvarado** [comment]
Thank you for the report. Comes this in the batch file?

**Comment by nille02** [comment]
It comes if i launch media-autobuild_suite.bat and a config file is present

**Comment by jb-alvarado** [comment]
Ah, you mean a ini file. Ok I need to look at this. Yesterday comes some big patches from Ricardo, maybe they works not so good together with a old build. But maybe we can fix that.

**Comment by nille02** [comment]
this happen also with a new setup. after the problem i started again from zero and its the same.

**Comment by jb-alvarado** [comment]
Oh, ok that is not good... I try to fix that later.

**Comment by jb-alvarado** [comment]
Ok, the error is fixed.
