### ISSUE TITLE
suite hangs after libass-git

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#631]
after new build-setup - no logs:
[nologs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1463734/nologs.zip)

**Comment by ASopH** [comment]
now after libgcrypt 1.7.8 ?? -- strange ??

**Comment by kliffgomel** [comment]
There is no such problem now.

**Comment by ASopH** [comment]
after fresh install of mas it's hanging after updated libgcrypt-1.7.8 - no logs 
[nologs_build.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1487973/nologs_build.zip)

**Comment by nille02** [comment]
i have the same problem. i cause is gnutls and it hangs at

**Comment by wiiaboo** [comment]
Duplicate oof https://github.com/jb-alvarado/media-autobuild_suite/issues/631
