### ISSUE TITLE
fribidi url is wrong,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#634]
``
fribidi 0.19.7 ......................................... [Not installed]
└ fribidi-0.19.7 .............................................. [Failed]
Error 404 while downloading http://fribidi.org/download/fribidi-0.19.7.tar.bz2
``
needs to be:
``
https://github.com/fribidi/fribidi/archive/0.19.7.tar.gz
``
or
``
http://pkgs.fedoraproject.org/repo/pkgs/fribidi/fribidi-0.19.7.tar.bz2/6c7e7cfdd39c908f7ac619351c1c5c23/fribidi-0.19.7.tar.bz2
``

**Comment by hydra3333** [comment]
Ah, maybe not github.

2017.11.17 - https://www.fribidi.org redirect to https://github.com/fribidi
BUT BUT BUT https://github.com/fribidi/fribidi/issues/28#issuecomment-344826192 says in part
"I recently noticed when trying to build with cerbero that this file has disappeared.
I tried to replace it with this archive https://github.com/fribidi/fribidi/archive/0.19.7.tar.gz,
but got strange build errors.
After looking at the source side by side
(I happened to have a copy of the original .tar.bz2),
I could see that the two archives did not contain the same content."

Also see this
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/277#issuecomment-344964369

**Comment by kliffgomel** [comment]
fixed
