### ISSUE TITLE
 vorbis-tools make failed

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#637]
``Likely error:
              ^~~~~~~
In file included from ../../intl/dcigettext.c:67:0:
H:/media-autobuild_suite_4_32bit/msys64/mingw32/i686-w64-mingw32/include/string.   h:52:18: note: previous declaration of 'mempcpy' was here
   void * __cdecl mempcpy (void *_Dst, const void *_Src, size_t _Size);
                  ^~~~~~~
make[2]: *** [Makefile:215: dcigettext.o] Error 1
make[2]: Leaving directory '/build/vorbis-tools-git/build-32bit/intl'
make[1]: *** [Makefile:497: all-recursive] Error 1
make[1]: Leaving directory '/build/vorbis-tools-git/build-32bit'
make: *** [Makefile:427: all] Error 2
``
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1485475/logs.zip)

**Comment by Selur** [comment]
aborting and restarting causes an error during configure
[logs.zip](https://0x0.st/s-BA.zip)

**Comment by wiiaboo** [comment]
https://github.com/xiph/vorbis-tools/issues
