### ISSUE TITLE
sndfile build failure

### ISSUE THREAD

**Issue by aswin1980** [jb-alvarado/media-autobuild_suite#639]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1498767/logs.zip)
Hi,
when compiling using the script the build file during sndfile build failure.

Let me know if you need any other information.
Enclosed the zip file.

Thanks
Aswin

**Comment by aswin1980** [comment]
Hi,
The failure is due to it cannot run autogen. Checked autogen manually and this is the error.
 autogen
C:/media-autobuild_suite/msys64/usr/bin/autogen.exe: error while loading shared libraries: msys-guile-2.0-22.dll: cannot open shared object file: No such file or directory
.
Any idea how to solve the problem.

Thanks
Aswin

**Comment by wiiaboo** [comment]
Yeah, let MSYS2 people know autogen is broken.

**Comment by Sparktank** [comment]
how do we know that?

**Comment by aswin1980** [comment]
Hi,
I downloaded the msys2 and installed it on my system. Also installed autogen using pacman. When i run autogen, it did not complain about missing dll and it did show the version as 5.18.4.

Either msys is broken or the script is broken.

Dont know who is broken. Anyway raised the issue at msys2
https://github.com/msys2/msys2/issues/116

Thanks

**Comment by aswin1980** [comment]
Hi,
Looks like msys2 is broken. Did pacman update and executed autogen, failed with the above mentioned error.

Thanks

**Comment by hydra3333** [comment]
Hmmm. It just built OK for me using a variation of rdp's cross-compile script. 
mingw built as 
`--mingw-w64-ver=5.0.2 --binutils-ver=2.29 --gcc-ver=7.2.0 --pthreads-w32-ver=2-9-1 --disable-shared --enable-gendef --enable-widl --enable-nls --clean-build`
So, I'm wondering why msys2 is said to be broken ?
```
build_libsndfile() {
echo "---------------------------------------------------------------------------------------------------"
echo "---------------------------------------------------------------------------------------------------"
echo "build_libsndfile \"${1}\" ... expected parameter 1 = \"install-libgsm\""
echo "---------------------------------------------------------------------------------------------------"
echo "---------------------------------------------------------------------------------------------------"
  do_git_checkout https://github.com/erikd/libsndfile.git
  cd libsndfile_git
    if [[ ! -f Makefile.am.bak ]]; then # Library only.
      sed -i.bak "/^SUBDIRS/s/=.*/= src/" Makefile.am || exit 1 
    fi
    generic_configure "--disable-sqlite --disable-external-libs --disable-full-suite"
    do_make_and_make_install
    if [ "$1" = "install-libgsm" ]; then
      #if [[ ! -f $mingw_w64_x86_64_prefix/lib/libgsm.a ]]; then
        install -m644 src/GSM610/gsm.h $mingw_w64_x86_64_prefix/include/gsm.h || exit 1
        install -m644 src/GSM610/.libs/libgsm.a $mingw_w64_x86_64_prefix/lib/libgsm.a || exit 1
      #else
      #  echo "already installed GSM 6.10 ..."
      #fi
    fi
  cd ..
}
```

**Comment by wiiaboo** [comment]
Well, I don't see autogen being used anywhere, so that's why.
MSYS2 autogen.exe IS broken since it wasn't rebuilt with the newer libguile, so it is a MSYS2 issue.

**Comment by hydra3333** [comment]
ok thank you for clarifying

**Comment by Metaphorce812** [comment]
So in the meantime the "fix" to get the suite to run all the way through is to just disable sox (set `soxB=2` in `media-autobuild_suite.ini`).

**Comment by aswin1980** [comment]
Any impact?
I hope not...

**Comment by Metaphorce812** [comment]
@aswin1980 Well, a new version of sox won't get built and if you have `--enable-libbs2b` enabled in `ffmpeg_options.txt` then I think ffmpeg will be built with the latest version of libbs2b you had before MSYS2 messed up sox and libsndfile[which is a compenent of libbs2b]. But I got the suite to run all the way through by disabling sox.

**Comment by aswin1980** [comment]
Ok great. ill try that.

**Comment by LigH-de** [comment]
It seems to me (based on reading **var/log/pacman.log**) that libguile was updated more recently than autogen.

`[2017-05-24 14:44] [ALPM] installed libguile (2.0.11-3)`
`[2017-05-24 14:44] [ALPM] installed autogen (5.18.4-2)`

`[2017-06-06 16:33] [ALPM] upgraded libguile (2.0.11-3 -> 2.0.14-1)`
`[2017-06-06 16:33] [ALPM] upgraded autogen (5.18.4-2 -> 5.18.12-1)`

`[2017-11-22 11:58] [ALPM] upgraded libguile (2.0.14-1 -> 2.2.2-1)`
But no equally recent update of autogen.

**Comment by Selur** [comment]
Might be related:

> ┌ sndfile git ....................................... [Recently updated]
├ Running autogen...
Likely error:
checking for autogen ...
You must have GNU autogen installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
no
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
autogen failed. Check H:/media-autobuild_suite/build/sndfile-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/soYk.zip
Copy and paste [logs.zip](https://0x0.st/soYk.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
I said exactly that in https://github.com/jb-alvarado/media-autobuild_suite/issues/639#issuecomment-346938038

Until they merge the PR fixing this and release a new version of autogen, this issue won't be fixed.

See https://github.com/Alexpux/MSYS2-packages/pull/1075
