### ISSUE TITLE
opencore-amrnb build failed. 

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#64]
Package opencore-amrnb was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencore-amrnb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencore-amrnb' found
--2015-03-24 08:24:23--  http://downloads.sourceforge.net/project/opencore-amr/o                                                   pencore-amr/opencore-amr-0.1.3.tar.gz
Auflösen des Hostnamens »downloads.sourceforge.net (downloads.sourceforge.net)«                                                    … 216.34.181.59
Verbindungsaufbau zu downloads.sourceforge.net (downloads.sourceforge.net)|216.3                                                   4.181.59|:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Found
Platz: http://vorboss.dl.sourceforge.net/project/opencore-amr/opencore-amr/openc                                                   ore-amr-0.1.3.tar.gz [folgend]
--2015-03-24 08:24:24--  http://vorboss.dl.sourceforge.net/project/opencore-amr/                                                   opencore-amr/opencore-amr-0.1.3.tar.gz
Auflösen des Hostnamens »vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)                                                   « … fehlgeschlagen: Name or service not known.
wget: Host-Adresse »vorboss.dl.sourceforge.net« kann nicht aufgelöst werden
tar: opencore-amr-0.1.3.tar.gz: Funktion open fehlgeschlagen: No such file or di                                                   rectory
tar: Error is not recoverable: exiting now
rm: das Entfernen von „opencore-amr-0.1.3.tar.gz“ ist nicht möglich: No such fil                                                   e or directory
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 757:                                                    cd: opencore-amr-0.1.3: No such file or directory
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 759:                                                    ./configure: No such file or directory
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.                                                     Schluss.
make: *** Keine Regel, um „install“ zu erstellen.  Schluss.
-------------------------------------------------
build opencore-amr-0.1.3 failed...
delete the source folder under '/build64' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window

**Comment by jb-alvarado** [comment]
I think it works now, please try it again.

**Comment by nille02** [comment]
I start again from zero and now he get troubles earlier 

Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 107: [: ==: Einstelliger (unärer) Operator erwartet.
wget: option requires an argument -- O
wget: URL fehlt
Aufruf: wget [OPTION]... [URL] …

»wget --help« gibt weitere Informationen.
tar: freetype-2.5.5.tar.bz2: Funktion open fehlgeschlagen: No such file or directory
tar: Error is not recoverable: exiting now
rm: das Entfernen von „freetype-2.5.5.tar.bz2“ ist nicht möglich: No such file or directory
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 213: cd: freetype-2.5.5: No such file or directory
E:\Niels\Desktop\media-autobuild_suite-master\media-suite_compile.sh: Zeile 214: ./configure: No such file or directory
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
make: *** Keine Regel, um „install“ zu erstellen.  Schluss.
-------------------------------------------------
build freetype-2.5.5 failed...
delete the source folder under '/build64' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window

The /build64 folder is empty.

**Comment by jb-alvarado** [comment]
You can try it again, with the fix. But I think at the moment ffmpeg an mktoolnix doesn't work.

**Comment by nille02** [comment]
now it works like you sayd that it fails not at ffmpeg 

common.mak:57: die Regel für Ziel „libavformat/avisynth.o“ scheiterte
make: *** [libavformat/avisynth.o] Fehler 1
sed: kann /local64/lib/pkgconfig/libavcodec.pc nicht lesen: No such file or directory
sed: kann /local64/lib/pkgconfig/libavdevice.pc nicht lesen: No such file or directory
sed: kann /local64/lib/pkgconfig/libavfilter.pc nicht lesen: No such file or directory
sed: kann /local64/lib/pkgconfig/libavformat.pc nicht lesen: No such file or directory
sed: kann /local64/lib/pkgconfig/libswresample.pc nicht lesen: No such file or directory

**Comment by jb-alvarado** [comment]
Maybe we need to make a bug report by the ffmpeg dev team.

**Comment by nille02** [comment]
The .pc files are not in /local64/lib/pkgconfig/. i guess there is somewhere the fault in the script

**Comment by nille02** [comment]
with an older version from the buildscript it compiles without a problem

**Comment by jb-alvarado** [comment]
also with the the newest ffmpeg version?

**Comment by nille02** [comment]
no oO but the change that breaks it must be new

**Comment by jb-alvarado** [comment]
Ok, yes but now we need to now it comes from our script, or from ffmpeg source. I think it comes from the source because they have this change:
https://github.com/FFmpeg/FFmpeg/commit/153073201cdcfd641042114b2bd39b00a532cbb9?diff=unified

**Comment by nille02** [comment]
it is in the source because the older script fails now too :/

**Comment by jb-alvarado** [comment]
Ok :). I wrote a bug ticket.
https://trac.ffmpeg.org/ticket/4391#comment:1

**Comment by nille02** [comment]
everything compile fine again. i think this ticket can be closed
