### ISSUE TITLE
How to target CPU instruction sets more precisely

### ISSUE THREAD

**Issue by mkver** [jb-alvarado/media-autobuild_suite#642]
Hello,

several tools have specially optimized codepaths that make use of modern CPU instruction sets. Suppose I want to target only CPUs that support several instruction sets and don't care about the rest. What would I need to change in the script so that the code for CPUs that don't support these instruction sets isn't compiled in the produced binary?

Greetings and thanks
mkver

**Comment by wiiaboo** [comment]
See https://github.com/jb-alvarado/media-autobuild_suite/issues/358
