### ISSUE TITLE
Compile Specific Version of FFmpeg (3.4)

### ISSUE THREAD

**Issue by tadmn** [jb-alvarado/media-autobuild_suite#644]
Hello, I've been trying to compile FFmpeg n3.4 shared libs (DLLs) with LGPL enabled. This script has gotten me the closest (and is one of the faster options), so thanks for all the hard work!

My question is what is the canonical way to select a particular FFmpeg version? Right now I've swapped out all the original FFmpeg git repo URLs with a custom URL that points to my own fork. This fork's master branch points to n3.4.

This ends up compiling the correct version but the make command fails when compiling. I'm wondering if I'm approaching this in the wrong way (perhaps I also have to change media_autobuild_suite to a specific version?). I've tested other FFmpeg previous builds as well & each time the make command fails with different errors.

Many thanks and kind regards!

Tad

**Comment by tadmn** [comment]
Here are the logs [logs.zip](https://0x0.st/soJb.zip)

**Comment by tadmn** [comment]
I should also note that I'm using the release branch for 3.4, not the tag. I've tried both though (the logs above are from the release branch)

**Comment by wiiaboo** [comment]
Non-master branches might be missing some newer external libs or changes in how the config works.

In your case, I think some external lib is overriding libav* symbols with their own. Check other issues like this to check for solutions.

**Comment by wiiaboo** [comment]
Like this https://github.com/jb-alvarado/media-autobuild_suite/issues/599
