### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by carlhen** [jb-alvarado/media-autobuild_suite#645]
make[3]: *** [Makefile:636: fccfg.lo] Error 1
make[3]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make[2]: *** [Makefile:501: all] Error 2
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make[1]: *** [Makefile:575: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-64bit'
make: *** [Makefile:459: all] Error 2
make failed. Check C:/media-autobuild_suite-master/build/fontconfig-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

[logs.zip](https://0x0.st/soES.zip)

I've tried 3 times now

**Comment by carlhen** [comment]
From compile.stripped.log:
`media-autobuild_suite (64bit)
	[311mStarting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat
media-autobuild_suite (64bit): compiling global tools
	[311mStarting 64bit compilation of global tools
freetype2 2.8.1 ........................................ [Not installed]
 ┌ freetype-2.8.1 .......................................... [[311mDownloaded]
├ Running extract...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ freetype-2.8.1 ............................................. [[312mUpdated]
  Running git clone for fontconfig...
┌ fontconfig git .................................... [[311mRecently updated]
Installing python2-lxml... done
Installing python2-six... done
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
 #include "../fc-blanks/fcblanks.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:636: fccfg.lo] Error 1
make[3]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make[2]: *** [Makefile:501: all] Error 2
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make[1]: *** [Makefile:575: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-64bit'
make: *** [Makefile:459: all] Error 2
make failed. Check C:/media-autobuild_suite-master/build/fontconfig-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
`

**Comment by pcspeak** [comment]
The same problen for me; been trying daily for 10 days.
Followed troubleshooting guide steps 1 and 3.
This is step 3 - and here are my logs.
Thanks & cheers.

[logs.zip](https://0x0.st/sHPN.zip)

**Comment by charlie460** [comment]
Same issue here,  failing on fontconfig.

**Comment by carlhen** [comment]
Make passed now 😄
