### ISSUE TITLE
How to recompile ffmpeg now?

### ISSUE THREAD

**Issue by pluto439** [jb-alvarado/media-autobuild_suite#648]
I have set media-autobuild_suite to not delete source codes and object files. Commented out a few lines of code in `ffmpeg-git`. How to compile it again now?

Tried running `media-suite_compile.sh` , didn't work.

Tried running `make` inside `build/ffmpeg-git`, nothing.

**Comment by wiiaboo** [comment]
You run make inside the respective `build-*` directory which you want to recompile, not in the root of ffmpeg-git.
