### ISSUE TITLE
libsndfile fails to build

### ISSUE THREAD

**Issue by kode54** [jb-alvarado/media-autobuild_suite#650]
It claims to need GNU autogen.

[logs.zip](https://0x0.st/sH8p.zip)

Attempting to run the command it runs to check for autogen:

```
$ (autogen --version)
C:/Users/kode5/Documents/Source/Repos/media-autobuild_suite/msys64/usr/bin/autogen.exe: error while loading shared libraries: msys-guile-2.0-22.dll: cannot open shared object file: No such file or directory
```

Crud, I see this is already posted in a closed issue.

**Comment by wiiaboo** [comment]
Yeah, wait for a new version of MSYS2 autogen before this or anything requiring autogen to work again.

**Comment by schmidthubert** [comment]
autogen-5.18.12-2 is out now, https://github.com/Alexpux/MSYS2-packages/pull/1075 :+1:
