### ISSUE TITLE
ffmpeg / hwcontext_opencl.c: undefined reference to several OpenCL functions

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#652]
Probably an ffmpeg issue ([#6893](http://trac.ffmpeg.org/ticket/6893)).

**Comment by LigH-de** [comment]
Not sure if this depends on the available GPU and related OpenCL support. The mentioned issue was reported on a PC with GeForce 9600. On this other PC with GT 450, I do not have this issue. Or it was fixed in the meantime ... but the ffmpeg issue was not yet read.

**Comment by GyanD** [comment]
Resolved this by deleting libOpenCL.a in local64/lib. This gets the script to generate a new static lib.

**Comment by LigH-de** [comment]
Testing, will report...

**Comment by GyanD** [comment]
File content won't "depend" on GPU - but different library versions may be bundled with different drivers, so it's possible that you can't enable OpenCL in ffmpeg for this card.

**Comment by LigH-de** [comment]
So I wonder if it would be easy to check the availability of a compatible library and disable OpenCL linking on-the-fly if not (while I am not sure how, which criterion to decide on...); or what did the ffmpeg developers mean to link to a generic ICD loader?

**Comment by hydra3333** [comment]
Not intended as a useful script (it is used as a learning exercise) - this linux script 
https://github.com/hydra3333/ffmpeg-windows-build-helpers-withOpenCL/blob/master/cross_compile_ffmpeg.rdp-mod009.sh
does a cross-compile of ffmpeg with Windows as the target, using a generic OpenCL loader and thus is not dependent on any specific driver.
It is mentioned only as a working example of it being done.

**Comment by LigH-de** [comment]
MABS also uses the OpenCL.dll from the system directory of the matching bitness, and uses **gendef** to extract its export symbols into libOpenCL.def to build libOpenCL.a; if I have only an OpenCL.dll compatible to OpenCL 1.1, then some OpenCL 1.2 specific exports are not available, thus missing in the libOpenCL.def, thus missing in libOpenCL.a, thus failing to link into avutil-56.dll.

I wonder if ffmpeg just recently implemented some new features which require now OpenCL 1.2, because about a month ago, ffmpeg still built fine. So I have to assume that ffmpeg only required OpenCL 1.1 during this era.

**Comment by schmidthubert** [comment]
You forgot to mention which ffmpeg functionality doesn't work for you (anymore)? Yes, there [have been many opencl changes in ffmpeg](https://git.ffmpeg.org/gitweb/ffmpeg.git?a=search&h=HEAD&st=commit&s=opencl), but ffmpegs min/max API opencl version was/is 1.2 [for over a year](https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/801eca1372dd7e4bdc25271877cda06c0674f76e) now if I read that correctly. So yes, recent opencl changes in ffmpeg. But how does it concern you anyway [if your card only supports opencl 1.1](https://en.wikipedia.org/wiki/GeForce_9_series)? You didn't say. Just leave --enable-opencl off and be done with it for now or get a(n even) cheap(er) Pascal series card next spring when [Volta](https://en.wikipedia.org/wiki/Nvidia_Tesla#GV100) is out for everyones pocket if you for whatever reason don't want to bin your old card right now .. :+1:

**Comment by LigH-de** [comment]
Functionality? I want to **build** ffmpeg. I want to build it with most available options. I may not even want to execute ffmpeg on the PC I built it on. But if the linking already fails, I cannot build it with the desired options.

**Linking avutil-56.dll** fails on a PC which has no OpenCL 1.2 compatible driver, if I use `--enable-opencl` – so I can only **build ffmpeg without OpenCL support** on a PC which has no OpenCL 1.2 compatible driver. Means: Enabling OpenCL support makes the created ffmpeg.exe depend on this PC it was built on, to some degree.

If I want an ffmpeg.exe which supports OpenCL, I need to **build** it on a PC which has OpenCL 1.2 compatible hardware installed.

**Comment by schmidthubert** [comment]
>I want to build it with most available options.
So you want to have the longest, even if you don't use it. That's not possible (anymore) on a non-opencl-12 system, apparently. You should get over it ...

**Comment by LigH-de** [comment]
I will accept that it is not possible anymore (yet, for curiosity, I wonder why it was possible until about 1-2 months ago...).

But in this case, it may be recommendable for MABS to at least document this constraint. Possibly even to check for it and warn specifically. I guess an easy method might be testing for the existence of 

- "clCreateImage@28" in build/opencl/build-32bit/OpenCL.def if building for Win32 is selected
- "clCreateImage" alone (not clCreateImage2D or clCreateImage3D) in build/opencl/build-64bit/OpenCL.def if building for Win64 is selected

But it might not be sufficient, I am not sure.

**Comment by schmidthubert** [comment]
If you have followed MABS then you should've noticed CUDA 8 was replaced with CUDA 9 recently and while the compilation went fine the functionality was zilch because NVidias driver wasn't even supporting v9 while the SDK already was. I think it can be EXPECTED here that beeps check FIRST what capability the HW + driver has before starting to complain here so things can be kept more ore less simple ...

**Comment by LigH-de** [comment]
Sorry, I am not so deep into these details, I am only a half-wit. I report issues when they happen and try my best to help detecting the reasons, but most of the times I do not even understand them. Not to mention their optimal solutions.

From here on, I will leave it to the MABS developers.

**Comment by schmidthubert** [comment]
[n3.4.1](https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/refs/tags/n3.4.1) maybe still works for you and so maybe some more stable releases to come ... :+1:

**Comment by LigH-de** [comment]
I still have a PC with GTS 450, here ffmpeg builds with OpenCL 1.2 support.

And then there is also a PC with 32-bit Win7. Building 64-bit tools with cross-compilation would be a whole different challenge. Of course, building ffmpeg with OpenCL would not work there because there is no 64-bit OpenCL.dll available. But there I already have an issue with a completely fresh MSYS2 installation (autogen vs. guile, again, different version). Groundhog days ... or, at least, weeks.

**Comment by LigH-de** [comment]
Conclusion: To build ffmpeg with OpenCL support, it must be built on a PC where an OpenCL v1.2 compatible Khronos loader is available, because it is used to generate the definition file.

**Comment by schmidthubert** [comment]
OpenCL is on github as well for just building if it's not installed, check out some bash code I posted a while back:
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/183#issuecomment-324818289

But you'll have to change jb's script by yourself then, good luck :+1:

**Comment by wiiaboo** [comment]
Now you just need to find some pre-built 1.2+ ICD loader or build it yourself with MSVC and cmake and put it in the respective bin-video before running the suite.
No idea if it works, but the ICD loader can't be built for Windows without MSVC.

**Comment by hydra3333** [comment]
"No idea if it works, but the ICD loader can't be built for Windows without MSVC." 
... if it's the the khronos ICD loader you are mentioning (I am unsure) then it is cross-compilable from a slightly older commit. refer https://github.com/jb-alvarado/media-autobuild_suite/issues/652#issuecomment-351088477
