### ISSUE TITLE
fontconfig make failed

### ISSUE THREAD

**Issue by pcspeak** [jb-alvarado/media-autobuild_suite#655]
Problem still exists for me as per #645
New logs. 

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1537210/logs.zip)

**Comment by BlohoJo** [comment]
Mine's failing as well at fontconfig. Tried deleting the fontconfig-git directory and re-running; same crash.

`make failed. Check C:/WIP/BuildFFMPEG/build/fontconfig-git/build-32bit/ab-suite.make.log`

From that log:

```
41  In file included from ../../fc-lang/fc-lang.c:26:0:
42  ../../src/fcstr.c:61:10: fatal error: ../fc-case/fccase.h: No such file or directory
43   #include "../fc-case/fccase.h"
```

Checked fc-case folder; fccase.h isn't there.

```
90  ../../src/fccfg.c:30:10: fatal error: ../fc-blanks/fcblanks.h: No such file or directory
91   #include "../fc-blanks/fcblanks.h"
```

Again fc-blanks folder exists, fcblanks.h does not.

[logs.zip](https://0x0.st/sXMb.zip)

**Comment by BlohoJo** [comment]
Well, I just deleted the whole directory, redownloaded, and ran it again, giving the directory a 4 character name. I also selected the options to build all the individual standalone .exe's. Not sure why but now the fontconfig-git error doesn't happen and it works.

But, now it stops and fails due to issue #646. :( Anyone know of a workaround?

**Comment by pcspeak** [comment]
I followed the method Blohojo outlined above. make worked and everything is good.
Cannot explain. Closing this issue.

**Comment by pcspeak** [comment]
Really have no answer. I'd done a full install, twice, from the mabs batch file. x32 & x64
fontconfig make failed.
Did it a third time allowing the build of all .exes and it worked.
Thanks & cheers.
