### ISSUE TITLE
xvidcore

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#662]
Just updated to the latest version of MABS and this happend......

┌ xvidcore ................................................ [Downloaded]
┌ xvidcore ................................................ [Downloaded]
┌ xvidcore ................................................ [Downloaded]
├ Running extract...
/build/media-suite_helper.sh: line 53: cd: xvidcore: No such file or directory
  Creating diagnostics file...

ERROR:
Duplicate filename on disk:
ab-suite.autogen.log
ab-suite.autogen.log

Failed changing to directory xvidcore.

**Comment by schmidthubert** [comment]
> /build/media-suite_helper.sh: line 53: cd: xvidcore: No such file or directory
The sha256sum of xvidcore-1.3.5.tar.gz is incorrect, change it on line 1248 of media-suite_compile.sh to 165ba6a2a447a8375f7b06db5a3c91810181f2898166e7c8137401d7fc894cf0

**Comment by Barough** [comment]
Thnx schmidthubert :)

I've changed sha265sum but now this happens

├ xvidcore ........................................... [File up-to-date]
├ Running extract...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running make...
├ /local32/lib/libxvidcore.a ............................... [Not found]
└ xvidcore .................................................... [Failed]

Try deleting '/build/xvidcore' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

I've deleted the '/build/xvidcore' folder but it doesn't help

**Comment by schmidthubert** [comment]
Seems this step doesn't succeed:
`    do_install \=build/xvidcore.a lib/libxvidcore.a`

For now simply copy it manually (and rename it in the target dir) from `(yourdir)\build\xvidcore\build\generic\=build\xvidcore.a`
to
`(yourdir)\local(32|64)\lib\libxvidcore.a`. 
You'll have to do that twice if you build for 32bit and 64bit, simply do it one time after each error. It should continue build then for now ...

**Comment by Barough** [comment]
I can wait. Just wanted to pint out this issue in question.

**Comment by Barough** [comment]
Thanks :)
