### ISSUE TITLE
ffmpeg git build fail - tls_openssl / BIO_meth_set_create

### ISSUE THREAD

**Issue by BlohoJo** [jb-alvarado/media-autobuild_suite#664]
Looks like you're currently trying to nail down all open issues. Sorry to be reporting this! :\

```
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error:
C:/mingw/build/ffmpeg-git/libavformat/tls_openssl.c:285:5: error: implicit declaration of function 'BIO_meth_set_create'; did you mean 'BIO_gethostbyname'? [-Werror=implicit-function-declaration]
     BIO_meth_set_create(p->url_bio_method, url_bio_create);
     ^~~~~~~~~~~~~~~~~~~
     BIO_gethostbyname
C:/mingw/build/ffmpeg-git/libavformat/tls_openssl.c:286:5: error: implicit declaration of function 'BIO_meth_set_destroy'; did you mean 'ff_mutex_destroy'? [-Werror=implicit-function-declaration]
     BIO_meth_set_destroy(p->url_bio_method, url_bio_destroy);
     ^~~~~~~~~~~~~~~~~~~~
     ff_mutex_destroy
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavformat/tls_openssl.o] Error 1
make failed. Check C:/mingw/build/ffmpeg-git/build-shared-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```

As before... 100% fresh using latest master (12/20/2017 5:08 PM) - completely deleted previous C:\mingw folder and started from scratch.

Tried twice, same error.

[ab-suite.configure.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1578223/ab-suite.configure.log)
[ab-suite.make.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1578224/ab-suite.make.log)

[logs.zip](https://0x0.st/s8sm.zip)

**Comment by wiiaboo** [comment]
That seems weird. Why would it want to use 1.1 functions when there's only 1.0.2 available?

**Comment by BlohoJo** [comment]
In light of issue #665, I tried installing the latest release (16.1.2) of Intel's [OpenCL Runtime for Intel Core and Intel Xeon Processors](https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime). (I'm running media-autobuild on a Win 2008 R2 VPS with a 6 core Xeon processor and no GPU).

I again started completely from scratch with the latest media-autobuild updated 12/21/2017 8:04 AM.

It still fails with the same error:

```
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error:
C:/mingw/build/ffmpeg-git/libavformat/tls_openssl.c:285:5: error: implicit declaration of function 'BIO_meth_set_create'; did you mean 'BIO_gethostbyname'? [-Werror=implicit-function-declaration]
     BIO_meth_set_create(p->url_bio_method, url_bio_create);
     ^~~~~~~~~~~~~~~~~~~
     BIO_gethostbyname
C:/mingw/build/ffmpeg-git/libavformat/tls_openssl.c:286:5: error: implicit declaration of function 'BIO_meth_set_destroy'; did you mean 'ff_mutex_destroy'? [-Werror=implicit-function-declaration]
     BIO_meth_set_destroy(p->url_bio_method, url_bio_destroy);
     ^~~~~~~~~~~~~~~~~~~~
     ff_mutex_destroy
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavformat/tls_openssl.o] Error 1
make failed. Check C:/mingw/build/ffmpeg-git/build-shared-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```

[ab-suite.configure.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1579588/ab-suite.configure.log)
[ab-suite.make.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1579589/ab-suite.make.log)

[logs.zip](https://0x0.st/s8iP.zip)

**Comment by BlohoJo** [comment]
> [LigH-de commented](https://github.com/jb-alvarado/media-autobuild_suite/issues/665)
> Check if you have libressl or openssl enabled in your ffmpeg-options.txt if you are using that. You should try having only gnutls enabled instead. Or which ffmpeg choice (1..4) did you use?
>
>Or maybe I miss the point.

I am running the batch file straight out of the media-autobuild download.

Used ffmpeg choice 4.

[media-autobuild_suite.ini.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1579636/media-autobuild_suite.ini.txt)

**Comment by BlohoJo** [comment]
> _wiiaboo commented:_
> That seems weird. Why would it want to use 1.1 functions when there's only 1.0.2 available?

Is this not reproducible?

Could any installed software or environment variables be playing a role in this?

Just in case, here's my Path and PATHEXT (replaced semicolons with new line):

Path:
C:\Program Files\Python 3.6.3\Scripts\
C:\Program Files\Python 3.6.3\
C:\ProgramData\Oracle\Java\javapath
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
%SystemRoot%\System32\Windows System Resource Manager\bin
%systemroot%\idmu\common
C:\Program Files\Prio 2.1.0.4391
C:\Program Files\UltraEdit 24.00.0.76
C:\Program Files\FFmpeg 3.4\static
C:\Program Files (x86)\Sox 14.4.2

PATHEXT:
.COM
.EXE
.BAT
.CMD
.VBS
.VBE
.JS
.JSE
.WSF
.WSH
.MSC
.PY
.PYW
