### ISSUE TITLE
build/ffmpeg-git/opencl first not created, then complained missing

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#665]
Completely new installation of MABS on a Win64 PC, building ffmpeg with OpenCL support enabled (and GPU is v1.2 capable). C:\Windows\System32\OpenCL.dll (Khronos loader v2.0.4.0) does exist.

[logs.zip](https://0x0.st/s8sP.zip)

**Comment by BlohoJo** [comment]
I am running media-autobuild on a VPS running Win 2008 R2 with an Intel Xeon processor and no video card. After reading your issue, I installed the latest release (16.1.2) of [Intel's OpenCL Runtime for Intel Core and Intel Xeon Processors](https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime). After starting Media Autobuild from scratch, I get your error. OpenCL.dll is present is both C:\Windows\System32 and C:\Windows\SysWOW64.

Without OpenCL, it failed at the ffmpeg git shared compile with Issue #664.

**Comment by BlohoJo** [comment]
You posted your reply at about the exact same time as I posted mine. I just updated and tried again and indeed this issue is fixed, but Issue #664 remains. :\

**Comment by LigH-de** [comment]
Check if you have libressl or openssl enabled in your ffmpeg-options.txt if you are using that. You should try having only gnutls enabled instead. Or which ffmpeg choice (1..4) did you use?

**Comment by BlohoJo** [comment]
I am running the batch file straight out of the media-autobuild download.

Used ffmpeg choice 4.

[media-autobuild_suite.ini.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1579636/media-autobuild_suite.ini.txt)
