### ISSUE TITLE
ffmpeg compile error

### ISSUE THREAD

**Issue by atomsfear** [jb-alvarado/media-autobuild_suite#668]
Running git update for ffmpeg...
┌ ffmpeg git ........................................... [Updates found]
├ Changing options to comply to nonfree...
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error:
                 from D:/media/msys64/mingw64/x86_64-w64-mingw32/include/winscard.h:10,
                 from D:/media/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:97,
                 from D:/media/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from D:/media/build/ffmpeg-git/libavformat/os_support.h:112,
                 from D:/media/build/ffmpeg-git/libavformat/internal.h:28,
                 from D:/media/build/ffmpeg-git/libavdevice/decklink_common.cpp:25:
D:/media/msys64/mingw64/x86_64-w64-mingw32/include/propidl.h:1290:28: note: previous declaration of 'void BSTR_UserFree(ULONG*, OLECHAR**)'
 void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
                            ^~~~~~~~~~~~~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:63: libavdevice/decklink_common.o] Error 1
make failed. Check D:/media/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

[ab-suite.configure.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1584105/ab-suite.configure.log)
[ab-suite.make.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1584106/ab-suite.make.log)
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1584107/logs.zip)

**Comment by wiiaboo** [comment]
That's a FFmpeg issue, open a trac issue there. I've mentioned it to the one who made the breaking commit, but a trac issue might solve it faster.

**Comment by BlohoJo** [comment]
Yep I have the same error. Beginning to wonder if I'll ever get a binary at this point. :\

But of course I appreciate all the work you've been doing.

**Comment by wiiaboo** [comment]
If you're in a hurry, just disable decklink temporarily. It's the only C++ source code in FFmpeg, so it's the only one affected by this.

**Comment by BlohoJo** [comment]
No hurry. I [created the trac issue](https://trac.ffmpeg.org/ticket/6926).

**Comment by wiiaboo** [comment]
Fixed upstream.
