### ISSUE TITLE
mpv compile error --lua^

### ISSUE THREAD

**Issue by atomsfear** [jb-alvarado/media-autobuild_suite#671]
Thank you for solve the problem yesterday.

┌ mpv git ........................................... [Recently updated]
Installing python3-docutils... done
Installing python2-rst2pdf... done
├ Running configure...
Likely error:
    --disable-audio-input
                        disable audio input support [autodetect]
    --enable-dvbin      enable DVB input module [disable]

  standalone app:
    --disable-apple-remote
                        disable Apple Remote support [autodetect]
    --disable-macos-touchbar
                        disable macOS Touch Bar support [autodetect]
waf: error: no such option: --lua^
configure failed. Check D:/media/build/mpv-git/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/s8Q9.zip
Copy and paste [logs.zip](https://0x0.st/s8Q9.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

[ab-suite.configure.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1584591/ab-suite.configure.log)
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1584592/logs.zip)

**Comment by BlohoJo** [comment]
Same exact error for me.
