### ISSUE TITLE
question x265&x264&cuda

### ISSUE THREAD

**Issue by atomsfear** [jb-alvarado/media-autobuild_suite#672]
I have the problem with mpv,to ensure that is no my problem,I switch to another drive to use suite from beginning with same setting(media-autobuild_suite.ini).
And it stop at mpv too,and I found the x265.exe was not in local64\bin-video\,but there was a x265.exe in build\x265-hg\build-64bit\8bit\,compare to the file I compile in original drive,about 4.5MB bigger,same version(2.6.0.22) and same 8bit+10bit+12bit,the strip ver seems not copy to the local64\bin-video\.

And I want to ask,is there any way to recompile x264.exe while libavformat and ffms2 been update?
Last thing is how can I do with not delete my system cuda path to use the suite's cuda instead.

Sorry about the bad grammar,I am not good at it.

**Comment by wiiaboo** [comment]
> And it stop at mpv too,and I found the x265.exe was not in local64\bin-video,but there was a x265.exe in build\x265-hg\build-64bit\8bit,compare to the file I compile in original drive,about 4.5MB bigger,same version(2.6.0.22) and same 8bit+10bit+12bit,the strip ver seems not copy to the local64\bin-video.

Sorry, can you split the questions or rephrase a bit? I can't understand the problem.

> And I want to ask,is there any way to recompile x264.exe while libavformat and ffms2 been update?

Delete x264.exe to force a recompilation. It'd be too bothersome to recompile all versions of FFmpeg in the suite every time there's an update to it.

> Last thing is how can I do with not delete my system cuda path to use the suite's cuda instead.

There's no suite cuda, so I don't know what you're talking about. Either that or I don't understand the question.

**Comment by atomsfear** [comment]
The x265.exe not in local64\bin-video,but it have a bigger size one in build\x265-hg\build-64bit\8bit.

I don't want let it use my cuda,because I don't have vs2015 installed.
I delete the path about the cuda,so the suite while compile won't say [FFmpeg and related apps will depend on CUDA SDK!][FFmpeg and related apps will depend on Nvidia drivers!].
How can I do that without delete my path?

Thanks for your answer.

**Comment by wiiaboo** [comment]
I need your media-autobuild_suite.ini and ffmpeg_options.txt.

**Comment by atomsfear** [comment]
[compiler list]
msys2Arch=2
arch=3
license2=1
xpcomp=2
standalone=1
vpx2=1
aom=1
daala=1
x2642=4
x2652=1
other265=1
flac=1
fdkaac=1
faac=1
mediainfo=1
soxB=1
ffmpegB2=4
ffmpegUpdate=1
ffmpegChoice=4
mp4box=1
rtmpdump=1
mplayer2=1
mpv=1
bmx=1
curl=1
ffmbc=1
cyanrip=1
cores=4
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=2

I chose 4,and there is no ffmpeg_options.txt

**Comment by wiiaboo** [comment]
Then that's why cuda's enabled. Choose ffmpegChoice=1 and remove or comment `--enable-cuda-sdk`.

**Comment by wiiaboo** [comment]
Also, I can't reproduce the x265 issue. It shouldn't even finish the suite if it didn't install x265.exe properly.

**Comment by atomsfear** [comment]
I solved the cuda's problem.

X265's problem was happen when I delete entire folder and start from beginning,I cannot reproduce it again,too bother.

Thank you for helping me.
