### ISSUE TITLE
mpv compile error

### ISSUE THREAD

**Issue by atomsfear** [jb-alvarado/media-autobuild_suite#674]
┌ mpv git ........................................... [Recently updated]
├ Running configure...
├ Running build...
Likely error:
<line>Displays current media-title, filename, or custom title</line> line
<line>Shows current cache fill status</line> line
<line>Shows current playback position timestamp</line> line
<line>Indicates current playback position and position of chapters</line> line
<line>Shows remaining playback time timestamp</line> line
<line>Displays selected track and amount of available tracks</line> line

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
build failed. Check D:/media/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach D:\media\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by wiiaboo** [comment]
> Attach D:\media\build\logs.zip to the GitHub issue.

**Comment by BlohoJo** [comment]
Ho ho ho it's still a no go. :p 

Same error. Latest media-autobuild_suite (timestamp 12/24/17 8:17AM). Clean / from scratch run.

```
  Running git clone for mpv...
┌ mpv git ........................................... [Recently updated]
Installing python3-docutils... done
Installing python2-rst2pdf... done
├ Running configure...
├ Running build...
Likely error:
<line>Displays current media-title, filename, or custom title</line> line
<line>Shows current cache fill status</line> line
<line>Shows current playback position timestamp</line> line
<line>Indicates current playback position and position of chapters</line> line
<line>Shows remaining playback time timestamp</line> line
<line>Displays selected track and amount of available tracks</line> line

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/mingw/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/s8e7.zip
Copy and paste [logs.zip](https://0x0.st/s8e7.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```
[\build\mpv-git\ab-suite.build.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1584977/ab-suite.build.log)
[\build\mpv-git\ab-suite.configure.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1584978/ab-suite.configure.log)
[\build\mpv-git\ab-suite.git.reset.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1584979/ab-suite.git.reset.log)


[\build\media-autobuild_suite.ini](https://github.com/jb-alvarado/media-autobuild_suite/files/1584980/media-autobuild_suite.ini.txt)

[logs.zip](https://0x0.st/s8e7.zip)

**Comment by BlohoJo** [comment]
Hey wiiaboo, now guess what happened.

It finally compiled with no errors.

Thank you so much for all of your work over the past several days.

Merry Christmas! :)

**Comment by wiiaboo** [comment]
If only you didn't select the option with all the possible external libs, you might've finished compiling weeks ago.

**Comment by BlohoJo** [comment]
Sorry!

But, you _did_ get it working so that it compiles now for all libraries. :)

Believe it or not, I _may_ actually be using some of those old shitty codecs as I'm currently going through a bunch of old video archives from the late 1990's... I just opened a random one for example and it uses RealNetworks G2 codecs (remember that thing?), with the Cook audio codec and the RV20 video codec. I'm not sure if libavcodec supports Cook audio decoding without all external libraries... I know for example that YouTube doesn't even support Cook audio.
