### ISSUE TITLE
Cross-compile fails in "libavcodec/libx264.c: In function ‘X264_frame’"

### ISSUE THREAD

**Issue by hydra3333** [jb-alvarado/media-autobuild_suite#676]
more info rather than bug
depending on how you clone ffmpeg and x264 an rdp based cross-compile can fail with
"libavcodec/libx264.c: In function ‘X264_frame’" 
which suggests it may temporarily fail here too.

For the time being, the latest ffmpeg from git won't cross-compile with the latest x264 from git
https://trac.ffmpeg.org/ticket/6932

If you use x264 commit e9a5903edf8ca59ef20e6f4894c196f135af735e then it works (until ffmpeg is changed in the near future to use the new api, then you'll have to look at using a newer x264 commit).

**Comment by BlohoJo** [comment]
It does indeed fail here... issue #675 was caused by this, NOT by what I originally thought (building with xpcomp=1). I had just gotten a fully successful run of media-autobuild yesterday so I didn't think anything else changed since then that would break it.

**Comment by wiiaboo** [comment]
#675 duplicate.
