### ISSUE TITLE
Suite build fails at opus-tools

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#680]
Tried a few times, deleting the dir in the build dir - but no success. Any ideas?
[logs.zip] (https://0x0.st/s8wh.zip)

**Comment by Barough** [comment]
delete all opus related build folders. i had to do it 4 times or so b4 i got the building to work

**Comment by wiiaboo** [comment]
Run
```bash
source /build/media-suite_helper.sh
do_uninstall tls.h lib{crypto,ssl,tls}.{pc,{,l}a} openssl.pc etc/ssl include/openssl bin-global/openssl.exe
```
and try to run the suite again. opusfile doesn't work with libressl.

**Comment by BlackScreen** [comment]
And now it fails at ffms2... :(
[logs.zip] (https://0x0.st/s8x1.zip)

**Comment by wiiaboo** [comment]
No idea. Delete /local64/opt/lightffmpeg.

**Comment by BlackScreen** [comment]
Thanks. The whole suite is working again now!
