### ISSUE TITLE
Lame 3.100 missing some command line options

### ISSUE THREAD

**Issue by BlohoJo** [jb-alvarado/media-autobuild_suite#681]
Do a lame --longhelp with the media-autobuild_suite binary and compare it to the --longhelp from the [Rarewares](http://www.rarewares.org/mp3-lame-bundle.php) binary.

It's missing the following command line options:

```
    --mp1input      input file is a MPEG Layer I   file
    --mp2input      input file is a MPEG Layer II  file
    --mp3input      input file is a MPEG Layer III file
    --replaygain-accurate   compute RG more accurately and find the peak sample
    --clipdetect    enable --replaygain-accurate and print a message whether
                    clipping occurs and how far the waveform is from full scale
```

The media-autobuild_suite binary does have this option that the rarewares one doesn't:

```
  Platform specific:
    --noasm <instructions> disable assembly optimizations for mmx/3dnow/sse
```

I did check and the media-autobuild_suite binary does return an unrecognized option error if you try to use for example --replaygain-accurate.

Any way to add those missing command line options in?

**Comment by schmidthubert** [comment]
By looking at lames configure file it looks as if the "--disable-decoder" part is causing the missing options, all of them. So remove that parameter from media-suite_compile.sh line 631 and check again what you get ...

**Comment by schmidthubert** [comment]
Removing that option works just fine and the missing options are there now ... :+1:
