### ISSUE TITLE
git clone for AMF halts

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#684]
```
  Running git clone for AMF...
```

How long does it take normally? After 10 minutes I stopped.

**Comment by wiiaboo** [comment]
It's a regular github repo.

**Comment by LigH-de** [comment]
I let it run for about half an hour, suddenly it worked... Strange delay.

**Comment by wiiaboo** [comment]
Shitty net, or shitty github, can't help there.
