### ISSUE TITLE
Freeytpe-2.8.1 compilation fails

### ISSUE THREAD

**Issue by Taris9047** [jb-alvarado/media-autobuild_suite#686]
Windows 10, updated to newest version.

Freshly cloned from git.

Error message:
freetype2 2.8.1 ........................................ [Not installed]
├ freetype-2.8.1 ..................................... [File up-to-date]
rm: cannot remove 'freetype-2.8.1': Device or resource busy
├ Running extract...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
../configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/local64 --disable-shared --enable-static --bindir=/local64/bin-global --with-harfbuzz=no --with-png=no --with-bzip2=no
../configure: line 96: test: 13086892883114646894: integer expression expected
make: *** No rule to make target 'setup'.  Stop.
configure failed. Check E:/media-autobuild_suite/build/freetype-2.8.1/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
/build/media-suite_helper.sh: line 1412: git: command not found

All relevant logs have been anonymously uploaded to https://0x0.st/sKbK.zip
Copy and paste [logs.zip](https://0x0.st/sKbK.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1594882/logs.zip)

**Comment by wiiaboo** [comment]
Can't reproduce. Try deleting freetype build directory manually.
