### ISSUE TITLE
Using Cisco openh264 dll?

### ISSUE THREAD

**Issue by ed0llo** [jb-alvarado/media-autobuild_suite#688]
Hey, is it possible to compile ffmpeg with this script using the openh264 binaries provided by cisco? I've managed to get it running fine with a static build but I'd like to use the royalty free h264 encoding and need to download the cisco dlls separately. Thanks

**Comment by wiiaboo** [comment]
Check if it works with a1928e3.

**Comment by ed0llo** [comment]
Seems to have worked perfectly. Thanks a lot
