### ISSUE TITLE
FFmpeg build now requires "libopenh264.dll" on the system

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#690]
After building everything today with the suite, I wanted to test the new version of FFmpeg.
After starting I get an error dialog, that "libopenh264.dll" is missing on my system.
FFmpeg does not work like this at moment. What can I do to fix this?

**Comment by wiiaboo** [comment]
There should be that exact file inside bin-video. FFmpeg now requires that if openh264 is enabled. Since there's basically no point in including openh264 if you're not using the official binaries,  this made sense to me.

**Comment by BlackScreen** [comment]
Sorry. I had an automatic script copying the FFmpeg.exe out of the build dir to another dir. I did not look inside "bin-video". If I copy the dll-file, too it works. Thanks and sorry for the silly question.
