### ISSUE TITLE
ffms2: ffindex.exe without ffms2.dll?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#694]
So, okay, you built ffindex.exe ... but where is the ffms2.dll? Is there any other use for ffindex files, except being used in the matching AviSynth/VapourSynth decoder plugin?

But I guess building the DLL is a lot more tricky, from what I read in the doom9 forum.

**Comment by wiiaboo** [comment]
ffms2 is only built for usage with x264. If you want the plugin you need visual studio.
