### ISSUE TITLE
ffmpeg compilation fails

### ISSUE THREAD

**Issue by mkver** [jb-alvarado/media-autobuild_suite#695]
Hello,

I just tried to build ffmpeg (I tried both static and shared in two runs) because somehow "MPV_OPTS" was included in the LDFLAGS for ffmpeg. The logs are [here](https://0x0.st/sZ2P.zip) and [here](https://0x0.st/sZ2A.zip) for shared and static builds.

Thanks in advance
Andi

PS: As you can see, I have already trimmed the amount of stuff to compile down to just basic ffmpeg without any external libs. Yet nevertheless several external libraries are built: freetype, harfbuzz, fribidi, libass, rubberband, sdl2 (I disabled it in the ffmpeg options), libbluray, AMF. Why is that so?

**Comment by wiiaboo** [comment]
> Yet nevertheless several external libraries are built: freetype, harfbuzz, fribidi, libass, rubberband, sdl2 (I disabled it in the ffmpeg options), libbluray, AMF.

Because in FFmpeg and mpv some (or most, for mpv) of those options are by default enabled and you need to explicitely disable them. Commenting them doesn't disable them.

But the fact that you got mpv options inside ffmpeg options is weird, that is definitely a bug.

**Comment by mkver** [comment]
I think I found out what triggers this: If I comment everything out in "mpv_options.txt", somehow "MPV_OPTS" is included in ffmpeg's LDFLAGS. If I uncomment anything (or disable some of the libraries there to make it not build something that is not needed at all) it works.

**Comment by mkver** [comment]
I just wanted to add that I still have "MPV_OPTS" in ffmpeg's flags if I comment everything out in mpv_options.txt. See [here](https://0x0.st/sZVj.zip).

**Comment by wiiaboo** [comment]
> And I think that avisynth should only be a common option, not a built-in option. After all, one needs to explicitly enable it.

Yeah, it used to be built-in.

**Comment by wiiaboo** [comment]
The MPV_OPTS in flags issue is probably fixed now(?)
