### ISSUE TITLE
sdl2/ffplay problem

### ISSUE THREAD

**Issue by mkver** [jb-alvarado/media-autobuild_suite#696]
Hello,

sorry to disturb you again, but it seems that [this commit](https://github.com/FFmpeg/FFmpeg/commit/d03c39b46b21c893d6549a532289b7fb9935b3fc) broke sdl2/ffplay. If I build with "--enable-sdl2" commented out, sdl2 is built, but it doesn't end up in ffmpeg. If I build with sdl2 enabled, compilation fails.  [Here](https://0x0.st/sZ4L.zip) are the logs.

Thanks in advance
Andi

**Comment by schmidthubert** [comment]
Just patch it back then for now: Add
`patch -i ../sdl2ffplay.patch` 
at line 1390 of media-suite_compile.sh and put the attachment into your build dir (remove the .txt ext). Done for now! :+1: (until more untested cr*p comes up from the "works for me" devs) :roll_eyes: :hammer: 
[sdl2ffplay.patch.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1610107/sdl2ffplay.patch.txt)

**Comment by wiiaboo** [comment]
It's an issue upstream, yeah. Soon to be fixed.

**Comment by mkver** [comment]
Thanks @schmidthubert for this patch. It works.

**Comment by wiiaboo** [comment]
Use https://patchwork.ffmpeg.org/patch/7186/ instead if you want a patch. That what'll get merged to fix this.

**Comment by wiiaboo** [comment]
Fixed upstream.
