### ISSUE TITLE
support for x264 unified build 

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#698]
starting with https://git.videolan.org/?p=x264.git;a=commit;h=71ed44c7312438fac7c5c5301e45522e57127db4 which is now two weeks old x264 can be build as unified build would be nice if media-autobuild_suite would support building a unified version,...
I'm mainly interested into x264 (8-/10bit + libav + numa) in one build. :)

+ Seems like all the latest updates haven't been noticed by media-autobuild_suite,..

**Comment by wiiaboo** [comment]
It's been done for two weeks now https://github.com/jb-alvarado/media-autobuild_suite/commit/f465cacd3c2aa4d27ebb018d4b4337a76ebddc26?

**Comment by wiiaboo** [comment]
And there's no non-numa build in x264. You're mistaking it with x265.
