### ISSUE TITLE
FFmpeg build error

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#703]
The suite now runs again smoothly - until the building of FFmpeg. It seems to have something to do with the Decklink support or pthread?
[logs.zip] (https://0x0.st/sZFM.zip)

**Comment by wiiaboo** [comment]
That looks like a FFmpeg problem. And it could be anything from your 50 external libraries. I doubt they'll even go near this.

**Comment by wiiaboo** [comment]
Nevermind, it's my bug. pthreads should be enabled if zvbi and decklink are enabled together.

**Comment by BlackScreen** [comment]
Working. Thanks for fixing! :+1:
