### ISSUE TITLE
Static Build Problem

### ISSUE THREAD

**Issue by IcePlanet2000** [jb-alvarado/media-autobuild_suite#706]
The static build of FFMPEG is requiring the external file **libopenh264.dll** in order for it to run. This started around the time the h264 with both 8-bit and 10-bit build was available. I compiled with 8 bit only and it still requires this .dll file. I have all build options turned on.
Is it just me?

**Comment by mkver** [comment]
Then don't build libopenh264. See #690 for the rationale.
