### ISSUE TITLE
configure failed!

### ISSUE THREAD

**Issue by unixfx** [jb-alvarado/media-autobuild_suite#707]
Hey jb-alvarado.

 I got an error

> solve the problem.
> configure failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-static-32bit/ab-suite.configure.log
> This is required for other packages, so this script will exit.
>   Creating diagnostics file...
> 
> All relevant logs have been anonymously uploaded to https://0x0.st/sNXc.zip
> Copy and paste [logs.zip](https://0x0.st/sNXc.zip)

ab-suite.configure.log:

> CFLAGS: -mthreads -mtune=generic -O2 -pipe
> LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
> ../configure --prefix=/local32 --bindir=/local32/bin-video --pkg-config-flags=--static --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-openssl --enable-avisynth --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-libopenmpt --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --disable-w32threads --extra-cflags=-DPTW32_STATIC_LIB --extra-libs=-lwsock32 --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --disable-debug
> ERROR: libbluray not found using pkg-config
>

**Comment by wiiaboo** [comment]
jb-alvarado hasn't looked at this for years, by the way.

**Comment by unixfx** [comment]
Ok, I want to know how to fix this error if its possible. 

Regards.

**Comment by wiiaboo** [comment]
![image](https://i.fsbn.eu/z8XK.png)
