### ISSUE TITLE
Static ffmpeg depends on libopenh264.dll

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#709]
Is this a configuration mistake or currently unavoidable?

**Comment by wiiaboo** [comment]
Unavoidable and duplicate (triplicate actually) question.

**Comment by LigH-de** [comment]
Hmm, I swear I searched for ... something ... before asking. Sorry.

**Comment by wiiaboo** [comment]
I could add yet another option, but I'd rather not. OpenH264 is completely fucking pointless if you're not using the official binaries.
