### ISSUE TITLE
GnuTLS/Libnettle error

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#71]
Not necessarily related to media-autobuild_script.
gnutls can't be compiled now because latest MinGW updates also change/update libnettle to v3.0.
Error messages:
"Libnettle 2.7.1 was not found. Note that this version of gnutls doesn't support nettle 3.0."

best regards,
laur

**Comment by wiiaboo** [comment]
Known issue. #70 will fix it.

**Comment by jb-alvarado** [comment]
It works now, but for getting sure is better to rebuild everything.
