### ISSUE TITLE
ERROR: zvbi-0.2 not found using pkg-config

### ISSUE THREAD

**Issue by anana93** [jb-alvarado/media-autobuild_suite#711]
I do a clean install, then it shows up when compiling FFmpeg. Tried to remove FFmpeg folder, remove the zvbi.pc in pkgconfig folder, and remove the zvbi-0.2.35 folder in build folder, This error still exist.

Here's the log:
https://0x0.st/sNcR.zip

My OS: win 10 enterprise x64

**Comment by wiiaboo** [comment]
Don't open duplicate issues.
