### ISSUE TITLE
(no real issue) Amazingly flexible ffmpeg configuration, adding vmaf

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#713]
Just out of curiosity, because another video developer asked me for my experiences and if I could confirm a bug, I added `--enable-libvmaf` to **ffmpeg_options.txt**; not much else.

And MABS started to download and compile libvmaf prior to ffmpeg. As if that was intended. It possibly was? Great foresight.

And if compiling vmaf for a Win32 target did not fail due to 64-bit restricted sources, it might even have succeeded to build ffmpeg supporting vmaf.

I will try to patch the **ffmpeg_options.txt** and **media-autobuild_suite.ini** manually around that and build only a Win64 branch with it, then remove this option again. But ... thank you for this very positive experience.

And if there is any better way to discuss such things than opening an issue, please tell me how.

This is not meant to be a feature request due to the target platform restrictions of this module.

**Comment by wiiaboo** [comment]
I had no idea it was 64-bit only. I can remove it for 32-bit builds easily.

**Comment by LigH-de** [comment]
Eehm ... but you did not even include it? Please read it all again, not that you may change something I never asked for.

I only played with it and wanted to thank you for easy success. But I do not even understand yet why it worked. Your set of ffmpeg options did not contain libvmaf, yet it was enabled so easily and correctly, as if it was prepared some time, long ago...

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/dac0933576c9c0aebb8e65dd0eac46ddb4178bf2

**Comment by LigH-de** [comment]
Just for the smirk: libvmaf now has a C-only implementation to build in 32 bits too. While weare about to get rid of 32 bit building...

**Comment by 1480c1** [comment]
Perhaps, however I do know by default the 32 bit version will give different results than the 64 bit version, so we will need to apply some cflags to make sure they align on the float and double calculations

**Comment by 1480c1** [comment]
btw, after applying the relevant cflags, there seems to still be some issues, but I think I will chalk this up to printf

```bash
[libvmaf @ 0000029ee02291c0] VMAF score: 17.958143
[libvmaf @ 103f9f40] VMAF score: 17.958142
```

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/8401205955abd687c0a313e1b71fed0252eb05f2
