### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by NakedSam** [jb-alvarado/media-autobuild_suite#714]
I have this error when trying to compile
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1628214/logs.zip)
And I don't know what it means. If somebody could help me with it, I'd be grateful
`CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_clone 
/build/media-suite_helper.sh: line 93: git: command not found
`

**Comment by schmidthubert** [comment]
https://github.com/jb-alvarado/media-autobuild_suite#troubleshooting

**Comment by NakedSam** [comment]
Didn't I already went through those steps ?

**Comment by wiiaboo** [comment]
Try deleting the whole thing and running the suite again. Seems like it's broken.
