### ISSUE TITLE
Script proceeds without updating ffmpeg

### ISSUE THREAD

**Issue by GyanD** [jb-alvarado/media-autobuild_suite#715]
I ran the suite yesterday and it executed without any errors. Today, when running a ffmpeg command, I notice that the banner says `N-89656` which is two weeks old and dates to the last time I ran the suite.  After confirming that my path refers to the latest binary, I checked `ab-suite.git.update` in build\ffmpeg.git, which says,

```
vcs_update origin/HEAD
fatal: unable to access 'https://git.ffmpeg.org/ffmpeg.git/': Connection timed out after 300052 milliseconds
```

I'm surprised the script didn't error out. ffmpeg is the central tool built in the script and I, and presumably others, run it to get an updated build of ffmpeg. I suggest that the script should exit if ffmpeg update fails. Or at least give a choice to do so.

Thanks.

**Comment by wiiaboo** [comment]
Well, it should do exactly that since a few days ago.
