### ISSUE TITLE
[Feature Request] youtube-dl

### ISSUE THREAD

**Issue by rld243** [jb-alvarado/media-autobuild_suite#716]
Is it possible to add support for youtube-dl? Their releases may happen any time, but usually weekly. Sometimes they push some important fixes in master yet I have to wait until next release. I'd like to have an ability to compile youtube-dl anytime using this suite. Sorry If this was asked already.

**Comment by wiiaboo** [comment]
No.

**Comment by rld243** [comment]
Well, okay. Thanks for the answer!
