### ISSUE TITLE
Check C:/media-autobuild_suite-master/build/fribidi-git/build-64bit/ab-suite.make.log

### ISSUE THREAD

**Issue by CarlosJSA** [jb-alvarado/media-autobuild_suite#720]
Tried executing it from scratch several times. It juts won't work.

`make failed. Check C:/media-autobuild_suite-master/build/fribidi-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sNkE.zip
Copy and paste [logs.zip](https://0x0.st/sNkE.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
`

**Comment by wiiaboo** [comment]
Hey, what a coincidence, someone opened the exact same issue just hours ago.

https://github.com/jb-alvarado/media-autobuild_suite/issues/718
