### ISSUE TITLE
curl "make ca-bundle" fails

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#726]
1st run: [logs.zip](https://0x0.st/sqnP.zip)
2nd run: [logs.zip](https://0x0.st/sqny.zip)
I successfully ran MABS yesterday, but I've run into problems with the updated build from today. The first problem is with curl (the second problem is with FFmpeg/libopenmpt which I created a separate issue for: #727). I got the following error the first time I ran the new version of MABS:
```
  Running git clone for curl...
┌ curl git .......................................... [Recently updated]
├ Running uninstall...
├ Running autogen...
├ Running configure...
├ Running make...
├ Running install...
├ Running ca-bundle...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
make ca-bundle
make: *** No rule to make target 'ca-bundle'.  Stop.
make: *** No rule to make target 'ca-bundle'.  Stop.
ca-bundle failed. Check Z:/Media-AB_Suite/build/curl-git/ab-suite.ca-bundle.log
This isn't required for anything so we can move on.
├ Stripping...
└ curl-git ................................................... [Updated]
```
Here is the log referenced by that error: [ab-suite.ca-bundle.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1666031/ab-suite.ca-bundle.log)

The second time I ran the new version of MABS, it just said
```
  Running git update for curl...
curl git .................................................. [Up-to-date]
```

**Comment by wiiaboo** [comment]
Weird that it didn't error before.
