### ISSUE TITLE
FFmpeg build still fails: "libopenmpt >= 0.2.6557 not found using pkg-config"

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#730]
[logs.zip](https://0x0.st/sbXN.zip)
Although the previous issue I made for this (#727) was closed, it still hasn't been fixed by the commit ([7d641f9](https://github.com/jb-alvarado/media-autobuild_suite/commit/7d641f9bc066315f6d97077ec5c52d4c1377dab3)) that was supposed to fix it. I'm still getting the exact same error:
```
  Running git update for ffmpeg...
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-openssl --enable-avisynth --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-libopenmpt --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-opengl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --disable-debug
ERROR: libopenmpt >= 0.2.6557 not found using pkg-config
```

**Comment by wiiaboo** [comment]
It didn't recompile openmpt.

**Comment by Metaphorce812** [comment]
I managed to successfully build FFmpeg by deleting the `build\openmpt-svn` and `build\openmpt-git` folders and running MABS again.
Since the commit that caused the problem with FFmpeg and openmpt ([cc18ace](https://github.com/jb-alvarado/media-autobuild_suite/commit/7d641f9bc066315f6d97077ec5c52d4c1377dab3)) changed the openmpt source from svn to git, I'm guessing the problem was that FFmpeg was trying to use the pre-existing `build\openmpt-svn` folder. When I ran MABS after deleting those two folders, the `build\openmpt-git` folder was rebuilt while the `build\openmpt-svn` folder wasn't. That's another sign to me that the old svn folder was what was causing the FFmpeg build failure.

So, assuming I'm right, I'd recommend updating MABS to automatically delete the `build\openmpt-svn` folder, and that _should_ fix the error. And of course **end-users could just delete `build\openmpt-svn` manually for the time being**.

**Comment by wiiaboo** [comment]
FFmpeg doesn't use build folders. Deleting openmpt-svn did nothing since the suite doesn't use that anymore since the change to git. You're supposed to follow https://github.com/jb-alvarado/media-autobuild_suite/blob/master/doc/forcing-recompilations.md to force recompilations. Deleting build folders unnecessarily only makes you download potentially hundreds of MBs again before building.

**Comment by Metaphorce812** [comment]
@wiiaboo Ah, OK. Thanks for the info.

**Comment by GyanD** [comment]
I get the error too.

ffmpeg's config.log says, `Requested 'libopenmpt >= 0.2.6557' but version of libopenmpt is 0.2`

libopenmpt was recompiled.  The newly installed .pc says, `Version: 0.2`
