### ISSUE TITLE
vpx git: update from v1.6.1 to v1.7.0 not detected?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#731]
[Tag v1.7.0](https://chromium.googlesource.com/webm/libvpx/+/v1.7.0) was announced yesterday; but my last build v1.6.1-1495-g9debbc2ec is still considered as recent enough not to download updated sources and build new binaries.

**Comment by schmidthubert** [comment]
https://chromium.googlesource.com/webm/libvpx/+/master/CHANGELOG
reads 2017-01-09 v1.6.1 "Long Tailed Duck" while https://chromium.googlesource.com/webm/libvpx/+/f80be22a1099b2a431c2796f529bb261064ec6b4/CHANGELOG (which is the v1.7.0 TAG) reads 2017-01-04 v1.7.0 "Mandarin Duck". How is this a JB issue???

**Comment by LigH-de** [comment]
I don't know how MABS detects source changes worth to be downloaded and re-built. If the solution is "wait another day", fine, may it be. But I do not have the knowledge to certainly tell apart a bug in MABS from just a delay in updates of key files in a repo. I am not a C developer. I am not a Linux pro. I am not experienced in versioning systems. Please do not assume I should know all that.

**Comment by wiiaboo** [comment]
This is a vpx issue, not the suite's.

**Comment by LigH-de** [comment]
So it's Google's duty to update the master changelog so MABS can detect the update?

**Comment by schmidthubert** [comment]
>MABS detects source changes
There's no change. MASTER is MASTER and TAG vXXX is TAG vXXX, that's all, it's different branch/tree.

**Comment by schmidthubert** [comment]
>So it's Google's duty to update the master changelog so MABS can detect the update?

This is called vcs, its all non-linear. You should do a readup on the concepts ...

**Comment by wiiaboo** [comment]
The suite doesn't read from the changelog, lol.
Whatever's the way they get their version, it's broken by them, so it's their issue to fix, not mine, wtf. The suite doesn't only build at tags for vpx it's for every new commit.

**Comment by schmidthubert** [comment]
>The suite doesn't read from the changelog, lol.

I DO know that, don't worry ....

**Comment by wiiaboo** [comment]
I figure it's because whatever commit they tagged as v1.7.0 isn't actually present at master.

**Comment by schmidthubert** [comment]
Exactly, and so all is OK for now even at their end ...

**Comment by LigH-de** [comment]
My experienec is only limited, but I try to compare with x265... they have a default and a stable branch. if you check the default branch (which is more regularly updated), then you don't get the updates valid only for the stable branch, until they are merged. So ... in case of vpx, I have to wait for a merge of the master branch you are watching with the branch where the v1.7.0 tag is applied to, which may contain "experimental" commits, if this analogy is correct.

**Comment by wiiaboo** [comment]
Except it doesn't make sense that master is missing things from a release. So I'd suggest you notify them of such breakage, if you care about those new features in 1.7.0.

**Comment by schmidthubert** [comment]
I'd prefer ANY master NOT to show ANY version if EXECUTED at all, ffmpeg does that. For example this is the CHANGELOG of ffmpeg stable v3.4.1:
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/bc839fb39dc376d462856863de2933f0b6b0351a:/Changelog

while this is MASTER:
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/HEAD:/Changelog

do you see v3.4.1 in there? I don't ....

**Comment by wiiaboo** [comment]
FFmpeg's changelog is not supposed to show patch versions because those never contain new features, just security fixes and fixes in general to existing features.

**Comment by wiiaboo** [comment]
When version 3.5 is released, they rename `version <next>` to `version 3.5` and add another `version <next>` above, after which you list the new features that will come up in 3.6/4.0.

**Comment by LigH-de** [comment]
So I'll wait for branch "mandarinduck" joining the "master" branch...

**Comment by wiiaboo** [comment]
And tell them master's showing the wrong version too.

**Comment by LigH-de** [comment]
I do not yet see any way to submit issues in https://chromium.googlesource.com/ ... must be in a completely different location. Unlike github.

**Comment by LigH-de** [comment]
[Status: Fixed](https://bugs.chromium.org/p/webm/issues/detail?id=1490#c2) ... testing ... vpx git does not yet update, maybe they did not yet commit the change? Hopefully soon.

**Comment by wiiaboo** [comment]
Dunno. Both the changelog and `git describe --tags` show v1.7.0 now.

**Comment by LigH-de** [comment]
There were two merging commits in [webm/libvpx](https://chromium.googlesource.com/webm/libvpx/), 35 and 15 min ago. Seems to be a different reason.

**Comment by LigH-de** [comment]
I deleted the local??/bin-video/vpx*.exe and ran the suite again, this made vpx git find an update and build v1.7.0-69-g77108f500.

**Comment by LigH-de** [comment]
Same on the other PC: "vpx git" is considered `Already built` until I delete the binaries, then suddenly there are `Updates found`.

**Comment by wiiaboo** [comment]
Well, if you git pull before running the suite it will be confused because locally it's as up-to-date as remote.

**Comment by LigH-de** [comment]
What do you mean? Did you misunderstand what I did?

- Last time I ran the suite, vpx v1.6.1 was current.
- The git repo of libvpx was updated to v1.7.0 by merging the mandarinduck branch to HEAD on googlesource.
- I run the suite again; it does not detect the update.
- I delete the local binaries.
- I run the suite again; suddenly it detects the update and downloads it.

I did not pull outside the suite.

**Comment by wiiaboo** [comment]
No idea, then. Working fine here.
