### ISSUE TITLE
Compilation fail for vf_scale_cuda

### ISSUE THREAD

**Issue by valesho** [jb-alvarado/media-autobuild_suite#732]
Compiling is failing at libavfilter/vf_scale_cuda even having the compiler in path. Please refer to attached log and screen print:

![compiling_nvcc_fail](https://user-images.githubusercontent.com/21370260/35534848-8041389c-0520-11e8-91ad-c7e828fefa29.jpg)

Attached is output of set command at **"x64 Native Tools Command Prompt for VS 2017"** after running the media-autobuild_suite.bat file.
[environment_variables_cmd_windows.txt](https://github.com/jb-alvarado/media-autobuild_suite/files/1675274/environment_variables_cmd_windows.txt)

I do a fresh Windows/MSVS17/MSVS25 installation trying  to solve.

[logs.zip](https://0x0.st/sba9.zip)

Using last (commit e547ff5) at the time of this writing.

Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64 **is** in the path, at least before and after running **media-autobuild_suite.bat**. Just tried by running **media-autobuild_suite.bat**, didn't try by mintty/bash command line.
Also tried in plain Windows Command Prompt + path setting for cl.exe

Please also note the **warning: "_MSC_VER" is not defined**

**Comment by wiiaboo** [comment]
> Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64 is in the path.

It's not.
ffmpeg's config.log shows:
`PATH='/local64/bin-audio:/local64/bin-global:/local64/bin-video:/local64/bin:/mingw64/bin:/local64/share/info:/mingw64/share/info:/usr/share/info:/usr/local/bin:/usr/bin:/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/libnvvp:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Users/malas/AppData/Local/Microsoft/WindowsApps:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
`

**Comment by wiiaboo** [comment]
And of course _MSC_VER isn't set, the suite doesn't compile with MSVC.

**Comment by valesho** [comment]
I've updated my comment to explain better.

> cl.exe is in the path, at least before and after running **media-autobuild_suite.bat**. Just tried by running **media-autobuild_suite.bat**, didn't try by mintty/bash command line.

Running cl.exe at command prompt:
![cl_is_ok](https://user-images.githubusercontent.com/21370260/35539119-16323e1a-052f-11e8-9b2a-527dd0f77f0e.jpg)

**Comment by schmidthubert** [comment]
Run "where cl.exe" in a cmd Windows, what's the actual path?

**Comment by wiiaboo** [comment]
Or better yet, open mintty and run `which cl`. If it can't find it, it's won't be available on the suite either.

**Comment by valesho** [comment]
I'm going to close this issue and admin can delete safely.

The issue only shown when running `media-autobuild_suite.bat` in the command prompt created by "x64 Native Tools Command Prompt for VS 2017" shorcut from MS Visual Studio (shorcut is `%comspec% /k "C:\MSVS17\VC\Auxiliary\Build\vcvars64.bat"`).  Has used this shortcut to take advantage of full environment variables settings.
So, looks like it's just a batch files calling and variables inherit issue.

If Windows path or path in set through mitty /etc/profile or .bashrc, then .bat script run fine.

Hints learned: NVCC didn't compile with MSVS 2017 in the path, but compile once changed to MSVS 2015. And no more `"_MSC_VER" is not defined` message. Using commit fb32bc5

**Comment by wiiaboo** [comment]
Yeah, I specifically say you need MSVC2015 cl.exe in PATH in the readme.
