### ISSUE TITLE
ffmpeg compiling error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#733]
ERROR: libopenmpt >= 0.2.6557 not found using pkg-config

┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK!
FFmpeg and related apps will depend on Nvidia drivers!
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-openssl --enable-avisynth --enable-chromaprint --enable-cuda-sdk --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libnpp --enable-libopenh264 --enable-libopenmpt --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --enable-libvmaf --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --extra-cflags=-IC:/PROGRA~1/NVIDIA~2/CUDA/v9.1/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA~2/CUDA/v9.1/lib/x64 --disable-debug

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check D:/ffmpeg-autobuild/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.

https://0x0.st/sber.zip

**Comment by wiiaboo** [comment]
Should be fixed already.

**Comment by kliffgomel** [comment]
not working yet
ERROR: libopenmpt >= 0.2.6557 not found using pkg-config
https://0x0.st/sb9_.zip

**Comment by wiiaboo** [comment]
Except you didn't do what I told you to.
