### ISSUE TITLE
xvc support

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#734]
Would be nice if https://github.com/divideon/xvc could be added.

**Comment by wiiaboo** [comment]
Sounds like a shit codec if it's "based" on MPEG stuff and changing the codec if you get sued.
Why would anyone want this?

**Comment by Selur** [comment]
To try whether it is good or not.

**Comment by wiiaboo** [comment]
Well, if you just wanna try it, just run mintty and
```bash
cd /build
source media-suite_helper.sh
git clone https://github.com/divideon/xvc.git
cd xvc
do_cmake -DBUILD_TESTS=off
ninja
```
and there you go.
I think I'll pass on adding a lawsuit liability and waste of time codec no one will ever use.

**Comment by LigH-de** [comment]
PS: Was the patch now included?

```
┌ xvc git  ............................................... [Updates found]
├ Running uninstall...
15.patch
        Patch could not be applied with `git am`. Continuing without patching.
```

**Comment by 1480c1** [comment]
Yep https://github.com/m-ab-s/media-autobuild_suite/commit/1c6b35eefb6029fa0116772da5cdf5dda2dfbc27
