### ISSUE TITLE
(cosmetic) xterm-256color is unreliable when using MinGW manually

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#735]
There are apparently several reasons - e.g. https://github.com/Alexpux/MSYS2-packages/issues/1124 or https://github.com/mintty/mintty/issues/377#issuecomment-137728631 - why the `xterm-256color` terminal mode (which appears to be set up as default?) can be unreliable in bash+mintty, in a way that backspace and cursor history functions do not clear the input line, and the text cursor does not return to a position right after the prompt. The mode `xterm` is more reliable. But I believe that makes the output miss a few colorization effects.

This may not be apparent if you let the suite just build and close. But if you want to use the MinGW shell manually, you will see the command line expand more and more.

**Comment by wiiaboo** [comment]
Why is this a suite issue? I can't do anything with it. Go pester them to fix it.

**Comment by LigH-de** [comment]
Suggesting to consider not to use xterm-256color is no reason to mention it here?

**Comment by wiiaboo** [comment]
xterm-256color is the only way to support proper colors. For the purpose of the suite it still works fine.

**Comment by LigH-de** [comment]
Well, @Alexpux is going to discover the reason; so the best about this report may be: If anyone else searches for the same symptoms in this project, they may find this closed issue containing links to further details.

**Comment by LigH-de** [comment]
An update for bash to version 4.4.019-1 in MSYS2 fixed the shell history in terminal mode xterm-256color in mintty for me.
