### ISSUE TITLE
Auto-confirm installation of lz4 packages?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#737]
Every time I re-install the suite, there is one package (pair) which is never automatically installed:

```
Install:
mingw-w64-i686-lz4
mingw-w64-x86_64-lz4
install packs [y/n]?
```

Is it possible to auto-confirm here too?

**Comment by wiiaboo** [comment]
Install them manually? Never had that problem.

**Comment by wiiaboo** [comment]
Or remove them from /msys64/pac-mingw-extra.pk. I can't see anything that explicitely requires it.
