### ISSUE TITLE
Suite build fails at libwebp

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#742]
```
┌ libwebp git ....................................... [Recently updated]
├ Running autoreconf...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
autoreconf -fiv
autoreconf failed. Check E:/AB-Suite/build/libwebp-git/ab-suite.autoreconf.log
This is required for other packages, so this script will exit.
```
[logs.zip] (https://0x0.st/scLn.zip)

**Comment by BlackScreen** [comment]
I just noticed there are error messages in the two windows at the start two.
See here: https://imgur.com/zyeKdmR
And here: https://imgur.com/K5RBDAU
Also before the error a few things were updated. Maybe this is the reason for the error above?

**Comment by wiiaboo** [comment]
Sorry, I can't read german.

**Comment by wiiaboo** [comment]
I can't reproduce the issue, so it does seem a problem on your side.
Just run `pacman -Syyuu` manually.

**Comment by BlackScreen** [comment]
No errors after running the command you said. The error from the first post is also gone - so. Closed. Sorry and thanks.

**Comment by Selur** [comment]
I confirm, running
> pacman -Syyuu
two times fixed the issue for me.
