### ISSUE TITLE
git.clone failed. Check C:/media-autobuild_suite/build/ab-suite.git.clone.log

### ISSUE THREAD

**Issue by TimWardC3** [jb-alvarado/media-autobuild_suite#744]
Download latest and tried to build on 64bit Windows 7 and it failed with "git.clone failed. Check C:/media-autobuild_suite/build/ab-suite.git.clone.log". It said check "ab-suite.git.clone.log" but that didn't give me anything I could understand... no idea how to get this working 

CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_clone 
Cloning into 'freetype2-git'...

[compile.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1711631/compile.log)
[ab-suite.git.clone.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1711632/ab-suite.git.clone.log)

**Comment by wiiaboo** [comment]
Well, you could try `cd /build; git clone https://git.savannah.gnu.org/git/freetype/freetype2.git freetype2-git` manually in mintty. If it doesn't work, it's either down or some firewall on your end is blocking it.

**Comment by TimWardC3** [comment]
Hi Thanks for the quick answer, I tried that and all it said was "Cloning into 'freetype2-git'..." and appears to do nothing.
I can browse to https://git.savannah.gnu.org/git/freetype/freetype2.git/ OK.
I Wiresharked and could see no attempt bring made to connect to the site (as i did when browsed).
I turned off my virus scanner/firewall and nothing different.
We've tried this on two different machines just in case and get the same.

**Comment by wiiaboo** [comment]
You could try `git clone -v` for verbose, but it's working fine here, so I doubt it's the repo being down.

**Comment by TimWardC3** [comment]
Tried that and it still outputs nothing more than "Cloning into 'freetype2-git'..." and then returns to the command line immediately.

**Comment by wiiaboo** [comment]
Well, do other repositories work at all? https://anongit.freedesktop.org/git/fontconfig or https://github.com/behdad/harfbuzz.git ?
If not, that's probably a broken installation or something. Can't help there.

**Comment by TimWardC3** [comment]
The same thing, outputs that's its going to clone then just stops with no further output. Just looks like git is not even trying... and reporting no errors. I wondered if it was file permissions so manually created the directory, and it deletes it when trying a git clone into in.

I've scrubbed the install and tried fresh and get the same result, also on another machine. I guess I'll try at home on a Win 10 to see if I get anything different.

**Comment by TimWardC3** [comment]
I can confirm that running "pacman -Syyuu" manually (although that then crashed mintty) worked in getting it past this problem. Also it had worked fine on my home Win 10 (as long as I disabled Avast) without doing this.
