### ISSUE TITLE
 libwebp git  fails,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#745]
[logs.zip](https://0x0.st/scgk.zip)
 [logs.zip](https://0x0.st/scg5.zip)

**Comment by myfreeer** [comment]
Check https://github.com/jb-alvarado/media-autobuild_suite/issues/742#issuecomment-364179054

**Comment by wiiaboo** [comment]
It's broken everywhere where pacman is run automatically, like appveyor, etc.
