### ISSUE TITLE
Error building opus-tools

### ISSUE THREAD

**Issue by DoctorVanGogh** [jb-alvarado/media-autobuild_suite#746]
```
...
┌ opus-tools git ....................................... [Updates found]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
D:/Projekte/Mediabuild/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x2a56): undefined reference to `BIO_meth_set_destroy'
D:/Projekte/Mediabuild/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x2aa6): undefined reference to `BIO_meth_free'
D:/Projekte/Mediabuild/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x2cd6): undefined reference to `BIO_meth_free'
D:/Projekte/Mediabuild/local32/lib/libopusurl.a(libopusurl_la-http.o):(.text+0x4690): undefined reference to `OPENSSL_init_ssl'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:646: opusdec.exe] Error 1
make[2]: Leaving directory '/build/opus-tools-git/build-32bit'
make[1]: *** [Makefile:1064: all-recursive] Error 1
make[1]: Leaving directory '/build/opus-tools-git/build-32bit'
make: *** [Makefile:507: all] Error 2
```

**Comment by DoctorVanGogh** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1714928/logs.zip)

**Comment by wiiaboo** [comment]
Force rebuild of opusfile.

**Comment by DoctorVanGogh** [comment]
No clue how... would deleting `build/opus-tools-git` be sufficient?

**Comment by schmidthubert** [comment]
RTFM or the [frontpage](https://github.com/jb-alvarado/media-autobuild_suite) here. All you have to do is search for the word "force" ...

**Comment by wiiaboo** [comment]
Just delete /local32/lib/pkgconfig/libopusfile.pc.

**Comment by DoctorVanGogh** [comment]
@schmidthubert _Thank you_ for those ~~kind and helpful~~ words.

Sadly `opus tools` is neither mentioned in the 'using pkgconfig' section or the 'other' section... but well... that's okay.
And since the `lib<XYZ>` file is _not_ called like the package you're SOL unless you know that `libfoo` belongs to package `bar`...

Alas... things worked on a clean bootstrap last fall, so to preempt other issues stemming from a previous compile, I'll just go the nuclear option and do a `git reset --hard HEAD` and kill the build, local & msys directories.

**Comment by schmidthubert** [comment]
For the even more lazy ones there's `format <drive>:/q`, which works even faster without any reading at all ... :+1:

**Comment by wiiaboo** [comment]
Or just delete a tiny little file and rerun the suite, but sure. Other than time and energy, cleanups don't waste anything.

**Comment by DoctorVanGogh** [comment]
Yeah, a tiny file _might_ have done it, but the total compilation time for a full rebuild wont be _that_ much longer than an incremental update from a previous result.

And _my_ time and attention on a clean rebuild is just copying the ini file. With a 'wonky' upgrade I might have to recheck multiple times if several packages or architectures have issues and need to restart several times.

---

Also, wanted to take this time and say **THANK YOU** for this amazing project. As nice as rdp's version is, it's always been a bit finicky for my windows trained fingers & eyes. It's great being able to do a native compile.
