### ISSUE TITLE
 https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.zip does not exist

### ISSUE THREAD

**Issue by TimWardC3** [jb-alvarado/media-autobuild_suite#748]
Hi, https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.zip does not exist.
apache-ant-1.10.2-bin.zip was released 2018-02-06 and I assume apache-ant-1.10.1-bin.zip has very recently. 

Changing the path and hash in media-suite_compile.sh worked fine

**Comment by wiiaboo** [comment]
And they just remove the file like that? wtf.

**Comment by TimWardC3** [comment]
Yup, not really very helpful or considerate of them.
