### ISSUE TITLE
cannot compile, any help?

### ISSUE THREAD

**Issue by addriumruss** [jb-alvarado/media-autobuild_suite#750]
Starting 32bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat

        Starting 32bit compilation of global tools
  Running git update for freetype2...
┌ freetype2 git ..................................... [Recently updated]
├ Running autogen...
├ Running configure...
Likely error:
/build/freetype2-git/builds/unix/configure  '--build=i686-w64-mingw32' '--host=i686-w64-mingw32' '--target=i686-w64-mingw32' '--prefix=/local32' '--disable-shared' '--enable-static' '--bindir=/local32/bin-global' '--with-harfbuzz=no' '--with-png=no' '--with-bzip2=no'
configure: loading site script /mingw32/etc/config.site
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking for i686-w64-mingw32-gcc... gcc
checking whether the C compiler works... no
configure: error: in `/build/freetype2-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [/build/freetype2-git/builds/unix/detect.mk:83: setup] Error 77
configure failed. Check D:/MinGWSuite/build/freetype2-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sTe_.zip
Copy and paste [logs.zip](https://0x0.st/sTe_.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[ab-suite.configure.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1730088/ab-suite.configure.log)
[config.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1730089/config.log)

**Comment by wiiaboo** [comment]
`/mingw32/bin/gcc: cannot execute binary file: Exec format error`
Broken installation.
