### ISSUE TITLE
x264 light build

### ISSUE THREAD

**Issue by mkver** [jb-alvarado/media-autobuild_suite#758]
I have a question regarding the light build of x264 (option 6): How is one supposed to use the lavf/ffms inside the binaries at all? The only way I could use them was by manually enabling the file and pipe protocols in the builds. Otherwise it always fails with lavf and ffms and falls back onto avisynth input.
Btw: it seems that one can safely disable all bsf for this build; one can still decode H.2645 inside mp4/Matroska. And one can also disable e.g. d3d11va, dxva2, cuda, cuvid, schannel, iconv. If I am not mistaken, then there isn't even a real way to use this stuff inside the x264 build at all.

**Comment by wiiaboo** [comment]
Well, what options did work exactly then? I don't use x264.

**Comment by LigH-de** [comment]
Just rebuilding after recent updates; I believe commit c566f85ed18a791f16c03c63da136b3f0272c731 fixes this issue by updating LAVF. A quick test confirms that FFMS2 can now index an AVI input.

**Comment by mkver** [comment]
I used
```
--disable-bsfs \
--enable-protocol=file,pipe \
--enable-bsf=extract_extradata \
--disable-amf --disable-d3d11va --disable-dxva2 --disable-iconv --disable-schannel --disable-cuda --disable-cuvid
```
The h2645_mp4toannexb bsf are unnecessary to actually decode H.2645 in mp4/Matroska; without extract_extradata several transport streams failed to be decoded. Also the vp9 related bitstream filters don't seem to be needed, at least not for the youtube videos I tested.

**Comment by wiiaboo** [comment]
The bsfs being enabled or not is probably negligible. Same with the autodetected libs.
