### ISSUE TITLE
Is it okay to ask a question? QuickSync...

### ISSUE THREAD

**Issue by Baddest-Juju** [jb-alvarado/media-autobuild_suite#760]
I'm very pleased with the NVENC/CUDA/CUVID functionality. It's very fast. But I wanted to experiment and compare with Intel QuickSync. However, my experience with it has not been good. I have QuickSync working in Windows encoders such as Handlebar, but in ffmpeg it'll often run into an unrecoverable error very quickly in the encoding. No fault of your own, just seems to be a shortcoming within ffmpeg itself.

In your experience, is there a way to utilize QuickSync in ffmpeg that is reliable on Windows 10 64 bit?

**Comment by wiiaboo** [comment]
No idea. Ask FFmpeg. From what I know, it's very dependant on how recent your CPU is.
