### ISSUE TITLE
(Suggestion) A small tweak to prevent erroneous an report

### ISSUE THREAD

**Issue by Baddest-Juju** [jb-alvarado/media-autobuild_suite#764]
Sometimes people run the batch script as an administrator, but this causes the current directory (but not working directory) to be C:\Windows\System32

Include cd /d "%~dp0" to fix this potential issue, I'd put it right below setlocal.

**Comment by wiiaboo** [comment]
Why would anyone want to run this as administrator?

**Comment by Baddest-Juju** [comment]
I guarantee someone at some point has, and someone at some point will complain about it.
