### ISSUE TITLE
MABS Doesn't Compile Latest Version of x265

### ISSUE THREAD

**Issue by Metaphorce812** [jb-alvarado/media-autobuild_suite#765]
I noticed that [x265 was updated to v2.7 on Feb. 21, 2018](https://www.videohelp.com/software/x265-Encoder), yet the version compiled by MABS is 2.6+15 (as of March 9, 2018). I updated MABS, deleted `local64\lib\pkgconfig\x265.pc` to force a recompilation of x265, then ran MABS again, and it still compiled x265 as v2.6+15. [This x265 binary download mirror](http://msystem.waw.pl/x265/) has x265 v2.7+9 & v2.6+49 binaries from the default branch and v2.7+1 from the stable branch. So I'm wondering why MABS doesn't compile the latest version of x265. 
Since this isn't a bug that causes MABS to fail, I don't have a logs.zip file, but I've attached my `compile.log`, `last_successful_run`, and `media-autobuild_suite.ini` files, as well as a screenshot of the command line output from running the command `x265 -V` with the binary compiled by MABS and the v2.7+9 binary from the download mirror I linked to.
[MABS_x265.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1798428/MABS_x265.zip)

**Comment by schmidthubert** [comment]
The timestamp of my x265.exe is March 5th 14:39, my last run of the suite. A `x265 --version` puts out
`x265 [info]: HEVC encoder version 2.7+8-613d9f443769` so not +9 but at least v2.7 already. Try deleting your build/x265 folder and try again?

**Comment by Metaphorce812** [comment]
OK, I tried that and it gave me this error (but for some reason it didn't create a logs.zip file):
```
  Running hg clone for x265...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_clone
abort: No module named sslutil!
hg.clone failed. Check Z:/Media-AB_Suite/build/ab-suite.hg.clone.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...


ERROR:
Duplicate filename on disk:
ab-suite.git.reset.log
ab-suite.git.reset.log


Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```
And the error message in `ab-suite.hg.clone.log` is:
```
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_clone 
abort: No module named sslutil!
```
[x265_Compile_Error_Files.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1798523/x265_Compile_Error_Files.zip)

**Comment by schmidthubert** [comment]
Seen that myself once. Reboot your PC, delete the x265 directory again and run the script again. Something is wrong with your install ...

**Comment by wiiaboo** [comment]
Working fine here.

**Comment by wiiaboo** [comment]
```bash
$ hg log -r. --template "{latesttag}+{latesttagdistance}-{node}"
2.7+12-98e48e8dd6ab5747ed5dd9eb03e344054d659f63
```

**Comment by Metaphorce812** [comment]
@schmidthubert I tried your suggestion but got the same error. So I deleted the whole suite, downloaded the latest version, ran it, and now I've got x265 v2.7+15, which is the latest build. So I'm not sure what the issue was, but it's resolved now.
