### ISSUE TITLE
Static ffmpeg build depens on libopenh264.dll

### ISSUE THREAD

**Issue by fast9881** [jb-alvarado/media-autobuild_suite#766]
It's three days that i'm trying to build static ffmpeg but it depends on libopenh264.dll and i don't know why

**Comment by wiiaboo** [comment]
And it'll still depend on openh264 if you try it again in three days.

https://github.com/jb-alvarado/media-autobuild_suite/issues/688
https://github.com/jb-alvarado/media-autobuild_suite/issues/690
https://github.com/jb-alvarado/media-autobuild_suite/issues/709

**Comment by fast9881** [comment]
So could you please explain why an old build i made with this suite didn't need that dll?
