### ISSUE TITLE
Fresh install on W7-32b: compiling sndfile fails, can't run autogen, guile fails compiling components

### ISSUE THREAD

**Issue by yunhai2009** [jb-alvarado/media-autobuild_suite#767]
@jb-alvarado 
(autogen --version) < /dev/null > /dev/null 2>&1 || {
        echo
        echo "You must have GNU autogen installed to compile $package."
        echo "Download the appropriate package for your distribution,"
        echo "or get the source tarball at ftp://ftp.gnu.org/pub/gnu/"
		result="no"
        DIE=1
}

autogen --version cannot be used.

**Comment by wiiaboo** [comment]
Doesn't fail here. Maybe 32-bit Msys2 is broken, like always.

**Comment by wiiaboo** [comment]
Report the issue to https://github.com/Alexpux/MSYS2-packages, btw.
I can't fix MSYS2 issues, and looking at the list of issues, absolutely no one is using 32-bit either.
