### ISSUE TITLE
[Question] How to compile with the "decklink" parameter

### ISSUE THREAD

**Issue by tenisak** [jb-alvarado/media-autobuild_suite#769]
I'm trying to compile FFmpeg, but I do not know what settings to use. I tried compiling multiple times, but the decklink still does not work :-1:  

I need to compile with these parameters + parameters needed for [decklink](https://www.ffmpeg.org/ffmpeg-devices.html#decklink): ``--enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx``

It seems that for decklink these parameters should be enough: `--enable-decklink`. But I do not know how to set it up in media-autobuild_suite.

**Can anyone please advise me who you are compiling with the decklink parameter?** 

(My goal is to use [ffmediaelement](https://github.com/unosquare/ffmediaelement) for the decklink card. But ffmediaelement for its operation recommends compiling ffmpeg from [Zeranoe](https://ffmpeg.zeranoe.com/builds/). But it is not compiled with the decklink parameter. Zeranoe compilation contains the following files: avcodec-57.dll, avdevice-57.dll, avfilter-6.dll, avformat-57.dll, avutil-55.dll, postproc-54.dll, swresample-2.dll, swscale-4.dll, ffmpeg. exe, ffplay.exe, ffprobe.exe)

**Comment by wiiaboo** [comment]
It's included with Zeranoe because decklink is nonfree. So you can't redistribute FFmpeg compiled with decklink support.

**Comment by tenisak** [comment]
Thanks for the tip for editing INI files. It helped. 
BTW: What specific license issues are there?

**Comment by wiiaboo** [comment]
Decklink SDK uses a restrictive, unredistributable license.
