### ISSUE TITLE
libbluray can build when it's unnecessary

### ISSUE THREAD

**Issue by Baddest-Juju** [jb-alvarado/media-autobuild_suite#771]
line 870 ``if { [[ $ffmpeg != "no" ]] && enabled libbluray; } || ! mpv_disabled libbluray; then``

should be

``if { [[ $ffmpeg != "no" ]] && enabled libbluray; } || { [[ $mpv != "n" ]] && ! mpv_disabled libbluray; }; then``

 

line 899 ``if { { [[ $ffmpeg != "no" ]] && enabled libbluray; } || ! mpv_disabled libbluray; } &&``

should be

``if { { [[ $ffmpeg != "no" ]] && enabled libbluray; } || { [[ $mpv != "n" ]] && ! mpv_disabled libbluray; }; } &&``

**Comment by wiiaboo** [comment]
mpv_enabled/disabled() already return 1/0 if mpv is "no". Was just typoed.
