### ISSUE TITLE
clean_suite misses .\build\angle-latest-win##.7z

### ISSUE THREAD

**Issue by Baddest-Juju** [jb-alvarado/media-autobuild_suite#772]
Not 100% sure clean_suite is the function that's supposed to handle it, but...

On a clean first time run, `build\angle-latest-win64.7z` remained in my build directly despite its `build\angle-latest-win64\` directory being present with all contents. Subsequent runs did not take care of it either. Seems to be a tiny oversight unless I'm mistaken.

**Comment by wiiaboo** [comment]
It's supposed to.  The filename doesn't change with newer builds, so the file is needed for curl to check if it's newer than the server's.

**Comment by Baddest-Juju** [comment]
``wget -qO- https://i.fsbn.eu/pub/angle/ | grep -Pom1 'angle(.*?)win64.7z' | head -n 1`` will resolve the latest  file. Then you can just append the output of that onto https://i.fsbn.eu/pub/angle/

**Comment by wiiaboo** [comment]
> wget -qO- https://i.fsbn.eu/pub/angle/ | grep -Pom1 'angle(.*?)win64.7z' | head -n 1 will resolve the latest file.

What's the point? That still doesn't tell if the file is newer than what's installed, just that it's the latest, which is the point of symlinking it to "angle-latest". There's no kept reference other than the actual file to compare it to the server's.
