### ISSUE TITLE
how to use vsfilter without avisynth?

### ISSUE THREAD

**Issue by anoosi** [jb-alvarado/media-autobuild_suite#773]
hello..
i need to use vsfilter with ffmpeg without avisynth script.avs ...
libass is a good but for rtl arabic, persian, urdu it doesn't satisfied me..

i know vsfilter works with DirectShowSource .. but i need to use without depend on DirectShowSource, just put vsfilter.dll in same dir ffmpeg ..
i was used x264_custom https://github.com/jpsdr/x264 it's have a patch for use vsfilter without install avisynth and in x264 params `--sub "sub.ass"`..

can i change the git of x264 from media-suite_compile.sh to https://github.com/jpsdr/x264.git?
and is that allow me to use vsfilter with libx264?

my greetings

**Comment by wiiaboo** [comment]
I have no idea. Ask that guy.
