### ISSUE TITLE
[question] compile works but my changes keep getting overwritten. how to stop updates?

### ISSUE THREAD

**Issue by badhras** [jb-alvarado/media-autobuild_suite#775]
First of all, credit where credit is due: this is great script. Thank you.

As to my issue/question... Every time I make changes to source files, my changes get overwritten. I've attempted changes to files in "build\mpv-git\video\" and "build\ffmpeg-git\libavutil\" and running media-autobuild_suite.bat causes my changes to get overwritten.

The ini file's updateSuite=2, but I'm guessing that doesn't control whether the source pulled in from other repositories get updated. Is there an easy way to disable the updates to source files?

**Comment by wiiaboo** [comment]
The script isn't made to support user changes to the local repos.

**Comment by badhras** [comment]
Thank you for the insight and the examples. This gives me something to examine.

**Comment by badhras** [comment]
Can you provide some advice as to what I'm doing incorrectly? I suspect my errors are related to relative folder paths, but I'm unsure how to correct things.

I created ./build/mpv_extra.sh, which has:
`#!/bin/sh
git am ./mpv-git/video/test.patch || git am --abort`

I created the ./build/mpv-git/video/test.patch file using **git format-patch**, after creating a branch. The test.patch is supposed to modify **./build/mpv-git/video/d3d.c** although I noticed that the .patch file refers to **video/d3d.c**.

I see that media-suite_compile.sh tests for mpv_extra.sh's existence, and I think **source** is supposed to cause the mpv_extra.sh script to run. Did I put mpv_extra.sh in the correct folder: **./build** ?

**Comment by schmidthubert** [comment]
You need to create your patches outside /build ...

**Comment by schmidthubert** [comment]
... or better NOT into one of the /build-directories AT ALL.

**Comment by wiiaboo** [comment]
> Use ffmpeg_extra.sh inside ffmpeg-git or mpv_extra.sh inside mpv-git

`#!/bin/sh` isn't needed, but if you do use it, it needs to be the first line and on its own.

> You need to create your patches outside /build ...

No, the patches can be anywhere, even not locally at all, but you need the proper path to them.
The scripts are run while inside `/build/mpv-git` or `/build/ffmpeg-git` respectively.

**Comment by schmidthubert** [comment]
> the patches can be anywhere
Yes. But once you need to delete a subdir under /build for some reason then that patch is gone so better put them outside /build ... It would be VERY nice to have a "/patches"-dir along the /build-dir and that it could be addressed by "do_patch" with "file:///patches/mypatch.diff" etc or something ...

**Comment by wiiaboo** [comment]
There used to be something like that, but it was painful to keep them updated if people don't update the suite.

**Comment by schmidthubert** [comment]
Updated? The /patches-dir should be for "personal" patches, like if someone wants to apply one of those special patches to x264 etc. Keeping the /patches-dir up-to-date is UP to the user if "public" patches ar put there instead of downloading (the latest) ...

**Comment by badhras** [comment]
Thank you all for the help.
