### ISSUE TITLE
git address for libbluray / libudfread seems out of date

### ISSUE THREAD

**Issue by joagle** [jb-alvarado/media-autobuild_suite#776]
Hi,
thanks so much for this amazing project!

I just tried compiling on Windows 10 using the instructions provided and everything goes perfectly according to plan up to libbluray.
It wants to
`git clone git://git.videolan.org/libbluray.git` and
`git clone git://git.videolan.org/libudfread.git `
but fails (timeout).

I was able to successfully clone like this from the command line:
```
git clone https://git.videolan.org/git/libbluray.git 
git clone https://git.videolan.org/git/libudfread.git 
```

Apparently Videolan have restructured their git addressing scheme.

I was able to fix this manually in media_autobuild_compile.sh for libbluray, but the address to libudfread.git seems to be part of the libbluray repositoy and I haven't found a workaround for that one yet. Maybe libbluray will need to be disabled until it is fixed there?

Best,
J

**Comment by wiiaboo** [comment]
I'm not using `git://git.videolan.org/libbluray.git` anywhere.

**Comment by wiiaboo** [comment]
And regarding the libudfread, you should ask libbluray to change their .gitmodules file then. They might not want to if the https:// repo doesn't support git authentication.

**Comment by joagle** [comment]
Just for sake of completeness I would like the leave the error message that disrupts the config step on my system (Windows 10):
```
┌ libbluray git ..................................... [Recently updated]
├ Running git.submodule...
Likely error:

fatal: clone of 'git://git.videolan.org/libudfread.git' into submodule path '/build/libbluray-git/contrib/libudfread' failed
Failed to clone 'contrib/libudfread'. Retry scheduled
Cloning into '/build/libbluray-git/contrib/libudfread'...
fatal: unable to connect to git.videolan.org:
git.videolan.org[0: 88.191.250.5]: errno=Connection timed out
git.videolan.org[1: 2a01:e0d:1:3:58bf:fa02:c0de:c01d]: errno=Network is unreachable

fatal: clone of 'git://git.videolan.org/libudfread.git' into submodule path '/build/libbluray-git/contrib/libudfread' failed
Failed to clone 'contrib/libudfread' a second time, aborting
git.submodule failed. Check C:/(...)/media-autobuild_suite-master/build/libbluray-git/ab-suite.git.submodule.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sB3W.zip
Copy and paste [logs.zip](https://0x0.st/sB3W.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```
Cheers, j

**Comment by wiiaboo** [comment]
But do you still have an issue with udread/libbluray?
