### ISSUE TITLE
How long does it usually take to compile a custom FFMPEG release from everything with this little neat program?

### ISSUE THREAD

**Issue by DumbJoe** [jb-alvarado/media-autobuild_suite#777]
So far it's been a day....how long more do I need to wait?? Y_Y Surely it doesn't take this long to compile a custom FFMPEG from source with all the extras....

**Comment by wiiaboo** [comment]
As long as your computer needs it, but a day seems too much, unless you're on a Pentium 4 or something shitty like that. If it's not moving for more than an hour, it could be stuck in something.
With a i5 3570K it takes me a couple of hours for a full build. Would be something like 30 mins in Linux.

**Comment by DumbJoe** [comment]
Oh so it's not suppose to take a day or longer.....I"m on a 2015 laptop....

Well it crashed the laptop(like literally all windows disappeared and it was just blank screen...) so I just gave up as I'm not prepared to wait another day or longer just to compile *one* program.... 

Used dbPoweramp instead for the last remaining conversions...

Waste of time, lol....but thanks for replying anyways! ☺
