### ISSUE TITLE
srt build error

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#779]
Running git clone for srt...
┌ srt git ........................................... [Recently updated]
├ Running cmake...
├ Running build...
Likely error:
collect2.exe: error: ld returned 1 exit status
[38/38] Linking CXX executable utility-test.exe
ninja: build stopped: subcommand failed.
[1/2] Linking CXX executable stransmit.exe
FAILED: stransmit.exe
cmd.exe /C "cd . && D:\media-ab_suite\msys64\mingw32\bin\c++.exe -mthreads -mtune=generic -O2 -pipe   -Wall -Wextra -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ CMakeFiles/stransmit.dir/apps/stransmit.cpp.o CMakeFiles/stransmit.dir/common/uriparser.cpp.o CMakeFiles/stransmit.dir/common/socketoptions.cpp.o  -o stransmit.exe -Wl,--major-image-version,0,--minor-image-version,0  libsrt.dll.a -lws2_32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/libgcc_eh.a(unwind-dw2.o):(.text+0x22a0): multiple definition of `_Unwind_Resume'
libsrt.dll.a(d002473.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/media-ab_suite/build/srt-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sB3M.zip
Copy and paste [logs.zip](https://0x0.st/sB3M.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by Barough** [comment]
Never seen this 'tool' being compiled earlier. It was the 1st thing after x265 that 'popped' up.

**Comment by Metaphorce812** [comment]
[logs.zip](https://0x0.st/sB0N.zip)
Getting the same error here with a 64-bit build:
```
┌ srt git ........................................... [Recently updated]
├ Running cmake...
├ Running build...
Likely error:
collect2.exe: error: ld returned 1 exit status
[38/38] Linking CXX executable utility-test.exe
ninja: build stopped: subcommand failed.
[1/2] Linking CXX executable stransmit.exe
FAILED: stransmit.exe
cmd.exe /C "cd . && Z:\Media-AB_Suite\msys64\mingw64\bin\c++.exe -mthreads -mtune=generic -O2 -pipe   -Wall -Wextra -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ CMakeFiles/stransmit.dir/apps/stransmit.cpp.o CMakeFiles/stransmit.dir/common/uriparser.cpp.o CMakeFiles/stransmit.dir/common/socketoptions.cpp.o  -o stransmit.exe -Wl,--major-image-version,0,--minor-image-version,0  libsrt.dll.a -lws2_32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
Z:/Media-AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/libgcc_eh.a(unwind-seh.o):(.text+0x3c0): multiple definition of `_Unwind_Resume'
libsrt.dll.a(d002471.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check Z:/Media-AB_Suite/build/srt-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
```

**Comment by LigH-de** [comment]
OpenSRT is new via commit 5f74a2e3bc27ceae5f086e23a15d6872f262e47a

You may have to recreate the ffmpeg linker option file `build/ffmpeg_options.txt` if you use `ffmpegChoice=1` (with customizable options file) when you recognize a new library being supported in the commits list. If not, libsrt is only used in "full" mode (`ffmpegChoice=4` in `build/media-autobuild_suite.ini`). So if you restrict your ffmpeg options to Light (`ffmpegChoice=2`) or Zeranoe (`ffmpegChoice=3`), you won't see this issue.
