### ISSUE TITLE
You manually enabled the feature 'egl-angle', but the autodetection check failed.

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#781]
Checking for OpenGL ANGLE headers                                 : no
You manually enabled the feature 'egl-angle', but the autodetection check failed.
configure failed. Check C:/Users/kuh3h/Downloads/media-autobuild_suite/build/mpv-git/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sBdO.zip
Copy and paste [logs.zip](https://0x0.st/sBdO.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Try deleting the angle-latest-win64.7z archive from `build/`. For some reason it didn't install them.
