### ISSUE TITLE
mpv build  need openssl?

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#782]
from https://github.com/jb-alvarado/media-autobuild_suite/issues/781
maybe it`s extract only error.

i manually copied egl-angle headers to local64/include folder from media-autobuild_suite\build\angle-latest-win64\.

build egl-angle  configure check pass but suddenly need openssl lib.

but i used gnutls for all other(ffmpeg mplayer etc...).
why only mpv need openssl?

┌ mpv git ........................................... [Recently updated]
├ Running configure...
├ Running build...
Likely error:
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/Users/kuh3h/Downloads/media-autobuild_suite/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sBd3.zip
Copy and paste [logs.zip](https://0x0.st/sBd3.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
No idea. Do you absolutely need all those 200 external libraries in FFmpeg?

**Comment by pat357** [comment]
Both ffmpeg and mpv need openssl if you have **--enable-libsrt** in your config for ffmpeg.
Is this the case for you kuh3h3 ?

**Comment by wiiaboo** [comment]
This was before srt change.

**Comment by pat357** [comment]
Opusfile (opusurl) also needs openssl

**Comment by wiiaboo** [comment]
Problem is some lib depending on openssl and that dependence not being visible in ffmpeg's pkgconfig files.
I don't have the availability to check which of the full options triggers this, so I'm just going with closing this.
If you find out which one does, I can add some workaround.

**Comment by kuh3h3** [comment]
full option? you mean this?

mpv_options.txt [https://file.io/yjV8lR](url)
ffmpeg_options.txt [https://file.io/73CNs1](url)

**Comment by kuh3h3** [comment]
mpv_options.txt
 https://justpaste.it/4y30f

ffmpeg_options.txt
 https://justpaste.it/4ggdi

**Comment by wiiaboo** [comment]
Well, that doesn't really tell me anything. You have almost every single lib enabled.

**Comment by wiiaboo** [comment]
Remove half the libs, compile and check if it's still needed. If it works, try enabling the other half. If that one errors, divide that one in half again and repeat until you pinpoint which lib actually needs openssl but is missing from the pkgconfig.

Outside of the weekends I don't really have time to do it, so it's on you if you want this fixed faster to do that pinpointing yourself.
