### ISSUE TITLE
Error while Creating ffmpeg with media-autobuild_suite

### ISSUE THREAD

**Issue by ThomasN24** [jb-alvarado/media-autobuild_suite#783]
Hi,
I got an error while creating a ffmpeg version with media-autobuild_suite. The script got an error while try to access the URL:  https://anongit.freedesktop.org/git/fontconfig fontconfig-git
If i try this via a browser I got an 404.
[ab-suite.git.clone.log](https://github.com/jb-alvarado/media-autobuild_suite/files/1859207/ab-suite.git.clone.log)

**Comment by wiiaboo** [comment]
Works for me. Problem is probably on your network.

**Comment by ThomasN24** [comment]
I am deactivating my proxy, now it is running. Maybe this was the reason
