### ISSUE TITLE
ERROR: srt >= 1.2.0 not found using pkg-config

### ISSUE THREAD

**Issue by schmidthubert** [jb-alvarado/media-autobuild_suite#785]
Since the `--enable-libsrt` switch [is official now](https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/a2fc8dbae85339d1b418d296f2982b6c04c53c57) I have removed `do_removeOption FFMPEG_OPTS "--enable-libsrt"` from line 1374 but now I'm getting the error in the subject. Also there's a haisrt.pc and srt.pc in the pkgconfig-dir and they're 100% identical? Checking the pc's version(s) it is 1.2.3 and the include(s) and libsrt.a are all in place so what gives? 

Thanks!

**Comment by wiiaboo** [comment]
Logs, please.

**Comment by schmidthubert** [comment]
That's looking good (please fix the 's' though, see patch comment), thank you! :+1:
