### ISSUE TITLE
--enable-libvmaf is not used in second build

### ISSUE THREAD

**Issue by enctac** [jb-alvarado/media-autobuild_suite#787]
I am using --enable-libvmaf in ffmpeg_options.txt.
In the first build, --enable-libvmaf works fine.
However, in the second build, --enable-libvmaf is not used in configure of ffmpeg.
You probably need to modify media-suite_compile.sh.

**Comment by schmidthubert** [comment]
Yeah, I've found the same a while back. Sometimes it was in and sometimes out when checking with -buildconf param. I've changed my script from 

`if [[ $ffmpeg != "no" && $bits = 64bit ]] && enabled libvmaf &&`
to
`if [[ $ffmpeg != "no" ]] && [[ $bits = 64bit ]] && enabled libvmaf &&`

I'm not sure why this would be different, but "it works for me" so anyways. :+1: 
This is currently at line 1288 in media-suite_compile.sh, so try that and see if it works for you as well.

**Comment by schmidthubert** [comment]
I've changed my script now to:

`if [[ $bits = 32bit ]]; then`
`    do_removeOption --enable-libvmaf`
`else`
`    _check=(libvmaf.{a,h,pc})`
`    if [[ $ffmpeg != "no" ]] && enabled libvmaf &&`
`    do_vcs "https://github.com/Netflix/vmaf.git"; then`
`      do_uninstall share/model "${_check[@]}"`
`      log clean make clean`
`      do_make INSTALL_PREFIX="$LOCALDESTDIR"`
`      do_makeinstall INSTALL_PREFIX="$LOCALDESTDIR"`
`      do_checkIfExist`
`    fi`
`fi`

which I like even better. :+1:

**Comment by wiiaboo** [comment]
No idea.

> if [[ $ffmpeg != "no" && $bits = 64bit ]] && enabled libvmaf &&
to
if [[ $ffmpeg != "no" ]] && [[ $bits = 64bit ]] && enabled libvmaf &&

That should give the exact same results, unless there's something seriously wrong with bash.
Same thing with your second post with a nested if for some reason.

**Comment by enctac** [comment]
Reference: libvmaf 32bit compile failed -> #713

Current code:
```
_check=(libvmaf.{a,h,pc})
if [[ $ffmpeg != "no" && $bits = 64bit ]] && enabled libvmaf &&
    do_vcs "https://github.com/Netflix/vmaf.git"; then
    do_uninstall share/model "${_check[@]}"
    log clean make clean
    do_make INSTALL_PREFIX="$LOCALDESTDIR"
    do_makeinstall INSTALL_PREFIX="$LOCALDESTDIR"
    do_checkIfExist
else
    do_removeOption --enable-libvmaf
fi
```
Remove --enable-libvmaf, when do_vcs is "Up-to-date".
This is the cause of the problem.
<br>

Suggestion:
```
_check=(libvmaf.{a,h,pc})
if [[ $bits = 32bit ]]; then
    do_removeOption --enable-libvmaf
elif [[ $ffmpeg != "no" ]] && enabled libvmaf &&
    do_vcs "https://github.com/Netflix/vmaf.git"; then
    do_uninstall share/model "${_check[@]}"
    log clean make clean
    do_make INSTALL_PREFIX="$LOCALDESTDIR"
    do_makeinstall INSTALL_PREFIX="$LOCALDESTDIR"
    do_checkIfExist
fi
```

**Comment by schmidthubert** [comment]
Then probably the smallest change to the current code is just to move the "; then" before the do_vcs:
`if [[ $ffmpeg != "no" && $bits = 64bit ]] && enabled libvmaf; then`
`do_vcs ...`
and that should be all. But let Ricardo decide :+1:

**Comment by chhe** [comment]
The issue is --enable-libvmaf gets removed if there are no VCS changes. It
should only be removed if $bits is 32bit.

**Comment by enctac** [comment]
I made a comment and a suggestion to #788.
