### ISSUE TITLE
AOM won't compile

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#791]
I've set AOM to compile in 'media-autobuild_suite.ini', aom=1 but nothing related to it happens after running 'media-autobuild_suite.bat'. The other encoders compiles just fine but not AOM. Any suggestions what this can be due.
[build.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1868077/build.zip)

**Comment by wiiaboo** [comment]
That option has been removed. It's only with --enable-libaom in ffmpeg_options.txt now and standalone=1 for the aom binaries.

**Comment by Barough** [comment]
That kinda sux. It is what it is.

**Comment by LigH-de** [comment]
Probably consistency.

Before, as long as there was no "release" state, AOM was not supported as ffmpeg module and had to be handled separately (only as separate encoder/decoder binaries).

Now, after AOM being released and libaom being supported as ffmpeg module, it can be handled like all other similar codecs (primarily as ffmpeg module, and optionally as additional encoder/decoder binaries).

**Comment by wiiaboo** [comment]
I can readd the option, if it's of interest to compile FFmpeg without libaom.

**Comment by LigH-de** [comment]
Because AOM apparently has no private CLI option parser API for ffmpeg (in contrast to x264/x265), this may be useful for people who want to test options ffmpeg may not expose, only aomenc.

**Comment by wiiaboo** [comment]
Done.

**Comment by Barough** [comment]
Thnx a lot for putting AOM back again. :)
