### ISSUE TITLE
msys2 standalone project?

### ISSUE THREAD

**Issue by Aidolii** [jb-alvarado/media-autobuild_suite#792]
I was curious if you'd be willing to provide a general-purpose version of your batch script simply for installing and maintaining msys2 without doing any of the ffmpeg stuff. Right now I accomplish this by making a copy and just by closing the window right after it finishes updating pac-man packages.

I very much like portable installations like this, they're very convenient.

**Comment by schmidthubert** [comment]
???
There's several shortcuts in your msys64 directory? Try to run them???

**Comment by Aidolii** [comment]
I am aware you CAN use it in this manner @schmidthubert, as I said I'm already doing that. It'd just be nice if there were a more general-purpose version of the script meant just for setting up the msys2 environment. An example of a difference would be running /usr/bin/mandb --quiet during setup.

**Comment by schmidthubert** [comment]
Ask [Alexpux](https://github.com/Alexpux) ??

**Comment by wiiaboo** [comment]
Setting up msys2 is just using their installer?? What's the need for scripts?

**Comment by Aidolii** [comment]
Their installer, well, installs. It's not portable.

**Comment by wiiaboo** [comment]
Then don't use the installer, extract the archive as the suite does.
There's no extra setup needed. You update it yourself later with `pacman -Syu`.
This isn't a place to ask for questions not directly related to the suite, btw, I'm not available for hand-holding.
