### ISSUE TITLE
Tesseract uses outdated dictionaires

### ISSUE THREAD

**Issue by mkver** [jb-alvarado/media-autobuild_suite#794]
When one enables tesseract (whether standalone or in ffmpeg) one gets tesseract 4.0 beta (in my case tesseract 4.0.0-beta.1-69-g10f4); but the automatically downloaded trained data for English are for version 3.04/3.05 and don't work with the version that is actually compiled (one gets the error message "read_params_file: parameter not found: enable_new_segsearch" when one of the versions is used with the old trained data), but work with the [new trained data](https://github.com/tesseract-ocr/tessdata).
And the link in the file need_more_languages.txt doesn't work anymore.

**Comment by wiiaboo** [comment]
I've never actually used that, so you're welcome to PR an update to that.

**Comment by wiiaboo** [comment]
I will only refuse git cloning that tessdata repo. That's huge, contains only data, a ridiculous idea all round._

Also, I don't understand what you mean by the link not working. It's still the same here: https://github.com/tesseract-ocr/tessdata

**Comment by wiiaboo** [comment]
Fixed. Also, you could notify https://github.com/Alexpux/MINGW-packages that they could update the langdata to 4.00 or something.
