### ISSUE TITLE
mediainfo.exe report libbrotlidec.dll missed

### ISSUE THREAD

**Issue by atomsfear** [jb-alvarado/media-autobuild_suite#796]
![default](https://user-images.githubusercontent.com/34787114/38416783-7307c164-39c8-11e8-9b10-2585cfd42d30.png)

Former version could run without extra dll.
And I can't find libbrotlidec.dll in the directory.

Thank you.

**Comment by wiiaboo** [comment]
You need to force recompilation of curl, since mediainfo depends on it.
