### ISSUE TITLE
libmpv .dll .lib

### ISSUE THREAD

**Issue by krylovgeorgii** [jb-alvarado/media-autobuild_suite#799]
Нow to generate libmpv.dll и libmpv.lib?
(I need to use it in my project in Visual Studio)
libmpv-shared generate only libmpv.dll.a

**Comment by wiiaboo** [comment]
No idea. Ask in mpv.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#linking-libmpv-with-msvc-programs
