### ISSUE TITLE
Debug symbols for libmpv

### ISSUE THREAD

**Issue by leavittx** [jb-alvarado/media-autobuild_suite#801]
Hi. Is there a possiblity to build libmpv/mpv with debug symbols included? (likely in DWARF format)
There is this line of code in the `media-suite_compile.sh`, but I don't get what it does exactly:
`! mpv_disabled debug-build &&
            create_debug_link "$LOCALDESTDIR"/bin-video/mpv{.exe,-1.dll}`
Thanks

**Comment by wiiaboo** [comment]
Just comment the line `--disable-debug-build` in mpv_options.txt and it should compile debug symbols.

**Comment by leavittx** [comment]
No additional files seem to appear, are the debug symbols getting included to the mpv-1.{dll,exe} files?

**Comment by wiiaboo** [comment]
No. There should be .debug files along with both with the debug link. I haven't used that in a while, so I'm not sure if it's working properly. Probably not, it seems.

**Comment by wiiaboo** [comment]
Right, I forgot to remove something in helper.sh that's adding --disabled-debug-build on its own if it's not explicitely enabled.
Instead of commenting the line, change it to --enable-debug-build and it should work.
