### ISSUE TITLE
fribidi/meson confused about sub-directory hierarchy

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#806]
To refresh all the tools to be built, I wiped the bin-global, bin-audio, bin-video, and lib directories below local32 and local64.

Compiling fribidi gave me a curious error in the meson step:

```
├ Running meson...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
meson .. --default-library=static --prefix=/local32 --bindir=/local32/bin-video -Ddocs=false -Dglib=false

ERROR: The value of the 'bindir' option is 'H:/development/media-autobuild_suite-master/local32/bin-video' which must be a subdir of the prefix 'H:/development/media-autobuild_suite-master/local32'.
Note that if you pass a relative path, it is assumed to be a subdir of prefix.
```

Actually, the directory hierarchy looks fine to me?!

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1910108/logs.zip)

**Comment by wiiaboo** [comment]
Try changing bindir to just "bin-video"?

**Comment by LigH-de** [comment]
Yes, this makes fribidi pass. I have no experience in making a diff, but in pseudo-syntax:

Line 177 in build/media-suite_compile.sh
```
-        extracommands=(--bindir="$LOCALDESTDIR/bin-video" -Ddocs=false -Dglib=false)
+        extracommands=(--bindir="bin-video" -Ddocs=false -Dglib=false)
```
