### ISSUE TITLE
mpv binary size exploded

### ISSUE THREAD

**Issue by aufkrawall** [jb-alvarado/media-autobuild_suite#809]
It's now ~150MB without compression, while it was ~45MB a few weeks back. I already tried explicitly disabling some optional ffmpeg and mpv deps, but no avail.
I'm compiling as GPL 2 with GnuTLS.

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/6016730644b1f4b17e94b87e65c9a2cf0e00164d
