### ISSUE TITLE
Build of opus-1.1 failed

### ISSUE THREAD

**Issue by m-audio91** [jb-alvarado/media-autobuild_suite#81]
Hello,

After a fresh install of latest script, now opus is failing to build,
Content of config.log inside opus dir can be found here:
http://pastebin.com/YD9csUDw
Thanks.
And the error message is:

-------------------------------------------------
bin-fdk-aac is already up to date
-------------------------------------------------
Package opus was not found in the pkg-config search path.
Perhaps you should add the directory containing `opus.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opus' found
--2015-04-14 17:30:19--  http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz
Resolving downloads.xiph.org (downloads.xiph.org)... 140.211.166.134
Connecting to downloads.xiph.org (downloads.xiph.org)|140.211.166.134|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 850208 (830K) [application/x-gzip]
Saving to: ‘opus-1.1.tar.gz’

opus-1.1.tar.gz               100%[===================================================>] 830.28K  --.-KB/s   in 0.01s

2015-04-14 17:30:57 (62.4 MB/s) - ‘opus-1.1.tar.gz’ saved [850208/850208]

--2015-04-14 17:30:59--  https://raw.github.com/jb-alvarado/media-autobuild_suite/master/patches/opus11.patch
Resolving raw.github.com (raw.github.com)... 199.27.75.133, 199.27.78.133
Connecting to raw.github.com (raw.github.com)|199.27.75.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/jb-alvarado/media-autobuild_suite/master/patches/opus11.patch [following]
--2015-04-14 17:31:04--  https://raw.githubusercontent.com/jb-alvarado/media-autobuild_suite/master/patches/opus11.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.43.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.43.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 502 [text/plain]
Saving to: ‘opus11.patch’

opus11.patch                  100%[===================================================>]     502  --.-KB/s   in 0s

2015-04-14 17:31:10 (1.61 MB/s) - ‘opus11.patch’ saved [502/502]

patching file ./include/opus_defines.h
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking how to print strings... printf
checking for style of include used by make... GNU
checking for i686-w64-mingw32-gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... configure: error: in `/build/opus-1.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for 'install'.
-------------------------------------------------
Build of opus-1.1 failed...
Delete the source folder under '/build' and start again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

**Comment by wiiaboo** [comment]
Probably not related to the problem, but any reason you're using mingw32 instead of mingw64?

**Comment by wiiaboo** [comment]
I had no trouble compiling opus here with mingw32 to 32-bit, so I'd recommend just deleting the whole media-autobuild_suite and downloading a fresh copy.

**Comment by m-audio91** [comment]
"Probably not related to the problem, but any reason you're using mingw32 instead of mingw64?"

I think probably it's because of arch=2 right?
[compiler list]
msys2Arch=2
arch=2
free=1
ffmbc=2
x264=2
x265=2
other265=2
ffmpegB=1
ffmpegUpdate=1
mp4box=2
mplayer=2
mpv=2
mkv=2
cores=2
deleteSource=1
strip=1
pack=1

any chance to not delete /build and /local32 folder?(cause it took ages to download!)

**Comment by wiiaboo** [comment]
Maybe I read something wrong.
But anyway, you should only need to delete local32 and mingw32 or mingw64 whichever appropriate. It will download the toolchain again and build every package but sources won't need to be downloaded again.
