### ISSUE TITLE
got terribly slow,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#812]
Did anything change during the last 10 days which could explain why the script now takes more than 48 hours to finish?
I event checked it out to another sdd to make sure it wasn't caused by the drive I used.
-> Just want to make sure whether this might be caused by some change or whether I should look for another cause. (Even compiling something like fdk-aac takes multiple hours,..)

**Comment by Selur** [comment]
just the compilation of fdk-aac-git took 1 1/2 hours.
One thing I notice is that since starting the CPU handles reported by the Windows Task-Manager climbed from ~60k before starting the script to now 150k and it's still climbing,..

**Comment by pat357** [comment]
Has it been running faster on your Ryzen 7 system before ?
fdk-aac should take no more then a couple of minutes to compile, I guess max 5 minites on my i7-970 
(= 8 years old CPU with 6/12 cores/threads)

**Comment by wiiaboo** [comment]
No idea. Most likely it's on MSYS/MinGW, not the suite.

**Comment by Selur** [comment]
Yes, it was faster before on my Ryzen 7. 
@wiiaboo: Thanks, just wanted to know whether I overlooked something in the change logs.
