### ISSUE TITLE
Feature request: add times to output

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#814]
Would be nice to have times at the start&end of the steps to easier spot when the script simply hangs.

**Comment by 1480c1** [comment]
Do you mean in the compile script or just in general including pacman installation etc?

**Comment by Selur** [comment]
during the compiling to see the start and end time and thus be able to better know whether a compiling step is hung for x hours or just started.

**Comment by 1480c1** [comment]
```
┌ tesseract git .................................... 10:10:09[Recently updated]
├ Running autogen...10:10:09
├ Running configure...10:10:34
├ Running make...10:10:34
├ Running install...10:10:32
├ Stripping...10:10:38
└ tesseract-git .............................................10:10:38 [Updated]
```
Do you mean something like this?

**Comment by 1480c1** [comment]
Those are the start times, aka when the message was typed to console

**Comment by Selur** [comment]
Thanks that, end times would be nice too, but I'm happy even if there are only start times. :)

**Comment by 1480c1** [comment]
You could consider the start times of the next line to be the end time as if the command ended, the next command will start right after.

**Comment by wiiaboo** [comment]
I'd assumed he wanted like

```
10:10:38.123:┌ tesseract git .................................... [Recently updated]
10:10:38.123:├ Running autogen...
10:10:38.123:├ Running configure...
10:10:38.123:├ Running make...
10:10:38.123:├ Running install...
10:10:38.123:├ Stripping...
10:10:38.123:└ tesseract-git ............................................. [Updated]
```

**Comment by 1480c1** [comment]
I see, that's probably better, was testing how the printf works

**Comment by Selur** [comment]
I have no real preference where the time data is present (start, middle, end of line). :)

**Comment by 1480c1** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/pull/1052
Is this okay?

**Comment by wiiaboo** [comment]
I originally ignored this because I thought it needed to be the times since the start of the suite, not the absolute time.

**Comment by 1480c1** [comment]
Is this considered done?

**Comment by wiiaboo** [comment]
Yeah. You can add the issue number in the commit message along with "Fix" or "Close" before to auto-close the issue when it's merged.

**Comment by 1480c1** [comment]
I see, that's good to know.
