### ISSUE TITLE
mpv link need psapi

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#815]
add -lpsapi to media-suite_compile.sh

 mpv_ldflags=("-L$LOCALDESTDIR/lib" "-L$MINGW_PREFIX/lib" "-lpsapi")

**Comment by wiiaboo** [comment]
No. If that's something needed in mpv without external libs you ask mpv themselves that they need it, you don't add it to the script even when it's not needed.
