### ISSUE TITLE
Please add more configuration options

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#816]
I wanted to only build aom and thus used:
```
[compiler list]
msys2Arch=2
arch=1
license2=1
standalone=1
vpx2=2
aom=1
x2643=2
x2652=2
other265=2
flac=2
fdkaac=2
faac=2
mediainfo=2
soxB=2
ffmpegB2=2
ffmpegUpdate=2
ffmpegChoice=2
mp4box=2
rtmpdump=2
mplayer2=2
mpv=2
bmx=2
curl=2
ffmbc=2
cyanrip=2
redshift=2
cores=4
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=1
```
the script build tons of audio tools I had no interest in.
Would be nice if the script your give a better choice in what to build.

**Comment by wiiaboo** [comment]
You could help by saying which audio tools are getting compiled.

**Comment by wiiaboo** [comment]
Also, I'm definitely not adding options for every single standalone tool being built.

**Comment by Selur** [comment]
> Also, I'm definitely not adding options for every single standalone tool being built.

Why not?
At least adding options for it inside the media-autobuild_suite.ini file which one could edit manually and adding if/then entries inside the media-suite_compile.sh shouldn't be much work.

audio tool build are:
> opus git
> opusfile git
> libopusenc git
> opus-tools git
> lame 3.100
