### ISSUE TITLE
libbrotlidec.dll was not found

### ISSUE THREAD

**Issue by rld243** [jb-alvarado/media-autobuild_suite#818]
Made a full clean install and noticed that both curl and mediainfo stopped working:

![curl](https://user-images.githubusercontent.com/34302354/39083497-4d934db0-4597-11e8-9a02-2873800fa145.png)

Tried to force recompile with no success. There were no errors during compiling so I can't attach logs.zip
I guess 97484bb was supposed to fix this but the error still persists.

**Comment by wiiaboo** [comment]
Check/Paste the contents of msys64/mingw64/lib/pkgconfig/libbrotlicommon.pc

**Comment by rld243** [comment]
```
prefix=/mingw64
exec_prefix=/mingw64
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libbrotlicommon
URL: https://github.com/google/brotli
Description: Brotli common dictionary library
Version: 1.0.3
Libs: -L${libdir} -lbrotlicommon-static
Cflags: -I${includedir}

```

**Comment by wiiaboo** [comment]
And the other brotli .pc files?

**Comment by rld243** [comment]
libbrotlidec.pc
```
prefix=/mingw64
exec_prefix=/mingw64
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libbrotlidec
URL: https://github.com/google/brotli
Description: Brotli decoder library
Version: 1.0.3
Libs: -L${libdir} -lbrotlidec-static
Requires.private: libbrotlicommon >= 1.0.2
Cflags: -I${includedir}

```
libbrotlienc.pc
```
prefix=/mingw64
exec_prefix=/mingw64
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libbrotlienc
URL: https://github.com/google/brotli
Description: Brotli encoder library
Version: 1.0.3
Libs: -L${libdir} -lbrotlienc-static
Requires.private: libbrotlicommon >= 1.0.2
Cflags: -I${includedir}

```

**Comment by Selur** [comment]
Build mediainfo yesterday and got the same message and now I get:

> The code execution cannot proceed because libbrotlidec.dll was not found. Reinstalling the program may fix this problem. 

when calling mediainfo,  isn't the library statically build into mediainfo?

**Comment by Selur** [comment]
hoping deleting the curl-git will help,..
