### ISSUE TITLE
libaacs error

### ISSUE THREAD

**Issue by Felixkruemel** [jb-alvarado/media-autobuild_suite#819]
libaacs failes while doing make

See the log here:
https://0x0.st/sSDU.zip

**Comment by wiiaboo** [comment]
Can't reproduce, did you try more than once?

**Comment by Felixkruemel** [comment]
Yes. Already the thrid try. I could try to start with a fresh folder but this could take some time. Maybe there's something wrong with already existing files.

**Comment by wiiaboo** [comment]
libgcrypt is always required. But it shouldn't be looking for it just in local64 since we never build it.
