### ISSUE TITLE
Add more options to INI

### ISSUE THREAD

**Issue by wiiaboo** [jb-alvarado/media-autobuild_suite#82]
Placeholder issue to add options to standalone apps and ffmpeg external libraries since this will probably take a while.

Optional apps:
- [x] mediainfo
- [x] sox

Optional apps to add option to build static, libs only or not at all:
- [x] vpx
- [x] x264
- [x] x265

Optional ffmpeg external libraries (optional to choose so as not to overwhelm users)
- [x] bs2b
- [x] caca
- [x] dcadec
- [x] decklink
- [x] dirac (schroedinger)
- [x] dvdread/dvdnav/libbluray
- [x] flac (app, lib or no)
- [x] fdkaac (app, lib or no)
- [x] frei0r
- [x] gme
- [x] gsm
- [x] ilbc
- [x] modplug
- [x] nvenc
- [x] opencore-amr
- [x] openjpeg (app, lib or no) <- ffmpeg has native encoder/decoder
- [x] opus (app, lib or no)
- [x] rtmp (app, lib or no)
- [x] sdl (ffplay needs it so disable if no)
- [x] soxr
- [x] speex (app, lib or no) <- needed for encoding and decoding
- [x] theora <- needed for encoding
- [x] twolame (app, lib or no)
- [x] utvideo <- libutvideo has worse performance than native utvideo
- [x] vidstab
- [x] vo-aacenc <- low quality encoder
- [x] xavs
- [x] zvbi

A few of these can be removed if they aren't compiled by us and don't take much space on the binary.

**Comment by jb-alvarado** [comment]
When this is only in the ini, it is fine for me - I think this is very useful for some people!

**Comment by wiiaboo** [comment]
Safest option for ffmpeg libs would be a separate INI, so if we add any libs we just delete that one instead of the main one.

What do you think?

Something like adding a single option to main INI that selects whether you want to choose ffmpeg's external libs and then we read from ffmpeg.ini and go from there.

**Comment by jb-alvarado** [comment]
I think I like it a bit more to have everything in one ini. We can make there also a new section `[ffmpeg]`.

When msys2 is set up we can also use the tools from there in the batchfile, like sed, grep, awk. I make it much more easy to work with text files.

At the moment the source code folders get also delete, when it comes from 32bit to 64bit. I think we can also change this and we use the existing ones. Almost all have already a distclean, so it must be possible.

**Comment by wiiaboo** [comment]
>I think I like it a bit more to have everything in one ini. We can make there also a new section [ffmpeg].

>When msys2 is set up we can also use the tools from there in the batchfile, like sed, grep, awk. It make it much more easy to work with text files.

Then make something that edits the ini, because if everytime one single option is missing we have to choose between 30 choices it's kind of a pain. Move ffmpeg lib choices to something that runs after media-suite_update.sh then.

>At the moment the source code folders get also delete, when it comes from 32bit to 64bit. I think we can also change this and we use the existing ones. Almost all have already a distclean, so it must be possible. 

What do you mean? They only get deleted after both 32-bit and 64-bit are built succesfully without errors. And after you added clean to wxwidgets I think all of them have "make clean". Only faac and ffmbc are missing.

**Comment by jb-alvarado** [comment]
Ah ok, you really want that it is possible to choose every ffmpeg lib, by running first time the batch file? I though we only expose this option in the ini. Yes in that way is better to have a separate ini file.

My first run of the script was breaking after the 32 bit compiling was done. I think I have edit something in the shell script, so the breaking was normal. But now since I run it again, it download the source for the 64bit compiling new, not the git/hg/svn folders, but the others.

**Comment by wiiaboo** [comment]
I'm thinking then of doing all choices other than toolchain and arch to either `media-suite_update.sh` (since it's always run) or one more separate .sh. I agree *nix tools are much easier and better to use than tools available in Windows.

But this will probably take me a week or so. The optional apps PR could probably be merged while I work on ffmpeg's libs, since that will take some time.

**Comment by jb-alvarado** [comment]
Ok, then we can do it like this:
By running the first time the batch file, it comes a question block with the question: `do you want more options for choosing external libs for ffmpeg? The questions will come when the compiling script starts to run.`
Then the `media-suite_update.sh` starts and here comes the questions, and the answers will write to the ffmpeg.ini.

Is that good for you?

I only think, that maybe than is better to put vpx/x264/x265 also to the questions in the `media-suite_update.sh` file. That are almost standard libs in ffmpeg.

**Comment by jb-alvarado** [comment]
Ah and the Information in the question block from the batch file needs also the information that, when you choose no all possible libs will integrated in ffmpeg :).

**Comment by wiiaboo** [comment]
Yes, that was what I was planning.

Like:

1. open .bat
2. choose toolchain mingw32 or mingw64
3. choose arch 32-bit, 64-bit or both
  * delete `media-autobuild_suite.ini` if any of these two options are missing
4. do everything else the .bat does until `media-suite_update.sh`
5. start questions there
6. start from "choose non-free binaries" until question named "choose ffmpeg optional libraries?"
  1. if yes start another series of options that get written to `media-autobuild_suite.ffmpeg.ini`
  2. if not, set every ffmpeg lib to "yes" and write them to `media-autobuild_suite.ffmpeg.ini`
7. after `media-suite_update.sh` finishes running, read every option from both INI files and use the choices to run `media-autobuild_compile.sh`

Content of `media-autobuild_suite.ini`:
```
[compiler list]
msys2Arch=2
arch=3
```
Content of `media-autobuild_suite.ffmpeg.ini`:
```
[apps]
free=1
ffmbc=2
vpx=2
x264=2
x265=2
other265=2
mediainfo=2
ffmpegB=1
ffmpegUpdate=2
ffmpegOpt=1
mp4box=2
mplayer=2
mpv=1
mkv=2
cores=2
deleteSource=1
strip=1
pack=1

[ffmpeg libs]
openjpeg=2
amr=2
xavs=2
ilbc=2
twolame=2
...
```

**Comment by jb-alvarado** [comment]
Yeah sounds good! I only think it is better to put only the related stuff from ffmpeg to the ffmpeg.ini mediainfo, mpv and the other match better in the batch file, I think. The nonfree option can go to the ffmpeg.ini to.

**Comment by wiiaboo** [comment]
The reason I was leaving everything in ffmpeg.ini was so we could avoid having to read the two .ini files after writing them. I'll think of which is better later. Will be busy the next few days with other stuff.

**Comment by jb-alvarado** [comment]
Ok, no stress.

**Comment by wiiaboo** [comment]
I was thinking there were two ways we could use for options.

1. Make choices using `update.sh` and save to `/etc/ffmpeg-options.conf` which then we `source` in `compile.sh`
    - Pros: 
        - keeps root tidier
        - can be easily `source`'d by `compile.sh`
        - avoids having to read every option using the .bat and then sending each option to the start command (easier to extend to future additional options)
    - Cons:
        - harder to find to delete or edit
    - Using this, to add one optional component we just have to add the choice to `update.sh` and one `if` in `compile.sh`

2. Make choices using `update.sh` and save to `ffmpeg.ini` in root
    - To read the choices we have to add another `for /F "tokens=2 delims==" %%f in ('findstr /i "opt" %ini%') do set optINI=%%f`, another argument to start command, another arg reader at the beginning of `compile.sh` and the `if` for the component

I'm partial to the first, but we'd probably have to reset the file if someone deleted the original `media-autobuild_suite.ini` so the behavior would be the same.
We could also have `compile.sh` always copy to /etc a `ffmpeg-options.conf` that stays in root so people could edit/delete it easily. I think this would be a good compromise.

**Comment by jb-alvarado** [comment]
Another contra from the first option is, that we need to take care of it, when the msys* folder get deleted. I do this some time, to build the compiler environment new, but hold the libs.

**Comment by jb-alvarado** [comment]
We also can put ffmpeg-options.conf in the build folder, or in the root.

**Comment by wiiaboo** [comment]
Is that easily source'd by compile.sh?

**Comment by jb-alvarado** [comment]
What do you mean?

I am ok with your first option, I only don't like it so much to put it in the etc folder. And it want be good when it is good readable, for people how have not much knowledge.

We also can put in general the most files in the build folder, and have only the batch file and the shortcut in the root. Maybe like:

build
    sources
    include
    patches
    *.sh
    *.ini
    *.conf

**Comment by wiiaboo** [comment]
Oh, I get it. Yeah, that be a good idea too. Cleaning up the root and leaving with the most important files. Even so far as to allow people to just download the .bat and downloading by itself the most recent compile.sh and update.sh would be cool.

**Comment by jb-alvarado** [comment]
This with the downloading the recent files I had at the very begin. When you take a look in v1 you found it in the bat file :).

**Comment by wiiaboo** [comment]
I still haven't done anything on this because I was sorta disappointed that ffmpeg didn't get much smaller without the optional libs. Guess most of the bulk is internal decoders and encoders.

Also, still not sure how is the best way of making most of the components optional, either reading from a file with ffmpeg options like `--enable-libfdk-aac --enable-nvenc` that you edit and remove those you don't want and then compile accordingly or explicit options on the first time running like the others.

**Comment by jb-alvarado** [comment]
Ah, I almost forget that topic :). Yeah is not so easy. And it only makes really sense, I guess, when this affects also the compiling process from the libs itself. Otherwise there is not a time save.

**Comment by wiiaboo** [comment]
Yeah, it's mostly because of those libs compilation taking time and creating bugs, like utvideo did and the standalone apps not being needed (like caca, twolame, speex, openjpeg)

**Comment by wiiaboo** [comment]
All done!
