### ISSUE TITLE
Error when compile ffmpeg by manual

### ISSUE THREAD

**Issue by manhcuongbbbk** [jb-alvarado/media-autobuild_suite#821]
bharfbuzz_la-hb-graphite2.o):(.text+0x632): undefined reference to `gr_seg_n_slo                                                                                                                                                 ts'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x64c): undefined reference to `gr_featureva                                                                                                                                                 l_destroy'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x657): undefined reference to `gr_seg_destr                                                                                                                                                 oy'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x711): undefined reference to `gr_featureva                                                                                                                                                 l_destroy'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x71c): undefined reference to `gr_seg_destr                                                                                                                                                 oy'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x862): undefined reference to `gr_seg_first                                                                                                                                                 _slot'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x86a): undefined reference to `gr_slot_orig                                                                                                                                                 in_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x884): undefined reference to `gr_seg_advan                                                                                                                                                 ce_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x8a2): undefined reference to `gr_seg_first                                                                                                                                                 _slot'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x8c1): undefined reference to `gr_slot_befo                                                                                                                                                 re'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x8cf): undefined reference to `gr_slot_afte                                                                                                                                                 r'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x8e0): undefined reference to `gr_slot_gid'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x9fc): undefined reference to `gr_slot_can_                                                                                                                                                 insert_before'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xb20): undefined reference to `gr_slot_orig                                                                                                                                                 in_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xb46): undefined reference to `gr_slot_orig                                                                                                                                                 in_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xb86): undefined reference to `gr_slot_orig                                                                                                                                                 in_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xc2f): undefined reference to `gr_slot_next                                                                                                                                                 _in_segment'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xc85): undefined reference to `gr_seg_advan                                                                                                                                                 ce_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xee4): undefined reference to `gr_seg_first                                                                                                                                                 _slot'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xefc): undefined reference to `gr_slot_orig                                                                                                                                                 in_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0xf44): undefined reference to `gr_slot_orig                                                                                                                                                 in_Y'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1008): undefined reference to `gr_slot_adv                                                                                                                                                 ance_Y'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x106f): undefined reference to `gr_slot_nex                                                                                                                                                 t_in_segment'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1082): undefined reference to `gr_seg_adva                                                                                                                                                 nce_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1098): undefined reference to `gr_seg_firs                                                                                                                                                 t_slot'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1142): undefined reference to `gr_slot_adv                                                                                                                                                 ance_Y'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x11a1): undefined reference to `gr_slot_ori                                                                                                                                                 gin_X'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1210): undefined reference to `gr_slot_ori                                                                                                                                                 gin_Y'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1260): undefined reference to `gr_slot_nex                                                                                                                                                 t_in_segment'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x1284): undefined reference to `gr_featurev                                                                                                                                                 al_destroy'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libharfbuzz.a(li                                                                                                                                                 bharfbuzz_la-hb-graphite2.o):(.text+0x128f): undefined reference to `gr_seg_dest                                                                                                                                                 roy'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x13b): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x181): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x200): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x221): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x275): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x28f): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x309): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x36a): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0xb30): undefined reference to `libintl_setlocale'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0xbda): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x2101): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x23aa): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x2ba6): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x2c9c): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x2cc8): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x2ce3): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x2cf8): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x41ad): undefined reference to `libintl_dgettext'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccfg.o):(.text+0x4210): undefined reference to `libintl_dgettext'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccharset.o):(.text+0x3e3): undefined reference to `libintl_snprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccharset.o):(.text+0x1a0d): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x17): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x28): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x38): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x48): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0xa6): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x1e2): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x2eb): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x374): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x3db): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x4c3): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x508): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x5e7): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x611): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x637): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x212): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x231): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x24e): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x26b): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x289): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x2ba): more undefined references to `libintl_fprintf' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x5b0): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x64e): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x661): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x9bd): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x9ce): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcdbg.o):(.text+0x9df): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcinit.o):(.text+0x1d8): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcinit.o):(.text+0x20b): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcinit.o):(.text+0x22c): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcinit.o):(.text+0x279): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcinit.o):(.text+0x2b3): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0x344): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0x47f): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0x4a0): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0x536): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0x5a9): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0x627): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0xb40): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fclang.o):(.text+0xb8e): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x1924): undefined reference to `libintl_sprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x2065): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x2088): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x20a1): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x20b1): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x22a0): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcmatch.o):(.text+0x2490): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcname.o):(.text+0x9ba): undefined reference to `libintl_sprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcname.o):(.text+0x9f8): undefined reference to `libintl_sprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcname.o):(.text+0xa9f): undefined reference to `libintl_sprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcname.o):(.text+0xb01): undefined reference to `libintl_sprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcobjs.o):(.text+0x17d): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x1114): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x115a): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x12cf): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x1319): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x2a22): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x2a36): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcpat.o):(.text+0x2a4e): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x262): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x28d): undefined reference to `libintl_vfprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x2a6): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x2e2): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x30f): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x1b49): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x1da8): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fcxml.o):(.text+0x24e5): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0x9ed): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0xab2): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0xbca): more undefined references to `__printf__' follow
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0x237d): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0x23d0): undefined reference to `libintl_fprintf'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0x2411): undefined reference to `__printf__'
C:/Users/CUONGH/media-autobuild_suite-master/msys64/mingw32/lib/libfontconfig.a(                                                                                                                                                 fccache.o):(.text+0x2469): undefined reference to `__printf__'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:107: ffmpeg_g.exe] Error 1

**Comment by wiiaboo** [comment]
I don't know what that title means but the suite never uses mingw fontconfig.
This isn't a compilation for newbies forum.
