### ISSUE TITLE
Build fails at tesseract git

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#825]
[logs.zip] (https://0x0.st/sQfY.zip)

**Comment by wiiaboo** [comment]
tesseract's problem. Someone notify them.

**Comment by schmidthubert** [comment]
fixed now:
https://github.com/tesseract-ocr/tesseract/commit/4f9493c409a0e9842c174c50547a7eb50e07d490#diff-c949f93d03f44a4217d7a138f9e2e54a
