### ISSUE TITLE
Reoccuring problem,...

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#829]
This -> [logs.zip](https://0x0.st/sQRM.zip)
happens from time to time, deleting the ffmpeg folder and rerunning the script then fixes the issue for a few days, but then it happens again,...
No clue whats causing this,

**Comment by Selur** [comment]
just deleted the ffmpeg folder and this time it didn't help same error occurred:  [logs.zip](https://0x0.st/sQRL.zip)

**Comment by wiiaboo** [comment]
Who knows? Never happened to me. Try asking ffmpeg.

**Comment by Selur** [comment]
just wanted to report it, since it keeps reappearing,..

**Comment by GyanD** [comment]
I see this in the ffmpeg make log

```
G:/media-autobuild_suite/build/ffmpeg-git/libavfilter/vf_scale.c: In function 'filter_frame':
G:/media-autobuild_suite/build/ffmpeg-git/libavfilter/vf_scale.c:525:1: internal compiler error: Segmentation fault
 }
 ^

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

G:/media-autobuild_suite/build/ffmpeg-git/libavfilter/vf_scale.c:525:1: internal compiler error: Aborted

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
gcc.exe: internal compiler error: Aborted (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
```

It doesn't happen here. I would suggest reinstalling the suite so that the toolchain is reset.
