### ISSUE TITLE
FFmpeg fails with ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#831]
[logs.zip](https://0x0.st/s1Nx.zip)

**Comment by schmidthubert** [comment]
Don't bother to read the other issues first ...

**Comment by Selur** [comment]
Other issue I saw was about an bool variable issue which didn't happen to me,...

**Comment by schmidthubert** [comment]
Yes it is the same, read the config log in the subdir and not just what see on screen ...
