### ISSUE TITLE
ffmpeg 32bit doesn't build with --enable-vapoursynth if 64bit VapourSynth is installed

### ISSUE THREAD

**Issue by schmidthubert** [jb-alvarado/media-autobuild_suite#833]
And I didn't check the opposite but instead restricted myself to build ffmpeg with vs only in 64bit, line 1346:
`if [[ $bits = 64bit ]] && [[ -n "$vsprefix" ]] &&`

Needs more than that though if properly fixed for 32bit and 64bit because the current code also copies stuff into local32 which then errors when ffmpeg 32bit is building ...

**Comment by wiiaboo** [comment]
Explain better what you do and don't have.
Which flavors of vapoursynth do you have installed?
If only 64-bit, it shouldn't be installing anything to local32 since it shouldn't be finding the vsprefix in 32-bit registry.

**Comment by schmidthubert** [comment]
That's what I was expecting but not so. I'm ALWAYS compiling ffmpeg for both 32bit and 64bit. My VapourSynth is 64bit. If I open a MSYS2/mingw32.exe then this is my output:
`me@host /trunk`
`$ cd build`
`me@host /trunk/build`
`$ source ./media-suite_helper.sh`
`me@host /trunk/build`
`$ get_vs_prefix`
`me@host /trunk/build`
`$`

so no vsprefix there as expected. Nevertheless the 32bit ffmpeg build fails with:

`+ vapoursynth git ................................... [Recently updated]`
`+ Stripping...`
`+ vapoursynth-git ............................................ [Updated]`
`Compiling FFmpeg with Vapoursynth R43`
`FFmpeg will need vapoursynth.dll and vsscript.dll to run!`
`  Running git update for ffmpeg...`
`+ ffmpeg git ........................................... [Updates found]`
`+ Changing options to comply to nonfree...`
`+ Compiling static FFmpeg...`
`+ Running uninstall...`
`+ Running configure...`
`Likely error:`
`CFLAGS: ...`
`LDFLAGS: ...`
`ERROR: vapoursynth-script >= 42 not found using pkg-config`

So it is clearly entering the "vs block" currently at line 1346 when it should NOT and then messing things up ...

**Comment by pat357** [comment]
I've both Vapoursynth 32bit and 64 bit installed on default location.
For 32bit compile, the variable $vsprefix comes out empty.

I think I found the reason
```
patrick@Win7 /trunk
$ cygpath -u "c:\Program Files (x86)\VapourSynth\core64\"
> ^C
patrick@Win7 /trunk
$ cygpath -u 'c:\Program Files (x86)\VapourSynth\core64\'
/c/Program Files (x86)/VapourSynth/core64/
patrick@Win7 /trunk
$ cygpath -sm "c:\Program Files (x86)\VapourSynth\core64\"
>
> ^C
patrick@Win7 /trunk
$ cygpath -sm 'c:\Program Files (x86)\VapourSynth\core64\'
C:/PROGRA~2/VapourSynth/core64/
patrick@Win7 /trunk
$ cygpath -u "C:/PROGRA~2/VapourSynth/core64"
/c/PROGRA~2/VapourSynth/core64
patrick@Win7 /trunk
$
```
As you can see, cygpath -u "path" (double quotes) doesn't work because of the shell.
With single quotes, it works.
With the "short" version, it works both with single and double quotes.

A way around this problem is directly turn the value from the registry in short mode and then process like we do now.
I got it working on my setup for both 32bit and 64bit mode.

**Comment by schmidthubert** [comment]
Thanks! :+1:  But I think this will get even more complicated, especially now that you say you have both installed. I really don't like the 
`# last resort, check if vspipe is in path`
`        vsprefix="$(dirname "$(which vspipe.exe)")"`
part in the helper because just from searching the .exe the vs bitness installed be concluded. The same goes for short `Progra~X` pathes and the numbers therein etc. Even finding the .exe(s) and then extending the path(es) could result in say `C:\VS32\vspipe.exe` and `C:\VS64\vspipe.exe` or worse `C:\Progra~3\vspipe.exe` and `C:\Progra~4\vspipe.exe` and it wouldn't say anything about which bitness which is, even if that's in the path(es) name(s) in the former case. This is getting worse if the embedded version(s) is/are used. Making that work for 32bit and 64bit will be tricky. Something like `file c/path/vspipe.exe` (or something better) needs to be used then to figure out what architecture it is etc.

So if it works for you then congrats! :+1:  For now I'll stick with my 64bit vs since there's a wrapper for avisynth and leave the more complicated cases to Ricardos skills here! :+1:

**Comment by pat357** [comment]
For me, this is what I get for the var vsprefix:

32 bit : /c/PROGRA~2/VapourSynth/core32/
64 bit : /c/PROGRA~2/VapourSynth/core64/

It's still easy to see the bitness and it works like a charm !

I'm gonna test now what exactly ffmpeg can do with this option enabled ; I was hoping it could directly open a VS .vpy  file, but that isn't the case. Maybe it will if I manually specify the demuxer to use ,,, need to test further.

**Comment by schmidthubert** [comment]
This was the addition: https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/7074a7ccd9a4d4e445252780fd182aa0b3778b79

As for embedded python + portable vs: portable vs doesn't contain the core64/core32 subfolders. Instead there are vapoursynth64 and vapoursynth32 subfolders. Just unpacking a portable vs .zipsobviously doesn't do anything to $path or the registry. So that's the task at hand here to work cases like this out. :flushed:

**Comment by pat357** [comment]
The only way to make portable work in full-auto mode would be searching all partitions for the relevant files.
This would be a bit problematic because it would take long and require some extra programming to close all possible holes.  The required effort would outweight the gain ; not worth it IMHO.

**Comment by pat357** [comment]
I created a PR that should fix the always empty vsprefix in 32bit.

**Comment by schmidthubert** [comment]
For me the recent changes are working fine now, no 64bit vs stuff in local32 anymore. Thanks Ricardo! :+1: 

Just something cosmetic, line 1352 and line 1353:
`        do_uninstall {vapoursynth,vsscript}.lib "${_check[@]}"`
`        do_vcs "https://github.com/vapoursynth/vapoursynth.git"`
should be the other way round.

Thanks again! :+1:
