### ISSUE TITLE
'https://i.fsbn.eu/pub/wget-pack.exe' was unexpected at this time.

### ISSUE THREAD

**Issue by chebum** [jb-alvarado/media-autobuild_suite#837]
An error "'https://i.fsbn.eu/pub/wget-pack.exe' was unexpected at this time." appears when building on Windows 10 with the  master version.

The issue can be solved by changing line 1001 to 
`powershell -noprofile -command "[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12';(New-Object System.Net.WebClient).DownloadFile('https://i.fsbn.eu/pub/wget-pack.exe', 'wget-pack.exe')"`
e.g. joining three lines into a single one

**Comment by wiiaboo** [comment]
Weird, it worked fine on actual cmd.exe.

**Comment by mcelhennyi** [comment]
I tired this fix, seems to not work for me. I copied your one liner over 
`    powershell -noprofile -command ^
"[System.Net.ServicePointManager]::SecurityProtocol = 'Tls12';(new-object System.Net.WebClient).DownloadFile('https://i.fsbn.eu/pub/wget-pack.exe', 'wget-pack.exe')"
`

Windows 10, master pulled at 10:30 AM ET: 1ec89c650c451cd274912eb8f6127f31c555364a

When I make your change it says "The syntax of the command is incorrect."

**Comment by mcelhennyi** [comment]
I just manually downloaded and unpacked it like the next couple lines state

**Comment by wiiaboo** [comment]
It's an actual one-liner now, without the '^'.
