### ISSUE TITLE
script freezes on 'scons: Reading SConscript files ...'

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#84]
When I run the current version is simply ideals with 
'scons: Reading SConscript files ...'
right after skipping f265

**Comment by wiiaboo** [comment]
Not sure what's wrong. It works here, but I'll add a "rm -f bin-video/f265-cli.exe" to avoid skipping silently.
Could you paste your .ini file?

**Comment by Selur** [comment]
Here you go:
[compiler list]
msys2Arch=2
arch=1
free=2
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
mp4box=1
mplayer=1
mpv=2
mkv=1
cores=8
deleteSource=1
strip=1
pack=2

**Comment by Selur** [comment]
updated and restarted the script,... didn't help, see: http://pastebin.com/qKHNBJCe

**Comment by wiiaboo** [comment]
I forgot I could just compile 64-bit, since f265 only gets compiled to 64-bit, so I'm still waiting on 32-bit stuff.

Could you delete or rename the old f265cli.exe yourself and try again?

**Comment by Selur** [comment]
There's no f265cli.exe in the local64/bin-video folder

**Comment by wiiaboo** [comment]
I really can't tell what's wrong, it [still works here](https://gist.github.com/wiiaboo/3f9e13765615bcdbb298). How about deleting /build/f265-git/ ?

**Comment by Selur** [comment]
the latest update helps, but now I'm stuck at:

-------------------------------------------------
dvdnav is already up to date
-------------------------------------------------
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12 (delta 10), reused 0 (delta 0)
Unpacking objects: 100% (12/12), done.
From git://git.videolan.org/libbluray
 * branch            master     -> FETCH_HEAD
   f8de9a5..a10b15f  master     -> origin/master
Updating f8de9a5..a10b15f
Fast-forward
 src/libbluray/disc/disc.c       | 88 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/libbluray/disc/disc.h       |  3 +++
 src/libbluray/player_settings.h |  2 +-
 3 files changed, 92 insertions(+), 1 deletion(-)
test -z "libbluray.la" || rm -f libbluray.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf contrib/libudfread/src/.libs contrib/libudfread/src/_libs
rm -rf src/file/.libs src/file/_libs
rm -rf src/libbluray/.libs src/libbluray/_libs
rm -rf src/libbluray/bdj/.libs src/libbluray/bdj/_libs
rm -rf src/libbluray/bdj/native/.libs src/libbluray/bdj/native/_libs
rm -rf src/libbluray/bdnav/.libs src/libbluray/bdnav/_libs
rm -rf src/libbluray/decoders/.libs src/libbluray/decoders/_libs
rm -rf src/libbluray/disc/.libs src/libbluray/disc/_libs
rm -rf src/libbluray/hdmv/.libs src/libbluray/hdmv/_libs
rm -rf src/util/.libs src/util/_libs
rm -f *.o
rm -f contrib/libudfread/src/*.o
rm -f contrib/libudfread/src/*.lo
rm -f src/examples/*.o
rm -f src/file/*.o
rm -f src/file/*.lo
rm -f src/libbluray/*.o
rm -f src/libbluray/*.lo
rm -f src/libbluray/bdj/*.o
rm -f src/libbluray/bdj/*.lo
rm -f src/libbluray/bdj/native/*.o
rm -f src/libbluray/bdj/native/*.lo
rm -f src/libbluray/bdnav/*.o
rm -f src/libbluray/bdnav/*.lo
rm -f src/libbluray/decoders/*.o
rm -f src/libbluray/decoders/*.lo
rm -f src/libbluray/disc/*.o
rm -f src/libbluray/disc/*.lo
rm -f src/libbluray/hdmv/*.o
rm -f src/libbluray/hdmv/*.lo
rm -f src/util/*.o
rm -f src/util/*.lo
test -z "" || rm -f
rm -f *.lo
rm -f *.tab.c
test -z "src/libbluray.pc src/libbluray/bluray-version.h" || rm -f src/libbluray.pc src/libbluray/bluray-version.h
test . = "." || test -z "" || rm -f
rm -f contrib/libudfread/src/.deps/.dirstamp
rm -f contrib/libudfread/src/.dirstamp
rm -f src/examples/.deps/.dirstamp
rm -f src/examples/.dirstamp
rm -f src/file/.deps/.dirstamp
rm -f src/file/.dirstamp
rm -f src/libbluray/.deps/.dirstamp
rm -f src/libbluray/.dirstamp
rm -f src/libbluray/bdj/.deps/.dirstamp
rm -f src/libbluray/bdj/.dirstamp
rm -f src/libbluray/bdj/native/.deps/.dirstamp
rm -f src/libbluray/bdj/native/.dirstamp
rm -f src/libbluray/bdnav/.deps/.dirstamp
rm -f src/libbluray/bdnav/.dirstamp
rm -f src/libbluray/decoders/.deps/.dirstamp
rm -f src/libbluray/decoders/.dirstamp
rm -f src/libbluray/disc/.deps/.dirstamp
rm -f src/libbluray/disc/.dirstamp
rm -f src/libbluray/hdmv/.deps/.dirstamp
rm -f src/libbluray/hdmv/.dirstamp
rm -f src/util/.deps/.dirstamp
rm -f src/util/.dirstamp
rm -f config.h stamp-h1
rm -f libtool config.lt
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -rf contrib/libudfread/src/.deps src/examples/.deps src/file/.deps src/libbluray/.deps src/libbluray/bdj/.deps src/li                                                                                                                                                       bbluray/bdj/native/.deps src/libbluray/bdnav/.deps src/libbluray/decoders/.deps src/libbluray/disc/.deps src/libbluray/h                                                                                                                                                       dmv/.deps src/util/.deps
rm -f Makefile
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '197609' is supported by ustar format... yes
checking whether GID '197121' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for i686-w64-mingw32-gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... H:/media-autobuild_suite/msys64/mingw32/i686-w64-mingw32/bin/ld.exe
checking if the linker (H:/media-autobuild_suite/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw32/bin/nm -B
checking the name lister (/mingw32/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert i686-w64-mingw32 file names to i686-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert i686-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for H:/media-autobuild_suite/msys64/mingw32/i686-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for i686-w64-mingw32-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic file format (pei*-i386(.*architecture: i386)?|pe-arm-wince|p                                                                                                                                                       e-x86-64)
checking for i686-w64-mingw32-dlltool... no
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for i686-w64-mingw32-ar... no
checking for ar... ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32-strip... no
checking for strip... strip
checking for i686-w64-mingw32-ranlib... no
checking for ranlib... ranlib
checking command to parse /mingw32/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for i686-w64-mingw32-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (H:/media-autobuild_suite/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) supports shared li                                                                                                                                                       braries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking return type of signal handlers... void
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking libgen.h usability... yes
checking libgen.h presence... yes
checking for libgen.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking mntent.h usability... no
checking mntent.h presence... no
checking for mntent.h... no
checking linux/cdrom.h usability... no
checking linux/cdrom.h presence... no
checking for linux/cdrom.h... no
checking for inttypes.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for mntent.h... (cached) no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for struct dirent.d_type... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for snprintf... yes
checking for i686-w64-mingw32-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBXML2... yes
checking for FT2... yes
checking if gcc supports -Wall flag... yes
checking if gcc supports -Wdisabled-optimization flag... yes
checking if gcc supports -Wpointer-arith flag... yes
checking if gcc supports -Wredundant-decls flag... yes
checking if gcc supports -Wcast-qual flag... yes
checking if gcc supports -Wwrite-strings flag... yes
checking if gcc supports -Wtype-limits flag... yes
checking if gcc supports -Wundef flag... yes
checking if gcc supports -Wmissing-prototypes flag... yes
checking if gcc supports -Wshadow flag... yes
checking if gcc supports -Werror=implicit-function-declaration flag... yes
checking for gcc way to treat warnings as errors... -Werror
checking if gcc supports -Wextra flag... yes
checking if gcc supports -Winline flag... yes
checking if gcc supports -O3 flag... yes
checking if gcc supports -fomit-frame-pointer flag... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/libbluray.pc
config.status: creating src/libbluray/bluray-version.h
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
  Summary:
  --------
  BD-J support:                  no
  Font support (freetype2):      yes
  Metadata support (libxml2):    yes
  UDF filesystem support:        no
  Build examples:                no
make  all-am
make[1]: Entering directory '/build/libbluray-git'
  CC       src/file/dir_win32.lo
  CC       src/file/dirs_win32.lo
  CC       src/file/dl_win32.lo
  CC       src/file/file_win32.lo
  CC       src/file/mount.lo
  CC       src/file/file.lo
  CC       src/file/filesystem.lo
  CC       src/libbluray/bluray.lo
  CC       src/libbluray/register.lo
  CC       src/libbluray/bdnav/bdid_parse.lo
  CC       src/libbluray/bdnav/clpi_parse.lo
  CC       src/libbluray/bdnav/extdata_parse.lo
  CC       src/libbluray/bdnav/index_parse.lo
  CC       src/libbluray/bdnav/meta_parse.lo
  CC       src/libbluray/bdnav/mpls_parse.lo
  CC       src/libbluray/bdnav/navigation.lo
  CC       src/libbluray/bdnav/sound_parse.lo
  CC       src/libbluray/decoders/graphics_controller.lo
  CC       src/libbluray/decoders/graphics_processor.lo
  CC       src/libbluray/decoders/ig_decode.lo
  CC       src/libbluray/decoders/m2ts_demux.lo
src/libbluray/decoders/graphics_controller.c: In function '_render_textst':
src/libbluray/decoders/graphics_controller.c:1012:13: warning: format '%d' expects argument of type 'int', but argument                                                                                                                                                        6 has type 'int64_t' [-Wformat=]
             GC_TRACE("_render_textst(): next event #%d in %"PRId64" seconds (pts %"PRId64")\n",
             ^
src/libbluray/decoders/graphics_controller.c:1012:13: warning: format '%d' expects argument of type 'int', but argument                                                                                                                                                        7 has type 'int64_t' [-Wformat=]
src/libbluray/decoders/graphics_controller.c:1037:9: warning: format '%d' expects argument of type 'int', but argument 6                                                                                                                                                        has type 'int64_t' [-Wformat=]
         GC_TRACE("_render_textst(): rendering dialog #%d (pts %"PRId64", diff %"PRId64"\n",
         ^
src/libbluray/decoders/graphics_controller.c:1037:9: warning: format '%d' expects argument of type 'int', but argument 7                                                                                                                                                        has type 'int64_t' [-Wformat=]
  CC       src/libbluray/decoders/m2ts_filter.lo
  CC       src/libbluray/decoders/pg_decode.lo
  CC       src/libbluray/decoders/pes_buffer.lo
  CC       src/libbluray/decoders/rle.lo
  CC       src/libbluray/decoders/textst_decode.lo
  CC       src/libbluray/decoders/textst_render.lo
  CC       src/libbluray/disc/aacs.lo
  CC       src/libbluray/disc/bdplus.lo
  CC       src/libbluray/disc/dec.lo
  CC       src/libbluray/disc/disc.lo
  CC       src/libbluray/hdmv/hdmv_vm.lo
  CC       src/libbluray/hdmv/mobj_parse.lo
  CC       src/libbluray/hdmv/mobj_print.lo
  CC       src/util/array.lo
  CC       src/util/bits.lo
src/libbluray/disc/disc.c:519:17: error: static declaration of '_rotl64' follows non-static declaration
 static uint64_t _rotl64(uint64_t k, int n)
                 ^
In file included from ./src/util/macro.h:24:0,
                 from src/libbluray/disc/disc.c:29:
H:/media-autobuild_suite/msys64/mingw32/i686-w64-mingw32/include/stdlib.h:572:46: note: previous declaration of '_rotl64                                                                                                                                                       ' was here
   __MINGW_EXTENSION unsigned __int64 __cdecl _rotl64(unsigned __int64 _Val,int _Shift);
                                              ^
Makefile:1484: recipe for target 'src/libbluray/disc/disc.lo' failed
make[1]: *** [src/libbluray/disc/disc.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
  CC       src/util/logging.lo
make[1]: Leaving directory '/build/libbluray-git'
Makefile:915: recipe for target 'all' failed
make: *** [all] Error 2
  CC       src/libbluray/disc/disc.lo
src/libbluray/disc/disc.c:519:17: error: static declaration of '_rotl64' follows non-static declaration
 static uint64_t _rotl64(uint64_t k, int n)
                 ^
In file included from ./src/util/macro.h:24:0,
                 from src/libbluray/disc/disc.c:29:
H:/media-autobuild_suite/msys64/mingw32/i686-w64-mingw32/include/stdlib.h:572:46: note: previous declaration of '_rotl64                                                                                                                                                       ' was here
   __MINGW_EXTENSION unsigned __int64 __cdecl _rotl64(unsigned __int64 _Val,int _Shift);
                                              ^
Makefile:1484: recipe for target 'src/libbluray/disc/disc.lo' failed
make: *** [src/libbluray/disc/disc.lo] Error 1
-------------------------------------------------
Build of libbluray-git failed...

**Comment by wiiaboo** [comment]
Seems to be a problem created in the last commit.
Either compile manually, opening mintty, going to /build/libbluray-git and:
```
git reset --hard HEAD^
./configure --build=$targetBuild --host=$targetHost --prefix=$LOCALDESTDIR --bindir=$LOCALDESTDIR/bin-video --disable-shared --enable-static --disable-examples --disable-bdjava --disable-doxygen-doc --disable-doxygen-dot LIBXML2_LIBS="-L$LOCALDESTDIR/lib -lxml2" LIBXML2_CFLAGS="-I$LOCALDESTDIR/include/libxml2 -DLIBXML_STATIC"
make
make install
touch build_successful$bits
``` and repeat configure, make and make install for 64-bits after running `source /local64/etc/profile.local`

or wait for it to be fixed.

**Comment by wiiaboo** [comment]
They're taking a bit to fix, so I'm forcing libbluray and libutvideo to known working commits while both aren't fixed.

**Comment by wiiaboo** [comment]
Libbluray commited a fix a few hours ago, but libutvideo is more complicated, but both should compile on their own and with ffmpeg fine now.

**Comment by Selur** [comment]
just came home from work and saw that the script stopped at f265 with:

From http://f265.org/repos/f265
 * branch            master     -> FETCH_HEAD
Already up-to-date.
-------------------------------------------------
f265 is already up to date
-------------------------------------------------
scons: Reading SConscript files ...

again,....

**Comment by Selur** [comment]
ran it again, this time it didn't stop at f265,..

**Comment by wiiaboo** [comment]
With the latest commit maybe f265 problems are fixed once and for all on our side.
