### ISSUE TITLE
compiling won't start

### ISSUE THREAD

**Issue by futurion** [jb-alvarado/media-autobuild_suite#840]
Hello,

in the latest release there's an error, before files downloading and compiling even begins:

Create update script: 1
-------------------------------------------------------------
- Download wget
-------------------------------------------------------------
.DownloadFile('https://i.fsbn.eu/pub/wget-pack.exe' was unexpected at this time.

Is there maybe a fix for this?

Best regards!

**Comment by futurion** [comment]
Still not good:

-------------------------------------------------------------

- Download wget

-------------------------------------------------------------
-------------------------------------------------------------------------------
Script to download necessary components failed.

Download and extract this manually to inside "D:\mingw\build":
https://i.fsbn.eu/pub/wget-pack.exe
-------------------------------------------------------------------------------
Press any key to continue . . .

**Comment by futurion** [comment]
If I extract the above files manually... a few lines below, another issue:

--2018-05-17 12:09:26--  (try: 5)  http://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz
Connecting to repo.msys2.org (repo.msys2.org)|45.59.69.178|:80...

**Comment by wiiaboo** [comment]
That's not our problem. It works fine here, so maybe you have some firewall or something blocking that host. You can also download that msys2 archive manually and extract it and the build probably continues, but if you can't access repo.msys2.org nothing will work.

**Comment by futurion** [comment]
The above is true... repo.msys2.org was just currently unavailable. But the issue with the script still remains:

- Download wget

-------------------------------------------------------------
-------------------------------------------------------------------------------
Script to download necessary components failed.

Download and extract this manually to inside "D:\mingw\build":
https://i.fsbn.eu/pub/wget-pack.exe
-------------------------------------------------------------------------------
Press any key to continue . . .

Is it possible to fix this as well, so we don't need to download anything by hand?

**Comment by wiiaboo** [comment]
> Is it possible to fix this as well, so we don't need to download anything by hand

Well, it says what you can do right there:
> Download and extract this manually to inside "D:\mingw\build":
https://i.fsbn.eu/pub/wget-pack.exe

**Comment by wiiaboo** [comment]
But if you're already moving on to failing in downloading msys2, it means the wget-pack one was successful before.

**Comment by futurion** [comment]
No, I downloaded "wget-pack" and extraced it manually, so I was able to get to the next step. Therefore I was asking if there's an option to fix this, so wget-pack would be also downloaded automatically as it worked before. The download link for wget-pack works ok, it just won't download it automatically for some reason. Is it possible to fix this as well inside main .bat script?

**Comment by wiiaboo** [comment]
The automatic download of the wget-pack.exe should already be working as of  5ac2685 for good.

**Comment by rdp** [comment]
As a note on "one computer but not others" I get this:

```

- Downloading and unpacking msys2 basic system

-------------------------------------------------------------------------------
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadFile('https://github.com/ch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

'7za' is not recognized as an internal or external command,
operable program or batch file.
```
yet curl from git works OK:
```
curl https://github.com/m-ab-s/media-autobuild_suite/raw/master/build/ > build1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131  100   131    0     0    365      0 --:--:-- --:--:-- --:--:--   365

```
Weird...
