### ISSUE TITLE
ffmpeg with --enable vapoursynth gives a non-working compile

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#841]
The way ffmpeg is compiled in the suite with the --enable-vapoursynth is wrong and gives a non working ffmpeg.exe
Just try:
```
fflplay -f vapoursynth -i any.vpy   or
ffmpeg -f vapoursynth -i any.vpy -c:v libx264 -an test.mkv
```
For a **properly compiled ffmpeg** with --enable-vapoursynth, dowload the **binary ffmpeg.exe** from here:
https://forum.doom9.org/showthread.php?p=1840663#post1840663

now try the above again : ffmpeg -f vapoursynth -i any.vpy -c:v libx264 -an test.mkv   ->  (works !!)

For instructions how to compile a working version:
https://forum.doom9.org/showthread.php?t=175341  (starting from **posts 16** although it might be interesting to read the whole tread (only 2 pages).

I can't test it myself because I don't have VS2017 installed.

**Comment by LigH-de** [comment]
If building ffmpeg with optional on-demand VapourSynth support requires Visual Studio 2017, and won't work with GNU C and Assembler in MinGW only, then MABS won't be able to build it equivalently.

**Comment by wiiaboo** [comment]
I personally don't give two shits about vapoursynth in ffmpeg. Either someone submits a PR for it, or wontfix, since I don't want to spend not even 10 seconds on fixing shit for someone that called me an idiot. Go fuck yourself and have a nice day.
