### ISSUE TITLE
Adding loudness-scanner to the suite?

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#846]
Hey there,
for my workflows it would help me very much, when you could add the loudness-scanner to the suite.
https://github.com/jiixyj/loudness-scanner/
Would that be possible? Thanks for your consideration!

**Comment by wiiaboo** [comment]
That has very annoying dependencies. If you can find a better alternative, or someone to fix the issues when building this, sure.

**Comment by wiiaboo** [comment]
Did you try https://github.com/desbma/r128gain? That would be much easier and only depends on ffmpeg executable.

**Comment by schmidthubert** [comment]
Is the loudnorm filter not sufficient enough:

https://trac.ffmpeg.org/wiki/AudioVolume
?

There's no source for [XmediaRecode](https://www.xmedia-recode.de/) but whatever they use works for me just fine to correct some dB occasionally. And I doubt they use anything fancy like that loudness scanner as in practice XmediaRecoder is just another GUI for ffmpeg which does the job here and there especially in batch mode ... :+1:

**Comment by BlackScreen** [comment]
> Did you try https://github.com/desbma/r128gain? That would be much easier and only depends on ffmpeg executable.
I looked at that one for a short time. It seems good for tagging audio files with the replay gain informations. The one I proposed seems to work more detailed with more stats. So, if I had to chose, then I would take loudness-scanner. 
@schmidthubert I know about loudnorm, which is great, I am using it frequently. In this case I am looking for a detailed scanner with all possible informations and also the correct informations. FFmpeg seems a bit off on some of the EBU test files.

**Comment by wiiaboo** [comment]
FFmpeg's r128 scanner is ported from the same libebur128 that loudness-scanner uses, afaik.

**Comment by wiiaboo** [comment]
Well, if you absolutely need loudness-scanner, ask the author to make it not error with FFmpeg 4.0 at the very least. It's using API from 2015.

**Comment by BlackScreen** [comment]
The author says it should be fixed. Could you check that?

**Comment by GyanD** [comment]
@BlackScreen can you share some details about the cases where FFmpeg's filter is off w.r.t EBU test files?

**Comment by BlackScreen** [comment]
Especially with momentary and shortterm values it is most of the time out of the tolerance zone.
I have measured all of the EBU test files with FFmpeg a while ago - I have to look and find the spreadsheet, if you want to know it more in detail.

**Comment by wiiaboo** [comment]
Did you try `loudnorm` filter? That's what's actually using the internal libebur128 port, not `-af ebur128` which was written long before by a FFmpeg dev.

**Comment by GyanD** [comment]
If the loudnorm scanner within ffmpeg is not accurate, we would like to [know](https://ffmpeg.org/bugreports.html) about it. FFmpeg upsamples audio streams to 192 kHz using an auto-inserted filter. Its parameters/flags may differ from what loudness scanner does. Of course, could be something else.
