### ISSUE TITLE
ERROR: tesseract not found using pkg-config

### ISSUE THREAD

**Issue by logicomyu** [jb-alvarado/media-autobuild_suite#848]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2065019/logs.zip)

**Comment by wiiaboo** [comment]
Seems like an issue on their side: https://github.com/tesseract-ocr/tesseract/issues

**Comment by wiiaboo** [comment]
If you care about getting newer tesseract commits, open an issue on their side with more information than that: say that it's failing at FFmpeg configuration, what's the error it's failing (pastebin ffmpeg-git/build-shared-64bit/ffbuild/config.log and add the link to the issue).

**Comment by schmidthubert** [comment]
https://github.com/tesseract-ocr/tesseract.git#commit=8d3f811 worked on Friday and does still work :+1:
