### ISSUE TITLE
Expect an exodus of several projects from MS-github to alternative hosters

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#854]
[Microsoft to acquire GitHub for $7.5 billion](https://news.microsoft.com/2018/06/04/microsoft-to-acquire-github-for-7-5-billion/)

People are afraid that the real price will be the users' privacy...

**Comment by wiiaboo** [comment]
I'll welcome the PRs that'll come from concerned users then.
