### ISSUE TITLE
liblsmash can not deal with the naming of the shared multi depth libx264

### ISSUE THREAD

**Issue by EraYaN** [jb-alvarado/media-autobuild_suite#855]
The x264 compile generates a `lib/libx264.dll.a`

liblsmash looks for `lib/libx264.a` halting the build process.

A quick fix is to link the *.a to the *.dll.a (in the script, if done manually the file gets removed.)

The script helpfully suggests removing x264_git (and thus building again) but that just (sucessfully I might add) regenerates the libx264.dll.a

The x264 is build shared so in the *compile.sh main script is should actually check for the *.dll.a and I'm not enough of a bash buff to be able to tell whenever the comma in that pattern messes it up. Or it's something else completely.

I though about this maybe being something upstream, but a manual make works just fine.

**Comment by wiiaboo** [comment]
lsmash doesn't depend on x264, it's the reverse. I'm not understanding the issue.

**Comment by EraYaN** [comment]
In that case the regular build success check for x264 fails. The libx264.dll.a does get created, but the script looks for libx264.a (the static version) does not find it, marks it as failed and exits.

```
[...]
  Running git update for gpac...
[1mgpac git (B[m.................................................. [[32mUp-to-date(B[m]
  Running git update for x264...
[1m┌ x264 git (B[m.......................................... [[311mRecently updated(B[m]
  Running git update for liblsmash...
[1mliblsmash git (B[m............................................. [[32mUp-to-date(B[m]
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
[1m├ /local64/lib/libx264.a (B[m................................... [[31mNot found(B[m]
[1m└ x264-git (B[m.................................................... [[31mFailed(B[m]

Try deleting '/build/x264-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.
```
That is the output (excuse the beautiful ascii color stuff, I got it from the log file.). 

```
[...]
adding file changes
transaction abort!
rollback completed
interrupted!
+ set +x
```
The clone fails for some reason as well, it gets an interrupt signal?

And the shared file does exist. So I wonder how that happened if the hg clone fails, but manually show that is worked.

<img width="607" alt="screen shot 2018-06-06 at 23 34 53" src="https://user-images.githubusercontent.com/1627021/41044940-48d7145e-69e2-11e8-9a20-3856b8941eb3.png">

**Comment by wiiaboo** [comment]
That's much simpler then; the script shouldn't expect static lib for shared lib builds.
