### ISSUE TITLE
[Error] too few arguments to function 'compute_vmaf'

### ISSUE THREAD

**Issue by Mirabis** [jb-alvarado/media-autobuild_suite#857]
Unfortunately, I'm unable to build ffmpeg due to errors with libvmaf : (
`
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error:
CC      libavfilter/vf_libvmaf.o
C:/Tools/media-autobuild_suite/build/ffmpeg-git/libavfilter/vf_libvmaf.c: In function 'compute_vmaf_score':
C:/Tools/media-autobuild_suite/build/ffmpeg-git/libavfilter/vf_libvmaf.c:165:16: error: too few arguments to function 'compute_vmaf'
     s->error = compute_vmaf(&s->vmaf_score, format, s->width, s->height,
                ^~~~~~~~~~~~
In file included from C:/Tools/media-autobuild_suite/build/ffmpeg-git/libavfilter/vf_libvmaf.c:28:0:
C:/Tools/media-autobuild_suite/local64/include/libvmaf.h:26:5: note: declared here
 int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),
     ^~~~~~~~~~~~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavfilter/vf_libvmaf.o] Error 1
make failed. Check C:/Tools/media-autobuild_suite/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
`

[logs.zip](https://0x0.st/s_VX.zip)

**Comment by LigH-de** [comment]
Already discussed in #845 – the reason is a recent API change in libvmaf, they suddenly need 2 more parameters. We are waiting for ffmpeg to catch up, I reported it in their trac 2 days ago.

_BTW, your paste lacks newlines; your text editor where you copied it out of seems not to support Unix line breaks well?_

**Comment by Mirabis** [comment]
Apologies, I copied directly from the mintty (I suppose) shell to github :/

I'll keep track of the other issue - thanks!

**Comment by LigH-de** [comment]
Copying from the log file may be more convenient, it also has the ANSI color escape sequences stripped off.
