### ISSUE TITLE
Autobuild repeatedly fails compiling  vf_libvmaf.o

### ISSUE THREAD

**Issue by wdmcdonald** [jb-alvarado/media-autobuild_suite#858]
[logs.zip](https://0x0.st/sLsE.zip)

├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error:
CC      libavfilter/vf_libvmaf.o
C:/autobuild/media-autobuild_suite-master/build/ffmpeg-git/libavfilter/vf_libvma                                                                                                                                                                                               f.c: In function 'compute_vmaf_score':
C:/autobuild/media-autobuild_suite-master/build/ffmpeg-git/libavfilter/vf_libvma                                                                                                                                                                                               f.c:165:16: error: too few arguments to function 'compute_vmaf'
     s->error = compute_vmaf(&s->vmaf_score, format, s->width, s->height,
                ^~~~~~~~~~~~

To me this looks very similar to https://trac.ffmpeg.org/ticket/6921
Which has been closed, "wontfix".
Comments on that ticket below read:

Changed 6 months ago by bermond
ffmpeg currently needs libvmaf git master.
Currently it will not compile with libvmaf stable release version.
I think this can be closed.
comment:4 Changed 2 weeks ago by richardpl
Resolution set to wontfix
Status changed from new to closed

How do I get around this problem using Autobuild?

**Comment by wiiaboo** [comment]
See https://github.com/jb-alvarado/media-autobuild_suite/issues/845
