### ISSUE TITLE
MP4Box no longer updated?

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#86]
When I run the script I get:

gpac is already up to date

but:
a. the MP4Box binary inside my local64/bin-video folder is from the 16th of April
and
b. http://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/ shows tons of builds since then,..

Would be nice if someone could look into this,...

**Comment by wiiaboo** [comment]
http://sourceforge.net/p/gpac/code/commit_browser
Last commit was in January (the February one is not to gpac trunk).

http://gpac.wp.mines-telecom.fr/2015/01/27/leaving-svn-and-sourceforge-using-git-and-github/
Seems they moved to github but @jb-alvarado didn't notice it.

**Comment by Selur** [comment]
-> would be nice if the script could be adjusted accordingly :)

**Comment by wiiaboo** [comment]
Done
