### ISSUE TITLE
shine-3.1.1 building failed

### ISSUE THREAD

**Issue by alex6dj** [jb-alvarado/media-autobuild_suite#864]
make failed. Check C:/mingw/build/shine-3.1.1/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.

https://0x0.st/sLYV.zip

**Comment by wiiaboo** [comment]
Could you upload the file `Makefile.am` inside `C:/mingw/build/shine-3.1.1/` somewhere?

**Comment by alex6dj** [comment]
I upload both plus the one in build-32bit, just in case.

[Makefile.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2112483/Makefile.zip)

**Comment by wiiaboo** [comment]
Just delete `shine-3.1.1` directory.
