### ISSUE TITLE
Build stops at aom git

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#865]
[logs.zip] (https://0x0.st/s9ij.zip)
Issue to fix upstream at aoms end?

**Comment by hydra3333** [comment]
This may not be related to you issue, or it may ... in a different build process, I had to add "-DENABLE_TESTS=0" to the cmake commandline otherwise the build process aborted.

**Comment by wiiaboo** [comment]
Could help. Make a PR for it.

**Comment by LigH-de** [comment]
Might have been a hint towards AOM getting tagged as v1.0.0 now. _Yay, release! ... What, again?!_
