### ISSUE TITLE
ffmpeg stops with undefined reference

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#866]
reporting it since I'm not sure whether it's a bug in ffmpeg or the suite
[logs.zip](https://0x0.st/s9af.zip)

**Comment by schmidthubert** [comment]
So there just these 2 possibilities, and after all it's only you again. Let's try a 3rd then: could it be the weather? :ice_cream:

**Comment by GyanD** [comment]
Please quote the error in the comment, so others can arrive via search and not open duplicate issues.

```
Likely error:
libavcodec/libavcodec.a(svq1enc.o):svq1enc.c:(.text.unlikely+0x18f): undefined reference to `ff_me_cmp_init'
libavcodec/libavcodec.a(ac3enc.o):ac3enc.c:(.text.unlikely+0x133f): undefined reference to `ff_me_cmp_init'
libavcodec/libavcodec.a(error_resilience.o):error_resilience.c:(.text+0xfde): undefined reference to `ff_me_cmp_init'
libavcodec/libavcodec.a(motion_est.o):motion_est.c:(.text+0x12f78): undefined reference to `ff_set_cmp'
libavcodec/libavcodec.a(motion_est.o):motion_est.c:(.text+0x12f9a): undefined reference to `ff_set_cmp'
libavcodec/libavcodec.a(motion_est.o):motion_est.c:(.text+0x12fbc): undefined reference to `ff_set_cmp'
libavcodec/libavcodec.a(motion_est.o):motion_est.c:(.text+0x12fde): undefined reference to `ff_set_cmp'
libavcodec/libavcodec.a(snow.o):snow.c:(.text.unlikely+0x33): undefined reference to `ff_me_cmp_init'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:107: ffmpeg_g.exe] Error 1
```

This has to be you. If this were ffmpeg, none of the FATE builds would even get to running the FATE suite. But they [do](http://fate.ffmpeg.org/?sort=descdate).

Remove the ffmpeg source dir and try again. There's probably a simpler solution, but this should work.

**Comment by Selur** [comment]
@GyanD: deleting the source helped (will now delete the source  before every run of the script since stuff like this happens more frequent in the last few month,..)
