### ISSUE TITLE
ffmpeg make error

### ISSUE THREAD

**Issue by wljcom** [jb-alvarado/media-autobuild_suite#872]
┌ x264 git .......................................... [Recently updated]
  Running git update for ffmpeg...
┌ ffmpeg git ........................................ [Recently updated]
├ Running uninstall...
├ Running configure...
├ Running install...
Likely error:
 static av_always_inline av_const double trunc(double x)
                                         ^~~~~
In file included from E:/opensource/media-autobuild_suite/build/ffmpeg-git/libavutil/common.h:36:0,
                 from E:/opensource/media-autobuild_suite/build/ffmpeg-git/compat/w32pthreads.h:43,
                 from E:/opensource/media-autobuild_suite/build/ffmpeg-git/libavutil/thread.h:133,
                 from E:/opensource/media-autobuild_suite/build/ffmpeg-git/libavdevice/alldevices.c:22:
E:/opensource/media-autobuild_suite/msys64/mingw64/x86_64-w64-mingw32/include/math.h:1044:25: note: previous declaration of 'trunc' was here
   extern double __cdecl trunc (double);
                         ^~~~~
make

: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavdevice/alldevices.o] Error 1
install failed. Check E:/opensource/media-autobuild_suite/build/ffmpeg-git/build-light-64bit/ab-suite.install.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2175303/logs.zip)

**Comment by wiiaboo** [comment]
That's not an error with the suite.

FFmpeg's configure is complaining about permissions being denied, so obviously something's broken in your system:
`E:/opensource/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file E:/opensource/media-autobuild_suite/msys64/tmp/ffconf.PQgh73Ii/test.exe: Permission denied`
