### ISSUE TITLE
Error building vulkan: No module named 'dispatch_table_helper_generator'

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#875]
[logs.zip](https://0x0.st/sfRU.zip)

I believe python3 has been updated recently. But may that be a possible cause, I don't know.

**Comment by chhe** [comment]
This is caused by MINGW's update of Python from 3.6 to 3.7. See https://github.com/Alexpux/MINGW-packages/issues/4062

**Comment by LigH-de** [comment]
Thanks. Good to know my brain still works.

**Comment by LigH-de** [comment]
The MSYS2 update to python 3.7.0-9 is supposed to fix this issue; testing...
