### ISSUE TITLE
would it be possible to add building dependency "libtensorflow" ?

### ISSUE THREAD

**Issue by hydra3333** [jb-alvarado/media-autobuild_suite#878]
would it be possible to add building dependency "libtensorflow" for nvidia GPU ? and maybe optionally cpu instead ?
AI seems to be the new wave of computing with filters ...

not sure if this helps:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake#step-by-step-windows-build

**Comment by wiiaboo** [comment]
Doesn't help at all, since that uses Visual Studio for the compilation.
Also, I don't see MinGW mentioned everywhere, so I'll it's totally unsupported and I won't waste any time on this.
