### ISSUE TITLE
MP4Box broken when build with media-autobuild_suite

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#88]
When using the rev376 from: http://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/

with 
> MP4Box.exe -hint  "h:\Output\02_01_24_7810__05.mp4"

I get:
>Hinting file with Path-MTU 1450 Bytes
Hinting track ID 1 - Type "mp4v:mp4v" (mpeg4-generic) - BW 723 kbps
Hinting track ID 2 - Type "mp4a:mp4a" (mpeg4-generic) - BW 317 kbps
Saving h:\Output\02_01_24_7810__05.mp4: 0.500 secs Interleaving

but when I use the one build with media-autobuild_suite I get:
> Option -hint unknown. Please check usage

I used: 
> MP4Box -par 1=1:1 -add "h:\Output\02_01_24_7810_03.m4v"#video:fps=25:delay=43 -add "h:\Output\iId_3_aid_1_ms_02_01_24_7810_02.aac"#audio:lang=:group=1
 -mpeg4 -ipod -itags tool="Hybrid 2015.05.09.1" -tmp "h:\Output" -new "h:\Output
\02_01_24_7810__05.m4v"

to create the file which works fine, so this seems like a compilation problem.
(this happens with the 32bit and the 64bit build)

**Comment by wiiaboo** [comment]
Building a static mp4box implies that a lot of things get disabled.

I've been able to compile with it but then MP4Box is no longer static, so it needs to be distributed along with libgpac.dll.

**Comment by wiiaboo** [comment]
I'm testing now with a fresh compilation of everything to see if shared gpac messes anything.

**Comment by Selur** [comment]
Strange thing is that afaik this did work once before,...

**Comment by jb-alvarado** [comment]
The `-hint` Parameter I also had use since long and it always have worked. gpac shared is not so so good, because we use the lib also for x264.

**Comment by wiiaboo** [comment]
x264 compiles fine with shared gpac, since gpac static also gets compiled. And encoding to .mp4 works even without libgpac.dll so I'd say it's safe to compile gpac shared.

**Comment by jb-alvarado** [comment]
Maybe we post this first to the gpac issue list, normally they replay very fast. And when they can fix this than is better for us :).

**Comment by jb-alvarado** [comment]
Can you use the -hint command with the shared version?

**Comment by wiiaboo** [comment]
Yes.

**Comment by Selur** [comment]
http://pastebin.com/uh3Be622
-> seems like an error got ignored,..

**Comment by wiiaboo** [comment]
It's supposed to error copying shared libs, because gpac shared libs aren't built.

**Comment by Vangelis66** [comment]
Selur commented:

> Strange thing is that afaik this did work once before,...

I can atest to that, too...
I still have on my disk the x86 MP4Box static binary that I compiled last November (2014) 
with media-autobuild_suite-master-v2.9-git-531ce45; OS used for compilation was 
WinVista SP2 32bit; the binary's version is MP4Box-0.5.1-dev-r5499-x86-static. 
Command used:

mp4box -hint bbc3.mp4 -out bbc3-hinted.mp4
Hinting file with Path-MTU 1450 Bytes
Hinting track ID 1 - Type "avc1:avc1" (H264) - BW 1619 kbps
Hinting track ID 2 - Type "mp4a:mp4a" (mpeg4-generic) - BW 123 kbps
Saving to bbc3-hinted.mp4: 0.500 secs Interleaving

If it's at all possible, I would prefer it if the script could continue to compile fully functional MP4Box static binaries...
Many thanks for your continued efforts in keeping this precious project alive...
Regards

**Comment by wiiaboo** [comment]
Before we changed the source to github the script was probably still compiling versions with working -hint since the commit that removed is from January. We just noticed it now.

**Comment by jb-alvarado** [comment]
We get feedback from the gpac dev team and they can reproduce it, that means they will fix it. I hope is soon.

**Comment by Murmur** [comment]
I have this same problem but with dashing a file "unknown -rap". So problem is static mp4box build script disables most features(?). How do I compile a shared mp4box whitn media-autobuild_suite environment?

**Comment by wiiaboo** [comment]
Check https://github.com/jb-alvarado/media-autobuild_suite/pull/89/files on what to change to build shared mp4box.

**Comment by wiiaboo** [comment]
We'll leave this open to remind ourselves when gpac fix the problem.

**Comment by wiiaboo** [comment]
With https://github.com/gpac/gpac/commit/fe222b3fdb7d28835238946963045bb8d8856645 -hint works. I have no idea what -rap does, but it should probably work too.
