### ISSUE TITLE
Updating the suite: option --force is obsolete

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#882]
Instead, the option --overwrite is recommended.

I am not sure which tool this warning belongs to, yet I would guess: pacman, because the next messages report solving dependencies and searching for conflicting packages.

This excerpt of **build/update.log** contains messages in German; before you get grumpy about that fact: I tried to translate them by meaning already above here. I still want to quote it so you can see in which chapter it happens.

```
-------------------------------------------------------------------------------
Updating msys2 system and installed packages...
-------------------------------------------------------------------------------
Warnung: Option --force ist überholt; stattdessen benutze --overwrite
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...
```

**Comment by wiiaboo** [comment]
Yeah, I expected that, but overwrite isn't really the same thing. When force is gone, then we stop using force.
