### ISSUE TITLE
vulkan-loader: undefined reference to `_imp__CM_…' symbols

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#883]
Is this like OpenCL, that I need Vulkan drivers installed and working to be able to compile this library?

[logs.zip](https://0x0.st/sVBB.zip)
___

Maybe it's not that ... I have a GeForce GTX 1050 Ti, drivers 391.140.0, Vulkan version 1.0.65; Basemark GPU benchmark 1.0.0 works in Vulkan mode.

May it just be a symbol naming convention issue (Win32 vs. Win64 target, with or without @##)?

**Comment by nwgat** [comment]
i got a related issue

[22/22] Linking C static library loader\libvulkan.a
install: cannot stat 'loader/vulkan.pc': No such file or directory
├ /local64/lib/pkgconfig/vulkan.pc ......................... [Not found]
└ vulkan-loader-git ........................................... [Failed]

**Comment by wiiaboo** [comment]
Will be fixed if/when https://github.com/shinchiro/mpv-winbuild-cmake/pull/3 is merged.
