### ISSUE TITLE
AOM fail build

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#885]
https://0x0.st/sVgo.zip

It breaks when building aom git

**Comment by LigH-de** [comment]
Confirming.

**build/aom-git/build-32bit/ab-suite.cmake.log**
```
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
cmake .. -G Ninja -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX=/local32 -DUNIX=on -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=off -DENABLE_TOOLS=off -DENABLE_TESTS=off -DENABLE_NASM=on -DCONFIG_UNIT_TESTS=0 -DENABLE_TESTS=OFF -DENABLE_TESTDATA=OFF
H:/development/media-autobuild_suite-master/msys64/mingw32/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

Without any clue, 
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2233214/logs.zip)
I suspect a recent MSYS update being part of the issue; updated packages are: `asciidoc bison curl file libcurl libgnutls libopenssl mingw-w64-i686-curl mingw-w64-x86_64-curl openssl perl-Error perl-HTTP-Message perl-IO-Socket-SSL perl-Net-HTTP perl-Test-Pod perl-URI perl-libwww`

**Comment by wiiaboo** [comment]
Likely some issue with some updated package, not the suite, likely broken cmake or some cmake dependency. Complain to MSYS2 devs.

**Comment by LigH-de** [comment]
Yes, a few more reports in [MINGW-packages issues 4111](https://github.com/Alexpux/MINGW-packages/issues/4111) about missing base libraries.
