### ISSUE TITLE
ffmpeg 4.0 with pthreads enabled

### ISSUE THREAD

**Issue by futurion** [jb-alvarado/media-autobuild_suite#888]
I'd like to compile a specific version of ffmpeg. Actually I'd like to compile official "ffmpeg-4.0-w32-shared". Is it possible to do this with media-autobuild-suite? Currently this suite only compiles every time the latest snapshot from ffmpeg repository. Is it possible to set it up so it would compile official 4.0 ffmpeg release instead?

Also I'd need shared .dll libraries instead of everything inside one .exe package. This should be achieved using "--enable-shared" parameter. Is this possible with media-autobuild-suite?

Lastly, I'd need this because I want to have 4.0-ffmpeg-shared version with pthreads enabled (or in other words w32threads disabled). What's the easiest option to achieve this? Should I only add "--disable-w32threads" or do I also need to add "--enable-pthreads" parameter?

Simply, I need the official "ffmpeg-4.0-w32-shared" binaries with pthreads enabled. Is this possible to achieve with media autobuild suite?

Kind regards and thank you in advance for help.

**Comment by wiiaboo** [comment]
> I'd like to compile a specific version of ffmpeg. Actually I'd like to compile official "ffmpeg-4.0-w32-shared". Is it possible to do this with media-autobuild-suite? Currently this suite only compiles every time the latest snapshot from ffmpeg repository. Is it possible to set it up so it would compile official 4.0 ffmpeg release instead?

Create a file called ffmpeg_extra.sh inside /build/ffmpeg-git.
There, add the line `do_vcs "https://git.ffmpeg.org/ffmpeg.git#branch=release/4.0"`.

> Also I'd need shared .dll libraries instead of everything inside one .exe package. This should be achieved using "--enable-shared" parameter. Is this possible with media-autobuild-suite?

Choose the option to compile FFmpeg shared on the first run of the suite or change in the .ini ffmpegB2 to `ffmpegB2=3`.

> Lastly, I'd need this because I want to have 4.0-ffmpeg-shared version with pthreads enabled (or in other words w32threads disabled). What's the easiest option to achieve this? Should I only add "--disable-w32threads" or do I also need to add "--enable-pthreads" parameter?

Adding `--disable-w32threads` to ffmpeg_options.txt is enough.

**Comment by futurion** [comment]
Ricardo, thank you very much for this. That was really helpful.

Maybe one more question, if I may. Let's say I'd just like to re-compile official "Zeranoe w32-shared 4.0" build as it is found on his binaries download site. The only differenc would be "pthreads enabled", nothing more, nothing less. I spotted the option "mimic zeranoe" inside media suite. Is it enough just to use that "mimic zeranoe" option after I setup that special ffmpeg_extra.sh file or should I also add something extra? In simple words, I'd need "official zeranoe w32 shared" with pthreads enabled.

Thank you again!

**Comment by wiiaboo** [comment]
I don't pay any attention to changes zeranoe does to his builds. It's up to you to see what options are missing.

Don't choose the mimic zeranoe because you won't have ffmpeg_options.txt available to use. The file contains all the supported options in the suite in comments. Just uncomment the ones you need.

I also don't pay attention or really care at all to use the same versions of the libraries as zeranoe, so it won't be just pthreads being different. A whole lot of libs and variables will be different from zeranoe's. Zeranoe's is also compiled in Linux, not MSYS.

If you're looking to just change a single thing and still have the "stability" of zeranoe's, just ask for a personal build. This suite's purpose is building mostly bleeding edge libs and programs, not to be a production-ready binary builder.

**Comment by futurion** [comment]
Thank you, that post above clarifies everything. I managed to compile the latest ffmpeg with all the latest libraries with pthreads support and for now it works just fine. I think you're right there's no need to have the actual "zeranoe" build.

Btw, would you maybe know, are there any kind of advantages/disdvantages when using pthreads instead w32threads? I need pthreads because of some additional UDP mpegts output parameters (bitrate, burst_bits, etc.). The only work with pthreads enabled and these parameters produce perfect CBR UDP mpegts output. Without them it just isn't true CBR. Will some other functions/codecs suffer because of this? I read around that w32threads should be faster than pthreads. Maybe any other incompatibility issues?

Oh, about compiling 4.0. It didn't work. I added the line as you suggested, but it just returned an error... something like "there's no sources..." and "post the log file online". But again, i doesn't matter. With latest it works ok.

Regards and thank you again.

**Comment by wiiaboo** [comment]
> Oh, about compiling 4.0. It didn't work. I added the line as you suggested, but it just returned an error... something like "there's no sources..." and "post the log file online". But again, i doesn't matter. With latest it works ok.

Well, I thought that would work, but I've never actually tried it like that. You probably need to directly change the corresponding line in media-suite_compile.sh to use that branch.
Look for the second time `do_vcs "https://git.ffmpeg.org/ffmpeg.git"` shows up.
As of git master, it's here https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1495

**Comment by schmidthubert** [comment]
Use tag instead of branch in ffmpeg_extra.sh, like this

`do_vcs "https://git.ffmpeg.org/ffmpeg.git#tag=n4.0"`
or even
`do_vcs "https://git.ffmpeg.org/ffmpeg.git#tag=n4.0.2"`

if you want to use latest stable inside 4.x . For latest stable 4.x commits directly instead of master tree pick the commit directly from
https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/refs/heads/release/4.0
by copying the latest commit SHA from the top, eg

`do_vcs "https://git.ffmpeg.org/ffmpeg.git#commit=9cc5337247b2eab04966af71057381d95f852e55"`
or [shorten it](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1) to
`do_vcs "https://git.ffmpeg.org/ffmpeg.git#commit=9cc53372"`

in ffmpeg_extra.sh and it should work as well ...

**Comment by wiiaboo** [comment]
Or try `do_vcs "https://git.ffmpeg.org/ffmpeg.git#branch=origin/release/4.0"`.
The `/` character messed it up.

**Comment by wiiaboo** [comment]
No, it should be needed to clean up the suite.
Can you paste the contents of ffmpeg_extra.sh to make sure?

**Comment by futurion** [comment]
Curreently I'm running it again, clean installation. I created the folder /build/ffmpeg-git as it doesn't exist initially. Inside that folder I created additional file ffmpeg_extra.sh as you suggested. Inside that file I only pasted one single line, nothing else. Currently I entered:

do_vcs "https://git.ffmpeg.org/ffmpeg.git#tag=n4.0"

as Hubert suggested, to see if this option works. If I'm missing something, please let me know, and I'll try it.

**Comment by wiiaboo** [comment]
If using the ffmpeg_extra.sh doesn't work change it in the script like I said in https://github.com/jb-alvarado/media-autobuild_suite/issues/888#issuecomment-410095838

**Comment by futurion** [comment]
Is it only necessary to change that single line to approppriate version? I found that same link git.ffmpeg.org at many places in that .sh file. Do I need to enter that same git version everywhere or only in that single line?

**Comment by wiiaboo** [comment]
Just that single line.

**Comment by futurion** [comment]
Thank you, that did it! Maybe it would be nice if you can fix the script so ffmpeg_extra.sh would be functional as well, so we don't need to replace the original files.

**Comment by futurion** [comment]
One more issue. After changing that line at 1495 in media-suite_compile.sh it is only possible to compile nonfree version. If I try to create GPL v3 it always returns an error when configuring ffmpeg-git. I tried multiple options (zeranoe, full, manual), but only minimal version can be compiled with GPLv3, all other options return an error.

Is there something that can be done to compile GPLv3 with manual packages or zeranoe mimic selection as well? I'm using: do_vcs "https://git.ffmpeg.org/ffmpeg.git#tag=n4.0.2". With latest git by default also GPLv3 can be compiled, but not with 4.0.2.

**Comment by wiiaboo** [comment]
Changing that line shouldn't in any way inhibit the license you can use.
I need the logs.zip.

**Comment by futurion** [comment]
Below is the output error with link to logs... same happens with 4.0 or 4.0.2, but only with GPL. If I choose nonfree, it compiles ok.

-

  Running git clone for ffmpeg...
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to gplv3...
├ Compiling shared FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
../configure --disable-static --enable-shared --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-libx265 --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-version3 --enable-chromaprint --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-libopenmpt --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-mbedtls --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --prefix=/local32 --bindir=/local32/bin-video --shlibdir=/local32/bin-video
Unknown option "--enable-mbedtls".
See ../configure --help for available options.
configure failed. Check D:/mingw402-gpl/build/ffmpeg-git/build-shared-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/s4i7.zip
Copy and paste [logs.zip](https://0x0.st/s4i7.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
That doesn't have anything to do with the license. You're trying to include a library that doesn't exist in 4.x.
> Unknown option "--enable-mbedtls".

**Comment by futurion** [comment]
That's what I see as well, but I didn't set any manual parameters. Where can I remove this parameter? Also, I see "--disable-w32threads" is also there, but it shouldn't be by default. Are these parameters set somehow automatically or where are they read from?

**Comment by wiiaboo** [comment]
> That's what I see as well, but I didn't set any manual parameters. Where can I remove this parameter? Also, I see "--disable-w32threads" is also there, but it shouldn't be by default. Are these parameters set somehow automatically or where are they read from? Are all of them even correct?

You should be using ffmpeg_options.txt like I said right at the beginning instead of the built-in options.
They are correct, for git master, not releases. That's why I don't make it easier to just use random tags/branches.

> Still, if this doesn't have to do aynthing with licence, why then nonfree compiles ok every time?

Because nonfree prefers openssl instead of mbedtls if both are enabled.

**Comment by futurion** [comment]
I am using ffmpeg_options.txt to pass the parameters as you suggested, but the --disable-w32threads isn't in there, but ffmpeg is still compiled with it. Even if I write --enable-w32threads in the .txt it still compiles with --disable-w32threads. It seems like it is ignoring it. That's for v4.0 or v4.0.2. If I use git-master then all works as it should. All I actally changed was editing one single line with branch tag at line 1495 as mentioned above, nothing else. The file ffmpeg_options.tx is generated by default and I haven't touched it. It is without --disable-w32threads, but ffmpeg is still compiled with that option If I choose nonfree. If I choose GPLv3, it won't compile. 

Therefore I'm wondering, would it be possible for you to prepare some kind of working setup or at least point me into the righ direction what should I do so I would be able to compile release 4.0 and 4.0.2 with GPLv3 licence (without fdk-aac and openssl), but with x264, x265 and all other options included. Also, I'd like to compile two releases (one with --disable-w32threads, and one with --enable-w32threads). Is this doable somehow?

**Comment by wiiaboo** [comment]
There's probably some lib forcing disabled w32threads, like libvmaf, or decklink and libzvbi. If you enable any of these you're forced to disable w32threads.

I noticed your ffmpeg_options.txt in the zip includes more libs than zeranoes, including zvbi and libvmaf. If you want two builds with pthreads and w32threads you can't use these.

**Comment by futurion** [comment]
The file ffmpeg_options.txt was generated automatically and I haven't touched it. But however, it seems there's really a lot of knowledge involved in compiling these builds and I surely don't have it.

Would it be possible for you if I kindly ask you to prepare a working setup, maybe just a working ffmpeg_options.txt or whatever special other settings I would need, so I would be able to compile two working 4.0.2 releases, one with pthreads and one with w32threads, both including x264, x265 and other ordinary libs, similar to zeranoe?
