### ISSUE TITLE
mpv error with default mpv_options.txt

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#889]
If you use the built-i┌ mpv git ........................................... [Recently updated]
├ Running configure...
Likely error:
Checking for Xv video output                                      : x11 not found
Checking for OpenGL Cocoa Backend                                 : cocoa not found
Checking for OpenGL X11 Backend                                   : x11 not found
Checking for OpenGL X11 EGL Backend                               : x11 not found
Checking for OpenGL DRM EGL Backend                               : drm not found
Checking for OpenGL Wayland Backend                               : wayland not found
Checking for OpenGL Win32 Backend                                 : yes
Checking for OpenGL/DirectX Interop Backend                       : yes
Checking for OpenGL ANGLE headers                                 : no
You manually enabled the feature 'egl-angle', but the autodetection check failed.
n options and it's broken because of a lib you didn't even
know existed or will never use, please choose your own libs and avoid creating
issues about it. I barely have any time or will to maintain this.

For new libs and tools pull requests are strongly recommended instead of opening
a feature request for the same reason above.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2258023/logs.zip)

if I diasable --enable-egl-angle the compilation goes on .. ! ???

**Comment by wiiaboo** [comment]
The Angle build might be too old. Don't use it unless for some reason you're using a GPU without DX11.

**Comment by ASopH** [comment]
it should be disabled by default in mpv_options.txt - thanks for information
