### ISSUE TITLE
Building ffmpeg/tools

### ISSUE THREAD

**Issue by Wallboy** [jb-alvarado/media-autobuild_suite#890]
Hello, thanks for the great tool. I needed a ffmpeg build that was similar to the default Windows builds BUT I needed lib-rubberband as well. After reading build guides, I eventually stumbled upon this tool and it works great. I now have a fully built ffmpeg with all features. 

I work with a lot of ffmpeg filter chains and seen the tool ffmpeg provides called graph2dot in the /tools directory which looks like it could be handy. I was wondering how I can build this tools directory? I still have all my build files. Is it possible to build these tools using the mintty easily now with all the build directories still present?

Thanks

**Comment by wiiaboo** [comment]
If you still have build-64bit/ or build-32bit/ directory inside /build/ffmpeg-git, sure.
Just `cd` until you're there and then `make tools/graph2dot`.

**Comment by Wallboy** [comment]
Doh, I don't have those. I guess I must have selected the auto clean up option. Is the only option to re-run the .bat and build it all again?

**Comment by wiiaboo** [comment]
Yeah. Or at least run configure.

**Comment by Wallboy** [comment]
I ran `./configure` in ffmpeg-git. I know this configure is different then the one that gets built using the .bat. But if a vanilla ffmpeg configure is only needed to compile graph2dot that is fine. I then tried `make tools/graph2dot` and got this error:

> make: *** No rule to make target 'tools/graph2dot'.  Stop.

 Did I have to specify something additional with ./configure?

**Comment by wiiaboo** [comment]
It's `make tools/graph2dot.exe`

**Comment by Wallboy** [comment]
Yup! Just figured it out after reading someone was trying to build Ismindex with the same error. Thanks. And wow, it's 150MB in size. Wonder why it's so big. Not that it matters...

Thanks for your help!
