### ISSUE TITLE
aomenc (MinGW64, GCC 8.2.0) crashes, Tree SLP vectorization bug?

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#893]
MSYS2 recently updated MinGW64 with GCC 8.2.0; since then, aomenc crashes while encoding in second pass.

[aomedia issue 2055](https://bugs.chromium.org/p/aomedia/issues/detail?id=2055) – Segmentation fault when encoding (introduced by "Remove code about dev speed features")
Summary: `So it looks like -ftree-slp-vectorize is the culprit here`

Better wait if Alexpux downgrades GCC back to 7.3.0, or try to disable vectorization using a flag?

**Comment by wiiaboo** [comment]
I haven't the faintest. If the flag can be disabled, why would there be a need to downgrade GCC?

**Comment by LigH-de** [comment]
Would it be re-enabled when the bug is fixed (fixable at all)?

I may sound a bit pessimistic, GCC 8.2.0 was already left out in MinGW32 due to internal compiler issues, and now also an issue in the MinGW64 version ... so I wonder if Alexpux might step back to 7.3.0 until 8.3.0 may be available. Who knows.

**Comment by wiiaboo** [comment]
No idea. I think FFmpeg explicitely disables some vectorizations because they're sorta unstable/buggy.

**Comment by schmidthubert** [comment]
Use 
`extracommands=(-DAOM_EXTRA_C_FLAGS="-fno-tree-slp-vectorize")`
in the script as has been suggested there and be done with it for now .... or forever, as certainly the speed of aom doesn't depend on just that optimization flag alone. :ice_cream:

**Comment by wiiaboo** [comment]
If it causes issues with GCC as a whole, it shouldn't even be enabled by default either in GCC or aom compiling. It shouldn't be a magic CFLAG that you have to add everywhere where you need to compile it.

**Comment by LigH-de** [comment]
From one to the next GCC generations, default compiler flags changed sometimes. It's indeed possible that GCC 8.2.0 has defaults GCC 7.3.0 did not yet have. Unfortunately, I don't read much about default flags in [GCC 8 Changes](https://gcc.gnu.org/gcc-8/changes.html). It seems to depend on `-O3` according to [GCC Vectorization](https://www.gnu.org/software/gcc/projects/tree-ssa/vectorization.html).

**Comment by wiiaboo** [comment]
They're fixing the issue on aom side. If you're not in a hurry for newer builds of aom, just wait for it to be fixed upstream.

**Comment by LigH-de** [comment]
Still, it's an interesting case for the compiler developers: The reason for the crash appears to be aligned vs. unaligned memory access, so the final fix may eventually have to be implemented in the vectorization code generation.

There is a temporary patch for aomenc in issue 2055, reordering instructions in shuffle functions to avoid this issue.

**Comment by LigH-de** [comment]
aomedia calls issue 2055 fixed: "shuffle code to work around gcc 8.2.0 issue"

**Comment by LigH-de** [comment]
Would you revert the temporary patch? https://github.com/jb-alvarado/media-autobuild_suite/commit/89ad3b493c4377a4ed2480e466fd18d137f69ef5 was edited.
