### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [jb-alvarado/media-autobuild_suite#894]
I keep getting errors when trying to compile. It breaks either while compiling libx264 or mpv.

[logs.zip](https://0x0.st/sJW5.zip)

**Comment by l-l-l-l-l-l** [comment]
It seems that part of it is an issue withx264 latest "stable" build, as the non-stable compiles just fine.

**Comment by wiiaboo** [comment]
I have no idea what you mean by stable or non-stable.

**Comment by wiiaboo** [comment]
I can't reproduce here with the same options used in your configure. Also, you're not saving logs, so that's way too much rubbish text to go through.
