### ISSUE TITLE
liblensfun: not enabled and not installed

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#899]
According to the README.md, liblensfun should be enabled for the full non-free ffmpeg build, but it is missing in the set of libraries to be enabled (pull request will follow).

When it is enabled, then it is not correctly installed after building, **/local32/lib/pkgconfig/liblensfun.pc** is not found afterwards:

```
  Running git clone for lensfun...
┌ lensfun git ....................................... [Recently updated]
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ /local32/lib/pkgconfig/liblensfun.pc ..................... [Not found]
└ lensfun-git ................................................. [Failed]

Try deleting '/build/lensfun-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.
```

**Comment by LigH-de** [comment]
I found that instead of `/local32/lib/pkgconfig/liblensfun.pc` there is a file `/local32/lib/pkgconfig/lensfun.pc` – do you believe that a mistake of the build scripts provided by the lensfun project, shall I complain in [the SF project](https://sourceforge.net/p/lensfun/bugs/) about it?

**Comment by wiiaboo** [comment]
Maybe they changed it, but FFmpeg does expect liblensfun.pc, so even if we
expect a different file, at most we'd have to duplicate it with the
different name.

**Comment by LigH-de** [comment]
In this case I will tell them in their SourceForge bug tracker, maybe they change it upstream to get compatible.

**Comment by LigH-de** [comment]
It may be related to a linker error: `undefined reference to `_imp__g_utf8_skip'`
[logs.zip](https://0x0.st/stTc.zip)

**Comment by LigH-de** [comment]
https://github.com/Alexpux/MINGW-packages/issues/988 mentions a GCC compiler flag `-DGLIB_STATIC_COMPILATION` which should possibly be enabled when ffmpeg will be built statically.

Patching media-suite_compile.sh for this case is possibly beyond my shell script skills...
