### ISSUE TITLE
Compiling single x265 binary with support for 8 and 10-bit output

### ISSUE THREAD

**Issue by wiiaboo** [jb-alvarado/media-autobuild_suite#90]
An interesting commit got pushed a few days ago: https://bitbucket.org/multicoreware/x265/commits/dadd6c419e55bfef08edd8339bd9c97249e625f4

This is not like vpxenc's single static binary 8-12bit support. The way this works is, you can couple a libx265_main10.dll together with x265.exe to enable the choice between 8 or 10-bit output after compilation. libx265_main10.dll is basically the same as libx265.dll but renamed so x265.exe can use it.
A few hours ago I think ffmpeg became able to do the same.

We could choose to build only 16-bit or only 8-bit static x265.exe and compile the other flavor into just the .dll and rename the latter to libx265_main.dll (8-bit) or libx265_main10.dll.

What do you think?

Finished testing now with ffmpeg.exe compiled with high bit-depth libx265 and libx265_main.dll in the same directory and it seems to work.

Using high bit-depth x265.exe with libx265_main.dll in the same directory:
`x265 --output-depth 8 in.y4m -o out.hevc` = 8-bit hevc
`x265 in.y4m -o out.hevc` = 10-bit hevc

Using ffmpeg.exe compiled with high bit-depth libx265 with libx265_main.dll in the same directory:
`ffmpeg -i in.y4m -pix_fmt yuv420p -c:v libx265 out.hevc` = 8-bit hevc
`ffmpeg -i in.y4m -c:v libx265 out.hevc` = 10-bit hevc

Using mpv with libx265_main.dll in the same directory:
`mpv in.y4m --ovc libx265 --o out.hevc` = 8-bit hevc (mpv by default encodes to the same format as input file)
`mpv in.y4m --vf format=fmt=yuv420p10 --ovc libx265 --o out.hevc` = 10-bit hevc

**Comment by jb-alvarado** [comment]
Is nice that they have put this function is. I like the idea to have the chance to select the output bit depth. I only like it not so much to have a shared lib. But as I understand you, it works also without the .dll, in standard mode? Then it is good! 
I also would like it to have the 8 bit as standard, and 10 bit as selection. Is that possible to? I think this is better, because of the compatibility to players, like quicktime, and hardware decoder - maybe they works only in 8 bit mode, like it was by x264.

**Comment by wiiaboo** [comment]
Hardware acceleration for hevc is more likely to support 10-bit since 4k
Blu-ray spec needs it. But yeah, 8-bit is fine. Eventually they want to
enable support like vpx.

**Comment by jb-alvarado** [comment]
Ah ok, that I was not knowing. Ok when the most decoders support 10 bit, then lets prefer it to.

**Comment by wiiaboo** [comment]
In case some
