### ISSUE TITLE
aom install fail

### ISSUE THREAD

**Issue by jkchoi2** [jb-alvarado/media-autobuild_suite#901]
If you use the built-in options and it's broken because of a lib you didn't even
know existed or will never use, please choose your own libs and avoid creating
issues about it. I barely have any time or will to maintain this.

For new libs and tools pull requests are strongly recommended instead of opening
a feature request for the same reason above.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2327493/logs.zip)

**Comment by jkchoi2** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2327495/logs.zip)

**Comment by wiiaboo** [comment]
Not a suite issue, complain to https://github.com/Alexpux/MSYS2-packages
