### ISSUE TITLE
Support for --enable libndi_newtek NDI libraries

### ISSUE THREAD

**Issue by kgoodyer** [jb-alvarado/media-autobuild_suite#903]
Is anybody able to look at support for 'libndi_newtek' which has been part of ffmpeg since 3.4.  media_autobuild_suite is perfect for building ffmpeg, but hooking in NDI manually is a pain. Don't think there is a GIT for it but the NDI SDK (which contains the headers and library's required for ffmpeg support) can be downloaded from http://pages.newtek.com/NDI-Developers-SDK-Download-Link.html.

**Comment by wiiaboo** [comment]
That's been requested [before](https://github.com/jb-alvarado/media-autobuild_suite/issues/721), and unless the situation's changed, it's still wontfix for me.

**Comment by jb-alvarado** [comment]
Here is a way, of how to compile it:

1. from the newtek sdk copy all the **include** files to media-autobuild-suite **/local64/include**
2. copy the **lib/Processing.NDI.Lib.x64.lib** to **/local64/lib/libndi.dll.a**
3. start the **mintty** shortcut in the suite root folder (with that you get all the right environment settings you need)
4. navigate to **/build/ffmpeg-git**
5. run **make distclean**
6. configure ffmpeg to your need, minimum: **--enable-libndi_newtek --enable-nonfree**
7. run **make**
8. now you have your ffmpeg.exe in the source folder
9. for running you need the **Processing.NDI.Lib.x64.dll** in the same folder

As you see the version is not totally static and of course you have to deal with the registration process from newtek. When I had include the decklink headers, I have ask blackmagic if they allow me to share the header from them and they say yes to me - but only the necessary files...

**Comment by wiiaboo** [comment]
And in the case of decklink you only need the headers. In this case you actually need the import lib and the only way they make them available is with a shitty installer, so it can't be automated.
Overall, a shitty way of making a public lib.

**Comment by jb-alvarado** [comment]
Yes that is right! And the download time can be very slow.

**Comment by hmedia1** [comment]
> Here is a way, of how to compile it:
> 
> 1. from the newtek sdk copy all the **include** files to media-autobuild-suite **/local64/include**
> 2. copy the **lib/Processing.NDI.Lib.x64.lib** to **/local64/lib/libndi.dll.a**
> 3. start the **mintty** shortcut in the suite root folder (with that you get all the right environment settings you need)
> 4. navigate to **/build/ffmpeg-git**
> 5. run **make distclean**
> 6. configure ffmpeg to your need, minimum: **--enable-libndi_newtek --enable-nonfree**
> 7. run **make**
> 8. now you have your ffmpeg.exe in the source folder
> 9. for running you need the **Processing.NDI.Lib.x64.dll** in the same folder
> 
> As you see the version is not totally static. When I had include the decklink headers, I have ask blackmagic if they allow me to share the header from them and they say yes to me - but only the necessary files...

What's the process on a Mac ?

**Comment by BlackScreen** [comment]
Weird thing, building ffmpeg with newtek support does not work on the Windows 10 computer here.
On my Windows 7 computer at home, it works. With the same libraries and so on.
Any idea, I know, not supported, but maybe someone has an idea.

**Comment by wiiaboo** [comment]
Heh, FFmpeg is thinking of removing libndi support because of them distributing non-free Windows binaries.

**Comment by sneakyjoeru** [comment]
Does someone have a compiled windows or ubuntu version of ffmpeg for download still?

**Comment by gaamaaresosa** [comment]
> Here is a way, of how to compile it:
> 
> 1. from the newtek sdk copy all the **include** files to media-autobuild-suite **/local64/include**
> 2. copy the **lib/Processing.NDI.Lib.x64.lib** to **/local64/lib/libndi.dll.a**
> 3. start the **mintty** shortcut in the suite root folder (with that you get all the right environment settings you need)
> 4. navigate to **/build/ffmpeg-git**
> 5. run **make distclean**
> 6. configure ffmpeg to your need, minimum: **--enable-libndi_newtek --enable-nonfree**
> 7. run **make**
> 8. now you have your ffmpeg.exe in the source folder
> 9. for running you need the **Processing.NDI.Lib.x64.dll** in the same folder
> 
> As you see the version is not totally static. When I had include the decklink headers, I have ask blackmagic if they allow me to share the header from them and they say yes to me - but only the necessary files...

Where is the problem with **ffmpeg and NDI** world ?
Why no 100% working samples around ?
None on the steps working so far.
Please see the response from mintty shortcut.

Kindly give me the clean working steps and keep in mind that we are not a linux experts.

> 5. run make distclean

make distclean
Makefile:2: ffbuild/config.mak: No such file or directory
make: No rule to make target 'ffbuild/config.mak'.  Stop.

> 6. configure ffmpeg to your need, minimum: --enable-libndi_newtek --enable-nonfree

./configure --enable-libndi_newtek --enable-nonfree
Unknown option "--enable-libndi_newtek".
See ./configure --help for available options.
