### ISSUE TITLE
Can I remove .stripped files safely?

### ISSUE THREAD

**Issue by gnucian** [jb-alvarado/media-autobuild_suite#904]
m-a_s leaves some .stripped files after successfully building binary files but failing to move the .stripped files.

![media-autobuild_suite_mv_failure](https://user-images.githubusercontent.com/3157518/44882692-3ecd8500-ac69-11e8-864e-78cb02a6a522.png)

The .stripped file seems newer than the .exe file.

![media-autobuild_suite_stripped_file_remains](https://user-images.githubusercontent.com/3157518/44882702-573d9f80-ac69-11e8-8503-e156ba9329a9.png)

Can I remove the .stripped file safely?

**Comment by wiiaboo** [comment]
Sure, you can even disable stripping them if the issue is that frequent.
You can also just rename them to the .exe to get smaller binaries with no loss of functionality.
