### ISSUE TITLE
lensfun: config misses gnulib

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#908]
ffbuild/config.log reports:

```
gcc -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib -Wl,--allow-multiple-definition -Wl,--large-address-aware -Wl,--nxcompat,--dynamicbase -Wl,--as-needed -Wl,--pic-executable,-e,_mainCRTStartup -mms-bitfields -IH:/development/media-autobuild_suite-master/local32/include/lensfun -IH:/development/media-autobuild_suite-master/msys64/mingw32/include/glib-2.0 -IH:/development/media-autobuild_suite-master/msys64/mingw32/lib/glib-2.0/include -LH:/development/media-autobuild_suite-master/local32/lib -LH:/development/media-autobuild_suite-master/msys64/mingw32/lib -pthread -o /tmp/ffconf.xhpNLOT0/test.exe /tmp/ffconf.xhpNLOT0/test.o -llensfun -lglib-2.0 -lintl -liconv -lcharset -lgnulib -lws2_32 -lwinmm -lws2_32 -lole32 -lwinmm -lshlwapi -lpcre -liconv -lpsapi -lstdc++ -lstdc++ -lgomp
H:/development/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgnulib
collect2.exe: error: ld returned 1 exit status
ERROR: lensfun not found using pkg-config
```

[logs.zip](https://0x0.st/svTh.zip)
__

Just guessing, would this work (line 1421)?

```
-    do_pacman_install glib2
+    do_pacman_install glib2 gnulib
```
__

Uhm, no, probably wrong place, ffmpeg needs it. Furthermore, it's possibly even a different package name. Or failing for ... reasons.
```
Installing gnulib... failed
```

**Comment by wiiaboo** [comment]
There's nothing in MSYS2 pacman with gnulib and I'd never heard of that before.

**Comment by schmidthubert** [comment]
MSYS2 recent updates:
`...`
`[2018-09-03 20:47] [ALPM] upgraded mingw-w64-i686-glib2 (2.56.2-1 -> 2.58.0-1)`
`...`
Another production fuckup?

**Comment by LigH-de** [comment]
The reason may be in https://github.com/Alexpux/MINGW-packages/issues/4364 (and https://github.com/Alexpux/MINGW-packages/issues/4372 may be a duplicate).

**Comment by bbcooper29** [comment]
Couldn't compile. Same error. I didn't need lensfun so I've disabled it in `ffmpeg_options.txt`. 
But now #906 is the new error.

**Comment by LigH-de** [comment]
That's a different issue. There are some dependencies of libsrt to wsock32, ws2_32, and socket.h I believe... (lost it in the meantime).

And in addition, fdk-aac doesn't compile in ffmpeg either. Several mistakes at once. All of them will have to be solved separately.

**Comment by bbcooper29** [comment]
Yeah latest commit from @wiiaboo fixed libsrt. `FDK` is the problem now.
Yesterday I tried cross-compiling from a Linux VM using [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers), I replaced `encoderDelay` with `nDelay` and compilation went OK. But trying to encode something using `libfdk_aac` gave me sync and frame skipping issues.

**Comment by LigH-de** [comment]
The latest commit fixed building libsrt; but it did not solve all the dependencies to missing files in ffmpeg's configure.

**Comment by wiiaboo** [comment]
If fdk-aac is enabled in the .bat and standalone isn't, it'll implicitely enable fdk on FFmpeg (or else the lib would be built for nothing). I can remove this implicit adding and/or you can explicitely disable it meanwhile.

**Comment by wiiaboo** [comment]
Check if 1ded98a fixes the lensfun issue.

**Comment by LigH-de** [comment]
https://github.com/Alexpux/MINGW-packages/commit/93cc01cd94966fca5fedd6de2f11e1b371a817fe should fix generating package configs with internal static libs. So you should be able to revoke the sed.

**Comment by wiiaboo** [comment]
Unlike the seds adding libs, the ones removing libs shouldn't break anything, so there's no hurry.

**Comment by schmidthubert** [comment]
glib2 was just updated to 2.58.0-2, see also https://gitlab.gnome.org/GNOME/glib/issues/1516 as well, should be fixed now ...
