### ISSUE TITLE
libsrt: INSTALL cannot find stdint.h

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#909]
In PR https://github.com/Haivision/srt/pull/454 the file common/win/stdint.h was removed from installation due to license issues; but the removal was probably incomplete, as cmake_install.cmake still contains a reference.

Reported there in issue https://github.com/Haivision/srt/issues/453

**Comment by wiiaboo** [comment]
Fixed upstream, I think.
