### ISSUE TITLE
Still fails to make ffmpeg, without liblensfun

### ISSUE THREAD

**Issue by carlhen** [jb-alvarado/media-autobuild_suite#913]
So, i went and removed liblensfun from media-autobuild_suite.bat, so that ffmpeg ignores it. #911 
Now it fails at fdk-aac in the ffmpeg make prosess, which is a library i need.
This is from a "clean" run, but the liblensfun removed from media-autobuild_suite.bat.
[logs.zip](https://0x0.st/svF4.zip)

**Comment by carlhen** [comment]
I found the fdk-aac issue in their github. https://github.com/mstorsjo/fdk-aac/issues/93
I don't know hot to apply it though.

**Comment by schmidthubert** [comment]
That doesn't apply cleanly and also there are more fdk patches coming. ffmpegs files differ from libavs and you'd have to do a lot of manual editing etc. Ricardo will probably have to pin versions again until ffmpegs sources are fixed ...

**Comment by LigH-de** [comment]
@carlhen - it's "liblensfun"...

I talked a bit in IRC #ffmpeg-devel about the progress of this kind of patch, but there seem to be more related changes, and they want to release it all together, so it may take a few more days.
