### ISSUE TITLE
libaomenc.c: undeclared symbol AOM_ERROR_RESILIENT_PARTITIONS

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#914]
A standalone aomenc builds without error, but fails to be built into ffmpeg. After AV1 "froze" the API, it seems to melt again:

```
libavcodec/libaomenc.c:744:109: error: 'AOM_ERROR_RESILIENT_PARTITIONS' undeclared here (not in a function); did you mean 'AOM_ERROR_RESILIENT_DEFAULT'?
                          " is still done over the partition boundary.",       0, AV_OPT_TYPE_CONST, {.i64 = AOM_ERROR_RESILIENT_PARTITIONS}, 0, 0, VE, "er"},
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                             AOM_ERROR_RESILIENT_DEFAULT
```

Reported to [ffmpeg trac ticket 7433](http://trac.ffmpeg.org/ticket/7433) and [aomedia code review 70421](https://aomedia-review.googlesource.com/q/Icae4b721cd07ab3385d2b3095903c873823f060a).

They seem to try to get rid of some VP8 remains.

**Comment by wiiaboo** [comment]
Clamped in bceaf0d1277231273ce392d4023b261a78f70c39 to previous commit.

**Comment by wiiaboo** [comment]
Fixed in FFmpeg upstream.
