### ISSUE TITLE
ffmpeg compile error

### ISSUE THREAD

**Issue by viviancfhung** [jb-alvarado/media-autobuild_suite#916]
![image](https://user-images.githubusercontent.com/42426931/45414357-b8c02e00-b6ad-11e8-8fcb-d2e4ebfaf5d2.png)

I found this problem when compliling

**Comment by wpapp** [comment]
mujs too

**Comment by wiiaboo** [comment]
Please don't open duplicate issues.
https://github.com/jb-alvarado/media-autobuild_suite/issues/914
