### ISSUE TITLE
compile build ffmpeg 64bit fails

### ISSUE THREAD

**Issue by badhras** [jb-alvarado/media-autobuild_suite#92]
When I get to the "compile ffmpeg 64bit" step, it fails. 

    ERROR: vidstab not found using pkg-config

    If you think configure made a mistake, make sure you are using the latest
    version from Git.  If the latest version fails, report the problem to the
    ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
    Include the log file "config.log" produced by configure as this will help
    solve the problem.

**Comment by badhras** [comment]
If it helps, this is my media-autobuild_suite.ini file
------------------------------------
[compiler list]
msys2Arch=2
arch=3
free=1
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
mp4box=1
mplayer=1
mpv=1
mkv=1
cores=4
deleteSource=1
strip=1
pack=2

**Comment by badhras** [comment]
This has more extended error information. Not sure if it helps.

=========
-------------------------------------------------------------------------------
compile ffmpeg 64bit
-------------------------------------------------------------------------------
From https://github.com/FFmpeg/FFmpeg
 * branch            master     -> FETCH_HEAD
Already up-to-date.
ERROR: vidstab not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
Makefile:2: config.mak: No such file or directory
Makefile:59: /common.mak: No such file or directory
Makefile:100: /libavutil/Makefile: No such file or directory
Makefile:100: /library.mak: No such file or directory
Makefile:102: /doc/Makefile: No such file or directory
Makefile:185: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:59: /common.mak: No such file or directory
Makefile:100: /libavutil/Makefile: No such file or directory
Makefile:100: /library.mak: No such file or directory
Makefile:102: /doc/Makefile: No such file or directory
Makefile:185: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
sed: can't read /local64/lib/pkgconfig/libavcodec.pc: No such file or directory
sed: can't read /local64/lib/pkgconfig/libavdevice.pc: No such file or directory
sed: can't read /local64/lib/pkgconfig/libavfilter.pc: No such file or directory
sed: can't read /local64/lib/pkgconfig/libavformat.pc: No such file or directory
sed: can't read /local64/lib/pkgconfig/libswresample.pc: No such file or directory
-------------------------------------------------
Build of ffmpeg-git failed...
Delete the source folder under '/build' and start again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

**Comment by jb-alvarado** [comment]
Hello badhras, can you please post the last lines in the /build/ffmpeg-git/config.log file, where it explain the error. Is at the very end from the file.

**Comment by wiiaboo** [comment]
I

**Comment by badhras** [comment]
Do I need to get updated code for media-autobuild-suite or does the existing code magically take care of updating itself? (sorry for the n00b question.)

**Comment by jb-alvarado** [comment]
Yes, you need to change the media-suite_compile.sh file with the new version. Maybe is also good when you delete the folders; `vidstab-git` and `ffmpeg-git`, under /build.

**Comment by wiiaboo** [comment]
No need to delete `ffmpeg-git`, just delete ffmpeg.exe inside bin-video and it'll recompile ffmpeg again.
