### ISSUE TITLE
fail to build libmediainfo

### ISSUE THREAD

**Issue by viviancfhung** [jb-alvarado/media-autobuild_suite#920]
when build ffmpeg 32bit windows and with lgplv3 license
![image](https://user-images.githubusercontent.com/42426931/45663785-d58bb400-bb3a-11e8-97d0-dc7d8a10e275.png)

**Comment by wiiaboo** [comment]
Great screenshot. Where's the logs?

**Comment by schmidthubert** [comment]
It's in the screenshot: https://0x0.st/sxvb.zip

**Comment by LigH-de** [comment]
Typing off your [logs.zip](https://0x0.st/sxvb.zip) you should have C/P'd.

A "nonfree" build seems to work, could there be a license mismatch?

**Comment by wiiaboo** [comment]
Upload the contents of `C:/media-autobuild_suite/local32/lib/cmake/zenlib/ZenLibTargets.cmake`

**Comment by brucedk** [comment]
Same error here... 
logs: https://0x0.st/s3nG.zip
ZenLibTargets.cmake:
`# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget zen)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "C:/media-autobuild_suite-master/local32")

# Create imported target zen
add_library(zen STATIC IMPORTED)

set_target_properties(zen PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE;_FILE_OFFSET_BITS=64"
  INTERFACE_INCLUDE_DIRECTORIES "C:/media-autobuild_suite-master/local32/include"
)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/ZenLibTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
`
