### ISSUE TITLE
opus-tools now need libopusenc >=0.2, no update detected

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#922]
I see no reason immediately, libopusenc appears not to be clamped.

```
opus git .................................................. [Up-to-date]
  Running git update for opusfile...
opusfile git .............................................. [Up-to-date]
  Running git update for libopusenc...
libopusenc git ............................................ [Up-to-date]
  Running git update for opus-tools...
┌ opus-tools git .................................... [Recently updated]
├ Running autogen...
├ Running configure...
Likely error:

Requested 'libopusenc >= 0.2' but version of libopusenc is 0.1.1-55-gc950e07
You may find new versions of libopusenc at https://opus-codec.org/

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBOPUSENC_CFLAGS
and LIBOPUSENC_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
[logs.zip](https://0x0.st/sxlv.zip)

IRC #opus on Freenode recommends https://git.xiph.org/?p=libopusenc.git as primary source. But https://github.com/xiph/libopusenc.git seems to be up to date as well.

I guess I can enforce updates by removing .pc files.

**Comment by wiiaboo** [comment]
Try removing libopusenc.pc inside /local64/lib/pkgconfig/. It's working fine here, but I didn't compile with opus-tools before in this installation, so I can't check if it's an issue with the vcs update check.

**Comment by wiiaboo** [comment]
You might have built the update before there was a tag. You'd need to have checked before the forced rebuild if `git tag -l` showed 0.2 there.
