### ISSUE TITLE
libvmaf not found

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#923]
Guys, I was trying to update today and recive this error: ERROR: libvmaf >= 1.3.9 not found using pkg-config, when it will compile the ffmpeg git. I dont know if it is an ffmpeg error, thats why I'm asking here first.
logs: https://0x0.st/sxFH.zip

**Comment by LigH-de** [comment]
Often when an update for a library was not detected, it is helpful to delete the package config file of this library to enforce a download of most recent sources. In your case, try to delete: local64/lib/pkgconfig/libvmaf.pc

**Comment by brucedk** [comment]
Ok, deleted and now works, thanks
