### ISSUE TITLE
(FR) build aomenc with CONFIG_LOWBITDEPTH

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#924]
In contrast to x264 and x265 which are already able to provide a multilib configuration to link encoder paths with both low and high bit depths, aomenc requires a separate build for each. The low bit depth path has to be enabled for higher speed (but limited precision) at compile time, using the CONFIG_LOWBITDEPTH flag.

Would you consider enabling it by default? Or possibly even by choice? ... _Maybe even building both LBD and HBD executables, similar to `x2652=d`?_

Related aomedia issues for reference: [2062](https://bugs.chromium.org/p/aomedia/issues/detail?id=2062) and [2147](https://bugs.chromium.org/p/aomedia/issues/detail?id=2147)

**Comment by LigH-de** [comment]
[Contra](https://forum.doom9.org/showthread.php?p=1852397#post1852397):
»I think there's no need for CONFIG_LOWBITDEPTH=0 builds, the appropriate codepaths are selected automatically based on input and output bit depths.«
:thinking:

**Comment by wiiaboo** [comment]
You can already add your own options, by the way.
Create the file aom_options.txt in /build with your personal configure/cmake options and it'll get picked up.

But I'll add that option by default then, if it doesn't hurt anything.

**Comment by hydra3333** [comment]
Just observing the texts "optimized code path" = "(but limited precision)", if that's that you really wanted.

**Comment by wiiaboo** [comment]
Well, I'm not adding another special duplicate build for that. If people don't want the faster 8-bit they can just use aom_options.txt with `-DCONFIG_LOWBITDEPTH=0`.

**Comment by LigH-de** [comment]
@hydra3333 - that may have been an early misunderstanding. Today it rather appears to me like the source started with "16 bit alignment for all bit depths", and later a special "8 bit alignment for 8 bit depth" code path was added but considered "to be tested before using it as default". Well, tests in the doom9 forum by SmilingWolf appeared successful.
