### ISSUE TITLE
Vulkan-loader error to compile

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#926]
I already delete and try again...

logs: https://0x0.st/s3Xv.zip

**Comment by wiiaboo** [comment]
Fixed in 5682503

**Comment by Selur** [comment]
[logs.zip](https://0x0.st/zN9d.zip)

**Comment by 1480c1** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/pull/1167

**Comment by 1480c1** [comment]
please try with that patch. Vulkan-loader requires vulkan-header v1.1.106, but we are clamped to v1.1.102 right now

**Comment by Selur** [comment]
tried with the modified media-suite_compile.shand it failed with:
[logs.zip](https://0x0.st/zNpK.zip) 
deleted the existing vulkan-* source folders and started the build again, this time it worked :)
