### ISSUE TITLE
Vulcan patch couldn`t applied

### ISSUE THREAD

**Issue by DigitalTVRepo** [jb-alvarado/media-autobuild_suite#927]
Deleted folders, Also I updated [build/media-suite_compile.sh](https://github.com/jb-alvarado/media-autobuild_suite/commit/5682503f70204ec959ffbb6dbe7cbf30c2d0974b) regarding [this answer](https://github.com/jb-alvarado/media-autobuild_suite/issues/926) but still not works.

logs: [logs.zip](https://0x0.st/s3Zm.zip)

**Comment by wiiaboo** [comment]
Probably fixed in upstream already. Try again.

**Comment by DigitalTVRepo** [comment]
Downloaded [latest version](https://github.com/jb-alvarado/media-autobuild_suite) and worked well
