### ISSUE TITLE
Error compiling mpv

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#929]
I'm having some error when it compiles the mpv git.

Logs: https://0x0.st/s3u0.zip
![capturar2](https://user-images.githubusercontent.com/40279859/45928310-e744d100-bf17-11e8-969c-313bfc38db5f.JPG)

**Comment by LigH-de** [comment]
Try to delete build/angle-latest-*.zip (I believe it helped me on one PC where I had this issue too).

**Comment by brucedk** [comment]
Don't work for me, but I make a new installation from the beginning and worked...
