### ISSUE TITLE
(Solved) Broken opusfile-git

### ISSUE THREAD

**Issue by slyfox1186** [jb-alvarado/media-autobuild_suite#930]
Broken opusfile-git

> https://0x0.st/s3YC.zip

**Comment by LigH-de** [comment]
Brief excerpt from ab-suite.make.log (to include searchable keywords in this report):

```
  CC       src/libopusurl_la-wincerts.lo
../src/wincerts.c: In function 'op_capi_new':
../src/wincerts.c:42:8: error: dereferencing pointer to incomplete type 'X509_LOOKUP {aka struct x509_lookup_st}'
     _lu->method_data=(char *)h_store;
        ^~
../src/wincerts.c: In function 'op_capi_retrieve_by_subject':
../src/wincerts.c:61:3: warning: implicit declaration of function 'CRYPTO_w_lock'; did you mean 'CRYPTO_zalloc'? [-Wimplicit-function-declaration]
   CRYPTO_w_lock(CRYPTO_LOCK_X509_STORE);
   ^~~~~~~~~~~~~
   CRYPTO_zalloc
../src/wincerts.c:61:17: error: 'CRYPTO_LOCK_X509_STORE' undeclared (first use in this function); did you mean 'CRYPTO_EX_INDEX_X509_STORE'?
   CRYPTO_w_lock(CRYPTO_LOCK_X509_STORE);
                 ^~~~~~~~~~~~~~~~~~~~~~
                 CRYPTO_EX_INDEX_X509_STORE
../src/wincerts.c:61:17: note: each undeclared identifier is reported only once for each function it appears in
../src/wincerts.c:63:3: warning: implicit declaration of function 'CRYPTO_w_unlock'; did you mean 'CRYPTO_realloc'? [-Wimplicit-function-declaration]
   CRYPTO_w_unlock(CRYPTO_LOCK_X509_STORE);
   ^~~~~~~~~~~~~~~
   CRYPTO_realloc
```

Will mention it in their bug tracker.

**Comment by slyfox1186** [comment]
replace line 559 with 
> do_separate_confmakeinstall --disable-{http,examples,doc}

replace line 568 with 
> do_separate_confmakeinstall --disable-{http,examples,doc}

**Comment by LigH-de** [comment]
Creating patch and pull request...

**Comment by wiiaboo** [comment]
Removing http seems like a big feature loss.

**Comment by LigH-de** [comment]
At least it can be reverted easily when it works again.

Alternative? ... Force a dependency to a lower but supported OpenSSL version until a newer version is supported?

And - damn, I wanted to test this patch before submitting it, but the next (unrelated) issue breaks it.

**Comment by wiiaboo** [comment]
Workaround in f77cb0b3ce36d28afef160bcb5a4015c56049276.

**Comment by wiiaboo** [comment]
Was checking why only mingw was affected since opusfile is working fine in Archlinux, but it's because of windows-specific code to get certificates.
