### ISSUE TITLE
Opusfile Errors

### ISSUE THREAD

**Issue by Revan654** [jb-alvarado/media-autobuild_suite#933]
I'm getting error codes when it comes to opusfile.

> make[1]:

> 
>  Entering directory '/build/opusfile-git/build-64bit'
>   CC       src/libopusurl_la-http.lo
> ../src/http.c:216:12: fatal error: openssl/ssl.h: No such file or directory
>  #  include <openssl/ssl.h>
>             ^~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:671: src/libopusurl_la-http.lo] Error 1
> make[1]: Leaving directory '/build/opusfile-git/build-64bit'
> make: *** [Makefile:471: all] Error 2

> make failed. Check C:/MediaTools.Suite/build/opusfile-git/build-64bit/ab-suite.make.log
> This is required for other packages, so this script will exit.

Logs: https://0x0.st/s3ly.zip

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/issues/930
