### ISSUE TITLE
x265 Git instead of hg?

### ISSUE THREAD

**Issue by 1480c1** [jb-alvarado/media-autobuild_suite#934]
I was wondering if it would be better to use https://github.com/videolan/x265 instead of https://bitbucket.org/multicoreware/x265? I can't immediately think of any problems using the github mirror as it seems to be a direct mirror from the bitbucket, unless I don't know something.

**Comment by wiiaboo** [comment]
It's been tried before. The commit hashes are unrelated and confuse people. Mercurial repo is the canonical one, not the git one.
