### ISSUE TITLE
Failed to Excute Script.exe

### ISSUE THREAD

**Issue by Revan654** [jb-alvarado/media-autobuild_suite#944]
It built everything fine last night, However today with latest update applied I'm getting: 

C:\MediaTools.Suite\msys64\usr\bin\script.exe: Exit 126.
Failed to run 'C:\MediaTools.Suite\msys64\usr\bin\script.exe': No such file or directory

It's not producing any errors logs for me to Upload. Some how the script.exe got deleted, moved or corrupted by one of the script. Not sure where to download the replacement exe file from.

**Comment by LigH-de** [comment]
As mentioned about at the same time in #945 – the reason is probably a mistake in the last MSYS2 update.

**Comment by GDXN** [comment]
grab it from http://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz , old version but worls

**Comment by schmidthubert** [comment]
Even if so: it needs foot soldiers like us noticing that something is missing? I can only repeat: quality control, where is it today?

**Comment by schmidthubert** [comment]
IOW: some X decided to change something and didn't inform anyone else, right? That's always a good idea, just do it but don't tell anyone ...

**Comment by schmidthubert** [comment]
>so it won't ever be in msys2
Yeah, then fuck these idiots doing that ....

**Comment by wiiaboo** [comment]
Well, things can't just be stuck in the past forever. For some reason upstream decided they needed that functionality and it's utils-**linux**, so fuck the others.

**Comment by schmidthubert** [comment]
>can't just be stuck in the past forever
This is plain ignorant behavior not looking left or right They/s/he/ must be fully aware of the consequences but nevertheless they push it and that apparently even without any previous announcement, fully aware that such tools are used everywhere from VMware to Azure etc. and that it will cause a quite a hickup. Is this line of action really necessary? I don't think so!

**Comment by wiiaboo** [comment]
Once again, you're mistaking upstream developers for people who care about all who use their software. It's in all FOSS' licenses that they give no warranty or basically any shits if stuff stops working.

**Comment by schmidthubert** [comment]
No, I fully understand. And that's also why Redmonds stock is up day after day, because there's no match for them. Just a bunch of ants, each of them following their own ideas (and licences). An unorganized mess against tie wearing world rip off pricks. Much congrats to that. Will we go on like that forever then?

**Comment by LigH-de** [comment]
Maybe there is an alternative available, outside the MSYS2 software distribution. If I understood correctly, it's just a logger, which reminds me of e.g. https://github.com/lordmulder/LoggingUtil

**Comment by wiiaboo** [comment]
> No, I fully understand. And that's also why Redmonds stock is up day after day, because there's no match for them. Just a bunch of ants, each of them following their own ideas (and licences). An unorganized mess against tie wearing world rip off pricks. Much congrats to that. Will we go on like that forever then?

The issue here is not on the developers but on Windows which lacks support for a lot of great APIs available in Linux/MacOS.

> https://github.com/lordmulder/LoggingUtil

mintty isn't a console application.

**Comment by LigH-de** [comment]
But the shell which is hosted by mintty should be – I wonder if it may be possible to wrap it. Or maybe @lordmulder has another idea...

**Comment by wiiaboo** [comment]
That's what was being done before. Mintty called script which called the scripts and logged them. I might look into tee instead, but if as is works fine, it's low priority.

**Comment by LigH-de** [comment]
I do remember, tee was quite the minimal console output splitter. May depend on its behaviour with both stdout and stderr.
