### ISSUE TITLE
MSYS2 update removes script.exe

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#945]
Reported in https://github.com/Alexpux/MINGW-packages/issues/4497

After the update ran, the following compile script aborts with:
```
H:\development\media-autobuild_suite-master\msys64\usr\bin\script.exe: Exit 126.
Failed to run 'H:\development\media-autobuild_suite-master\msys64\usr\bin\script.exe': No such file or directory
```

No **script.exe** exists anymore below **msys64/usr**.

**Comment by schmidthubert** [comment]
I'm starting to get VERY pissed off now of the almost daily changes of MSYS2 and the impaired quality, functions in glib2 missing etc. Also looking at the meson project with tons of open PR's and issues it will take weeks if not months until they will probably make it to MSYS2. I think I'll stop my pacman from updating and freeze my installation now (will just add the meson update Ricardo provided) and then that's it. This is really unbelievable, what's is going on over there? It used to be VERY stable+reliable, but now it is starting to consume to much time to trace back all the problems we encounter almost daily here ... :-1:

**Comment by wiiaboo** [comment]
One issue about it is enough.
