### ISSUE TITLE
Signature update failed,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#946]
Signature update failed due to my desktop firewall and since then I get:
> error: abrepo: signature from "Ricardo Constantino <wiiaboo@gmail.com>" is unknown trust

-> how to redownload and fix the signature?

**Comment by wiiaboo** [comment]
Can you do a `pacman-key --list-sigs` in mintty?

**Comment by wiiaboo** [comment]
Can you try `pacman-key --lsign AE4FF531`?

**Comment by wiiaboo** [comment]
That doesn't have to do with the firewall.
Do `pacman-key --init` then and try the other two commands again. I assumed pacman would have already done that on the first run, but I guess not.

**Comment by Selur** [comment]
`pacman-key --init`
gives me:
```
$ pacman-key --init
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: Generating pacman keyring master key...
gpg: can't connect to the agent: IPC connect call failed
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
gpg: Done
==> Updating trust database...
gpg: no need for a trustdb check
```
(didn't run the other two since it seemed like that should have output something else,..)

**Comment by Selur** [comment]
No clue, but that seems to have fixed the issue.
Thanks.

**Comment by schmidthubert** [comment]
>I find it weird no one else complained about it either.

My stuff is modified so I apply all your patches manually. And this one wasn't necessary yet. Or better I WAS still hoping the problems we have would be fixed upstream soon enough. :tired_face:

**Comment by rjia** [comment]
> Open msys64/etc/pacman.conf and add the line `SigLevel = Never` below `[abrepo]` and then try doing `pacman -Syu`.
> I find it weird no one else complained about it either.

I experienced the exact same issue when building in a Windows 10 1803 VM with Parallels Desktop 14. However, the build proceeds without problem when I switched to a PC running Windows 10 1803 under the same network.

**Comment by Kagami** [comment]
I had same issue, `pacman-key --lsign AE4FF531` helped. It asked me to add that key, but for some reason didn't sign it. Seems like you need to do it manually.

**Comment by wiiaboo** [comment]
Maybe I should just nuke that whole part of the code. When/If I ever do a own repo in the future, I'll consider a more robust solution.
