### ISSUE TITLE
libavfilter / libdav1d compile errors

### ISSUE THREAD

**Issue by masterkivat** [jb-alvarado/media-autobuild_suite#947]
![libav-libdav1d](https://user-images.githubusercontent.com/43658221/46406793-16f79400-c6e3-11e8-9a70-1af0fa4d62f6.png)
[sY3z.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2441730/sY3z.zip)

**Comment by wiiaboo** [comment]
Broken upstream, should be temporarily fixed by using a previous commit: 9581fd3
