### ISSUE TITLE
fontconfig keeps failing to build

### ISSUE THREAD

**Issue by gnucian** [jb-alvarado/media-autobuild_suite#948]
I've been running the m-a_s over the last week and it keeps failing to build fontconfig with the following error message everytime I run it.

```
┌ fontconfig git.................................... Recently updated
├ Running uninstall...
├ Running autogen...
├ Running configure...
├ Running make...
├ Running install...
Likely error:
libtool: install: /usr/bin/install -c .libs/libfontconfig.lai /local64/lib/libfontconfig.la
libtool: install: /usr/bin/install -c .libs/libfontconfig.a /local64/lib/libfontconfig.a
/usr/bin/install: cannot remove '/local64/lib/libfontconfig.a': Device or resource busy
make[3]: *** [Makefile:560: install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make[2]: *** [Makefile:768: install-am] Error 2
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make[1]: *** [Makefile:762: install] Error 2
make[1]: Leaving directory '/build/fontconfig-git/build-64bit/src'
make: *** [Makefile:575: install-recursive] Error 1
install failed. Check C:/Utilities/ffmpeg/build/fontconfig-git/build-64bit/ab-suite.install.log
This is required for other packages, so this script will exit.
```

I always update the m-a_s script before I run it but it doesn't prove to be of help.
How can I solve this issue?

FYI, the logs file is also auto-uploaded by the script to [logs.zip](https://0x0.st/sYII.zip).
Can someone please tell me if this is an upstream issue or applies only to me?
Thanks in advance.

**Comment by schmidthubert** [comment]
C:\Utilities\ffmpeg\msys64\mingw64\bin\ranlib.exe: unable to rename 'C:/Utilities/ffmpeg/local64/lib/libfontconfig.a'; reason: File exists
/usr/bin/install: cannot remove '/local64/lib/libfontconfig.a': Device or resource busy

Did you try to manually delete this file? That's from your logs ...

**Comment by gnucian** [comment]
No.

I deleted the whole folder after I had a similar problem with building **curl** and put the most recent m-a_s files in the folder and tried building again. But I still have a similar problem with **fontconfig** now.

I have no idea why I keep getting the **'Device or resource busy'** error message. I do nothing on the computer while the script tries building the whole packages.

**Comment by gnucian** [comment]
I think I figured out why.

It's most probable that McAfee is the culprit. After I disabled the **real-time scan function of McAfee**, the problem is gone.

Sorry about the confusion.

**Comment by schmidthubert** [comment]
Yes, always make an exception for locations of which you know they're good. :+1:
