### ISSUE TITLE
libaom 1.0.0-729-ged7d0d090 is buggy

### ISSUE THREAD

**Issue by gnucian** [jb-alvarado/media-autobuild_suite#954]
I know this is an upstream problem, but I think I need to report this.

Currently, m-a_s builds AV1 standalone binaries and libaom-av1 wrapper using libaom ver. 1.0.0-729-ged7d0d090. After some testing, I found out that this version is buggy and fails to decode/encode AV1 streams.

Converting an rav1e encoded IVF video stream to the webm/mkv format using FFmpeg fails because libaom-av1 fails to read the AV1 stream correctly. Likewise, libaom-av1 encoder of FFmpeg fails and stops at the start of the process.

For comparison, I downloaded Zeranoe's FFmpeg (20181007-0a41a8b(N-92132-g0a41a8bf29), 64-bit, static) and succeeded in decoding/encoding/muxing AV1 streams without any issues. Its libaom version is 1.0.0-691-gbb8157b89.

**Comment by wiiaboo** [comment]
Well, you'd need to disable libvpx to get a newer libaom. Or really press upstream to fix this. There's no other way.

c.f. https://github.com/jb-alvarado/media-autobuild_suite/issues/951

**Comment by wiiaboo** [comment]
Also, zeranoe works because it's using an even older version.

**Comment by gnucian** [comment]
I see. Thank you for the answer.

**Comment by wiiaboo** [comment]
At most I can clamp to the same version until they fix upstream.

**Comment by gnucian** [comment]
I'd greatly appreciate it if you could do so. I can't forsake libvpx for libaom for now because there's no other alternative to libvpx on Windows that I can think of now. (Other than YouTube, of course.) The libaom build is of no use and just a piece of junk as it is now.

**Comment by gnucian** [comment]
Hi.

m-a_s successfully builds the same version libaom-av1 as Zeranoe, but those two libaom-av1's yield different results. While Zeronoe's libaom-av1 succeeds in decoding, m-a_s version does not. Please see this screenshot:

![same_libaom-av1_different_results](https://user-images.githubusercontent.com/3157518/46785613-25e3d500-cce7-11e8-85a5-d63f84f7c1ac.png)

I have no idea why this happens. I think I'll have to put up with this for now until the upstream problem is fixed.

Thank you.

**Comment by gnucian** [comment]
Hi,

Thanks for your reply.

Am I supposed to add `-DCONFIG_LOWBITDEPTH=0` or `-DCONFIG_LOWBITDEPTH=1` in aom_options.txt? I'm a little confused. Is the suite using 1 or 0?

**Comment by gnucian** [comment]
Hi.

Thanks for your advice. However, the `-DCONFIG_LOWBITDEPTH=0` option in `\build\aom_options.txt` does not solve the problem. Per your advice, I guess I need to ask Zeranoe about this.

![aom_built_with_aom_options txt](https://user-images.githubusercontent.com/3157518/46847152-c09bec80-cd97-11e8-8189-82b1bd23da8d.png)

![same_aom_different_results](https://user-images.githubusercontent.com/3157518/46847155-c4c80a00-cd97-11e8-8280-d3a1cb7eaaf2.png)

Thank you again.
