### ISSUE TITLE
Clean install - key not found and build stops at fontconfig

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#958]
Hey there,
I recently changed to Windows 10. I therefore started with a clean install.
It does not work. I don't know why...

```
        Starting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat

        Starting 64bit compilation of global tools
error: abrepo: key "EFD16019AE4FF531" is unknown
error: key "EFD16019AE4FF531" could not be looked up remotely
  Running git update for freetype2...
freetype2 git ............................................. [Up-to-date]
  Running git update for fontconfig...
┌ fontconfig git .................................... [Recently updated]
error: abrepo: key "EFD16019AE4FF531" is unknown
error: key "EFD16019AE4FF531" could not be looked up remotely
Installing python2-lxml... failed
Installing python2-six... failed
├ Running autogen...
├ Running configure...
├ Running make...
Likely error:
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/fontconfig'
Making all in fc-blanks
make[2]: Entering directory '/build/fontconfig-git/build-64bit/fc-blanks'
  GEN      fcblanks.h
/bin/sh: /mingw64/bin/python2: No such file or directory
make[2]: *** [Makefile:596: fcblanks.h] Error 1
make[2]: Leaving directory '/build/fontconfig-git/build-64bit/fc-blanks'
make[1]: *** [Makefile:579: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-64bit'
make: *** [Makefile:463: all] Error 2
make failed. Check D:/AB-Suite/build/fontconfig-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
error: abrepo: key "EFD16019AE4FF531" is unknown
error: key "EFD16019AE4FF531" could not be looked up remotely
error: abrepo: key "EFD16019AE4FF531" is unknown
error: key "EFD16019AE4FF531" could not be looked up remotely

Attach D:\AB-Suite\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```
[logs.zip] (https://github.com/jb-alvarado/media-autobuild_suite/files/2477943/logs.zip)

**Comment by schmidthubert** [comment]
I've just tried *MY* updater which still on line 65 contains 
`pacman-key --init`
so I removed Ricardos key first and then manually went through it again adding it manually as per the updater without -q switches but *including* the now missing line and it imported Ricardos key just fine. This line was removed in https://github.com/jb-alvarado/media-autobuild_suite/commit/7096c41618ce045ae6316171aa32f33f744a208c#diff-0f5b2e7b09d05ff6eeefdf9ca40ca742 so try adding that back and see if it works then, if not then wait for Ricardo to fix it ... :+1: 
![unbenannt](https://user-images.githubusercontent.com/26191502/46940674-908b6c80-d069-11e8-91e9-0dc101fb4c57.JPG)

**Comment by BlackScreen** [comment]
I added the line... Then I get - sorry it is in german - but the short version: not working.

```
gpg: fordere Schlüssel AE4FF531 von hkp-Server pool.sks-keyservers.net an
gpg: Schlüsselserver-Zeitüberschreitung
gpg: Empfangen vom Schlüsselserver fehlgeschlagen: Schlüsselserverfehler
==> FEHLER: Entfernter Schlüssel konnte nicht korrekt vom Schlüssel-Server abgerufen werden.
  -> Signiere Schlüssel AE4FF531 lokal...
==> FEHLER: AE4FF531 konnte nicht lokal signiert werden.

-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

Fehler: abrepo: key "EFD16019AE4FF531" is unknown
Fehler: key "EFD16019AE4FF531" could not be looked up remotely
:: Synchronisiere Paketdatenbanken...
 abrepo                  1829,0   B  0,00B/s 00:00 [#####################] 100%
 abrepo.sig               566,0   B  0,00B/s 00:00 [#####################] 100%
Fehler: abrepo: key "EFD16019AE4FF531" is unknown
Fehler: key "EFD16019AE4FF531" could not be looked up remotely
Fehler: Konnte abrepo nicht aktualisieren (Ungültige oder beschädigte Datenbank(PGP-Signatur))
 mingw32 ist aktuell
 mingw64 ist aktuell
 msys ist aktuell
Fehler: Fehler beim synchronisieren aller Datenbanken
Fehler: abrepo: key "EFD16019AE4FF531" is unknown
```

**Comment by schmidthubert** [comment]
I'm getting a ping to that server of up to 345ms, I'm using different servers from different locations in Germany to test, bad day maybe? What do you get if you run ` pacman-key --init && pacman-key --recv-keys AE4FF531` in the shell? You can also increase the timeout in `/etc/pacman.d/gnupg/gpg.conf` and try to change to a different server in that file, check here: https://sks-keyservers.net/overview-of-pools.php.  And looking at that page: maybe it's your firewall/virusscanner etc blocking port 11371? Run `telnet pool.sks-keyservers.net 11371`  in Windows and msys shells and check if you can get there at all ...

**Comment by BlackScreen** [comment]
```
$ pacman-key --init && pacman-key --recv-keys AE4FF531
gpg: requesting key AE4FF531 from hkp server pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
==> ERROR: Remote key not fetched correctly from keyserver.
```

```
$ telnet pool.sks-keyservers.net 11371
Trying 176.9.31.215...
Connection failed: Connection timed out
Trying 24.134.103.65...
Connection failed: Connection timed out
Trying 74.50.54.68...
Connection failed: Connection timed out
...
```
I increased the time in the config file from 10 to 1000. No change.
Blocked by the firewall probably? Is there something different in Windows 10?

**Comment by BlackScreen** [comment]
Thanks for your help. "hkp://pool.sks-keyservers.net:80" did the trick for me. Running the suite now again.

**Comment by kieranjol** [comment]
I had the same issue - just for anyone else who might need to do this step manually:
* open the mingw64.exe file in the `msys64` folder
* type `start /etc/pacman.d/gnupg/gpg.conf` in the terminal
* This will most likely prompt you to open the file with a text editor
* edit the file so that the url changes to `hkp://pool.sks-keyservers.net:80`
