### ISSUE TITLE
gnutls compiling error

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#960]
┌ gnutls git ........................................ [Recently updated]
├ Running bootstrap...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./bootstrap
No gtk-doc support found. You can't build the docs.
./bootstrap: Bootstrapping from checked-out gnutls sources...
./bootstrap: consider installing git-merge-changelog from gnulib
./bootstrap: getting gnulib files...
error: pathspec 'gnulib' did not match any file(s) known to git
bootstrap failed. 
https://0x0.st/sELu.zip

ab-suite.bootstrap.log>>>
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./bootstrap 
No gtk-doc support found. You can't build the docs.
./bootstrap: Bootstrapping from checked-out gnutls sources...
./bootstrap: consider installing git-merge-changelog from gnulib
./bootstrap: getting gnulib files...
error: pathspec 'gnulib' did not match any file(s) known to git

**Comment by wiiaboo** [comment]
Try again, the error is in retrieving git submodules, nothing to do with the suite.

**Comment by kliffgomel** [comment]
not working for me
https://0x0.st/sE0Y.zip

**Comment by wiiaboo** [comment]
Have you tried deleting the gnutls directory?

**Comment by kliffgomel** [comment]
Yes of course. And a clean install too.

**Comment by wiiaboo** [comment]
Well, maybe you're on a restricted network which doesn't let you download gnulib. Try a VPN.

**Comment by kliffgomel** [comment]
If there were any problems in my network with access to github/gnulib, then I would not be able to get other libraries. Once again I tried a clean installation from scratch with ffmpegChoice = 4, the problem repeats.
https://0x0.st/s6zL.zip

**Comment by wiiaboo** [comment]
It depends. Gnulib is retrieved from GnuTLS's gitlab instance.
Try doing `git submodule init --update` manually with a clean git clone of gnutls.

**Comment by wiiaboo** [comment]
Could you try doing a manual `git submodule update --init` inside a clean git clone of gnutls?
Maybe you can't access GnuTLS's gitlab instance where gnulib is hosted on.

**Comment by wiiaboo** [comment]
Could you try doing a manual `git submodule update --init` inside a clean git clone of gnutls?
Maybe you can't access GnuTLS's gitlab instance where gnulib is hosted on.

**Comment by kliffgomel** [comment]
I can get a copy of the https://gitlab.com/gnutls/ repository and submodules without any problems. Also without problems, I can build a project with ffmpegChoice = 3.

**Comment by wiiaboo** [comment]
Could you remove the submodules directories and try a manual `./bootstrap` then? That's weird.
The error doesn't happen on my side.

**Comment by wiiaboo** [comment]
Could you try doing a manual `git submodule update --init` inside a clean
git clone of gnutls?
Maybe you can't access GnuTLS's gitlab instance where gnulib is hosted on.
