### ISSUE TITLE
mpv not able to play av1 files anymore

### ISSUE THREAD

**Issue by jane1969** [jb-alvarado/media-autobuild_suite#962]
With latest commit reverting previous libaom clamping commit, the resulting mpv cannot play any av1 file (from https://www.elecard.com/videos for example) using libaom-av1. The video can be played using libdav1d decoder, but performance is even worse than it used to be with libaom.
Build of mpv from shinchiro of october 14th works, and there does not seem to be any mpv commit since this date that might have broken the feature.

Mpv log is not very explicite:

[vd] Codec list:
[vd]     libaom-av1 (av1) - libaom AV1
[vd]     libdav1d (av1) - dav1d AV1 decoder by VideoLAN
[vd] Opening decoder libaom-av1
[vd] No hardware decoding available for this codec.
[vd] Using software decoding.
[vd] Requesting 12 threads for decoding.
[ffmpeg/video] libaom-av1: 1.0.0-782-g1996a35dc
[vd] Selected codec: libaom-av1 (libaom AV1)
[vf] User filter list:
[vf]   (empty)
Starting playback...

and then nothing after, the program shuts itself.

Thanks.

**Comment by LigH-de** [comment]
The media-autobuild_suite builds them. If an executable was created with all desired libraries linked, it was successful. If using one of them fails, don't blame the suite; that's a case for the issue tracker of this project (mpv).

**Comment by jane1969** [comment]
Yes, of course. The issue may also come from aomedia-av1 and need to be fixed upstream.
I just intended to signal the problem as it can sometimes be useful to clamp to a working version until things are settled.
Anyway, it is of no importance as av1 encoded videos still are for test purpose and very uncommon so far.

**Comment by LigH-de** [comment]
I just built again, and mpv can play my small AV1 test video as well as a larger video I just downloaded from the YouTube AV1 beta playlist (checked twice that youtube-dl used an "av01" video stream format).

No issues for me right now.

**Comment by wiiaboo** [comment]
If you can't tell me what was the latest working commit, I'm not going to investigate it myself either, so this issue is useless.

**Comment by wiiaboo** [comment]
Also, mpv is not at all responsible for broken decoding, it's using FFmpeg as backend for 99% of the brunt work. So the issue would come from FFmpeg wrapper of libaom or from libaom itself.

**Comment by jane1969** [comment]
I found time to investigate more thoroughly into the issue. The culprit is libdav1d. Removing this lib from the "common external libs" in "media-autobuild_suite.bat" solves the problem. I understand it was disabled by default for reason, because it was unstable, but did not suspect that enabling this decoder would also break av1 playing with liabaom-av1. It is unexpected, and what is even weirder is that libdav1d works even if very slow.
I can also confirm that the issue does not come from mpv as neither ffplay nor ffmpeg can read av1 files when compiled with dav1d support. So it has to do with ffmpeg or libaom-av1.
Thanks for everything.

**Comment by easyfab** [comment]
It should  be ok now to have libdav1d + libaom after https://code.videolan.org/videolan/dav1d/commit/c163cbdb8360847b22ab4f0fbd6c7a5723af7bdf

For me it works now with ffmpeg ( -c:v libdav1d ) and with mpv (--vd=libdav1d ).
but I don't know how to change framethreads and tilethreads with mpv ( I changed the default in libdav1d.c for the moment )
