### ISSUE TITLE
Error on libmediainfo

### ISSUE THREAD

**Issue by brucedk** [jb-alvarado/media-autobuild_suite#966]
Hello guys, I'm having an issue on libmediainfo compiling, here are the logs: https://0x0.st/sIzg.zip

thanks

**Comment by wiiaboo** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/issues/920

**Comment by brucedk** [comment]
My mistake, in that time I have to re-build all over again form the start... Thanks
