### ISSUE TITLE
libbluray fails

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#97]
posted the log as far as it was available to: https://paste.ee/p/cRljC
ffmpeg_options i use:
>--enable-librtmp --enable-gnutls --enable-frei0r \
--enable-libbluray --enable-libcaca --enable-libopenjpeg --enable-libass --enable-libgsm \
--enable-libilbc --enable-libmodplug --enable-libmp3lame \
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger \
--enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis \
--enable-libvo-aacenc --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid \
--enable-libzvbi --enable-libdcadec --enable-libbs2b \
--enable-decklink --enable-libutvideo --enable-libgme

my media-autobuild_suite.ini:
> [compiler list]
msys2Arch=2
arch=1
free=2
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
mplayer=1
mpv=2
mkv=1
cores=8
deleteSource=1
strip=1
pack=2

https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=1453 might help

**Comment by wiiaboo** [comment]
Delete libblurray-git and try again.

**Comment by Selur** [comment]
that helped,..

**Comment by Selur** [comment]
Argh, now mkvtoolnix fails:
https://paste.ee/p/kSGE2
deleted the mkvtoolnix-git, but that didn't help 64bit version still failed,..

**Comment by wiiaboo** [comment]
https://github.com/mbunkus/mkvtoolnix/commit/01ad2ca2e353f0bfb8e9fd465d450c6cd5f585c4

Try again now. It was a problem with upstream.

**Comment by Selur** [comment]
works now
