### ISSUE TITLE
mplayer build failed . maybe -Werror?

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#971]
┌ mplayer svn .......................................... [Updates found]
├ Running distclean...
├ Running configure...
├ Running install...
Likely error:

In file included from libavformat/internal.h:28,
                 from libavformat/3dostr.c:23:
libavformat/os_support.h: In function 'win32_rename':
libavformat/os_support.h:221:6: warning: "HAVE_UWP" is not defined, evaluates to 0 [-Wundef]
 #if !HAVE_UWP
      ^~~~~~~~
make[1]: *** [ffbuild/common.mak:60: libavformat/3dostr.o] Error 1
make[1]: Leaving directory '/build/mplayer-svn/ffmpeg'
make: *** [Makefile:740: ffmpeg/libavformat/libavformat.a] Error 2
install failed. 

Check C:/Users/kuh3h/Downloads/media-autobuild_suite/build/mplayer-svn/ab-suite.install.log
This isn't required for anything so we can move on.

**Comment by LigH-de** [comment]
You should have read during the configuration of MABS that wiiaboo doesn't care about mplayer; I have this issue too, for several weeks now, but I was afraid to post it here, not to risk any anger reactions... :sweat_smile: 

More or less nobody cares about mplayer anymore. I opened a [trac ticket](http://trac.mplayerhq.hu/ticket/2350). I asked in their IRC channel. One user (with Linux base) tested it but could not help me with the MSYS2 specific variation of this error.

It seems to be somewhat related to a redefinition of 'struct pollfd', despite having a constant HAVE_STRUCT_POLLFD defined, and this struct si defined in winsock2.h as well as os_support.h (and this is the threshold of my insight).

**Comment by wiiaboo** [comment]
I don't get angry, I just don't care the least about mplayer or ffmbc and there's no developer from those projects coming here to read about issues, so there's absolutely no use posting about them here.

**Comment by LigH-de** [comment]
I got a message with a theory, which I will forward to the mplayer trac, but I doubt it will be considered...

»In winsock2.h the pollfd is defined inside `#if (_WIN32_WINNT>=0x0600)`
For me it (/usr/share/mingw-w64/include/_mingw.h) is _WIN32_WINNT=0x502. I guess it's 0x0600 or higher for you. So... patch mingw header, or add -D_WIN32_WINNT=0x502 to --extra-cflags='...'. Or fix mplayer's ./configure to actually check if pollfd is defined by <winsock2.h>.«

**Comment by LigH-de** [comment]
I would like to test [this proposed patch](http://lists.mplayerhq.hu/pipermail/mplayer-dev-eng/2018-November/073746.html); can anyone help me learning how to apply an additional patch in MABS easily?

**Comment by kuh3h3** [comment]
LigH-de i `ve tested Reimar Döffinger`patch.
compile ok, run ok

i don`t know hwo to apply the patch in MABS.
so applied manually in mintty and run configure

./configure --prefix=/local64 --bindir=/local64/bin-video --cc=gcc --extra-cflags="-DPTW32_STATIC_LIB -O3 -std=gnu99 -DMODPLUG_STATIC" --extra-libs="-llzma -liconv -lws2_32 -lpthread -lwinpthread -lpng -lwinmm" --extra-ldflags="-Wl,--allow-multiple-definition" --enable-static --enable-runtime-cpudetection --disable-gif --disable-cddb --with-dvdread-config="/mingw64/bin/pkg-config --static dvdread" --with-freetype-config="/mingw64/bin/pkg-config --static freetype2" --with-dvdnav-config="/mingw64/bin/pkg-config --static dvdnav"
make
make install

check  working mplayer
https://i.imgur.com/VuKbJuG.png

**Comment by wiiaboo** [comment]
Save the mail's contents to a .diff file and try to apply it with `do_patch stuff.diff` while inside mplayer's repo directory. If it works, I can add it. You only need the lines after `index 80d18edfb..d1aa8cdf2 100755` and until before `--` (before the git version).

Here's how to do it in the shell: 
```bash
# cd to mplayer-svn
cd "$LOCALBUILDDIR"/mplayer-svn

# get patch from mplayer-dev and save it to `fixpollfd.diff`
curl -o fixpollfd.diff -s "http://lists.mplayerhq.hu/pipermail/mplayer-dev-eng/2018-November/073746.html"

# trim it to only contain the diff itself
sed -inE '/^--- /,/^--/p' fixpollfd.diff

# delete the last line
sed -i '$d' fixpollfd.diff

# apply it (use --dry-run to test it first)
patch -p1 -N < fixpollfd.diff
```

This worked for me even with non-gnu sed on macOS, which is shittier than GNU's.

When submitting a PR for it, you could upload the trimmed version to 0x0.st or somewhere that lets you download the raw text and then you just need `do_patch https://0x0.st/sGma.diff` before running mplayer's configure.

**Comment by LigH-de** [comment]
I could apply the patch from a temporary upload on my server. Building finishes without errors.

**Comment by LigH-de** [comment]
The patch `fixpollfd.diff` appears to be obsolete now.
