### ISSUE TITLE
Feature request: BAT launch with parameters

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#973]
Hi,

I suggest one improvement for a more user-friendly use.
In any case, it's a suggestion. Forget it if you feel it's irrelevant:

- Add support for a parameter to initiate specific actions. For example:
 . `.\media-autobuild_suite.bat /compile-only`

The idea is to not manually require to start ".sh" scripts in MinTTY (or other supported console) to launch specific actions. And why? Because it's quite confusing and it's not clear what does each script. So, with this approach all is centralized inside the .BAT script.

What you think?

**Comment by wiiaboo** [comment]
They're needed for logging. Find another way of having proper logs, user-friendly colors and proper console fonts and I'll accept the PR.
