### ISSUE TITLE
Suggestion: script to auto-update the build suite

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#976]
Hi,

As Windows doesn't have (as default) the wget tool, it will be useful to have one simple script that uses the current environment to update the build suite. So, we don't need to download the `MASTER.ZIP` and extract it manually.

What you think?

**Comment by wiiaboo** [comment]
I think you missed [that option](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-autobuild_suite.bat#L1026-L1048) when running the .bat. It's been there for years.
It creates a file in the root of the suite that you drag onto the mintty shortcut and it updates the suite itself.
