### ISSUE TITLE
standalone rav1e compilation fails on proc-macro-hac (experimental feature)

### ISSUE THREAD

**Issue by Murmur** [jb-alvarado/media-autobuild_suite#979]
One week ago 2018-11-08 able to compile `bin-video/rav1e.exe`. Today an error I think something to do with rustc-stable and rustc-nightly experimental code support in a `proc-macro-hack-0.5.1` source.

My fix for the time being was editing `build/media-autobuild_suite.ini` flag to rav1e=0 value. Then running media-autobuild_suite.bat script was able to build ffmpeg and mp4box I was trying to update this time.

[logs.zip](https://0x0.st/slnY.zip)

```
┌ rav1e git ......................................... [Recently updated]
├ Running submodule...
├ Running build...
Likely error:
    |
130 |     syn::custom_keyword!(export);
    |     ^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro-hack`.
warning: build failed, waiting for other jobs to finish...
error: build failed
build failed. Check C:/projects/media-autobuild_suite/media-autobuild_suite/build/rav1e-git/ab-suite.build.log
This is required for other packages, so this script will exit. Creating diagnostics file...
All relevant logs have been anonymously uploaded to https://0x0.st/slnY.zip
Copy and paste [logs.zip](https://0x0.st/slnY.zip) in the GitHub issue.

RUN rustc COMMAND in a build/rav1e-git folder
$ cd build/rav1e-git
$ rustc --explain E0658
An unstable feature was used.
Erroneous code example:

#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).
If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:
#![feature(repr128)]
#[repr(u128)] // ok!
enum Foo {
    Bar(u64),
}

https://github.com/dtolnay/proc-macro-hack/blob/0.5.1/src/lib.rs
https://github.com/dtolnay/proc-macro-hack/blob/master/src/lib.rs
```

**Comment by wiiaboo** [comment]
Report to upstream. I don't know Rust.

**Comment by easyfab** [comment]
the error message is :
CMake Error at CMakeLists.txt:60 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

I think it's since https://github.com/jb-alvarado/media-autobuild_suite/commit/05eec874c69973b68d978eed088af4974cd3cc05 or https://github.com/jb-alvarado/media-autobuild_suite/commit/a7c4510b450a94feab6e822b61412e441a3bd4af

**Comment by wiiaboo** [comment]
Rust doesn't have CMake so this is the completely wrong issue to comment on.

**Comment by easyfab** [comment]
I don't know, perharps the error is when building the submodule with aom.
Is the submodule still needed ?

**Comment by wiiaboo** [comment]
No idea, ask upstream.

**Comment by Murmur** [comment]
@wiiaboo How do you update `media-autobuild_suite\msys64\opt\cargo and rustc` tools? Do you download ready-to-use binaries and bundle together?

Upstream instructs to update to the latest rustc stable release. I have `rustc --version   1.29.0` binary.

https://github.com/rust-lang/rust/blob/master/RELEASES.md  version 1.30.0

**Comment by wiiaboo** [comment]
The update script already runs `rustup update` so it should've updated on its own.

**Comment by Selur** [comment]
update script didn't update rust here, had to run it manually like suggested from Murmur to get rav1e compiling working again

**Comment by Murmur** [comment]
I had one remaining issue, 32bit rav1e was compiling fine but 64bit rav1e kept failing. I did the following `cargo` trick told by the upstream devs in a related issue. No idea what cargo update+build does. Both 32bit and 64bit compiled fine. 

```
Run Mintty console. 
$ ./update_suite.sh
$ cd /build/rav1e-git
$ /opt/cargo/bin/cargo update
$ /opt/cargo/bin/cargo build
$ exit 
Run media-autobuild_suite.bat script.
```

**Comment by LigH-de** [comment]
Upstream may have fixed something... still, building the updated cargo package fails for me:

```
Entwicklung@MARIO3 /trunk
$ cd /build/rav1e-git/
Entwicklung@MARIO3 /build/rav1e-git
$ /opt/cargo/bin/cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/tdaede/nasm-rs.git`
Entwicklung@MARIO3 /build/rav1e-git
$ /opt/cargo/bin/cargo build
   Compiling proc-macro2 v0.4.24
   Compiling unicode-xid v0.1.0
   Compiling winapi-i686-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.6
   Compiling num-traits v0.2.6
   Compiling rand_core v0.3.0
   Compiling unicode-width v0.1.5
   Compiling rustc-demangle v0.1.9
   Compiling cfg-if v0.1.6
   Compiling bitflags v1.0.4
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling rav1e v0.1.0 (file:///H:/development/media-autobuild_suite-master/build/rav1e-git)
   Compiling libc v0.2.43
   Compiling bitstream-io v0.8.1
   Compiling y4m v0.3.1
   Compiling textwrap v0.10.0
   Compiling rand_core v0.2.2
   Compiling quote v0.6.10
   Compiling syn v0.15.21
   Compiling atty v0.2.11
   Compiling backtrace v0.3.9
   Compiling rand v0.5.5
   Compiling clap v2.32.0
   Compiling proc-macro-hack v0.5.2
error[E0658]: non-ident macro paths are experimental (see issue #35896)
   --> H:/development/media-autobuild_suite-master/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro-hack-0.5.2\src\lib.rs:260:5
    |
260 |     syn::custom_keyword!(support_nested);
    |     ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro-hack`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It seems that compiling unstable extensions has to be enabled explicitly by updating to a nightly build of rust by using rustup.

**Comment by wiiaboo** [comment]
I'd prefer not using nightly rust. It probably needs too frequent updates to not be annoying.

**Comment by LigH-de** [comment]
Then your alternative may be to clamp rav1e until it builds with a stable rust version again... not optimal either, but maybe less hassle. Said the Hoff.
