### ISSUE TITLE
feature request: bring back old x265-16bit.exe

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#98]
Would be nice if there would be an option to set whether libx265_main10.dll was build or if a static x265-16bit.exe was build.

**Comment by wiiaboo** [comment]
Any specific reason why? x265.exe with libx265_main10.dll has option to both encode to 8 and 10-bits.

**Comment by Selur** [comment]
Same reason why I like ffmpeg and all the other tools statically linked:
For me dynamically linked tools, on Windows, just cause trouble in the long run.
 
Also, when ffmpeg -> 'Include non-free libraries' was set to 'No' and 'Choose ffmpeg optional libs' + 'Yes' was selected the ffmpeg_options.txt should not contains non-free libraries.

Reading:
> Edit it now or leave it unedited to compile according to defaults.

scares me a bit, since if one distributes non-free libraries one can get in a world of trouble,...

**Comment by wiiaboo** [comment]
ffmpeg_options can contain non-free libraries.
If "non-free" is selected in the bat, it won't compile non-free libraries or include them in FFmpeg.
You can check what's compiled inside FFmpeg just by running it and checking the first lines.

I'll add an option to x265 to select between separate exes and the dll.

**Comment by Selur** [comment]
> I'll add an option to x265 to select between separate exes and the dll.
Thanks
