### ISSUE TITLE
dav1d error- although deactivated

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#980]
I got an error today that ffmpeg building failed at something related to dav1d.
In the ini I have deactivated it completely. It also is building since a few days, for some reason...
[logs.zip] (https://0x0.st/slRK.zip)

**Comment by BlackScreen** [comment]
Building working again, but still building dav1d...

```
  Running git update for dav1d...
┌ dav1d git ............................................ [Updates found]
├ Running uninstall...
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ dav1d-git .................................................. [Updated]
```

**Comment by wiiaboo** [comment]
Well, do you have `--enable-libdav1d` on ffmpeg_options.txt or are you using default presets of FFmpeg configurations?

**Comment by wiiaboo** [comment]
That doesn't tell me anything. If you wanted to make have to open the .zip you might've just said so.
You have `--enable-libdav1d` since you're using a default preset. Case closed.
