### ISSUE TITLE
 tesseract not found using pkg-config but still present

### ISSUE THREAD

**Issue by ASopH** [jb-alvarado/media-autobuild_suite#981]
deleted ffmpeg, tesseract and dav1d-git folders. Can't figure out how tesseract not present!

**Comment by ASopH** [comment]
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2596038/logs.zip)

**Comment by wiiaboo** [comment]
It's missing some dependency of libtiff. I'll only have time to look this up on the weekend.

**Comment by schmidthubert** [comment]
`do_addOption --extra-libs=-lzstd` :+1:

**Comment by LigH-de** [comment]
At which position? End of tesseract building block?

**Comment by schmidthubert** [comment]
That doesn't really matter here, it's global so you can put it on line 2 if you want, otherwise try line 411. And I didn't create a PR because Ricardo wanted to have a look at it. But it builds with this option ...

**Comment by LigH-de** [comment]
I changed line 432 and had success.

```
-do_addOption --extra-cflags=-fopenmp --extra-libs=-lgomp
+do_addOption --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-libs=-lzstd
```

**Comment by LigH-de** [comment]
Uhm, well, strange ... despite including this change in tesseract, the 32-bit build of mpv passes, but then the 64-bit build of mpv fails with the same kind of issue.

**Comment by LigH-de** [comment]
Works again.

**Comment by schmidthubert** [comment]
No problems here so far building mpv in both 32+64, I just checked. If mpv occasionally errors then I simply remove the build/mpv folder and then it compiles again.

**Comment by LigH-de** [comment]
There was an update in the meantime when I just built it again.

**Comment by BlackScreen** [comment]
I think the error is still present...
[logs.zip] (https://0x0.st/s0OH.zip)

**Comment by LigH-de** [comment]
Wrapping in single quotes seems to be the correct way to add several extra libraries. So I hope. I am not sure. But it builds this way.

build/media-suite_compile.sh line 434:

```
-    do_addOption --extra-cflags=-fopenmp --extra-libs=-lgomp
+    do_addOption --extra-cflags=-fopenmp --extra-libs='-lgomp -lzstd'
```

**Comment by wiiaboo** [comment]
Force a recompilation of leptonica and that modification shouldn't be needed.
The issue is in libtiff's pkg-config file not having that needed dependency and that's how it should be fixed, not adding libs unnecessarily.
