### ISSUE TITLE
Error in the Final Compiling step i.e. FFmpeg 64bit (Windows 10 x64 1803 build 17134.407)

### ISSUE THREAD

**Issue by BUAWF** [jb-alvarado/media-autobuild_suite#983]
[If](https://0x0.st/sUkj.zip
[sUkj.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2602634/sUkj.zip)
For Any Detail info, You May check the logs Please.
I'm completely new to this.
Any Help would be Heartily appreciated.
Trying this since a Week, its always displaying that 1 Single Error all the time !!.
To be Honest, I only Need FFmpeg with libfdk_aac, thats it, Nothing else.

**Comment by wiiaboo** [comment]
If you only need fdk-aac, why are you also enabling libtesseract? Which is already known to be broken: https://github.com/jb-alvarado/media-autobuild_suite/issues/981

**Comment by BUAWF** [comment]
> If you only need fdk-aac, why are you also enabling libtesseract? Which is already known to be broken: #981

Please, how can I disable it ?

**Comment by wiiaboo** [comment]
Remove it from ffmpeg_options.txt and all other enables you don't need.

**Comment by BUAWF** [comment]
> Remove it from ffmpeg_options.txt and all other enables you don't need.
Love You, Love You & Love You.
Thanks alot Mate.
OMG !! It's Done....
Yaayyyyy..
God Bless You Dear And I Pray to God that You get Success in every step of Your Life.
Thanks once again.

**Comment by BUAWF** [comment]
@wiiaboo I've a .ts (audio only) with aac codec, I just want to copy it to .m4a via ffmpeg with fdkaac. How do I do that ? And that too in variable bitrate.

**Comment by wiiaboo** [comment]
If you want to just copy it without reencoding you don't even need fdkaac. Just use `-c:a copy` and it'll remux it into any container.

This isn't the FFmpeg user mailing list, so you can also ask there.

**Comment by BUAWF** [comment]
> If you want to just copy it without reencoding you don't even need fdkaac. Just use `-c:a copy` and it'll remux it into any container.
> 
Thanks Ricardo.
