### ISSUE TITLE
FFMPEG fails to compile in libavutil

### ISSUE THREAD

**Issue by maclauk** [jb-alvarado/media-autobuild_suite#985]
A brand new cloned today version of the suite failed to compile during FFMPEG.
[logs.zip](https://0x0.st/sGsp.zip)

I also tried a fresh version yesterday. Reason for starting fresh was a brand new hard drive and starting from a "clean" version of Win 7 Pro.

I also note that the initial download of wgetpack.exe failed just after selecting options both days. I was able to fix that myself by downloading the link in Chrome and unpacking myself to /build. Now looking at the code suspect that I don't have PowerShell installed is the problem. Anyway, side issue.

Console from the main FFMPEG failure :

  Running git clone for ffmpeg...
+ ffmpeg git ........................................ [Recently updated]
+ Changing options to comply to nonfree...
CUDA_PATH environment variable not set.
MSVC cl.exe not found in PATH or through vswhere.
Disabling libnpp/cuda-sdk.
+ Compiling static FFmpeg...
+ Running configure...
+ Running make...
Likely error:
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x22fb): undefined reference to `clGetExtensionFunctionAddressForPlatform'
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x22fb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `clGetExtensionFunctionAddressForPlatform'
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x2333): undefined reference to `clGetExtensionFunctionAddressForPlatform'
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x2333): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `clGetExtensionFunctionAddressForPlatform'
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x2417): more undefined references to `clGetExtensionFunctionAddressForPlatform' follow
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x2417): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `clGetExtensionFunctionAddressForPlatform'
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x244f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `clGetExtensionFunctionAddressForPlatform'
libavutil/libavutil.a(hwcontext_opencl.o):hwcontext_opencl.c:(.text+0x2487): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `clGetExtensionFunctionAddressForPlatform'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:108: ffmpeg_g.exe] Error 1
make failed. Check C:/Temp/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sGsp.zip
Copy and paste [logs.zip](https://0x0.st/sGsp.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Search the issues for the fix. Your OpenCL driver is too old.
