### ISSUE TITLE
gnutls  build failed. Requested 'nettle >= 3.4.1' but version of Nettle is 3.4

### ISSUE THREAD

**Issue by kuh3h3** [jb-alvarado/media-autobuild_suite#986]
┌ gnutls git ........................................... [Updates found]
├ Running uninstall...
├ Running bootstrap...
├ Running configure...
Likely error:
checking threads.h usability... no
checking threads.h presence... no
checking for threads.h... no
checking for getrandom... no
checking for getentropy... no
checking for nettle >= 3.4.1... no
configure: error:
  ***
  *** Libnettle 3.4 was not found.

configure failed. Check C:/Users/kuh3h/Downloads/media-autobuild_suite/build/gnutls-git/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sGbT.zip
Copy and paste [logs.zip](https://0x0.st/sGbT.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

================================

config.log
==============================
configure:10015: $? = 1
configure:10029: $PKG_CONFIG --exists --print-errors "nettle >= 3.4.1"
Requested 'nettle >= 3.4.1' but version of Nettle is 3.4

You may find new versions of Nettle at http://www.lysator.liu.se/~nisse/nettle

configure:10032: $? = 1
configure:10046: result: no
Requested 'nettle >= 3.4.1' but version of Nettle is 3.4

You may find new versions of Nettle at http://www.lysator.liu.se/~nisse/nettle
configure:10063: error: 
  ***
  *** Libnettle 3.4 was not found.

**Comment by cc5771027** [comment]
GunTLS Version 3.6.5 News (released 2018-12-01)
[](https://github.com/gnutls/gnutls/blob/4353ea025ae032887f3e8cf5aadace25662c6b35/NEWS#L21-L29)

**Comment by hydra3333** [comment]
yes, as of today, https://ftp.gnu.org/gnu/nettle/?C=M;O=D shows only nettle 3.4 as does https://fossies.org/linux/privat/

**Comment by wiiaboo** [comment]
There's nettle 3.4.1 in MINGW already.
