### ISSUE TITLE
Questions about Bat script.

### ISSUE THREAD

**Issue by 1480c1** [jb-alvarado/media-autobuild_suite#989]
Continuation of the previous line of question, why is it that only cyanrip2 in line 858 and 859 has "yes" and "no" instead of shorted y and n? I do noticed that you check for yes instead of the y in the compile.sh. Nothing really major affected by this, just wondering why.

**Comment by 1480c1** [comment]
I guess another question is should I limit the maximum amount of cores/threads for the cpu cores count question? Right now I have the max to be 99 because I doubt anyone would want to run more than 99 jobs on one computer.

**Comment by wiiaboo** [comment]
Correct. Same thing with try64.

**Comment by 1480c1** [comment]
Next major question, should I still include XP support (the x265 option 6)? Because xp does not have a powershell by default. And the latest I can download is 2.0, while the actual latest is 6.1, with the minimum of the script being 3.0 which is available on 7 and on 8 by default. Like should I keep it, or should I hide it ( still an option, just now shown in the list)?

**Comment by 1480c1** [comment]
I'm right trying to test to see if I can run the script, however, I will not be able to test a 64 bit installation due to my 64 bit xp pro iso not working even though I just ripped it from a dell cd.

**Comment by wiiaboo** [comment]
The script should not be expected to run on anything older than 8.1. The xp option is for the compiled binaries.
64-bit XP is a travesty that shouldn't have existed.

**Comment by 1480c1** [comment]
Okay, next, I looked through the bat script and the only time forceQuitBatch is mentioned outside of the question thing is in a if that is commented out. Is it necessary for me to include this?

**Comment by wiiaboo** [comment]
Probably not, that was a questionable workaround for a msys issue.

**Comment by 1480c1** [comment]
So, far, I'm stuck on running the update script because it keeps on saying that I'm missing mintty even though it's clearly installed. One thing I do note is that mintty does not show up in pacman -Qqe.  My current problem is that even though it runs the compile script, it seemingly does not run it properly when I try to circumvent using mintty even though everything else seems in order.

**Comment by 1480c1** [comment]
Even when I have mintty set as explicit using pacman -D --asexplicit --noconfirm mintty right before running the script, it still says its not installed.

**Comment by 1480c1** [comment]
Although another thing to note is that also happens when running the bat, so I'm looking in the update script right now to see if it somehow sets mintty as dep.

**Comment by 1480c1** [comment]
Also, I'm not exactly sure on how the licenses work since I've never had an interest in reading up on how GPL and LGPL work but can I include (7Zip4Powershell)[https://github.com/thoemmi/7Zip4Powershell] in the script? It's licenced as LGPL 2.1 while this suite is GPL 3.0. I've tried looking up if I can include a LGPL program/script within a GPL program/script but all the answers were just either look at the license or ask a lawyer and there were no clear answers.

**Comment by wiiaboo** [comment]
> Although another thing to note is that also happens when running the bat, so I'm looking in the update script right now to see if it somehow sets mintty as dep.

It's explicitely in the msyspackages list of packages, so it shouldn't be marked as dependency. By itself, it shouldn't ever be a dependency, since it's one terminal emulator, so nothing should ever depend on it.

You can include more liberal licensed programs or libraries inside GPL, yes.

**Comment by wiiaboo** [comment]
And yes, you can include 7zip4Powershell, as long as you don't have to install anything to get it. other than Powershell itself.

**Comment by 1480c1** [comment]
So far so good, only problem is that the pac-* files aren't being written properly by powershell and thus the update script is not reading them correctly, even through the ming($bit).sh is installing them properly. The other problem right now is that when circumventing mintty by running bash within powershell, powershell does not handle ascii colors properly and thus it shows `Γö£` and `[[311m` within the console (the logs generated both from mintty and powershell show the same thing though). Right now, I'm trying to figure out how to properly fix the writing of pac- files and trying to find a way to display the colors without a systemwide reg edit.

**Comment by 1480c1** [comment]
Update: I got the ├ to work, only problem now is the colors as powershell can't handle direct ascii colors like mintty does.

**Comment by 1480c1** [comment]
Uhh, I think this might be a problem, Leptonica `1.77.0  14 Dec 18... Renamed autobuild --> autogen.sh`
Line 410 of media-suite_compile.sh `[[ -f configure ]] || log autogen ./autobuild`
Might need to change this?

**Comment by 1480c1** [comment]
If anything, it seems to be nearly the exact same file except the third line having `# autogen.sh` instead of `# autobuild`

**Comment by 1480c1** [comment]
Actually, nevermind. Didn't see the new changes.

**Comment by wiiaboo** [comment]
There's RSS and and you can also Follow the repository.

**Comment by 1480c1** [comment]
I see, I've never had much of a problem when installing a few packages using pacman, but then again I've never installed the same amount of packages as the script does at one time.

**Comment by 1480c1** [comment]
Should I add in the option to have it automatically add the bin-video,bin-audio folders to path?
Meaning ask a question about adding the bin folders to the environment path with warnings about it and then checking if bin-video and bin-audio already exists in the path then splitting based on ; and replacing them with %instdir%\local%bit%\bin-video and bin-audio or if they don't exist in path, append them to path?
something like `[Environment]::SetEnvironmentVariable("Path", $env:Path + ";$PSScriptroot\local$($bit)\bin-video;$PSScriptroot\local$($bit)\bin-audio", [EnvironmentVariableTarget]::Machine)`

**Comment by 1480c1** [comment]
I do know that it will go against the "just delete the suite folder" idea of removing it, but I'm thinking that at least a notification of the existence of environment path would probably help for people who have little to no experience with console and just wanted to build ffmpeg with fdk with non-free license such as @ #999

**Comment by 1480c1** [comment]
Okay, I probably will add that instead.

**Comment by 1480c1** [comment]
So I see,
```
ffmpeg and apps that use it will depend on
%INSTALLDIR%/local64/bin-video/Processing.NDI.Lib.x64.dll to run!
```
Does that mean that ffmpeg will look for it in the same folder?
I'm trying to make sure which items I would need to copy over to a final directory.

**Comment by wiiaboo** [comment]
It needs to be on %PATH%, afaik. So it could be same directory or any other directory that's in %PATH%. If it were *nix, it'd use LD_LIBRARY_PATH or something.

**Comment by 1480c1** [comment]
I see, I'll just copy whatever is in the bin* folders along with the exe while keeping and sub folder structure. I'll just add a notification that it's up to the user to either add the end folder to path or set the final folder to a folder that's already in path.

**Comment by schmidthubert** [comment]
https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications

**Comment by 1480c1** [comment]
I guess also that way, anytime any of the dlls or executables have been updated, the forced copy will replace the old ones in the final directory.

**Comment by wiiaboo** [comment]
Which will fail if they're being used, so try to handle that, if possible. In *nix it works because executables don't get locked while being run.

**Comment by 1480c1** [comment]
I'm going to try to use <https://stackoverflow.com/questions/24992681/powershell-check-if-a-file-is-locked> and <https://beamusupscotty.wordpress.com/2012/11/14/use-powershell-to-find-out-which-process-locks-a-file/> to try to make sure that the files are not in use before copy.

**Comment by 1480c1** [comment]
Just curious, what editor do you guys use?

**Comment by wiiaboo** [comment]
Sublime ocasionally and mostly VSCode.

**Comment by 1480c1** [comment]
Is the whole, ending the parenthesis one indention in with the same indentation as the things in between, a quirk of JB? Because since some of the things weren't consistent, it's been slightly annoying.
e.g. 
Line 1396-1404
``` batch
(
echo.echo -ne "\033]0;install base system\007"
echo.msysbasesystem="$(cat /etc/pac-base.pk | tr '\n\r' '  ')"
echo.[[ "$(uname)" = *6.1* ]] ^&^& nargs="-n 4"
echo.echo $msysbasesystem ^| xargs $nargs pacman -Sw --noconfirm --ask=20 --needed
echo.echo $msysbasesystem ^| xargs $nargs pacman -S --noconfirm --ask=20 --needed
echo.echo $msysbasesystem ^| xargs $nargs pacman -D --asexplicit
echo.sleep ^3
echo.exit
    )>%build%\pacman.sh
```
vs line 1447-1455
``` batch
(
    echo.echo -ne "\033]0;install 32 bit compiler\007"
    echo.mingw32compiler="$(cat /etc/pac-mingw.pk | sed 's;.*;mingw-w64-i686-&;g' | tr '\n\r' '  ')"
    echo.[[ "$(uname)" = *6.1* ]] ^&^& nargs="-n 4"
    echo.echo $mingw32compiler ^| xargs $nargs pacman -Sw --noconfirm --ask=20 --needed
    echo.echo $mingw32compiler ^| xargs $nargs pacman -S --noconfirm --ask=20 --needed
    echo.sleep ^3
    echo.exit
    )>%build%\mingw32.sh
```

**Comment by wiiaboo** [comment]
I think the second one's from me/SublimeText. I've always hated both kinds of indentation.

**Comment by wiiaboo** [comment]
I don't know what're the guidelines for batch code, choose whichever you want.
