### ISSUE TITLE
FR (experimental, low prio): JVET VCC builds now with MSYS/MinGW+GCC

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#990]
Fraunhofer just merged a [cmake-update](https://vcgit.hhi.fraunhofer.de/ksuehring/VVCSoftware_VTM/tree/cmake-update) patch, so building the future codec VVC = "Versatile Video Coding" (successor of HEVC) in an MSYS/MinGW environment with GCC is now supported good enough from the master branch to finish without errors.

Yet, the encoder software is still quite experimental (VTM = VVC Test Model), requires powerful hardware (e.g. at least SSE4 support, better AVX). And integration in ffmpeg won't happen at such an early stage (high risk of possibly changing bitstream specs), so if at all, you may only support it as separate encoder/decoder software.

Another disadvantage: Configuring an encoding session is very complex, using configuration files is highly recommended over a pure CLI parameter line; several samples are available in the source directory as auxiliary result of a checkout from [their repository](https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM).

_Note: text in {curly braces} means my personal suggestion. Brackets mean [A|B] alternatives._

The important stand-alone applications will be `{vvc-git}/bin/msys_makefiles/gcc-mingw-[7.3/x86|8.2/x86_64]/release/[En|De]coderApp.exe` to be redirected to `local[32|64]/bin-video` but a few more are built; for a future ffmpeg integration, `{vvc-git}/lib/msys_makefiles/gcc-mingw-[7.3/x86|8.2/x86_64]/release/lib*.a` may become important when a "final bitstream" is announced in a few .. years?!

The build sequence is pretty much the expectable one, which should be easily adaptable...

```
cd /build/{vvc-git}
mkdir build
cd build
cmake .. -G "MSYS Makefiles"
make
```

I don't mind postponing this feature request. Just to have some useful details reported already, which may be found when searching.

**Comment by wiiaboo** [comment]
They can't add install rules like sane people?

**Comment by wiiaboo** [comment]
Only installing the binaries because there's probably nothing using the libs or headers yet.

**Comment by LigH-de** [comment]
They even managed to leave the repo in a failed state. Teach them! :smirk:
