### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nickverlinden** [jb-alvarado/media-autobuild_suite#992]
Hi,

I'm trying to compile on vanilla windows 10 64bit in virtual machine, also tried 32 bit, but keep getting this error:

![image](https://user-images.githubusercontent.com/26145952/49824811-382fcd00-fd83-11e8-92f9-f70429901f6c.png)

Kind regards,
Nick

**Comment by nickverlinden** [comment]
In the ab-suite.make.log:

![image](https://user-images.githubusercontent.com/26145952/49824964-8cd34800-fd83-11e8-8a0b-056e004c2994.png)
![image](https://user-images.githubusercontent.com/26145952/49825007-ae343400-fd83-11e8-861e-6a70ac7a6370.png)

**Comment by wiiaboo** [comment]
Try again after running this in the mintty shortcut:
`pacman -S mingw-w64-x86_64-python2 --overwrite /mingw64`

And next time, don't bother posting screenshots, just copy-paste the green line like it says so.

**Comment by wiiaboo** [comment]
Try this: https://github.com/jb-alvarado/media-autobuild_suite/issues/958#issuecomment-439837029

**Comment by 1480c1** [comment]
Another alternative if that still doesn't work is to do `pacman-key -r EFD16019AE4FF531; pacman-key --lsign EFD16019AE4FF531` in order to manually download and sign the key locally as that is what I did to fix the problem.

**Comment by nickverlinden** [comment]
@wiiaboo Thanks, that worked! Building now...
