### ISSUE TITLE
mpv, build fails.

### ISSUE THREAD

**Issue by carlhen** [jb-alvarado/media-autobuild_suite#995]
┌ mpv git ........................................... [Recently updated]
├ Running bootstrap...
├ Running configure...
├ Running build...
Likely error:
<line>Displays current media-title, filename, or custom title</line> line
<line>Shows current cache fill status</line> line
<line>Shows current playback position timestamp</line> line
<line>Indicates current playback position and position of chapters</line> line
<line>Shows remaining playback time timestamp</line> line
<line>Displays selected track and amount of available tracks</line> line

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/media-autobuild_suite/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/skx-.zip
Copy and paste [logs.zip](https://0x0.st/skx-.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Try forcing a recompilation of FFmpeg, it seems like yours is broken.

**Comment by carlhen** [comment]
Ok, so i wiped the suite and downloaded a new one, but now i'm faced with a new error message from ffmpeg make. 
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error:
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/libaomenc.c:197:20: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 static av_cold int codecctl_int(AVCodecContext *avctx,
                    ^~~~~~~~~~~~
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/libaomenc.c: In function 'set_color_range':
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/libaomenc.c:294:26: error: storage size of 'aom_cr' isn't known
     enum aom_color_range aom_cr;
                          ^~~~~~
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/libaomenc.c:294:26: warning: unused variable 'aom_cr' [-Wunused-variable]
make: *** [/build/ffmpeg-git/ffbuild/common.mak:60: libavcodec/libaomenc.o] Error 1
make failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/skls.zip
Copy and paste [logs.zip](https://0x0.st/skls.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

PS. I just want to thank you for making such wonderful scripts. Thank you for your time. (Not ironically meant.)

**Comment by 1480c1** [comment]
I'm going to make a uneducated guess that your aom encoder/decoder is broken. Maybe try again? I compiled everything fine just now.

**Comment by 1480c1** [comment]
I re ran the compilation and got the same error, I'm right now re ruining it, but it may be possible it's an aom error rather than here.

**Comment by SmilingWolf** [comment]
Broken upstream: https://aomedia.googlesource.com/aom/+/4667aa1a373566e9c124afcd58c71731ab0d7377%5E%21/
Patch to at least make it compile succesfully:
```diff --git a/libavcodec/libaomenc.c b/libavcodec/libaomenc.c
index 09ef423ce1..6d1955f9cc 100644
--- a/libavcodec/libaomenc.c
+++ b/libavcodec/libaomenc.c
@@ -195,7 +195,7 @@ static av_cold void free_frame_list(struct FrameListData *list)
 }
 
 static av_cold int codecctl_int(AVCodecContext *avctx,
-                                enum aome_enc_control_id id, int val)
+                                aome_enc_control_id id, int val)
 {
     AOMContext *ctx = avctx->priv_data;
     char buf[80];
@@ -291,7 +291,7 @@ static int set_pix_fmt(AVCodecContext *avctx, aom_codec_caps_t codec_caps,
 
 static void set_color_range(AVCodecContext *avctx)
 {
-    enum aom_color_range aom_cr;
+    aom_color_range_t aom_cr;
     switch (avctx->color_range) {
     case AVCOL_RANGE_UNSPECIFIED:
     case AVCOL_RANGE_MPEG:       aom_cr = AOM_CR_STUDIO_RANGE; break;
```
Attached too: [ffmpeg_aom.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/2694225/ffmpeg_aom.zip)

Haven't tested encoding with the patched FFMpeg yet

**Comment by carlhen** [comment]
Doing a static build, with the patch, worked perfectly. Thank you.

**Comment by carlhen** [comment]
Should I close this issue or not? The problem
is that mpv won’t compile if you are doing a shared build.

**Comment by LigH-de** [comment]
Compilation passes without extra patch, aomedia fixed one part upstream, ffmpeg possibly the other half?

**Comment by SmilingWolf** [comment]
> 
> 
> Static compilation passes without extra patch, aomedia fixed one part upstream, ffmpeg possibly the other half?

Unfortunately aomedia didn't fix anything. Their proposed patch [upstream](https://aomedia-review.googlesource.com/c/aom/+/77241) might actually break FFmpeg AGAIN.
Somebody wrote a patch following [jamrial's suggestion](https://bugs.chromium.org/p/aomedia/issues/detail?id=2280#c1) and it was [merged in FFmpeg](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/aaf9171574791cfa6bc5dd2115a840968d7ca5dc) a few hours after the breakage.

**Comment by LigH-de** [comment]
Ah, well, I see activity in my aomedia tracker issue, but maybe misinterpreted that as success when it's actually still preparation... so we have to expect more turbulences in the progress of this development.

**Comment by wiiaboo** [comment]
The libaom issue is unrelated, please open another issue with it if it's not fixed in upstreams yet.
