### ISSUE TITLE
Prototype errors in libavcodec/libaomenc.c

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#997]
The development of aomedia probably broke API compatibility in libavcodec again; ffmpeg "only supports releases", according to a moderator in the ffmpeg IRC channel. I will notify the [aomedia tracker](https://bugs.chromium.org/p/aomedia/issues/detail?id=2280).

**Comment by SmilingWolf** [comment]
Fixed in FFmpeg: https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/aaf9171574791cfa6bc5dd2115a840968d7ca5dc
The way Google treats the API is pure BS though
