### ISSUE TITLE
Question, regarding gnutls git

### ISSUE THREAD

**Issue by ArcAngelRyse** [jb-alvarado/media-autobuild_suite#998]
So I'm in the middle of compiling and building the libraries but I'm curious its been at Running bootstrap for about 30mins or so, how long should that typically take? It shows no errors, at least no obvious ones.
![annotation 2018-12-19 212743](https://user-images.githubusercontent.com/34932364/50260678-0fd54d80-03d7-11e9-8038-42f73b7d628e.jpg)

**Comment by wiiaboo** [comment]
Depends on a lot of stuff: CPU, network, servers being down, disk types and speeds. If it runs for hours without any change, it's probably frozen, because Windows.

**Comment by Selur** [comment]
Running bootstrap sometimes takes ages,... just waited for ~30min and now it's at 'Running configure...' which also doesn't really use much CPU,... so leaving the script over night,...
